/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.leads.model.DetailDrive;
import com.mypage.leads.model.DetailDriveModel;
import com.mypage.leads.model.DetailDriveSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DetailDrive service. Represents a row in the &quot;DetailDrive&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DetailDriveModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DetailDriveImpl}.
 * </p>
 *
 * @author Gositus
 * @see DetailDriveImpl
 * @generated
 */
@JSON(strict = true)
public class DetailDriveModelImpl
	extends BaseModelImpl<DetailDrive> implements DetailDriveModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a detail drive model instance should use the <code>DetailDrive</code> interface instead.
	 */
	public static final String TABLE_NAME = "DetailDrive";

	public static final Object[][] TABLE_COLUMNS = {
		{"detailDriveId", Types.BIGINT}, {"leadsId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"vehicleCode", Types.VARCHAR}, {"VehicleManufacture", Types.VARCHAR},
		{"vehicleModel", Types.VARCHAR}, {"vehicleSubModel", Types.VARCHAR},
		{"vehicleBody", Types.VARCHAR}, {"manufactureYear", Types.INTEGER},
		{"manufactureAge", Types.INTEGER}, {"coverageType", Types.VARCHAR},
		{"vehicleType", Types.VARCHAR}, {"typeOfUse", Types.VARCHAR},
		{"vehicleInsured", Types.DOUBLE}, {"accessoriesInsured", Types.DOUBLE},
		{"sumInsured", Types.DOUBLE}, {"regionPlate", Types.VARCHAR},
		{"cc", Types.INTEGER}, {"make", Types.VARCHAR}, {"dpg", Types.VARCHAR},
		{"seatCapacity", Types.INTEGER}, {"startDate", Types.TIMESTAMP},
		{"expiredDate", Types.TIMESTAMP}, {"commercialOffers", Types.INTEGER},
		{"name", Types.VARCHAR}, {"birthPlace", Types.VARCHAR},
		{"dob", Types.TIMESTAMP}, {"nationality", Types.VARCHAR},
		{"idNumber", Types.VARCHAR}, {"passportNumber", Types.VARCHAR},
		{"kitasNumber", Types.VARCHAR}, {"mobilePhone", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"address2", Types.VARCHAR}, {"province", Types.VARCHAR},
		{"city", Types.VARCHAR}, {"policeNumber", Types.VARCHAR},
		{"chassisNumber", Types.VARCHAR}, {"engineNumber", Types.VARCHAR},
		{"policyNumber", Types.VARCHAR}, {"referenceNumber", Types.VARCHAR},
		{"policyStatus", Types.VARCHAR}, {"currency_", Types.VARCHAR},
		{"policyCost", Types.DOUBLE}, {"stampDuty", Types.DOUBLE},
		{"premium", Types.DOUBLE}, {"netPremium", Types.DOUBLE},
		{"discount", Types.INTEGER}, {"commission", Types.VARCHAR},
		{"leads", Types.BIGINT}, {"transactionId", Types.VARCHAR},
		{"bussinesModel", Types.VARCHAR}, {"channel", Types.VARCHAR},
		{"promoCode", Types.VARCHAR}, {"step1", Types.INTEGER},
		{"step2", Types.INTEGER}, {"step3", Types.INTEGER},
		{"dailyReportStatus", Types.INTEGER}, {"dailyReportFile", Types.BIGINT},
		{"dailyReportAgentStatus", Types.INTEGER},
		{"dailyReportAgentFile", Types.BIGINT}, {"utmSource", Types.VARCHAR},
		{"utmMedium", Types.VARCHAR}, {"utmCampaign", Types.VARCHAR},
		{"utmTerm", Types.VARCHAR}, {"utmContent", Types.VARCHAR},
		{"clickId", Types.VARCHAR}, {"managedBy", Types.BIGINT},
		{"agentCode", Types.VARCHAR}, {"subAgent", Types.BIGINT},
		{"marketingCode", Types.VARCHAR}, {"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("detailDriveId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leadsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("vehicleCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("VehicleManufacture", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleModel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleSubModel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleBody", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("manufactureYear", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("manufactureAge", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("coverageType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("typeOfUse", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleInsured", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("accessoriesInsured", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("sumInsured", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("regionPlate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cc", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("make", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dpg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("seatCapacity", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expiredDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commercialOffers", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthPlace", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dob", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nationality", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("passportNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kitasNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobilePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("province", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("policeNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("chassisNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("engineNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("policyNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("referenceNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("policyStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("currency_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("policyCost", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("stampDuty", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("premium", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("netPremium", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("discount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("commission", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leads", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("transactionId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bussinesModel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("channel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("promoCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("step1", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("step2", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("step3", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dailyReportStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dailyReportFile", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dailyReportAgentStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dailyReportAgentFile", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("utmSource", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmMedium", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmCampaign", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmTerm", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmContent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("clickId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("managedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("agentCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subAgent", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("marketingCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DetailDrive (detailDriveId LONG not null primary key,leadsId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,vehicleCode VARCHAR(75) null,VehicleManufacture VARCHAR(75) null,vehicleModel VARCHAR(75) null,vehicleSubModel VARCHAR(75) null,vehicleBody VARCHAR(75) null,manufactureYear INTEGER,manufactureAge INTEGER,coverageType VARCHAR(75) null,vehicleType VARCHAR(75) null,typeOfUse VARCHAR(75) null,vehicleInsured DOUBLE,accessoriesInsured DOUBLE,sumInsured DOUBLE,regionPlate VARCHAR(75) null,cc INTEGER,make VARCHAR(75) null,dpg VARCHAR(75) null,seatCapacity INTEGER,startDate DATE null,expiredDate DATE null,commercialOffers INTEGER,name VARCHAR(75) null,birthPlace VARCHAR(75) null,dob DATE null,nationality VARCHAR(75) null,idNumber VARCHAR(75) null,passportNumber VARCHAR(75) null,kitasNumber VARCHAR(75) null,mobilePhone VARCHAR(75) null,email VARCHAR(75) null,address VARCHAR(75) null,address2 VARCHAR(75) null,province VARCHAR(75) null,city VARCHAR(75) null,policeNumber VARCHAR(75) null,chassisNumber VARCHAR(75) null,engineNumber VARCHAR(75) null,policyNumber VARCHAR(75) null,referenceNumber VARCHAR(75) null,policyStatus VARCHAR(75) null,currency_ VARCHAR(75) null,policyCost DOUBLE,stampDuty DOUBLE,premium DOUBLE,netPremium DOUBLE,discount INTEGER,commission VARCHAR(75) null,leads LONG,transactionId VARCHAR(75) null,bussinesModel VARCHAR(75) null,channel VARCHAR(75) null,promoCode VARCHAR(75) null,step1 INTEGER,step2 INTEGER,step3 INTEGER,dailyReportStatus INTEGER,dailyReportFile LONG,dailyReportAgentStatus INTEGER,dailyReportAgentFile LONG,utmSource VARCHAR(75) null,utmMedium VARCHAR(75) null,utmCampaign VARCHAR(75) null,utmTerm VARCHAR(75) null,utmContent VARCHAR(75) null,clickId VARCHAR(75) null,managedBy LONG,agentCode VARCHAR(75) null,subAgent LONG,marketingCode VARCHAR(75) null,active_ INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table DetailDrive";

	public static final String ORDER_BY_JPQL =
		" ORDER BY detailDrive.detailDriveId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DetailDrive.detailDriveId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static DetailDrive toModel(DetailDriveSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DetailDrive model = new DetailDriveImpl();

		model.setDetailDriveId(soapModel.getDetailDriveId());
		model.setLeadsId(soapModel.getLeadsId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setVehicleCode(soapModel.getVehicleCode());
		model.setVehicleManufacture(soapModel.getVehicleManufacture());
		model.setVehicleModel(soapModel.getVehicleModel());
		model.setVehicleSubModel(soapModel.getVehicleSubModel());
		model.setVehicleBody(soapModel.getVehicleBody());
		model.setManufactureYear(soapModel.getManufactureYear());
		model.setManufactureAge(soapModel.getManufactureAge());
		model.setCoverageType(soapModel.getCoverageType());
		model.setVehicleType(soapModel.getVehicleType());
		model.setTypeOfUse(soapModel.getTypeOfUse());
		model.setVehicleInsured(soapModel.getVehicleInsured());
		model.setAccessoriesInsured(soapModel.getAccessoriesInsured());
		model.setSumInsured(soapModel.getSumInsured());
		model.setRegionPlate(soapModel.getRegionPlate());
		model.setCc(soapModel.getCc());
		model.setMake(soapModel.getMake());
		model.setDpg(soapModel.getDpg());
		model.setSeatCapacity(soapModel.getSeatCapacity());
		model.setStartDate(soapModel.getStartDate());
		model.setExpiredDate(soapModel.getExpiredDate());
		model.setCommercialOffers(soapModel.getCommercialOffers());
		model.setName(soapModel.getName());
		model.setBirthPlace(soapModel.getBirthPlace());
		model.setDob(soapModel.getDob());
		model.setNationality(soapModel.getNationality());
		model.setIdNumber(soapModel.getIdNumber());
		model.setPassportNumber(soapModel.getPassportNumber());
		model.setKitasNumber(soapModel.getKitasNumber());
		model.setMobilePhone(soapModel.getMobilePhone());
		model.setEmail(soapModel.getEmail());
		model.setAddress(soapModel.getAddress());
		model.setAddress2(soapModel.getAddress2());
		model.setProvince(soapModel.getProvince());
		model.setCity(soapModel.getCity());
		model.setPoliceNumber(soapModel.getPoliceNumber());
		model.setChassisNumber(soapModel.getChassisNumber());
		model.setEngineNumber(soapModel.getEngineNumber());
		model.setPolicyNumber(soapModel.getPolicyNumber());
		model.setReferenceNumber(soapModel.getReferenceNumber());
		model.setPolicyStatus(soapModel.getPolicyStatus());
		model.setCurrency(soapModel.getCurrency());
		model.setPolicyCost(soapModel.getPolicyCost());
		model.setStampDuty(soapModel.getStampDuty());
		model.setPremium(soapModel.getPremium());
		model.setNetPremium(soapModel.getNetPremium());
		model.setDiscount(soapModel.getDiscount());
		model.setCommission(soapModel.getCommission());
		model.setLeads(soapModel.getLeads());
		model.setTransactionId(soapModel.getTransactionId());
		model.setBussinesModel(soapModel.getBussinesModel());
		model.setChannel(soapModel.getChannel());
		model.setPromoCode(soapModel.getPromoCode());
		model.setStep1(soapModel.getStep1());
		model.setStep2(soapModel.getStep2());
		model.setStep3(soapModel.getStep3());
		model.setDailyReportStatus(soapModel.getDailyReportStatus());
		model.setDailyReportFile(soapModel.getDailyReportFile());
		model.setDailyReportAgentStatus(soapModel.getDailyReportAgentStatus());
		model.setDailyReportAgentFile(soapModel.getDailyReportAgentFile());
		model.setUtmSource(soapModel.getUtmSource());
		model.setUtmMedium(soapModel.getUtmMedium());
		model.setUtmCampaign(soapModel.getUtmCampaign());
		model.setUtmTerm(soapModel.getUtmTerm());
		model.setUtmContent(soapModel.getUtmContent());
		model.setClickId(soapModel.getClickId());
		model.setManagedBy(soapModel.getManagedBy());
		model.setAgentCode(soapModel.getAgentCode());
		model.setSubAgent(soapModel.getSubAgent());
		model.setMarketingCode(soapModel.getMarketingCode());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<DetailDrive> toModels(DetailDriveSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DetailDrive> models = new ArrayList<DetailDrive>(
			soapModels.length);

		for (DetailDriveSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DetailDriveModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _detailDriveId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDetailDriveId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _detailDriveId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DetailDrive.class;
	}

	@Override
	public String getModelClassName() {
		return DetailDrive.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DetailDrive, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DetailDrive, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailDrive, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DetailDrive)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DetailDrive, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DetailDrive, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DetailDrive)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DetailDrive, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DetailDrive, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DetailDrive, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DetailDrive, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DetailDrive, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DetailDrive, Object>>();
		Map<String, BiConsumer<DetailDrive, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DetailDrive, ?>>();

		attributeGetterFunctions.put(
			"detailDriveId", DetailDrive::getDetailDriveId);
		attributeSetterBiConsumers.put(
			"detailDriveId",
			(BiConsumer<DetailDrive, Long>)DetailDrive::setDetailDriveId);
		attributeGetterFunctions.put("leadsId", DetailDrive::getLeadsId);
		attributeSetterBiConsumers.put(
			"leadsId", (BiConsumer<DetailDrive, Long>)DetailDrive::setLeadsId);
		attributeGetterFunctions.put("groupId", DetailDrive::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<DetailDrive, Long>)DetailDrive::setGroupId);
		attributeGetterFunctions.put("companyId", DetailDrive::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DetailDrive, Long>)DetailDrive::setCompanyId);
		attributeGetterFunctions.put("userId", DetailDrive::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<DetailDrive, Long>)DetailDrive::setUserId);
		attributeGetterFunctions.put("userName", DetailDrive::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DetailDrive, String>)DetailDrive::setUserName);
		attributeGetterFunctions.put("createDate", DetailDrive::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DetailDrive, Date>)DetailDrive::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DetailDrive::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DetailDrive, Date>)DetailDrive::setModifiedDate);
		attributeGetterFunctions.put(
			"vehicleCode", DetailDrive::getVehicleCode);
		attributeSetterBiConsumers.put(
			"vehicleCode",
			(BiConsumer<DetailDrive, String>)DetailDrive::setVehicleCode);
		attributeGetterFunctions.put(
			"VehicleManufacture", DetailDrive::getVehicleManufacture);
		attributeSetterBiConsumers.put(
			"VehicleManufacture",
			(BiConsumer<DetailDrive, String>)
				DetailDrive::setVehicleManufacture);
		attributeGetterFunctions.put(
			"vehicleModel", DetailDrive::getVehicleModel);
		attributeSetterBiConsumers.put(
			"vehicleModel",
			(BiConsumer<DetailDrive, String>)DetailDrive::setVehicleModel);
		attributeGetterFunctions.put(
			"vehicleSubModel", DetailDrive::getVehicleSubModel);
		attributeSetterBiConsumers.put(
			"vehicleSubModel",
			(BiConsumer<DetailDrive, String>)DetailDrive::setVehicleSubModel);
		attributeGetterFunctions.put(
			"vehicleBody", DetailDrive::getVehicleBody);
		attributeSetterBiConsumers.put(
			"vehicleBody",
			(BiConsumer<DetailDrive, String>)DetailDrive::setVehicleBody);
		attributeGetterFunctions.put(
			"manufactureYear", DetailDrive::getManufactureYear);
		attributeSetterBiConsumers.put(
			"manufactureYear",
			(BiConsumer<DetailDrive, Integer>)DetailDrive::setManufactureYear);
		attributeGetterFunctions.put(
			"manufactureAge", DetailDrive::getManufactureAge);
		attributeSetterBiConsumers.put(
			"manufactureAge",
			(BiConsumer<DetailDrive, Integer>)DetailDrive::setManufactureAge);
		attributeGetterFunctions.put(
			"coverageType", DetailDrive::getCoverageType);
		attributeSetterBiConsumers.put(
			"coverageType",
			(BiConsumer<DetailDrive, String>)DetailDrive::setCoverageType);
		attributeGetterFunctions.put(
			"vehicleType", DetailDrive::getVehicleType);
		attributeSetterBiConsumers.put(
			"vehicleType",
			(BiConsumer<DetailDrive, String>)DetailDrive::setVehicleType);
		attributeGetterFunctions.put("typeOfUse", DetailDrive::getTypeOfUse);
		attributeSetterBiConsumers.put(
			"typeOfUse",
			(BiConsumer<DetailDrive, String>)DetailDrive::setTypeOfUse);
		attributeGetterFunctions.put(
			"vehicleInsured", DetailDrive::getVehicleInsured);
		attributeSetterBiConsumers.put(
			"vehicleInsured",
			(BiConsumer<DetailDrive, Double>)DetailDrive::setVehicleInsured);
		attributeGetterFunctions.put(
			"accessoriesInsured", DetailDrive::getAccessoriesInsured);
		attributeSetterBiConsumers.put(
			"accessoriesInsured",
			(BiConsumer<DetailDrive, Double>)
				DetailDrive::setAccessoriesInsured);
		attributeGetterFunctions.put("sumInsured", DetailDrive::getSumInsured);
		attributeSetterBiConsumers.put(
			"sumInsured",
			(BiConsumer<DetailDrive, Double>)DetailDrive::setSumInsured);
		attributeGetterFunctions.put(
			"regionPlate", DetailDrive::getRegionPlate);
		attributeSetterBiConsumers.put(
			"regionPlate",
			(BiConsumer<DetailDrive, String>)DetailDrive::setRegionPlate);
		attributeGetterFunctions.put("cc", DetailDrive::getCc);
		attributeSetterBiConsumers.put(
			"cc", (BiConsumer<DetailDrive, Integer>)DetailDrive::setCc);
		attributeGetterFunctions.put("make", DetailDrive::getMake);
		attributeSetterBiConsumers.put(
			"make", (BiConsumer<DetailDrive, String>)DetailDrive::setMake);
		attributeGetterFunctions.put("dpg", DetailDrive::getDpg);
		attributeSetterBiConsumers.put(
			"dpg", (BiConsumer<DetailDrive, String>)DetailDrive::setDpg);
		attributeGetterFunctions.put(
			"seatCapacity", DetailDrive::getSeatCapacity);
		attributeSetterBiConsumers.put(
			"seatCapacity",
			(BiConsumer<DetailDrive, Integer>)DetailDrive::setSeatCapacity);
		attributeGetterFunctions.put("startDate", DetailDrive::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<DetailDrive, Date>)DetailDrive::setStartDate);
		attributeGetterFunctions.put(
			"expiredDate", DetailDrive::getExpiredDate);
		attributeSetterBiConsumers.put(
			"expiredDate",
			(BiConsumer<DetailDrive, Date>)DetailDrive::setExpiredDate);
		attributeGetterFunctions.put(
			"commercialOffers", DetailDrive::getCommercialOffers);
		attributeSetterBiConsumers.put(
			"commercialOffers",
			(BiConsumer<DetailDrive, Integer>)DetailDrive::setCommercialOffers);
		attributeGetterFunctions.put("name", DetailDrive::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<DetailDrive, String>)DetailDrive::setName);
		attributeGetterFunctions.put("birthPlace", DetailDrive::getBirthPlace);
		attributeSetterBiConsumers.put(
			"birthPlace",
			(BiConsumer<DetailDrive, String>)DetailDrive::setBirthPlace);
		attributeGetterFunctions.put("dob", DetailDrive::getDob);
		attributeSetterBiConsumers.put(
			"dob", (BiConsumer<DetailDrive, Date>)DetailDrive::setDob);
		attributeGetterFunctions.put(
			"nationality", DetailDrive::getNationality);
		attributeSetterBiConsumers.put(
			"nationality",
			(BiConsumer<DetailDrive, String>)DetailDrive::setNationality);
		attributeGetterFunctions.put("idNumber", DetailDrive::getIdNumber);
		attributeSetterBiConsumers.put(
			"idNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setIdNumber);
		attributeGetterFunctions.put(
			"passportNumber", DetailDrive::getPassportNumber);
		attributeSetterBiConsumers.put(
			"passportNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setPassportNumber);
		attributeGetterFunctions.put(
			"kitasNumber", DetailDrive::getKitasNumber);
		attributeSetterBiConsumers.put(
			"kitasNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setKitasNumber);
		attributeGetterFunctions.put(
			"mobilePhone", DetailDrive::getMobilePhone);
		attributeSetterBiConsumers.put(
			"mobilePhone",
			(BiConsumer<DetailDrive, String>)DetailDrive::setMobilePhone);
		attributeGetterFunctions.put("email", DetailDrive::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<DetailDrive, String>)DetailDrive::setEmail);
		attributeGetterFunctions.put("address", DetailDrive::getAddress);
		attributeSetterBiConsumers.put(
			"address",
			(BiConsumer<DetailDrive, String>)DetailDrive::setAddress);
		attributeGetterFunctions.put("address2", DetailDrive::getAddress2);
		attributeSetterBiConsumers.put(
			"address2",
			(BiConsumer<DetailDrive, String>)DetailDrive::setAddress2);
		attributeGetterFunctions.put("province", DetailDrive::getProvince);
		attributeSetterBiConsumers.put(
			"province",
			(BiConsumer<DetailDrive, String>)DetailDrive::setProvince);
		attributeGetterFunctions.put("city", DetailDrive::getCity);
		attributeSetterBiConsumers.put(
			"city", (BiConsumer<DetailDrive, String>)DetailDrive::setCity);
		attributeGetterFunctions.put(
			"policeNumber", DetailDrive::getPoliceNumber);
		attributeSetterBiConsumers.put(
			"policeNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setPoliceNumber);
		attributeGetterFunctions.put(
			"chassisNumber", DetailDrive::getChassisNumber);
		attributeSetterBiConsumers.put(
			"chassisNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setChassisNumber);
		attributeGetterFunctions.put(
			"engineNumber", DetailDrive::getEngineNumber);
		attributeSetterBiConsumers.put(
			"engineNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setEngineNumber);
		attributeGetterFunctions.put(
			"policyNumber", DetailDrive::getPolicyNumber);
		attributeSetterBiConsumers.put(
			"policyNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setPolicyNumber);
		attributeGetterFunctions.put(
			"referenceNumber", DetailDrive::getReferenceNumber);
		attributeSetterBiConsumers.put(
			"referenceNumber",
			(BiConsumer<DetailDrive, String>)DetailDrive::setReferenceNumber);
		attributeGetterFunctions.put(
			"policyStatus", DetailDrive::getPolicyStatus);
		attributeSetterBiConsumers.put(
			"policyStatus",
			(BiConsumer<DetailDrive, String>)DetailDrive::setPolicyStatus);
		attributeGetterFunctions.put("currency", DetailDrive::getCurrency);
		attributeSetterBiConsumers.put(
			"currency",
			(BiConsumer<DetailDrive, String>)DetailDrive::setCurrency);
		attributeGetterFunctions.put("policyCost", DetailDrive::getPolicyCost);
		attributeSetterBiConsumers.put(
			"policyCost",
			(BiConsumer<DetailDrive, Double>)DetailDrive::setPolicyCost);
		attributeGetterFunctions.put("stampDuty", DetailDrive::getStampDuty);
		attributeSetterBiConsumers.put(
			"stampDuty",
			(BiConsumer<DetailDrive, Double>)DetailDrive::setStampDuty);
		attributeGetterFunctions.put("premium", DetailDrive::getPremium);
		attributeSetterBiConsumers.put(
			"premium",
			(BiConsumer<DetailDrive, Double>)DetailDrive::setPremium);
		attributeGetterFunctions.put("netPremium", DetailDrive::getNetPremium);
		attributeSetterBiConsumers.put(
			"netPremium",
			(BiConsumer<DetailDrive, Double>)DetailDrive::setNetPremium);
		attributeGetterFunctions.put("discount", DetailDrive::getDiscount);
		attributeSetterBiConsumers.put(
			"discount",
			(BiConsumer<DetailDrive, Integer>)DetailDrive::setDiscount);
		attributeGetterFunctions.put("commission", DetailDrive::getCommission);
		attributeSetterBiConsumers.put(
			"commission",
			(BiConsumer<DetailDrive, String>)DetailDrive::setCommission);
		attributeGetterFunctions.put("leads", DetailDrive::getLeads);
		attributeSetterBiConsumers.put(
			"leads", (BiConsumer<DetailDrive, Long>)DetailDrive::setLeads);
		attributeGetterFunctions.put(
			"transactionId", DetailDrive::getTransactionId);
		attributeSetterBiConsumers.put(
			"transactionId",
			(BiConsumer<DetailDrive, String>)DetailDrive::setTransactionId);
		attributeGetterFunctions.put(
			"bussinesModel", DetailDrive::getBussinesModel);
		attributeSetterBiConsumers.put(
			"bussinesModel",
			(BiConsumer<DetailDrive, String>)DetailDrive::setBussinesModel);
		attributeGetterFunctions.put("channel", DetailDrive::getChannel);
		attributeSetterBiConsumers.put(
			"channel",
			(BiConsumer<DetailDrive, String>)DetailDrive::setChannel);
		attributeGetterFunctions.put("promoCode", DetailDrive::getPromoCode);
		attributeSetterBiConsumers.put(
			"promoCode",
			(BiConsumer<DetailDrive, String>)DetailDrive::setPromoCode);
		attributeGetterFunctions.put("step1", DetailDrive::getStep1);
		attributeSetterBiConsumers.put(
			"step1", (BiConsumer<DetailDrive, Integer>)DetailDrive::setStep1);
		attributeGetterFunctions.put("step2", DetailDrive::getStep2);
		attributeSetterBiConsumers.put(
			"step2", (BiConsumer<DetailDrive, Integer>)DetailDrive::setStep2);
		attributeGetterFunctions.put("step3", DetailDrive::getStep3);
		attributeSetterBiConsumers.put(
			"step3", (BiConsumer<DetailDrive, Integer>)DetailDrive::setStep3);
		attributeGetterFunctions.put(
			"dailyReportStatus", DetailDrive::getDailyReportStatus);
		attributeSetterBiConsumers.put(
			"dailyReportStatus",
			(BiConsumer<DetailDrive, Integer>)
				DetailDrive::setDailyReportStatus);
		attributeGetterFunctions.put(
			"dailyReportFile", DetailDrive::getDailyReportFile);
		attributeSetterBiConsumers.put(
			"dailyReportFile",
			(BiConsumer<DetailDrive, Long>)DetailDrive::setDailyReportFile);
		attributeGetterFunctions.put(
			"dailyReportAgentStatus", DetailDrive::getDailyReportAgentStatus);
		attributeSetterBiConsumers.put(
			"dailyReportAgentStatus",
			(BiConsumer<DetailDrive, Integer>)
				DetailDrive::setDailyReportAgentStatus);
		attributeGetterFunctions.put(
			"dailyReportAgentFile", DetailDrive::getDailyReportAgentFile);
		attributeSetterBiConsumers.put(
			"dailyReportAgentFile",
			(BiConsumer<DetailDrive, Long>)
				DetailDrive::setDailyReportAgentFile);
		attributeGetterFunctions.put("utmSource", DetailDrive::getUtmSource);
		attributeSetterBiConsumers.put(
			"utmSource",
			(BiConsumer<DetailDrive, String>)DetailDrive::setUtmSource);
		attributeGetterFunctions.put("utmMedium", DetailDrive::getUtmMedium);
		attributeSetterBiConsumers.put(
			"utmMedium",
			(BiConsumer<DetailDrive, String>)DetailDrive::setUtmMedium);
		attributeGetterFunctions.put(
			"utmCampaign", DetailDrive::getUtmCampaign);
		attributeSetterBiConsumers.put(
			"utmCampaign",
			(BiConsumer<DetailDrive, String>)DetailDrive::setUtmCampaign);
		attributeGetterFunctions.put("utmTerm", DetailDrive::getUtmTerm);
		attributeSetterBiConsumers.put(
			"utmTerm",
			(BiConsumer<DetailDrive, String>)DetailDrive::setUtmTerm);
		attributeGetterFunctions.put("utmContent", DetailDrive::getUtmContent);
		attributeSetterBiConsumers.put(
			"utmContent",
			(BiConsumer<DetailDrive, String>)DetailDrive::setUtmContent);
		attributeGetterFunctions.put("clickId", DetailDrive::getClickId);
		attributeSetterBiConsumers.put(
			"clickId",
			(BiConsumer<DetailDrive, String>)DetailDrive::setClickId);
		attributeGetterFunctions.put("managedBy", DetailDrive::getManagedBy);
		attributeSetterBiConsumers.put(
			"managedBy",
			(BiConsumer<DetailDrive, Long>)DetailDrive::setManagedBy);
		attributeGetterFunctions.put("agentCode", DetailDrive::getAgentCode);
		attributeSetterBiConsumers.put(
			"agentCode",
			(BiConsumer<DetailDrive, String>)DetailDrive::setAgentCode);
		attributeGetterFunctions.put("subAgent", DetailDrive::getSubAgent);
		attributeSetterBiConsumers.put(
			"subAgent",
			(BiConsumer<DetailDrive, Long>)DetailDrive::setSubAgent);
		attributeGetterFunctions.put(
			"marketingCode", DetailDrive::getMarketingCode);
		attributeSetterBiConsumers.put(
			"marketingCode",
			(BiConsumer<DetailDrive, String>)DetailDrive::setMarketingCode);
		attributeGetterFunctions.put("active", DetailDrive::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<DetailDrive, Integer>)DetailDrive::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getDetailDriveId() {
		return _detailDriveId;
	}

	@Override
	public void setDetailDriveId(long detailDriveId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_detailDriveId = detailDriveId;
	}

	@JSON
	@Override
	public long getLeadsId() {
		return _leadsId;
	}

	@Override
	public void setLeadsId(long leadsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leadsId = leadsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeadsId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("leadsId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getVehicleCode() {
		if (_vehicleCode == null) {
			return "";
		}
		else {
			return _vehicleCode;
		}
	}

	@Override
	public void setVehicleCode(String vehicleCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleCode = vehicleCode;
	}

	@JSON
	@Override
	public String getVehicleManufacture() {
		if (_VehicleManufacture == null) {
			return "";
		}
		else {
			return _VehicleManufacture;
		}
	}

	@Override
	public void setVehicleManufacture(String VehicleManufacture) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VehicleManufacture = VehicleManufacture;
	}

	@JSON
	@Override
	public String getVehicleModel() {
		if (_vehicleModel == null) {
			return "";
		}
		else {
			return _vehicleModel;
		}
	}

	@Override
	public void setVehicleModel(String vehicleModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleModel = vehicleModel;
	}

	@JSON
	@Override
	public String getVehicleSubModel() {
		if (_vehicleSubModel == null) {
			return "";
		}
		else {
			return _vehicleSubModel;
		}
	}

	@Override
	public void setVehicleSubModel(String vehicleSubModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleSubModel = vehicleSubModel;
	}

	@JSON
	@Override
	public String getVehicleBody() {
		if (_vehicleBody == null) {
			return "";
		}
		else {
			return _vehicleBody;
		}
	}

	@Override
	public void setVehicleBody(String vehicleBody) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleBody = vehicleBody;
	}

	@JSON
	@Override
	public int getManufactureYear() {
		return _manufactureYear;
	}

	@Override
	public void setManufactureYear(int manufactureYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_manufactureYear = manufactureYear;
	}

	@JSON
	@Override
	public int getManufactureAge() {
		return _manufactureAge;
	}

	@Override
	public void setManufactureAge(int manufactureAge) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_manufactureAge = manufactureAge;
	}

	@JSON
	@Override
	public String getCoverageType() {
		if (_coverageType == null) {
			return "";
		}
		else {
			return _coverageType;
		}
	}

	@Override
	public void setCoverageType(String coverageType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_coverageType = coverageType;
	}

	@JSON
	@Override
	public String getVehicleType() {
		if (_vehicleType == null) {
			return "";
		}
		else {
			return _vehicleType;
		}
	}

	@Override
	public void setVehicleType(String vehicleType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleType = vehicleType;
	}

	@JSON
	@Override
	public String getTypeOfUse() {
		if (_typeOfUse == null) {
			return "";
		}
		else {
			return _typeOfUse;
		}
	}

	@Override
	public void setTypeOfUse(String typeOfUse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeOfUse = typeOfUse;
	}

	@JSON
	@Override
	public double getVehicleInsured() {
		return _vehicleInsured;
	}

	@Override
	public void setVehicleInsured(double vehicleInsured) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleInsured = vehicleInsured;
	}

	@JSON
	@Override
	public double getAccessoriesInsured() {
		return _accessoriesInsured;
	}

	@Override
	public void setAccessoriesInsured(double accessoriesInsured) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accessoriesInsured = accessoriesInsured;
	}

	@JSON
	@Override
	public double getSumInsured() {
		return _sumInsured;
	}

	@Override
	public void setSumInsured(double sumInsured) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sumInsured = sumInsured;
	}

	@JSON
	@Override
	public String getRegionPlate() {
		if (_regionPlate == null) {
			return "";
		}
		else {
			return _regionPlate;
		}
	}

	@Override
	public void setRegionPlate(String regionPlate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_regionPlate = regionPlate;
	}

	@JSON
	@Override
	public int getCc() {
		return _cc;
	}

	@Override
	public void setCc(int cc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cc = cc;
	}

	@JSON
	@Override
	public String getMake() {
		if (_make == null) {
			return "";
		}
		else {
			return _make;
		}
	}

	@Override
	public void setMake(String make) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_make = make;
	}

	@JSON
	@Override
	public String getDpg() {
		if (_dpg == null) {
			return "";
		}
		else {
			return _dpg;
		}
	}

	@Override
	public void setDpg(String dpg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dpg = dpg;
	}

	@JSON
	@Override
	public int getSeatCapacity() {
		return _seatCapacity;
	}

	@Override
	public void setSeatCapacity(int seatCapacity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seatCapacity = seatCapacity;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getExpiredDate() {
		return _expiredDate;
	}

	@Override
	public void setExpiredDate(Date expiredDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expiredDate = expiredDate;
	}

	@JSON
	@Override
	public int getCommercialOffers() {
		return _commercialOffers;
	}

	@Override
	public void setCommercialOffers(int commercialOffers) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commercialOffers = commercialOffers;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getBirthPlace() {
		if (_birthPlace == null) {
			return "";
		}
		else {
			return _birthPlace;
		}
	}

	@Override
	public void setBirthPlace(String birthPlace) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthPlace = birthPlace;
	}

	@JSON
	@Override
	public Date getDob() {
		return _dob;
	}

	@Override
	public void setDob(Date dob) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dob = dob;
	}

	@JSON
	@Override
	public String getNationality() {
		if (_nationality == null) {
			return "";
		}
		else {
			return _nationality;
		}
	}

	@Override
	public void setNationality(String nationality) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nationality = nationality;
	}

	@JSON
	@Override
	public String getIdNumber() {
		if (_idNumber == null) {
			return "";
		}
		else {
			return _idNumber;
		}
	}

	@Override
	public void setIdNumber(String idNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idNumber = idNumber;
	}

	@JSON
	@Override
	public String getPassportNumber() {
		if (_passportNumber == null) {
			return "";
		}
		else {
			return _passportNumber;
		}
	}

	@Override
	public void setPassportNumber(String passportNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_passportNumber = passportNumber;
	}

	@JSON
	@Override
	public String getKitasNumber() {
		if (_kitasNumber == null) {
			return "";
		}
		else {
			return _kitasNumber;
		}
	}

	@Override
	public void setKitasNumber(String kitasNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kitasNumber = kitasNumber;
	}

	@JSON
	@Override
	public String getMobilePhone() {
		if (_mobilePhone == null) {
			return "";
		}
		else {
			return _mobilePhone;
		}
	}

	@Override
	public void setMobilePhone(String mobilePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobilePhone = mobilePhone;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public String getAddress2() {
		if (_address2 == null) {
			return "";
		}
		else {
			return _address2;
		}
	}

	@Override
	public void setAddress2(String address2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address2 = address2;
	}

	@JSON
	@Override
	public String getProvince() {
		if (_province == null) {
			return "";
		}
		else {
			return _province;
		}
	}

	@Override
	public void setProvince(String province) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_province = province;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@JSON
	@Override
	public String getPoliceNumber() {
		if (_policeNumber == null) {
			return "";
		}
		else {
			return _policeNumber;
		}
	}

	@Override
	public void setPoliceNumber(String policeNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policeNumber = policeNumber;
	}

	@JSON
	@Override
	public String getChassisNumber() {
		if (_chassisNumber == null) {
			return "";
		}
		else {
			return _chassisNumber;
		}
	}

	@Override
	public void setChassisNumber(String chassisNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chassisNumber = chassisNumber;
	}

	@JSON
	@Override
	public String getEngineNumber() {
		if (_engineNumber == null) {
			return "";
		}
		else {
			return _engineNumber;
		}
	}

	@Override
	public void setEngineNumber(String engineNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_engineNumber = engineNumber;
	}

	@JSON
	@Override
	public String getPolicyNumber() {
		if (_policyNumber == null) {
			return "";
		}
		else {
			return _policyNumber;
		}
	}

	@Override
	public void setPolicyNumber(String policyNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyNumber = policyNumber;
	}

	@JSON
	@Override
	public String getReferenceNumber() {
		if (_referenceNumber == null) {
			return "";
		}
		else {
			return _referenceNumber;
		}
	}

	@Override
	public void setReferenceNumber(String referenceNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_referenceNumber = referenceNumber;
	}

	@JSON
	@Override
	public String getPolicyStatus() {
		if (_policyStatus == null) {
			return "";
		}
		else {
			return _policyStatus;
		}
	}

	@Override
	public void setPolicyStatus(String policyStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyStatus = policyStatus;
	}

	@JSON
	@Override
	public String getCurrency() {
		if (_currency == null) {
			return "";
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currency = currency;
	}

	@JSON
	@Override
	public double getPolicyCost() {
		return _policyCost;
	}

	@Override
	public void setPolicyCost(double policyCost) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyCost = policyCost;
	}

	@JSON
	@Override
	public double getStampDuty() {
		return _stampDuty;
	}

	@Override
	public void setStampDuty(double stampDuty) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stampDuty = stampDuty;
	}

	@JSON
	@Override
	public double getPremium() {
		return _premium;
	}

	@Override
	public void setPremium(double premium) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_premium = premium;
	}

	@JSON
	@Override
	public double getNetPremium() {
		return _netPremium;
	}

	@Override
	public void setNetPremium(double netPremium) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_netPremium = netPremium;
	}

	@JSON
	@Override
	public int getDiscount() {
		return _discount;
	}

	@Override
	public void setDiscount(int discount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_discount = discount;
	}

	@JSON
	@Override
	public String getCommission() {
		if (_commission == null) {
			return "";
		}
		else {
			return _commission;
		}
	}

	@Override
	public void setCommission(String commission) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commission = commission;
	}

	@JSON
	@Override
	public long getLeads() {
		return _leads;
	}

	@Override
	public void setLeads(long leads) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leads = leads;
	}

	@JSON
	@Override
	public String getTransactionId() {
		if (_transactionId == null) {
			return "";
		}
		else {
			return _transactionId;
		}
	}

	@Override
	public void setTransactionId(String transactionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transactionId = transactionId;
	}

	@JSON
	@Override
	public String getBussinesModel() {
		if (_bussinesModel == null) {
			return "";
		}
		else {
			return _bussinesModel;
		}
	}

	@Override
	public void setBussinesModel(String bussinesModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bussinesModel = bussinesModel;
	}

	@JSON
	@Override
	public String getChannel() {
		if (_channel == null) {
			return "";
		}
		else {
			return _channel;
		}
	}

	@Override
	public void setChannel(String channel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channel = channel;
	}

	@JSON
	@Override
	public String getPromoCode() {
		if (_promoCode == null) {
			return "";
		}
		else {
			return _promoCode;
		}
	}

	@Override
	public void setPromoCode(String promoCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promoCode = promoCode;
	}

	@JSON
	@Override
	public int getStep1() {
		return _step1;
	}

	@Override
	public void setStep1(int step1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_step1 = step1;
	}

	@JSON
	@Override
	public int getStep2() {
		return _step2;
	}

	@Override
	public void setStep2(int step2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_step2 = step2;
	}

	@JSON
	@Override
	public int getStep3() {
		return _step3;
	}

	@Override
	public void setStep3(int step3) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_step3 = step3;
	}

	@JSON
	@Override
	public int getDailyReportStatus() {
		return _dailyReportStatus;
	}

	@Override
	public void setDailyReportStatus(int dailyReportStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dailyReportStatus = dailyReportStatus;
	}

	@JSON
	@Override
	public long getDailyReportFile() {
		return _dailyReportFile;
	}

	@Override
	public void setDailyReportFile(long dailyReportFile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dailyReportFile = dailyReportFile;
	}

	@JSON
	@Override
	public int getDailyReportAgentStatus() {
		return _dailyReportAgentStatus;
	}

	@Override
	public void setDailyReportAgentStatus(int dailyReportAgentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dailyReportAgentStatus = dailyReportAgentStatus;
	}

	@JSON
	@Override
	public long getDailyReportAgentFile() {
		return _dailyReportAgentFile;
	}

	@Override
	public void setDailyReportAgentFile(long dailyReportAgentFile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dailyReportAgentFile = dailyReportAgentFile;
	}

	@JSON
	@Override
	public String getUtmSource() {
		if (_utmSource == null) {
			return "";
		}
		else {
			return _utmSource;
		}
	}

	@Override
	public void setUtmSource(String utmSource) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmSource = utmSource;
	}

	@JSON
	@Override
	public String getUtmMedium() {
		if (_utmMedium == null) {
			return "";
		}
		else {
			return _utmMedium;
		}
	}

	@Override
	public void setUtmMedium(String utmMedium) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmMedium = utmMedium;
	}

	@JSON
	@Override
	public String getUtmCampaign() {
		if (_utmCampaign == null) {
			return "";
		}
		else {
			return _utmCampaign;
		}
	}

	@Override
	public void setUtmCampaign(String utmCampaign) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmCampaign = utmCampaign;
	}

	@JSON
	@Override
	public String getUtmTerm() {
		if (_utmTerm == null) {
			return "";
		}
		else {
			return _utmTerm;
		}
	}

	@Override
	public void setUtmTerm(String utmTerm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmTerm = utmTerm;
	}

	@JSON
	@Override
	public String getUtmContent() {
		if (_utmContent == null) {
			return "";
		}
		else {
			return _utmContent;
		}
	}

	@Override
	public void setUtmContent(String utmContent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmContent = utmContent;
	}

	@JSON
	@Override
	public String getClickId() {
		if (_clickId == null) {
			return "";
		}
		else {
			return _clickId;
		}
	}

	@Override
	public void setClickId(String clickId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_clickId = clickId;
	}

	@JSON
	@Override
	public long getManagedBy() {
		return _managedBy;
	}

	@Override
	public void setManagedBy(long managedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managedBy = managedBy;
	}

	@JSON
	@Override
	public String getAgentCode() {
		if (_agentCode == null) {
			return "";
		}
		else {
			return _agentCode;
		}
	}

	@Override
	public void setAgentCode(String agentCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agentCode = agentCode;
	}

	@JSON
	@Override
	public long getSubAgent() {
		return _subAgent;
	}

	@Override
	public void setSubAgent(long subAgent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subAgent = subAgent;
	}

	@JSON
	@Override
	public String getMarketingCode() {
		if (_marketingCode == null) {
			return "";
		}
		else {
			return _marketingCode;
		}
	}

	@Override
	public void setMarketingCode(String marketingCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_marketingCode = marketingCode;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DetailDrive.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DetailDrive toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DetailDrive>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DetailDriveImpl detailDriveImpl = new DetailDriveImpl();

		detailDriveImpl.setDetailDriveId(getDetailDriveId());
		detailDriveImpl.setLeadsId(getLeadsId());
		detailDriveImpl.setGroupId(getGroupId());
		detailDriveImpl.setCompanyId(getCompanyId());
		detailDriveImpl.setUserId(getUserId());
		detailDriveImpl.setUserName(getUserName());
		detailDriveImpl.setCreateDate(getCreateDate());
		detailDriveImpl.setModifiedDate(getModifiedDate());
		detailDriveImpl.setVehicleCode(getVehicleCode());
		detailDriveImpl.setVehicleManufacture(getVehicleManufacture());
		detailDriveImpl.setVehicleModel(getVehicleModel());
		detailDriveImpl.setVehicleSubModel(getVehicleSubModel());
		detailDriveImpl.setVehicleBody(getVehicleBody());
		detailDriveImpl.setManufactureYear(getManufactureYear());
		detailDriveImpl.setManufactureAge(getManufactureAge());
		detailDriveImpl.setCoverageType(getCoverageType());
		detailDriveImpl.setVehicleType(getVehicleType());
		detailDriveImpl.setTypeOfUse(getTypeOfUse());
		detailDriveImpl.setVehicleInsured(getVehicleInsured());
		detailDriveImpl.setAccessoriesInsured(getAccessoriesInsured());
		detailDriveImpl.setSumInsured(getSumInsured());
		detailDriveImpl.setRegionPlate(getRegionPlate());
		detailDriveImpl.setCc(getCc());
		detailDriveImpl.setMake(getMake());
		detailDriveImpl.setDpg(getDpg());
		detailDriveImpl.setSeatCapacity(getSeatCapacity());
		detailDriveImpl.setStartDate(getStartDate());
		detailDriveImpl.setExpiredDate(getExpiredDate());
		detailDriveImpl.setCommercialOffers(getCommercialOffers());
		detailDriveImpl.setName(getName());
		detailDriveImpl.setBirthPlace(getBirthPlace());
		detailDriveImpl.setDob(getDob());
		detailDriveImpl.setNationality(getNationality());
		detailDriveImpl.setIdNumber(getIdNumber());
		detailDriveImpl.setPassportNumber(getPassportNumber());
		detailDriveImpl.setKitasNumber(getKitasNumber());
		detailDriveImpl.setMobilePhone(getMobilePhone());
		detailDriveImpl.setEmail(getEmail());
		detailDriveImpl.setAddress(getAddress());
		detailDriveImpl.setAddress2(getAddress2());
		detailDriveImpl.setProvince(getProvince());
		detailDriveImpl.setCity(getCity());
		detailDriveImpl.setPoliceNumber(getPoliceNumber());
		detailDriveImpl.setChassisNumber(getChassisNumber());
		detailDriveImpl.setEngineNumber(getEngineNumber());
		detailDriveImpl.setPolicyNumber(getPolicyNumber());
		detailDriveImpl.setReferenceNumber(getReferenceNumber());
		detailDriveImpl.setPolicyStatus(getPolicyStatus());
		detailDriveImpl.setCurrency(getCurrency());
		detailDriveImpl.setPolicyCost(getPolicyCost());
		detailDriveImpl.setStampDuty(getStampDuty());
		detailDriveImpl.setPremium(getPremium());
		detailDriveImpl.setNetPremium(getNetPremium());
		detailDriveImpl.setDiscount(getDiscount());
		detailDriveImpl.setCommission(getCommission());
		detailDriveImpl.setLeads(getLeads());
		detailDriveImpl.setTransactionId(getTransactionId());
		detailDriveImpl.setBussinesModel(getBussinesModel());
		detailDriveImpl.setChannel(getChannel());
		detailDriveImpl.setPromoCode(getPromoCode());
		detailDriveImpl.setStep1(getStep1());
		detailDriveImpl.setStep2(getStep2());
		detailDriveImpl.setStep3(getStep3());
		detailDriveImpl.setDailyReportStatus(getDailyReportStatus());
		detailDriveImpl.setDailyReportFile(getDailyReportFile());
		detailDriveImpl.setDailyReportAgentStatus(getDailyReportAgentStatus());
		detailDriveImpl.setDailyReportAgentFile(getDailyReportAgentFile());
		detailDriveImpl.setUtmSource(getUtmSource());
		detailDriveImpl.setUtmMedium(getUtmMedium());
		detailDriveImpl.setUtmCampaign(getUtmCampaign());
		detailDriveImpl.setUtmTerm(getUtmTerm());
		detailDriveImpl.setUtmContent(getUtmContent());
		detailDriveImpl.setClickId(getClickId());
		detailDriveImpl.setManagedBy(getManagedBy());
		detailDriveImpl.setAgentCode(getAgentCode());
		detailDriveImpl.setSubAgent(getSubAgent());
		detailDriveImpl.setMarketingCode(getMarketingCode());
		detailDriveImpl.setActive(getActive());

		detailDriveImpl.resetOriginalValues();

		return detailDriveImpl;
	}

	@Override
	public int compareTo(DetailDrive detailDrive) {
		long primaryKey = detailDrive.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DetailDrive)) {
			return false;
		}

		DetailDrive detailDrive = (DetailDrive)object;

		long primaryKey = detailDrive.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;
	}

	@Override
	public CacheModel<DetailDrive> toCacheModel() {
		DetailDriveCacheModel detailDriveCacheModel =
			new DetailDriveCacheModel();

		detailDriveCacheModel.detailDriveId = getDetailDriveId();

		detailDriveCacheModel.leadsId = getLeadsId();

		detailDriveCacheModel.groupId = getGroupId();

		detailDriveCacheModel.companyId = getCompanyId();

		detailDriveCacheModel.userId = getUserId();

		detailDriveCacheModel.userName = getUserName();

		String userName = detailDriveCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			detailDriveCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			detailDriveCacheModel.createDate = createDate.getTime();
		}
		else {
			detailDriveCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			detailDriveCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			detailDriveCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		detailDriveCacheModel.vehicleCode = getVehicleCode();

		String vehicleCode = detailDriveCacheModel.vehicleCode;

		if ((vehicleCode != null) && (vehicleCode.length() == 0)) {
			detailDriveCacheModel.vehicleCode = null;
		}

		detailDriveCacheModel.VehicleManufacture = getVehicleManufacture();

		String VehicleManufacture = detailDriveCacheModel.VehicleManufacture;

		if ((VehicleManufacture != null) &&
			(VehicleManufacture.length() == 0)) {

			detailDriveCacheModel.VehicleManufacture = null;
		}

		detailDriveCacheModel.vehicleModel = getVehicleModel();

		String vehicleModel = detailDriveCacheModel.vehicleModel;

		if ((vehicleModel != null) && (vehicleModel.length() == 0)) {
			detailDriveCacheModel.vehicleModel = null;
		}

		detailDriveCacheModel.vehicleSubModel = getVehicleSubModel();

		String vehicleSubModel = detailDriveCacheModel.vehicleSubModel;

		if ((vehicleSubModel != null) && (vehicleSubModel.length() == 0)) {
			detailDriveCacheModel.vehicleSubModel = null;
		}

		detailDriveCacheModel.vehicleBody = getVehicleBody();

		String vehicleBody = detailDriveCacheModel.vehicleBody;

		if ((vehicleBody != null) && (vehicleBody.length() == 0)) {
			detailDriveCacheModel.vehicleBody = null;
		}

		detailDriveCacheModel.manufactureYear = getManufactureYear();

		detailDriveCacheModel.manufactureAge = getManufactureAge();

		detailDriveCacheModel.coverageType = getCoverageType();

		String coverageType = detailDriveCacheModel.coverageType;

		if ((coverageType != null) && (coverageType.length() == 0)) {
			detailDriveCacheModel.coverageType = null;
		}

		detailDriveCacheModel.vehicleType = getVehicleType();

		String vehicleType = detailDriveCacheModel.vehicleType;

		if ((vehicleType != null) && (vehicleType.length() == 0)) {
			detailDriveCacheModel.vehicleType = null;
		}

		detailDriveCacheModel.typeOfUse = getTypeOfUse();

		String typeOfUse = detailDriveCacheModel.typeOfUse;

		if ((typeOfUse != null) && (typeOfUse.length() == 0)) {
			detailDriveCacheModel.typeOfUse = null;
		}

		detailDriveCacheModel.vehicleInsured = getVehicleInsured();

		detailDriveCacheModel.accessoriesInsured = getAccessoriesInsured();

		detailDriveCacheModel.sumInsured = getSumInsured();

		detailDriveCacheModel.regionPlate = getRegionPlate();

		String regionPlate = detailDriveCacheModel.regionPlate;

		if ((regionPlate != null) && (regionPlate.length() == 0)) {
			detailDriveCacheModel.regionPlate = null;
		}

		detailDriveCacheModel.cc = getCc();

		detailDriveCacheModel.make = getMake();

		String make = detailDriveCacheModel.make;

		if ((make != null) && (make.length() == 0)) {
			detailDriveCacheModel.make = null;
		}

		detailDriveCacheModel.dpg = getDpg();

		String dpg = detailDriveCacheModel.dpg;

		if ((dpg != null) && (dpg.length() == 0)) {
			detailDriveCacheModel.dpg = null;
		}

		detailDriveCacheModel.seatCapacity = getSeatCapacity();

		Date startDate = getStartDate();

		if (startDate != null) {
			detailDriveCacheModel.startDate = startDate.getTime();
		}
		else {
			detailDriveCacheModel.startDate = Long.MIN_VALUE;
		}

		Date expiredDate = getExpiredDate();

		if (expiredDate != null) {
			detailDriveCacheModel.expiredDate = expiredDate.getTime();
		}
		else {
			detailDriveCacheModel.expiredDate = Long.MIN_VALUE;
		}

		detailDriveCacheModel.commercialOffers = getCommercialOffers();

		detailDriveCacheModel.name = getName();

		String name = detailDriveCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			detailDriveCacheModel.name = null;
		}

		detailDriveCacheModel.birthPlace = getBirthPlace();

		String birthPlace = detailDriveCacheModel.birthPlace;

		if ((birthPlace != null) && (birthPlace.length() == 0)) {
			detailDriveCacheModel.birthPlace = null;
		}

		Date dob = getDob();

		if (dob != null) {
			detailDriveCacheModel.dob = dob.getTime();
		}
		else {
			detailDriveCacheModel.dob = Long.MIN_VALUE;
		}

		detailDriveCacheModel.nationality = getNationality();

		String nationality = detailDriveCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			detailDriveCacheModel.nationality = null;
		}

		detailDriveCacheModel.idNumber = getIdNumber();

		String idNumber = detailDriveCacheModel.idNumber;

		if ((idNumber != null) && (idNumber.length() == 0)) {
			detailDriveCacheModel.idNumber = null;
		}

		detailDriveCacheModel.passportNumber = getPassportNumber();

		String passportNumber = detailDriveCacheModel.passportNumber;

		if ((passportNumber != null) && (passportNumber.length() == 0)) {
			detailDriveCacheModel.passportNumber = null;
		}

		detailDriveCacheModel.kitasNumber = getKitasNumber();

		String kitasNumber = detailDriveCacheModel.kitasNumber;

		if ((kitasNumber != null) && (kitasNumber.length() == 0)) {
			detailDriveCacheModel.kitasNumber = null;
		}

		detailDriveCacheModel.mobilePhone = getMobilePhone();

		String mobilePhone = detailDriveCacheModel.mobilePhone;

		if ((mobilePhone != null) && (mobilePhone.length() == 0)) {
			detailDriveCacheModel.mobilePhone = null;
		}

		detailDriveCacheModel.email = getEmail();

		String email = detailDriveCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			detailDriveCacheModel.email = null;
		}

		detailDriveCacheModel.address = getAddress();

		String address = detailDriveCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			detailDriveCacheModel.address = null;
		}

		detailDriveCacheModel.address2 = getAddress2();

		String address2 = detailDriveCacheModel.address2;

		if ((address2 != null) && (address2.length() == 0)) {
			detailDriveCacheModel.address2 = null;
		}

		detailDriveCacheModel.province = getProvince();

		String province = detailDriveCacheModel.province;

		if ((province != null) && (province.length() == 0)) {
			detailDriveCacheModel.province = null;
		}

		detailDriveCacheModel.city = getCity();

		String city = detailDriveCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			detailDriveCacheModel.city = null;
		}

		detailDriveCacheModel.policeNumber = getPoliceNumber();

		String policeNumber = detailDriveCacheModel.policeNumber;

		if ((policeNumber != null) && (policeNumber.length() == 0)) {
			detailDriveCacheModel.policeNumber = null;
		}

		detailDriveCacheModel.chassisNumber = getChassisNumber();

		String chassisNumber = detailDriveCacheModel.chassisNumber;

		if ((chassisNumber != null) && (chassisNumber.length() == 0)) {
			detailDriveCacheModel.chassisNumber = null;
		}

		detailDriveCacheModel.engineNumber = getEngineNumber();

		String engineNumber = detailDriveCacheModel.engineNumber;

		if ((engineNumber != null) && (engineNumber.length() == 0)) {
			detailDriveCacheModel.engineNumber = null;
		}

		detailDriveCacheModel.policyNumber = getPolicyNumber();

		String policyNumber = detailDriveCacheModel.policyNumber;

		if ((policyNumber != null) && (policyNumber.length() == 0)) {
			detailDriveCacheModel.policyNumber = null;
		}

		detailDriveCacheModel.referenceNumber = getReferenceNumber();

		String referenceNumber = detailDriveCacheModel.referenceNumber;

		if ((referenceNumber != null) && (referenceNumber.length() == 0)) {
			detailDriveCacheModel.referenceNumber = null;
		}

		detailDriveCacheModel.policyStatus = getPolicyStatus();

		String policyStatus = detailDriveCacheModel.policyStatus;

		if ((policyStatus != null) && (policyStatus.length() == 0)) {
			detailDriveCacheModel.policyStatus = null;
		}

		detailDriveCacheModel.currency = getCurrency();

		String currency = detailDriveCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			detailDriveCacheModel.currency = null;
		}

		detailDriveCacheModel.policyCost = getPolicyCost();

		detailDriveCacheModel.stampDuty = getStampDuty();

		detailDriveCacheModel.premium = getPremium();

		detailDriveCacheModel.netPremium = getNetPremium();

		detailDriveCacheModel.discount = getDiscount();

		detailDriveCacheModel.commission = getCommission();

		String commission = detailDriveCacheModel.commission;

		if ((commission != null) && (commission.length() == 0)) {
			detailDriveCacheModel.commission = null;
		}

		detailDriveCacheModel.leads = getLeads();

		detailDriveCacheModel.transactionId = getTransactionId();

		String transactionId = detailDriveCacheModel.transactionId;

		if ((transactionId != null) && (transactionId.length() == 0)) {
			detailDriveCacheModel.transactionId = null;
		}

		detailDriveCacheModel.bussinesModel = getBussinesModel();

		String bussinesModel = detailDriveCacheModel.bussinesModel;

		if ((bussinesModel != null) && (bussinesModel.length() == 0)) {
			detailDriveCacheModel.bussinesModel = null;
		}

		detailDriveCacheModel.channel = getChannel();

		String channel = detailDriveCacheModel.channel;

		if ((channel != null) && (channel.length() == 0)) {
			detailDriveCacheModel.channel = null;
		}

		detailDriveCacheModel.promoCode = getPromoCode();

		String promoCode = detailDriveCacheModel.promoCode;

		if ((promoCode != null) && (promoCode.length() == 0)) {
			detailDriveCacheModel.promoCode = null;
		}

		detailDriveCacheModel.step1 = getStep1();

		detailDriveCacheModel.step2 = getStep2();

		detailDriveCacheModel.step3 = getStep3();

		detailDriveCacheModel.dailyReportStatus = getDailyReportStatus();

		detailDriveCacheModel.dailyReportFile = getDailyReportFile();

		detailDriveCacheModel.dailyReportAgentStatus =
			getDailyReportAgentStatus();

		detailDriveCacheModel.dailyReportAgentFile = getDailyReportAgentFile();

		detailDriveCacheModel.utmSource = getUtmSource();

		String utmSource = detailDriveCacheModel.utmSource;

		if ((utmSource != null) && (utmSource.length() == 0)) {
			detailDriveCacheModel.utmSource = null;
		}

		detailDriveCacheModel.utmMedium = getUtmMedium();

		String utmMedium = detailDriveCacheModel.utmMedium;

		if ((utmMedium != null) && (utmMedium.length() == 0)) {
			detailDriveCacheModel.utmMedium = null;
		}

		detailDriveCacheModel.utmCampaign = getUtmCampaign();

		String utmCampaign = detailDriveCacheModel.utmCampaign;

		if ((utmCampaign != null) && (utmCampaign.length() == 0)) {
			detailDriveCacheModel.utmCampaign = null;
		}

		detailDriveCacheModel.utmTerm = getUtmTerm();

		String utmTerm = detailDriveCacheModel.utmTerm;

		if ((utmTerm != null) && (utmTerm.length() == 0)) {
			detailDriveCacheModel.utmTerm = null;
		}

		detailDriveCacheModel.utmContent = getUtmContent();

		String utmContent = detailDriveCacheModel.utmContent;

		if ((utmContent != null) && (utmContent.length() == 0)) {
			detailDriveCacheModel.utmContent = null;
		}

		detailDriveCacheModel.clickId = getClickId();

		String clickId = detailDriveCacheModel.clickId;

		if ((clickId != null) && (clickId.length() == 0)) {
			detailDriveCacheModel.clickId = null;
		}

		detailDriveCacheModel.managedBy = getManagedBy();

		detailDriveCacheModel.agentCode = getAgentCode();

		String agentCode = detailDriveCacheModel.agentCode;

		if ((agentCode != null) && (agentCode.length() == 0)) {
			detailDriveCacheModel.agentCode = null;
		}

		detailDriveCacheModel.subAgent = getSubAgent();

		detailDriveCacheModel.marketingCode = getMarketingCode();

		String marketingCode = detailDriveCacheModel.marketingCode;

		if ((marketingCode != null) && (marketingCode.length() == 0)) {
			detailDriveCacheModel.marketingCode = null;
		}

		detailDriveCacheModel.active = getActive();

		return detailDriveCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DetailDrive, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DetailDrive, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailDrive, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DetailDrive)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DetailDrive, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DetailDrive, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailDrive, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DetailDrive)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DetailDrive>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DetailDrive.class, ModelWrapper.class);

	}

	private long _detailDriveId;
	private long _leadsId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _vehicleCode;
	private String _VehicleManufacture;
	private String _vehicleModel;
	private String _vehicleSubModel;
	private String _vehicleBody;
	private int _manufactureYear;
	private int _manufactureAge;
	private String _coverageType;
	private String _vehicleType;
	private String _typeOfUse;
	private double _vehicleInsured;
	private double _accessoriesInsured;
	private double _sumInsured;
	private String _regionPlate;
	private int _cc;
	private String _make;
	private String _dpg;
	private int _seatCapacity;
	private Date _startDate;
	private Date _expiredDate;
	private int _commercialOffers;
	private String _name;
	private String _birthPlace;
	private Date _dob;
	private String _nationality;
	private String _idNumber;
	private String _passportNumber;
	private String _kitasNumber;
	private String _mobilePhone;
	private String _email;
	private String _address;
	private String _address2;
	private String _province;
	private String _city;
	private String _policeNumber;
	private String _chassisNumber;
	private String _engineNumber;
	private String _policyNumber;
	private String _referenceNumber;
	private String _policyStatus;
	private String _currency;
	private double _policyCost;
	private double _stampDuty;
	private double _premium;
	private double _netPremium;
	private int _discount;
	private String _commission;
	private long _leads;
	private String _transactionId;
	private String _bussinesModel;
	private String _channel;
	private String _promoCode;
	private int _step1;
	private int _step2;
	private int _step3;
	private int _dailyReportStatus;
	private long _dailyReportFile;
	private int _dailyReportAgentStatus;
	private long _dailyReportAgentFile;
	private String _utmSource;
	private String _utmMedium;
	private String _utmCampaign;
	private String _utmTerm;
	private String _utmContent;
	private String _clickId;
	private long _managedBy;
	private String _agentCode;
	private long _subAgent;
	private String _marketingCode;
	private int _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DetailDrive, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DetailDrive)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("detailDriveId", _detailDriveId);
		_columnOriginalValues.put("leadsId", _leadsId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("vehicleCode", _vehicleCode);
		_columnOriginalValues.put("VehicleManufacture", _VehicleManufacture);
		_columnOriginalValues.put("vehicleModel", _vehicleModel);
		_columnOriginalValues.put("vehicleSubModel", _vehicleSubModel);
		_columnOriginalValues.put("vehicleBody", _vehicleBody);
		_columnOriginalValues.put("manufactureYear", _manufactureYear);
		_columnOriginalValues.put("manufactureAge", _manufactureAge);
		_columnOriginalValues.put("coverageType", _coverageType);
		_columnOriginalValues.put("vehicleType", _vehicleType);
		_columnOriginalValues.put("typeOfUse", _typeOfUse);
		_columnOriginalValues.put("vehicleInsured", _vehicleInsured);
		_columnOriginalValues.put("accessoriesInsured", _accessoriesInsured);
		_columnOriginalValues.put("sumInsured", _sumInsured);
		_columnOriginalValues.put("regionPlate", _regionPlate);
		_columnOriginalValues.put("cc", _cc);
		_columnOriginalValues.put("make", _make);
		_columnOriginalValues.put("dpg", _dpg);
		_columnOriginalValues.put("seatCapacity", _seatCapacity);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("expiredDate", _expiredDate);
		_columnOriginalValues.put("commercialOffers", _commercialOffers);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("birthPlace", _birthPlace);
		_columnOriginalValues.put("dob", _dob);
		_columnOriginalValues.put("nationality", _nationality);
		_columnOriginalValues.put("idNumber", _idNumber);
		_columnOriginalValues.put("passportNumber", _passportNumber);
		_columnOriginalValues.put("kitasNumber", _kitasNumber);
		_columnOriginalValues.put("mobilePhone", _mobilePhone);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("address2", _address2);
		_columnOriginalValues.put("province", _province);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("policeNumber", _policeNumber);
		_columnOriginalValues.put("chassisNumber", _chassisNumber);
		_columnOriginalValues.put("engineNumber", _engineNumber);
		_columnOriginalValues.put("policyNumber", _policyNumber);
		_columnOriginalValues.put("referenceNumber", _referenceNumber);
		_columnOriginalValues.put("policyStatus", _policyStatus);
		_columnOriginalValues.put("currency_", _currency);
		_columnOriginalValues.put("policyCost", _policyCost);
		_columnOriginalValues.put("stampDuty", _stampDuty);
		_columnOriginalValues.put("premium", _premium);
		_columnOriginalValues.put("netPremium", _netPremium);
		_columnOriginalValues.put("discount", _discount);
		_columnOriginalValues.put("commission", _commission);
		_columnOriginalValues.put("leads", _leads);
		_columnOriginalValues.put("transactionId", _transactionId);
		_columnOriginalValues.put("bussinesModel", _bussinesModel);
		_columnOriginalValues.put("channel", _channel);
		_columnOriginalValues.put("promoCode", _promoCode);
		_columnOriginalValues.put("step1", _step1);
		_columnOriginalValues.put("step2", _step2);
		_columnOriginalValues.put("step3", _step3);
		_columnOriginalValues.put("dailyReportStatus", _dailyReportStatus);
		_columnOriginalValues.put("dailyReportFile", _dailyReportFile);
		_columnOriginalValues.put(
			"dailyReportAgentStatus", _dailyReportAgentStatus);
		_columnOriginalValues.put(
			"dailyReportAgentFile", _dailyReportAgentFile);
		_columnOriginalValues.put("utmSource", _utmSource);
		_columnOriginalValues.put("utmMedium", _utmMedium);
		_columnOriginalValues.put("utmCampaign", _utmCampaign);
		_columnOriginalValues.put("utmTerm", _utmTerm);
		_columnOriginalValues.put("utmContent", _utmContent);
		_columnOriginalValues.put("clickId", _clickId);
		_columnOriginalValues.put("managedBy", _managedBy);
		_columnOriginalValues.put("agentCode", _agentCode);
		_columnOriginalValues.put("subAgent", _subAgent);
		_columnOriginalValues.put("marketingCode", _marketingCode);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("currency_", "currency");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;
	private DetailDrive _escapedModel;

}