/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.leads.model.DetailTlp;
import com.mypage.leads.model.DetailTlpModel;
import com.mypage.leads.model.DetailTlpSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DetailTlp service. Represents a row in the &quot;DetailTlp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DetailTlpModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DetailTlpImpl}.
 * </p>
 *
 * @author Gositus
 * @see DetailTlpImpl
 * @generated
 */
@JSON(strict = true)
public class DetailTlpModelImpl
	extends BaseModelImpl<DetailTlp> implements DetailTlpModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a detail tlp model instance should use the <code>DetailTlp</code> interface instead.
	 */
	public static final String TABLE_NAME = "DetailTlp";

	public static final Object[][] TABLE_COLUMNS = {
		{"detailTlpId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"startDate", Types.TIMESTAMP},
		{"expiredDate", Types.TIMESTAMP},
		{"mainPolicyStartDate", Types.TIMESTAMP},
		{"mainPolicyEndDate", Types.TIMESTAMP}, {"numberOfDays", Types.INTEGER},
		{"name", Types.VARCHAR}, {"birthPlace", Types.VARCHAR},
		{"dob", Types.TIMESTAMP}, {"nationality", Types.VARCHAR},
		{"idNumber", Types.VARCHAR}, {"passportNumber", Types.VARCHAR},
		{"kitasNumber", Types.VARCHAR}, {"mobilePhone", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"address2", Types.VARCHAR}, {"province", Types.VARCHAR},
		{"city", Types.VARCHAR}, {"postCode", Types.VARCHAR},
		{"commercialOffer", Types.INTEGER}, {"driveModel", Types.BIGINT},
		{"vehicleManufacture", Types.VARCHAR}, {"vehicleModel", Types.VARCHAR},
		{"vehicleSubModel", Types.VARCHAR}, {"manufactureYear", Types.INTEGER},
		{"vehicleInsured", Types.DOUBLE}, {"regionPlate", Types.VARCHAR},
		{"policeNumber", Types.VARCHAR}, {"chassisNumber", Types.VARCHAR},
		{"engineNumber", Types.VARCHAR}, {"leadsId", Types.BIGINT},
		{"transactionId_", Types.BIGINT}, {"businessModel", Types.VARCHAR},
		{"channel", Types.VARCHAR}, {"promoCode", Types.VARCHAR},
		{"step1", Types.INTEGER}, {"policyNumber", Types.VARCHAR},
		{"referenceNumber", Types.VARCHAR}, {"policyStatus", Types.VARCHAR},
		{"packageName", Types.VARCHAR}, {"packageInfo", Types.BIGINT},
		{"rate", Types.DOUBLE}, {"currency_", Types.VARCHAR},
		{"sumInsured", Types.DOUBLE}, {"policyCost", Types.DOUBLE},
		{"stampDuty", Types.DOUBLE}, {"premium", Types.DOUBLE},
		{"netPremium", Types.DOUBLE}, {"discount", Types.DOUBLE},
		{"commision", Types.DOUBLE}, {"insuranceName", Types.VARCHAR},
		{"insurancePolicyNo", Types.VARCHAR}, {"managedBy", Types.BIGINT},
		{"agentCode", Types.VARCHAR}, {"subAgent", Types.BIGINT},
		{"marketingCode", Types.VARCHAR}, {"utmSource", Types.VARCHAR},
		{"utmMedium", Types.VARCHAR}, {"utmCampaign", Types.VARCHAR},
		{"utmTerm", Types.VARCHAR}, {"utmContent", Types.VARCHAR},
		{"clickId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("detailTlpId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expiredDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("mainPolicyStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("mainPolicyEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("numberOfDays", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthPlace", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dob", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nationality", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("passportNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kitasNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobilePhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("province", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commercialOffer", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("driveModel", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vehicleManufacture", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleModel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleSubModel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("manufactureYear", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("vehicleInsured", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("regionPlate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("policeNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("chassisNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("engineNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leadsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("transactionId_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("businessModel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("channel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("promoCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("step1", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("policyNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("referenceNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("policyStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("packageName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("packageInfo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rate", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("currency_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sumInsured", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("policyCost", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("stampDuty", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("premium", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("netPremium", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("discount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("commision", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("insuranceName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("insurancePolicyNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("managedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("agentCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subAgent", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("marketingCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmSource", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmMedium", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmCampaign", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmTerm", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmContent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("clickId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DetailTlp (detailTlpId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,startDate DATE null,expiredDate DATE null,mainPolicyStartDate DATE null,mainPolicyEndDate DATE null,numberOfDays INTEGER,name VARCHAR(75) null,birthPlace VARCHAR(75) null,dob DATE null,nationality VARCHAR(75) null,idNumber VARCHAR(75) null,passportNumber VARCHAR(75) null,kitasNumber VARCHAR(75) null,mobilePhone VARCHAR(75) null,email VARCHAR(75) null,address VARCHAR(75) null,address2 VARCHAR(75) null,province VARCHAR(75) null,city VARCHAR(75) null,postCode VARCHAR(75) null,commercialOffer INTEGER,driveModel LONG,vehicleManufacture VARCHAR(75) null,vehicleModel VARCHAR(75) null,vehicleSubModel VARCHAR(75) null,manufactureYear INTEGER,vehicleInsured DOUBLE,regionPlate VARCHAR(75) null,policeNumber VARCHAR(75) null,chassisNumber VARCHAR(75) null,engineNumber VARCHAR(75) null,leadsId LONG,transactionId_ LONG,businessModel VARCHAR(75) null,channel VARCHAR(75) null,promoCode VARCHAR(75) null,step1 INTEGER,policyNumber VARCHAR(75) null,referenceNumber VARCHAR(75) null,policyStatus VARCHAR(75) null,packageName VARCHAR(75) null,packageInfo LONG,rate DOUBLE,currency_ VARCHAR(75) null,sumInsured DOUBLE,policyCost DOUBLE,stampDuty DOUBLE,premium DOUBLE,netPremium DOUBLE,discount DOUBLE,commision DOUBLE,insuranceName VARCHAR(75) null,insurancePolicyNo VARCHAR(75) null,managedBy LONG,agentCode VARCHAR(75) null,subAgent LONG,marketingCode VARCHAR(75) null,utmSource VARCHAR(75) null,utmMedium VARCHAR(75) null,utmCampaign VARCHAR(75) null,utmTerm VARCHAR(75) null,utmContent VARCHAR(75) null,clickId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table DetailTlp";

	public static final String ORDER_BY_JPQL =
		" ORDER BY detailTlp.detailTlpId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DetailTlp.detailTlpId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static DetailTlp toModel(DetailTlpSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DetailTlp model = new DetailTlpImpl();

		model.setDetailTlpId(soapModel.getDetailTlpId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStartDate(soapModel.getStartDate());
		model.setExpiredDate(soapModel.getExpiredDate());
		model.setMainPolicyStartDate(soapModel.getMainPolicyStartDate());
		model.setMainPolicyEndDate(soapModel.getMainPolicyEndDate());
		model.setNumberOfDays(soapModel.getNumberOfDays());
		model.setName(soapModel.getName());
		model.setBirthPlace(soapModel.getBirthPlace());
		model.setDob(soapModel.getDob());
		model.setNationality(soapModel.getNationality());
		model.setIdNumber(soapModel.getIdNumber());
		model.setPassportNumber(soapModel.getPassportNumber());
		model.setKitasNumber(soapModel.getKitasNumber());
		model.setMobilePhone(soapModel.getMobilePhone());
		model.setEmail(soapModel.getEmail());
		model.setAddress(soapModel.getAddress());
		model.setAddress2(soapModel.getAddress2());
		model.setProvince(soapModel.getProvince());
		model.setCity(soapModel.getCity());
		model.setPostCode(soapModel.getPostCode());
		model.setCommercialOffer(soapModel.getCommercialOffer());
		model.setDriveModel(soapModel.getDriveModel());
		model.setVehicleManufacture(soapModel.getVehicleManufacture());
		model.setVehicleModel(soapModel.getVehicleModel());
		model.setVehicleSubModel(soapModel.getVehicleSubModel());
		model.setManufactureYear(soapModel.getManufactureYear());
		model.setVehicleInsured(soapModel.getVehicleInsured());
		model.setRegionPlate(soapModel.getRegionPlate());
		model.setPoliceNumber(soapModel.getPoliceNumber());
		model.setChassisNumber(soapModel.getChassisNumber());
		model.setEngineNumber(soapModel.getEngineNumber());
		model.setLeadsId(soapModel.getLeadsId());
		model.setTransactionId_(soapModel.getTransactionId_());
		model.setBusinessModel(soapModel.getBusinessModel());
		model.setChannel(soapModel.getChannel());
		model.setPromoCode(soapModel.getPromoCode());
		model.setStep1(soapModel.getStep1());
		model.setPolicyNumber(soapModel.getPolicyNumber());
		model.setReferenceNumber(soapModel.getReferenceNumber());
		model.setPolicyStatus(soapModel.getPolicyStatus());
		model.setPackageName(soapModel.getPackageName());
		model.setPackageInfo(soapModel.getPackageInfo());
		model.setRate(soapModel.getRate());
		model.setCurrency_(soapModel.getCurrency_());
		model.setSumInsured(soapModel.getSumInsured());
		model.setPolicyCost(soapModel.getPolicyCost());
		model.setStampDuty(soapModel.getStampDuty());
		model.setPremium(soapModel.getPremium());
		model.setNetPremium(soapModel.getNetPremium());
		model.setDiscount(soapModel.getDiscount());
		model.setCommision(soapModel.getCommision());
		model.setInsuranceName(soapModel.getInsuranceName());
		model.setInsurancePolicyNo(soapModel.getInsurancePolicyNo());
		model.setManagedBy(soapModel.getManagedBy());
		model.setAgentCode(soapModel.getAgentCode());
		model.setSubAgent(soapModel.getSubAgent());
		model.setMarketingCode(soapModel.getMarketingCode());
		model.setUtmSource(soapModel.getUtmSource());
		model.setUtmMedium(soapModel.getUtmMedium());
		model.setUtmCampaign(soapModel.getUtmCampaign());
		model.setUtmTerm(soapModel.getUtmTerm());
		model.setUtmContent(soapModel.getUtmContent());
		model.setClickId(soapModel.getClickId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<DetailTlp> toModels(DetailTlpSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DetailTlp> models = new ArrayList<DetailTlp>(soapModels.length);

		for (DetailTlpSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DetailTlpModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _detailTlpId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDetailTlpId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _detailTlpId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DetailTlp.class;
	}

	@Override
	public String getModelClassName() {
		return DetailTlp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DetailTlp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DetailTlp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailTlp, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((DetailTlp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DetailTlp, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DetailTlp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DetailTlp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DetailTlp, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DetailTlp, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DetailTlp, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DetailTlp, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DetailTlp, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DetailTlp, Object>>();
		Map<String, BiConsumer<DetailTlp, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DetailTlp, ?>>();

		attributeGetterFunctions.put("detailTlpId", DetailTlp::getDetailTlpId);
		attributeSetterBiConsumers.put(
			"detailTlpId",
			(BiConsumer<DetailTlp, Long>)DetailTlp::setDetailTlpId);
		attributeGetterFunctions.put("groupId", DetailTlp::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<DetailTlp, Long>)DetailTlp::setGroupId);
		attributeGetterFunctions.put("companyId", DetailTlp::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<DetailTlp, Long>)DetailTlp::setCompanyId);
		attributeGetterFunctions.put("userId", DetailTlp::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<DetailTlp, Long>)DetailTlp::setUserId);
		attributeGetterFunctions.put("userName", DetailTlp::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<DetailTlp, String>)DetailTlp::setUserName);
		attributeGetterFunctions.put("createDate", DetailTlp::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DetailTlp, Date>)DetailTlp::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DetailTlp::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DetailTlp, Date>)DetailTlp::setModifiedDate);
		attributeGetterFunctions.put("startDate", DetailTlp::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate", (BiConsumer<DetailTlp, Date>)DetailTlp::setStartDate);
		attributeGetterFunctions.put("expiredDate", DetailTlp::getExpiredDate);
		attributeSetterBiConsumers.put(
			"expiredDate",
			(BiConsumer<DetailTlp, Date>)DetailTlp::setExpiredDate);
		attributeGetterFunctions.put(
			"mainPolicyStartDate", DetailTlp::getMainPolicyStartDate);
		attributeSetterBiConsumers.put(
			"mainPolicyStartDate",
			(BiConsumer<DetailTlp, Date>)DetailTlp::setMainPolicyStartDate);
		attributeGetterFunctions.put(
			"mainPolicyEndDate", DetailTlp::getMainPolicyEndDate);
		attributeSetterBiConsumers.put(
			"mainPolicyEndDate",
			(BiConsumer<DetailTlp, Date>)DetailTlp::setMainPolicyEndDate);
		attributeGetterFunctions.put(
			"numberOfDays", DetailTlp::getNumberOfDays);
		attributeSetterBiConsumers.put(
			"numberOfDays",
			(BiConsumer<DetailTlp, Integer>)DetailTlp::setNumberOfDays);
		attributeGetterFunctions.put("name", DetailTlp::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<DetailTlp, String>)DetailTlp::setName);
		attributeGetterFunctions.put("birthPlace", DetailTlp::getBirthPlace);
		attributeSetterBiConsumers.put(
			"birthPlace",
			(BiConsumer<DetailTlp, String>)DetailTlp::setBirthPlace);
		attributeGetterFunctions.put("dob", DetailTlp::getDob);
		attributeSetterBiConsumers.put(
			"dob", (BiConsumer<DetailTlp, Date>)DetailTlp::setDob);
		attributeGetterFunctions.put("nationality", DetailTlp::getNationality);
		attributeSetterBiConsumers.put(
			"nationality",
			(BiConsumer<DetailTlp, String>)DetailTlp::setNationality);
		attributeGetterFunctions.put("idNumber", DetailTlp::getIdNumber);
		attributeSetterBiConsumers.put(
			"idNumber", (BiConsumer<DetailTlp, String>)DetailTlp::setIdNumber);
		attributeGetterFunctions.put(
			"passportNumber", DetailTlp::getPassportNumber);
		attributeSetterBiConsumers.put(
			"passportNumber",
			(BiConsumer<DetailTlp, String>)DetailTlp::setPassportNumber);
		attributeGetterFunctions.put("kitasNumber", DetailTlp::getKitasNumber);
		attributeSetterBiConsumers.put(
			"kitasNumber",
			(BiConsumer<DetailTlp, String>)DetailTlp::setKitasNumber);
		attributeGetterFunctions.put("mobilePhone", DetailTlp::getMobilePhone);
		attributeSetterBiConsumers.put(
			"mobilePhone",
			(BiConsumer<DetailTlp, String>)DetailTlp::setMobilePhone);
		attributeGetterFunctions.put("email", DetailTlp::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<DetailTlp, String>)DetailTlp::setEmail);
		attributeGetterFunctions.put("address", DetailTlp::getAddress);
		attributeSetterBiConsumers.put(
			"address", (BiConsumer<DetailTlp, String>)DetailTlp::setAddress);
		attributeGetterFunctions.put("address2", DetailTlp::getAddress2);
		attributeSetterBiConsumers.put(
			"address2", (BiConsumer<DetailTlp, String>)DetailTlp::setAddress2);
		attributeGetterFunctions.put("province", DetailTlp::getProvince);
		attributeSetterBiConsumers.put(
			"province", (BiConsumer<DetailTlp, String>)DetailTlp::setProvince);
		attributeGetterFunctions.put("city", DetailTlp::getCity);
		attributeSetterBiConsumers.put(
			"city", (BiConsumer<DetailTlp, String>)DetailTlp::setCity);
		attributeGetterFunctions.put("postCode", DetailTlp::getPostCode);
		attributeSetterBiConsumers.put(
			"postCode", (BiConsumer<DetailTlp, String>)DetailTlp::setPostCode);
		attributeGetterFunctions.put(
			"commercialOffer", DetailTlp::getCommercialOffer);
		attributeSetterBiConsumers.put(
			"commercialOffer",
			(BiConsumer<DetailTlp, Integer>)DetailTlp::setCommercialOffer);
		attributeGetterFunctions.put("driveModel", DetailTlp::getDriveModel);
		attributeSetterBiConsumers.put(
			"driveModel",
			(BiConsumer<DetailTlp, Long>)DetailTlp::setDriveModel);
		attributeGetterFunctions.put(
			"vehicleManufacture", DetailTlp::getVehicleManufacture);
		attributeSetterBiConsumers.put(
			"vehicleManufacture",
			(BiConsumer<DetailTlp, String>)DetailTlp::setVehicleManufacture);
		attributeGetterFunctions.put(
			"vehicleModel", DetailTlp::getVehicleModel);
		attributeSetterBiConsumers.put(
			"vehicleModel",
			(BiConsumer<DetailTlp, String>)DetailTlp::setVehicleModel);
		attributeGetterFunctions.put(
			"vehicleSubModel", DetailTlp::getVehicleSubModel);
		attributeSetterBiConsumers.put(
			"vehicleSubModel",
			(BiConsumer<DetailTlp, String>)DetailTlp::setVehicleSubModel);
		attributeGetterFunctions.put(
			"manufactureYear", DetailTlp::getManufactureYear);
		attributeSetterBiConsumers.put(
			"manufactureYear",
			(BiConsumer<DetailTlp, Integer>)DetailTlp::setManufactureYear);
		attributeGetterFunctions.put(
			"vehicleInsured", DetailTlp::getVehicleInsured);
		attributeSetterBiConsumers.put(
			"vehicleInsured",
			(BiConsumer<DetailTlp, Double>)DetailTlp::setVehicleInsured);
		attributeGetterFunctions.put("regionPlate", DetailTlp::getRegionPlate);
		attributeSetterBiConsumers.put(
			"regionPlate",
			(BiConsumer<DetailTlp, String>)DetailTlp::setRegionPlate);
		attributeGetterFunctions.put(
			"policeNumber", DetailTlp::getPoliceNumber);
		attributeSetterBiConsumers.put(
			"policeNumber",
			(BiConsumer<DetailTlp, String>)DetailTlp::setPoliceNumber);
		attributeGetterFunctions.put(
			"chassisNumber", DetailTlp::getChassisNumber);
		attributeSetterBiConsumers.put(
			"chassisNumber",
			(BiConsumer<DetailTlp, String>)DetailTlp::setChassisNumber);
		attributeGetterFunctions.put(
			"engineNumber", DetailTlp::getEngineNumber);
		attributeSetterBiConsumers.put(
			"engineNumber",
			(BiConsumer<DetailTlp, String>)DetailTlp::setEngineNumber);
		attributeGetterFunctions.put("leadsId", DetailTlp::getLeadsId);
		attributeSetterBiConsumers.put(
			"leadsId", (BiConsumer<DetailTlp, Long>)DetailTlp::setLeadsId);
		attributeGetterFunctions.put(
			"transactionId_", DetailTlp::getTransactionId_);
		attributeSetterBiConsumers.put(
			"transactionId_",
			(BiConsumer<DetailTlp, Long>)DetailTlp::setTransactionId_);
		attributeGetterFunctions.put(
			"businessModel", DetailTlp::getBusinessModel);
		attributeSetterBiConsumers.put(
			"businessModel",
			(BiConsumer<DetailTlp, String>)DetailTlp::setBusinessModel);
		attributeGetterFunctions.put("channel", DetailTlp::getChannel);
		attributeSetterBiConsumers.put(
			"channel", (BiConsumer<DetailTlp, String>)DetailTlp::setChannel);
		attributeGetterFunctions.put("promoCode", DetailTlp::getPromoCode);
		attributeSetterBiConsumers.put(
			"promoCode",
			(BiConsumer<DetailTlp, String>)DetailTlp::setPromoCode);
		attributeGetterFunctions.put("step1", DetailTlp::getStep1);
		attributeSetterBiConsumers.put(
			"step1", (BiConsumer<DetailTlp, Integer>)DetailTlp::setStep1);
		attributeGetterFunctions.put(
			"policyNumber", DetailTlp::getPolicyNumber);
		attributeSetterBiConsumers.put(
			"policyNumber",
			(BiConsumer<DetailTlp, String>)DetailTlp::setPolicyNumber);
		attributeGetterFunctions.put(
			"referenceNumber", DetailTlp::getReferenceNumber);
		attributeSetterBiConsumers.put(
			"referenceNumber",
			(BiConsumer<DetailTlp, String>)DetailTlp::setReferenceNumber);
		attributeGetterFunctions.put(
			"policyStatus", DetailTlp::getPolicyStatus);
		attributeSetterBiConsumers.put(
			"policyStatus",
			(BiConsumer<DetailTlp, String>)DetailTlp::setPolicyStatus);
		attributeGetterFunctions.put("packageName", DetailTlp::getPackageName);
		attributeSetterBiConsumers.put(
			"packageName",
			(BiConsumer<DetailTlp, String>)DetailTlp::setPackageName);
		attributeGetterFunctions.put("packageInfo", DetailTlp::getPackageInfo);
		attributeSetterBiConsumers.put(
			"packageInfo",
			(BiConsumer<DetailTlp, Long>)DetailTlp::setPackageInfo);
		attributeGetterFunctions.put("rate", DetailTlp::getRate);
		attributeSetterBiConsumers.put(
			"rate", (BiConsumer<DetailTlp, Double>)DetailTlp::setRate);
		attributeGetterFunctions.put("currency_", DetailTlp::getCurrency_);
		attributeSetterBiConsumers.put(
			"currency_",
			(BiConsumer<DetailTlp, String>)DetailTlp::setCurrency_);
		attributeGetterFunctions.put("sumInsured", DetailTlp::getSumInsured);
		attributeSetterBiConsumers.put(
			"sumInsured",
			(BiConsumer<DetailTlp, Double>)DetailTlp::setSumInsured);
		attributeGetterFunctions.put("policyCost", DetailTlp::getPolicyCost);
		attributeSetterBiConsumers.put(
			"policyCost",
			(BiConsumer<DetailTlp, Double>)DetailTlp::setPolicyCost);
		attributeGetterFunctions.put("stampDuty", DetailTlp::getStampDuty);
		attributeSetterBiConsumers.put(
			"stampDuty",
			(BiConsumer<DetailTlp, Double>)DetailTlp::setStampDuty);
		attributeGetterFunctions.put("premium", DetailTlp::getPremium);
		attributeSetterBiConsumers.put(
			"premium", (BiConsumer<DetailTlp, Double>)DetailTlp::setPremium);
		attributeGetterFunctions.put("netPremium", DetailTlp::getNetPremium);
		attributeSetterBiConsumers.put(
			"netPremium",
			(BiConsumer<DetailTlp, Double>)DetailTlp::setNetPremium);
		attributeGetterFunctions.put("discount", DetailTlp::getDiscount);
		attributeSetterBiConsumers.put(
			"discount", (BiConsumer<DetailTlp, Double>)DetailTlp::setDiscount);
		attributeGetterFunctions.put("commision", DetailTlp::getCommision);
		attributeSetterBiConsumers.put(
			"commision",
			(BiConsumer<DetailTlp, Double>)DetailTlp::setCommision);
		attributeGetterFunctions.put(
			"insuranceName", DetailTlp::getInsuranceName);
		attributeSetterBiConsumers.put(
			"insuranceName",
			(BiConsumer<DetailTlp, String>)DetailTlp::setInsuranceName);
		attributeGetterFunctions.put(
			"insurancePolicyNo", DetailTlp::getInsurancePolicyNo);
		attributeSetterBiConsumers.put(
			"insurancePolicyNo",
			(BiConsumer<DetailTlp, String>)DetailTlp::setInsurancePolicyNo);
		attributeGetterFunctions.put("managedBy", DetailTlp::getManagedBy);
		attributeSetterBiConsumers.put(
			"managedBy", (BiConsumer<DetailTlp, Long>)DetailTlp::setManagedBy);
		attributeGetterFunctions.put("agentCode", DetailTlp::getAgentCode);
		attributeSetterBiConsumers.put(
			"agentCode",
			(BiConsumer<DetailTlp, String>)DetailTlp::setAgentCode);
		attributeGetterFunctions.put("subAgent", DetailTlp::getSubAgent);
		attributeSetterBiConsumers.put(
			"subAgent", (BiConsumer<DetailTlp, Long>)DetailTlp::setSubAgent);
		attributeGetterFunctions.put(
			"marketingCode", DetailTlp::getMarketingCode);
		attributeSetterBiConsumers.put(
			"marketingCode",
			(BiConsumer<DetailTlp, String>)DetailTlp::setMarketingCode);
		attributeGetterFunctions.put("utmSource", DetailTlp::getUtmSource);
		attributeSetterBiConsumers.put(
			"utmSource",
			(BiConsumer<DetailTlp, String>)DetailTlp::setUtmSource);
		attributeGetterFunctions.put("utmMedium", DetailTlp::getUtmMedium);
		attributeSetterBiConsumers.put(
			"utmMedium",
			(BiConsumer<DetailTlp, String>)DetailTlp::setUtmMedium);
		attributeGetterFunctions.put("utmCampaign", DetailTlp::getUtmCampaign);
		attributeSetterBiConsumers.put(
			"utmCampaign",
			(BiConsumer<DetailTlp, String>)DetailTlp::setUtmCampaign);
		attributeGetterFunctions.put("utmTerm", DetailTlp::getUtmTerm);
		attributeSetterBiConsumers.put(
			"utmTerm", (BiConsumer<DetailTlp, String>)DetailTlp::setUtmTerm);
		attributeGetterFunctions.put("utmContent", DetailTlp::getUtmContent);
		attributeSetterBiConsumers.put(
			"utmContent",
			(BiConsumer<DetailTlp, String>)DetailTlp::setUtmContent);
		attributeGetterFunctions.put("clickId", DetailTlp::getClickId);
		attributeSetterBiConsumers.put(
			"clickId", (BiConsumer<DetailTlp, String>)DetailTlp::setClickId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getDetailTlpId() {
		return _detailTlpId;
	}

	@Override
	public void setDetailTlpId(long detailTlpId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_detailTlpId = detailTlpId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getExpiredDate() {
		return _expiredDate;
	}

	@Override
	public void setExpiredDate(Date expiredDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expiredDate = expiredDate;
	}

	@JSON
	@Override
	public Date getMainPolicyStartDate() {
		return _mainPolicyStartDate;
	}

	@Override
	public void setMainPolicyStartDate(Date mainPolicyStartDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mainPolicyStartDate = mainPolicyStartDate;
	}

	@JSON
	@Override
	public Date getMainPolicyEndDate() {
		return _mainPolicyEndDate;
	}

	@Override
	public void setMainPolicyEndDate(Date mainPolicyEndDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mainPolicyEndDate = mainPolicyEndDate;
	}

	@JSON
	@Override
	public int getNumberOfDays() {
		return _numberOfDays;
	}

	@Override
	public void setNumberOfDays(int numberOfDays) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numberOfDays = numberOfDays;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getBirthPlace() {
		if (_birthPlace == null) {
			return "";
		}
		else {
			return _birthPlace;
		}
	}

	@Override
	public void setBirthPlace(String birthPlace) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthPlace = birthPlace;
	}

	@JSON
	@Override
	public Date getDob() {
		return _dob;
	}

	@Override
	public void setDob(Date dob) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dob = dob;
	}

	@JSON
	@Override
	public String getNationality() {
		if (_nationality == null) {
			return "";
		}
		else {
			return _nationality;
		}
	}

	@Override
	public void setNationality(String nationality) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nationality = nationality;
	}

	@JSON
	@Override
	public String getIdNumber() {
		if (_idNumber == null) {
			return "";
		}
		else {
			return _idNumber;
		}
	}

	@Override
	public void setIdNumber(String idNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idNumber = idNumber;
	}

	@JSON
	@Override
	public String getPassportNumber() {
		if (_passportNumber == null) {
			return "";
		}
		else {
			return _passportNumber;
		}
	}

	@Override
	public void setPassportNumber(String passportNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_passportNumber = passportNumber;
	}

	@JSON
	@Override
	public String getKitasNumber() {
		if (_kitasNumber == null) {
			return "";
		}
		else {
			return _kitasNumber;
		}
	}

	@Override
	public void setKitasNumber(String kitasNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kitasNumber = kitasNumber;
	}

	@JSON
	@Override
	public String getMobilePhone() {
		if (_mobilePhone == null) {
			return "";
		}
		else {
			return _mobilePhone;
		}
	}

	@Override
	public void setMobilePhone(String mobilePhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobilePhone = mobilePhone;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public String getAddress2() {
		if (_address2 == null) {
			return "";
		}
		else {
			return _address2;
		}
	}

	@Override
	public void setAddress2(String address2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address2 = address2;
	}

	@JSON
	@Override
	public String getProvince() {
		if (_province == null) {
			return "";
		}
		else {
			return _province;
		}
	}

	@Override
	public void setProvince(String province) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_province = province;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@JSON
	@Override
	public String getPostCode() {
		if (_postCode == null) {
			return "";
		}
		else {
			return _postCode;
		}
	}

	@Override
	public void setPostCode(String postCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_postCode = postCode;
	}

	@JSON
	@Override
	public int getCommercialOffer() {
		return _commercialOffer;
	}

	@Override
	public void setCommercialOffer(int commercialOffer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commercialOffer = commercialOffer;
	}

	@JSON
	@Override
	public long getDriveModel() {
		return _driveModel;
	}

	@Override
	public void setDriveModel(long driveModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_driveModel = driveModel;
	}

	@JSON
	@Override
	public String getVehicleManufacture() {
		if (_vehicleManufacture == null) {
			return "";
		}
		else {
			return _vehicleManufacture;
		}
	}

	@Override
	public void setVehicleManufacture(String vehicleManufacture) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleManufacture = vehicleManufacture;
	}

	@JSON
	@Override
	public String getVehicleModel() {
		if (_vehicleModel == null) {
			return "";
		}
		else {
			return _vehicleModel;
		}
	}

	@Override
	public void setVehicleModel(String vehicleModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleModel = vehicleModel;
	}

	@JSON
	@Override
	public String getVehicleSubModel() {
		if (_vehicleSubModel == null) {
			return "";
		}
		else {
			return _vehicleSubModel;
		}
	}

	@Override
	public void setVehicleSubModel(String vehicleSubModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleSubModel = vehicleSubModel;
	}

	@JSON
	@Override
	public int getManufactureYear() {
		return _manufactureYear;
	}

	@Override
	public void setManufactureYear(int manufactureYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_manufactureYear = manufactureYear;
	}

	@JSON
	@Override
	public double getVehicleInsured() {
		return _vehicleInsured;
	}

	@Override
	public void setVehicleInsured(double vehicleInsured) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vehicleInsured = vehicleInsured;
	}

	@JSON
	@Override
	public String getRegionPlate() {
		if (_regionPlate == null) {
			return "";
		}
		else {
			return _regionPlate;
		}
	}

	@Override
	public void setRegionPlate(String regionPlate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_regionPlate = regionPlate;
	}

	@JSON
	@Override
	public String getPoliceNumber() {
		if (_policeNumber == null) {
			return "";
		}
		else {
			return _policeNumber;
		}
	}

	@Override
	public void setPoliceNumber(String policeNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policeNumber = policeNumber;
	}

	@JSON
	@Override
	public String getChassisNumber() {
		if (_chassisNumber == null) {
			return "";
		}
		else {
			return _chassisNumber;
		}
	}

	@Override
	public void setChassisNumber(String chassisNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chassisNumber = chassisNumber;
	}

	@JSON
	@Override
	public String getEngineNumber() {
		if (_engineNumber == null) {
			return "";
		}
		else {
			return _engineNumber;
		}
	}

	@Override
	public void setEngineNumber(String engineNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_engineNumber = engineNumber;
	}

	@JSON
	@Override
	public long getLeadsId() {
		return _leadsId;
	}

	@Override
	public void setLeadsId(long leadsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leadsId = leadsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeadsId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("leadsId"));
	}

	@JSON
	@Override
	public long getTransactionId_() {
		return _transactionId_;
	}

	@Override
	public void setTransactionId_(long transactionId_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_transactionId_ = transactionId_;
	}

	@JSON
	@Override
	public String getBusinessModel() {
		if (_businessModel == null) {
			return "";
		}
		else {
			return _businessModel;
		}
	}

	@Override
	public void setBusinessModel(String businessModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_businessModel = businessModel;
	}

	@JSON
	@Override
	public String getChannel() {
		if (_channel == null) {
			return "";
		}
		else {
			return _channel;
		}
	}

	@Override
	public void setChannel(String channel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channel = channel;
	}

	@JSON
	@Override
	public String getPromoCode() {
		if (_promoCode == null) {
			return "";
		}
		else {
			return _promoCode;
		}
	}

	@Override
	public void setPromoCode(String promoCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promoCode = promoCode;
	}

	@JSON
	@Override
	public int getStep1() {
		return _step1;
	}

	@Override
	public void setStep1(int step1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_step1 = step1;
	}

	@JSON
	@Override
	public String getPolicyNumber() {
		if (_policyNumber == null) {
			return "";
		}
		else {
			return _policyNumber;
		}
	}

	@Override
	public void setPolicyNumber(String policyNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyNumber = policyNumber;
	}

	@JSON
	@Override
	public String getReferenceNumber() {
		if (_referenceNumber == null) {
			return "";
		}
		else {
			return _referenceNumber;
		}
	}

	@Override
	public void setReferenceNumber(String referenceNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_referenceNumber = referenceNumber;
	}

	@JSON
	@Override
	public String getPolicyStatus() {
		if (_policyStatus == null) {
			return "";
		}
		else {
			return _policyStatus;
		}
	}

	@Override
	public void setPolicyStatus(String policyStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyStatus = policyStatus;
	}

	@JSON
	@Override
	public String getPackageName() {
		if (_packageName == null) {
			return "";
		}
		else {
			return _packageName;
		}
	}

	@Override
	public void setPackageName(String packageName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_packageName = packageName;
	}

	@JSON
	@Override
	public long getPackageInfo() {
		return _packageInfo;
	}

	@Override
	public void setPackageInfo(long packageInfo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_packageInfo = packageInfo;
	}

	@JSON
	@Override
	public double getRate() {
		return _rate;
	}

	@Override
	public void setRate(double rate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rate = rate;
	}

	@JSON
	@Override
	public String getCurrency_() {
		if (_currency_ == null) {
			return "";
		}
		else {
			return _currency_;
		}
	}

	@Override
	public void setCurrency_(String currency_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currency_ = currency_;
	}

	@JSON
	@Override
	public double getSumInsured() {
		return _sumInsured;
	}

	@Override
	public void setSumInsured(double sumInsured) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sumInsured = sumInsured;
	}

	@JSON
	@Override
	public double getPolicyCost() {
		return _policyCost;
	}

	@Override
	public void setPolicyCost(double policyCost) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyCost = policyCost;
	}

	@JSON
	@Override
	public double getStampDuty() {
		return _stampDuty;
	}

	@Override
	public void setStampDuty(double stampDuty) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stampDuty = stampDuty;
	}

	@JSON
	@Override
	public double getPremium() {
		return _premium;
	}

	@Override
	public void setPremium(double premium) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_premium = premium;
	}

	@JSON
	@Override
	public double getNetPremium() {
		return _netPremium;
	}

	@Override
	public void setNetPremium(double netPremium) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_netPremium = netPremium;
	}

	@JSON
	@Override
	public double getDiscount() {
		return _discount;
	}

	@Override
	public void setDiscount(double discount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_discount = discount;
	}

	@JSON
	@Override
	public double getCommision() {
		return _commision;
	}

	@Override
	public void setCommision(double commision) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commision = commision;
	}

	@JSON
	@Override
	public String getInsuranceName() {
		if (_insuranceName == null) {
			return "";
		}
		else {
			return _insuranceName;
		}
	}

	@Override
	public void setInsuranceName(String insuranceName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuranceName = insuranceName;
	}

	@JSON
	@Override
	public String getInsurancePolicyNo() {
		if (_insurancePolicyNo == null) {
			return "";
		}
		else {
			return _insurancePolicyNo;
		}
	}

	@Override
	public void setInsurancePolicyNo(String insurancePolicyNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insurancePolicyNo = insurancePolicyNo;
	}

	@JSON
	@Override
	public long getManagedBy() {
		return _managedBy;
	}

	@Override
	public void setManagedBy(long managedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_managedBy = managedBy;
	}

	@JSON
	@Override
	public String getAgentCode() {
		if (_agentCode == null) {
			return "";
		}
		else {
			return _agentCode;
		}
	}

	@Override
	public void setAgentCode(String agentCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agentCode = agentCode;
	}

	@JSON
	@Override
	public long getSubAgent() {
		return _subAgent;
	}

	@Override
	public void setSubAgent(long subAgent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subAgent = subAgent;
	}

	@JSON
	@Override
	public String getMarketingCode() {
		if (_marketingCode == null) {
			return "";
		}
		else {
			return _marketingCode;
		}
	}

	@Override
	public void setMarketingCode(String marketingCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_marketingCode = marketingCode;
	}

	@JSON
	@Override
	public String getUtmSource() {
		if (_utmSource == null) {
			return "";
		}
		else {
			return _utmSource;
		}
	}

	@Override
	public void setUtmSource(String utmSource) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmSource = utmSource;
	}

	@JSON
	@Override
	public String getUtmMedium() {
		if (_utmMedium == null) {
			return "";
		}
		else {
			return _utmMedium;
		}
	}

	@Override
	public void setUtmMedium(String utmMedium) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmMedium = utmMedium;
	}

	@JSON
	@Override
	public String getUtmCampaign() {
		if (_utmCampaign == null) {
			return "";
		}
		else {
			return _utmCampaign;
		}
	}

	@Override
	public void setUtmCampaign(String utmCampaign) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmCampaign = utmCampaign;
	}

	@JSON
	@Override
	public String getUtmTerm() {
		if (_utmTerm == null) {
			return "";
		}
		else {
			return _utmTerm;
		}
	}

	@Override
	public void setUtmTerm(String utmTerm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmTerm = utmTerm;
	}

	@JSON
	@Override
	public String getUtmContent() {
		if (_utmContent == null) {
			return "";
		}
		else {
			return _utmContent;
		}
	}

	@Override
	public void setUtmContent(String utmContent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmContent = utmContent;
	}

	@JSON
	@Override
	public String getClickId() {
		if (_clickId == null) {
			return "";
		}
		else {
			return _clickId;
		}
	}

	@Override
	public void setClickId(String clickId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_clickId = clickId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DetailTlp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DetailTlp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DetailTlp>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DetailTlpImpl detailTlpImpl = new DetailTlpImpl();

		detailTlpImpl.setDetailTlpId(getDetailTlpId());
		detailTlpImpl.setGroupId(getGroupId());
		detailTlpImpl.setCompanyId(getCompanyId());
		detailTlpImpl.setUserId(getUserId());
		detailTlpImpl.setUserName(getUserName());
		detailTlpImpl.setCreateDate(getCreateDate());
		detailTlpImpl.setModifiedDate(getModifiedDate());
		detailTlpImpl.setStartDate(getStartDate());
		detailTlpImpl.setExpiredDate(getExpiredDate());
		detailTlpImpl.setMainPolicyStartDate(getMainPolicyStartDate());
		detailTlpImpl.setMainPolicyEndDate(getMainPolicyEndDate());
		detailTlpImpl.setNumberOfDays(getNumberOfDays());
		detailTlpImpl.setName(getName());
		detailTlpImpl.setBirthPlace(getBirthPlace());
		detailTlpImpl.setDob(getDob());
		detailTlpImpl.setNationality(getNationality());
		detailTlpImpl.setIdNumber(getIdNumber());
		detailTlpImpl.setPassportNumber(getPassportNumber());
		detailTlpImpl.setKitasNumber(getKitasNumber());
		detailTlpImpl.setMobilePhone(getMobilePhone());
		detailTlpImpl.setEmail(getEmail());
		detailTlpImpl.setAddress(getAddress());
		detailTlpImpl.setAddress2(getAddress2());
		detailTlpImpl.setProvince(getProvince());
		detailTlpImpl.setCity(getCity());
		detailTlpImpl.setPostCode(getPostCode());
		detailTlpImpl.setCommercialOffer(getCommercialOffer());
		detailTlpImpl.setDriveModel(getDriveModel());
		detailTlpImpl.setVehicleManufacture(getVehicleManufacture());
		detailTlpImpl.setVehicleModel(getVehicleModel());
		detailTlpImpl.setVehicleSubModel(getVehicleSubModel());
		detailTlpImpl.setManufactureYear(getManufactureYear());
		detailTlpImpl.setVehicleInsured(getVehicleInsured());
		detailTlpImpl.setRegionPlate(getRegionPlate());
		detailTlpImpl.setPoliceNumber(getPoliceNumber());
		detailTlpImpl.setChassisNumber(getChassisNumber());
		detailTlpImpl.setEngineNumber(getEngineNumber());
		detailTlpImpl.setLeadsId(getLeadsId());
		detailTlpImpl.setTransactionId_(getTransactionId_());
		detailTlpImpl.setBusinessModel(getBusinessModel());
		detailTlpImpl.setChannel(getChannel());
		detailTlpImpl.setPromoCode(getPromoCode());
		detailTlpImpl.setStep1(getStep1());
		detailTlpImpl.setPolicyNumber(getPolicyNumber());
		detailTlpImpl.setReferenceNumber(getReferenceNumber());
		detailTlpImpl.setPolicyStatus(getPolicyStatus());
		detailTlpImpl.setPackageName(getPackageName());
		detailTlpImpl.setPackageInfo(getPackageInfo());
		detailTlpImpl.setRate(getRate());
		detailTlpImpl.setCurrency_(getCurrency_());
		detailTlpImpl.setSumInsured(getSumInsured());
		detailTlpImpl.setPolicyCost(getPolicyCost());
		detailTlpImpl.setStampDuty(getStampDuty());
		detailTlpImpl.setPremium(getPremium());
		detailTlpImpl.setNetPremium(getNetPremium());
		detailTlpImpl.setDiscount(getDiscount());
		detailTlpImpl.setCommision(getCommision());
		detailTlpImpl.setInsuranceName(getInsuranceName());
		detailTlpImpl.setInsurancePolicyNo(getInsurancePolicyNo());
		detailTlpImpl.setManagedBy(getManagedBy());
		detailTlpImpl.setAgentCode(getAgentCode());
		detailTlpImpl.setSubAgent(getSubAgent());
		detailTlpImpl.setMarketingCode(getMarketingCode());
		detailTlpImpl.setUtmSource(getUtmSource());
		detailTlpImpl.setUtmMedium(getUtmMedium());
		detailTlpImpl.setUtmCampaign(getUtmCampaign());
		detailTlpImpl.setUtmTerm(getUtmTerm());
		detailTlpImpl.setUtmContent(getUtmContent());
		detailTlpImpl.setClickId(getClickId());

		detailTlpImpl.resetOriginalValues();

		return detailTlpImpl;
	}

	@Override
	public int compareTo(DetailTlp detailTlp) {
		long primaryKey = detailTlp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DetailTlp)) {
			return false;
		}

		DetailTlp detailTlp = (DetailTlp)object;

		long primaryKey = detailTlp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;
	}

	@Override
	public CacheModel<DetailTlp> toCacheModel() {
		DetailTlpCacheModel detailTlpCacheModel = new DetailTlpCacheModel();

		detailTlpCacheModel.detailTlpId = getDetailTlpId();

		detailTlpCacheModel.groupId = getGroupId();

		detailTlpCacheModel.companyId = getCompanyId();

		detailTlpCacheModel.userId = getUserId();

		detailTlpCacheModel.userName = getUserName();

		String userName = detailTlpCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			detailTlpCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			detailTlpCacheModel.createDate = createDate.getTime();
		}
		else {
			detailTlpCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			detailTlpCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			detailTlpCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			detailTlpCacheModel.startDate = startDate.getTime();
		}
		else {
			detailTlpCacheModel.startDate = Long.MIN_VALUE;
		}

		Date expiredDate = getExpiredDate();

		if (expiredDate != null) {
			detailTlpCacheModel.expiredDate = expiredDate.getTime();
		}
		else {
			detailTlpCacheModel.expiredDate = Long.MIN_VALUE;
		}

		Date mainPolicyStartDate = getMainPolicyStartDate();

		if (mainPolicyStartDate != null) {
			detailTlpCacheModel.mainPolicyStartDate =
				mainPolicyStartDate.getTime();
		}
		else {
			detailTlpCacheModel.mainPolicyStartDate = Long.MIN_VALUE;
		}

		Date mainPolicyEndDate = getMainPolicyEndDate();

		if (mainPolicyEndDate != null) {
			detailTlpCacheModel.mainPolicyEndDate = mainPolicyEndDate.getTime();
		}
		else {
			detailTlpCacheModel.mainPolicyEndDate = Long.MIN_VALUE;
		}

		detailTlpCacheModel.numberOfDays = getNumberOfDays();

		detailTlpCacheModel.name = getName();

		String name = detailTlpCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			detailTlpCacheModel.name = null;
		}

		detailTlpCacheModel.birthPlace = getBirthPlace();

		String birthPlace = detailTlpCacheModel.birthPlace;

		if ((birthPlace != null) && (birthPlace.length() == 0)) {
			detailTlpCacheModel.birthPlace = null;
		}

		Date dob = getDob();

		if (dob != null) {
			detailTlpCacheModel.dob = dob.getTime();
		}
		else {
			detailTlpCacheModel.dob = Long.MIN_VALUE;
		}

		detailTlpCacheModel.nationality = getNationality();

		String nationality = detailTlpCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			detailTlpCacheModel.nationality = null;
		}

		detailTlpCacheModel.idNumber = getIdNumber();

		String idNumber = detailTlpCacheModel.idNumber;

		if ((idNumber != null) && (idNumber.length() == 0)) {
			detailTlpCacheModel.idNumber = null;
		}

		detailTlpCacheModel.passportNumber = getPassportNumber();

		String passportNumber = detailTlpCacheModel.passportNumber;

		if ((passportNumber != null) && (passportNumber.length() == 0)) {
			detailTlpCacheModel.passportNumber = null;
		}

		detailTlpCacheModel.kitasNumber = getKitasNumber();

		String kitasNumber = detailTlpCacheModel.kitasNumber;

		if ((kitasNumber != null) && (kitasNumber.length() == 0)) {
			detailTlpCacheModel.kitasNumber = null;
		}

		detailTlpCacheModel.mobilePhone = getMobilePhone();

		String mobilePhone = detailTlpCacheModel.mobilePhone;

		if ((mobilePhone != null) && (mobilePhone.length() == 0)) {
			detailTlpCacheModel.mobilePhone = null;
		}

		detailTlpCacheModel.email = getEmail();

		String email = detailTlpCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			detailTlpCacheModel.email = null;
		}

		detailTlpCacheModel.address = getAddress();

		String address = detailTlpCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			detailTlpCacheModel.address = null;
		}

		detailTlpCacheModel.address2 = getAddress2();

		String address2 = detailTlpCacheModel.address2;

		if ((address2 != null) && (address2.length() == 0)) {
			detailTlpCacheModel.address2 = null;
		}

		detailTlpCacheModel.province = getProvince();

		String province = detailTlpCacheModel.province;

		if ((province != null) && (province.length() == 0)) {
			detailTlpCacheModel.province = null;
		}

		detailTlpCacheModel.city = getCity();

		String city = detailTlpCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			detailTlpCacheModel.city = null;
		}

		detailTlpCacheModel.postCode = getPostCode();

		String postCode = detailTlpCacheModel.postCode;

		if ((postCode != null) && (postCode.length() == 0)) {
			detailTlpCacheModel.postCode = null;
		}

		detailTlpCacheModel.commercialOffer = getCommercialOffer();

		detailTlpCacheModel.driveModel = getDriveModel();

		detailTlpCacheModel.vehicleManufacture = getVehicleManufacture();

		String vehicleManufacture = detailTlpCacheModel.vehicleManufacture;

		if ((vehicleManufacture != null) &&
			(vehicleManufacture.length() == 0)) {

			detailTlpCacheModel.vehicleManufacture = null;
		}

		detailTlpCacheModel.vehicleModel = getVehicleModel();

		String vehicleModel = detailTlpCacheModel.vehicleModel;

		if ((vehicleModel != null) && (vehicleModel.length() == 0)) {
			detailTlpCacheModel.vehicleModel = null;
		}

		detailTlpCacheModel.vehicleSubModel = getVehicleSubModel();

		String vehicleSubModel = detailTlpCacheModel.vehicleSubModel;

		if ((vehicleSubModel != null) && (vehicleSubModel.length() == 0)) {
			detailTlpCacheModel.vehicleSubModel = null;
		}

		detailTlpCacheModel.manufactureYear = getManufactureYear();

		detailTlpCacheModel.vehicleInsured = getVehicleInsured();

		detailTlpCacheModel.regionPlate = getRegionPlate();

		String regionPlate = detailTlpCacheModel.regionPlate;

		if ((regionPlate != null) && (regionPlate.length() == 0)) {
			detailTlpCacheModel.regionPlate = null;
		}

		detailTlpCacheModel.policeNumber = getPoliceNumber();

		String policeNumber = detailTlpCacheModel.policeNumber;

		if ((policeNumber != null) && (policeNumber.length() == 0)) {
			detailTlpCacheModel.policeNumber = null;
		}

		detailTlpCacheModel.chassisNumber = getChassisNumber();

		String chassisNumber = detailTlpCacheModel.chassisNumber;

		if ((chassisNumber != null) && (chassisNumber.length() == 0)) {
			detailTlpCacheModel.chassisNumber = null;
		}

		detailTlpCacheModel.engineNumber = getEngineNumber();

		String engineNumber = detailTlpCacheModel.engineNumber;

		if ((engineNumber != null) && (engineNumber.length() == 0)) {
			detailTlpCacheModel.engineNumber = null;
		}

		detailTlpCacheModel.leadsId = getLeadsId();

		detailTlpCacheModel.transactionId_ = getTransactionId_();

		detailTlpCacheModel.businessModel = getBusinessModel();

		String businessModel = detailTlpCacheModel.businessModel;

		if ((businessModel != null) && (businessModel.length() == 0)) {
			detailTlpCacheModel.businessModel = null;
		}

		detailTlpCacheModel.channel = getChannel();

		String channel = detailTlpCacheModel.channel;

		if ((channel != null) && (channel.length() == 0)) {
			detailTlpCacheModel.channel = null;
		}

		detailTlpCacheModel.promoCode = getPromoCode();

		String promoCode = detailTlpCacheModel.promoCode;

		if ((promoCode != null) && (promoCode.length() == 0)) {
			detailTlpCacheModel.promoCode = null;
		}

		detailTlpCacheModel.step1 = getStep1();

		detailTlpCacheModel.policyNumber = getPolicyNumber();

		String policyNumber = detailTlpCacheModel.policyNumber;

		if ((policyNumber != null) && (policyNumber.length() == 0)) {
			detailTlpCacheModel.policyNumber = null;
		}

		detailTlpCacheModel.referenceNumber = getReferenceNumber();

		String referenceNumber = detailTlpCacheModel.referenceNumber;

		if ((referenceNumber != null) && (referenceNumber.length() == 0)) {
			detailTlpCacheModel.referenceNumber = null;
		}

		detailTlpCacheModel.policyStatus = getPolicyStatus();

		String policyStatus = detailTlpCacheModel.policyStatus;

		if ((policyStatus != null) && (policyStatus.length() == 0)) {
			detailTlpCacheModel.policyStatus = null;
		}

		detailTlpCacheModel.packageName = getPackageName();

		String packageName = detailTlpCacheModel.packageName;

		if ((packageName != null) && (packageName.length() == 0)) {
			detailTlpCacheModel.packageName = null;
		}

		detailTlpCacheModel.packageInfo = getPackageInfo();

		detailTlpCacheModel.rate = getRate();

		detailTlpCacheModel.currency_ = getCurrency_();

		String currency_ = detailTlpCacheModel.currency_;

		if ((currency_ != null) && (currency_.length() == 0)) {
			detailTlpCacheModel.currency_ = null;
		}

		detailTlpCacheModel.sumInsured = getSumInsured();

		detailTlpCacheModel.policyCost = getPolicyCost();

		detailTlpCacheModel.stampDuty = getStampDuty();

		detailTlpCacheModel.premium = getPremium();

		detailTlpCacheModel.netPremium = getNetPremium();

		detailTlpCacheModel.discount = getDiscount();

		detailTlpCacheModel.commision = getCommision();

		detailTlpCacheModel.insuranceName = getInsuranceName();

		String insuranceName = detailTlpCacheModel.insuranceName;

		if ((insuranceName != null) && (insuranceName.length() == 0)) {
			detailTlpCacheModel.insuranceName = null;
		}

		detailTlpCacheModel.insurancePolicyNo = getInsurancePolicyNo();

		String insurancePolicyNo = detailTlpCacheModel.insurancePolicyNo;

		if ((insurancePolicyNo != null) && (insurancePolicyNo.length() == 0)) {
			detailTlpCacheModel.insurancePolicyNo = null;
		}

		detailTlpCacheModel.managedBy = getManagedBy();

		detailTlpCacheModel.agentCode = getAgentCode();

		String agentCode = detailTlpCacheModel.agentCode;

		if ((agentCode != null) && (agentCode.length() == 0)) {
			detailTlpCacheModel.agentCode = null;
		}

		detailTlpCacheModel.subAgent = getSubAgent();

		detailTlpCacheModel.marketingCode = getMarketingCode();

		String marketingCode = detailTlpCacheModel.marketingCode;

		if ((marketingCode != null) && (marketingCode.length() == 0)) {
			detailTlpCacheModel.marketingCode = null;
		}

		detailTlpCacheModel.utmSource = getUtmSource();

		String utmSource = detailTlpCacheModel.utmSource;

		if ((utmSource != null) && (utmSource.length() == 0)) {
			detailTlpCacheModel.utmSource = null;
		}

		detailTlpCacheModel.utmMedium = getUtmMedium();

		String utmMedium = detailTlpCacheModel.utmMedium;

		if ((utmMedium != null) && (utmMedium.length() == 0)) {
			detailTlpCacheModel.utmMedium = null;
		}

		detailTlpCacheModel.utmCampaign = getUtmCampaign();

		String utmCampaign = detailTlpCacheModel.utmCampaign;

		if ((utmCampaign != null) && (utmCampaign.length() == 0)) {
			detailTlpCacheModel.utmCampaign = null;
		}

		detailTlpCacheModel.utmTerm = getUtmTerm();

		String utmTerm = detailTlpCacheModel.utmTerm;

		if ((utmTerm != null) && (utmTerm.length() == 0)) {
			detailTlpCacheModel.utmTerm = null;
		}

		detailTlpCacheModel.utmContent = getUtmContent();

		String utmContent = detailTlpCacheModel.utmContent;

		if ((utmContent != null) && (utmContent.length() == 0)) {
			detailTlpCacheModel.utmContent = null;
		}

		detailTlpCacheModel.clickId = getClickId();

		String clickId = detailTlpCacheModel.clickId;

		if ((clickId != null) && (clickId.length() == 0)) {
			detailTlpCacheModel.clickId = null;
		}

		return detailTlpCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DetailTlp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DetailTlp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailTlp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DetailTlp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DetailTlp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DetailTlp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DetailTlp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DetailTlp)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DetailTlp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DetailTlp.class, ModelWrapper.class);

	}

	private long _detailTlpId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _startDate;
	private Date _expiredDate;
	private Date _mainPolicyStartDate;
	private Date _mainPolicyEndDate;
	private int _numberOfDays;
	private String _name;
	private String _birthPlace;
	private Date _dob;
	private String _nationality;
	private String _idNumber;
	private String _passportNumber;
	private String _kitasNumber;
	private String _mobilePhone;
	private String _email;
	private String _address;
	private String _address2;
	private String _province;
	private String _city;
	private String _postCode;
	private int _commercialOffer;
	private long _driveModel;
	private String _vehicleManufacture;
	private String _vehicleModel;
	private String _vehicleSubModel;
	private int _manufactureYear;
	private double _vehicleInsured;
	private String _regionPlate;
	private String _policeNumber;
	private String _chassisNumber;
	private String _engineNumber;
	private long _leadsId;
	private long _transactionId_;
	private String _businessModel;
	private String _channel;
	private String _promoCode;
	private int _step1;
	private String _policyNumber;
	private String _referenceNumber;
	private String _policyStatus;
	private String _packageName;
	private long _packageInfo;
	private double _rate;
	private String _currency_;
	private double _sumInsured;
	private double _policyCost;
	private double _stampDuty;
	private double _premium;
	private double _netPremium;
	private double _discount;
	private double _commision;
	private String _insuranceName;
	private String _insurancePolicyNo;
	private long _managedBy;
	private String _agentCode;
	private long _subAgent;
	private String _marketingCode;
	private String _utmSource;
	private String _utmMedium;
	private String _utmCampaign;
	private String _utmTerm;
	private String _utmContent;
	private String _clickId;

	public <T> T getColumnValue(String columnName) {
		Function<DetailTlp, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DetailTlp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("detailTlpId", _detailTlpId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("expiredDate", _expiredDate);
		_columnOriginalValues.put("mainPolicyStartDate", _mainPolicyStartDate);
		_columnOriginalValues.put("mainPolicyEndDate", _mainPolicyEndDate);
		_columnOriginalValues.put("numberOfDays", _numberOfDays);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("birthPlace", _birthPlace);
		_columnOriginalValues.put("dob", _dob);
		_columnOriginalValues.put("nationality", _nationality);
		_columnOriginalValues.put("idNumber", _idNumber);
		_columnOriginalValues.put("passportNumber", _passportNumber);
		_columnOriginalValues.put("kitasNumber", _kitasNumber);
		_columnOriginalValues.put("mobilePhone", _mobilePhone);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("address2", _address2);
		_columnOriginalValues.put("province", _province);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("postCode", _postCode);
		_columnOriginalValues.put("commercialOffer", _commercialOffer);
		_columnOriginalValues.put("driveModel", _driveModel);
		_columnOriginalValues.put("vehicleManufacture", _vehicleManufacture);
		_columnOriginalValues.put("vehicleModel", _vehicleModel);
		_columnOriginalValues.put("vehicleSubModel", _vehicleSubModel);
		_columnOriginalValues.put("manufactureYear", _manufactureYear);
		_columnOriginalValues.put("vehicleInsured", _vehicleInsured);
		_columnOriginalValues.put("regionPlate", _regionPlate);
		_columnOriginalValues.put("policeNumber", _policeNumber);
		_columnOriginalValues.put("chassisNumber", _chassisNumber);
		_columnOriginalValues.put("engineNumber", _engineNumber);
		_columnOriginalValues.put("leadsId", _leadsId);
		_columnOriginalValues.put("transactionId_", _transactionId_);
		_columnOriginalValues.put("businessModel", _businessModel);
		_columnOriginalValues.put("channel", _channel);
		_columnOriginalValues.put("promoCode", _promoCode);
		_columnOriginalValues.put("step1", _step1);
		_columnOriginalValues.put("policyNumber", _policyNumber);
		_columnOriginalValues.put("referenceNumber", _referenceNumber);
		_columnOriginalValues.put("policyStatus", _policyStatus);
		_columnOriginalValues.put("packageName", _packageName);
		_columnOriginalValues.put("packageInfo", _packageInfo);
		_columnOriginalValues.put("rate", _rate);
		_columnOriginalValues.put("currency_", _currency_);
		_columnOriginalValues.put("sumInsured", _sumInsured);
		_columnOriginalValues.put("policyCost", _policyCost);
		_columnOriginalValues.put("stampDuty", _stampDuty);
		_columnOriginalValues.put("premium", _premium);
		_columnOriginalValues.put("netPremium", _netPremium);
		_columnOriginalValues.put("discount", _discount);
		_columnOriginalValues.put("commision", _commision);
		_columnOriginalValues.put("insuranceName", _insuranceName);
		_columnOriginalValues.put("insurancePolicyNo", _insurancePolicyNo);
		_columnOriginalValues.put("managedBy", _managedBy);
		_columnOriginalValues.put("agentCode", _agentCode);
		_columnOriginalValues.put("subAgent", _subAgent);
		_columnOriginalValues.put("marketingCode", _marketingCode);
		_columnOriginalValues.put("utmSource", _utmSource);
		_columnOriginalValues.put("utmMedium", _utmMedium);
		_columnOriginalValues.put("utmCampaign", _utmCampaign);
		_columnOriginalValues.put("utmTerm", _utmTerm);
		_columnOriginalValues.put("utmContent", _utmContent);
		_columnOriginalValues.put("clickId", _clickId);
	}

	private transient Map<String, Object> _columnOriginalValues;
	private DetailTlp _escapedModel;

}