/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.leads.model.Payment;
import com.mypage.leads.model.PaymentModel;
import com.mypage.leads.model.PaymentSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Payment service. Represents a row in the &quot;Payment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PaymentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentImpl}.
 * </p>
 *
 * @author Gositus
 * @see PaymentImpl
 * @generated
 */
@JSON(strict = true)
public class PaymentModelImpl
	extends BaseModelImpl<Payment> implements PaymentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a payment model instance should use the <code>Payment</code> interface instead.
	 */
	public static final String TABLE_NAME = "Payment";

	public static final Object[][] TABLE_COLUMNS = {
		{"paymentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"TransactionId", Types.VARCHAR},
		{"SessionId", Types.VARCHAR}, {"LeadsId", Types.BIGINT},
		{"Amount", Types.DOUBLE}, {"Discount", Types.DOUBLE},
		{"DiscountAmount", Types.DOUBLE}, {"PaymentStatus", Types.VARCHAR},
		{"PaymentChannelId", Types.BIGINT}, {"LinkAjaRefNum", Types.VARCHAR},
		{"Tenor", Types.VARCHAR}, {"PaymentCode", Types.VARCHAR},
		{"PaymentMessage", Types.VARCHAR}, {"CreditCardType", Types.VARCHAR},
		{"TransactionDateTime", Types.TIMESTAMP},
		{"PaymentDateTime", Types.TIMESTAMP}, {"Bank", Types.VARCHAR},
		{"ManagedBy", Types.BIGINT}, {"ReportGenerated", Types.INTEGER},
		{"DailyReportGenerated", Types.INTEGER},
		{"WeeklyReportGenerated", Types.INTEGER},
		{"MonthlyReportGenerated", Types.INTEGER},
		{"CheckStatusCounter", Types.INTEGER}, {"UserCreditId", Types.BIGINT},
		{"CreditPaymentStatus", Types.VARCHAR},
		{"CreditTransactionId", Types.VARCHAR},
		{"CreditPaymentDate", Types.TIMESTAMP},
		{"CreditPaymentChannelId", Types.BIGINT}, {"CreditBank", Types.VARCHAR},
		{"CreditPaymentCode", Types.VARCHAR},
		{"CreditPaymentMessage", Types.VARCHAR},
		{"ReportSettlementGenerated", Types.INTEGER},
		{"CreditSettlementAttachmentId", Types.BIGINT}, {"UtmId", Types.BIGINT},
		{"Sojern", Types.INTEGER}, {"InvolveAsia", Types.INTEGER},
		{"Ada", Types.INTEGER}, {"Active", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("paymentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("TransactionId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SessionId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LeadsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Amount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("Discount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("DiscountAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("PaymentStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PaymentChannelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("LinkAjaRefNum", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Tenor", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PaymentCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PaymentMessage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreditCardType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TransactionDateTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("PaymentDateTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Bank", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ManagedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ReportGenerated", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DailyReportGenerated", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("WeeklyReportGenerated", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("MonthlyReportGenerated", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("CheckStatusCounter", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("UserCreditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CreditPaymentStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreditTransactionId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreditPaymentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreditPaymentChannelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CreditBank", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreditPaymentCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreditPaymentMessage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ReportSettlementGenerated", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("CreditSettlementAttachmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("UtmId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Sojern", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("InvolveAsia", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Ada", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Active", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Payment (paymentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,TransactionId VARCHAR(75) null,SessionId VARCHAR(75) null,LeadsId LONG,Amount DOUBLE,Discount DOUBLE,DiscountAmount DOUBLE,PaymentStatus VARCHAR(75) null,PaymentChannelId LONG,LinkAjaRefNum VARCHAR(75) null,Tenor VARCHAR(75) null,PaymentCode VARCHAR(75) null,PaymentMessage VARCHAR(75) null,CreditCardType VARCHAR(75) null,TransactionDateTime DATE null,PaymentDateTime DATE null,Bank VARCHAR(75) null,ManagedBy LONG,ReportGenerated INTEGER,DailyReportGenerated INTEGER,WeeklyReportGenerated INTEGER,MonthlyReportGenerated INTEGER,CheckStatusCounter INTEGER,UserCreditId LONG,CreditPaymentStatus VARCHAR(75) null,CreditTransactionId VARCHAR(75) null,CreditPaymentDate DATE null,CreditPaymentChannelId LONG,CreditBank VARCHAR(75) null,CreditPaymentCode VARCHAR(75) null,CreditPaymentMessage VARCHAR(75) null,ReportSettlementGenerated INTEGER,CreditSettlementAttachmentId LONG,UtmId LONG,Sojern INTEGER,InvolveAsia INTEGER,Ada INTEGER,Active INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table Payment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY payment.paymentId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Payment.paymentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LEADSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRANSACTIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PAYMENTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Payment toModel(PaymentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Payment model = new PaymentImpl();

		model.setPaymentId(soapModel.getPaymentId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTransactionId(soapModel.getTransactionId());
		model.setSessionId(soapModel.getSessionId());
		model.setLeadsId(soapModel.getLeadsId());
		model.setAmount(soapModel.getAmount());
		model.setDiscount(soapModel.getDiscount());
		model.setDiscountAmount(soapModel.getDiscountAmount());
		model.setPaymentStatus(soapModel.getPaymentStatus());
		model.setPaymentChannelId(soapModel.getPaymentChannelId());
		model.setLinkAjaRefNum(soapModel.getLinkAjaRefNum());
		model.setTenor(soapModel.getTenor());
		model.setPaymentCode(soapModel.getPaymentCode());
		model.setPaymentMessage(soapModel.getPaymentMessage());
		model.setCreditCardType(soapModel.getCreditCardType());
		model.setTransactionDateTime(soapModel.getTransactionDateTime());
		model.setPaymentDateTime(soapModel.getPaymentDateTime());
		model.setBank(soapModel.getBank());
		model.setManagedBy(soapModel.getManagedBy());
		model.setReportGenerated(soapModel.getReportGenerated());
		model.setDailyReportGenerated(soapModel.getDailyReportGenerated());
		model.setWeeklyReportGenerated(soapModel.getWeeklyReportGenerated());
		model.setMonthlyReportGenerated(soapModel.getMonthlyReportGenerated());
		model.setCheckStatusCounter(soapModel.getCheckStatusCounter());
		model.setUserCreditId(soapModel.getUserCreditId());
		model.setCreditPaymentStatus(soapModel.getCreditPaymentStatus());
		model.setCreditTransactionId(soapModel.getCreditTransactionId());
		model.setCreditPaymentDate(soapModel.getCreditPaymentDate());
		model.setCreditPaymentChannelId(soapModel.getCreditPaymentChannelId());
		model.setCreditBank(soapModel.getCreditBank());
		model.setCreditPaymentCode(soapModel.getCreditPaymentCode());
		model.setCreditPaymentMessage(soapModel.getCreditPaymentMessage());
		model.setReportSettlementGenerated(
			soapModel.getReportSettlementGenerated());
		model.setCreditSettlementAttachmentId(
			soapModel.getCreditSettlementAttachmentId());
		model.setUtmId(soapModel.getUtmId());
		model.setSojern(soapModel.getSojern());
		model.setInvolveAsia(soapModel.getInvolveAsia());
		model.setAda(soapModel.getAda());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Payment> toModels(PaymentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Payment> models = new ArrayList<Payment>(soapModels.length);

		for (PaymentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PaymentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _paymentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPaymentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _paymentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Payment.class;
	}

	@Override
	public String getModelClassName() {
		return Payment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Payment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Payment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Payment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Payment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Payment, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Payment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Payment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Payment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Payment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Payment, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Payment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Payment, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Payment, Object>>();
		Map<String, BiConsumer<Payment, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Payment, ?>>();

		attributeGetterFunctions.put("paymentId", Payment::getPaymentId);
		attributeSetterBiConsumers.put(
			"paymentId", (BiConsumer<Payment, Long>)Payment::setPaymentId);
		attributeGetterFunctions.put("groupId", Payment::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Payment, Long>)Payment::setGroupId);
		attributeGetterFunctions.put("companyId", Payment::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Payment, Long>)Payment::setCompanyId);
		attributeGetterFunctions.put("userId", Payment::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Payment, Long>)Payment::setUserId);
		attributeGetterFunctions.put("userName", Payment::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Payment, String>)Payment::setUserName);
		attributeGetterFunctions.put("createDate", Payment::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Payment, Date>)Payment::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Payment::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Payment, Date>)Payment::setModifiedDate);
		attributeGetterFunctions.put(
			"TransactionId", Payment::getTransactionId);
		attributeSetterBiConsumers.put(
			"TransactionId",
			(BiConsumer<Payment, String>)Payment::setTransactionId);
		attributeGetterFunctions.put("SessionId", Payment::getSessionId);
		attributeSetterBiConsumers.put(
			"SessionId", (BiConsumer<Payment, String>)Payment::setSessionId);
		attributeGetterFunctions.put("LeadsId", Payment::getLeadsId);
		attributeSetterBiConsumers.put(
			"LeadsId", (BiConsumer<Payment, Long>)Payment::setLeadsId);
		attributeGetterFunctions.put("Amount", Payment::getAmount);
		attributeSetterBiConsumers.put(
			"Amount", (BiConsumer<Payment, Double>)Payment::setAmount);
		attributeGetterFunctions.put("Discount", Payment::getDiscount);
		attributeSetterBiConsumers.put(
			"Discount", (BiConsumer<Payment, Double>)Payment::setDiscount);
		attributeGetterFunctions.put(
			"DiscountAmount", Payment::getDiscountAmount);
		attributeSetterBiConsumers.put(
			"DiscountAmount",
			(BiConsumer<Payment, Double>)Payment::setDiscountAmount);
		attributeGetterFunctions.put(
			"PaymentStatus", Payment::getPaymentStatus);
		attributeSetterBiConsumers.put(
			"PaymentStatus",
			(BiConsumer<Payment, String>)Payment::setPaymentStatus);
		attributeGetterFunctions.put(
			"PaymentChannelId", Payment::getPaymentChannelId);
		attributeSetterBiConsumers.put(
			"PaymentChannelId",
			(BiConsumer<Payment, Long>)Payment::setPaymentChannelId);
		attributeGetterFunctions.put(
			"LinkAjaRefNum", Payment::getLinkAjaRefNum);
		attributeSetterBiConsumers.put(
			"LinkAjaRefNum",
			(BiConsumer<Payment, String>)Payment::setLinkAjaRefNum);
		attributeGetterFunctions.put("Tenor", Payment::getTenor);
		attributeSetterBiConsumers.put(
			"Tenor", (BiConsumer<Payment, String>)Payment::setTenor);
		attributeGetterFunctions.put("PaymentCode", Payment::getPaymentCode);
		attributeSetterBiConsumers.put(
			"PaymentCode",
			(BiConsumer<Payment, String>)Payment::setPaymentCode);
		attributeGetterFunctions.put(
			"PaymentMessage", Payment::getPaymentMessage);
		attributeSetterBiConsumers.put(
			"PaymentMessage",
			(BiConsumer<Payment, String>)Payment::setPaymentMessage);
		attributeGetterFunctions.put(
			"CreditCardType", Payment::getCreditCardType);
		attributeSetterBiConsumers.put(
			"CreditCardType",
			(BiConsumer<Payment, String>)Payment::setCreditCardType);
		attributeGetterFunctions.put(
			"TransactionDateTime", Payment::getTransactionDateTime);
		attributeSetterBiConsumers.put(
			"TransactionDateTime",
			(BiConsumer<Payment, Date>)Payment::setTransactionDateTime);
		attributeGetterFunctions.put(
			"PaymentDateTime", Payment::getPaymentDateTime);
		attributeSetterBiConsumers.put(
			"PaymentDateTime",
			(BiConsumer<Payment, Date>)Payment::setPaymentDateTime);
		attributeGetterFunctions.put("Bank", Payment::getBank);
		attributeSetterBiConsumers.put(
			"Bank", (BiConsumer<Payment, String>)Payment::setBank);
		attributeGetterFunctions.put("ManagedBy", Payment::getManagedBy);
		attributeSetterBiConsumers.put(
			"ManagedBy", (BiConsumer<Payment, Long>)Payment::setManagedBy);
		attributeGetterFunctions.put(
			"ReportGenerated", Payment::getReportGenerated);
		attributeSetterBiConsumers.put(
			"ReportGenerated",
			(BiConsumer<Payment, Integer>)Payment::setReportGenerated);
		attributeGetterFunctions.put(
			"DailyReportGenerated", Payment::getDailyReportGenerated);
		attributeSetterBiConsumers.put(
			"DailyReportGenerated",
			(BiConsumer<Payment, Integer>)Payment::setDailyReportGenerated);
		attributeGetterFunctions.put(
			"WeeklyReportGenerated", Payment::getWeeklyReportGenerated);
		attributeSetterBiConsumers.put(
			"WeeklyReportGenerated",
			(BiConsumer<Payment, Integer>)Payment::setWeeklyReportGenerated);
		attributeGetterFunctions.put(
			"MonthlyReportGenerated", Payment::getMonthlyReportGenerated);
		attributeSetterBiConsumers.put(
			"MonthlyReportGenerated",
			(BiConsumer<Payment, Integer>)Payment::setMonthlyReportGenerated);
		attributeGetterFunctions.put(
			"CheckStatusCounter", Payment::getCheckStatusCounter);
		attributeSetterBiConsumers.put(
			"CheckStatusCounter",
			(BiConsumer<Payment, Integer>)Payment::setCheckStatusCounter);
		attributeGetterFunctions.put("UserCreditId", Payment::getUserCreditId);
		attributeSetterBiConsumers.put(
			"UserCreditId",
			(BiConsumer<Payment, Long>)Payment::setUserCreditId);
		attributeGetterFunctions.put(
			"CreditPaymentStatus", Payment::getCreditPaymentStatus);
		attributeSetterBiConsumers.put(
			"CreditPaymentStatus",
			(BiConsumer<Payment, String>)Payment::setCreditPaymentStatus);
		attributeGetterFunctions.put(
			"CreditTransactionId", Payment::getCreditTransactionId);
		attributeSetterBiConsumers.put(
			"CreditTransactionId",
			(BiConsumer<Payment, String>)Payment::setCreditTransactionId);
		attributeGetterFunctions.put(
			"CreditPaymentDate", Payment::getCreditPaymentDate);
		attributeSetterBiConsumers.put(
			"CreditPaymentDate",
			(BiConsumer<Payment, Date>)Payment::setCreditPaymentDate);
		attributeGetterFunctions.put(
			"CreditPaymentChannelId", Payment::getCreditPaymentChannelId);
		attributeSetterBiConsumers.put(
			"CreditPaymentChannelId",
			(BiConsumer<Payment, Long>)Payment::setCreditPaymentChannelId);
		attributeGetterFunctions.put("CreditBank", Payment::getCreditBank);
		attributeSetterBiConsumers.put(
			"CreditBank", (BiConsumer<Payment, String>)Payment::setCreditBank);
		attributeGetterFunctions.put(
			"CreditPaymentCode", Payment::getCreditPaymentCode);
		attributeSetterBiConsumers.put(
			"CreditPaymentCode",
			(BiConsumer<Payment, String>)Payment::setCreditPaymentCode);
		attributeGetterFunctions.put(
			"CreditPaymentMessage", Payment::getCreditPaymentMessage);
		attributeSetterBiConsumers.put(
			"CreditPaymentMessage",
			(BiConsumer<Payment, String>)Payment::setCreditPaymentMessage);
		attributeGetterFunctions.put(
			"ReportSettlementGenerated", Payment::getReportSettlementGenerated);
		attributeSetterBiConsumers.put(
			"ReportSettlementGenerated",
			(BiConsumer<Payment, Integer>)
				Payment::setReportSettlementGenerated);
		attributeGetterFunctions.put(
			"CreditSettlementAttachmentId",
			Payment::getCreditSettlementAttachmentId);
		attributeSetterBiConsumers.put(
			"CreditSettlementAttachmentId",
			(BiConsumer<Payment, Long>)
				Payment::setCreditSettlementAttachmentId);
		attributeGetterFunctions.put("UtmId", Payment::getUtmId);
		attributeSetterBiConsumers.put(
			"UtmId", (BiConsumer<Payment, Long>)Payment::setUtmId);
		attributeGetterFunctions.put("Sojern", Payment::getSojern);
		attributeSetterBiConsumers.put(
			"Sojern", (BiConsumer<Payment, Integer>)Payment::setSojern);
		attributeGetterFunctions.put("InvolveAsia", Payment::getInvolveAsia);
		attributeSetterBiConsumers.put(
			"InvolveAsia",
			(BiConsumer<Payment, Integer>)Payment::setInvolveAsia);
		attributeGetterFunctions.put("Ada", Payment::getAda);
		attributeSetterBiConsumers.put(
			"Ada", (BiConsumer<Payment, Integer>)Payment::setAda);
		attributeGetterFunctions.put("Active", Payment::getActive);
		attributeSetterBiConsumers.put(
			"Active", (BiConsumer<Payment, Integer>)Payment::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPaymentId() {
		return _paymentId;
	}

	@Override
	public void setPaymentId(long paymentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentId = paymentId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTransactionId() {
		if (_TransactionId == null) {
			return "";
		}
		else {
			return _TransactionId;
		}
	}

	@Override
	public void setTransactionId(String TransactionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TransactionId = TransactionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTransactionId() {
		return getColumnOriginalValue("TransactionId");
	}

	@JSON
	@Override
	public String getSessionId() {
		if (_SessionId == null) {
			return "";
		}
		else {
			return _SessionId;
		}
	}

	@Override
	public void setSessionId(String SessionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_SessionId = SessionId;
	}

	@JSON
	@Override
	public long getLeadsId() {
		return _LeadsId;
	}

	@Override
	public void setLeadsId(long LeadsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_LeadsId = LeadsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLeadsId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("LeadsId"));
	}

	@JSON
	@Override
	public double getAmount() {
		return _Amount;
	}

	@Override
	public void setAmount(double Amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Amount = Amount;
	}

	@JSON
	@Override
	public double getDiscount() {
		return _Discount;
	}

	@Override
	public void setDiscount(double Discount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Discount = Discount;
	}

	@JSON
	@Override
	public double getDiscountAmount() {
		return _DiscountAmount;
	}

	@Override
	public void setDiscountAmount(double DiscountAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DiscountAmount = DiscountAmount;
	}

	@JSON
	@Override
	public String getPaymentStatus() {
		if (_PaymentStatus == null) {
			return "";
		}
		else {
			return _PaymentStatus;
		}
	}

	@Override
	public void setPaymentStatus(String PaymentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PaymentStatus = PaymentStatus;
	}

	@JSON
	@Override
	public long getPaymentChannelId() {
		return _PaymentChannelId;
	}

	@Override
	public void setPaymentChannelId(long PaymentChannelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PaymentChannelId = PaymentChannelId;
	}

	@JSON
	@Override
	public String getLinkAjaRefNum() {
		if (_LinkAjaRefNum == null) {
			return "";
		}
		else {
			return _LinkAjaRefNum;
		}
	}

	@Override
	public void setLinkAjaRefNum(String LinkAjaRefNum) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_LinkAjaRefNum = LinkAjaRefNum;
	}

	@JSON
	@Override
	public String getTenor() {
		if (_Tenor == null) {
			return "";
		}
		else {
			return _Tenor;
		}
	}

	@Override
	public void setTenor(String Tenor) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tenor = Tenor;
	}

	@JSON
	@Override
	public String getPaymentCode() {
		if (_PaymentCode == null) {
			return "";
		}
		else {
			return _PaymentCode;
		}
	}

	@Override
	public void setPaymentCode(String PaymentCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PaymentCode = PaymentCode;
	}

	@JSON
	@Override
	public String getPaymentMessage() {
		if (_PaymentMessage == null) {
			return "";
		}
		else {
			return _PaymentMessage;
		}
	}

	@Override
	public void setPaymentMessage(String PaymentMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PaymentMessage = PaymentMessage;
	}

	@JSON
	@Override
	public String getCreditCardType() {
		if (_CreditCardType == null) {
			return "";
		}
		else {
			return _CreditCardType;
		}
	}

	@Override
	public void setCreditCardType(String CreditCardType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditCardType = CreditCardType;
	}

	@JSON
	@Override
	public Date getTransactionDateTime() {
		return _TransactionDateTime;
	}

	@Override
	public void setTransactionDateTime(Date TransactionDateTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TransactionDateTime = TransactionDateTime;
	}

	@JSON
	@Override
	public Date getPaymentDateTime() {
		return _PaymentDateTime;
	}

	@Override
	public void setPaymentDateTime(Date PaymentDateTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PaymentDateTime = PaymentDateTime;
	}

	@JSON
	@Override
	public String getBank() {
		if (_Bank == null) {
			return "";
		}
		else {
			return _Bank;
		}
	}

	@Override
	public void setBank(String Bank) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Bank = Bank;
	}

	@JSON
	@Override
	public long getManagedBy() {
		return _ManagedBy;
	}

	@Override
	public void setManagedBy(long ManagedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ManagedBy = ManagedBy;
	}

	@JSON
	@Override
	public int getReportGenerated() {
		return _ReportGenerated;
	}

	@Override
	public void setReportGenerated(int ReportGenerated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReportGenerated = ReportGenerated;
	}

	@JSON
	@Override
	public int getDailyReportGenerated() {
		return _DailyReportGenerated;
	}

	@Override
	public void setDailyReportGenerated(int DailyReportGenerated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DailyReportGenerated = DailyReportGenerated;
	}

	@JSON
	@Override
	public int getWeeklyReportGenerated() {
		return _WeeklyReportGenerated;
	}

	@Override
	public void setWeeklyReportGenerated(int WeeklyReportGenerated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_WeeklyReportGenerated = WeeklyReportGenerated;
	}

	@JSON
	@Override
	public int getMonthlyReportGenerated() {
		return _MonthlyReportGenerated;
	}

	@Override
	public void setMonthlyReportGenerated(int MonthlyReportGenerated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_MonthlyReportGenerated = MonthlyReportGenerated;
	}

	@JSON
	@Override
	public int getCheckStatusCounter() {
		return _CheckStatusCounter;
	}

	@Override
	public void setCheckStatusCounter(int CheckStatusCounter) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CheckStatusCounter = CheckStatusCounter;
	}

	@JSON
	@Override
	public long getUserCreditId() {
		return _UserCreditId;
	}

	@Override
	public void setUserCreditId(long UserCreditId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_UserCreditId = UserCreditId;
	}

	@JSON
	@Override
	public String getCreditPaymentStatus() {
		if (_CreditPaymentStatus == null) {
			return "";
		}
		else {
			return _CreditPaymentStatus;
		}
	}

	@Override
	public void setCreditPaymentStatus(String CreditPaymentStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditPaymentStatus = CreditPaymentStatus;
	}

	@JSON
	@Override
	public String getCreditTransactionId() {
		if (_CreditTransactionId == null) {
			return "";
		}
		else {
			return _CreditTransactionId;
		}
	}

	@Override
	public void setCreditTransactionId(String CreditTransactionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditTransactionId = CreditTransactionId;
	}

	@JSON
	@Override
	public Date getCreditPaymentDate() {
		return _CreditPaymentDate;
	}

	@Override
	public void setCreditPaymentDate(Date CreditPaymentDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditPaymentDate = CreditPaymentDate;
	}

	@JSON
	@Override
	public long getCreditPaymentChannelId() {
		return _CreditPaymentChannelId;
	}

	@Override
	public void setCreditPaymentChannelId(long CreditPaymentChannelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditPaymentChannelId = CreditPaymentChannelId;
	}

	@JSON
	@Override
	public String getCreditBank() {
		if (_CreditBank == null) {
			return "";
		}
		else {
			return _CreditBank;
		}
	}

	@Override
	public void setCreditBank(String CreditBank) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditBank = CreditBank;
	}

	@JSON
	@Override
	public String getCreditPaymentCode() {
		if (_CreditPaymentCode == null) {
			return "";
		}
		else {
			return _CreditPaymentCode;
		}
	}

	@Override
	public void setCreditPaymentCode(String CreditPaymentCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditPaymentCode = CreditPaymentCode;
	}

	@JSON
	@Override
	public String getCreditPaymentMessage() {
		if (_CreditPaymentMessage == null) {
			return "";
		}
		else {
			return _CreditPaymentMessage;
		}
	}

	@Override
	public void setCreditPaymentMessage(String CreditPaymentMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditPaymentMessage = CreditPaymentMessage;
	}

	@JSON
	@Override
	public int getReportSettlementGenerated() {
		return _ReportSettlementGenerated;
	}

	@Override
	public void setReportSettlementGenerated(int ReportSettlementGenerated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReportSettlementGenerated = ReportSettlementGenerated;
	}

	@JSON
	@Override
	public long getCreditSettlementAttachmentId() {
		return _CreditSettlementAttachmentId;
	}

	@Override
	public void setCreditSettlementAttachmentId(
		long CreditSettlementAttachmentId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreditSettlementAttachmentId = CreditSettlementAttachmentId;
	}

	@JSON
	@Override
	public long getUtmId() {
		return _UtmId;
	}

	@Override
	public void setUtmId(long UtmId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_UtmId = UtmId;
	}

	@JSON
	@Override
	public int getSojern() {
		return _Sojern;
	}

	@Override
	public void setSojern(int Sojern) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Sojern = Sojern;
	}

	@JSON
	@Override
	public int getInvolveAsia() {
		return _InvolveAsia;
	}

	@Override
	public void setInvolveAsia(int InvolveAsia) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_InvolveAsia = InvolveAsia;
	}

	@JSON
	@Override
	public int getAda() {
		return _Ada;
	}

	@Override
	public void setAda(int Ada) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Ada = Ada;
	}

	@JSON
	@Override
	public int getActive() {
		return _Active;
	}

	@Override
	public void setActive(int Active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Active = Active;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Payment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Payment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Payment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PaymentImpl paymentImpl = new PaymentImpl();

		paymentImpl.setPaymentId(getPaymentId());
		paymentImpl.setGroupId(getGroupId());
		paymentImpl.setCompanyId(getCompanyId());
		paymentImpl.setUserId(getUserId());
		paymentImpl.setUserName(getUserName());
		paymentImpl.setCreateDate(getCreateDate());
		paymentImpl.setModifiedDate(getModifiedDate());
		paymentImpl.setTransactionId(getTransactionId());
		paymentImpl.setSessionId(getSessionId());
		paymentImpl.setLeadsId(getLeadsId());
		paymentImpl.setAmount(getAmount());
		paymentImpl.setDiscount(getDiscount());
		paymentImpl.setDiscountAmount(getDiscountAmount());
		paymentImpl.setPaymentStatus(getPaymentStatus());
		paymentImpl.setPaymentChannelId(getPaymentChannelId());
		paymentImpl.setLinkAjaRefNum(getLinkAjaRefNum());
		paymentImpl.setTenor(getTenor());
		paymentImpl.setPaymentCode(getPaymentCode());
		paymentImpl.setPaymentMessage(getPaymentMessage());
		paymentImpl.setCreditCardType(getCreditCardType());
		paymentImpl.setTransactionDateTime(getTransactionDateTime());
		paymentImpl.setPaymentDateTime(getPaymentDateTime());
		paymentImpl.setBank(getBank());
		paymentImpl.setManagedBy(getManagedBy());
		paymentImpl.setReportGenerated(getReportGenerated());
		paymentImpl.setDailyReportGenerated(getDailyReportGenerated());
		paymentImpl.setWeeklyReportGenerated(getWeeklyReportGenerated());
		paymentImpl.setMonthlyReportGenerated(getMonthlyReportGenerated());
		paymentImpl.setCheckStatusCounter(getCheckStatusCounter());
		paymentImpl.setUserCreditId(getUserCreditId());
		paymentImpl.setCreditPaymentStatus(getCreditPaymentStatus());
		paymentImpl.setCreditTransactionId(getCreditTransactionId());
		paymentImpl.setCreditPaymentDate(getCreditPaymentDate());
		paymentImpl.setCreditPaymentChannelId(getCreditPaymentChannelId());
		paymentImpl.setCreditBank(getCreditBank());
		paymentImpl.setCreditPaymentCode(getCreditPaymentCode());
		paymentImpl.setCreditPaymentMessage(getCreditPaymentMessage());
		paymentImpl.setReportSettlementGenerated(
			getReportSettlementGenerated());
		paymentImpl.setCreditSettlementAttachmentId(
			getCreditSettlementAttachmentId());
		paymentImpl.setUtmId(getUtmId());
		paymentImpl.setSojern(getSojern());
		paymentImpl.setInvolveAsia(getInvolveAsia());
		paymentImpl.setAda(getAda());
		paymentImpl.setActive(getActive());

		paymentImpl.resetOriginalValues();

		return paymentImpl;
	}

	@Override
	public int compareTo(Payment payment) {
		long primaryKey = payment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Payment)) {
			return false;
		}

		Payment payment = (Payment)object;

		long primaryKey = payment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Payment> toCacheModel() {
		PaymentCacheModel paymentCacheModel = new PaymentCacheModel();

		paymentCacheModel.paymentId = getPaymentId();

		paymentCacheModel.groupId = getGroupId();

		paymentCacheModel.companyId = getCompanyId();

		paymentCacheModel.userId = getUserId();

		paymentCacheModel.userName = getUserName();

		String userName = paymentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			paymentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			paymentCacheModel.createDate = createDate.getTime();
		}
		else {
			paymentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			paymentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			paymentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		paymentCacheModel.TransactionId = getTransactionId();

		String TransactionId = paymentCacheModel.TransactionId;

		if ((TransactionId != null) && (TransactionId.length() == 0)) {
			paymentCacheModel.TransactionId = null;
		}

		paymentCacheModel.SessionId = getSessionId();

		String SessionId = paymentCacheModel.SessionId;

		if ((SessionId != null) && (SessionId.length() == 0)) {
			paymentCacheModel.SessionId = null;
		}

		paymentCacheModel.LeadsId = getLeadsId();

		paymentCacheModel.Amount = getAmount();

		paymentCacheModel.Discount = getDiscount();

		paymentCacheModel.DiscountAmount = getDiscountAmount();

		paymentCacheModel.PaymentStatus = getPaymentStatus();

		String PaymentStatus = paymentCacheModel.PaymentStatus;

		if ((PaymentStatus != null) && (PaymentStatus.length() == 0)) {
			paymentCacheModel.PaymentStatus = null;
		}

		paymentCacheModel.PaymentChannelId = getPaymentChannelId();

		paymentCacheModel.LinkAjaRefNum = getLinkAjaRefNum();

		String LinkAjaRefNum = paymentCacheModel.LinkAjaRefNum;

		if ((LinkAjaRefNum != null) && (LinkAjaRefNum.length() == 0)) {
			paymentCacheModel.LinkAjaRefNum = null;
		}

		paymentCacheModel.Tenor = getTenor();

		String Tenor = paymentCacheModel.Tenor;

		if ((Tenor != null) && (Tenor.length() == 0)) {
			paymentCacheModel.Tenor = null;
		}

		paymentCacheModel.PaymentCode = getPaymentCode();

		String PaymentCode = paymentCacheModel.PaymentCode;

		if ((PaymentCode != null) && (PaymentCode.length() == 0)) {
			paymentCacheModel.PaymentCode = null;
		}

		paymentCacheModel.PaymentMessage = getPaymentMessage();

		String PaymentMessage = paymentCacheModel.PaymentMessage;

		if ((PaymentMessage != null) && (PaymentMessage.length() == 0)) {
			paymentCacheModel.PaymentMessage = null;
		}

		paymentCacheModel.CreditCardType = getCreditCardType();

		String CreditCardType = paymentCacheModel.CreditCardType;

		if ((CreditCardType != null) && (CreditCardType.length() == 0)) {
			paymentCacheModel.CreditCardType = null;
		}

		Date TransactionDateTime = getTransactionDateTime();

		if (TransactionDateTime != null) {
			paymentCacheModel.TransactionDateTime =
				TransactionDateTime.getTime();
		}
		else {
			paymentCacheModel.TransactionDateTime = Long.MIN_VALUE;
		}

		Date PaymentDateTime = getPaymentDateTime();

		if (PaymentDateTime != null) {
			paymentCacheModel.PaymentDateTime = PaymentDateTime.getTime();
		}
		else {
			paymentCacheModel.PaymentDateTime = Long.MIN_VALUE;
		}

		paymentCacheModel.Bank = getBank();

		String Bank = paymentCacheModel.Bank;

		if ((Bank != null) && (Bank.length() == 0)) {
			paymentCacheModel.Bank = null;
		}

		paymentCacheModel.ManagedBy = getManagedBy();

		paymentCacheModel.ReportGenerated = getReportGenerated();

		paymentCacheModel.DailyReportGenerated = getDailyReportGenerated();

		paymentCacheModel.WeeklyReportGenerated = getWeeklyReportGenerated();

		paymentCacheModel.MonthlyReportGenerated = getMonthlyReportGenerated();

		paymentCacheModel.CheckStatusCounter = getCheckStatusCounter();

		paymentCacheModel.UserCreditId = getUserCreditId();

		paymentCacheModel.CreditPaymentStatus = getCreditPaymentStatus();

		String CreditPaymentStatus = paymentCacheModel.CreditPaymentStatus;

		if ((CreditPaymentStatus != null) &&
			(CreditPaymentStatus.length() == 0)) {

			paymentCacheModel.CreditPaymentStatus = null;
		}

		paymentCacheModel.CreditTransactionId = getCreditTransactionId();

		String CreditTransactionId = paymentCacheModel.CreditTransactionId;

		if ((CreditTransactionId != null) &&
			(CreditTransactionId.length() == 0)) {

			paymentCacheModel.CreditTransactionId = null;
		}

		Date CreditPaymentDate = getCreditPaymentDate();

		if (CreditPaymentDate != null) {
			paymentCacheModel.CreditPaymentDate = CreditPaymentDate.getTime();
		}
		else {
			paymentCacheModel.CreditPaymentDate = Long.MIN_VALUE;
		}

		paymentCacheModel.CreditPaymentChannelId = getCreditPaymentChannelId();

		paymentCacheModel.CreditBank = getCreditBank();

		String CreditBank = paymentCacheModel.CreditBank;

		if ((CreditBank != null) && (CreditBank.length() == 0)) {
			paymentCacheModel.CreditBank = null;
		}

		paymentCacheModel.CreditPaymentCode = getCreditPaymentCode();

		String CreditPaymentCode = paymentCacheModel.CreditPaymentCode;

		if ((CreditPaymentCode != null) && (CreditPaymentCode.length() == 0)) {
			paymentCacheModel.CreditPaymentCode = null;
		}

		paymentCacheModel.CreditPaymentMessage = getCreditPaymentMessage();

		String CreditPaymentMessage = paymentCacheModel.CreditPaymentMessage;

		if ((CreditPaymentMessage != null) &&
			(CreditPaymentMessage.length() == 0)) {

			paymentCacheModel.CreditPaymentMessage = null;
		}

		paymentCacheModel.ReportSettlementGenerated =
			getReportSettlementGenerated();

		paymentCacheModel.CreditSettlementAttachmentId =
			getCreditSettlementAttachmentId();

		paymentCacheModel.UtmId = getUtmId();

		paymentCacheModel.Sojern = getSojern();

		paymentCacheModel.InvolveAsia = getInvolveAsia();

		paymentCacheModel.Ada = getAda();

		paymentCacheModel.Active = getActive();

		return paymentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Payment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Payment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Payment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Payment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Payment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Payment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Payment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Payment)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Payment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Payment.class, ModelWrapper.class);

	}

	private long _paymentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _TransactionId;
	private String _SessionId;
	private long _LeadsId;
	private double _Amount;
	private double _Discount;
	private double _DiscountAmount;
	private String _PaymentStatus;
	private long _PaymentChannelId;
	private String _LinkAjaRefNum;
	private String _Tenor;
	private String _PaymentCode;
	private String _PaymentMessage;
	private String _CreditCardType;
	private Date _TransactionDateTime;
	private Date _PaymentDateTime;
	private String _Bank;
	private long _ManagedBy;
	private int _ReportGenerated;
	private int _DailyReportGenerated;
	private int _WeeklyReportGenerated;
	private int _MonthlyReportGenerated;
	private int _CheckStatusCounter;
	private long _UserCreditId;
	private String _CreditPaymentStatus;
	private String _CreditTransactionId;
	private Date _CreditPaymentDate;
	private long _CreditPaymentChannelId;
	private String _CreditBank;
	private String _CreditPaymentCode;
	private String _CreditPaymentMessage;
	private int _ReportSettlementGenerated;
	private long _CreditSettlementAttachmentId;
	private long _UtmId;
	private int _Sojern;
	private int _InvolveAsia;
	private int _Ada;
	private int _Active;

	public <T> T getColumnValue(String columnName) {
		Function<Payment, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Payment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("paymentId", _paymentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("TransactionId", _TransactionId);
		_columnOriginalValues.put("SessionId", _SessionId);
		_columnOriginalValues.put("LeadsId", _LeadsId);
		_columnOriginalValues.put("Amount", _Amount);
		_columnOriginalValues.put("Discount", _Discount);
		_columnOriginalValues.put("DiscountAmount", _DiscountAmount);
		_columnOriginalValues.put("PaymentStatus", _PaymentStatus);
		_columnOriginalValues.put("PaymentChannelId", _PaymentChannelId);
		_columnOriginalValues.put("LinkAjaRefNum", _LinkAjaRefNum);
		_columnOriginalValues.put("Tenor", _Tenor);
		_columnOriginalValues.put("PaymentCode", _PaymentCode);
		_columnOriginalValues.put("PaymentMessage", _PaymentMessage);
		_columnOriginalValues.put("CreditCardType", _CreditCardType);
		_columnOriginalValues.put("TransactionDateTime", _TransactionDateTime);
		_columnOriginalValues.put("PaymentDateTime", _PaymentDateTime);
		_columnOriginalValues.put("Bank", _Bank);
		_columnOriginalValues.put("ManagedBy", _ManagedBy);
		_columnOriginalValues.put("ReportGenerated", _ReportGenerated);
		_columnOriginalValues.put(
			"DailyReportGenerated", _DailyReportGenerated);
		_columnOriginalValues.put(
			"WeeklyReportGenerated", _WeeklyReportGenerated);
		_columnOriginalValues.put(
			"MonthlyReportGenerated", _MonthlyReportGenerated);
		_columnOriginalValues.put("CheckStatusCounter", _CheckStatusCounter);
		_columnOriginalValues.put("UserCreditId", _UserCreditId);
		_columnOriginalValues.put("CreditPaymentStatus", _CreditPaymentStatus);
		_columnOriginalValues.put("CreditTransactionId", _CreditTransactionId);
		_columnOriginalValues.put("CreditPaymentDate", _CreditPaymentDate);
		_columnOriginalValues.put(
			"CreditPaymentChannelId", _CreditPaymentChannelId);
		_columnOriginalValues.put("CreditBank", _CreditBank);
		_columnOriginalValues.put("CreditPaymentCode", _CreditPaymentCode);
		_columnOriginalValues.put(
			"CreditPaymentMessage", _CreditPaymentMessage);
		_columnOriginalValues.put(
			"ReportSettlementGenerated", _ReportSettlementGenerated);
		_columnOriginalValues.put(
			"CreditSettlementAttachmentId", _CreditSettlementAttachmentId);
		_columnOriginalValues.put("UtmId", _UtmId);
		_columnOriginalValues.put("Sojern", _Sojern);
		_columnOriginalValues.put("InvolveAsia", _InvolveAsia);
		_columnOriginalValues.put("Ada", _Ada);
		_columnOriginalValues.put("Active", _Active);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("paymentId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("TransactionId", 128L);

		columnBitmasks.put("SessionId", 256L);

		columnBitmasks.put("LeadsId", 512L);

		columnBitmasks.put("Amount", 1024L);

		columnBitmasks.put("Discount", 2048L);

		columnBitmasks.put("DiscountAmount", 4096L);

		columnBitmasks.put("PaymentStatus", 8192L);

		columnBitmasks.put("PaymentChannelId", 16384L);

		columnBitmasks.put("LinkAjaRefNum", 32768L);

		columnBitmasks.put("Tenor", 65536L);

		columnBitmasks.put("PaymentCode", 131072L);

		columnBitmasks.put("PaymentMessage", 262144L);

		columnBitmasks.put("CreditCardType", 524288L);

		columnBitmasks.put("TransactionDateTime", 1048576L);

		columnBitmasks.put("PaymentDateTime", 2097152L);

		columnBitmasks.put("Bank", 4194304L);

		columnBitmasks.put("ManagedBy", 8388608L);

		columnBitmasks.put("ReportGenerated", 16777216L);

		columnBitmasks.put("DailyReportGenerated", 33554432L);

		columnBitmasks.put("WeeklyReportGenerated", 67108864L);

		columnBitmasks.put("MonthlyReportGenerated", 134217728L);

		columnBitmasks.put("CheckStatusCounter", 268435456L);

		columnBitmasks.put("UserCreditId", 536870912L);

		columnBitmasks.put("CreditPaymentStatus", 1073741824L);

		columnBitmasks.put("CreditTransactionId", 2147483648L);

		columnBitmasks.put("CreditPaymentDate", 4294967296L);

		columnBitmasks.put("CreditPaymentChannelId", 8589934592L);

		columnBitmasks.put("CreditBank", 17179869184L);

		columnBitmasks.put("CreditPaymentCode", 34359738368L);

		columnBitmasks.put("CreditPaymentMessage", 68719476736L);

		columnBitmasks.put("ReportSettlementGenerated", 137438953472L);

		columnBitmasks.put("CreditSettlementAttachmentId", 274877906944L);

		columnBitmasks.put("UtmId", 549755813888L);

		columnBitmasks.put("Sojern", 1099511627776L);

		columnBitmasks.put("InvolveAsia", 2199023255552L);

		columnBitmasks.put("Ada", 4398046511104L);

		columnBitmasks.put("Active", 8796093022208L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Payment _escapedModel;

}