/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aii.esppk.admin.model.impl;

import com.aii.esppk.admin.model.SppkUser;
import com.aii.esppk.admin.model.SppkUserModel;
import com.aii.esppk.admin.model.SppkUserSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SppkUser service. Represents a row in the &quot;MSPPK_SppkUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SppkUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SppkUserImpl}.
 * </p>
 *
 * @author Gositus
 * @see SppkUserImpl
 * @generated
 */
@JSON(strict = true)
public class SppkUserModelImpl
	extends BaseModelImpl<SppkUser> implements SppkUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sppk user model instance should use the <code>SppkUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "MSPPK_SppkUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"sppkUserId", Types.BIGINT}, {"sppkLoginCode", Types.VARCHAR},
		{"password_", Types.VARCHAR}, {"fullName", Types.VARCHAR},
		{"roleCode", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"allAccess", Types.INTEGER}, {"accessData", Types.INTEGER},
		{"accessMonitoring", Types.INTEGER}, {"active_", Types.INTEGER},
		{"expireDate", Types.TIMESTAMP}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"otpCode", Types.VARCHAR},
		{"otpExpired", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("sppkUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sppkLoginCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("password_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fullName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("roleCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("allAccess", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("accessData", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("accessMonitoring", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("expireDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("otpCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("otpExpired", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MSPPK_SppkUser (sppkUserId LONG not null primary key,sppkLoginCode VARCHAR(75) null,password_ VARCHAR(75) null,fullName VARCHAR(75) null,roleCode VARCHAR(75) null,email VARCHAR(75) null,allAccess INTEGER,accessData INTEGER,accessMonitoring INTEGER,active_ INTEGER,expireDate DATE null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,otpCode VARCHAR(75) null,otpExpired DATE null)";

	public static final String TABLE_SQL_DROP = "drop table MSPPK_SppkUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY sppkUser.sppkUserId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MSPPK_SppkUser.sppkUserId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMAIL_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FULLNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OTPCODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PASSWORD_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SPPKLOGINCODE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SPPKUSERID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SppkUser toModel(SppkUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SppkUser model = new SppkUserImpl();

		model.setSppkUserId(soapModel.getSppkUserId());
		model.setSppkLoginCode(soapModel.getSppkLoginCode());
		model.setPassword(soapModel.getPassword());
		model.setFullName(soapModel.getFullName());
		model.setRoleCode(soapModel.getRoleCode());
		model.setEmail(soapModel.getEmail());
		model.setAllAccess(soapModel.getAllAccess());
		model.setAccessData(soapModel.getAccessData());
		model.setAccessMonitoring(soapModel.getAccessMonitoring());
		model.setActive(soapModel.getActive());
		model.setExpireDate(soapModel.getExpireDate());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setOtpCode(soapModel.getOtpCode());
		model.setOtpExpired(soapModel.getOtpExpired());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SppkUser> toModels(SppkUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SppkUser> models = new ArrayList<SppkUser>(soapModels.length);

		for (SppkUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SppkUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sppkUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSppkUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sppkUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SppkUser.class;
	}

	@Override
	public String getModelClassName() {
		return SppkUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SppkUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SppkUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SppkUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SppkUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SppkUser, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SppkUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SppkUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SppkUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SppkUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SppkUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SppkUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SppkUser, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SppkUser, Object>>();
		Map<String, BiConsumer<SppkUser, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SppkUser, ?>>();

		attributeGetterFunctions.put("sppkUserId", SppkUser::getSppkUserId);
		attributeSetterBiConsumers.put(
			"sppkUserId", (BiConsumer<SppkUser, Long>)SppkUser::setSppkUserId);
		attributeGetterFunctions.put(
			"sppkLoginCode", SppkUser::getSppkLoginCode);
		attributeSetterBiConsumers.put(
			"sppkLoginCode",
			(BiConsumer<SppkUser, String>)SppkUser::setSppkLoginCode);
		attributeGetterFunctions.put("password", SppkUser::getPassword);
		attributeSetterBiConsumers.put(
			"password", (BiConsumer<SppkUser, String>)SppkUser::setPassword);
		attributeGetterFunctions.put("fullName", SppkUser::getFullName);
		attributeSetterBiConsumers.put(
			"fullName", (BiConsumer<SppkUser, String>)SppkUser::setFullName);
		attributeGetterFunctions.put("roleCode", SppkUser::getRoleCode);
		attributeSetterBiConsumers.put(
			"roleCode", (BiConsumer<SppkUser, String>)SppkUser::setRoleCode);
		attributeGetterFunctions.put("email", SppkUser::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<SppkUser, String>)SppkUser::setEmail);
		attributeGetterFunctions.put("allAccess", SppkUser::getAllAccess);
		attributeSetterBiConsumers.put(
			"allAccess", (BiConsumer<SppkUser, Integer>)SppkUser::setAllAccess);
		attributeGetterFunctions.put("accessData", SppkUser::getAccessData);
		attributeSetterBiConsumers.put(
			"accessData",
			(BiConsumer<SppkUser, Integer>)SppkUser::setAccessData);
		attributeGetterFunctions.put(
			"accessMonitoring", SppkUser::getAccessMonitoring);
		attributeSetterBiConsumers.put(
			"accessMonitoring",
			(BiConsumer<SppkUser, Integer>)SppkUser::setAccessMonitoring);
		attributeGetterFunctions.put("active", SppkUser::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<SppkUser, Integer>)SppkUser::setActive);
		attributeGetterFunctions.put("expireDate", SppkUser::getExpireDate);
		attributeSetterBiConsumers.put(
			"expireDate", (BiConsumer<SppkUser, Date>)SppkUser::setExpireDate);
		attributeGetterFunctions.put("groupId", SppkUser::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<SppkUser, Long>)SppkUser::setGroupId);
		attributeGetterFunctions.put("companyId", SppkUser::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<SppkUser, Long>)SppkUser::setCompanyId);
		attributeGetterFunctions.put("userId", SppkUser::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<SppkUser, Long>)SppkUser::setUserId);
		attributeGetterFunctions.put("userName", SppkUser::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<SppkUser, String>)SppkUser::setUserName);
		attributeGetterFunctions.put("createDate", SppkUser::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<SppkUser, Date>)SppkUser::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", SppkUser::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SppkUser, Date>)SppkUser::setModifiedDate);
		attributeGetterFunctions.put("otpCode", SppkUser::getOtpCode);
		attributeSetterBiConsumers.put(
			"otpCode", (BiConsumer<SppkUser, String>)SppkUser::setOtpCode);
		attributeGetterFunctions.put("otpExpired", SppkUser::getOtpExpired);
		attributeSetterBiConsumers.put(
			"otpExpired", (BiConsumer<SppkUser, Date>)SppkUser::setOtpExpired);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSppkUserId() {
		return _sppkUserId;
	}

	@Override
	public void setSppkUserId(long sppkUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sppkUserId = sppkUserId;
	}

	@Override
	public String getSppkUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getSppkUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setSppkUserUuid(String sppkUserUuid) {
	}

	@JSON
	@Override
	public String getSppkLoginCode() {
		if (_sppkLoginCode == null) {
			return "";
		}
		else {
			return _sppkLoginCode;
		}
	}

	@Override
	public void setSppkLoginCode(String sppkLoginCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sppkLoginCode = sppkLoginCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSppkLoginCode() {
		return getColumnOriginalValue("sppkLoginCode");
	}

	@JSON
	@Override
	public String getPassword() {
		if (_password == null) {
			return "";
		}
		else {
			return _password;
		}
	}

	@Override
	public void setPassword(String password) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_password = password;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPassword() {
		return getColumnOriginalValue("password_");
	}

	@JSON
	@Override
	public String getFullName() {
		if (_fullName == null) {
			return "";
		}
		else {
			return _fullName;
		}
	}

	@Override
	public void setFullName(String fullName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fullName = fullName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFullName() {
		return getColumnOriginalValue("fullName");
	}

	@JSON
	@Override
	public String getRoleCode() {
		if (_roleCode == null) {
			return "";
		}
		else {
			return _roleCode;
		}
	}

	@Override
	public void setRoleCode(String roleCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleCode = roleCode;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEmail() {
		return getColumnOriginalValue("email");
	}

	@JSON
	@Override
	public int getAllAccess() {
		return _allAccess;
	}

	@Override
	public void setAllAccess(int allAccess) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allAccess = allAccess;
	}

	@JSON
	@Override
	public int getAccessData() {
		return _accessData;
	}

	@Override
	public void setAccessData(int accessData) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accessData = accessData;
	}

	@JSON
	@Override
	public int getAccessMonitoring() {
		return _accessMonitoring;
	}

	@Override
	public void setAccessMonitoring(int accessMonitoring) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accessMonitoring = accessMonitoring;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public Date getExpireDate() {
		return _expireDate;
	}

	@Override
	public void setExpireDate(Date expireDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expireDate = expireDate;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getOtpCode() {
		if (_otpCode == null) {
			return "";
		}
		else {
			return _otpCode;
		}
	}

	@Override
	public void setOtpCode(String otpCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_otpCode = otpCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalOtpCode() {
		return getColumnOriginalValue("otpCode");
	}

	@JSON
	@Override
	public Date getOtpExpired() {
		return _otpExpired;
	}

	@Override
	public void setOtpExpired(Date otpExpired) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_otpExpired = otpExpired;
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SppkUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SppkUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SppkUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SppkUserImpl sppkUserImpl = new SppkUserImpl();

		sppkUserImpl.setSppkUserId(getSppkUserId());
		sppkUserImpl.setSppkLoginCode(getSppkLoginCode());
		sppkUserImpl.setPassword(getPassword());
		sppkUserImpl.setFullName(getFullName());
		sppkUserImpl.setRoleCode(getRoleCode());
		sppkUserImpl.setEmail(getEmail());
		sppkUserImpl.setAllAccess(getAllAccess());
		sppkUserImpl.setAccessData(getAccessData());
		sppkUserImpl.setAccessMonitoring(getAccessMonitoring());
		sppkUserImpl.setActive(getActive());
		sppkUserImpl.setExpireDate(getExpireDate());
		sppkUserImpl.setGroupId(getGroupId());
		sppkUserImpl.setCompanyId(getCompanyId());
		sppkUserImpl.setUserId(getUserId());
		sppkUserImpl.setUserName(getUserName());
		sppkUserImpl.setCreateDate(getCreateDate());
		sppkUserImpl.setModifiedDate(getModifiedDate());
		sppkUserImpl.setOtpCode(getOtpCode());
		sppkUserImpl.setOtpExpired(getOtpExpired());

		sppkUserImpl.resetOriginalValues();

		return sppkUserImpl;
	}

	@Override
	public int compareTo(SppkUser sppkUser) {
		long primaryKey = sppkUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SppkUser)) {
			return false;
		}

		SppkUser sppkUser = (SppkUser)object;

		long primaryKey = sppkUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SppkUser> toCacheModel() {
		SppkUserCacheModel sppkUserCacheModel = new SppkUserCacheModel();

		sppkUserCacheModel.sppkUserId = getSppkUserId();

		sppkUserCacheModel.sppkLoginCode = getSppkLoginCode();

		String sppkLoginCode = sppkUserCacheModel.sppkLoginCode;

		if ((sppkLoginCode != null) && (sppkLoginCode.length() == 0)) {
			sppkUserCacheModel.sppkLoginCode = null;
		}

		sppkUserCacheModel.password = getPassword();

		String password = sppkUserCacheModel.password;

		if ((password != null) && (password.length() == 0)) {
			sppkUserCacheModel.password = null;
		}

		sppkUserCacheModel.fullName = getFullName();

		String fullName = sppkUserCacheModel.fullName;

		if ((fullName != null) && (fullName.length() == 0)) {
			sppkUserCacheModel.fullName = null;
		}

		sppkUserCacheModel.roleCode = getRoleCode();

		String roleCode = sppkUserCacheModel.roleCode;

		if ((roleCode != null) && (roleCode.length() == 0)) {
			sppkUserCacheModel.roleCode = null;
		}

		sppkUserCacheModel.email = getEmail();

		String email = sppkUserCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			sppkUserCacheModel.email = null;
		}

		sppkUserCacheModel.allAccess = getAllAccess();

		sppkUserCacheModel.accessData = getAccessData();

		sppkUserCacheModel.accessMonitoring = getAccessMonitoring();

		sppkUserCacheModel.active = getActive();

		Date expireDate = getExpireDate();

		if (expireDate != null) {
			sppkUserCacheModel.expireDate = expireDate.getTime();
		}
		else {
			sppkUserCacheModel.expireDate = Long.MIN_VALUE;
		}

		sppkUserCacheModel.groupId = getGroupId();

		sppkUserCacheModel.companyId = getCompanyId();

		sppkUserCacheModel.userId = getUserId();

		sppkUserCacheModel.userName = getUserName();

		String userName = sppkUserCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sppkUserCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sppkUserCacheModel.createDate = createDate.getTime();
		}
		else {
			sppkUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sppkUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sppkUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sppkUserCacheModel.otpCode = getOtpCode();

		String otpCode = sppkUserCacheModel.otpCode;

		if ((otpCode != null) && (otpCode.length() == 0)) {
			sppkUserCacheModel.otpCode = null;
		}

		Date otpExpired = getOtpExpired();

		if (otpExpired != null) {
			sppkUserCacheModel.otpExpired = otpExpired.getTime();
		}
		else {
			sppkUserCacheModel.otpExpired = Long.MIN_VALUE;
		}

		return sppkUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SppkUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SppkUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SppkUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SppkUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SppkUser, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SppkUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SppkUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SppkUser)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SppkUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SppkUser.class, ModelWrapper.class);

	}

	private long _sppkUserId;
	private String _sppkLoginCode;
	private String _password;
	private String _fullName;
	private String _roleCode;
	private String _email;
	private int _allAccess;
	private int _accessData;
	private int _accessMonitoring;
	private int _active;
	private Date _expireDate;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _otpCode;
	private Date _otpExpired;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SppkUser, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SppkUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("sppkUserId", _sppkUserId);
		_columnOriginalValues.put("sppkLoginCode", _sppkLoginCode);
		_columnOriginalValues.put("password_", _password);
		_columnOriginalValues.put("fullName", _fullName);
		_columnOriginalValues.put("roleCode", _roleCode);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("allAccess", _allAccess);
		_columnOriginalValues.put("accessData", _accessData);
		_columnOriginalValues.put("accessMonitoring", _accessMonitoring);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("expireDate", _expireDate);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("otpCode", _otpCode);
		_columnOriginalValues.put("otpExpired", _otpExpired);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("password_", "password");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("sppkUserId", 1L);

		columnBitmasks.put("sppkLoginCode", 2L);

		columnBitmasks.put("password_", 4L);

		columnBitmasks.put("fullName", 8L);

		columnBitmasks.put("roleCode", 16L);

		columnBitmasks.put("email", 32L);

		columnBitmasks.put("allAccess", 64L);

		columnBitmasks.put("accessData", 128L);

		columnBitmasks.put("accessMonitoring", 256L);

		columnBitmasks.put("active_", 512L);

		columnBitmasks.put("expireDate", 1024L);

		columnBitmasks.put("groupId", 2048L);

		columnBitmasks.put("companyId", 4096L);

		columnBitmasks.put("userId", 8192L);

		columnBitmasks.put("userName", 16384L);

		columnBitmasks.put("createDate", 32768L);

		columnBitmasks.put("modifiedDate", 65536L);

		columnBitmasks.put("otpCode", 131072L);

		columnBitmasks.put("otpExpired", 262144L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SppkUser _escapedModel;

}