create table Customer (
	customerId LONG not null primary key,
	LeadsId LONG,
	Name VARCHAR(75) null,
	Email VARCHAR(75) null,
	MobilePhone VARCHAR(75) null,
	Gender VARCHAR(75) null,
	Dob DATE null,
	BirthPlace VARCHAR(75) null,
	Nationality VARCHAR(75) null,
	IdNumber VARCHAR(75) null,
	PassportNumber VARCHAR(75) null,
	KitasNumber VARCHAR(75) null,
	Address VARCHAR(75) null,
	Address2 VARCHAR(75) null,
	Relationship VARCHAR(75) null,
	Province VARCHAR(75) null,
	City VARCHAR(75) null,
	Zip VARCHAR(75) null,
	Beneficiary VARCHAR(75) null,
	BeneficiaryRelationship VARCHAR(75) null,
	Type VARCHAR(75) null,
	ProductCode VARCHAR(75) null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	isPep INTEGER,
	CountryCode VARCHAR(75) null,
	Job VARCHAR(75) null,
	JobOther VARCHAR(75) null,
	Age INTEGER,
	MaritalStatus VARCHAR(75) null,
	Phone VARCHAR(75) null,
	idPhotoFileEntryId LONG,
	PhotoFileUrl VARCHAR(75) null
);

create table DetailDomesticTravel (
	detailDomesticTravelId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	LeadsId LONG,
	TravelType VARCHAR(75) null,
	TravelPlan VARCHAR(75) null,
	TravellerType VARCHAR(75) null,
	Adult INTEGER,
	Child INTEGER,
	DepartureDate DATE null,
	ArrivalDate DATE null,
	CommercialOffers INTEGER
);

create table DetailDrive (
	detailDriveId LONG not null primary key,
	leadsId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	vehicleCode VARCHAR(75) null,
	VehicleManufacture VARCHAR(75) null,
	vehicleModel VARCHAR(75) null,
	vehicleSubModel VARCHAR(75) null,
	vehicleBody VARCHAR(75) null,
	manufactureYear INTEGER,
	manufactureAge INTEGER,
	coverageType VARCHAR(75) null,
	vehicleType VARCHAR(75) null,
	typeOfUse VARCHAR(75) null,
	vehicleInsured DOUBLE,
	accessoriesInsured DOUBLE,
	sumInsured DOUBLE,
	regionPlate VARCHAR(75) null,
	cc INTEGER,
	make VARCHAR(75) null,
	dpg VARCHAR(75) null,
	seatCapacity INTEGER,
	startDate DATE null,
	expiredDate DATE null,
	commercialOffers INTEGER,
	name VARCHAR(75) null,
	birthPlace VARCHAR(75) null,
	dob DATE null,
	nationality VARCHAR(75) null,
	idNumber VARCHAR(75) null,
	passportNumber VARCHAR(75) null,
	kitasNumber VARCHAR(75) null,
	mobilePhone VARCHAR(75) null,
	email VARCHAR(75) null,
	address VARCHAR(75) null,
	address2 VARCHAR(75) null,
	province VARCHAR(75) null,
	city VARCHAR(75) null,
	policeNumber VARCHAR(75) null,
	chassisNumber VARCHAR(75) null,
	engineNumber VARCHAR(75) null,
	policyNumber VARCHAR(75) null,
	referenceNumber VARCHAR(75) null,
	policyStatus VARCHAR(75) null,
	currency_ VARCHAR(75) null,
	policyCost DOUBLE,
	stampDuty DOUBLE,
	premium DOUBLE,
	netPremium DOUBLE,
	discount INTEGER,
	commission VARCHAR(75) null,
	leads LONG,
	transactionId VARCHAR(75) null,
	bussinesModel VARCHAR(75) null,
	channel VARCHAR(75) null,
	promoCode VARCHAR(75) null,
	step1 INTEGER,
	step2 INTEGER,
	step3 INTEGER,
	dailyReportStatus INTEGER,
	dailyReportFile LONG,
	dailyReportAgentStatus INTEGER,
	dailyReportAgentFile LONG,
	utmSource VARCHAR(75) null,
	utmMedium VARCHAR(75) null,
	utmCampaign VARCHAR(75) null,
	utmTerm VARCHAR(75) null,
	utmContent VARCHAR(75) null,
	clickId VARCHAR(75) null,
	managedBy LONG,
	agentCode VARCHAR(75) null,
	subAgent LONG,
	marketingCode VARCHAR(75) null,
	active_ INTEGER
);

create table DetailHealthIndividu (
	detailHealthIndividuId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	LeadsId LONG,
	PlanId LONG,
	PremiId LONG,
	SameAddress INTEGER,
	CurrentAddress VARCHAR(75) null,
	CurrentAddress2 VARCHAR(75) null,
	CurrentZip VARCHAR(75) null,
	JobCat VARCHAR(75) null,
	JobType VARCHAR(75) null,
	Job VARCHAR(75) null,
	JobPosition VARCHAR(75) null,
	AccountBankNumber VARCHAR(75) null,
	AccountBankName VARCHAR(75) null,
	BankName VARCHAR(75) null,
	HealthAgreement INTEGER,
	ChildAgreement INTEGER
);

create table DetailInternationalTravel (
	DetailId LONG not null primary key,
	LeadsId LONG,
	TravelType VARCHAR(75) null,
	Destination VARCHAR(75) null,
	PackageType VARCHAR(75) null,
	TravellerType VARCHAR(75) null,
	DepartureDate DATE null,
	ArrivalDate DATE null,
	Adult INTEGER,
	Child INTEGER,
	ListBenefitId VARCHAR(75) null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table DetailPet (
	detailPetId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	LeadsId LONG,
	PlanId LONG,
	LimitDisability DOUBLE,
	LimitMedical DOUBLE,
	LimitThirdParty DOUBLE,
	LimitCustody DOUBLE,
	PetName VARCHAR(75) null,
	PetType VARCHAR(75) null,
	PetGender VARCHAR(75) null,
	PetDob DATE null,
	PetIdNumber VARCHAR(75) null,
	PetIdNumberIssuing VARCHAR(75) null,
	PetIdNumberFileEntryId LONG,
	PetIdNumberURL VARCHAR(75) null,
	PetPhotoFileEntryId LONG,
	PetPhotoURL VARCHAR(75) null,
	PetLocation VARCHAR(75) null,
	PetVaccine INTEGER,
	PetAuthorizedCertificate INTEGER
);

create table DetailSmartactive (
	DetailId LONG not null primary key,
	LeadsId LONG,
	ExcludedActivityStatus INTEGER,
	JobType LONG,
	MainBenefitValue VARCHAR(75) null,
	StartPeriode DATE null,
	EndPeriode DATE null,
	ListBenefitId VARCHAR(75) null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table DetailTlp (
	detailTlpId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	startDate DATE null,
	expiredDate DATE null,
	mainPolicyStartDate DATE null,
	mainPolicyEndDate DATE null,
	numberOfDays INTEGER,
	name VARCHAR(75) null,
	birthPlace VARCHAR(75) null,
	dob DATE null,
	nationality VARCHAR(75) null,
	idNumber VARCHAR(75) null,
	passportNumber VARCHAR(75) null,
	kitasNumber VARCHAR(75) null,
	mobilePhone VARCHAR(75) null,
	email VARCHAR(75) null,
	address VARCHAR(75) null,
	address2 VARCHAR(75) null,
	province VARCHAR(75) null,
	city VARCHAR(75) null,
	postCode VARCHAR(75) null,
	commercialOffer INTEGER,
	driveModel LONG,
	vehicleManufacture VARCHAR(75) null,
	vehicleModel VARCHAR(75) null,
	vehicleSubModel VARCHAR(75) null,
	manufactureYear INTEGER,
	vehicleInsured DOUBLE,
	regionPlate VARCHAR(75) null,
	policeNumber VARCHAR(75) null,
	chassisNumber VARCHAR(75) null,
	engineNumber VARCHAR(75) null,
	leadsId LONG,
	transactionId_ LONG,
	businessModel VARCHAR(75) null,
	channel VARCHAR(75) null,
	promoCode VARCHAR(75) null,
	step1 INTEGER,
	policyNumber VARCHAR(75) null,
	referenceNumber VARCHAR(75) null,
	policyStatus VARCHAR(75) null,
	packageName VARCHAR(75) null,
	packageInfo LONG,
	rate DOUBLE,
	currency_ VARCHAR(75) null,
	sumInsured DOUBLE,
	policyCost DOUBLE,
	stampDuty DOUBLE,
	premium DOUBLE,
	netPremium DOUBLE,
	discount DOUBLE,
	commision DOUBLE,
	insuranceName VARCHAR(75) null,
	insurancePolicyNo VARCHAR(75) null,
	managedBy LONG,
	agentCode VARCHAR(75) null,
	subAgent LONG,
	marketingCode VARCHAR(75) null,
	utmSource VARCHAR(75) null,
	utmMedium VARCHAR(75) null,
	utmCampaign VARCHAR(75) null,
	utmTerm VARCHAR(75) null,
	utmContent VARCHAR(75) null,
	clickId VARCHAR(75) null
);

create table Leads (
	LeadsId LONG not null primary key,
	LeadsParentId LONG,
	LeadsType VARCHAR(75) null,
	BussinesModel VARCHAR(75) null,
	CommercialOffers INTEGER,
	PolicyNumber VARCHAR(75) null,
	ReferenceNumber VARCHAR(75) null,
	Currency VARCHAR(75) null,
	PolicyCost DOUBLE,
	StampDuty DOUBLE,
	Premium DOUBLE,
	NetPremium DOUBLE,
	Discount DOUBLE,
	DiscountAmount DOUBLE,
	Commission DOUBLE,
	Channel VARCHAR(75) null,
	PromoCode VARCHAR(75) null,
	ProductCode VARCHAR(75) null,
	UtmSource VARCHAR(75) null,
	UtmMedium VARCHAR(75) null,
	UtmCampaign VARCHAR(75) null,
	UtmTerm VARCHAR(75) null,
	UtmContent VARCHAR(75) null,
	ClickId VARCHAR(75) null,
	Name VARCHAR(75) null,
	Email VARCHAR(75) null,
	MobilePhone VARCHAR(75) null,
	Gender VARCHAR(75) null,
	Dob DATE null,
	BirthPlace VARCHAR(75) null,
	Nationality VARCHAR(75) null,
	IdNumber VARCHAR(75) null,
	PassportNumber VARCHAR(75) null,
	KitasNumber VARCHAR(75) null,
	idPhotoFileEntryId LONG,
	Address VARCHAR(75) null,
	Address2 VARCHAR(75) null,
	Province VARCHAR(75) null,
	City VARCHAR(75) null,
	Zip VARCHAR(75) null,
	Active INTEGER,
	Token VARCHAR(75) null,
	PolicyStartDate DATE null,
	PolicyEndDate DATE null,
	TempCode VARCHAR(75) null,
	Status VARCHAR(75) null,
	PaymentStatus VARCHAR(75) null,
	mypageUserId LONG,
	managedBy VARCHAR(75) null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	isPep INTEGER,
	CountryCode VARCHAR(75) null,
	Job VARCHAR(75) null,
	JobOther VARCHAR(75) null,
	Age INTEGER,
	MaritalStatus VARCHAR(75) null,
	Phone VARCHAR(75) null,
	PhotoFileUrl VARCHAR(75) null,
	WorkLocation VARCHAR(75) null,
	WorkLocationOther VARCHAR(75) null,
	MonthlyIncome VARCHAR(75) null,
	PaymentSource VARCHAR(75) null,
	PaymentSourceOther VARCHAR(75) null,
	Beneficiary VARCHAR(75) null,
	BeneficiaryRelationship VARCHAR(75) null
);

create table Payment (
	paymentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	TransactionId VARCHAR(75) null,
	SessionId VARCHAR(75) null,
	LeadsId LONG,
	Amount DOUBLE,
	Discount DOUBLE,
	DiscountAmount DOUBLE,
	PaymentStatus VARCHAR(75) null,
	PaymentChannelId LONG,
	LinkAjaRefNum VARCHAR(75) null,
	Tenor VARCHAR(75) null,
	PaymentCode VARCHAR(75) null,
	PaymentMessage VARCHAR(75) null,
	CreditCardType VARCHAR(75) null,
	TransactionDateTime DATE null,
	PaymentDateTime DATE null,
	Bank VARCHAR(75) null,
	ManagedBy LONG,
	ReportGenerated INTEGER,
	DailyReportGenerated INTEGER,
	WeeklyReportGenerated INTEGER,
	MonthlyReportGenerated INTEGER,
	CheckStatusCounter INTEGER,
	UserCreditId LONG,
	CreditPaymentStatus VARCHAR(75) null,
	CreditTransactionId VARCHAR(75) null,
	CreditPaymentDate DATE null,
	CreditPaymentChannelId LONG,
	CreditBank VARCHAR(75) null,
	CreditPaymentCode VARCHAR(75) null,
	CreditPaymentMessage VARCHAR(75) null,
	ReportSettlementGenerated INTEGER,
	CreditSettlementAttachmentId LONG,
	UtmId LONG,
	Sojern INTEGER,
	InvolveAsia INTEGER,
	Ada INTEGER,
	Active INTEGER
);