/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AgentTokenLimiter service. Represents a row in the &quot;AP_AgentTokenLimiter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.agencyportal.model.impl.AgentTokenLimiterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.agencyportal.model.impl.AgentTokenLimiterImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see AgentTokenLimiter
 * @generated
 */
@ProviderType
public interface AgentTokenLimiterModel
	extends BaseModel<AgentTokenLimiter>, GroupedModel, ShardedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agent token limiter model instance should use the {@link AgentTokenLimiter} interface instead.
	 */

	/**
	 * Returns the primary key of this agent token limiter.
	 *
	 * @return the primary key of this agent token limiter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agent token limiter.
	 *
	 * @param primaryKey the primary key of this agent token limiter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agent token limiter ID of this agent token limiter.
	 *
	 * @return the agent token limiter ID of this agent token limiter
	 */
	public long getAgentTokenLimiterId();

	/**
	 * Sets the agent token limiter ID of this agent token limiter.
	 *
	 * @param agentTokenLimiterId the agent token limiter ID of this agent token limiter
	 */
	public void setAgentTokenLimiterId(long agentTokenLimiterId);

	/**
	 * Returns the group ID of this agent token limiter.
	 *
	 * @return the group ID of this agent token limiter
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this agent token limiter.
	 *
	 * @param groupId the group ID of this agent token limiter
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this agent token limiter.
	 *
	 * @return the company ID of this agent token limiter
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this agent token limiter.
	 *
	 * @param companyId the company ID of this agent token limiter
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this agent token limiter.
	 *
	 * @return the user ID of this agent token limiter
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this agent token limiter.
	 *
	 * @param userId the user ID of this agent token limiter
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this agent token limiter.
	 *
	 * @return the user uuid of this agent token limiter
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this agent token limiter.
	 *
	 * @param userUuid the user uuid of this agent token limiter
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this agent token limiter.
	 *
	 * @return the user name of this agent token limiter
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this agent token limiter.
	 *
	 * @param userName the user name of this agent token limiter
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this agent token limiter.
	 *
	 * @return the create date of this agent token limiter
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this agent token limiter.
	 *
	 * @param createDate the create date of this agent token limiter
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agent token limiter.
	 *
	 * @return the modified date of this agent token limiter
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agent token limiter.
	 *
	 * @param modifiedDate the modified date of this agent token limiter
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dept code of this agent token limiter.
	 *
	 * @return the dept code of this agent token limiter
	 */
	@AutoEscape
	public String getDeptCode();

	/**
	 * Sets the dept code of this agent token limiter.
	 *
	 * @param deptCode the dept code of this agent token limiter
	 */
	public void setDeptCode(String deptCode);

	/**
	 * Returns the token of this agent token limiter.
	 *
	 * @return the token of this agent token limiter
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this agent token limiter.
	 *
	 * @param token the token of this agent token limiter
	 */
	public void setToken(String token);

	/**
	 * Returns the is valid of this agent token limiter.
	 *
	 * @return the is valid of this agent token limiter
	 */
	public int getIsValid();

	/**
	 * Sets the is valid of this agent token limiter.
	 *
	 * @param isValid the is valid of this agent token limiter
	 */
	public void setIsValid(int isValid);

	/**
	 * Returns the token type of this agent token limiter.
	 *
	 * @return the token type of this agent token limiter
	 */
	@AutoEscape
	public String getTokenType();

	/**
	 * Sets the token type of this agent token limiter.
	 *
	 * @param tokenType the token type of this agent token limiter
	 */
	public void setTokenType(String tokenType);

	/**
	 * Returns the status of this agent token limiter.
	 *
	 * @return the status of this agent token limiter
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this agent token limiter was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this agent token limiter.
	 *
	 * @return the trash entry created when this agent token limiter was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this agent token limiter.
	 *
	 * @return the class primary key of the trash entry for this agent token limiter
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this agent token limiter.
	 *
	 * @return the trash handler for this agent token limiter
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this agent token limiter is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this agent token limiter is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this agent token limiter is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this agent token limiter is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}