/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AgentCalendar service. Represents a row in the &quot;AP_AgentCalendar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.agencyportal.model.impl.AgentCalendarModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.agencyportal.model.impl.AgentCalendarImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see AgentCalendar
 * @generated
 */
@ProviderType
public interface AgentCalendarModel
	extends BaseModel<AgentCalendar>, GroupedModel, ShardedModel, TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agent calendar model instance should use the {@link AgentCalendar} interface instead.
	 */

	/**
	 * Returns the primary key of this agent calendar.
	 *
	 * @return the primary key of this agent calendar
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agent calendar.
	 *
	 * @param primaryKey the primary key of this agent calendar
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agent calendar ID of this agent calendar.
	 *
	 * @return the agent calendar ID of this agent calendar
	 */
	public long getAgentCalendarId();

	/**
	 * Sets the agent calendar ID of this agent calendar.
	 *
	 * @param agentCalendarId the agent calendar ID of this agent calendar
	 */
	public void setAgentCalendarId(long agentCalendarId);

	/**
	 * Returns the title of this agent calendar.
	 *
	 * @return the title of this agent calendar
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this agent calendar.
	 *
	 * @param title the title of this agent calendar
	 */
	public void setTitle(String title);

	/**
	 * Returns the location of this agent calendar.
	 *
	 * @return the location of this agent calendar
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this agent calendar.
	 *
	 * @param location the location of this agent calendar
	 */
	public void setLocation(String location);

	/**
	 * Returns the address of this agent calendar.
	 *
	 * @return the address of this agent calendar
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this agent calendar.
	 *
	 * @param address the address of this agent calendar
	 */
	public void setAddress(String address);

	/**
	 * Returns the start date of this agent calendar.
	 *
	 * @return the start date of this agent calendar
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this agent calendar.
	 *
	 * @param startDate the start date of this agent calendar
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the start time of this agent calendar.
	 *
	 * @return the start time of this agent calendar
	 */
	@AutoEscape
	public String getStartTime();

	/**
	 * Sets the start time of this agent calendar.
	 *
	 * @param startTime the start time of this agent calendar
	 */
	public void setStartTime(String startTime);

	/**
	 * Returns the end date of this agent calendar.
	 *
	 * @return the end date of this agent calendar
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this agent calendar.
	 *
	 * @param endDate the end date of this agent calendar
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the end time of this agent calendar.
	 *
	 * @return the end time of this agent calendar
	 */
	@AutoEscape
	public String getEndTime();

	/**
	 * Sets the end time of this agent calendar.
	 *
	 * @param endTime the end time of this agent calendar
	 */
	public void setEndTime(String endTime);

	/**
	 * Returns the mypage user role ID of this agent calendar.
	 *
	 * @return the mypage user role ID of this agent calendar
	 */
	public long getMypageUserRoleId();

	/**
	 * Sets the mypage user role ID of this agent calendar.
	 *
	 * @param mypageUserRoleId the mypage user role ID of this agent calendar
	 */
	public void setMypageUserRoleId(long mypageUserRoleId);

	/**
	 * Returns the role of this agent calendar.
	 *
	 * @return the role of this agent calendar
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this agent calendar.
	 *
	 * @param role the role of this agent calendar
	 */
	public void setRole(String role);

	/**
	 * Returns the mypage user group ID of this agent calendar.
	 *
	 * @return the mypage user group ID of this agent calendar
	 */
	public long getMypageUserGroupId();

	/**
	 * Sets the mypage user group ID of this agent calendar.
	 *
	 * @param mypageUserGroupId the mypage user group ID of this agent calendar
	 */
	public void setMypageUserGroupId(long mypageUserGroupId);

	/**
	 * Returns the group of this agent calendar.
	 *
	 * @return the group of this agent calendar
	 */
	@AutoEscape
	public String getGroup();

	/**
	 * Sets the group of this agent calendar.
	 *
	 * @param group the group of this agent calendar
	 */
	public void setGroup(String group);

	/**
	 * Returns the description of this agent calendar.
	 *
	 * @return the description of this agent calendar
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this agent calendar.
	 *
	 * @param description the description of this agent calendar
	 */
	public void setDescription(String description);

	/**
	 * Returns the link of this agent calendar.
	 *
	 * @return the link of this agent calendar
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this agent calendar.
	 *
	 * @param link the link of this agent calendar
	 */
	public void setLink(String link);

	/**
	 * Returns the category of this agent calendar.
	 *
	 * @return the category of this agent calendar
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this agent calendar.
	 *
	 * @param category the category of this agent calendar
	 */
	public void setCategory(String category);

	/**
	 * Returns the file upload entry ID of this agent calendar.
	 *
	 * @return the file upload entry ID of this agent calendar
	 */
	public long getFileUploadEntryId();

	/**
	 * Sets the file upload entry ID of this agent calendar.
	 *
	 * @param fileUploadEntryId the file upload entry ID of this agent calendar
	 */
	public void setFileUploadEntryId(long fileUploadEntryId);

	/**
	 * Returns the file upload url of this agent calendar.
	 *
	 * @return the file upload url of this agent calendar
	 */
	@AutoEscape
	public String getFileUploadUrl();

	/**
	 * Sets the file upload url of this agent calendar.
	 *
	 * @param fileUploadUrl the file upload url of this agent calendar
	 */
	public void setFileUploadUrl(String fileUploadUrl);

	/**
	 * Returns the is all day of this agent calendar.
	 *
	 * @return the is all day of this agent calendar
	 */
	public int getIsAllDay();

	/**
	 * Sets the is all day of this agent calendar.
	 *
	 * @param isAllDay the is all day of this agent calendar
	 */
	public void setIsAllDay(int isAllDay);

	/**
	 * Returns the active of this agent calendar.
	 *
	 * @return the active of this agent calendar
	 */
	public int getActive();

	/**
	 * Sets the active of this agent calendar.
	 *
	 * @param active the active of this agent calendar
	 */
	public void setActive(int active);

	/**
	 * Returns the mypage user ID of this agent calendar.
	 *
	 * @return the mypage user ID of this agent calendar
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this agent calendar.
	 *
	 * @param mypageUserId the mypage user ID of this agent calendar
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this agent calendar.
	 *
	 * @return the mypage user uuid of this agent calendar
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this agent calendar.
	 *
	 * @param mypageUserUuid the mypage user uuid of this agent calendar
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the group ID of this agent calendar.
	 *
	 * @return the group ID of this agent calendar
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this agent calendar.
	 *
	 * @param groupId the group ID of this agent calendar
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this agent calendar.
	 *
	 * @return the company ID of this agent calendar
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this agent calendar.
	 *
	 * @param companyId the company ID of this agent calendar
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this agent calendar.
	 *
	 * @return the user ID of this agent calendar
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this agent calendar.
	 *
	 * @param userId the user ID of this agent calendar
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this agent calendar.
	 *
	 * @return the user uuid of this agent calendar
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this agent calendar.
	 *
	 * @param userUuid the user uuid of this agent calendar
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this agent calendar.
	 *
	 * @return the user name of this agent calendar
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this agent calendar.
	 *
	 * @param userName the user name of this agent calendar
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this agent calendar.
	 *
	 * @return the create date of this agent calendar
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this agent calendar.
	 *
	 * @param createDate the create date of this agent calendar
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agent calendar.
	 *
	 * @return the modified date of this agent calendar
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agent calendar.
	 *
	 * @param modifiedDate the modified date of this agent calendar
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this agent calendar.
	 *
	 * @return the status of this agent calendar
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this agent calendar was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this agent calendar.
	 *
	 * @return the trash entry created when this agent calendar was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this agent calendar.
	 *
	 * @return the class primary key of the trash entry for this agent calendar
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this agent calendar.
	 *
	 * @return the trash handler for this agent calendar
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this agent calendar is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this agent calendar is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this agent calendar is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this agent calendar is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}