/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AgentFAQCategory service. Represents a row in the &quot;AP_AgentFAQCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.agencyportal.model.impl.AgentFAQCategoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.agencyportal.model.impl.AgentFAQCategoryImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see AgentFAQCategory
 * @generated
 */
@ProviderType
public interface AgentFAQCategoryModel
	extends BaseModel<AgentFAQCategory>, GroupedModel, ShardedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agent faq category model instance should use the {@link AgentFAQCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this agent faq category.
	 *
	 * @return the primary key of this agent faq category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agent faq category.
	 *
	 * @param primaryKey the primary key of this agent faq category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agent faq category ID of this agent faq category.
	 *
	 * @return the agent faq category ID of this agent faq category
	 */
	public long getAgentFaqCategoryId();

	/**
	 * Sets the agent faq category ID of this agent faq category.
	 *
	 * @param agentFaqCategoryId the agent faq category ID of this agent faq category
	 */
	public void setAgentFaqCategoryId(long agentFaqCategoryId);

	/**
	 * Returns the category of this agent faq category.
	 *
	 * @return the category of this agent faq category
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this agent faq category.
	 *
	 * @param category the category of this agent faq category
	 */
	public void setCategory(String category);

	/**
	 * Returns the active of this agent faq category.
	 *
	 * @return the active of this agent faq category
	 */
	public int getActive();

	/**
	 * Sets the active of this agent faq category.
	 *
	 * @param active the active of this agent faq category
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this agent faq category.
	 *
	 * @return the group ID of this agent faq category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this agent faq category.
	 *
	 * @param groupId the group ID of this agent faq category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this agent faq category.
	 *
	 * @return the company ID of this agent faq category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this agent faq category.
	 *
	 * @param companyId the company ID of this agent faq category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this agent faq category.
	 *
	 * @return the user ID of this agent faq category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this agent faq category.
	 *
	 * @param userId the user ID of this agent faq category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this agent faq category.
	 *
	 * @return the user uuid of this agent faq category
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this agent faq category.
	 *
	 * @param userUuid the user uuid of this agent faq category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this agent faq category.
	 *
	 * @return the user name of this agent faq category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this agent faq category.
	 *
	 * @param userName the user name of this agent faq category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this agent faq category.
	 *
	 * @return the create date of this agent faq category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this agent faq category.
	 *
	 * @param createDate the create date of this agent faq category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agent faq category.
	 *
	 * @return the modified date of this agent faq category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agent faq category.
	 *
	 * @param modifiedDate the modified date of this agent faq category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this agent faq category.
	 *
	 * @return the status of this agent faq category
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this agent faq category was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this agent faq category.
	 *
	 * @return the trash entry created when this agent faq category was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this agent faq category.
	 *
	 * @return the class primary key of the trash entry for this agent faq category
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this agent faq category.
	 *
	 * @return the trash handler for this agent faq category
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this agent faq category is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this agent faq category is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this agent faq category is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this agent faq category is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}