/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AgentEmailBucket service. Represents a row in the &quot;AP_AgentEmailBucket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.agencyportal.model.impl.AgentEmailBucketModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.agencyportal.model.impl.AgentEmailBucketImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see AgentEmailBucket
 * @generated
 */
@ProviderType
public interface AgentEmailBucketModel
	extends BaseModel<AgentEmailBucket>, GroupedModel, ShardedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agent email bucket model instance should use the {@link AgentEmailBucket} interface instead.
	 */

	/**
	 * Returns the primary key of this agent email bucket.
	 *
	 * @return the primary key of this agent email bucket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agent email bucket.
	 *
	 * @param primaryKey the primary key of this agent email bucket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agent email bucket ID of this agent email bucket.
	 *
	 * @return the agent email bucket ID of this agent email bucket
	 */
	public long getAgentEmailBucketId();

	/**
	 * Sets the agent email bucket ID of this agent email bucket.
	 *
	 * @param agentEmailBucketId the agent email bucket ID of this agent email bucket
	 */
	public void setAgentEmailBucketId(long agentEmailBucketId);

	/**
	 * Returns the activity of this agent email bucket.
	 *
	 * @return the activity of this agent email bucket
	 */
	@AutoEscape
	public String getActivity();

	/**
	 * Sets the activity of this agent email bucket.
	 *
	 * @param activity the activity of this agent email bucket
	 */
	public void setActivity(String activity);

	/**
	 * Returns the subject of this agent email bucket.
	 *
	 * @return the subject of this agent email bucket
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this agent email bucket.
	 *
	 * @param subject the subject of this agent email bucket
	 */
	public void setSubject(String subject);

	/**
	 * Returns the sender of this agent email bucket.
	 *
	 * @return the sender of this agent email bucket
	 */
	@AutoEscape
	public String getSender();

	/**
	 * Sets the sender of this agent email bucket.
	 *
	 * @param sender the sender of this agent email bucket
	 */
	public void setSender(String sender);

	/**
	 * Returns the recipient of this agent email bucket.
	 *
	 * @return the recipient of this agent email bucket
	 */
	@AutoEscape
	public String getRecipient();

	/**
	 * Sets the recipient of this agent email bucket.
	 *
	 * @param recipient the recipient of this agent email bucket
	 */
	public void setRecipient(String recipient);

	/**
	 * Returns the recipient cc of this agent email bucket.
	 *
	 * @return the recipient cc of this agent email bucket
	 */
	@AutoEscape
	public String getRecipientCC();

	/**
	 * Sets the recipient cc of this agent email bucket.
	 *
	 * @param recipientCC the recipient cc of this agent email bucket
	 */
	public void setRecipientCC(String recipientCC);

	/**
	 * Returns the recipient bcc of this agent email bucket.
	 *
	 * @return the recipient bcc of this agent email bucket
	 */
	@AutoEscape
	public String getRecipientBCC();

	/**
	 * Sets the recipient bcc of this agent email bucket.
	 *
	 * @param recipientBCC the recipient bcc of this agent email bucket
	 */
	public void setRecipientBCC(String recipientBCC);

	/**
	 * Returns the template of this agent email bucket.
	 *
	 * @return the template of this agent email bucket
	 */
	@AutoEscape
	public String getTemplate();

	/**
	 * Sets the template of this agent email bucket.
	 *
	 * @param template the template of this agent email bucket
	 */
	public void setTemplate(String template);

	/**
	 * Returns the params of this agent email bucket.
	 *
	 * @return the params of this agent email bucket
	 */
	@AutoEscape
	public String getParams();

	/**
	 * Sets the params of this agent email bucket.
	 *
	 * @param params the params of this agent email bucket
	 */
	public void setParams(String params);

	/**
	 * Returns the body text of this agent email bucket.
	 *
	 * @return the body text of this agent email bucket
	 */
	@AutoEscape
	public String getBodyText();

	/**
	 * Sets the body text of this agent email bucket.
	 *
	 * @param bodyText the body text of this agent email bucket
	 */
	public void setBodyText(String bodyText);

	/**
	 * Returns the status_ of this agent email bucket.
	 *
	 * @return the status_ of this agent email bucket
	 */
	@AutoEscape
	public String getStatus_();

	/**
	 * Sets the status_ of this agent email bucket.
	 *
	 * @param status_ the status_ of this agent email bucket
	 */
	public void setStatus_(String status_);

	/**
	 * Returns the counter of this agent email bucket.
	 *
	 * @return the counter of this agent email bucket
	 */
	public int getCounter();

	/**
	 * Sets the counter of this agent email bucket.
	 *
	 * @param counter the counter of this agent email bucket
	 */
	public void setCounter(int counter);

	/**
	 * Returns the message of this agent email bucket.
	 *
	 * @return the message of this agent email bucket
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this agent email bucket.
	 *
	 * @param message the message of this agent email bucket
	 */
	public void setMessage(String message);

	/**
	 * Returns the resend count of this agent email bucket.
	 *
	 * @return the resend count of this agent email bucket
	 */
	public int getResendCount();

	/**
	 * Sets the resend count of this agent email bucket.
	 *
	 * @param resendCount the resend count of this agent email bucket
	 */
	public void setResendCount(int resendCount);

	/**
	 * Returns the delay of this agent email bucket.
	 *
	 * @return the delay of this agent email bucket
	 */
	@AutoEscape
	public String getDelay();

	/**
	 * Sets the delay of this agent email bucket.
	 *
	 * @param delay the delay of this agent email bucket
	 */
	public void setDelay(String delay);

	/**
	 * Returns the attachment ID of this agent email bucket.
	 *
	 * @return the attachment ID of this agent email bucket
	 */
	public long getAttachmentId();

	/**
	 * Sets the attachment ID of this agent email bucket.
	 *
	 * @param attachmentId the attachment ID of this agent email bucket
	 */
	public void setAttachmentId(long attachmentId);

	/**
	 * Returns the attachment url of this agent email bucket.
	 *
	 * @return the attachment url of this agent email bucket
	 */
	@AutoEscape
	public String getAttachmentUrl();

	/**
	 * Sets the attachment url of this agent email bucket.
	 *
	 * @param attachmentUrl the attachment url of this agent email bucket
	 */
	public void setAttachmentUrl(String attachmentUrl);

	/**
	 * Returns the active of this agent email bucket.
	 *
	 * @return the active of this agent email bucket
	 */
	public int getActive();

	/**
	 * Sets the active of this agent email bucket.
	 *
	 * @param active the active of this agent email bucket
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this agent email bucket.
	 *
	 * @return the group ID of this agent email bucket
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this agent email bucket.
	 *
	 * @param groupId the group ID of this agent email bucket
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this agent email bucket.
	 *
	 * @return the company ID of this agent email bucket
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this agent email bucket.
	 *
	 * @param companyId the company ID of this agent email bucket
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this agent email bucket.
	 *
	 * @return the user ID of this agent email bucket
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this agent email bucket.
	 *
	 * @param userId the user ID of this agent email bucket
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this agent email bucket.
	 *
	 * @return the user uuid of this agent email bucket
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this agent email bucket.
	 *
	 * @param userUuid the user uuid of this agent email bucket
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this agent email bucket.
	 *
	 * @return the user name of this agent email bucket
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this agent email bucket.
	 *
	 * @param userName the user name of this agent email bucket
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this agent email bucket.
	 *
	 * @return the create date of this agent email bucket
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this agent email bucket.
	 *
	 * @param createDate the create date of this agent email bucket
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agent email bucket.
	 *
	 * @return the modified date of this agent email bucket
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agent email bucket.
	 *
	 * @param modifiedDate the modified date of this agent email bucket
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this agent email bucket.
	 *
	 * @return the status of this agent email bucket
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this agent email bucket was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this agent email bucket.
	 *
	 * @return the trash entry created when this agent email bucket was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this agent email bucket.
	 *
	 * @return the class primary key of the trash entry for this agent email bucket
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this agent email bucket.
	 *
	 * @return the trash handler for this agent email bucket
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this agent email bucket is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this agent email bucket is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this agent email bucket is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this agent email bucket is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}