/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AgentMarkCalendar service. Represents a row in the &quot;AP_AgentMarkCalendar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.agencyportal.model.impl.AgentMarkCalendarModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.agencyportal.model.impl.AgentMarkCalendarImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see AgentMarkCalendar
 * @generated
 */
@ProviderType
public interface AgentMarkCalendarModel
	extends BaseModel<AgentMarkCalendar>, GroupedModel, ShardedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agent mark calendar model instance should use the {@link AgentMarkCalendar} interface instead.
	 */

	/**
	 * Returns the primary key of this agent mark calendar.
	 *
	 * @return the primary key of this agent mark calendar
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agent mark calendar.
	 *
	 * @param primaryKey the primary key of this agent mark calendar
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agent mark calendar ID of this agent mark calendar.
	 *
	 * @return the agent mark calendar ID of this agent mark calendar
	 */
	public long getAgentMarkCalendarId();

	/**
	 * Sets the agent mark calendar ID of this agent mark calendar.
	 *
	 * @param agentMarkCalendarId the agent mark calendar ID of this agent mark calendar
	 */
	public void setAgentMarkCalendarId(long agentMarkCalendarId);

	/**
	 * Returns the agent calendar ID of this agent mark calendar.
	 *
	 * @return the agent calendar ID of this agent mark calendar
	 */
	public long getAgentCalendarId();

	/**
	 * Sets the agent calendar ID of this agent mark calendar.
	 *
	 * @param agentCalendarId the agent calendar ID of this agent mark calendar
	 */
	public void setAgentCalendarId(long agentCalendarId);

	/**
	 * Returns the mypage user ID of this agent mark calendar.
	 *
	 * @return the mypage user ID of this agent mark calendar
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this agent mark calendar.
	 *
	 * @param mypageUserId the mypage user ID of this agent mark calendar
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this agent mark calendar.
	 *
	 * @return the mypage user uuid of this agent mark calendar
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this agent mark calendar.
	 *
	 * @param mypageUserUuid the mypage user uuid of this agent mark calendar
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the group ID of this agent mark calendar.
	 *
	 * @return the group ID of this agent mark calendar
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this agent mark calendar.
	 *
	 * @param groupId the group ID of this agent mark calendar
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this agent mark calendar.
	 *
	 * @return the company ID of this agent mark calendar
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this agent mark calendar.
	 *
	 * @param companyId the company ID of this agent mark calendar
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this agent mark calendar.
	 *
	 * @return the user ID of this agent mark calendar
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this agent mark calendar.
	 *
	 * @param userId the user ID of this agent mark calendar
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this agent mark calendar.
	 *
	 * @return the user uuid of this agent mark calendar
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this agent mark calendar.
	 *
	 * @param userUuid the user uuid of this agent mark calendar
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this agent mark calendar.
	 *
	 * @return the user name of this agent mark calendar
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this agent mark calendar.
	 *
	 * @param userName the user name of this agent mark calendar
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this agent mark calendar.
	 *
	 * @return the create date of this agent mark calendar
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this agent mark calendar.
	 *
	 * @param createDate the create date of this agent mark calendar
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agent mark calendar.
	 *
	 * @return the modified date of this agent mark calendar
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agent mark calendar.
	 *
	 * @param modifiedDate the modified date of this agent mark calendar
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this agent mark calendar.
	 *
	 * @return the status of this agent mark calendar
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this agent mark calendar was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this agent mark calendar.
	 *
	 * @return the trash entry created when this agent mark calendar was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this agent mark calendar.
	 *
	 * @return the class primary key of the trash entry for this agent mark calendar
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this agent mark calendar.
	 *
	 * @return the trash handler for this agent mark calendar
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this agent mark calendar is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this agent mark calendar is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this agent mark calendar is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this agent mark calendar is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}