/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AgentSalesTools service. Represents a row in the &quot;AP_AgentSalesTools&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.agencyportal.model.impl.AgentSalesToolsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.agencyportal.model.impl.AgentSalesToolsImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see AgentSalesTools
 * @generated
 */
@ProviderType
public interface AgentSalesToolsModel
	extends BaseModel<AgentSalesTools>, GroupedModel, ShardedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agent sales tools model instance should use the {@link AgentSalesTools} interface instead.
	 */

	/**
	 * Returns the primary key of this agent sales tools.
	 *
	 * @return the primary key of this agent sales tools
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agent sales tools.
	 *
	 * @param primaryKey the primary key of this agent sales tools
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agent sales tools ID of this agent sales tools.
	 *
	 * @return the agent sales tools ID of this agent sales tools
	 */
	public long getAgentSalesToolsId();

	/**
	 * Sets the agent sales tools ID of this agent sales tools.
	 *
	 * @param agentSalesToolsId the agent sales tools ID of this agent sales tools
	 */
	public void setAgentSalesToolsId(long agentSalesToolsId);

	/**
	 * Returns the title of this agent sales tools.
	 *
	 * @return the title of this agent sales tools
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this agent sales tools.
	 *
	 * @param title the title of this agent sales tools
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this agent sales tools.
	 *
	 * @return the description of this agent sales tools
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this agent sales tools.
	 *
	 * @param description the description of this agent sales tools
	 */
	public void setDescription(String description);

	/**
	 * Returns the category ID of this agent sales tools.
	 *
	 * @return the category ID of this agent sales tools
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this agent sales tools.
	 *
	 * @param categoryId the category ID of this agent sales tools
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the category of this agent sales tools.
	 *
	 * @return the category of this agent sales tools
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this agent sales tools.
	 *
	 * @param category the category of this agent sales tools
	 */
	public void setCategory(String category);

	/**
	 * Returns the file upload entry ID of this agent sales tools.
	 *
	 * @return the file upload entry ID of this agent sales tools
	 */
	public long getFileUploadEntryId();

	/**
	 * Sets the file upload entry ID of this agent sales tools.
	 *
	 * @param fileUploadEntryId the file upload entry ID of this agent sales tools
	 */
	public void setFileUploadEntryId(long fileUploadEntryId);

	/**
	 * Returns the file upload url of this agent sales tools.
	 *
	 * @return the file upload url of this agent sales tools
	 */
	@AutoEscape
	public String getFileUploadUrl();

	/**
	 * Sets the file upload url of this agent sales tools.
	 *
	 * @param fileUploadUrl the file upload url of this agent sales tools
	 */
	public void setFileUploadUrl(String fileUploadUrl);

	/**
	 * Returns the mypage user role ID of this agent sales tools.
	 *
	 * @return the mypage user role ID of this agent sales tools
	 */
	public long getMypageUserRoleId();

	/**
	 * Sets the mypage user role ID of this agent sales tools.
	 *
	 * @param mypageUserRoleId the mypage user role ID of this agent sales tools
	 */
	public void setMypageUserRoleId(long mypageUserRoleId);

	/**
	 * Returns the role of this agent sales tools.
	 *
	 * @return the role of this agent sales tools
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this agent sales tools.
	 *
	 * @param role the role of this agent sales tools
	 */
	public void setRole(String role);

	/**
	 * Returns the active of this agent sales tools.
	 *
	 * @return the active of this agent sales tools
	 */
	public int getActive();

	/**
	 * Sets the active of this agent sales tools.
	 *
	 * @param active the active of this agent sales tools
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this agent sales tools.
	 *
	 * @return the group ID of this agent sales tools
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this agent sales tools.
	 *
	 * @param groupId the group ID of this agent sales tools
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this agent sales tools.
	 *
	 * @return the company ID of this agent sales tools
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this agent sales tools.
	 *
	 * @param companyId the company ID of this agent sales tools
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this agent sales tools.
	 *
	 * @return the user ID of this agent sales tools
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this agent sales tools.
	 *
	 * @param userId the user ID of this agent sales tools
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this agent sales tools.
	 *
	 * @return the user uuid of this agent sales tools
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this agent sales tools.
	 *
	 * @param userUuid the user uuid of this agent sales tools
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this agent sales tools.
	 *
	 * @return the user name of this agent sales tools
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this agent sales tools.
	 *
	 * @param userName the user name of this agent sales tools
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this agent sales tools.
	 *
	 * @return the create date of this agent sales tools
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this agent sales tools.
	 *
	 * @param createDate the create date of this agent sales tools
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agent sales tools.
	 *
	 * @return the modified date of this agent sales tools
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agent sales tools.
	 *
	 * @param modifiedDate the modified date of this agent sales tools
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this agent sales tools.
	 *
	 * @return the status of this agent sales tools
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this agent sales tools was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this agent sales tools.
	 *
	 * @return the trash entry created when this agent sales tools was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this agent sales tools.
	 *
	 * @return the class primary key of the trash entry for this agent sales tools
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this agent sales tools.
	 *
	 * @return the trash handler for this agent sales tools
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this agent sales tools is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this agent sales tools is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this agent sales tools is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this agent sales tools is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}