/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FAQ service. Represents a row in the &quot;AP_FAQ&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.agencyportal.model.impl.FAQModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.agencyportal.model.impl.FAQImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see FAQ
 * @generated
 */
@ProviderType
public interface FAQModel
	extends BaseModel<FAQ>, GroupedModel, ShardedModel, TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a faq model instance should use the {@link FAQ} interface instead.
	 */

	/**
	 * Returns the primary key of this faq.
	 *
	 * @return the primary key of this faq
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this faq.
	 *
	 * @param primaryKey the primary key of this faq
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the faq ID of this faq.
	 *
	 * @return the faq ID of this faq
	 */
	public long getFaqId();

	/**
	 * Sets the faq ID of this faq.
	 *
	 * @param faqId the faq ID of this faq
	 */
	public void setFaqId(long faqId);

	/**
	 * Returns the title of this faq.
	 *
	 * @return the title of this faq
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this faq.
	 *
	 * @param title the title of this faq
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this faq.
	 *
	 * @return the description of this faq
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this faq.
	 *
	 * @param description the description of this faq
	 */
	public void setDescription(String description);

	/**
	 * Returns the category ID of this faq.
	 *
	 * @return the category ID of this faq
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this faq.
	 *
	 * @param categoryId the category ID of this faq
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the category of this faq.
	 *
	 * @return the category of this faq
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this faq.
	 *
	 * @param category the category of this faq
	 */
	public void setCategory(String category);

	/**
	 * Returns the active of this faq.
	 *
	 * @return the active of this faq
	 */
	public int getActive();

	/**
	 * Sets the active of this faq.
	 *
	 * @param active the active of this faq
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this faq.
	 *
	 * @return the group ID of this faq
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this faq.
	 *
	 * @param groupId the group ID of this faq
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this faq.
	 *
	 * @return the company ID of this faq
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this faq.
	 *
	 * @param companyId the company ID of this faq
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this faq.
	 *
	 * @return the user ID of this faq
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this faq.
	 *
	 * @param userId the user ID of this faq
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this faq.
	 *
	 * @return the user uuid of this faq
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this faq.
	 *
	 * @param userUuid the user uuid of this faq
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this faq.
	 *
	 * @return the user name of this faq
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this faq.
	 *
	 * @param userName the user name of this faq
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this faq.
	 *
	 * @return the create date of this faq
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this faq.
	 *
	 * @param createDate the create date of this faq
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this faq.
	 *
	 * @return the modified date of this faq
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this faq.
	 *
	 * @param modifiedDate the modified date of this faq
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this faq.
	 *
	 * @return the status of this faq
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this faq was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this faq.
	 *
	 * @return the trash entry created when this faq was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this faq.
	 *
	 * @return the class primary key of the trash entry for this faq
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this faq.
	 *
	 * @return the trash handler for this faq
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this faq is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this faq is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this faq is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this faq is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}