/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CreditType service. Represents a row in the &quot;CreditType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.CreditTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.CreditTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreditType
 * @generated
 */
@ProviderType
public interface CreditTypeModel
	extends BaseModel<CreditType>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a credit type model instance should use the {@link CreditType} interface instead.
	 */

	/**
	 * Returns the primary key of this credit type.
	 *
	 * @return the primary key of this credit type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this credit type.
	 *
	 * @param primaryKey the primary key of this credit type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the credit type ID of this credit type.
	 *
	 * @return the credit type ID of this credit type
	 */
	public long getCreditTypeId();

	/**
	 * Sets the credit type ID of this credit type.
	 *
	 * @param creditTypeId the credit type ID of this credit type
	 */
	public void setCreditTypeId(long creditTypeId);

	/**
	 * Returns the group ID of this credit type.
	 *
	 * @return the group ID of this credit type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this credit type.
	 *
	 * @param groupId the group ID of this credit type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this credit type.
	 *
	 * @return the company ID of this credit type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this credit type.
	 *
	 * @param companyId the company ID of this credit type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this credit type.
	 *
	 * @return the user ID of this credit type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this credit type.
	 *
	 * @param userId the user ID of this credit type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this credit type.
	 *
	 * @return the user uuid of this credit type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this credit type.
	 *
	 * @param userUuid the user uuid of this credit type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this credit type.
	 *
	 * @return the user name of this credit type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this credit type.
	 *
	 * @param userName the user name of this credit type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this credit type.
	 *
	 * @return the create date of this credit type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this credit type.
	 *
	 * @param createDate the create date of this credit type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this credit type.
	 *
	 * @return the modified date of this credit type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this credit type.
	 *
	 * @param modifiedDate the modified date of this credit type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the mypage user ID of this credit type.
	 *
	 * @return the mypage user ID of this credit type
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this credit type.
	 *
	 * @param mypageUserId the mypage user ID of this credit type
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this credit type.
	 *
	 * @return the mypage user uuid of this credit type
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this credit type.
	 *
	 * @param mypageUserUuid the mypage user uuid of this credit type
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the name of this credit type.
	 *
	 * @return the name of this credit type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this credit type.
	 *
	 * @param name the name of this credit type
	 */
	public void setName(String name);

	/**
	 * Returns the agent type of this credit type.
	 *
	 * @return the agent type of this credit type
	 */
	@AutoEscape
	public String getAgentType();

	/**
	 * Sets the agent type of this credit type.
	 *
	 * @param agentType the agent type of this credit type
	 */
	public void setAgentType(String agentType);

	/**
	 * Returns the limit of this credit type.
	 *
	 * @return the limit of this credit type
	 */
	public double getLimit();

	/**
	 * Sets the limit of this credit type.
	 *
	 * @param limit the limit of this credit type
	 */
	public void setLimit(double limit);

	/**
	 * Returns the override grace period of this credit type.
	 *
	 * @return the override grace period of this credit type
	 */
	public int getOverrideGracePeriod();

	/**
	 * Sets the override grace period of this credit type.
	 *
	 * @param overrideGracePeriod the override grace period of this credit type
	 */
	public void setOverrideGracePeriod(int overrideGracePeriod);

	/**
	 * Returns the nett premi allowed of this credit type.
	 *
	 * @return the nett premi allowed of this credit type
	 */
	public int getNettPremiAllowed();

	/**
	 * Sets the nett premi allowed of this credit type.
	 *
	 * @param nettPremiAllowed the nett premi allowed of this credit type
	 */
	public void setNettPremiAllowed(int nettPremiAllowed);

	/**
	 * Returns the active of this credit type.
	 *
	 * @return the active of this credit type
	 */
	public int getActive();

	/**
	 * Sets the active of this credit type.
	 *
	 * @param active the active of this credit type
	 */
	public void setActive(int active);

}