/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MypageGroupUser service. Represents a row in the &quot;MypageGroupUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.MypageGroupUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.MypageGroupUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageGroupUser
 * @generated
 */
@ProviderType
public interface MypageGroupUserModel
	extends BaseModel<MypageGroupUser>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mypage group user model instance should use the {@link MypageGroupUser} interface instead.
	 */

	/**
	 * Returns the primary key of this mypage group user.
	 *
	 * @return the primary key of this mypage group user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mypage group user.
	 *
	 * @param primaryKey the primary key of this mypage group user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mypage group user ID of this mypage group user.
	 *
	 * @return the mypage group user ID of this mypage group user
	 */
	public long getMypageGroupUserId();

	/**
	 * Sets the mypage group user ID of this mypage group user.
	 *
	 * @param mypageGroupUserId the mypage group user ID of this mypage group user
	 */
	public void setMypageGroupUserId(long mypageGroupUserId);

	/**
	 * Returns the mypage group user uuid of this mypage group user.
	 *
	 * @return the mypage group user uuid of this mypage group user
	 */
	public String getMypageGroupUserUuid();

	/**
	 * Sets the mypage group user uuid of this mypage group user.
	 *
	 * @param mypageGroupUserUuid the mypage group user uuid of this mypage group user
	 */
	public void setMypageGroupUserUuid(String mypageGroupUserUuid);

	/**
	 * Returns the mypage group ID of this mypage group user.
	 *
	 * @return the mypage group ID of this mypage group user
	 */
	public long getMypageGroupId();

	/**
	 * Sets the mypage group ID of this mypage group user.
	 *
	 * @param mypageGroupId the mypage group ID of this mypage group user
	 */
	public void setMypageGroupId(long mypageGroupId);

	/**
	 * Returns the mypage user ID of this mypage group user.
	 *
	 * @return the mypage user ID of this mypage group user
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this mypage group user.
	 *
	 * @param mypageUserId the mypage user ID of this mypage group user
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this mypage group user.
	 *
	 * @return the mypage user uuid of this mypage group user
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this mypage group user.
	 *
	 * @param mypageUserUuid the mypage user uuid of this mypage group user
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the group ID of this mypage group user.
	 *
	 * @return the group ID of this mypage group user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this mypage group user.
	 *
	 * @param groupId the group ID of this mypage group user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mypage group user.
	 *
	 * @return the company ID of this mypage group user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mypage group user.
	 *
	 * @param companyId the company ID of this mypage group user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mypage group user.
	 *
	 * @return the user ID of this mypage group user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mypage group user.
	 *
	 * @param userId the user ID of this mypage group user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mypage group user.
	 *
	 * @return the user uuid of this mypage group user
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mypage group user.
	 *
	 * @param userUuid the user uuid of this mypage group user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mypage group user.
	 *
	 * @return the user name of this mypage group user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mypage group user.
	 *
	 * @param userName the user name of this mypage group user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mypage group user.
	 *
	 * @return the create date of this mypage group user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mypage group user.
	 *
	 * @param createDate the create date of this mypage group user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mypage group user.
	 *
	 * @return the modified date of this mypage group user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mypage group user.
	 *
	 * @param modifiedDate the modified date of this mypage group user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}