/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MypageUserTimeline service. Represents a row in the &quot;MypageUserTimeline&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.MypageUserTimelineModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.MypageUserTimelineImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageUserTimeline
 * @generated
 */
@ProviderType
public interface MypageUserTimelineModel
	extends BaseModel<MypageUserTimeline>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mypage user timeline model instance should use the {@link MypageUserTimeline} interface instead.
	 */

	/**
	 * Returns the primary key of this mypage user timeline.
	 *
	 * @return the primary key of this mypage user timeline
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mypage user timeline.
	 *
	 * @param primaryKey the primary key of this mypage user timeline
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mypage user timeline ID of this mypage user timeline.
	 *
	 * @return the mypage user timeline ID of this mypage user timeline
	 */
	public long getMypageUserTimelineId();

	/**
	 * Sets the mypage user timeline ID of this mypage user timeline.
	 *
	 * @param mypageUserTimelineId the mypage user timeline ID of this mypage user timeline
	 */
	public void setMypageUserTimelineId(long mypageUserTimelineId);

	/**
	 * Returns the group ID of this mypage user timeline.
	 *
	 * @return the group ID of this mypage user timeline
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this mypage user timeline.
	 *
	 * @param groupId the group ID of this mypage user timeline
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mypage user timeline.
	 *
	 * @return the company ID of this mypage user timeline
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mypage user timeline.
	 *
	 * @param companyId the company ID of this mypage user timeline
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mypage user timeline.
	 *
	 * @return the user ID of this mypage user timeline
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mypage user timeline.
	 *
	 * @param userId the user ID of this mypage user timeline
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mypage user timeline.
	 *
	 * @return the user uuid of this mypage user timeline
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mypage user timeline.
	 *
	 * @param userUuid the user uuid of this mypage user timeline
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mypage user timeline.
	 *
	 * @return the user name of this mypage user timeline
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mypage user timeline.
	 *
	 * @param userName the user name of this mypage user timeline
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mypage user timeline.
	 *
	 * @return the create date of this mypage user timeline
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mypage user timeline.
	 *
	 * @param createDate the create date of this mypage user timeline
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mypage user timeline.
	 *
	 * @return the modified date of this mypage user timeline
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mypage user timeline.
	 *
	 * @param modifiedDate the modified date of this mypage user timeline
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the mypage user ID of this mypage user timeline.
	 *
	 * @return the mypage user ID of this mypage user timeline
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this mypage user timeline.
	 *
	 * @param mypageUserId the mypage user ID of this mypage user timeline
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this mypage user timeline.
	 *
	 * @return the mypage user uuid of this mypage user timeline
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this mypage user timeline.
	 *
	 * @param mypageUserUuid the mypage user uuid of this mypage user timeline
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the img upload timeline entry ID of this mypage user timeline.
	 *
	 * @return the img upload timeline entry ID of this mypage user timeline
	 */
	public long getImgUploadTimelineEntryId();

	/**
	 * Sets the img upload timeline entry ID of this mypage user timeline.
	 *
	 * @param imgUploadTimelineEntryId the img upload timeline entry ID of this mypage user timeline
	 */
	public void setImgUploadTimelineEntryId(long imgUploadTimelineEntryId);

	/**
	 * Returns the img upload timeline url of this mypage user timeline.
	 *
	 * @return the img upload timeline url of this mypage user timeline
	 */
	@AutoEscape
	public String getImgUploadTimelineUrl();

	/**
	 * Sets the img upload timeline url of this mypage user timeline.
	 *
	 * @param imgUploadTimelineUrl the img upload timeline url of this mypage user timeline
	 */
	public void setImgUploadTimelineUrl(String imgUploadTimelineUrl);

	/**
	 * Returns the video upload timeline url of this mypage user timeline.
	 *
	 * @return the video upload timeline url of this mypage user timeline
	 */
	@AutoEscape
	public String getVideoUploadTimelineUrl();

	/**
	 * Sets the video upload timeline url of this mypage user timeline.
	 *
	 * @param videoUploadTimelineUrl the video upload timeline url of this mypage user timeline
	 */
	public void setVideoUploadTimelineUrl(String videoUploadTimelineUrl);

	/**
	 * Returns the text of this mypage user timeline.
	 *
	 * @return the text of this mypage user timeline
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this mypage user timeline.
	 *
	 * @param text the text of this mypage user timeline
	 */
	public void setText(String text);

}