/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MypageUserWorkingHour service. Represents a row in the &quot;MypageUserWorkingHour&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.MypageUserWorkingHourModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.MypageUserWorkingHourImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageUserWorkingHour
 * @generated
 */
@ProviderType
public interface MypageUserWorkingHourModel
	extends BaseModel<MypageUserWorkingHour>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mypage user working hour model instance should use the {@link MypageUserWorkingHour} interface instead.
	 */

	/**
	 * Returns the primary key of this mypage user working hour.
	 *
	 * @return the primary key of this mypage user working hour
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mypage user working hour.
	 *
	 * @param primaryKey the primary key of this mypage user working hour
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mypage user working hour ID of this mypage user working hour.
	 *
	 * @return the mypage user working hour ID of this mypage user working hour
	 */
	public long getMypageUserWorkingHourId();

	/**
	 * Sets the mypage user working hour ID of this mypage user working hour.
	 *
	 * @param mypageUserWorkingHourId the mypage user working hour ID of this mypage user working hour
	 */
	public void setMypageUserWorkingHourId(long mypageUserWorkingHourId);

	/**
	 * Returns the group ID of this mypage user working hour.
	 *
	 * @return the group ID of this mypage user working hour
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this mypage user working hour.
	 *
	 * @param groupId the group ID of this mypage user working hour
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mypage user working hour.
	 *
	 * @return the company ID of this mypage user working hour
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mypage user working hour.
	 *
	 * @param companyId the company ID of this mypage user working hour
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mypage user working hour.
	 *
	 * @return the user ID of this mypage user working hour
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mypage user working hour.
	 *
	 * @param userId the user ID of this mypage user working hour
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mypage user working hour.
	 *
	 * @return the user uuid of this mypage user working hour
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mypage user working hour.
	 *
	 * @param userUuid the user uuid of this mypage user working hour
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mypage user working hour.
	 *
	 * @return the user name of this mypage user working hour
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mypage user working hour.
	 *
	 * @param userName the user name of this mypage user working hour
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mypage user working hour.
	 *
	 * @return the create date of this mypage user working hour
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mypage user working hour.
	 *
	 * @param createDate the create date of this mypage user working hour
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mypage user working hour.
	 *
	 * @return the modified date of this mypage user working hour
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mypage user working hour.
	 *
	 * @param modifiedDate the modified date of this mypage user working hour
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the mypage user ID of this mypage user working hour.
	 *
	 * @return the mypage user ID of this mypage user working hour
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this mypage user working hour.
	 *
	 * @param mypageUserId the mypage user ID of this mypage user working hour
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this mypage user working hour.
	 *
	 * @return the mypage user uuid of this mypage user working hour
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this mypage user working hour.
	 *
	 * @param mypageUserUuid the mypage user uuid of this mypage user working hour
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the day of this mypage user working hour.
	 *
	 * @return the day of this mypage user working hour
	 */
	@AutoEscape
	public String getDay();

	/**
	 * Sets the day of this mypage user working hour.
	 *
	 * @param day the day of this mypage user working hour
	 */
	public void setDay(String day);

	/**
	 * Returns the start time of this mypage user working hour.
	 *
	 * @return the start time of this mypage user working hour
	 */
	@AutoEscape
	public String getStartTime();

	/**
	 * Sets the start time of this mypage user working hour.
	 *
	 * @param startTime the start time of this mypage user working hour
	 */
	public void setStartTime(String startTime);

	/**
	 * Returns the end time of this mypage user working hour.
	 *
	 * @return the end time of this mypage user working hour
	 */
	@AutoEscape
	public String getEndTime();

	/**
	 * Sets the end time of this mypage user working hour.
	 *
	 * @param endTime the end time of this mypage user working hour
	 */
	public void setEndTime(String endTime);

	/**
	 * Returns the status of this mypage user working hour.
	 *
	 * @return the status of this mypage user working hour
	 */
	public int getStatus();

	/**
	 * Sets the status of this mypage user working hour.
	 *
	 * @param status the status of this mypage user working hour
	 */
	public void setStatus(int status);

}