/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MypageUser service. Represents a row in the &quot;MypageUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.MypageUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.MypageUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageUser
 * @generated
 */
@ProviderType
public interface MypageUserModel
	extends BaseModel<MypageUser>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mypage user model instance should use the {@link MypageUser} interface instead.
	 */

	/**
	 * Returns the primary key of this mypage user.
	 *
	 * @return the primary key of this mypage user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mypage user.
	 *
	 * @param primaryKey the primary key of this mypage user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mypage user ID of this mypage user.
	 *
	 * @return the mypage user ID of this mypage user
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this mypage user.
	 *
	 * @param mypageUserId the mypage user ID of this mypage user
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this mypage user.
	 *
	 * @return the mypage user uuid of this mypage user
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this mypage user.
	 *
	 * @param mypageUserUuid the mypage user uuid of this mypage user
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the group ID of this mypage user.
	 *
	 * @return the group ID of this mypage user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this mypage user.
	 *
	 * @param groupId the group ID of this mypage user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mypage user.
	 *
	 * @return the company ID of this mypage user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mypage user.
	 *
	 * @param companyId the company ID of this mypage user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mypage user.
	 *
	 * @return the user ID of this mypage user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mypage user.
	 *
	 * @param userId the user ID of this mypage user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mypage user.
	 *
	 * @return the user uuid of this mypage user
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mypage user.
	 *
	 * @param userUuid the user uuid of this mypage user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mypage user.
	 *
	 * @return the user name of this mypage user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mypage user.
	 *
	 * @param userName the user name of this mypage user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mypage user.
	 *
	 * @return the create date of this mypage user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mypage user.
	 *
	 * @param createDate the create date of this mypage user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mypage user.
	 *
	 * @return the modified date of this mypage user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mypage user.
	 *
	 * @param modifiedDate the modified date of this mypage user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the liferay user ID of this mypage user.
	 *
	 * @return the liferay user ID of this mypage user
	 */
	public long getLiferayUserId();

	/**
	 * Sets the liferay user ID of this mypage user.
	 *
	 * @param liferayUserId the liferay user ID of this mypage user
	 */
	public void setLiferayUserId(long liferayUserId);

	/**
	 * Returns the liferay user uuid of this mypage user.
	 *
	 * @return the liferay user uuid of this mypage user
	 */
	public String getLiferayUserUuid();

	/**
	 * Sets the liferay user uuid of this mypage user.
	 *
	 * @param liferayUserUuid the liferay user uuid of this mypage user
	 */
	public void setLiferayUserUuid(String liferayUserUuid);

	/**
	 * Returns the user password of this mypage user.
	 *
	 * @return the user password of this mypage user
	 */
	@AutoEscape
	public String getUserPassword();

	/**
	 * Sets the user password of this mypage user.
	 *
	 * @param userPassword the user password of this mypage user
	 */
	public void setUserPassword(String userPassword);

	/**
	 * Returns the agent flag of this mypage user.
	 *
	 * @return the agent flag of this mypage user
	 */
	@AutoEscape
	public String getAgentFlag();

	/**
	 * Sets the agent flag of this mypage user.
	 *
	 * @param agentFlag the agent flag of this mypage user
	 */
	public void setAgentFlag(String agentFlag);

	/**
	 * Returns the user parent of this mypage user.
	 *
	 * @return the user parent of this mypage user
	 */
	public long getUserParent();

	/**
	 * Sets the user parent of this mypage user.
	 *
	 * @param userParent the user parent of this mypage user
	 */
	public void setUserParent(long userParent);

	/**
	 * Returns the user branch of this mypage user.
	 *
	 * @return the user branch of this mypage user
	 */
	public long getUserBranch();

	/**
	 * Sets the user branch of this mypage user.
	 *
	 * @param userBranch the user branch of this mypage user
	 */
	public void setUserBranch(long userBranch);

	/**
	 * Returns the mypage user role ID of this mypage user.
	 *
	 * @return the mypage user role ID of this mypage user
	 */
	public long getMypageUserRoleId();

	/**
	 * Sets the mypage user role ID of this mypage user.
	 *
	 * @param mypageUserRoleId the mypage user role ID of this mypage user
	 */
	public void setMypageUserRoleId(long mypageUserRoleId);

	/**
	 * Returns the status of this mypage user.
	 *
	 * @return the status of this mypage user
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this mypage user.
	 *
	 * @param status the status of this mypage user
	 */
	public void setStatus(String status);

	/**
	 * Returns the credit status of this mypage user.
	 *
	 * @return the credit status of this mypage user
	 */
	@AutoEscape
	public String getCreditStatus();

	/**
	 * Sets the credit status of this mypage user.
	 *
	 * @param creditStatus the credit status of this mypage user
	 */
	public void setCreditStatus(String creditStatus);

	/**
	 * Returns the credit wallet ID of this mypage user.
	 *
	 * @return the credit wallet ID of this mypage user
	 */
	public long getCreditWalletId();

	/**
	 * Sets the credit wallet ID of this mypage user.
	 *
	 * @param creditWalletId the credit wallet ID of this mypage user
	 */
	public void setCreditWalletId(long creditWalletId);

	/**
	 * Returns the cash payment of this mypage user.
	 *
	 * @return the cash payment of this mypage user
	 */
	public int getCashPayment();

	/**
	 * Sets the cash payment of this mypage user.
	 *
	 * @param cashPayment the cash payment of this mypage user
	 */
	public void setCashPayment(int cashPayment);

	/**
	 * Returns the payment method of this mypage user.
	 *
	 * @return the payment method of this mypage user
	 */
	@AutoEscape
	public String getPaymentMethod();

	/**
	 * Sets the payment method of this mypage user.
	 *
	 * @param paymentMethod the payment method of this mypage user
	 */
	public void setPaymentMethod(String paymentMethod);

	/**
	 * Returns the login counter of this mypage user.
	 *
	 * @return the login counter of this mypage user
	 */
	public int getLoginCounter();

	/**
	 * Sets the login counter of this mypage user.
	 *
	 * @param loginCounter the login counter of this mypage user
	 */
	public void setLoginCounter(int loginCounter);

	/**
	 * Returns the last submit login date of this mypage user.
	 *
	 * @return the last submit login date of this mypage user
	 */
	public Date getLastSubmitLoginDate();

	/**
	 * Sets the last submit login date of this mypage user.
	 *
	 * @param lastSubmitLoginDate the last submit login date of this mypage user
	 */
	public void setLastSubmitLoginDate(Date lastSubmitLoginDate);

	/**
	 * Returns the temp code of this mypage user.
	 *
	 * @return the temp code of this mypage user
	 */
	@AutoEscape
	public String getTempCode();

	/**
	 * Sets the temp code of this mypage user.
	 *
	 * @param TempCode the temp code of this mypage user
	 */
	public void setTempCode(String TempCode);

	/**
	 * Returns the temp code expiry date of this mypage user.
	 *
	 * @return the temp code expiry date of this mypage user
	 */
	public Date getTempCodeExpiryDate();

	/**
	 * Sets the temp code expiry date of this mypage user.
	 *
	 * @param TempCodeExpiryDate the temp code expiry date of this mypage user
	 */
	public void setTempCodeExpiryDate(Date TempCodeExpiryDate);

	/**
	 * Returns the phone of this mypage user.
	 *
	 * @return the phone of this mypage user
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this mypage user.
	 *
	 * @param phone the phone of this mypage user
	 */
	public void setPhone(String phone);

	/**
	 * Returns the mobile phone of this mypage user.
	 *
	 * @return the mobile phone of this mypage user
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this mypage user.
	 *
	 * @param mobilePhone the mobile phone of this mypage user
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the email of this mypage user.
	 *
	 * @return the email of this mypage user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this mypage user.
	 *
	 * @param email the email of this mypage user
	 */
	public void setEmail(String email);

	/**
	 * Returns the birth place of this mypage user.
	 *
	 * @return the birth place of this mypage user
	 */
	@AutoEscape
	public String getBirthPlace();

	/**
	 * Sets the birth place of this mypage user.
	 *
	 * @param birthPlace the birth place of this mypage user
	 */
	public void setBirthPlace(String birthPlace);

	/**
	 * Returns the dob of this mypage user.
	 *
	 * @return the dob of this mypage user
	 */
	public Date getDob();

	/**
	 * Sets the dob of this mypage user.
	 *
	 * @param dob the dob of this mypage user
	 */
	public void setDob(Date dob);

	/**
	 * Returns the id number of this mypage user.
	 *
	 * @return the id number of this mypage user
	 */
	@AutoEscape
	public String getIdNumber();

	/**
	 * Sets the id number of this mypage user.
	 *
	 * @param idNumber the id number of this mypage user
	 */
	public void setIdNumber(String idNumber);

	/**
	 * Returns the address of this mypage user.
	 *
	 * @return the address of this mypage user
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this mypage user.
	 *
	 * @param address the address of this mypage user
	 */
	public void setAddress(String address);

	/**
	 * Returns the zip of this mypage user.
	 *
	 * @return the zip of this mypage user
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this mypage user.
	 *
	 * @param zip the zip of this mypage user
	 */
	public void setZip(String zip);

	/**
	 * Returns the gender of this mypage user.
	 *
	 * @return the gender of this mypage user
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this mypage user.
	 *
	 * @param gender the gender of this mypage user
	 */
	public void setGender(String gender);

	/**
	 * Returns the country of this mypage user.
	 *
	 * @return the country of this mypage user
	 */
	public long getCountry();

	/**
	 * Sets the country of this mypage user.
	 *
	 * @param country the country of this mypage user
	 */
	public void setCountry(long country);

	/**
	 * Returns the province of this mypage user.
	 *
	 * @return the province of this mypage user
	 */
	public long getProvince();

	/**
	 * Sets the province of this mypage user.
	 *
	 * @param province the province of this mypage user
	 */
	public void setProvince(long province);

	/**
	 * Returns the city of this mypage user.
	 *
	 * @return the city of this mypage user
	 */
	public long getCity();

	/**
	 * Sets the city of this mypage user.
	 *
	 * @param city the city of this mypage user
	 */
	public void setCity(long city);

	/**
	 * Returns the latitude of this mypage user.
	 *
	 * @return the latitude of this mypage user
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this mypage user.
	 *
	 * @param latitude the latitude of this mypage user
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the longitude of this mypage user.
	 *
	 * @return the longitude of this mypage user
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this mypage user.
	 *
	 * @param longitude the longitude of this mypage user
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the position zoom of this mypage user.
	 *
	 * @return the position zoom of this mypage user
	 */
	public int getPositionZoom();

	/**
	 * Sets the position zoom of this mypage user.
	 *
	 * @param positionZoom the position zoom of this mypage user
	 */
	public void setPositionZoom(int positionZoom);

	/**
	 * Returns the code of this mypage user.
	 *
	 * @return the code of this mypage user
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this mypage user.
	 *
	 * @param code the code of this mypage user
	 */
	public void setCode(String code);

	/**
	 * Returns the branch of this mypage user.
	 *
	 * @return the branch of this mypage user
	 */
	public long getBranch();

	/**
	 * Sets the branch of this mypage user.
	 *
	 * @param branch the branch of this mypage user
	 */
	public void setBranch(long branch);

	/**
	 * Returns the promo code of this mypage user.
	 *
	 * @return the promo code of this mypage user
	 */
	@AutoEscape
	public String getPromoCode();

	/**
	 * Sets the promo code of this mypage user.
	 *
	 * @param promoCode the promo code of this mypage user
	 */
	public void setPromoCode(String promoCode);

	/**
	 * Returns the ags promo code of this mypage user.
	 *
	 * @return the ags promo code of this mypage user
	 */
	@AutoEscape
	public String getAgsPromoCode();

	/**
	 * Sets the ags promo code of this mypage user.
	 *
	 * @param agsPromoCode the ags promo code of this mypage user
	 */
	public void setAgsPromoCode(String agsPromoCode);

	/**
	 * Returns the deptore code of this mypage user.
	 *
	 * @return the deptore code of this mypage user
	 */
	@AutoEscape
	public String getDeptoreCode();

	/**
	 * Sets the deptore code of this mypage user.
	 *
	 * @param deptoreCode the deptore code of this mypage user
	 */
	public void setDeptoreCode(String deptoreCode);

	/**
	 * Returns the club of this mypage user.
	 *
	 * @return the club of this mypage user
	 */
	@AutoEscape
	public String getClub();

	/**
	 * Sets the club of this mypage user.
	 *
	 * @param club the club of this mypage user
	 */
	public void setClub(String club);

	/**
	 * Returns the leader of this mypage user.
	 *
	 * @return the leader of this mypage user
	 */
	public long getLeader();

	/**
	 * Sets the leader of this mypage user.
	 *
	 * @param leader the leader of this mypage user
	 */
	public void setLeader(long leader);

	/**
	 * Returns the status agent of this mypage user.
	 *
	 * @return the status agent of this mypage user
	 */
	@AutoEscape
	public String getStatusAgent();

	/**
	 * Sets the status agent of this mypage user.
	 *
	 * @param statusAgent the status agent of this mypage user
	 */
	public void setStatusAgent(String statusAgent);

	/**
	 * Returns the license number of this mypage user.
	 *
	 * @return the license number of this mypage user
	 */
	@AutoEscape
	public String getLicenseNumber();

	/**
	 * Sets the license number of this mypage user.
	 *
	 * @param licenseNumber the license number of this mypage user
	 */
	public void setLicenseNumber(String licenseNumber);

	/**
	 * Returns the join date of this mypage user.
	 *
	 * @return the join date of this mypage user
	 */
	public Date getJoinDate();

	/**
	 * Sets the join date of this mypage user.
	 *
	 * @param joinDate the join date of this mypage user
	 */
	public void setJoinDate(Date joinDate);

	/**
	 * Returns the end date of this mypage user.
	 *
	 * @return the end date of this mypage user
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this mypage user.
	 *
	 * @param endDate the end date of this mypage user
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the pretty url of this mypage user.
	 *
	 * @return the pretty url of this mypage user
	 */
	@AutoEscape
	public String getPrettyUrl();

	/**
	 * Sets the pretty url of this mypage user.
	 *
	 * @param prettyUrl the pretty url of this mypage user
	 */
	public void setPrettyUrl(String prettyUrl);

	/**
	 * Returns the pretty url change of this mypage user.
	 *
	 * @return the pretty url change of this mypage user
	 */
	public int getPrettyUrlChange();

	/**
	 * Sets the pretty url change of this mypage user.
	 *
	 * @param prettyUrlChange the pretty url change of this mypage user
	 */
	public void setPrettyUrlChange(int prettyUrlChange);

	/**
	 * Returns the tax rate of this mypage user.
	 *
	 * @return the tax rate of this mypage user
	 */
	public double getTaxRate();

	/**
	 * Sets the tax rate of this mypage user.
	 *
	 * @param taxRate the tax rate of this mypage user
	 */
	public void setTaxRate(double taxRate);

	/**
	 * Returns the visited count of this mypage user.
	 *
	 * @return the visited count of this mypage user
	 */
	public int getVisitedCount();

	/**
	 * Sets the visited count of this mypage user.
	 *
	 * @param visitedCount the visited count of this mypage user
	 */
	public void setVisitedCount(int visitedCount);

	/**
	 * Returns the is partnership of this mypage user.
	 *
	 * @return the is partnership of this mypage user
	 */
	public int getIsPartnership();

	/**
	 * Sets the is partnership of this mypage user.
	 *
	 * @param isPartnership the is partnership of this mypage user
	 */
	public void setIsPartnership(int isPartnership);

	/**
	 * Returns the partnership name of this mypage user.
	 *
	 * @return the partnership name of this mypage user
	 */
	@AutoEscape
	public String getPartnershipName();

	/**
	 * Sets the partnership name of this mypage user.
	 *
	 * @param partnershipName the partnership name of this mypage user
	 */
	public void setPartnershipName(String partnershipName);

	/**
	 * Returns the def comm partner mv of this mypage user.
	 *
	 * @return the def comm partner mv of this mypage user
	 */
	public double getDefCommPartnerMV();

	/**
	 * Sets the def comm partner mv of this mypage user.
	 *
	 * @param defCommPartnerMV the def comm partner mv of this mypage user
	 */
	public void setDefCommPartnerMV(double defCommPartnerMV);

	/**
	 * Returns the def comm partner eh of this mypage user.
	 *
	 * @return the def comm partner eh of this mypage user
	 */
	public double getDefCommPartnerEH();

	/**
	 * Sets the def comm partner eh of this mypage user.
	 *
	 * @param defCommPartnerEH the def comm partner eh of this mypage user
	 */
	public void setDefCommPartnerEH(double defCommPartnerEH);

	/**
	 * Returns the def comm partner dt of this mypage user.
	 *
	 * @return the def comm partner dt of this mypage user
	 */
	public double getDefCommPartnerDT();

	/**
	 * Sets the def comm partner dt of this mypage user.
	 *
	 * @param defCommPartnerDT the def comm partner dt of this mypage user
	 */
	public void setDefCommPartnerDT(double defCommPartnerDT);

	/**
	 * Returns the def comm partner it of this mypage user.
	 *
	 * @return the def comm partner it of this mypage user
	 */
	public double getDefCommPartnerIT();

	/**
	 * Sets the def comm partner it of this mypage user.
	 *
	 * @param defCommPartnerIT the def comm partner it of this mypage user
	 */
	public void setDefCommPartnerIT(double defCommPartnerIT);

	/**
	 * Returns the def comm partner sme of this mypage user.
	 *
	 * @return the def comm partner sme of this mypage user
	 */
	public double getDefCommPartnerSME();

	/**
	 * Sets the def comm partner sme of this mypage user.
	 *
	 * @param defCommPartnerSME the def comm partner sme of this mypage user
	 */
	public void setDefCommPartnerSME(double defCommPartnerSME);

	/**
	 * Returns the def comm partner property of this mypage user.
	 *
	 * @return the def comm partner property of this mypage user
	 */
	public double getDefCommPartnerProperty();

	/**
	 * Sets the def comm partner property of this mypage user.
	 *
	 * @param defCommPartnerProperty the def comm partner property of this mypage user
	 */
	public void setDefCommPartnerProperty(double defCommPartnerProperty);

	/**
	 * Returns the def comm partner pet of this mypage user.
	 *
	 * @return the def comm partner pet of this mypage user
	 */
	public double getDefCommPartnerPet();

	/**
	 * Sets the def comm partner pet of this mypage user.
	 *
	 * @param defCommPartnerPet the def comm partner pet of this mypage user
	 */
	public void setDefCommPartnerPet(double defCommPartnerPet);

	/**
	 * Returns the def comm partner pa of this mypage user.
	 *
	 * @return the def comm partner pa of this mypage user
	 */
	public double getDefCommPartnerPA();

	/**
	 * Sets the def comm partner pa of this mypage user.
	 *
	 * @param defCommPartnerPA the def comm partner pa of this mypage user
	 */
	public void setDefCommPartnerPA(double defCommPartnerPA);

	/**
	 * Returns the def comm partner gp of this mypage user.
	 *
	 * @return the def comm partner gp of this mypage user
	 */
	public double getDefCommPartnerGP();

	/**
	 * Sets the def comm partner gp of this mypage user.
	 *
	 * @param defCommPartnerGP the def comm partner gp of this mypage user
	 */
	public void setDefCommPartnerGP(double defCommPartnerGP);

	/**
	 * Returns the banner image url of this mypage user.
	 *
	 * @return the banner image url of this mypage user
	 */
	@AutoEscape
	public String getBannerImageURL();

	/**
	 * Sets the banner image url of this mypage user.
	 *
	 * @param bannerImageURL the banner image url of this mypage user
	 */
	public void setBannerImageURL(String bannerImageURL);

	/**
	 * Returns the banner image file entry ID of this mypage user.
	 *
	 * @return the banner image file entry ID of this mypage user
	 */
	public Long getBannerImageFileEntryId();

	/**
	 * Sets the banner image file entry ID of this mypage user.
	 *
	 * @param bannerImageFileEntryId the banner image file entry ID of this mypage user
	 */
	public void setBannerImageFileEntryId(Long bannerImageFileEntryId);

	/**
	 * Returns the profile image url of this mypage user.
	 *
	 * @return the profile image url of this mypage user
	 */
	@AutoEscape
	public String getProfileImageURL();

	/**
	 * Sets the profile image url of this mypage user.
	 *
	 * @param profileImageURL the profile image url of this mypage user
	 */
	public void setProfileImageURL(String profileImageURL);

	/**
	 * Returns the profile image file entry ID of this mypage user.
	 *
	 * @return the profile image file entry ID of this mypage user
	 */
	public Long getProfileImageFileEntryId();

	/**
	 * Sets the profile image file entry ID of this mypage user.
	 *
	 * @param profileImageFileEntryId the profile image file entry ID of this mypage user
	 */
	public void setProfileImageFileEntryId(Long profileImageFileEntryId);

	/**
	 * Returns the my title of this mypage user.
	 *
	 * @return the my title of this mypage user
	 */
	@AutoEscape
	public String getMyTitle();

	/**
	 * Sets the my title of this mypage user.
	 *
	 * @param myTitle the my title of this mypage user
	 */
	public void setMyTitle(String myTitle);

	/**
	 * Returns the my video of this mypage user.
	 *
	 * @return the my video of this mypage user
	 */
	@AutoEscape
	public String getMyVideo();

	/**
	 * Sets the my video of this mypage user.
	 *
	 * @param myVideo the my video of this mypage user
	 */
	public void setMyVideo(String myVideo);

	/**
	 * Returns the about me of this mypage user.
	 *
	 * @return the about me of this mypage user
	 */
	@AutoEscape
	public String getAboutMe();

	/**
	 * Sets the about me of this mypage user.
	 *
	 * @param aboutMe the about me of this mypage user
	 */
	public void setAboutMe(String aboutMe);

	/**
	 * Returns the facebook of this mypage user.
	 *
	 * @return the facebook of this mypage user
	 */
	@AutoEscape
	public String getFacebook();

	/**
	 * Sets the facebook of this mypage user.
	 *
	 * @param facebook the facebook of this mypage user
	 */
	public void setFacebook(String facebook);

	/**
	 * Returns the tiktok of this mypage user.
	 *
	 * @return the tiktok of this mypage user
	 */
	@AutoEscape
	public String getTiktok();

	/**
	 * Sets the tiktok of this mypage user.
	 *
	 * @param tiktok the tiktok of this mypage user
	 */
	public void setTiktok(String tiktok);

	/**
	 * Returns the instagram of this mypage user.
	 *
	 * @return the instagram of this mypage user
	 */
	@AutoEscape
	public String getInstagram();

	/**
	 * Sets the instagram of this mypage user.
	 *
	 * @param instagram the instagram of this mypage user
	 */
	public void setInstagram(String instagram);

	/**
	 * Returns the twitter of this mypage user.
	 *
	 * @return the twitter of this mypage user
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this mypage user.
	 *
	 * @param twitter the twitter of this mypage user
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the linked in of this mypage user.
	 *
	 * @return the linked in of this mypage user
	 */
	@AutoEscape
	public String getLinkedIn();

	/**
	 * Sets the linked in of this mypage user.
	 *
	 * @param linkedIn the linked in of this mypage user
	 */
	public void setLinkedIn(String linkedIn);

	/**
	 * Returns the blog of this mypage user.
	 *
	 * @return the blog of this mypage user
	 */
	@AutoEscape
	public String getBlog();

	/**
	 * Sets the blog of this mypage user.
	 *
	 * @param blog the blog of this mypage user
	 */
	public void setBlog(String blog);

	/**
	 * Returns the whatsapp of this mypage user.
	 *
	 * @return the whatsapp of this mypage user
	 */
	@AutoEscape
	public String getWhatsapp();

	/**
	 * Sets the whatsapp of this mypage user.
	 *
	 * @param whatsapp the whatsapp of this mypage user
	 */
	public void setWhatsapp(String whatsapp);

	/**
	 * Returns the skype of this mypage user.
	 *
	 * @return the skype of this mypage user
	 */
	@AutoEscape
	public String getSkype();

	/**
	 * Sets the skype of this mypage user.
	 *
	 * @param skype the skype of this mypage user
	 */
	public void setSkype(String skype);

	/**
	 * Returns the is24 hours of this mypage user.
	 *
	 * @return the is24 hours of this mypage user
	 */
	public int getIs24Hours();

	/**
	 * Sets the is24 hours of this mypage user.
	 *
	 * @param is24Hours the is24 hours of this mypage user
	 */
	public void setIs24Hours(int is24Hours);

	/**
	 * Returns the active of this mypage user.
	 *
	 * @return the active of this mypage user
	 */
	public int getActive();

	/**
	 * Sets the active of this mypage user.
	 *
	 * @param active the active of this mypage user
	 */
	public void setActive(int active);

}