/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MypageUserLicenses service. Represents a row in the &quot;MypageUserLicenses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.MypageUserLicensesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.MypageUserLicensesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageUserLicenses
 * @generated
 */
@ProviderType
public interface MypageUserLicensesModel
	extends BaseModel<MypageUserLicenses>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mypage user licenses model instance should use the {@link MypageUserLicenses} interface instead.
	 */

	/**
	 * Returns the primary key of this mypage user licenses.
	 *
	 * @return the primary key of this mypage user licenses
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mypage user licenses.
	 *
	 * @param primaryKey the primary key of this mypage user licenses
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mypage user licenses ID of this mypage user licenses.
	 *
	 * @return the mypage user licenses ID of this mypage user licenses
	 */
	public long getMypageUserLicensesId();

	/**
	 * Sets the mypage user licenses ID of this mypage user licenses.
	 *
	 * @param mypageUserLicensesId the mypage user licenses ID of this mypage user licenses
	 */
	public void setMypageUserLicensesId(long mypageUserLicensesId);

	/**
	 * Returns the group ID of this mypage user licenses.
	 *
	 * @return the group ID of this mypage user licenses
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this mypage user licenses.
	 *
	 * @param groupId the group ID of this mypage user licenses
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this mypage user licenses.
	 *
	 * @return the company ID of this mypage user licenses
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mypage user licenses.
	 *
	 * @param companyId the company ID of this mypage user licenses
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mypage user licenses.
	 *
	 * @return the user ID of this mypage user licenses
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mypage user licenses.
	 *
	 * @param userId the user ID of this mypage user licenses
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mypage user licenses.
	 *
	 * @return the user uuid of this mypage user licenses
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mypage user licenses.
	 *
	 * @param userUuid the user uuid of this mypage user licenses
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mypage user licenses.
	 *
	 * @return the user name of this mypage user licenses
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mypage user licenses.
	 *
	 * @param userName the user name of this mypage user licenses
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mypage user licenses.
	 *
	 * @return the create date of this mypage user licenses
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mypage user licenses.
	 *
	 * @param createDate the create date of this mypage user licenses
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mypage user licenses.
	 *
	 * @return the modified date of this mypage user licenses
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mypage user licenses.
	 *
	 * @param modifiedDate the modified date of this mypage user licenses
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the mypage user ID of this mypage user licenses.
	 *
	 * @return the mypage user ID of this mypage user licenses
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this mypage user licenses.
	 *
	 * @param mypageUserId the mypage user ID of this mypage user licenses
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this mypage user licenses.
	 *
	 * @return the mypage user uuid of this mypage user licenses
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this mypage user licenses.
	 *
	 * @param mypageUserUuid the mypage user uuid of this mypage user licenses
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the product ID of this mypage user licenses.
	 *
	 * @return the product ID of this mypage user licenses
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this mypage user licenses.
	 *
	 * @param productId the product ID of this mypage user licenses
	 */
	public void setProductId(long productId);

}