/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserRegistrationJobExp service. Represents a row in the &quot;UserRegistrationJobExp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.UserRegistrationJobExpModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.UserRegistrationJobExpImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistrationJobExp
 * @generated
 */
@ProviderType
public interface UserRegistrationJobExpModel
	extends BaseModel<UserRegistrationJobExp>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user registration job exp model instance should use the {@link UserRegistrationJobExp} interface instead.
	 */

	/**
	 * Returns the primary key of this user registration job exp.
	 *
	 * @return the primary key of this user registration job exp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user registration job exp.
	 *
	 * @param primaryKey the primary key of this user registration job exp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user registration job exp ID of this user registration job exp.
	 *
	 * @return the user registration job exp ID of this user registration job exp
	 */
	public long getUserRegistrationJobExpId();

	/**
	 * Sets the user registration job exp ID of this user registration job exp.
	 *
	 * @param userRegistrationJobExpId the user registration job exp ID of this user registration job exp
	 */
	public void setUserRegistrationJobExpId(long userRegistrationJobExpId);

	/**
	 * Returns the name of this user registration job exp.
	 *
	 * @return the name of this user registration job exp
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user registration job exp.
	 *
	 * @param name the name of this user registration job exp
	 */
	public void setName(String name);

	/**
	 * Returns the year of this user registration job exp.
	 *
	 * @return the year of this user registration job exp
	 */
	public int getYear();

	/**
	 * Sets the year of this user registration job exp.
	 *
	 * @param year the year of this user registration job exp
	 */
	public void setYear(int year);

	/**
	 * Returns the job head of this user registration job exp.
	 *
	 * @return the job head of this user registration job exp
	 */
	@AutoEscape
	public String getJobHead();

	/**
	 * Sets the job head of this user registration job exp.
	 *
	 * @param jobHead the job head of this user registration job exp
	 */
	public void setJobHead(String jobHead);

	/**
	 * Returns the job position of this user registration job exp.
	 *
	 * @return the job position of this user registration job exp
	 */
	@AutoEscape
	public String getJobPosition();

	/**
	 * Sets the job position of this user registration job exp.
	 *
	 * @param jobPosition the job position of this user registration job exp
	 */
	public void setJobPosition(String jobPosition);

	/**
	 * Returns the job income of this user registration job exp.
	 *
	 * @return the job income of this user registration job exp
	 */
	@AutoEscape
	public String getJobIncome();

	/**
	 * Sets the job income of this user registration job exp.
	 *
	 * @param jobIncome the job income of this user registration job exp
	 */
	public void setJobIncome(String jobIncome);

	/**
	 * Returns the other insurance company of this user registration job exp.
	 *
	 * @return the other insurance company of this user registration job exp
	 */
	public int getOtherInsuranceCompany();

	/**
	 * Sets the other insurance company of this user registration job exp.
	 *
	 * @param otherInsuranceCompany the other insurance company of this user registration job exp
	 */
	public void setOtherInsuranceCompany(int otherInsuranceCompany);

	/**
	 * Returns the user registration ID of this user registration job exp.
	 *
	 * @return the user registration ID of this user registration job exp
	 */
	public long getUserRegistrationId();

	/**
	 * Sets the user registration ID of this user registration job exp.
	 *
	 * @param userRegistrationId the user registration ID of this user registration job exp
	 */
	public void setUserRegistrationId(long userRegistrationId);

	/**
	 * Returns the group ID of this user registration job exp.
	 *
	 * @return the group ID of this user registration job exp
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user registration job exp.
	 *
	 * @param groupId the group ID of this user registration job exp
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user registration job exp.
	 *
	 * @return the company ID of this user registration job exp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user registration job exp.
	 *
	 * @param companyId the company ID of this user registration job exp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user registration job exp.
	 *
	 * @return the user ID of this user registration job exp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user registration job exp.
	 *
	 * @param userId the user ID of this user registration job exp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user registration job exp.
	 *
	 * @return the user uuid of this user registration job exp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user registration job exp.
	 *
	 * @param userUuid the user uuid of this user registration job exp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user registration job exp.
	 *
	 * @return the user name of this user registration job exp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user registration job exp.
	 *
	 * @param userName the user name of this user registration job exp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user registration job exp.
	 *
	 * @return the create date of this user registration job exp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user registration job exp.
	 *
	 * @param createDate the create date of this user registration job exp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user registration job exp.
	 *
	 * @return the modified date of this user registration job exp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user registration job exp.
	 *
	 * @param modifiedDate the modified date of this user registration job exp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}