/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserRegistrationReference service. Represents a row in the &quot;UserRegistrationReference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.UserRegistrationReferenceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.UserRegistrationReferenceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistrationReference
 * @generated
 */
@ProviderType
public interface UserRegistrationReferenceModel
	extends BaseModel<UserRegistrationReference>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user registration reference model instance should use the {@link UserRegistrationReference} interface instead.
	 */

	/**
	 * Returns the primary key of this user registration reference.
	 *
	 * @return the primary key of this user registration reference
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user registration reference.
	 *
	 * @param primaryKey the primary key of this user registration reference
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user registration reference ID of this user registration reference.
	 *
	 * @return the user registration reference ID of this user registration reference
	 */
	public long getUserRegistrationReferenceId();

	/**
	 * Sets the user registration reference ID of this user registration reference.
	 *
	 * @param userRegistrationReferenceId the user registration reference ID of this user registration reference
	 */
	public void setUserRegistrationReferenceId(
		long userRegistrationReferenceId);

	/**
	 * Returns the name of this user registration reference.
	 *
	 * @return the name of this user registration reference
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user registration reference.
	 *
	 * @param name the name of this user registration reference
	 */
	public void setName(String name);

	/**
	 * Returns the relation of this user registration reference.
	 *
	 * @return the relation of this user registration reference
	 */
	@AutoEscape
	public String getRelation();

	/**
	 * Sets the relation of this user registration reference.
	 *
	 * @param relation the relation of this user registration reference
	 */
	public void setRelation(String relation);

	/**
	 * Returns the age of this user registration reference.
	 *
	 * @return the age of this user registration reference
	 */
	public int getAge();

	/**
	 * Sets the age of this user registration reference.
	 *
	 * @param age the age of this user registration reference
	 */
	public void setAge(int age);

	/**
	 * Returns the address of this user registration reference.
	 *
	 * @return the address of this user registration reference
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this user registration reference.
	 *
	 * @param address the address of this user registration reference
	 */
	public void setAddress(String address);

	/**
	 * Returns the phone of this user registration reference.
	 *
	 * @return the phone of this user registration reference
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this user registration reference.
	 *
	 * @param phone the phone of this user registration reference
	 */
	public void setPhone(String phone);

	/**
	 * Returns the job of this user registration reference.
	 *
	 * @return the job of this user registration reference
	 */
	@AutoEscape
	public String getJob();

	/**
	 * Sets the job of this user registration reference.
	 *
	 * @param job the job of this user registration reference
	 */
	public void setJob(String job);

	/**
	 * Returns the year of this user registration reference.
	 *
	 * @return the year of this user registration reference
	 */
	public int getYear();

	/**
	 * Sets the year of this user registration reference.
	 *
	 * @param year the year of this user registration reference
	 */
	public void setYear(int year);

	/**
	 * Returns the user registration ID of this user registration reference.
	 *
	 * @return the user registration ID of this user registration reference
	 */
	public long getUserRegistrationId();

	/**
	 * Sets the user registration ID of this user registration reference.
	 *
	 * @param userRegistrationId the user registration ID of this user registration reference
	 */
	public void setUserRegistrationId(long userRegistrationId);

	/**
	 * Returns the group ID of this user registration reference.
	 *
	 * @return the group ID of this user registration reference
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user registration reference.
	 *
	 * @param groupId the group ID of this user registration reference
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user registration reference.
	 *
	 * @return the company ID of this user registration reference
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user registration reference.
	 *
	 * @param companyId the company ID of this user registration reference
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user registration reference.
	 *
	 * @return the user ID of this user registration reference
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user registration reference.
	 *
	 * @param userId the user ID of this user registration reference
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user registration reference.
	 *
	 * @return the user uuid of this user registration reference
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user registration reference.
	 *
	 * @param userUuid the user uuid of this user registration reference
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user registration reference.
	 *
	 * @return the user name of this user registration reference
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user registration reference.
	 *
	 * @param userName the user name of this user registration reference
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user registration reference.
	 *
	 * @return the create date of this user registration reference
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user registration reference.
	 *
	 * @param createDate the create date of this user registration reference
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user registration reference.
	 *
	 * @return the modified date of this user registration reference
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user registration reference.
	 *
	 * @param modifiedDate the modified date of this user registration reference
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}