/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserRegistrationEducation service. Represents a row in the &quot;UserRegistrationEducation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.user.model.impl.UserRegistrationEducationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.user.model.impl.UserRegistrationEducationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistrationEducation
 * @generated
 */
@ProviderType
public interface UserRegistrationEducationModel
	extends BaseModel<UserRegistrationEducation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user registration education model instance should use the {@link UserRegistrationEducation} interface instead.
	 */

	/**
	 * Returns the primary key of this user registration education.
	 *
	 * @return the primary key of this user registration education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user registration education.
	 *
	 * @param primaryKey the primary key of this user registration education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user registration education ID of this user registration education.
	 *
	 * @return the user registration education ID of this user registration education
	 */
	public long getUserRegistrationEducationId();

	/**
	 * Sets the user registration education ID of this user registration education.
	 *
	 * @param userRegistrationEducationId the user registration education ID of this user registration education
	 */
	public void setUserRegistrationEducationId(
		long userRegistrationEducationId);

	/**
	 * Returns the name of this user registration education.
	 *
	 * @return the name of this user registration education
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user registration education.
	 *
	 * @param name the name of this user registration education
	 */
	public void setName(String name);

	/**
	 * Returns the year of this user registration education.
	 *
	 * @return the year of this user registration education
	 */
	public int getYear();

	/**
	 * Sets the year of this user registration education.
	 *
	 * @param year the year of this user registration education
	 */
	public void setYear(int year);

	/**
	 * Returns the graduate of this user registration education.
	 *
	 * @return the graduate of this user registration education
	 */
	public int getGraduate();

	/**
	 * Sets the graduate of this user registration education.
	 *
	 * @param graduate the graduate of this user registration education
	 */
	public void setGraduate(int graduate);

	/**
	 * Returns the course type of this user registration education.
	 *
	 * @return the course type of this user registration education
	 */
	@AutoEscape
	public String getCourseType();

	/**
	 * Sets the course type of this user registration education.
	 *
	 * @param courseType the course type of this user registration education
	 */
	public void setCourseType(String courseType);

	/**
	 * Returns the title of this user registration education.
	 *
	 * @return the title of this user registration education
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this user registration education.
	 *
	 * @param title the title of this user registration education
	 */
	public void setTitle(String title);

	/**
	 * Returns the edu type of this user registration education.
	 *
	 * @return the edu type of this user registration education
	 */
	@AutoEscape
	public String getEduType();

	/**
	 * Sets the edu type of this user registration education.
	 *
	 * @param eduType the edu type of this user registration education
	 */
	public void setEduType(String eduType);

	/**
	 * Returns the user registration ID of this user registration education.
	 *
	 * @return the user registration ID of this user registration education
	 */
	public long getUserRegistrationId();

	/**
	 * Sets the user registration ID of this user registration education.
	 *
	 * @param userRegistrationId the user registration ID of this user registration education
	 */
	public void setUserRegistrationId(long userRegistrationId);

	/**
	 * Returns the group ID of this user registration education.
	 *
	 * @return the group ID of this user registration education
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user registration education.
	 *
	 * @param groupId the group ID of this user registration education
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user registration education.
	 *
	 * @return the company ID of this user registration education
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user registration education.
	 *
	 * @param companyId the company ID of this user registration education
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user registration education.
	 *
	 * @return the user ID of this user registration education
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user registration education.
	 *
	 * @param userId the user ID of this user registration education
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user registration education.
	 *
	 * @return the user uuid of this user registration education
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user registration education.
	 *
	 * @param userUuid the user uuid of this user registration education
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user registration education.
	 *
	 * @return the user name of this user registration education
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user registration education.
	 *
	 * @param userName the user name of this user registration education
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user registration education.
	 *
	 * @return the create date of this user registration education
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user registration education.
	 *
	 * @param createDate the create date of this user registration education
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user registration education.
	 *
	 * @return the modified date of this user registration education
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user registration education.
	 *
	 * @param modifiedDate the modified date of this user registration education
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}