/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DetailDomesticTravel service. Represents a row in the &quot;DetailDomesticTravel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.leads.model.impl.DetailDomesticTravelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.leads.model.impl.DetailDomesticTravelImpl</code>.
 * </p>
 *
 * @author Gositus
 * @see DetailDomesticTravel
 * @generated
 */
@ProviderType
public interface DetailDomesticTravelModel
	extends BaseModel<DetailDomesticTravel>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a detail domestic travel model instance should use the {@link DetailDomesticTravel} interface instead.
	 */

	/**
	 * Returns the primary key of this detail domestic travel.
	 *
	 * @return the primary key of this detail domestic travel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this detail domestic travel.
	 *
	 * @param primaryKey the primary key of this detail domestic travel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the detail domestic travel ID of this detail domestic travel.
	 *
	 * @return the detail domestic travel ID of this detail domestic travel
	 */
	public long getDetailDomesticTravelId();

	/**
	 * Sets the detail domestic travel ID of this detail domestic travel.
	 *
	 * @param detailDomesticTravelId the detail domestic travel ID of this detail domestic travel
	 */
	public void setDetailDomesticTravelId(long detailDomesticTravelId);

	/**
	 * Returns the group ID of this detail domestic travel.
	 *
	 * @return the group ID of this detail domestic travel
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this detail domestic travel.
	 *
	 * @param groupId the group ID of this detail domestic travel
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this detail domestic travel.
	 *
	 * @return the company ID of this detail domestic travel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this detail domestic travel.
	 *
	 * @param companyId the company ID of this detail domestic travel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this detail domestic travel.
	 *
	 * @return the user ID of this detail domestic travel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this detail domestic travel.
	 *
	 * @param userId the user ID of this detail domestic travel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this detail domestic travel.
	 *
	 * @return the user uuid of this detail domestic travel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this detail domestic travel.
	 *
	 * @param userUuid the user uuid of this detail domestic travel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this detail domestic travel.
	 *
	 * @return the user name of this detail domestic travel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this detail domestic travel.
	 *
	 * @param userName the user name of this detail domestic travel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this detail domestic travel.
	 *
	 * @return the create date of this detail domestic travel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this detail domestic travel.
	 *
	 * @param createDate the create date of this detail domestic travel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this detail domestic travel.
	 *
	 * @return the modified date of this detail domestic travel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this detail domestic travel.
	 *
	 * @param modifiedDate the modified date of this detail domestic travel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leads ID of this detail domestic travel.
	 *
	 * @return the leads ID of this detail domestic travel
	 */
	public long getLeadsId();

	/**
	 * Sets the leads ID of this detail domestic travel.
	 *
	 * @param LeadsId the leads ID of this detail domestic travel
	 */
	public void setLeadsId(long LeadsId);

	/**
	 * Returns the travel type of this detail domestic travel.
	 *
	 * @return the travel type of this detail domestic travel
	 */
	@AutoEscape
	public String getTravelType();

	/**
	 * Sets the travel type of this detail domestic travel.
	 *
	 * @param TravelType the travel type of this detail domestic travel
	 */
	public void setTravelType(String TravelType);

	/**
	 * Returns the travel plan of this detail domestic travel.
	 *
	 * @return the travel plan of this detail domestic travel
	 */
	@AutoEscape
	public String getTravelPlan();

	/**
	 * Sets the travel plan of this detail domestic travel.
	 *
	 * @param TravelPlan the travel plan of this detail domestic travel
	 */
	public void setTravelPlan(String TravelPlan);

	/**
	 * Returns the traveller type of this detail domestic travel.
	 *
	 * @return the traveller type of this detail domestic travel
	 */
	@AutoEscape
	public String getTravellerType();

	/**
	 * Sets the traveller type of this detail domestic travel.
	 *
	 * @param TravellerType the traveller type of this detail domestic travel
	 */
	public void setTravellerType(String TravellerType);

	/**
	 * Returns the adult of this detail domestic travel.
	 *
	 * @return the adult of this detail domestic travel
	 */
	public Integer getAdult();

	/**
	 * Sets the adult of this detail domestic travel.
	 *
	 * @param Adult the adult of this detail domestic travel
	 */
	public void setAdult(Integer Adult);

	/**
	 * Returns the child of this detail domestic travel.
	 *
	 * @return the child of this detail domestic travel
	 */
	public Integer getChild();

	/**
	 * Sets the child of this detail domestic travel.
	 *
	 * @param Child the child of this detail domestic travel
	 */
	public void setChild(Integer Child);

	/**
	 * Returns the departure date of this detail domestic travel.
	 *
	 * @return the departure date of this detail domestic travel
	 */
	public Date getDepartureDate();

	/**
	 * Sets the departure date of this detail domestic travel.
	 *
	 * @param DepartureDate the departure date of this detail domestic travel
	 */
	public void setDepartureDate(Date DepartureDate);

	/**
	 * Returns the arrival date of this detail domestic travel.
	 *
	 * @return the arrival date of this detail domestic travel
	 */
	public Date getArrivalDate();

	/**
	 * Sets the arrival date of this detail domestic travel.
	 *
	 * @param ArrivalDate the arrival date of this detail domestic travel
	 */
	public void setArrivalDate(Date ArrivalDate);

	/**
	 * Returns the commercial offers of this detail domestic travel.
	 *
	 * @return the commercial offers of this detail domestic travel
	 */
	public Integer getCommercialOffers();

	/**
	 * Sets the commercial offers of this detail domestic travel.
	 *
	 * @param CommercialOffers the commercial offers of this detail domestic travel
	 */
	public void setCommercialOffers(Integer CommercialOffers);

}