/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DetailDrive service. Represents a row in the &quot;DetailDrive&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.leads.model.impl.DetailDriveModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.leads.model.impl.DetailDriveImpl</code>.
 * </p>
 *
 * @author Gositus
 * @see DetailDrive
 * @generated
 */
@ProviderType
public interface DetailDriveModel
	extends BaseModel<DetailDrive>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a detail drive model instance should use the {@link DetailDrive} interface instead.
	 */

	/**
	 * Returns the primary key of this detail drive.
	 *
	 * @return the primary key of this detail drive
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this detail drive.
	 *
	 * @param primaryKey the primary key of this detail drive
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the detail drive ID of this detail drive.
	 *
	 * @return the detail drive ID of this detail drive
	 */
	public long getDetailDriveId();

	/**
	 * Sets the detail drive ID of this detail drive.
	 *
	 * @param detailDriveId the detail drive ID of this detail drive
	 */
	public void setDetailDriveId(long detailDriveId);

	/**
	 * Returns the leads ID of this detail drive.
	 *
	 * @return the leads ID of this detail drive
	 */
	public long getLeadsId();

	/**
	 * Sets the leads ID of this detail drive.
	 *
	 * @param leadsId the leads ID of this detail drive
	 */
	public void setLeadsId(long leadsId);

	/**
	 * Returns the group ID of this detail drive.
	 *
	 * @return the group ID of this detail drive
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this detail drive.
	 *
	 * @param groupId the group ID of this detail drive
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this detail drive.
	 *
	 * @return the company ID of this detail drive
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this detail drive.
	 *
	 * @param companyId the company ID of this detail drive
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this detail drive.
	 *
	 * @return the user ID of this detail drive
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this detail drive.
	 *
	 * @param userId the user ID of this detail drive
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this detail drive.
	 *
	 * @return the user uuid of this detail drive
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this detail drive.
	 *
	 * @param userUuid the user uuid of this detail drive
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this detail drive.
	 *
	 * @return the user name of this detail drive
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this detail drive.
	 *
	 * @param userName the user name of this detail drive
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this detail drive.
	 *
	 * @return the create date of this detail drive
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this detail drive.
	 *
	 * @param createDate the create date of this detail drive
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this detail drive.
	 *
	 * @return the modified date of this detail drive
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this detail drive.
	 *
	 * @param modifiedDate the modified date of this detail drive
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the vehicle code of this detail drive.
	 *
	 * @return the vehicle code of this detail drive
	 */
	@AutoEscape
	public String getVehicleCode();

	/**
	 * Sets the vehicle code of this detail drive.
	 *
	 * @param vehicleCode the vehicle code of this detail drive
	 */
	public void setVehicleCode(String vehicleCode);

	/**
	 * Returns the vehicle manufacture of this detail drive.
	 *
	 * @return the vehicle manufacture of this detail drive
	 */
	@AutoEscape
	public String getVehicleManufacture();

	/**
	 * Sets the vehicle manufacture of this detail drive.
	 *
	 * @param VehicleManufacture the vehicle manufacture of this detail drive
	 */
	public void setVehicleManufacture(String VehicleManufacture);

	/**
	 * Returns the vehicle model of this detail drive.
	 *
	 * @return the vehicle model of this detail drive
	 */
	@AutoEscape
	public String getVehicleModel();

	/**
	 * Sets the vehicle model of this detail drive.
	 *
	 * @param vehicleModel the vehicle model of this detail drive
	 */
	public void setVehicleModel(String vehicleModel);

	/**
	 * Returns the vehicle sub model of this detail drive.
	 *
	 * @return the vehicle sub model of this detail drive
	 */
	@AutoEscape
	public String getVehicleSubModel();

	/**
	 * Sets the vehicle sub model of this detail drive.
	 *
	 * @param vehicleSubModel the vehicle sub model of this detail drive
	 */
	public void setVehicleSubModel(String vehicleSubModel);

	/**
	 * Returns the vehicle body of this detail drive.
	 *
	 * @return the vehicle body of this detail drive
	 */
	@AutoEscape
	public String getVehicleBody();

	/**
	 * Sets the vehicle body of this detail drive.
	 *
	 * @param vehicleBody the vehicle body of this detail drive
	 */
	public void setVehicleBody(String vehicleBody);

	/**
	 * Returns the manufacture year of this detail drive.
	 *
	 * @return the manufacture year of this detail drive
	 */
	public int getManufactureYear();

	/**
	 * Sets the manufacture year of this detail drive.
	 *
	 * @param manufactureYear the manufacture year of this detail drive
	 */
	public void setManufactureYear(int manufactureYear);

	/**
	 * Returns the manufacture age of this detail drive.
	 *
	 * @return the manufacture age of this detail drive
	 */
	public int getManufactureAge();

	/**
	 * Sets the manufacture age of this detail drive.
	 *
	 * @param manufactureAge the manufacture age of this detail drive
	 */
	public void setManufactureAge(int manufactureAge);

	/**
	 * Returns the coverage type of this detail drive.
	 *
	 * @return the coverage type of this detail drive
	 */
	@AutoEscape
	public String getCoverageType();

	/**
	 * Sets the coverage type of this detail drive.
	 *
	 * @param coverageType the coverage type of this detail drive
	 */
	public void setCoverageType(String coverageType);

	/**
	 * Returns the vehicle type of this detail drive.
	 *
	 * @return the vehicle type of this detail drive
	 */
	@AutoEscape
	public String getVehicleType();

	/**
	 * Sets the vehicle type of this detail drive.
	 *
	 * @param vehicleType the vehicle type of this detail drive
	 */
	public void setVehicleType(String vehicleType);

	/**
	 * Returns the type of use of this detail drive.
	 *
	 * @return the type of use of this detail drive
	 */
	@AutoEscape
	public String getTypeOfUse();

	/**
	 * Sets the type of use of this detail drive.
	 *
	 * @param typeOfUse the type of use of this detail drive
	 */
	public void setTypeOfUse(String typeOfUse);

	/**
	 * Returns the vehicle insured of this detail drive.
	 *
	 * @return the vehicle insured of this detail drive
	 */
	public double getVehicleInsured();

	/**
	 * Sets the vehicle insured of this detail drive.
	 *
	 * @param vehicleInsured the vehicle insured of this detail drive
	 */
	public void setVehicleInsured(double vehicleInsured);

	/**
	 * Returns the accessories insured of this detail drive.
	 *
	 * @return the accessories insured of this detail drive
	 */
	public double getAccessoriesInsured();

	/**
	 * Sets the accessories insured of this detail drive.
	 *
	 * @param accessoriesInsured the accessories insured of this detail drive
	 */
	public void setAccessoriesInsured(double accessoriesInsured);

	/**
	 * Returns the sum insured of this detail drive.
	 *
	 * @return the sum insured of this detail drive
	 */
	public double getSumInsured();

	/**
	 * Sets the sum insured of this detail drive.
	 *
	 * @param sumInsured the sum insured of this detail drive
	 */
	public void setSumInsured(double sumInsured);

	/**
	 * Returns the region plate of this detail drive.
	 *
	 * @return the region plate of this detail drive
	 */
	@AutoEscape
	public String getRegionPlate();

	/**
	 * Sets the region plate of this detail drive.
	 *
	 * @param regionPlate the region plate of this detail drive
	 */
	public void setRegionPlate(String regionPlate);

	/**
	 * Returns the cc of this detail drive.
	 *
	 * @return the cc of this detail drive
	 */
	public int getCc();

	/**
	 * Sets the cc of this detail drive.
	 *
	 * @param cc the cc of this detail drive
	 */
	public void setCc(int cc);

	/**
	 * Returns the make of this detail drive.
	 *
	 * @return the make of this detail drive
	 */
	@AutoEscape
	public String getMake();

	/**
	 * Sets the make of this detail drive.
	 *
	 * @param make the make of this detail drive
	 */
	public void setMake(String make);

	/**
	 * Returns the dpg of this detail drive.
	 *
	 * @return the dpg of this detail drive
	 */
	@AutoEscape
	public String getDpg();

	/**
	 * Sets the dpg of this detail drive.
	 *
	 * @param dpg the dpg of this detail drive
	 */
	public void setDpg(String dpg);

	/**
	 * Returns the seat capacity of this detail drive.
	 *
	 * @return the seat capacity of this detail drive
	 */
	public int getSeatCapacity();

	/**
	 * Sets the seat capacity of this detail drive.
	 *
	 * @param seatCapacity the seat capacity of this detail drive
	 */
	public void setSeatCapacity(int seatCapacity);

	/**
	 * Returns the start date of this detail drive.
	 *
	 * @return the start date of this detail drive
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this detail drive.
	 *
	 * @param startDate the start date of this detail drive
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the expired date of this detail drive.
	 *
	 * @return the expired date of this detail drive
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this detail drive.
	 *
	 * @param expiredDate the expired date of this detail drive
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Returns the commercial offers of this detail drive.
	 *
	 * @return the commercial offers of this detail drive
	 */
	public int getCommercialOffers();

	/**
	 * Sets the commercial offers of this detail drive.
	 *
	 * @param commercialOffers the commercial offers of this detail drive
	 */
	public void setCommercialOffers(int commercialOffers);

	/**
	 * Returns the name of this detail drive.
	 *
	 * @return the name of this detail drive
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this detail drive.
	 *
	 * @param name the name of this detail drive
	 */
	public void setName(String name);

	/**
	 * Returns the birth place of this detail drive.
	 *
	 * @return the birth place of this detail drive
	 */
	@AutoEscape
	public String getBirthPlace();

	/**
	 * Sets the birth place of this detail drive.
	 *
	 * @param birthPlace the birth place of this detail drive
	 */
	public void setBirthPlace(String birthPlace);

	/**
	 * Returns the dob of this detail drive.
	 *
	 * @return the dob of this detail drive
	 */
	public Date getDob();

	/**
	 * Sets the dob of this detail drive.
	 *
	 * @param dob the dob of this detail drive
	 */
	public void setDob(Date dob);

	/**
	 * Returns the nationality of this detail drive.
	 *
	 * @return the nationality of this detail drive
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this detail drive.
	 *
	 * @param nationality the nationality of this detail drive
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the id number of this detail drive.
	 *
	 * @return the id number of this detail drive
	 */
	@AutoEscape
	public String getIdNumber();

	/**
	 * Sets the id number of this detail drive.
	 *
	 * @param idNumber the id number of this detail drive
	 */
	public void setIdNumber(String idNumber);

	/**
	 * Returns the passport number of this detail drive.
	 *
	 * @return the passport number of this detail drive
	 */
	@AutoEscape
	public String getPassportNumber();

	/**
	 * Sets the passport number of this detail drive.
	 *
	 * @param passportNumber the passport number of this detail drive
	 */
	public void setPassportNumber(String passportNumber);

	/**
	 * Returns the kitas number of this detail drive.
	 *
	 * @return the kitas number of this detail drive
	 */
	@AutoEscape
	public String getKitasNumber();

	/**
	 * Sets the kitas number of this detail drive.
	 *
	 * @param kitasNumber the kitas number of this detail drive
	 */
	public void setKitasNumber(String kitasNumber);

	/**
	 * Returns the mobile phone of this detail drive.
	 *
	 * @return the mobile phone of this detail drive
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this detail drive.
	 *
	 * @param mobilePhone the mobile phone of this detail drive
	 */
	public void setMobilePhone(String mobilePhone);

	/**
	 * Returns the email of this detail drive.
	 *
	 * @return the email of this detail drive
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this detail drive.
	 *
	 * @param email the email of this detail drive
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this detail drive.
	 *
	 * @return the address of this detail drive
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this detail drive.
	 *
	 * @param address the address of this detail drive
	 */
	public void setAddress(String address);

	/**
	 * Returns the address2 of this detail drive.
	 *
	 * @return the address2 of this detail drive
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this detail drive.
	 *
	 * @param address2 the address2 of this detail drive
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the province of this detail drive.
	 *
	 * @return the province of this detail drive
	 */
	@AutoEscape
	public String getProvince();

	/**
	 * Sets the province of this detail drive.
	 *
	 * @param province the province of this detail drive
	 */
	public void setProvince(String province);

	/**
	 * Returns the city of this detail drive.
	 *
	 * @return the city of this detail drive
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this detail drive.
	 *
	 * @param city the city of this detail drive
	 */
	public void setCity(String city);

	/**
	 * Returns the police number of this detail drive.
	 *
	 * @return the police number of this detail drive
	 */
	@AutoEscape
	public String getPoliceNumber();

	/**
	 * Sets the police number of this detail drive.
	 *
	 * @param policeNumber the police number of this detail drive
	 */
	public void setPoliceNumber(String policeNumber);

	/**
	 * Returns the chassis number of this detail drive.
	 *
	 * @return the chassis number of this detail drive
	 */
	@AutoEscape
	public String getChassisNumber();

	/**
	 * Sets the chassis number of this detail drive.
	 *
	 * @param chassisNumber the chassis number of this detail drive
	 */
	public void setChassisNumber(String chassisNumber);

	/**
	 * Returns the engine number of this detail drive.
	 *
	 * @return the engine number of this detail drive
	 */
	@AutoEscape
	public String getEngineNumber();

	/**
	 * Sets the engine number of this detail drive.
	 *
	 * @param engineNumber the engine number of this detail drive
	 */
	public void setEngineNumber(String engineNumber);

	/**
	 * Returns the policy number of this detail drive.
	 *
	 * @return the policy number of this detail drive
	 */
	@AutoEscape
	public String getPolicyNumber();

	/**
	 * Sets the policy number of this detail drive.
	 *
	 * @param policyNumber the policy number of this detail drive
	 */
	public void setPolicyNumber(String policyNumber);

	/**
	 * Returns the reference number of this detail drive.
	 *
	 * @return the reference number of this detail drive
	 */
	@AutoEscape
	public String getReferenceNumber();

	/**
	 * Sets the reference number of this detail drive.
	 *
	 * @param referenceNumber the reference number of this detail drive
	 */
	public void setReferenceNumber(String referenceNumber);

	/**
	 * Returns the policy status of this detail drive.
	 *
	 * @return the policy status of this detail drive
	 */
	@AutoEscape
	public String getPolicyStatus();

	/**
	 * Sets the policy status of this detail drive.
	 *
	 * @param policyStatus the policy status of this detail drive
	 */
	public void setPolicyStatus(String policyStatus);

	/**
	 * Returns the currency of this detail drive.
	 *
	 * @return the currency of this detail drive
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this detail drive.
	 *
	 * @param currency the currency of this detail drive
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the policy cost of this detail drive.
	 *
	 * @return the policy cost of this detail drive
	 */
	public double getPolicyCost();

	/**
	 * Sets the policy cost of this detail drive.
	 *
	 * @param policyCost the policy cost of this detail drive
	 */
	public void setPolicyCost(double policyCost);

	/**
	 * Returns the stamp duty of this detail drive.
	 *
	 * @return the stamp duty of this detail drive
	 */
	public double getStampDuty();

	/**
	 * Sets the stamp duty of this detail drive.
	 *
	 * @param stampDuty the stamp duty of this detail drive
	 */
	public void setStampDuty(double stampDuty);

	/**
	 * Returns the premium of this detail drive.
	 *
	 * @return the premium of this detail drive
	 */
	public double getPremium();

	/**
	 * Sets the premium of this detail drive.
	 *
	 * @param premium the premium of this detail drive
	 */
	public void setPremium(double premium);

	/**
	 * Returns the net premium of this detail drive.
	 *
	 * @return the net premium of this detail drive
	 */
	public double getNetPremium();

	/**
	 * Sets the net premium of this detail drive.
	 *
	 * @param netPremium the net premium of this detail drive
	 */
	public void setNetPremium(double netPremium);

	/**
	 * Returns the discount of this detail drive.
	 *
	 * @return the discount of this detail drive
	 */
	public int getDiscount();

	/**
	 * Sets the discount of this detail drive.
	 *
	 * @param discount the discount of this detail drive
	 */
	public void setDiscount(int discount);

	/**
	 * Returns the commission of this detail drive.
	 *
	 * @return the commission of this detail drive
	 */
	@AutoEscape
	public String getCommission();

	/**
	 * Sets the commission of this detail drive.
	 *
	 * @param commission the commission of this detail drive
	 */
	public void setCommission(String commission);

	/**
	 * Returns the leads of this detail drive.
	 *
	 * @return the leads of this detail drive
	 */
	public long getLeads();

	/**
	 * Sets the leads of this detail drive.
	 *
	 * @param leads the leads of this detail drive
	 */
	public void setLeads(long leads);

	/**
	 * Returns the transaction ID of this detail drive.
	 *
	 * @return the transaction ID of this detail drive
	 */
	@AutoEscape
	public String getTransactionId();

	/**
	 * Sets the transaction ID of this detail drive.
	 *
	 * @param transactionId the transaction ID of this detail drive
	 */
	public void setTransactionId(String transactionId);

	/**
	 * Returns the bussines model of this detail drive.
	 *
	 * @return the bussines model of this detail drive
	 */
	@AutoEscape
	public String getBussinesModel();

	/**
	 * Sets the bussines model of this detail drive.
	 *
	 * @param bussinesModel the bussines model of this detail drive
	 */
	public void setBussinesModel(String bussinesModel);

	/**
	 * Returns the channel of this detail drive.
	 *
	 * @return the channel of this detail drive
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this detail drive.
	 *
	 * @param channel the channel of this detail drive
	 */
	public void setChannel(String channel);

	/**
	 * Returns the promo code of this detail drive.
	 *
	 * @return the promo code of this detail drive
	 */
	@AutoEscape
	public String getPromoCode();

	/**
	 * Sets the promo code of this detail drive.
	 *
	 * @param promoCode the promo code of this detail drive
	 */
	public void setPromoCode(String promoCode);

	/**
	 * Returns the step1 of this detail drive.
	 *
	 * @return the step1 of this detail drive
	 */
	public int getStep1();

	/**
	 * Sets the step1 of this detail drive.
	 *
	 * @param step1 the step1 of this detail drive
	 */
	public void setStep1(int step1);

	/**
	 * Returns the step2 of this detail drive.
	 *
	 * @return the step2 of this detail drive
	 */
	public int getStep2();

	/**
	 * Sets the step2 of this detail drive.
	 *
	 * @param step2 the step2 of this detail drive
	 */
	public void setStep2(int step2);

	/**
	 * Returns the step3 of this detail drive.
	 *
	 * @return the step3 of this detail drive
	 */
	public int getStep3();

	/**
	 * Sets the step3 of this detail drive.
	 *
	 * @param step3 the step3 of this detail drive
	 */
	public void setStep3(int step3);

	/**
	 * Returns the daily report status of this detail drive.
	 *
	 * @return the daily report status of this detail drive
	 */
	public int getDailyReportStatus();

	/**
	 * Sets the daily report status of this detail drive.
	 *
	 * @param dailyReportStatus the daily report status of this detail drive
	 */
	public void setDailyReportStatus(int dailyReportStatus);

	/**
	 * Returns the daily report file of this detail drive.
	 *
	 * @return the daily report file of this detail drive
	 */
	public long getDailyReportFile();

	/**
	 * Sets the daily report file of this detail drive.
	 *
	 * @param dailyReportFile the daily report file of this detail drive
	 */
	public void setDailyReportFile(long dailyReportFile);

	/**
	 * Returns the daily report agent status of this detail drive.
	 *
	 * @return the daily report agent status of this detail drive
	 */
	public int getDailyReportAgentStatus();

	/**
	 * Sets the daily report agent status of this detail drive.
	 *
	 * @param dailyReportAgentStatus the daily report agent status of this detail drive
	 */
	public void setDailyReportAgentStatus(int dailyReportAgentStatus);

	/**
	 * Returns the daily report agent file of this detail drive.
	 *
	 * @return the daily report agent file of this detail drive
	 */
	public long getDailyReportAgentFile();

	/**
	 * Sets the daily report agent file of this detail drive.
	 *
	 * @param dailyReportAgentFile the daily report agent file of this detail drive
	 */
	public void setDailyReportAgentFile(long dailyReportAgentFile);

	/**
	 * Returns the utm source of this detail drive.
	 *
	 * @return the utm source of this detail drive
	 */
	@AutoEscape
	public String getUtmSource();

	/**
	 * Sets the utm source of this detail drive.
	 *
	 * @param utmSource the utm source of this detail drive
	 */
	public void setUtmSource(String utmSource);

	/**
	 * Returns the utm medium of this detail drive.
	 *
	 * @return the utm medium of this detail drive
	 */
	@AutoEscape
	public String getUtmMedium();

	/**
	 * Sets the utm medium of this detail drive.
	 *
	 * @param utmMedium the utm medium of this detail drive
	 */
	public void setUtmMedium(String utmMedium);

	/**
	 * Returns the utm campaign of this detail drive.
	 *
	 * @return the utm campaign of this detail drive
	 */
	@AutoEscape
	public String getUtmCampaign();

	/**
	 * Sets the utm campaign of this detail drive.
	 *
	 * @param utmCampaign the utm campaign of this detail drive
	 */
	public void setUtmCampaign(String utmCampaign);

	/**
	 * Returns the utm term of this detail drive.
	 *
	 * @return the utm term of this detail drive
	 */
	@AutoEscape
	public String getUtmTerm();

	/**
	 * Sets the utm term of this detail drive.
	 *
	 * @param utmTerm the utm term of this detail drive
	 */
	public void setUtmTerm(String utmTerm);

	/**
	 * Returns the utm content of this detail drive.
	 *
	 * @return the utm content of this detail drive
	 */
	@AutoEscape
	public String getUtmContent();

	/**
	 * Sets the utm content of this detail drive.
	 *
	 * @param utmContent the utm content of this detail drive
	 */
	public void setUtmContent(String utmContent);

	/**
	 * Returns the click ID of this detail drive.
	 *
	 * @return the click ID of this detail drive
	 */
	@AutoEscape
	public String getClickId();

	/**
	 * Sets the click ID of this detail drive.
	 *
	 * @param clickId the click ID of this detail drive
	 */
	public void setClickId(String clickId);

	/**
	 * Returns the managed by of this detail drive.
	 *
	 * @return the managed by of this detail drive
	 */
	public long getManagedBy();

	/**
	 * Sets the managed by of this detail drive.
	 *
	 * @param managedBy the managed by of this detail drive
	 */
	public void setManagedBy(long managedBy);

	/**
	 * Returns the agent code of this detail drive.
	 *
	 * @return the agent code of this detail drive
	 */
	@AutoEscape
	public String getAgentCode();

	/**
	 * Sets the agent code of this detail drive.
	 *
	 * @param agentCode the agent code of this detail drive
	 */
	public void setAgentCode(String agentCode);

	/**
	 * Returns the sub agent of this detail drive.
	 *
	 * @return the sub agent of this detail drive
	 */
	public long getSubAgent();

	/**
	 * Sets the sub agent of this detail drive.
	 *
	 * @param subAgent the sub agent of this detail drive
	 */
	public void setSubAgent(long subAgent);

	/**
	 * Returns the marketing code of this detail drive.
	 *
	 * @return the marketing code of this detail drive
	 */
	@AutoEscape
	public String getMarketingCode();

	/**
	 * Sets the marketing code of this detail drive.
	 *
	 * @param marketingCode the marketing code of this detail drive
	 */
	public void setMarketingCode(String marketingCode);

	/**
	 * Returns the active of this detail drive.
	 *
	 * @return the active of this detail drive
	 */
	public int getActive();

	/**
	 * Sets the active of this detail drive.
	 *
	 * @param active the active of this detail drive
	 */
	public void setActive(int active);

}