/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Leads service. Represents a row in the &quot;Leads&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.leads.model.impl.LeadsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.leads.model.impl.LeadsImpl</code>.
 * </p>
 *
 * @author Gositus
 * @see Leads
 * @generated
 */
@ProviderType
public interface LeadsModel
	extends BaseModel<Leads>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leads model instance should use the {@link Leads} interface instead.
	 */

	/**
	 * Returns the primary key of this leads.
	 *
	 * @return the primary key of this leads
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leads.
	 *
	 * @param primaryKey the primary key of this leads
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the leads ID of this leads.
	 *
	 * @return the leads ID of this leads
	 */
	public long getLeadsId();

	/**
	 * Sets the leads ID of this leads.
	 *
	 * @param LeadsId the leads ID of this leads
	 */
	public void setLeadsId(long LeadsId);

	/**
	 * Returns the leads parent ID of this leads.
	 *
	 * @return the leads parent ID of this leads
	 */
	public long getLeadsParentId();

	/**
	 * Sets the leads parent ID of this leads.
	 *
	 * @param LeadsParentId the leads parent ID of this leads
	 */
	public void setLeadsParentId(long LeadsParentId);

	/**
	 * Returns the leads type of this leads.
	 *
	 * @return the leads type of this leads
	 */
	@AutoEscape
	public String getLeadsType();

	/**
	 * Sets the leads type of this leads.
	 *
	 * @param LeadsType the leads type of this leads
	 */
	public void setLeadsType(String LeadsType);

	/**
	 * Returns the bussines model of this leads.
	 *
	 * @return the bussines model of this leads
	 */
	@AutoEscape
	public String getBussinesModel();

	/**
	 * Sets the bussines model of this leads.
	 *
	 * @param BussinesModel the bussines model of this leads
	 */
	public void setBussinesModel(String BussinesModel);

	/**
	 * Returns the commercial offers of this leads.
	 *
	 * @return the commercial offers of this leads
	 */
	public int getCommercialOffers();

	/**
	 * Sets the commercial offers of this leads.
	 *
	 * @param CommercialOffers the commercial offers of this leads
	 */
	public void setCommercialOffers(int CommercialOffers);

	/**
	 * Returns the policy number of this leads.
	 *
	 * @return the policy number of this leads
	 */
	@AutoEscape
	public String getPolicyNumber();

	/**
	 * Sets the policy number of this leads.
	 *
	 * @param PolicyNumber the policy number of this leads
	 */
	public void setPolicyNumber(String PolicyNumber);

	/**
	 * Returns the reference number of this leads.
	 *
	 * @return the reference number of this leads
	 */
	@AutoEscape
	public String getReferenceNumber();

	/**
	 * Sets the reference number of this leads.
	 *
	 * @param ReferenceNumber the reference number of this leads
	 */
	public void setReferenceNumber(String ReferenceNumber);

	/**
	 * Returns the currency of this leads.
	 *
	 * @return the currency of this leads
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this leads.
	 *
	 * @param Currency the currency of this leads
	 */
	public void setCurrency(String Currency);

	/**
	 * Returns the policy cost of this leads.
	 *
	 * @return the policy cost of this leads
	 */
	public double getPolicyCost();

	/**
	 * Sets the policy cost of this leads.
	 *
	 * @param PolicyCost the policy cost of this leads
	 */
	public void setPolicyCost(double PolicyCost);

	/**
	 * Returns the stamp duty of this leads.
	 *
	 * @return the stamp duty of this leads
	 */
	public double getStampDuty();

	/**
	 * Sets the stamp duty of this leads.
	 *
	 * @param StampDuty the stamp duty of this leads
	 */
	public void setStampDuty(double StampDuty);

	/**
	 * Returns the premium of this leads.
	 *
	 * @return the premium of this leads
	 */
	public double getPremium();

	/**
	 * Sets the premium of this leads.
	 *
	 * @param Premium the premium of this leads
	 */
	public void setPremium(double Premium);

	/**
	 * Returns the net premium of this leads.
	 *
	 * @return the net premium of this leads
	 */
	public double getNetPremium();

	/**
	 * Sets the net premium of this leads.
	 *
	 * @param NetPremium the net premium of this leads
	 */
	public void setNetPremium(double NetPremium);

	/**
	 * Returns the discount of this leads.
	 *
	 * @return the discount of this leads
	 */
	public double getDiscount();

	/**
	 * Sets the discount of this leads.
	 *
	 * @param Discount the discount of this leads
	 */
	public void setDiscount(double Discount);

	/**
	 * Returns the discount amount of this leads.
	 *
	 * @return the discount amount of this leads
	 */
	public double getDiscountAmount();

	/**
	 * Sets the discount amount of this leads.
	 *
	 * @param DiscountAmount the discount amount of this leads
	 */
	public void setDiscountAmount(double DiscountAmount);

	/**
	 * Returns the commission of this leads.
	 *
	 * @return the commission of this leads
	 */
	public double getCommission();

	/**
	 * Sets the commission of this leads.
	 *
	 * @param Commission the commission of this leads
	 */
	public void setCommission(double Commission);

	/**
	 * Returns the channel of this leads.
	 *
	 * @return the channel of this leads
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this leads.
	 *
	 * @param Channel the channel of this leads
	 */
	public void setChannel(String Channel);

	/**
	 * Returns the promo code of this leads.
	 *
	 * @return the promo code of this leads
	 */
	@AutoEscape
	public String getPromoCode();

	/**
	 * Sets the promo code of this leads.
	 *
	 * @param PromoCode the promo code of this leads
	 */
	public void setPromoCode(String PromoCode);

	/**
	 * Returns the product code of this leads.
	 *
	 * @return the product code of this leads
	 */
	@AutoEscape
	public String getProductCode();

	/**
	 * Sets the product code of this leads.
	 *
	 * @param ProductCode the product code of this leads
	 */
	public void setProductCode(String ProductCode);

	/**
	 * Returns the utm source of this leads.
	 *
	 * @return the utm source of this leads
	 */
	@AutoEscape
	public String getUtmSource();

	/**
	 * Sets the utm source of this leads.
	 *
	 * @param UtmSource the utm source of this leads
	 */
	public void setUtmSource(String UtmSource);

	/**
	 * Returns the utm medium of this leads.
	 *
	 * @return the utm medium of this leads
	 */
	@AutoEscape
	public String getUtmMedium();

	/**
	 * Sets the utm medium of this leads.
	 *
	 * @param UtmMedium the utm medium of this leads
	 */
	public void setUtmMedium(String UtmMedium);

	/**
	 * Returns the utm campaign of this leads.
	 *
	 * @return the utm campaign of this leads
	 */
	@AutoEscape
	public String getUtmCampaign();

	/**
	 * Sets the utm campaign of this leads.
	 *
	 * @param UtmCampaign the utm campaign of this leads
	 */
	public void setUtmCampaign(String UtmCampaign);

	/**
	 * Returns the utm term of this leads.
	 *
	 * @return the utm term of this leads
	 */
	@AutoEscape
	public String getUtmTerm();

	/**
	 * Sets the utm term of this leads.
	 *
	 * @param UtmTerm the utm term of this leads
	 */
	public void setUtmTerm(String UtmTerm);

	/**
	 * Returns the utm content of this leads.
	 *
	 * @return the utm content of this leads
	 */
	@AutoEscape
	public String getUtmContent();

	/**
	 * Sets the utm content of this leads.
	 *
	 * @param UtmContent the utm content of this leads
	 */
	public void setUtmContent(String UtmContent);

	/**
	 * Returns the click ID of this leads.
	 *
	 * @return the click ID of this leads
	 */
	@AutoEscape
	public String getClickId();

	/**
	 * Sets the click ID of this leads.
	 *
	 * @param ClickId the click ID of this leads
	 */
	public void setClickId(String ClickId);

	/**
	 * Returns the name of this leads.
	 *
	 * @return the name of this leads
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this leads.
	 *
	 * @param Name the name of this leads
	 */
	public void setName(String Name);

	/**
	 * Returns the email of this leads.
	 *
	 * @return the email of this leads
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this leads.
	 *
	 * @param Email the email of this leads
	 */
	public void setEmail(String Email);

	/**
	 * Returns the mobile phone of this leads.
	 *
	 * @return the mobile phone of this leads
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this leads.
	 *
	 * @param MobilePhone the mobile phone of this leads
	 */
	public void setMobilePhone(String MobilePhone);

	/**
	 * Returns the gender of this leads.
	 *
	 * @return the gender of this leads
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this leads.
	 *
	 * @param Gender the gender of this leads
	 */
	public void setGender(String Gender);

	/**
	 * Returns the dob of this leads.
	 *
	 * @return the dob of this leads
	 */
	public Date getDob();

	/**
	 * Sets the dob of this leads.
	 *
	 * @param Dob the dob of this leads
	 */
	public void setDob(Date Dob);

	/**
	 * Returns the birth place of this leads.
	 *
	 * @return the birth place of this leads
	 */
	@AutoEscape
	public String getBirthPlace();

	/**
	 * Sets the birth place of this leads.
	 *
	 * @param BirthPlace the birth place of this leads
	 */
	public void setBirthPlace(String BirthPlace);

	/**
	 * Returns the nationality of this leads.
	 *
	 * @return the nationality of this leads
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this leads.
	 *
	 * @param Nationality the nationality of this leads
	 */
	public void setNationality(String Nationality);

	/**
	 * Returns the id number of this leads.
	 *
	 * @return the id number of this leads
	 */
	@AutoEscape
	public String getIdNumber();

	/**
	 * Sets the id number of this leads.
	 *
	 * @param IdNumber the id number of this leads
	 */
	public void setIdNumber(String IdNumber);

	/**
	 * Returns the passport number of this leads.
	 *
	 * @return the passport number of this leads
	 */
	@AutoEscape
	public String getPassportNumber();

	/**
	 * Sets the passport number of this leads.
	 *
	 * @param PassportNumber the passport number of this leads
	 */
	public void setPassportNumber(String PassportNumber);

	/**
	 * Returns the kitas number of this leads.
	 *
	 * @return the kitas number of this leads
	 */
	@AutoEscape
	public String getKitasNumber();

	/**
	 * Sets the kitas number of this leads.
	 *
	 * @param KitasNumber the kitas number of this leads
	 */
	public void setKitasNumber(String KitasNumber);

	/**
	 * Returns the id photo file entry ID of this leads.
	 *
	 * @return the id photo file entry ID of this leads
	 */
	public long getIdPhotoFileEntryId();

	/**
	 * Sets the id photo file entry ID of this leads.
	 *
	 * @param idPhotoFileEntryId the id photo file entry ID of this leads
	 */
	public void setIdPhotoFileEntryId(long idPhotoFileEntryId);

	/**
	 * Returns the address of this leads.
	 *
	 * @return the address of this leads
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this leads.
	 *
	 * @param Address the address of this leads
	 */
	public void setAddress(String Address);

	/**
	 * Returns the address2 of this leads.
	 *
	 * @return the address2 of this leads
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this leads.
	 *
	 * @param Address2 the address2 of this leads
	 */
	public void setAddress2(String Address2);

	/**
	 * Returns the province of this leads.
	 *
	 * @return the province of this leads
	 */
	@AutoEscape
	public String getProvince();

	/**
	 * Sets the province of this leads.
	 *
	 * @param Province the province of this leads
	 */
	public void setProvince(String Province);

	/**
	 * Returns the city of this leads.
	 *
	 * @return the city of this leads
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this leads.
	 *
	 * @param City the city of this leads
	 */
	public void setCity(String City);

	/**
	 * Returns the zip of this leads.
	 *
	 * @return the zip of this leads
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this leads.
	 *
	 * @param Zip the zip of this leads
	 */
	public void setZip(String Zip);

	/**
	 * Returns the active of this leads.
	 *
	 * @return the active of this leads
	 */
	public int getActive();

	/**
	 * Sets the active of this leads.
	 *
	 * @param Active the active of this leads
	 */
	public void setActive(int Active);

	/**
	 * Returns the token of this leads.
	 *
	 * @return the token of this leads
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this leads.
	 *
	 * @param Token the token of this leads
	 */
	public void setToken(String Token);

	/**
	 * Returns the policy start date of this leads.
	 *
	 * @return the policy start date of this leads
	 */
	public Date getPolicyStartDate();

	/**
	 * Sets the policy start date of this leads.
	 *
	 * @param PolicyStartDate the policy start date of this leads
	 */
	public void setPolicyStartDate(Date PolicyStartDate);

	/**
	 * Returns the policy end date of this leads.
	 *
	 * @return the policy end date of this leads
	 */
	public Date getPolicyEndDate();

	/**
	 * Sets the policy end date of this leads.
	 *
	 * @param PolicyEndDate the policy end date of this leads
	 */
	public void setPolicyEndDate(Date PolicyEndDate);

	/**
	 * Returns the temp code of this leads.
	 *
	 * @return the temp code of this leads
	 */
	@AutoEscape
	public String getTempCode();

	/**
	 * Sets the temp code of this leads.
	 *
	 * @param TempCode the temp code of this leads
	 */
	public void setTempCode(String TempCode);

	/**
	 * Returns the status of this leads.
	 *
	 * @return the status of this leads
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this leads.
	 *
	 * @param Status the status of this leads
	 */
	public void setStatus(String Status);

	/**
	 * Returns the payment status of this leads.
	 *
	 * @return the payment status of this leads
	 */
	@AutoEscape
	public String getPaymentStatus();

	/**
	 * Sets the payment status of this leads.
	 *
	 * @param PaymentStatus the payment status of this leads
	 */
	public void setPaymentStatus(String PaymentStatus);

	/**
	 * Returns the mypage user ID of this leads.
	 *
	 * @return the mypage user ID of this leads
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this leads.
	 *
	 * @param mypageUserId the mypage user ID of this leads
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this leads.
	 *
	 * @return the mypage user uuid of this leads
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this leads.
	 *
	 * @param mypageUserUuid the mypage user uuid of this leads
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the managed by of this leads.
	 *
	 * @return the managed by of this leads
	 */
	@AutoEscape
	public String getManagedBy();

	/**
	 * Sets the managed by of this leads.
	 *
	 * @param managedBy the managed by of this leads
	 */
	public void setManagedBy(String managedBy);

	/**
	 * Returns the group ID of this leads.
	 *
	 * @return the group ID of this leads
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this leads.
	 *
	 * @param groupId the group ID of this leads
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leads.
	 *
	 * @return the company ID of this leads
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leads.
	 *
	 * @param companyId the company ID of this leads
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this leads.
	 *
	 * @return the user ID of this leads
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this leads.
	 *
	 * @param userId the user ID of this leads
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leads.
	 *
	 * @return the user uuid of this leads
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this leads.
	 *
	 * @param userUuid the user uuid of this leads
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this leads.
	 *
	 * @return the user name of this leads
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this leads.
	 *
	 * @param userName the user name of this leads
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this leads.
	 *
	 * @return the create date of this leads
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leads.
	 *
	 * @param createDate the create date of this leads
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leads.
	 *
	 * @return the modified date of this leads
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leads.
	 *
	 * @param modifiedDate the modified date of this leads
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the is pep of this leads.
	 *
	 * @return the is pep of this leads
	 */
	public int getIsPep();

	/**
	 * Sets the is pep of this leads.
	 *
	 * @param isPep the is pep of this leads
	 */
	public void setIsPep(int isPep);

	/**
	 * Returns the country code of this leads.
	 *
	 * @return the country code of this leads
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this leads.
	 *
	 * @param CountryCode the country code of this leads
	 */
	public void setCountryCode(String CountryCode);

	/**
	 * Returns the job of this leads.
	 *
	 * @return the job of this leads
	 */
	@AutoEscape
	public String getJob();

	/**
	 * Sets the job of this leads.
	 *
	 * @param Job the job of this leads
	 */
	public void setJob(String Job);

	/**
	 * Returns the job other of this leads.
	 *
	 * @return the job other of this leads
	 */
	@AutoEscape
	public String getJobOther();

	/**
	 * Sets the job other of this leads.
	 *
	 * @param JobOther the job other of this leads
	 */
	public void setJobOther(String JobOther);

	/**
	 * Returns the age of this leads.
	 *
	 * @return the age of this leads
	 */
	public int getAge();

	/**
	 * Sets the age of this leads.
	 *
	 * @param Age the age of this leads
	 */
	public void setAge(int Age);

	/**
	 * Returns the marital status of this leads.
	 *
	 * @return the marital status of this leads
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this leads.
	 *
	 * @param MaritalStatus the marital status of this leads
	 */
	public void setMaritalStatus(String MaritalStatus);

	/**
	 * Returns the phone of this leads.
	 *
	 * @return the phone of this leads
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this leads.
	 *
	 * @param Phone the phone of this leads
	 */
	public void setPhone(String Phone);

	/**
	 * Returns the photo file url of this leads.
	 *
	 * @return the photo file url of this leads
	 */
	@AutoEscape
	public String getPhotoFileUrl();

	/**
	 * Sets the photo file url of this leads.
	 *
	 * @param PhotoFileUrl the photo file url of this leads
	 */
	public void setPhotoFileUrl(String PhotoFileUrl);

	/**
	 * Returns the work location of this leads.
	 *
	 * @return the work location of this leads
	 */
	@AutoEscape
	public String getWorkLocation();

	/**
	 * Sets the work location of this leads.
	 *
	 * @param WorkLocation the work location of this leads
	 */
	public void setWorkLocation(String WorkLocation);

	/**
	 * Returns the work location other of this leads.
	 *
	 * @return the work location other of this leads
	 */
	@AutoEscape
	public String getWorkLocationOther();

	/**
	 * Sets the work location other of this leads.
	 *
	 * @param WorkLocationOther the work location other of this leads
	 */
	public void setWorkLocationOther(String WorkLocationOther);

	/**
	 * Returns the monthly income of this leads.
	 *
	 * @return the monthly income of this leads
	 */
	@AutoEscape
	public String getMonthlyIncome();

	/**
	 * Sets the monthly income of this leads.
	 *
	 * @param MonthlyIncome the monthly income of this leads
	 */
	public void setMonthlyIncome(String MonthlyIncome);

	/**
	 * Returns the payment source of this leads.
	 *
	 * @return the payment source of this leads
	 */
	@AutoEscape
	public String getPaymentSource();

	/**
	 * Sets the payment source of this leads.
	 *
	 * @param PaymentSource the payment source of this leads
	 */
	public void setPaymentSource(String PaymentSource);

	/**
	 * Returns the payment source other of this leads.
	 *
	 * @return the payment source other of this leads
	 */
	@AutoEscape
	public String getPaymentSourceOther();

	/**
	 * Sets the payment source other of this leads.
	 *
	 * @param PaymentSourceOther the payment source other of this leads
	 */
	public void setPaymentSourceOther(String PaymentSourceOther);

	/**
	 * Returns the beneficiary of this leads.
	 *
	 * @return the beneficiary of this leads
	 */
	@AutoEscape
	public String getBeneficiary();

	/**
	 * Sets the beneficiary of this leads.
	 *
	 * @param Beneficiary the beneficiary of this leads
	 */
	public void setBeneficiary(String Beneficiary);

	/**
	 * Returns the beneficiary relationship of this leads.
	 *
	 * @return the beneficiary relationship of this leads
	 */
	@AutoEscape
	public String getBeneficiaryRelationship();

	/**
	 * Sets the beneficiary relationship of this leads.
	 *
	 * @param BeneficiaryRelationship the beneficiary relationship of this leads
	 */
	public void setBeneficiaryRelationship(String BeneficiaryRelationship);

}