create table CreditType (
	creditTypeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	mypageUserId LONG,
	name VARCHAR(75) null,
	agentType VARCHAR(75) null,
	limit_ DOUBLE,
	overrideGracePeriod INTEGER,
	nettPremiAllowed INTEGER,
	active_ INTEGER
);

create table CreditWallet (
	creditWalletId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	creditTypeId LONG,
	dateIssued DATE null,
	dateExpired DATE null,
	amount DOUBLE,
	active_ INTEGER
);

create table CreditWalletHistory (
	creditWalletHistoryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	mypageUserId LONG,
	creditWalletId LONG,
	leadsId LONG,
	operation VARCHAR(75) null,
	amount DOUBLE,
	active_ INTEGER
);

create table MypageGroupUser (
	mypageGroupUserId LONG not null primary key,
	mypageGroupId LONG,
	mypageUserId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table MypageUser (
	mypageUserId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	liferayUserId LONG,
	userPassword VARCHAR(75) null,
	agentFlag VARCHAR(75) null,
	userParent LONG,
	userBranch LONG,
	mypageUserRoleId LONG,
	status VARCHAR(75) null,
	creditStatus VARCHAR(75) null,
	creditWalletId LONG,
	cashPayment INTEGER,
	paymentMethod VARCHAR(75) null,
	loginCounter INTEGER,
	lastSubmitLoginDate DATE null,
	TempCode VARCHAR(75) null,
	TempCodeExpiryDate DATE null,
	phone VARCHAR(75) null,
	mobilePhone VARCHAR(75) null,
	email VARCHAR(75) null,
	birthPlace VARCHAR(75) null,
	dob DATE null,
	idNumber VARCHAR(75) null,
	address VARCHAR(75) null,
	zip VARCHAR(75) null,
	gender VARCHAR(75) null,
	country LONG,
	province LONG,
	city LONG,
	latitude VARCHAR(75) null,
	longitude VARCHAR(75) null,
	positionZoom INTEGER,
	code_ VARCHAR(75) null,
	branch LONG,
	promoCode VARCHAR(75) null,
	agsPromoCode VARCHAR(75) null,
	deptoreCode VARCHAR(75) null,
	club VARCHAR(75) null,
	leader LONG,
	statusAgent VARCHAR(75) null,
	licenseNumber VARCHAR(75) null,
	joinDate DATE null,
	endDate DATE null,
	prettyUrl VARCHAR(75) null,
	prettyUrlChange INTEGER,
	taxRate DOUBLE,
	visitedCount INTEGER,
	isPartnership INTEGER,
	partnershipName VARCHAR(75) null,
	defCommPartnerMV DOUBLE,
	defCommPartnerEH DOUBLE,
	defCommPartnerDT DOUBLE,
	defCommPartnerIT DOUBLE,
	defCommPartnerSME DOUBLE,
	defCommPartnerProperty DOUBLE,
	defCommPartnerPet DOUBLE,
	defCommPartnerPA DOUBLE,
	defCommPartnerGP DOUBLE,
	bannerImageURL VARCHAR(75) null,
	bannerImageFileEntryId LONG,
	profileImageURL VARCHAR(75) null,
	profileImageFileEntryId LONG,
	myTitle VARCHAR(75) null,
	myVideo VARCHAR(75) null,
	aboutMe VARCHAR(75) null,
	facebook VARCHAR(75) null,
	tiktok VARCHAR(75) null,
	instagram VARCHAR(75) null,
	twitter VARCHAR(75) null,
	linkedIn VARCHAR(75) null,
	blog VARCHAR(75) null,
	whatsapp VARCHAR(75) null,
	skype VARCHAR(75) null,
	is24Hours INTEGER,
	active_ INTEGER
);

create table MypageUserGracePeriod (
	mypageUserGracePeriodId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	mypageUserId LONG,
	code_ VARCHAR(75) null,
	value INTEGER
);

create table MypageUserGroup (
	mypageUserGroupId LONG not null primary key,
	name VARCHAR(75) null,
	active_ INTEGER,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table MypageUserLicenses (
	mypageUserLicensesId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	mypageUserId LONG,
	productId LONG
);

create table MypageUserRole (
	mypageUserRoleId LONG not null primary key,
	name VARCHAR(75) null,
	active_ INTEGER,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table MypageUserTimeline (
	mypageUserTimelineId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	mypageUserId LONG,
	imgUploadTimelineEntryId LONG,
	imgUploadTimelineUrl VARCHAR(75) null,
	videoUploadTimelineUrl VARCHAR(75) null,
	text_ VARCHAR(75) null
);

create table MypageUserWorkingHour (
	mypageUserWorkingHourId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	mypageUserId LONG,
	day VARCHAR(75) null,
	startTime VARCHAR(75) null,
	endTime VARCHAR(75) null,
	status INTEGER
);

create table UserOneTimeCode (
	userOneTimeCodeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	sharedSecret VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	expiryDate DATE null,
	TimestampExpiryDate LONG,
	isUsed INTEGER
);

create table UserRegistration (
	userRegistrationId LONG not null primary key,
	name VARCHAR(75) null,
	idNumber VARCHAR(75) null,
	licenseNumber VARCHAR(75) null,
	address VARCHAR(75) null,
	postalAddress VARCHAR(75) null,
	province VARCHAR(75) null,
	city VARCHAR(75) null,
	zip VARCHAR(75) null,
	phone VARCHAR(75) null,
	mobilePhone VARCHAR(75) null,
	email VARCHAR(75) null,
	birthPlace VARCHAR(75) null,
	dob DATE null,
	gender VARCHAR(75) null,
	maritalStatus VARCHAR(75) null,
	residenceStatus VARCHAR(75) null,
	stayPeriod INTEGER,
	knowAXAFrom INTEGER,
	knowAXAFromOther VARCHAR(75) null,
	joinReason VARCHAR(75) null,
	bankName VARCHAR(75) null,
	bankAccountName VARCHAR(75) null,
	bankAccountNo VARCHAR(75) null,
	npwp VARCHAR(75) null,
	npwpName VARCHAR(75) null,
	portfolioFire INTEGER,
	portfolioMotor INTEGER,
	portfolioMarine INTEGER,
	portfolioHealth INTEGER,
	portfolioOther INTEGER,
	targetFire INTEGER,
	targetMotor INTEGER,
	targetMarine INTEGER,
	targetHealth INTEGER,
	targetOther INTEGER,
	annualPremiIncome LONG,
	targetCase INTEGER,
	targetPremi LONG,
	prospectSource VARCHAR(75) null,
	otherInsuranceJob INTEGER,
	tnc INTEGER,
	agentAFI INTEGER,
	sentToMAS INTEGER,
	approved INTEGER,
	active_ INTEGER,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table UserRegistrationEducation (
	userRegistrationEducationId LONG not null primary key,
	name VARCHAR(75) null,
	year INTEGER,
	graduate INTEGER,
	courseType VARCHAR(75) null,
	title VARCHAR(75) null,
	eduType VARCHAR(75) null,
	userRegistrationId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table UserRegistrationJobExp (
	userRegistrationJobExpId LONG not null primary key,
	name VARCHAR(75) null,
	year INTEGER,
	jobHead VARCHAR(75) null,
	jobPosition VARCHAR(75) null,
	jobIncome VARCHAR(75) null,
	otherInsuranceCompany INTEGER,
	userRegistrationId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table UserRegistrationLiability (
	userRegistrationLiabilityId LONG not null primary key,
	name VARCHAR(75) null,
	relationship VARCHAR(75) null,
	age INTEGER,
	userRegistrationId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table UserRegistrationReference (
	userRegistrationReferenceId LONG not null primary key,
	name VARCHAR(75) null,
	relation VARCHAR(75) null,
	age INTEGER,
	address VARCHAR(75) null,
	phone VARCHAR(75) null,
	job VARCHAR(75) null,
	year INTEGER,
	userRegistrationId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);