/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.user.model.CreditWalletHistory;
import com.mypage.user.service.CreditWalletHistoryLocalService;
import com.mypage.user.service.CreditWalletHistoryLocalServiceUtil;
import com.mypage.user.service.persistence.CreditTypePersistence;
import com.mypage.user.service.persistence.CreditWalletHistoryPersistence;
import com.mypage.user.service.persistence.CreditWalletPersistence;
import com.mypage.user.service.persistence.MypageGroupUserFinder;
import com.mypage.user.service.persistence.MypageGroupUserPersistence;
import com.mypage.user.service.persistence.MypageUserGracePeriodPersistence;
import com.mypage.user.service.persistence.MypageUserGroupPersistence;
import com.mypage.user.service.persistence.MypageUserLicensesPersistence;
import com.mypage.user.service.persistence.MypageUserPersistence;
import com.mypage.user.service.persistence.MypageUserRolePersistence;
import com.mypage.user.service.persistence.MypageUserTimelinePersistence;
import com.mypage.user.service.persistence.MypageUserWorkingHourPersistence;
import com.mypage.user.service.persistence.UserOneTimeCodePersistence;
import com.mypage.user.service.persistence.UserRegistrationEducationPersistence;
import com.mypage.user.service.persistence.UserRegistrationJobExpPersistence;
import com.mypage.user.service.persistence.UserRegistrationLiabilityPersistence;
import com.mypage.user.service.persistence.UserRegistrationPersistence;
import com.mypage.user.service.persistence.UserRegistrationReferencePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the credit wallet history local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.user.service.impl.CreditWalletHistoryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.mypage.user.service.impl.CreditWalletHistoryLocalServiceImpl
 * @generated
 */
public abstract class CreditWalletHistoryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CreditWalletHistoryLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CreditWalletHistoryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CreditWalletHistoryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the credit wallet history to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreditWalletHistoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creditWalletHistory the credit wallet history
	 * @return the credit wallet history that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CreditWalletHistory addCreditWalletHistory(
		CreditWalletHistory creditWalletHistory) {

		creditWalletHistory.setNew(true);

		return creditWalletHistoryPersistence.update(creditWalletHistory);
	}

	/**
	 * Creates a new credit wallet history with the primary key. Does not add the credit wallet history to the database.
	 *
	 * @param creditWalletHistoryId the primary key for the new credit wallet history
	 * @return the new credit wallet history
	 */
	@Override
	@Transactional(enabled = false)
	public CreditWalletHistory createCreditWalletHistory(
		long creditWalletHistoryId) {

		return creditWalletHistoryPersistence.create(creditWalletHistoryId);
	}

	/**
	 * Deletes the credit wallet history with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreditWalletHistoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creditWalletHistoryId the primary key of the credit wallet history
	 * @return the credit wallet history that was removed
	 * @throws PortalException if a credit wallet history with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CreditWalletHistory deleteCreditWalletHistory(
			long creditWalletHistoryId)
		throws PortalException {

		return creditWalletHistoryPersistence.remove(creditWalletHistoryId);
	}

	/**
	 * Deletes the credit wallet history from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreditWalletHistoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creditWalletHistory the credit wallet history
	 * @return the credit wallet history that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CreditWalletHistory deleteCreditWalletHistory(
		CreditWalletHistory creditWalletHistory) {

		return creditWalletHistoryPersistence.remove(creditWalletHistory);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CreditWalletHistory.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return creditWalletHistoryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.user.model.impl.CreditWalletHistoryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return creditWalletHistoryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.user.model.impl.CreditWalletHistoryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return creditWalletHistoryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return creditWalletHistoryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return creditWalletHistoryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CreditWalletHistory fetchCreditWalletHistory(
		long creditWalletHistoryId) {

		return creditWalletHistoryPersistence.fetchByPrimaryKey(
			creditWalletHistoryId);
	}

	/**
	 * Returns the credit wallet history with the primary key.
	 *
	 * @param creditWalletHistoryId the primary key of the credit wallet history
	 * @return the credit wallet history
	 * @throws PortalException if a credit wallet history with the primary key could not be found
	 */
	@Override
	public CreditWalletHistory getCreditWalletHistory(
			long creditWalletHistoryId)
		throws PortalException {

		return creditWalletHistoryPersistence.findByPrimaryKey(
			creditWalletHistoryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			creditWalletHistoryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CreditWalletHistory.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"creditWalletHistoryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			creditWalletHistoryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CreditWalletHistory.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"creditWalletHistoryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			creditWalletHistoryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CreditWalletHistory.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"creditWalletHistoryId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return creditWalletHistoryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return creditWalletHistoryLocalService.deleteCreditWalletHistory(
			(CreditWalletHistory)persistedModel);
	}

	public BasePersistence<CreditWalletHistory> getBasePersistence() {
		return creditWalletHistoryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return creditWalletHistoryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the credit wallet histories.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.user.model.impl.CreditWalletHistoryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of credit wallet histories
	 * @param end the upper bound of the range of credit wallet histories (not inclusive)
	 * @return the range of credit wallet histories
	 */
	@Override
	public List<CreditWalletHistory> getCreditWalletHistories(
		int start, int end) {

		return creditWalletHistoryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of credit wallet histories.
	 *
	 * @return the number of credit wallet histories
	 */
	@Override
	public int getCreditWalletHistoriesCount() {
		return creditWalletHistoryPersistence.countAll();
	}

	/**
	 * Updates the credit wallet history in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CreditWalletHistoryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param creditWalletHistory the credit wallet history
	 * @return the credit wallet history that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CreditWalletHistory updateCreditWalletHistory(
		CreditWalletHistory creditWalletHistory) {

		return creditWalletHistoryPersistence.update(creditWalletHistory);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CreditWalletHistoryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		creditWalletHistoryLocalService =
			(CreditWalletHistoryLocalService)aopProxy;

		_setLocalServiceUtilService(creditWalletHistoryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CreditWalletHistoryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CreditWalletHistory.class;
	}

	protected String getModelClassName() {
		return CreditWalletHistory.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				creditWalletHistoryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		CreditWalletHistoryLocalService creditWalletHistoryLocalService) {

		try {
			Field field =
				CreditWalletHistoryLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, creditWalletHistoryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CreditTypePersistence creditTypePersistence;

	@Reference
	protected CreditWalletPersistence creditWalletPersistence;

	protected CreditWalletHistoryLocalService creditWalletHistoryLocalService;

	@Reference
	protected CreditWalletHistoryPersistence creditWalletHistoryPersistence;

	@Reference
	protected MypageGroupUserPersistence mypageGroupUserPersistence;

	@Reference
	protected MypageGroupUserFinder mypageGroupUserFinder;

	@Reference
	protected MypageUserPersistence mypageUserPersistence;

	@Reference
	protected MypageUserGracePeriodPersistence mypageUserGracePeriodPersistence;

	@Reference
	protected MypageUserGroupPersistence mypageUserGroupPersistence;

	@Reference
	protected MypageUserLicensesPersistence mypageUserLicensesPersistence;

	@Reference
	protected MypageUserRolePersistence mypageUserRolePersistence;

	@Reference
	protected MypageUserTimelinePersistence mypageUserTimelinePersistence;

	@Reference
	protected MypageUserWorkingHourPersistence mypageUserWorkingHourPersistence;

	@Reference
	protected UserOneTimeCodePersistence userOneTimeCodePersistence;

	@Reference
	protected UserRegistrationPersistence userRegistrationPersistence;

	@Reference
	protected UserRegistrationEducationPersistence
		userRegistrationEducationPersistence;

	@Reference
	protected UserRegistrationJobExpPersistence
		userRegistrationJobExpPersistence;

	@Reference
	protected UserRegistrationLiabilityPersistence
		userRegistrationLiabilityPersistence;

	@Reference
	protected UserRegistrationReferencePersistence
		userRegistrationReferencePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}