/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.user.model.MypageUserGracePeriod;
import com.mypage.user.service.MypageUserGracePeriodService;
import com.mypage.user.service.MypageUserGracePeriodServiceUtil;
import com.mypage.user.service.persistence.CreditTypePersistence;
import com.mypage.user.service.persistence.CreditWalletHistoryPersistence;
import com.mypage.user.service.persistence.CreditWalletPersistence;
import com.mypage.user.service.persistence.MypageGroupUserFinder;
import com.mypage.user.service.persistence.MypageGroupUserPersistence;
import com.mypage.user.service.persistence.MypageUserGracePeriodPersistence;
import com.mypage.user.service.persistence.MypageUserGroupPersistence;
import com.mypage.user.service.persistence.MypageUserLicensesPersistence;
import com.mypage.user.service.persistence.MypageUserPersistence;
import com.mypage.user.service.persistence.MypageUserRolePersistence;
import com.mypage.user.service.persistence.MypageUserTimelinePersistence;
import com.mypage.user.service.persistence.MypageUserWorkingHourPersistence;
import com.mypage.user.service.persistence.UserOneTimeCodePersistence;
import com.mypage.user.service.persistence.UserRegistrationEducationPersistence;
import com.mypage.user.service.persistence.UserRegistrationJobExpPersistence;
import com.mypage.user.service.persistence.UserRegistrationLiabilityPersistence;
import com.mypage.user.service.persistence.UserRegistrationPersistence;
import com.mypage.user.service.persistence.UserRegistrationReferencePersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the mypage user grace period remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.user.service.impl.MypageUserGracePeriodServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.mypage.user.service.impl.MypageUserGracePeriodServiceImpl
 * @generated
 */
public abstract class MypageUserGracePeriodServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService,
			   MypageUserGracePeriodService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MypageUserGracePeriodService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>MypageUserGracePeriodServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MypageUserGracePeriodService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		mypageUserGracePeriodService = (MypageUserGracePeriodService)aopProxy;

		_setServiceUtilService(mypageUserGracePeriodService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MypageUserGracePeriodService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MypageUserGracePeriod.class;
	}

	protected String getModelClassName() {
		return MypageUserGracePeriod.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				mypageUserGracePeriodPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		MypageUserGracePeriodService mypageUserGracePeriodService) {

		try {
			Field field =
				MypageUserGracePeriodServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, mypageUserGracePeriodService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CreditTypePersistence creditTypePersistence;

	@Reference
	protected CreditWalletPersistence creditWalletPersistence;

	@Reference
	protected CreditWalletHistoryPersistence creditWalletHistoryPersistence;

	@Reference
	protected MypageGroupUserPersistence mypageGroupUserPersistence;

	@Reference
	protected MypageGroupUserFinder mypageGroupUserFinder;

	@Reference
	protected MypageUserPersistence mypageUserPersistence;

	@Reference
	protected com.mypage.user.service.MypageUserGracePeriodLocalService
		mypageUserGracePeriodLocalService;

	protected MypageUserGracePeriodService mypageUserGracePeriodService;

	@Reference
	protected MypageUserGracePeriodPersistence mypageUserGracePeriodPersistence;

	@Reference
	protected MypageUserGroupPersistence mypageUserGroupPersistence;

	@Reference
	protected MypageUserLicensesPersistence mypageUserLicensesPersistence;

	@Reference
	protected MypageUserRolePersistence mypageUserRolePersistence;

	@Reference
	protected MypageUserTimelinePersistence mypageUserTimelinePersistence;

	@Reference
	protected MypageUserWorkingHourPersistence mypageUserWorkingHourPersistence;

	@Reference
	protected UserOneTimeCodePersistence userOneTimeCodePersistence;

	@Reference
	protected UserRegistrationPersistence userRegistrationPersistence;

	@Reference
	protected UserRegistrationEducationPersistence
		userRegistrationEducationPersistence;

	@Reference
	protected UserRegistrationJobExpPersistence
		userRegistrationJobExpPersistence;

	@Reference
	protected UserRegistrationLiabilityPersistence
		userRegistrationLiabilityPersistence;

	@Reference
	protected UserRegistrationReferencePersistence
		userRegistrationReferencePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}