/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.user.model.MypageUserTimeline;
import com.mypage.user.service.MypageUserTimelineLocalService;
import com.mypage.user.service.MypageUserTimelineLocalServiceUtil;
import com.mypage.user.service.persistence.CreditTypePersistence;
import com.mypage.user.service.persistence.CreditWalletHistoryPersistence;
import com.mypage.user.service.persistence.CreditWalletPersistence;
import com.mypage.user.service.persistence.MypageGroupUserFinder;
import com.mypage.user.service.persistence.MypageGroupUserPersistence;
import com.mypage.user.service.persistence.MypageUserGracePeriodPersistence;
import com.mypage.user.service.persistence.MypageUserGroupPersistence;
import com.mypage.user.service.persistence.MypageUserLicensesPersistence;
import com.mypage.user.service.persistence.MypageUserPersistence;
import com.mypage.user.service.persistence.MypageUserRolePersistence;
import com.mypage.user.service.persistence.MypageUserTimelinePersistence;
import com.mypage.user.service.persistence.MypageUserWorkingHourPersistence;
import com.mypage.user.service.persistence.UserOneTimeCodePersistence;
import com.mypage.user.service.persistence.UserRegistrationEducationPersistence;
import com.mypage.user.service.persistence.UserRegistrationJobExpPersistence;
import com.mypage.user.service.persistence.UserRegistrationLiabilityPersistence;
import com.mypage.user.service.persistence.UserRegistrationPersistence;
import com.mypage.user.service.persistence.UserRegistrationReferencePersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the mypage user timeline local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.user.service.impl.MypageUserTimelineLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.mypage.user.service.impl.MypageUserTimelineLocalServiceImpl
 * @generated
 */
public abstract class MypageUserTimelineLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   MypageUserTimelineLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MypageUserTimelineLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>MypageUserTimelineLocalServiceUtil</code>.
	 */

	/**
	 * Adds the mypage user timeline to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MypageUserTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param mypageUserTimeline the mypage user timeline
	 * @return the mypage user timeline that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MypageUserTimeline addMypageUserTimeline(
		MypageUserTimeline mypageUserTimeline) {

		mypageUserTimeline.setNew(true);

		return mypageUserTimelinePersistence.update(mypageUserTimeline);
	}

	/**
	 * Creates a new mypage user timeline with the primary key. Does not add the mypage user timeline to the database.
	 *
	 * @param mypageUserTimelineId the primary key for the new mypage user timeline
	 * @return the new mypage user timeline
	 */
	@Override
	@Transactional(enabled = false)
	public MypageUserTimeline createMypageUserTimeline(
		long mypageUserTimelineId) {

		return mypageUserTimelinePersistence.create(mypageUserTimelineId);
	}

	/**
	 * Deletes the mypage user timeline with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MypageUserTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param mypageUserTimelineId the primary key of the mypage user timeline
	 * @return the mypage user timeline that was removed
	 * @throws PortalException if a mypage user timeline with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MypageUserTimeline deleteMypageUserTimeline(
			long mypageUserTimelineId)
		throws PortalException {

		return mypageUserTimelinePersistence.remove(mypageUserTimelineId);
	}

	/**
	 * Deletes the mypage user timeline from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MypageUserTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param mypageUserTimeline the mypage user timeline
	 * @return the mypage user timeline that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MypageUserTimeline deleteMypageUserTimeline(
		MypageUserTimeline mypageUserTimeline) {

		return mypageUserTimelinePersistence.remove(mypageUserTimeline);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			MypageUserTimeline.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return mypageUserTimelinePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.user.model.impl.MypageUserTimelineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return mypageUserTimelinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.user.model.impl.MypageUserTimelineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return mypageUserTimelinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return mypageUserTimelinePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return mypageUserTimelinePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public MypageUserTimeline fetchMypageUserTimeline(
		long mypageUserTimelineId) {

		return mypageUserTimelinePersistence.fetchByPrimaryKey(
			mypageUserTimelineId);
	}

	/**
	 * Returns the mypage user timeline with the primary key.
	 *
	 * @param mypageUserTimelineId the primary key of the mypage user timeline
	 * @return the mypage user timeline
	 * @throws PortalException if a mypage user timeline with the primary key could not be found
	 */
	@Override
	public MypageUserTimeline getMypageUserTimeline(long mypageUserTimelineId)
		throws PortalException {

		return mypageUserTimelinePersistence.findByPrimaryKey(
			mypageUserTimelineId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			mypageUserTimelineLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MypageUserTimeline.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"mypageUserTimelineId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			mypageUserTimelineLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MypageUserTimeline.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"mypageUserTimelineId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			mypageUserTimelineLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MypageUserTimeline.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"mypageUserTimelineId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return mypageUserTimelinePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return mypageUserTimelineLocalService.deleteMypageUserTimeline(
			(MypageUserTimeline)persistedModel);
	}

	public BasePersistence<MypageUserTimeline> getBasePersistence() {
		return mypageUserTimelinePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return mypageUserTimelinePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the mypage user timelines.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.user.model.impl.MypageUserTimelineModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of mypage user timelines
	 * @param end the upper bound of the range of mypage user timelines (not inclusive)
	 * @return the range of mypage user timelines
	 */
	@Override
	public List<MypageUserTimeline> getMypageUserTimelines(int start, int end) {
		return mypageUserTimelinePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of mypage user timelines.
	 *
	 * @return the number of mypage user timelines
	 */
	@Override
	public int getMypageUserTimelinesCount() {
		return mypageUserTimelinePersistence.countAll();
	}

	/**
	 * Updates the mypage user timeline in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MypageUserTimelineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param mypageUserTimeline the mypage user timeline
	 * @return the mypage user timeline that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MypageUserTimeline updateMypageUserTimeline(
		MypageUserTimeline mypageUserTimeline) {

		return mypageUserTimelinePersistence.update(mypageUserTimeline);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MypageUserTimelineLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		mypageUserTimelineLocalService =
			(MypageUserTimelineLocalService)aopProxy;

		_setLocalServiceUtilService(mypageUserTimelineLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MypageUserTimelineLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MypageUserTimeline.class;
	}

	protected String getModelClassName() {
		return MypageUserTimeline.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				mypageUserTimelinePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		MypageUserTimelineLocalService mypageUserTimelineLocalService) {

		try {
			Field field =
				MypageUserTimelineLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, mypageUserTimelineLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CreditTypePersistence creditTypePersistence;

	@Reference
	protected CreditWalletPersistence creditWalletPersistence;

	@Reference
	protected CreditWalletHistoryPersistence creditWalletHistoryPersistence;

	@Reference
	protected MypageGroupUserPersistence mypageGroupUserPersistence;

	@Reference
	protected MypageGroupUserFinder mypageGroupUserFinder;

	@Reference
	protected MypageUserPersistence mypageUserPersistence;

	@Reference
	protected MypageUserGracePeriodPersistence mypageUserGracePeriodPersistence;

	@Reference
	protected MypageUserGroupPersistence mypageUserGroupPersistence;

	@Reference
	protected MypageUserLicensesPersistence mypageUserLicensesPersistence;

	@Reference
	protected MypageUserRolePersistence mypageUserRolePersistence;

	protected MypageUserTimelineLocalService mypageUserTimelineLocalService;

	@Reference
	protected MypageUserTimelinePersistence mypageUserTimelinePersistence;

	@Reference
	protected MypageUserWorkingHourPersistence mypageUserWorkingHourPersistence;

	@Reference
	protected UserOneTimeCodePersistence userOneTimeCodePersistence;

	@Reference
	protected UserRegistrationPersistence userRegistrationPersistence;

	@Reference
	protected UserRegistrationEducationPersistence
		userRegistrationEducationPersistence;

	@Reference
	protected UserRegistrationJobExpPersistence
		userRegistrationJobExpPersistence;

	@Reference
	protected UserRegistrationLiabilityPersistence
		userRegistrationLiabilityPersistence;

	@Reference
	protected UserRegistrationReferencePersistence
		userRegistrationReferencePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}