/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.agencyportal.model.AgentEmailBucket;
import com.mypage.agencyportal.service.AgentEmailBucketLocalService;
import com.mypage.agencyportal.service.AgentEmailBucketLocalServiceUtil;
import com.mypage.agencyportal.service.persistence.AgentCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentCategorySalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentEmailBucketPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQCategoryPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQPersistence;
import com.mypage.agencyportal.service.persistence.AgentMarkCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentNotificationPersistence;
import com.mypage.agencyportal.service.persistence.AgentSalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenLimiterPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the agent email bucket local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.agencyportal.service.impl.AgentEmailBucketLocalServiceImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see com.mypage.agencyportal.service.impl.AgentEmailBucketLocalServiceImpl
 * @generated
 */
public abstract class AgentEmailBucketLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AgentEmailBucketLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AgentEmailBucketLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AgentEmailBucketLocalServiceUtil</code>.
	 */

	/**
	 * Adds the agent email bucket to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentEmailBucketLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentEmailBucket the agent email bucket
	 * @return the agent email bucket that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AgentEmailBucket addAgentEmailBucket(
		AgentEmailBucket agentEmailBucket) {

		agentEmailBucket.setNew(true);

		return agentEmailBucketPersistence.update(agentEmailBucket);
	}

	/**
	 * Creates a new agent email bucket with the primary key. Does not add the agent email bucket to the database.
	 *
	 * @param agentEmailBucketId the primary key for the new agent email bucket
	 * @return the new agent email bucket
	 */
	@Override
	@Transactional(enabled = false)
	public AgentEmailBucket createAgentEmailBucket(long agentEmailBucketId) {
		return agentEmailBucketPersistence.create(agentEmailBucketId);
	}

	/**
	 * Deletes the agent email bucket with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentEmailBucketLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentEmailBucketId the primary key of the agent email bucket
	 * @return the agent email bucket that was removed
	 * @throws PortalException if a agent email bucket with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AgentEmailBucket deleteAgentEmailBucket(long agentEmailBucketId)
		throws PortalException {

		return agentEmailBucketPersistence.remove(agentEmailBucketId);
	}

	/**
	 * Deletes the agent email bucket from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentEmailBucketLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentEmailBucket the agent email bucket
	 * @return the agent email bucket that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AgentEmailBucket deleteAgentEmailBucket(
		AgentEmailBucket agentEmailBucket) {

		return agentEmailBucketPersistence.remove(agentEmailBucket);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AgentEmailBucket.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return agentEmailBucketPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentEmailBucketModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return agentEmailBucketPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentEmailBucketModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return agentEmailBucketPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return agentEmailBucketPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return agentEmailBucketPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AgentEmailBucket fetchAgentEmailBucket(long agentEmailBucketId) {
		return agentEmailBucketPersistence.fetchByPrimaryKey(
			agentEmailBucketId);
	}

	/**
	 * Returns the agent email bucket with the primary key.
	 *
	 * @param agentEmailBucketId the primary key of the agent email bucket
	 * @return the agent email bucket
	 * @throws PortalException if a agent email bucket with the primary key could not be found
	 */
	@Override
	public AgentEmailBucket getAgentEmailBucket(long agentEmailBucketId)
		throws PortalException {

		return agentEmailBucketPersistence.findByPrimaryKey(agentEmailBucketId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			agentEmailBucketLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AgentEmailBucket.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("agentEmailBucketId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			agentEmailBucketLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AgentEmailBucket.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"agentEmailBucketId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			agentEmailBucketLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AgentEmailBucket.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("agentEmailBucketId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return agentEmailBucketPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return agentEmailBucketLocalService.deleteAgentEmailBucket(
			(AgentEmailBucket)persistedModel);
	}

	public BasePersistence<AgentEmailBucket> getBasePersistence() {
		return agentEmailBucketPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return agentEmailBucketPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the agent email buckets.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentEmailBucketModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of agent email buckets
	 * @param end the upper bound of the range of agent email buckets (not inclusive)
	 * @return the range of agent email buckets
	 */
	@Override
	public List<AgentEmailBucket> getAgentEmailBuckets(int start, int end) {
		return agentEmailBucketPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of agent email buckets.
	 *
	 * @return the number of agent email buckets
	 */
	@Override
	public int getAgentEmailBucketsCount() {
		return agentEmailBucketPersistence.countAll();
	}

	/**
	 * Updates the agent email bucket in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentEmailBucketLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentEmailBucket the agent email bucket
	 * @return the agent email bucket that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AgentEmailBucket updateAgentEmailBucket(
		AgentEmailBucket agentEmailBucket) {

		return agentEmailBucketPersistence.update(agentEmailBucket);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AgentEmailBucketLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		agentEmailBucketLocalService = (AgentEmailBucketLocalService)aopProxy;

		_setLocalServiceUtilService(agentEmailBucketLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AgentEmailBucketLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AgentEmailBucket.class;
	}

	protected String getModelClassName() {
		return AgentEmailBucket.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = agentEmailBucketPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AgentEmailBucketLocalService agentEmailBucketLocalService) {

		try {
			Field field =
				AgentEmailBucketLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, agentEmailBucketLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AgentCalendarPersistence agentCalendarPersistence;

	@Reference
	protected AgentCategorySalesToolsPersistence
		agentCategorySalesToolsPersistence;

	protected AgentEmailBucketLocalService agentEmailBucketLocalService;

	@Reference
	protected AgentEmailBucketPersistence agentEmailBucketPersistence;

	@Reference
	protected AgentFAQPersistence agentFAQPersistence;

	@Reference
	protected AgentFAQCategoryPersistence agentFAQCategoryPersistence;

	@Reference
	protected AgentMarkCalendarPersistence agentMarkCalendarPersistence;

	@Reference
	protected AgentNotificationPersistence agentNotificationPersistence;

	@Reference
	protected AgentSalesToolsPersistence agentSalesToolsPersistence;

	@Reference
	protected AgentTokenPersistence agentTokenPersistence;

	@Reference
	protected AgentTokenLimiterPersistence agentTokenLimiterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}