/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.agencyportal.model.AgentMarkCalendar;
import com.mypage.agencyportal.service.AgentMarkCalendarLocalService;
import com.mypage.agencyportal.service.AgentMarkCalendarLocalServiceUtil;
import com.mypage.agencyportal.service.persistence.AgentCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentCategorySalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentEmailBucketPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQCategoryPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQPersistence;
import com.mypage.agencyportal.service.persistence.AgentMarkCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentNotificationPersistence;
import com.mypage.agencyportal.service.persistence.AgentSalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenLimiterPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the agent mark calendar local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.agencyportal.service.impl.AgentMarkCalendarLocalServiceImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see com.mypage.agencyportal.service.impl.AgentMarkCalendarLocalServiceImpl
 * @generated
 */
public abstract class AgentMarkCalendarLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AgentMarkCalendarLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AgentMarkCalendarLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AgentMarkCalendarLocalServiceUtil</code>.
	 */

	/**
	 * Adds the agent mark calendar to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentMarkCalendarLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentMarkCalendar the agent mark calendar
	 * @return the agent mark calendar that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AgentMarkCalendar addAgentMarkCalendar(
		AgentMarkCalendar agentMarkCalendar) {

		agentMarkCalendar.setNew(true);

		return agentMarkCalendarPersistence.update(agentMarkCalendar);
	}

	/**
	 * Creates a new agent mark calendar with the primary key. Does not add the agent mark calendar to the database.
	 *
	 * @param agentMarkCalendarId the primary key for the new agent mark calendar
	 * @return the new agent mark calendar
	 */
	@Override
	@Transactional(enabled = false)
	public AgentMarkCalendar createAgentMarkCalendar(long agentMarkCalendarId) {
		return agentMarkCalendarPersistence.create(agentMarkCalendarId);
	}

	/**
	 * Deletes the agent mark calendar with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentMarkCalendarLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentMarkCalendarId the primary key of the agent mark calendar
	 * @return the agent mark calendar that was removed
	 * @throws PortalException if a agent mark calendar with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AgentMarkCalendar deleteAgentMarkCalendar(long agentMarkCalendarId)
		throws PortalException {

		return agentMarkCalendarPersistence.remove(agentMarkCalendarId);
	}

	/**
	 * Deletes the agent mark calendar from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentMarkCalendarLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentMarkCalendar the agent mark calendar
	 * @return the agent mark calendar that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AgentMarkCalendar deleteAgentMarkCalendar(
		AgentMarkCalendar agentMarkCalendar) {

		return agentMarkCalendarPersistence.remove(agentMarkCalendar);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AgentMarkCalendar.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return agentMarkCalendarPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentMarkCalendarModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return agentMarkCalendarPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentMarkCalendarModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return agentMarkCalendarPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return agentMarkCalendarPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return agentMarkCalendarPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AgentMarkCalendar fetchAgentMarkCalendar(long agentMarkCalendarId) {
		return agentMarkCalendarPersistence.fetchByPrimaryKey(
			agentMarkCalendarId);
	}

	/**
	 * Returns the agent mark calendar with the primary key.
	 *
	 * @param agentMarkCalendarId the primary key of the agent mark calendar
	 * @return the agent mark calendar
	 * @throws PortalException if a agent mark calendar with the primary key could not be found
	 */
	@Override
	public AgentMarkCalendar getAgentMarkCalendar(long agentMarkCalendarId)
		throws PortalException {

		return agentMarkCalendarPersistence.findByPrimaryKey(
			agentMarkCalendarId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			agentMarkCalendarLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AgentMarkCalendar.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("agentMarkCalendarId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			agentMarkCalendarLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AgentMarkCalendar.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"agentMarkCalendarId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			agentMarkCalendarLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AgentMarkCalendar.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("agentMarkCalendarId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return agentMarkCalendarPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return agentMarkCalendarLocalService.deleteAgentMarkCalendar(
			(AgentMarkCalendar)persistedModel);
	}

	public BasePersistence<AgentMarkCalendar> getBasePersistence() {
		return agentMarkCalendarPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return agentMarkCalendarPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the agent mark calendars.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentMarkCalendarModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of agent mark calendars
	 * @param end the upper bound of the range of agent mark calendars (not inclusive)
	 * @return the range of agent mark calendars
	 */
	@Override
	public List<AgentMarkCalendar> getAgentMarkCalendars(int start, int end) {
		return agentMarkCalendarPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of agent mark calendars.
	 *
	 * @return the number of agent mark calendars
	 */
	@Override
	public int getAgentMarkCalendarsCount() {
		return agentMarkCalendarPersistence.countAll();
	}

	/**
	 * Updates the agent mark calendar in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentMarkCalendarLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentMarkCalendar the agent mark calendar
	 * @return the agent mark calendar that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AgentMarkCalendar updateAgentMarkCalendar(
		AgentMarkCalendar agentMarkCalendar) {

		return agentMarkCalendarPersistence.update(agentMarkCalendar);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AgentMarkCalendarLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		agentMarkCalendarLocalService = (AgentMarkCalendarLocalService)aopProxy;

		_setLocalServiceUtilService(agentMarkCalendarLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AgentMarkCalendarLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AgentMarkCalendar.class;
	}

	protected String getModelClassName() {
		return AgentMarkCalendar.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				agentMarkCalendarPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AgentMarkCalendarLocalService agentMarkCalendarLocalService) {

		try {
			Field field =
				AgentMarkCalendarLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, agentMarkCalendarLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AgentCalendarPersistence agentCalendarPersistence;

	@Reference
	protected AgentCategorySalesToolsPersistence
		agentCategorySalesToolsPersistence;

	@Reference
	protected AgentEmailBucketPersistence agentEmailBucketPersistence;

	@Reference
	protected AgentFAQPersistence agentFAQPersistence;

	@Reference
	protected AgentFAQCategoryPersistence agentFAQCategoryPersistence;

	protected AgentMarkCalendarLocalService agentMarkCalendarLocalService;

	@Reference
	protected AgentMarkCalendarPersistence agentMarkCalendarPersistence;

	@Reference
	protected AgentNotificationPersistence agentNotificationPersistence;

	@Reference
	protected AgentSalesToolsPersistence agentSalesToolsPersistence;

	@Reference
	protected AgentTokenPersistence agentTokenPersistence;

	@Reference
	protected AgentTokenLimiterPersistence agentTokenLimiterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}