/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.agencyportal.model.AgentCalendar;
import com.mypage.agencyportal.service.AgentCalendarService;
import com.mypage.agencyportal.service.AgentCalendarServiceUtil;
import com.mypage.agencyportal.service.persistence.AgentCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentCategorySalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentEmailBucketPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQCategoryPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQPersistence;
import com.mypage.agencyportal.service.persistence.AgentMarkCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentNotificationPersistence;
import com.mypage.agencyportal.service.persistence.AgentSalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenLimiterPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the agent calendar remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.agencyportal.service.impl.AgentCalendarServiceImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see com.mypage.agencyportal.service.impl.AgentCalendarServiceImpl
 * @generated
 */
public abstract class AgentCalendarServiceBaseImpl
	extends BaseServiceImpl
	implements AgentCalendarService, AopService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AgentCalendarService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AgentCalendarServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AgentCalendarService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		agentCalendarService = (AgentCalendarService)aopProxy;

		_setServiceUtilService(agentCalendarService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AgentCalendarService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AgentCalendar.class;
	}

	protected String getModelClassName() {
		return AgentCalendar.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = agentCalendarPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		AgentCalendarService agentCalendarService) {

		try {
			Field field = AgentCalendarServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, agentCalendarService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected com.mypage.agencyportal.service.AgentCalendarLocalService
		agentCalendarLocalService;

	protected AgentCalendarService agentCalendarService;

	@Reference
	protected AgentCalendarPersistence agentCalendarPersistence;

	@Reference
	protected AgentCategorySalesToolsPersistence
		agentCategorySalesToolsPersistence;

	@Reference
	protected AgentEmailBucketPersistence agentEmailBucketPersistence;

	@Reference
	protected AgentFAQPersistence agentFAQPersistence;

	@Reference
	protected AgentFAQCategoryPersistence agentFAQCategoryPersistence;

	@Reference
	protected AgentMarkCalendarPersistence agentMarkCalendarPersistence;

	@Reference
	protected AgentNotificationPersistence agentNotificationPersistence;

	@Reference
	protected AgentSalesToolsPersistence agentSalesToolsPersistence;

	@Reference
	protected AgentTokenPersistence agentTokenPersistence;

	@Reference
	protected AgentTokenLimiterPersistence agentTokenLimiterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}