/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.agencyportal.model.AgentTokenLimiter;
import com.mypage.agencyportal.service.AgentTokenLimiterLocalService;
import com.mypage.agencyportal.service.AgentTokenLimiterLocalServiceUtil;
import com.mypage.agencyportal.service.persistence.AgentCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentCategorySalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentEmailBucketPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQCategoryPersistence;
import com.mypage.agencyportal.service.persistence.AgentFAQPersistence;
import com.mypage.agencyportal.service.persistence.AgentMarkCalendarPersistence;
import com.mypage.agencyportal.service.persistence.AgentNotificationPersistence;
import com.mypage.agencyportal.service.persistence.AgentSalesToolsPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenLimiterPersistence;
import com.mypage.agencyportal.service.persistence.AgentTokenPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the agent token limiter local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.agencyportal.service.impl.AgentTokenLimiterLocalServiceImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see com.mypage.agencyportal.service.impl.AgentTokenLimiterLocalServiceImpl
 * @generated
 */
public abstract class AgentTokenLimiterLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AgentTokenLimiterLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AgentTokenLimiterLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AgentTokenLimiterLocalServiceUtil</code>.
	 */

	/**
	 * Adds the agent token limiter to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentTokenLimiterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentTokenLimiter the agent token limiter
	 * @return the agent token limiter that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AgentTokenLimiter addAgentTokenLimiter(
		AgentTokenLimiter agentTokenLimiter) {

		agentTokenLimiter.setNew(true);

		return agentTokenLimiterPersistence.update(agentTokenLimiter);
	}

	/**
	 * Creates a new agent token limiter with the primary key. Does not add the agent token limiter to the database.
	 *
	 * @param agentTokenLimiterId the primary key for the new agent token limiter
	 * @return the new agent token limiter
	 */
	@Override
	@Transactional(enabled = false)
	public AgentTokenLimiter createAgentTokenLimiter(long agentTokenLimiterId) {
		return agentTokenLimiterPersistence.create(agentTokenLimiterId);
	}

	/**
	 * Deletes the agent token limiter with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentTokenLimiterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentTokenLimiterId the primary key of the agent token limiter
	 * @return the agent token limiter that was removed
	 * @throws PortalException if a agent token limiter with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AgentTokenLimiter deleteAgentTokenLimiter(long agentTokenLimiterId)
		throws PortalException {

		return agentTokenLimiterPersistence.remove(agentTokenLimiterId);
	}

	/**
	 * Deletes the agent token limiter from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentTokenLimiterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentTokenLimiter the agent token limiter
	 * @return the agent token limiter that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AgentTokenLimiter deleteAgentTokenLimiter(
		AgentTokenLimiter agentTokenLimiter) {

		return agentTokenLimiterPersistence.remove(agentTokenLimiter);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AgentTokenLimiter.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return agentTokenLimiterPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentTokenLimiterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return agentTokenLimiterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentTokenLimiterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return agentTokenLimiterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return agentTokenLimiterPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return agentTokenLimiterPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AgentTokenLimiter fetchAgentTokenLimiter(long agentTokenLimiterId) {
		return agentTokenLimiterPersistence.fetchByPrimaryKey(
			agentTokenLimiterId);
	}

	/**
	 * Returns the agent token limiter with the primary key.
	 *
	 * @param agentTokenLimiterId the primary key of the agent token limiter
	 * @return the agent token limiter
	 * @throws PortalException if a agent token limiter with the primary key could not be found
	 */
	@Override
	public AgentTokenLimiter getAgentTokenLimiter(long agentTokenLimiterId)
		throws PortalException {

		return agentTokenLimiterPersistence.findByPrimaryKey(
			agentTokenLimiterId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			agentTokenLimiterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AgentTokenLimiter.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("agentTokenLimiterId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			agentTokenLimiterLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AgentTokenLimiter.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"agentTokenLimiterId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			agentTokenLimiterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AgentTokenLimiter.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("agentTokenLimiterId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return agentTokenLimiterPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return agentTokenLimiterLocalService.deleteAgentTokenLimiter(
			(AgentTokenLimiter)persistedModel);
	}

	public BasePersistence<AgentTokenLimiter> getBasePersistence() {
		return agentTokenLimiterPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return agentTokenLimiterPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the agent token limiters.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.agencyportal.model.impl.AgentTokenLimiterModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of agent token limiters
	 * @param end the upper bound of the range of agent token limiters (not inclusive)
	 * @return the range of agent token limiters
	 */
	@Override
	public List<AgentTokenLimiter> getAgentTokenLimiters(int start, int end) {
		return agentTokenLimiterPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of agent token limiters.
	 *
	 * @return the number of agent token limiters
	 */
	@Override
	public int getAgentTokenLimitersCount() {
		return agentTokenLimiterPersistence.countAll();
	}

	/**
	 * Updates the agent token limiter in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AgentTokenLimiterLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param agentTokenLimiter the agent token limiter
	 * @return the agent token limiter that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AgentTokenLimiter updateAgentTokenLimiter(
		AgentTokenLimiter agentTokenLimiter) {

		return agentTokenLimiterPersistence.update(agentTokenLimiter);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AgentTokenLimiterLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		agentTokenLimiterLocalService = (AgentTokenLimiterLocalService)aopProxy;

		_setLocalServiceUtilService(agentTokenLimiterLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AgentTokenLimiterLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AgentTokenLimiter.class;
	}

	protected String getModelClassName() {
		return AgentTokenLimiter.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				agentTokenLimiterPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AgentTokenLimiterLocalService agentTokenLimiterLocalService) {

		try {
			Field field =
				AgentTokenLimiterLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, agentTokenLimiterLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AgentCalendarPersistence agentCalendarPersistence;

	@Reference
	protected AgentCategorySalesToolsPersistence
		agentCategorySalesToolsPersistence;

	@Reference
	protected AgentEmailBucketPersistence agentEmailBucketPersistence;

	@Reference
	protected AgentFAQPersistence agentFAQPersistence;

	@Reference
	protected AgentFAQCategoryPersistence agentFAQCategoryPersistence;

	@Reference
	protected AgentMarkCalendarPersistence agentMarkCalendarPersistence;

	@Reference
	protected AgentNotificationPersistence agentNotificationPersistence;

	@Reference
	protected AgentSalesToolsPersistence agentSalesToolsPersistence;

	@Reference
	protected AgentTokenPersistence agentTokenPersistence;

	protected AgentTokenLimiterLocalService agentTokenLimiterLocalService;

	@Reference
	protected AgentTokenLimiterPersistence agentTokenLimiterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}