dependencies {
	compileOnly group: "com.liferay.portal", name: "release.dxp.api"
    compileOnly group: "javax.ws.rs", name: "javax.ws.rs-api", version: "2.1.1"
    compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
    compileOnly group: "org.osgi", name: "org.osgi.service.jaxrs", version: "1.0.0"
	cssBuilder group: "com.liferay", name: "com.liferay.css.builder", version: "3.1.0"
	compileOnly project(":modules:MypageAdminProduct:MypageAdminProduct-api")
    compileOnly project(":modules:MypageAdminProduct:MypageAdminProduct-service")
    compileOnly project(":modules:aii-esppk-admin:aii-esppk-admin-api")
    compileOnly project(":modules:aii-esppk-admin:aii-esppk-admin-service")

    compileInclude group: 'com.googlecode.owasp-java-html-sanitizer', name: 'owasp-java-html-sanitizer', version: '20220608.1'

    // https://mvnrepository.com/artifact/io.jsonwebtoken
    compileOnly group: "io.jsonwebtoken", name: "jjwt-api", version: "0.11.2"
    compileInclude group: "io.jsonwebtoken", name: "jjwt-impl", version: "0.11.2"
    compileInclude group: "io.jsonwebtoken", name: "jjwt-gson", version: "0.11.2"

    // https://mvnrepository.com/artifact/at.favre.lib/bcrypt
    compileInclude group: "at.favre.lib", name: "bcrypt", version: "0.10.2"
}

