/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.user.model.MypageUserTimeline;
import com.mypage.user.model.MypageUserTimelineModel;
import com.mypage.user.model.MypageUserTimelineSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MypageUserTimeline service. Represents a row in the &quot;MypageUserTimeline&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MypageUserTimelineModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MypageUserTimelineImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageUserTimelineImpl
 * @generated
 */
@JSON(strict = true)
public class MypageUserTimelineModelImpl
	extends BaseModelImpl<MypageUserTimeline>
	implements MypageUserTimelineModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mypage user timeline model instance should use the <code>MypageUserTimeline</code> interface instead.
	 */
	public static final String TABLE_NAME = "MypageUserTimeline";

	public static final Object[][] TABLE_COLUMNS = {
		{"mypageUserTimelineId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"mypageUserId", Types.BIGINT},
		{"imgUploadTimelineEntryId", Types.BIGINT},
		{"imgUploadTimelineUrl", Types.VARCHAR},
		{"videoUploadTimelineUrl", Types.VARCHAR}, {"text_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mypageUserTimelineId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("mypageUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("imgUploadTimelineEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("imgUploadTimelineUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("videoUploadTimelineUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("text_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MypageUserTimeline (mypageUserTimelineId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,mypageUserId LONG,imgUploadTimelineEntryId LONG,imgUploadTimelineUrl VARCHAR(75) null,videoUploadTimelineUrl VARCHAR(75) null,text_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MypageUserTimeline";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mypageUserTimeline.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MypageUserTimeline.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEUSERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MypageUserTimeline toModel(MypageUserTimelineSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MypageUserTimeline model = new MypageUserTimelineImpl();

		model.setMypageUserTimelineId(soapModel.getMypageUserTimelineId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMypageUserId(soapModel.getMypageUserId());
		model.setImgUploadTimelineEntryId(
			soapModel.getImgUploadTimelineEntryId());
		model.setImgUploadTimelineUrl(soapModel.getImgUploadTimelineUrl());
		model.setVideoUploadTimelineUrl(soapModel.getVideoUploadTimelineUrl());
		model.setText(soapModel.getText());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MypageUserTimeline> toModels(
		MypageUserTimelineSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<MypageUserTimeline> models = new ArrayList<MypageUserTimeline>(
			soapModels.length);

		for (MypageUserTimelineSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MypageUserTimelineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mypageUserTimelineId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMypageUserTimelineId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mypageUserTimelineId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MypageUserTimeline.class;
	}

	@Override
	public String getModelClassName() {
		return MypageUserTimeline.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MypageUserTimeline, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MypageUserTimeline, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserTimeline, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MypageUserTimeline)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MypageUserTimeline, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MypageUserTimeline, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MypageUserTimeline)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MypageUserTimeline, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MypageUserTimeline, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MypageUserTimeline, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MypageUserTimeline, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MypageUserTimeline, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<MypageUserTimeline, Object>>();
		Map<String, BiConsumer<MypageUserTimeline, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<MypageUserTimeline, ?>>();

		attributeGetterFunctions.put(
			"mypageUserTimelineId",
			MypageUserTimeline::getMypageUserTimelineId);
		attributeSetterBiConsumers.put(
			"mypageUserTimelineId",
			(BiConsumer<MypageUserTimeline, Long>)
				MypageUserTimeline::setMypageUserTimelineId);
		attributeGetterFunctions.put("groupId", MypageUserTimeline::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MypageUserTimeline, Long>)
				MypageUserTimeline::setGroupId);
		attributeGetterFunctions.put(
			"companyId", MypageUserTimeline::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MypageUserTimeline, Long>)
				MypageUserTimeline::setCompanyId);
		attributeGetterFunctions.put("userId", MypageUserTimeline::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MypageUserTimeline, Long>)
				MypageUserTimeline::setUserId);
		attributeGetterFunctions.put(
			"userName", MypageUserTimeline::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MypageUserTimeline, String>)
				MypageUserTimeline::setUserName);
		attributeGetterFunctions.put(
			"createDate", MypageUserTimeline::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MypageUserTimeline, Date>)
				MypageUserTimeline::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MypageUserTimeline::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MypageUserTimeline, Date>)
				MypageUserTimeline::setModifiedDate);
		attributeGetterFunctions.put(
			"mypageUserId", MypageUserTimeline::getMypageUserId);
		attributeSetterBiConsumers.put(
			"mypageUserId",
			(BiConsumer<MypageUserTimeline, Long>)
				MypageUserTimeline::setMypageUserId);
		attributeGetterFunctions.put(
			"imgUploadTimelineEntryId",
			MypageUserTimeline::getImgUploadTimelineEntryId);
		attributeSetterBiConsumers.put(
			"imgUploadTimelineEntryId",
			(BiConsumer<MypageUserTimeline, Long>)
				MypageUserTimeline::setImgUploadTimelineEntryId);
		attributeGetterFunctions.put(
			"imgUploadTimelineUrl",
			MypageUserTimeline::getImgUploadTimelineUrl);
		attributeSetterBiConsumers.put(
			"imgUploadTimelineUrl",
			(BiConsumer<MypageUserTimeline, String>)
				MypageUserTimeline::setImgUploadTimelineUrl);
		attributeGetterFunctions.put(
			"videoUploadTimelineUrl",
			MypageUserTimeline::getVideoUploadTimelineUrl);
		attributeSetterBiConsumers.put(
			"videoUploadTimelineUrl",
			(BiConsumer<MypageUserTimeline, String>)
				MypageUserTimeline::setVideoUploadTimelineUrl);
		attributeGetterFunctions.put("text", MypageUserTimeline::getText);
		attributeSetterBiConsumers.put(
			"text",
			(BiConsumer<MypageUserTimeline, String>)
				MypageUserTimeline::setText);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMypageUserTimelineId() {
		return _mypageUserTimelineId;
	}

	@Override
	public void setMypageUserTimelineId(long mypageUserTimelineId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserTimelineId = mypageUserTimelineId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getMypageUserId() {
		return _mypageUserId;
	}

	@Override
	public void setMypageUserId(long mypageUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserId = mypageUserId;
	}

	@Override
	public String getMypageUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getMypageUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setMypageUserUuid(String mypageUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMypageUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("mypageUserId"));
	}

	@JSON
	@Override
	public long getImgUploadTimelineEntryId() {
		return _imgUploadTimelineEntryId;
	}

	@Override
	public void setImgUploadTimelineEntryId(long imgUploadTimelineEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imgUploadTimelineEntryId = imgUploadTimelineEntryId;
	}

	@JSON
	@Override
	public String getImgUploadTimelineUrl() {
		if (_imgUploadTimelineUrl == null) {
			return "";
		}
		else {
			return _imgUploadTimelineUrl;
		}
	}

	@Override
	public void setImgUploadTimelineUrl(String imgUploadTimelineUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imgUploadTimelineUrl = imgUploadTimelineUrl;
	}

	@JSON
	@Override
	public String getVideoUploadTimelineUrl() {
		if (_videoUploadTimelineUrl == null) {
			return "";
		}
		else {
			return _videoUploadTimelineUrl;
		}
	}

	@Override
	public void setVideoUploadTimelineUrl(String videoUploadTimelineUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_videoUploadTimelineUrl = videoUploadTimelineUrl;
	}

	@JSON
	@Override
	public String getText() {
		if (_text == null) {
			return "";
		}
		else {
			return _text;
		}
	}

	@Override
	public void setText(String text) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_text = text;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MypageUserTimeline.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MypageUserTimeline toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MypageUserTimeline>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MypageUserTimelineImpl mypageUserTimelineImpl =
			new MypageUserTimelineImpl();

		mypageUserTimelineImpl.setMypageUserTimelineId(
			getMypageUserTimelineId());
		mypageUserTimelineImpl.setGroupId(getGroupId());
		mypageUserTimelineImpl.setCompanyId(getCompanyId());
		mypageUserTimelineImpl.setUserId(getUserId());
		mypageUserTimelineImpl.setUserName(getUserName());
		mypageUserTimelineImpl.setCreateDate(getCreateDate());
		mypageUserTimelineImpl.setModifiedDate(getModifiedDate());
		mypageUserTimelineImpl.setMypageUserId(getMypageUserId());
		mypageUserTimelineImpl.setImgUploadTimelineEntryId(
			getImgUploadTimelineEntryId());
		mypageUserTimelineImpl.setImgUploadTimelineUrl(
			getImgUploadTimelineUrl());
		mypageUserTimelineImpl.setVideoUploadTimelineUrl(
			getVideoUploadTimelineUrl());
		mypageUserTimelineImpl.setText(getText());

		mypageUserTimelineImpl.resetOriginalValues();

		return mypageUserTimelineImpl;
	}

	@Override
	public int compareTo(MypageUserTimeline mypageUserTimeline) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), mypageUserTimeline.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MypageUserTimeline)) {
			return false;
		}

		MypageUserTimeline mypageUserTimeline = (MypageUserTimeline)object;

		long primaryKey = mypageUserTimeline.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MypageUserTimeline> toCacheModel() {
		MypageUserTimelineCacheModel mypageUserTimelineCacheModel =
			new MypageUserTimelineCacheModel();

		mypageUserTimelineCacheModel.mypageUserTimelineId =
			getMypageUserTimelineId();

		mypageUserTimelineCacheModel.groupId = getGroupId();

		mypageUserTimelineCacheModel.companyId = getCompanyId();

		mypageUserTimelineCacheModel.userId = getUserId();

		mypageUserTimelineCacheModel.userName = getUserName();

		String userName = mypageUserTimelineCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mypageUserTimelineCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mypageUserTimelineCacheModel.createDate = createDate.getTime();
		}
		else {
			mypageUserTimelineCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mypageUserTimelineCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mypageUserTimelineCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mypageUserTimelineCacheModel.mypageUserId = getMypageUserId();

		mypageUserTimelineCacheModel.imgUploadTimelineEntryId =
			getImgUploadTimelineEntryId();

		mypageUserTimelineCacheModel.imgUploadTimelineUrl =
			getImgUploadTimelineUrl();

		String imgUploadTimelineUrl =
			mypageUserTimelineCacheModel.imgUploadTimelineUrl;

		if ((imgUploadTimelineUrl != null) &&
			(imgUploadTimelineUrl.length() == 0)) {

			mypageUserTimelineCacheModel.imgUploadTimelineUrl = null;
		}

		mypageUserTimelineCacheModel.videoUploadTimelineUrl =
			getVideoUploadTimelineUrl();

		String videoUploadTimelineUrl =
			mypageUserTimelineCacheModel.videoUploadTimelineUrl;

		if ((videoUploadTimelineUrl != null) &&
			(videoUploadTimelineUrl.length() == 0)) {

			mypageUserTimelineCacheModel.videoUploadTimelineUrl = null;
		}

		mypageUserTimelineCacheModel.text = getText();

		String text = mypageUserTimelineCacheModel.text;

		if ((text != null) && (text.length() == 0)) {
			mypageUserTimelineCacheModel.text = null;
		}

		return mypageUserTimelineCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MypageUserTimeline, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MypageUserTimeline, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserTimeline, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MypageUserTimeline)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MypageUserTimeline, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MypageUserTimeline, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserTimeline, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MypageUserTimeline)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MypageUserTimeline>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MypageUserTimeline.class, ModelWrapper.class);

	}

	private long _mypageUserTimelineId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _mypageUserId;
	private long _imgUploadTimelineEntryId;
	private String _imgUploadTimelineUrl;
	private String _videoUploadTimelineUrl;
	private String _text;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MypageUserTimeline, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MypageUserTimeline)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"mypageUserTimelineId", _mypageUserTimelineId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("mypageUserId", _mypageUserId);
		_columnOriginalValues.put(
			"imgUploadTimelineEntryId", _imgUploadTimelineEntryId);
		_columnOriginalValues.put(
			"imgUploadTimelineUrl", _imgUploadTimelineUrl);
		_columnOriginalValues.put(
			"videoUploadTimelineUrl", _videoUploadTimelineUrl);
		_columnOriginalValues.put("text_", _text);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("text_", "text");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mypageUserTimelineId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("mypageUserId", 128L);

		columnBitmasks.put("imgUploadTimelineEntryId", 256L);

		columnBitmasks.put("imgUploadTimelineUrl", 512L);

		columnBitmasks.put("videoUploadTimelineUrl", 1024L);

		columnBitmasks.put("text_", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MypageUserTimeline _escapedModel;

}