/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.user.model.MypageGroupUser;
import com.mypage.user.model.MypageGroupUserModel;
import com.mypage.user.model.MypageGroupUserSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MypageGroupUser service. Represents a row in the &quot;MypageGroupUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MypageGroupUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MypageGroupUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageGroupUserImpl
 * @generated
 */
@JSON(strict = true)
public class MypageGroupUserModelImpl
	extends BaseModelImpl<MypageGroupUser> implements MypageGroupUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mypage group user model instance should use the <code>MypageGroupUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "MypageGroupUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"mypageGroupUserId", Types.BIGINT}, {"mypageGroupId", Types.BIGINT},
		{"mypageUserId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mypageGroupUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mypageGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mypageUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MypageGroupUser (mypageGroupUserId LONG not null primary key,mypageGroupId LONG,mypageUserId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table MypageGroupUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mypageGroupUser.mypageGroupUserId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MypageGroupUser.mypageGroupUserId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEGROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEUSERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEGROUPUSERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MypageGroupUser toModel(MypageGroupUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MypageGroupUser model = new MypageGroupUserImpl();

		model.setMypageGroupUserId(soapModel.getMypageGroupUserId());
		model.setMypageGroupId(soapModel.getMypageGroupId());
		model.setMypageUserId(soapModel.getMypageUserId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MypageGroupUser> toModels(
		MypageGroupUserSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<MypageGroupUser> models = new ArrayList<MypageGroupUser>(
			soapModels.length);

		for (MypageGroupUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MypageGroupUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mypageGroupUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMypageGroupUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mypageGroupUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MypageGroupUser.class;
	}

	@Override
	public String getModelClassName() {
		return MypageGroupUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MypageGroupUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MypageGroupUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageGroupUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MypageGroupUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MypageGroupUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MypageGroupUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MypageGroupUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MypageGroupUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MypageGroupUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MypageGroupUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MypageGroupUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MypageGroupUser, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<MypageGroupUser, Object>>();
		Map<String, BiConsumer<MypageGroupUser, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MypageGroupUser, ?>>();

		attributeGetterFunctions.put(
			"mypageGroupUserId", MypageGroupUser::getMypageGroupUserId);
		attributeSetterBiConsumers.put(
			"mypageGroupUserId",
			(BiConsumer<MypageGroupUser, Long>)
				MypageGroupUser::setMypageGroupUserId);
		attributeGetterFunctions.put(
			"mypageGroupId", MypageGroupUser::getMypageGroupId);
		attributeSetterBiConsumers.put(
			"mypageGroupId",
			(BiConsumer<MypageGroupUser, Long>)
				MypageGroupUser::setMypageGroupId);
		attributeGetterFunctions.put(
			"mypageUserId", MypageGroupUser::getMypageUserId);
		attributeSetterBiConsumers.put(
			"mypageUserId",
			(BiConsumer<MypageGroupUser, Long>)
				MypageGroupUser::setMypageUserId);
		attributeGetterFunctions.put("groupId", MypageGroupUser::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MypageGroupUser, Long>)MypageGroupUser::setGroupId);
		attributeGetterFunctions.put(
			"companyId", MypageGroupUser::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MypageGroupUser, Long>)MypageGroupUser::setCompanyId);
		attributeGetterFunctions.put("userId", MypageGroupUser::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MypageGroupUser, Long>)MypageGroupUser::setUserId);
		attributeGetterFunctions.put("userName", MypageGroupUser::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MypageGroupUser, String>)MypageGroupUser::setUserName);
		attributeGetterFunctions.put(
			"createDate", MypageGroupUser::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MypageGroupUser, Date>)MypageGroupUser::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MypageGroupUser::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MypageGroupUser, Date>)
				MypageGroupUser::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMypageGroupUserId() {
		return _mypageGroupUserId;
	}

	@Override
	public void setMypageGroupUserId(long mypageGroupUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageGroupUserId = mypageGroupUserId;
	}

	@Override
	public String getMypageGroupUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(
				getMypageGroupUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setMypageGroupUserUuid(String mypageGroupUserUuid) {
	}

	@JSON
	@Override
	public long getMypageGroupId() {
		return _mypageGroupId;
	}

	@Override
	public void setMypageGroupId(long mypageGroupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageGroupId = mypageGroupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMypageGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("mypageGroupId"));
	}

	@JSON
	@Override
	public long getMypageUserId() {
		return _mypageUserId;
	}

	@Override
	public void setMypageUserId(long mypageUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserId = mypageUserId;
	}

	@Override
	public String getMypageUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getMypageUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setMypageUserUuid(String mypageUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMypageUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("mypageUserId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MypageGroupUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MypageGroupUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MypageGroupUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MypageGroupUserImpl mypageGroupUserImpl = new MypageGroupUserImpl();

		mypageGroupUserImpl.setMypageGroupUserId(getMypageGroupUserId());
		mypageGroupUserImpl.setMypageGroupId(getMypageGroupId());
		mypageGroupUserImpl.setMypageUserId(getMypageUserId());
		mypageGroupUserImpl.setGroupId(getGroupId());
		mypageGroupUserImpl.setCompanyId(getCompanyId());
		mypageGroupUserImpl.setUserId(getUserId());
		mypageGroupUserImpl.setUserName(getUserName());
		mypageGroupUserImpl.setCreateDate(getCreateDate());
		mypageGroupUserImpl.setModifiedDate(getModifiedDate());

		mypageGroupUserImpl.resetOriginalValues();

		return mypageGroupUserImpl;
	}

	@Override
	public int compareTo(MypageGroupUser mypageGroupUser) {
		long primaryKey = mypageGroupUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MypageGroupUser)) {
			return false;
		}

		MypageGroupUser mypageGroupUser = (MypageGroupUser)object;

		long primaryKey = mypageGroupUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MypageGroupUser> toCacheModel() {
		MypageGroupUserCacheModel mypageGroupUserCacheModel =
			new MypageGroupUserCacheModel();

		mypageGroupUserCacheModel.mypageGroupUserId = getMypageGroupUserId();

		mypageGroupUserCacheModel.mypageGroupId = getMypageGroupId();

		mypageGroupUserCacheModel.mypageUserId = getMypageUserId();

		mypageGroupUserCacheModel.groupId = getGroupId();

		mypageGroupUserCacheModel.companyId = getCompanyId();

		mypageGroupUserCacheModel.userId = getUserId();

		mypageGroupUserCacheModel.userName = getUserName();

		String userName = mypageGroupUserCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mypageGroupUserCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mypageGroupUserCacheModel.createDate = createDate.getTime();
		}
		else {
			mypageGroupUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mypageGroupUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mypageGroupUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return mypageGroupUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MypageGroupUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MypageGroupUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageGroupUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MypageGroupUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MypageGroupUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MypageGroupUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageGroupUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MypageGroupUser)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MypageGroupUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MypageGroupUser.class, ModelWrapper.class);

	}

	private long _mypageGroupUserId;
	private long _mypageGroupId;
	private long _mypageUserId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<MypageGroupUser, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MypageGroupUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mypageGroupUserId", _mypageGroupUserId);
		_columnOriginalValues.put("mypageGroupId", _mypageGroupId);
		_columnOriginalValues.put("mypageUserId", _mypageUserId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mypageGroupUserId", 1L);

		columnBitmasks.put("mypageGroupId", 2L);

		columnBitmasks.put("mypageUserId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MypageGroupUser _escapedModel;

}