/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.user.model.MypageUserRole;
import com.mypage.user.model.MypageUserRoleModel;
import com.mypage.user.model.MypageUserRoleSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MypageUserRole service. Represents a row in the &quot;MypageUserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MypageUserRoleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MypageUserRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageUserRoleImpl
 * @generated
 */
@JSON(strict = true)
public class MypageUserRoleModelImpl
	extends BaseModelImpl<MypageUserRole> implements MypageUserRoleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mypage user role model instance should use the <code>MypageUserRole</code> interface instead.
	 */
	public static final String TABLE_NAME = "MypageUserRole";

	public static final Object[][] TABLE_COLUMNS = {
		{"mypageUserRoleId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mypageUserRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MypageUserRole (mypageUserRoleId LONG not null primary key,name VARCHAR(75) null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table MypageUserRole";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mypageUserRole.mypageUserRoleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MypageUserRole.mypageUserRoleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEUSERROLEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MypageUserRole toModel(MypageUserRoleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MypageUserRole model = new MypageUserRoleImpl();

		model.setMypageUserRoleId(soapModel.getMypageUserRoleId());
		model.setName(soapModel.getName());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MypageUserRole> toModels(
		MypageUserRoleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<MypageUserRole> models = new ArrayList<MypageUserRole>(
			soapModels.length);

		for (MypageUserRoleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MypageUserRoleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mypageUserRoleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMypageUserRoleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mypageUserRoleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MypageUserRole.class;
	}

	@Override
	public String getModelClassName() {
		return MypageUserRole.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MypageUserRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MypageUserRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserRole, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MypageUserRole)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MypageUserRole, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MypageUserRole, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MypageUserRole)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MypageUserRole, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MypageUserRole, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MypageUserRole, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MypageUserRole, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MypageUserRole, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MypageUserRole, Object>>();
		Map<String, BiConsumer<MypageUserRole, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MypageUserRole, ?>>();

		attributeGetterFunctions.put(
			"mypageUserRoleId", MypageUserRole::getMypageUserRoleId);
		attributeSetterBiConsumers.put(
			"mypageUserRoleId",
			(BiConsumer<MypageUserRole, Long>)
				MypageUserRole::setMypageUserRoleId);
		attributeGetterFunctions.put("name", MypageUserRole::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<MypageUserRole, String>)MypageUserRole::setName);
		attributeGetterFunctions.put("active", MypageUserRole::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<MypageUserRole, Integer>)MypageUserRole::setActive);
		attributeGetterFunctions.put("groupId", MypageUserRole::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MypageUserRole, Long>)MypageUserRole::setGroupId);
		attributeGetterFunctions.put("companyId", MypageUserRole::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MypageUserRole, Long>)MypageUserRole::setCompanyId);
		attributeGetterFunctions.put("userId", MypageUserRole::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MypageUserRole, Long>)MypageUserRole::setUserId);
		attributeGetterFunctions.put("userName", MypageUserRole::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MypageUserRole, String>)MypageUserRole::setUserName);
		attributeGetterFunctions.put(
			"createDate", MypageUserRole::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MypageUserRole, Date>)MypageUserRole::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MypageUserRole::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MypageUserRole, Date>)MypageUserRole::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMypageUserRoleId() {
		return _mypageUserRoleId;
	}

	@Override
	public void setMypageUserRoleId(long mypageUserRoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserRoleId = mypageUserRoleId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MypageUserRole.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MypageUserRole toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MypageUserRole>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MypageUserRoleImpl mypageUserRoleImpl = new MypageUserRoleImpl();

		mypageUserRoleImpl.setMypageUserRoleId(getMypageUserRoleId());
		mypageUserRoleImpl.setName(getName());
		mypageUserRoleImpl.setActive(getActive());
		mypageUserRoleImpl.setGroupId(getGroupId());
		mypageUserRoleImpl.setCompanyId(getCompanyId());
		mypageUserRoleImpl.setUserId(getUserId());
		mypageUserRoleImpl.setUserName(getUserName());
		mypageUserRoleImpl.setCreateDate(getCreateDate());
		mypageUserRoleImpl.setModifiedDate(getModifiedDate());

		mypageUserRoleImpl.resetOriginalValues();

		return mypageUserRoleImpl;
	}

	@Override
	public int compareTo(MypageUserRole mypageUserRole) {
		long primaryKey = mypageUserRole.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MypageUserRole)) {
			return false;
		}

		MypageUserRole mypageUserRole = (MypageUserRole)object;

		long primaryKey = mypageUserRole.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MypageUserRole> toCacheModel() {
		MypageUserRoleCacheModel mypageUserRoleCacheModel =
			new MypageUserRoleCacheModel();

		mypageUserRoleCacheModel.mypageUserRoleId = getMypageUserRoleId();

		mypageUserRoleCacheModel.name = getName();

		String name = mypageUserRoleCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			mypageUserRoleCacheModel.name = null;
		}

		mypageUserRoleCacheModel.active = getActive();

		mypageUserRoleCacheModel.groupId = getGroupId();

		mypageUserRoleCacheModel.companyId = getCompanyId();

		mypageUserRoleCacheModel.userId = getUserId();

		mypageUserRoleCacheModel.userName = getUserName();

		String userName = mypageUserRoleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mypageUserRoleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mypageUserRoleCacheModel.createDate = createDate.getTime();
		}
		else {
			mypageUserRoleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mypageUserRoleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mypageUserRoleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return mypageUserRoleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MypageUserRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MypageUserRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MypageUserRole)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MypageUserRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MypageUserRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MypageUserRole)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MypageUserRole>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MypageUserRole.class, ModelWrapper.class);

	}

	private long _mypageUserRoleId;
	private String _name;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MypageUserRole, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MypageUserRole)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mypageUserRoleId", _mypageUserRoleId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mypageUserRoleId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("active_", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MypageUserRole _escapedModel;

}