/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.user.model.MypageUserGracePeriod;
import com.mypage.user.model.MypageUserGracePeriodModel;
import com.mypage.user.model.MypageUserGracePeriodSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MypageUserGracePeriod service. Represents a row in the &quot;MypageUserGracePeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MypageUserGracePeriodModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MypageUserGracePeriodImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MypageUserGracePeriodImpl
 * @generated
 */
@JSON(strict = true)
public class MypageUserGracePeriodModelImpl
	extends BaseModelImpl<MypageUserGracePeriod>
	implements MypageUserGracePeriodModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mypage user grace period model instance should use the <code>MypageUserGracePeriod</code> interface instead.
	 */
	public static final String TABLE_NAME = "MypageUserGracePeriod";

	public static final Object[][] TABLE_COLUMNS = {
		{"mypageUserGracePeriodId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"mypageUserId", Types.BIGINT},
		{"code_", Types.VARCHAR}, {"value", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mypageUserGracePeriodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("mypageUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MypageUserGracePeriod (mypageUserGracePeriodId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,mypageUserId LONG,code_ VARCHAR(75) null,value INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table MypageUserGracePeriod";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mypageUserGracePeriod.mypageUserGracePeriodId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MypageUserGracePeriod.mypageUserGracePeriodId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEUSERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEUSERGRACEPERIODID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MypageUserGracePeriod toModel(
		MypageUserGracePeriodSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		MypageUserGracePeriod model = new MypageUserGracePeriodImpl();

		model.setMypageUserGracePeriodId(
			soapModel.getMypageUserGracePeriodId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMypageUserId(soapModel.getMypageUserId());
		model.setCode(soapModel.getCode());
		model.setValue(soapModel.getValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MypageUserGracePeriod> toModels(
		MypageUserGracePeriodSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<MypageUserGracePeriod> models =
			new ArrayList<MypageUserGracePeriod>(soapModels.length);

		for (MypageUserGracePeriodSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MypageUserGracePeriodModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mypageUserGracePeriodId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMypageUserGracePeriodId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mypageUserGracePeriodId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MypageUserGracePeriod.class;
	}

	@Override
	public String getModelClassName() {
		return MypageUserGracePeriod.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MypageUserGracePeriod, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MypageUserGracePeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserGracePeriod, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MypageUserGracePeriod)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MypageUserGracePeriod, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MypageUserGracePeriod, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MypageUserGracePeriod)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MypageUserGracePeriod, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MypageUserGracePeriod, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MypageUserGracePeriod, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MypageUserGracePeriod, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MypageUserGracePeriod, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<MypageUserGracePeriod, Object>>();
		Map<String, BiConsumer<MypageUserGracePeriod, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<MypageUserGracePeriod, ?>>();

		attributeGetterFunctions.put(
			"mypageUserGracePeriodId",
			MypageUserGracePeriod::getMypageUserGracePeriodId);
		attributeSetterBiConsumers.put(
			"mypageUserGracePeriodId",
			(BiConsumer<MypageUserGracePeriod, Long>)
				MypageUserGracePeriod::setMypageUserGracePeriodId);
		attributeGetterFunctions.put(
			"groupId", MypageUserGracePeriod::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MypageUserGracePeriod, Long>)
				MypageUserGracePeriod::setGroupId);
		attributeGetterFunctions.put(
			"companyId", MypageUserGracePeriod::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MypageUserGracePeriod, Long>)
				MypageUserGracePeriod::setCompanyId);
		attributeGetterFunctions.put(
			"userId", MypageUserGracePeriod::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MypageUserGracePeriod, Long>)
				MypageUserGracePeriod::setUserId);
		attributeGetterFunctions.put(
			"userName", MypageUserGracePeriod::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MypageUserGracePeriod, String>)
				MypageUserGracePeriod::setUserName);
		attributeGetterFunctions.put(
			"createDate", MypageUserGracePeriod::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MypageUserGracePeriod, Date>)
				MypageUserGracePeriod::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MypageUserGracePeriod::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MypageUserGracePeriod, Date>)
				MypageUserGracePeriod::setModifiedDate);
		attributeGetterFunctions.put(
			"mypageUserId", MypageUserGracePeriod::getMypageUserId);
		attributeSetterBiConsumers.put(
			"mypageUserId",
			(BiConsumer<MypageUserGracePeriod, Long>)
				MypageUserGracePeriod::setMypageUserId);
		attributeGetterFunctions.put("code", MypageUserGracePeriod::getCode);
		attributeSetterBiConsumers.put(
			"code",
			(BiConsumer<MypageUserGracePeriod, String>)
				MypageUserGracePeriod::setCode);
		attributeGetterFunctions.put("value", MypageUserGracePeriod::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<MypageUserGracePeriod, Integer>)
				MypageUserGracePeriod::setValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMypageUserGracePeriodId() {
		return _mypageUserGracePeriodId;
	}

	@Override
	public void setMypageUserGracePeriodId(long mypageUserGracePeriodId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserGracePeriodId = mypageUserGracePeriodId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getMypageUserId() {
		return _mypageUserId;
	}

	@Override
	public void setMypageUserId(long mypageUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserId = mypageUserId;
	}

	@Override
	public String getMypageUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getMypageUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setMypageUserUuid(String mypageUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMypageUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("mypageUserId"));
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	@JSON
	@Override
	public int getValue() {
		return _value;
	}

	@Override
	public void setValue(int value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MypageUserGracePeriod.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MypageUserGracePeriod toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MypageUserGracePeriod>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MypageUserGracePeriodImpl mypageUserGracePeriodImpl =
			new MypageUserGracePeriodImpl();

		mypageUserGracePeriodImpl.setMypageUserGracePeriodId(
			getMypageUserGracePeriodId());
		mypageUserGracePeriodImpl.setGroupId(getGroupId());
		mypageUserGracePeriodImpl.setCompanyId(getCompanyId());
		mypageUserGracePeriodImpl.setUserId(getUserId());
		mypageUserGracePeriodImpl.setUserName(getUserName());
		mypageUserGracePeriodImpl.setCreateDate(getCreateDate());
		mypageUserGracePeriodImpl.setModifiedDate(getModifiedDate());
		mypageUserGracePeriodImpl.setMypageUserId(getMypageUserId());
		mypageUserGracePeriodImpl.setCode(getCode());
		mypageUserGracePeriodImpl.setValue(getValue());

		mypageUserGracePeriodImpl.resetOriginalValues();

		return mypageUserGracePeriodImpl;
	}

	@Override
	public int compareTo(MypageUserGracePeriod mypageUserGracePeriod) {
		long primaryKey = mypageUserGracePeriod.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MypageUserGracePeriod)) {
			return false;
		}

		MypageUserGracePeriod mypageUserGracePeriod =
			(MypageUserGracePeriod)object;

		long primaryKey = mypageUserGracePeriod.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MypageUserGracePeriod> toCacheModel() {
		MypageUserGracePeriodCacheModel mypageUserGracePeriodCacheModel =
			new MypageUserGracePeriodCacheModel();

		mypageUserGracePeriodCacheModel.mypageUserGracePeriodId =
			getMypageUserGracePeriodId();

		mypageUserGracePeriodCacheModel.groupId = getGroupId();

		mypageUserGracePeriodCacheModel.companyId = getCompanyId();

		mypageUserGracePeriodCacheModel.userId = getUserId();

		mypageUserGracePeriodCacheModel.userName = getUserName();

		String userName = mypageUserGracePeriodCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mypageUserGracePeriodCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mypageUserGracePeriodCacheModel.createDate = createDate.getTime();
		}
		else {
			mypageUserGracePeriodCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mypageUserGracePeriodCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			mypageUserGracePeriodCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mypageUserGracePeriodCacheModel.mypageUserId = getMypageUserId();

		mypageUserGracePeriodCacheModel.code = getCode();

		String code = mypageUserGracePeriodCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			mypageUserGracePeriodCacheModel.code = null;
		}

		mypageUserGracePeriodCacheModel.value = getValue();

		return mypageUserGracePeriodCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MypageUserGracePeriod, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MypageUserGracePeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserGracePeriod, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MypageUserGracePeriod)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MypageUserGracePeriod, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MypageUserGracePeriod, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MypageUserGracePeriod, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((MypageUserGracePeriod)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MypageUserGracePeriod>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MypageUserGracePeriod.class, ModelWrapper.class);

	}

	private long _mypageUserGracePeriodId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _mypageUserId;
	private String _code;
	private int _value;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MypageUserGracePeriod, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MypageUserGracePeriod)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"mypageUserGracePeriodId", _mypageUserGracePeriodId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("mypageUserId", _mypageUserId);
		_columnOriginalValues.put("code_", _code);
		_columnOriginalValues.put("value", _value);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("code_", "code");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mypageUserGracePeriodId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("mypageUserId", 128L);

		columnBitmasks.put("code_", 256L);

		columnBitmasks.put("value", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MypageUserGracePeriod _escapedModel;

}