/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.user.model.UserRegistrationLiability;
import com.mypage.user.model.UserRegistrationLiabilityModel;
import com.mypage.user.model.UserRegistrationLiabilitySoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserRegistrationLiability service. Represents a row in the &quot;UserRegistrationLiability&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserRegistrationLiabilityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserRegistrationLiabilityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistrationLiabilityImpl
 * @generated
 */
@JSON(strict = true)
public class UserRegistrationLiabilityModelImpl
	extends BaseModelImpl<UserRegistrationLiability>
	implements UserRegistrationLiabilityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user registration liability model instance should use the <code>UserRegistrationLiability</code> interface instead.
	 */
	public static final String TABLE_NAME = "UserRegistrationLiability";

	public static final Object[][] TABLE_COLUMNS = {
		{"userRegistrationLiabilityId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"relationship", Types.VARCHAR}, {"age", Types.INTEGER},
		{"userRegistrationId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userRegistrationLiabilityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("relationship", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("age", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("userRegistrationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table UserRegistrationLiability (userRegistrationLiabilityId LONG not null primary key,name VARCHAR(75) null,relationship VARCHAR(75) null,age INTEGER,userRegistrationId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table UserRegistrationLiability";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userRegistrationLiability.userRegistrationLiabilityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY UserRegistrationLiability.userRegistrationLiabilityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERREGISTRATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERREGISTRATIONLIABILITYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static UserRegistrationLiability toModel(
		UserRegistrationLiabilitySoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		UserRegistrationLiability model = new UserRegistrationLiabilityImpl();

		model.setUserRegistrationLiabilityId(
			soapModel.getUserRegistrationLiabilityId());
		model.setName(soapModel.getName());
		model.setRelationship(soapModel.getRelationship());
		model.setAge(soapModel.getAge());
		model.setUserRegistrationId(soapModel.getUserRegistrationId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<UserRegistrationLiability> toModels(
		UserRegistrationLiabilitySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<UserRegistrationLiability> models =
			new ArrayList<UserRegistrationLiability>(soapModels.length);

		for (UserRegistrationLiabilitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public UserRegistrationLiabilityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userRegistrationLiabilityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserRegistrationLiabilityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userRegistrationLiabilityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserRegistrationLiability.class;
	}

	@Override
	public String getModelClassName() {
		return UserRegistrationLiability.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserRegistrationLiability, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserRegistrationLiability, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRegistrationLiability, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserRegistrationLiability)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserRegistrationLiability, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserRegistrationLiability, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserRegistrationLiability)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserRegistrationLiability, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserRegistrationLiability, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<UserRegistrationLiability, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<UserRegistrationLiability, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserRegistrationLiability, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<UserRegistrationLiability, Object>>();
		Map<String, BiConsumer<UserRegistrationLiability, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<UserRegistrationLiability, ?>>();

		attributeGetterFunctions.put(
			"userRegistrationLiabilityId",
			UserRegistrationLiability::getUserRegistrationLiabilityId);
		attributeSetterBiConsumers.put(
			"userRegistrationLiabilityId",
			(BiConsumer<UserRegistrationLiability, Long>)
				UserRegistrationLiability::setUserRegistrationLiabilityId);
		attributeGetterFunctions.put(
			"name", UserRegistrationLiability::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<UserRegistrationLiability, String>)
				UserRegistrationLiability::setName);
		attributeGetterFunctions.put(
			"relationship", UserRegistrationLiability::getRelationship);
		attributeSetterBiConsumers.put(
			"relationship",
			(BiConsumer<UserRegistrationLiability, String>)
				UserRegistrationLiability::setRelationship);
		attributeGetterFunctions.put("age", UserRegistrationLiability::getAge);
		attributeSetterBiConsumers.put(
			"age",
			(BiConsumer<UserRegistrationLiability, Integer>)
				UserRegistrationLiability::setAge);
		attributeGetterFunctions.put(
			"userRegistrationId",
			UserRegistrationLiability::getUserRegistrationId);
		attributeSetterBiConsumers.put(
			"userRegistrationId",
			(BiConsumer<UserRegistrationLiability, Long>)
				UserRegistrationLiability::setUserRegistrationId);
		attributeGetterFunctions.put(
			"groupId", UserRegistrationLiability::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<UserRegistrationLiability, Long>)
				UserRegistrationLiability::setGroupId);
		attributeGetterFunctions.put(
			"companyId", UserRegistrationLiability::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<UserRegistrationLiability, Long>)
				UserRegistrationLiability::setCompanyId);
		attributeGetterFunctions.put(
			"userId", UserRegistrationLiability::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<UserRegistrationLiability, Long>)
				UserRegistrationLiability::setUserId);
		attributeGetterFunctions.put(
			"userName", UserRegistrationLiability::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<UserRegistrationLiability, String>)
				UserRegistrationLiability::setUserName);
		attributeGetterFunctions.put(
			"createDate", UserRegistrationLiability::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<UserRegistrationLiability, Date>)
				UserRegistrationLiability::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", UserRegistrationLiability::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<UserRegistrationLiability, Date>)
				UserRegistrationLiability::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getUserRegistrationLiabilityId() {
		return _userRegistrationLiabilityId;
	}

	@Override
	public void setUserRegistrationLiabilityId(
		long userRegistrationLiabilityId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userRegistrationLiabilityId = userRegistrationLiabilityId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getRelationship() {
		if (_relationship == null) {
			return "";
		}
		else {
			return _relationship;
		}
	}

	@Override
	public void setRelationship(String relationship) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_relationship = relationship;
	}

	@JSON
	@Override
	public int getAge() {
		return _age;
	}

	@Override
	public void setAge(int age) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_age = age;
	}

	@JSON
	@Override
	public long getUserRegistrationId() {
		return _userRegistrationId;
	}

	@Override
	public void setUserRegistrationId(long userRegistrationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userRegistrationId = userRegistrationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserRegistrationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("userRegistrationId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UserRegistrationLiability.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserRegistrationLiability toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserRegistrationLiability>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserRegistrationLiabilityImpl userRegistrationLiabilityImpl =
			new UserRegistrationLiabilityImpl();

		userRegistrationLiabilityImpl.setUserRegistrationLiabilityId(
			getUserRegistrationLiabilityId());
		userRegistrationLiabilityImpl.setName(getName());
		userRegistrationLiabilityImpl.setRelationship(getRelationship());
		userRegistrationLiabilityImpl.setAge(getAge());
		userRegistrationLiabilityImpl.setUserRegistrationId(
			getUserRegistrationId());
		userRegistrationLiabilityImpl.setGroupId(getGroupId());
		userRegistrationLiabilityImpl.setCompanyId(getCompanyId());
		userRegistrationLiabilityImpl.setUserId(getUserId());
		userRegistrationLiabilityImpl.setUserName(getUserName());
		userRegistrationLiabilityImpl.setCreateDate(getCreateDate());
		userRegistrationLiabilityImpl.setModifiedDate(getModifiedDate());

		userRegistrationLiabilityImpl.resetOriginalValues();

		return userRegistrationLiabilityImpl;
	}

	@Override
	public int compareTo(UserRegistrationLiability userRegistrationLiability) {
		long primaryKey = userRegistrationLiability.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserRegistrationLiability)) {
			return false;
		}

		UserRegistrationLiability userRegistrationLiability =
			(UserRegistrationLiability)object;

		long primaryKey = userRegistrationLiability.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserRegistrationLiability> toCacheModel() {
		UserRegistrationLiabilityCacheModel
			userRegistrationLiabilityCacheModel =
				new UserRegistrationLiabilityCacheModel();

		userRegistrationLiabilityCacheModel.userRegistrationLiabilityId =
			getUserRegistrationLiabilityId();

		userRegistrationLiabilityCacheModel.name = getName();

		String name = userRegistrationLiabilityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			userRegistrationLiabilityCacheModel.name = null;
		}

		userRegistrationLiabilityCacheModel.relationship = getRelationship();

		String relationship = userRegistrationLiabilityCacheModel.relationship;

		if ((relationship != null) && (relationship.length() == 0)) {
			userRegistrationLiabilityCacheModel.relationship = null;
		}

		userRegistrationLiabilityCacheModel.age = getAge();

		userRegistrationLiabilityCacheModel.userRegistrationId =
			getUserRegistrationId();

		userRegistrationLiabilityCacheModel.groupId = getGroupId();

		userRegistrationLiabilityCacheModel.companyId = getCompanyId();

		userRegistrationLiabilityCacheModel.userId = getUserId();

		userRegistrationLiabilityCacheModel.userName = getUserName();

		String userName = userRegistrationLiabilityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			userRegistrationLiabilityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			userRegistrationLiabilityCacheModel.createDate =
				createDate.getTime();
		}
		else {
			userRegistrationLiabilityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userRegistrationLiabilityCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			userRegistrationLiabilityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return userRegistrationLiabilityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserRegistrationLiability, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserRegistrationLiability, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRegistrationLiability, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(UserRegistrationLiability)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<UserRegistrationLiability, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<UserRegistrationLiability, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRegistrationLiability, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((UserRegistrationLiability)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, UserRegistrationLiability>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						UserRegistrationLiability.class, ModelWrapper.class);

	}

	private long _userRegistrationLiabilityId;
	private String _name;
	private String _relationship;
	private int _age;
	private long _userRegistrationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<UserRegistrationLiability, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserRegistrationLiability)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"userRegistrationLiabilityId", _userRegistrationLiabilityId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("relationship", _relationship);
		_columnOriginalValues.put("age", _age);
		_columnOriginalValues.put("userRegistrationId", _userRegistrationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("userRegistrationLiabilityId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("relationship", 4L);

		columnBitmasks.put("age", 8L);

		columnBitmasks.put("userRegistrationId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserRegistrationLiability _escapedModel;

}