/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model.impl;

import com.mypage.user.model.UserRegistrationReference;
import com.mypage.user.service.UserRegistrationReferenceLocalServiceUtil;

/**
 * The extended model base implementation for the UserRegistrationReference service. Represents a row in the &quot;UserRegistrationReference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserRegistrationReferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistrationReferenceImpl
 * @see UserRegistrationReference
 * @generated
 */
public abstract class UserRegistrationReferenceBaseImpl
	extends UserRegistrationReferenceModelImpl
	implements UserRegistrationReference {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user registration reference model instance should use the <code>UserRegistrationReference</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserRegistrationReferenceLocalServiceUtil.
				addUserRegistrationReference(this);
		}
		else {
			UserRegistrationReferenceLocalServiceUtil.
				updateUserRegistrationReference(this);
		}
	}

}