/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.user.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.user.model.UserRegistrationJobExp;
import com.mypage.user.model.UserRegistrationJobExpModel;
import com.mypage.user.model.UserRegistrationJobExpSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserRegistrationJobExp service. Represents a row in the &quot;UserRegistrationJobExp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserRegistrationJobExpModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserRegistrationJobExpImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRegistrationJobExpImpl
 * @generated
 */
@JSON(strict = true)
public class UserRegistrationJobExpModelImpl
	extends BaseModelImpl<UserRegistrationJobExp>
	implements UserRegistrationJobExpModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user registration job exp model instance should use the <code>UserRegistrationJobExp</code> interface instead.
	 */
	public static final String TABLE_NAME = "UserRegistrationJobExp";

	public static final Object[][] TABLE_COLUMNS = {
		{"userRegistrationJobExpId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"year", Types.INTEGER}, {"jobHead", Types.VARCHAR},
		{"jobPosition", Types.VARCHAR}, {"jobIncome", Types.VARCHAR},
		{"otherInsuranceCompany", Types.INTEGER},
		{"userRegistrationId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userRegistrationJobExpId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("jobHead", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobPosition", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobIncome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("otherInsuranceCompany", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("userRegistrationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table UserRegistrationJobExp (userRegistrationJobExpId LONG not null primary key,name VARCHAR(75) null,year INTEGER,jobHead VARCHAR(75) null,jobPosition VARCHAR(75) null,jobIncome VARCHAR(75) null,otherInsuranceCompany INTEGER,userRegistrationId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table UserRegistrationJobExp";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userRegistrationJobExp.userRegistrationJobExpId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY UserRegistrationJobExp.userRegistrationJobExpId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERREGISTRATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERREGISTRATIONJOBEXPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static UserRegistrationJobExp toModel(
		UserRegistrationJobExpSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		UserRegistrationJobExp model = new UserRegistrationJobExpImpl();

		model.setUserRegistrationJobExpId(
			soapModel.getUserRegistrationJobExpId());
		model.setName(soapModel.getName());
		model.setYear(soapModel.getYear());
		model.setJobHead(soapModel.getJobHead());
		model.setJobPosition(soapModel.getJobPosition());
		model.setJobIncome(soapModel.getJobIncome());
		model.setOtherInsuranceCompany(soapModel.getOtherInsuranceCompany());
		model.setUserRegistrationId(soapModel.getUserRegistrationId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<UserRegistrationJobExp> toModels(
		UserRegistrationJobExpSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<UserRegistrationJobExp> models =
			new ArrayList<UserRegistrationJobExp>(soapModels.length);

		for (UserRegistrationJobExpSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public UserRegistrationJobExpModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userRegistrationJobExpId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserRegistrationJobExpId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userRegistrationJobExpId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserRegistrationJobExp.class;
	}

	@Override
	public String getModelClassName() {
		return UserRegistrationJobExp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserRegistrationJobExp, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserRegistrationJobExp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRegistrationJobExp, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserRegistrationJobExp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserRegistrationJobExp, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserRegistrationJobExp, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserRegistrationJobExp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserRegistrationJobExp, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserRegistrationJobExp, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<UserRegistrationJobExp, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UserRegistrationJobExp, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserRegistrationJobExp, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<UserRegistrationJobExp, Object>>();
		Map<String, BiConsumer<UserRegistrationJobExp, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<UserRegistrationJobExp, ?>>();

		attributeGetterFunctions.put(
			"userRegistrationJobExpId",
			UserRegistrationJobExp::getUserRegistrationJobExpId);
		attributeSetterBiConsumers.put(
			"userRegistrationJobExpId",
			(BiConsumer<UserRegistrationJobExp, Long>)
				UserRegistrationJobExp::setUserRegistrationJobExpId);
		attributeGetterFunctions.put("name", UserRegistrationJobExp::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<UserRegistrationJobExp, String>)
				UserRegistrationJobExp::setName);
		attributeGetterFunctions.put("year", UserRegistrationJobExp::getYear);
		attributeSetterBiConsumers.put(
			"year",
			(BiConsumer<UserRegistrationJobExp, Integer>)
				UserRegistrationJobExp::setYear);
		attributeGetterFunctions.put(
			"jobHead", UserRegistrationJobExp::getJobHead);
		attributeSetterBiConsumers.put(
			"jobHead",
			(BiConsumer<UserRegistrationJobExp, String>)
				UserRegistrationJobExp::setJobHead);
		attributeGetterFunctions.put(
			"jobPosition", UserRegistrationJobExp::getJobPosition);
		attributeSetterBiConsumers.put(
			"jobPosition",
			(BiConsumer<UserRegistrationJobExp, String>)
				UserRegistrationJobExp::setJobPosition);
		attributeGetterFunctions.put(
			"jobIncome", UserRegistrationJobExp::getJobIncome);
		attributeSetterBiConsumers.put(
			"jobIncome",
			(BiConsumer<UserRegistrationJobExp, String>)
				UserRegistrationJobExp::setJobIncome);
		attributeGetterFunctions.put(
			"otherInsuranceCompany",
			UserRegistrationJobExp::getOtherInsuranceCompany);
		attributeSetterBiConsumers.put(
			"otherInsuranceCompany",
			(BiConsumer<UserRegistrationJobExp, Integer>)
				UserRegistrationJobExp::setOtherInsuranceCompany);
		attributeGetterFunctions.put(
			"userRegistrationId",
			UserRegistrationJobExp::getUserRegistrationId);
		attributeSetterBiConsumers.put(
			"userRegistrationId",
			(BiConsumer<UserRegistrationJobExp, Long>)
				UserRegistrationJobExp::setUserRegistrationId);
		attributeGetterFunctions.put(
			"groupId", UserRegistrationJobExp::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<UserRegistrationJobExp, Long>)
				UserRegistrationJobExp::setGroupId);
		attributeGetterFunctions.put(
			"companyId", UserRegistrationJobExp::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<UserRegistrationJobExp, Long>)
				UserRegistrationJobExp::setCompanyId);
		attributeGetterFunctions.put(
			"userId", UserRegistrationJobExp::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<UserRegistrationJobExp, Long>)
				UserRegistrationJobExp::setUserId);
		attributeGetterFunctions.put(
			"userName", UserRegistrationJobExp::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<UserRegistrationJobExp, String>)
				UserRegistrationJobExp::setUserName);
		attributeGetterFunctions.put(
			"createDate", UserRegistrationJobExp::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<UserRegistrationJobExp, Date>)
				UserRegistrationJobExp::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", UserRegistrationJobExp::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<UserRegistrationJobExp, Date>)
				UserRegistrationJobExp::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getUserRegistrationJobExpId() {
		return _userRegistrationJobExpId;
	}

	@Override
	public void setUserRegistrationJobExpId(long userRegistrationJobExpId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userRegistrationJobExpId = userRegistrationJobExpId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_year = year;
	}

	@JSON
	@Override
	public String getJobHead() {
		if (_jobHead == null) {
			return "";
		}
		else {
			return _jobHead;
		}
	}

	@Override
	public void setJobHead(String jobHead) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jobHead = jobHead;
	}

	@JSON
	@Override
	public String getJobPosition() {
		if (_jobPosition == null) {
			return "";
		}
		else {
			return _jobPosition;
		}
	}

	@Override
	public void setJobPosition(String jobPosition) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jobPosition = jobPosition;
	}

	@JSON
	@Override
	public String getJobIncome() {
		if (_jobIncome == null) {
			return "";
		}
		else {
			return _jobIncome;
		}
	}

	@Override
	public void setJobIncome(String jobIncome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jobIncome = jobIncome;
	}

	@JSON
	@Override
	public int getOtherInsuranceCompany() {
		return _otherInsuranceCompany;
	}

	@Override
	public void setOtherInsuranceCompany(int otherInsuranceCompany) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_otherInsuranceCompany = otherInsuranceCompany;
	}

	@JSON
	@Override
	public long getUserRegistrationId() {
		return _userRegistrationId;
	}

	@Override
	public void setUserRegistrationId(long userRegistrationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userRegistrationId = userRegistrationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserRegistrationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("userRegistrationId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UserRegistrationJobExp.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserRegistrationJobExp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserRegistrationJobExp>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserRegistrationJobExpImpl userRegistrationJobExpImpl =
			new UserRegistrationJobExpImpl();

		userRegistrationJobExpImpl.setUserRegistrationJobExpId(
			getUserRegistrationJobExpId());
		userRegistrationJobExpImpl.setName(getName());
		userRegistrationJobExpImpl.setYear(getYear());
		userRegistrationJobExpImpl.setJobHead(getJobHead());
		userRegistrationJobExpImpl.setJobPosition(getJobPosition());
		userRegistrationJobExpImpl.setJobIncome(getJobIncome());
		userRegistrationJobExpImpl.setOtherInsuranceCompany(
			getOtherInsuranceCompany());
		userRegistrationJobExpImpl.setUserRegistrationId(
			getUserRegistrationId());
		userRegistrationJobExpImpl.setGroupId(getGroupId());
		userRegistrationJobExpImpl.setCompanyId(getCompanyId());
		userRegistrationJobExpImpl.setUserId(getUserId());
		userRegistrationJobExpImpl.setUserName(getUserName());
		userRegistrationJobExpImpl.setCreateDate(getCreateDate());
		userRegistrationJobExpImpl.setModifiedDate(getModifiedDate());

		userRegistrationJobExpImpl.resetOriginalValues();

		return userRegistrationJobExpImpl;
	}

	@Override
	public int compareTo(UserRegistrationJobExp userRegistrationJobExp) {
		long primaryKey = userRegistrationJobExp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserRegistrationJobExp)) {
			return false;
		}

		UserRegistrationJobExp userRegistrationJobExp =
			(UserRegistrationJobExp)object;

		long primaryKey = userRegistrationJobExp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserRegistrationJobExp> toCacheModel() {
		UserRegistrationJobExpCacheModel userRegistrationJobExpCacheModel =
			new UserRegistrationJobExpCacheModel();

		userRegistrationJobExpCacheModel.userRegistrationJobExpId =
			getUserRegistrationJobExpId();

		userRegistrationJobExpCacheModel.name = getName();

		String name = userRegistrationJobExpCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			userRegistrationJobExpCacheModel.name = null;
		}

		userRegistrationJobExpCacheModel.year = getYear();

		userRegistrationJobExpCacheModel.jobHead = getJobHead();

		String jobHead = userRegistrationJobExpCacheModel.jobHead;

		if ((jobHead != null) && (jobHead.length() == 0)) {
			userRegistrationJobExpCacheModel.jobHead = null;
		}

		userRegistrationJobExpCacheModel.jobPosition = getJobPosition();

		String jobPosition = userRegistrationJobExpCacheModel.jobPosition;

		if ((jobPosition != null) && (jobPosition.length() == 0)) {
			userRegistrationJobExpCacheModel.jobPosition = null;
		}

		userRegistrationJobExpCacheModel.jobIncome = getJobIncome();

		String jobIncome = userRegistrationJobExpCacheModel.jobIncome;

		if ((jobIncome != null) && (jobIncome.length() == 0)) {
			userRegistrationJobExpCacheModel.jobIncome = null;
		}

		userRegistrationJobExpCacheModel.otherInsuranceCompany =
			getOtherInsuranceCompany();

		userRegistrationJobExpCacheModel.userRegistrationId =
			getUserRegistrationId();

		userRegistrationJobExpCacheModel.groupId = getGroupId();

		userRegistrationJobExpCacheModel.companyId = getCompanyId();

		userRegistrationJobExpCacheModel.userId = getUserId();

		userRegistrationJobExpCacheModel.userName = getUserName();

		String userName = userRegistrationJobExpCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			userRegistrationJobExpCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			userRegistrationJobExpCacheModel.createDate = createDate.getTime();
		}
		else {
			userRegistrationJobExpCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userRegistrationJobExpCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			userRegistrationJobExpCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return userRegistrationJobExpCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserRegistrationJobExp, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserRegistrationJobExp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRegistrationJobExp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(UserRegistrationJobExp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<UserRegistrationJobExp, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<UserRegistrationJobExp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRegistrationJobExp, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((UserRegistrationJobExp)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserRegistrationJobExp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserRegistrationJobExp.class, ModelWrapper.class);

	}

	private long _userRegistrationJobExpId;
	private String _name;
	private int _year;
	private String _jobHead;
	private String _jobPosition;
	private String _jobIncome;
	private int _otherInsuranceCompany;
	private long _userRegistrationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<UserRegistrationJobExp, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserRegistrationJobExp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"userRegistrationJobExpId", _userRegistrationJobExpId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("year", _year);
		_columnOriginalValues.put("jobHead", _jobHead);
		_columnOriginalValues.put("jobPosition", _jobPosition);
		_columnOriginalValues.put("jobIncome", _jobIncome);
		_columnOriginalValues.put(
			"otherInsuranceCompany", _otherInsuranceCompany);
		_columnOriginalValues.put("userRegistrationId", _userRegistrationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("userRegistrationJobExpId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("year", 4L);

		columnBitmasks.put("jobHead", 8L);

		columnBitmasks.put("jobPosition", 16L);

		columnBitmasks.put("jobIncome", 32L);

		columnBitmasks.put("otherInsuranceCompany", 64L);

		columnBitmasks.put("userRegistrationId", 128L);

		columnBitmasks.put("groupId", 256L);

		columnBitmasks.put("companyId", 512L);

		columnBitmasks.put("userId", 1024L);

		columnBitmasks.put("userName", 2048L);

		columnBitmasks.put("createDate", 4096L);

		columnBitmasks.put("modifiedDate", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserRegistrationJobExp _escapedModel;

}