/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.BlacklistCustomer;
import com.mypage.admin.product.model.BlacklistCustomerModel;
import com.mypage.admin.product.model.BlacklistCustomerSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BlacklistCustomer service. Represents a row in the &quot;BlacklistCustomer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BlacklistCustomerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BlacklistCustomerImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see BlacklistCustomerImpl
 * @generated
 */
@JSON(strict = true)
public class BlacklistCustomerModelImpl
	extends BaseModelImpl<BlacklistCustomer> implements BlacklistCustomerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a blacklist customer model instance should use the <code>BlacklistCustomer</code> interface instead.
	 */
	public static final String TABLE_NAME = "BlacklistCustomer";

	public static final Object[][] TABLE_COLUMNS = {
		{"blacklistCustomerId", Types.BIGINT}, {"fullName", Types.VARCHAR},
		{"firstName", Types.VARCHAR}, {"middleName", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"ktp", Types.VARCHAR},
		{"kitas", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"dateOfBirth", Types.TIMESTAMP}, {"active_", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("blacklistCustomerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fullName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("middleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ktp", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kitas", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dateOfBirth", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BlacklistCustomer (blacklistCustomerId LONG not null primary key,fullName VARCHAR(75) null,firstName VARCHAR(75) null,middleName VARCHAR(75) null,lastName VARCHAR(75) null,ktp VARCHAR(75) null,kitas VARCHAR(75) null,email VARCHAR(75) null,dateOfBirth DATE null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table BlacklistCustomer";

	public static final String ORDER_BY_JPQL =
		" ORDER BY blacklistCustomer.blacklistCustomerId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BlacklistCustomer.blacklistCustomerId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMAIL_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FIRSTNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FULLNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KITAS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KTP_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LASTNAME_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MIDDLENAME_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BLACKLISTCUSTOMERID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static BlacklistCustomer toModel(BlacklistCustomerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BlacklistCustomer model = new BlacklistCustomerImpl();

		model.setBlacklistCustomerId(soapModel.getBlacklistCustomerId());
		model.setFullName(soapModel.getFullName());
		model.setFirstName(soapModel.getFirstName());
		model.setMiddleName(soapModel.getMiddleName());
		model.setLastName(soapModel.getLastName());
		model.setKtp(soapModel.getKtp());
		model.setKitas(soapModel.getKitas());
		model.setEmail(soapModel.getEmail());
		model.setDateOfBirth(soapModel.getDateOfBirth());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<BlacklistCustomer> toModels(
		BlacklistCustomerSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<BlacklistCustomer> models = new ArrayList<BlacklistCustomer>(
			soapModels.length);

		for (BlacklistCustomerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public BlacklistCustomerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _blacklistCustomerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBlacklistCustomerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _blacklistCustomerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BlacklistCustomer.class;
	}

	@Override
	public String getModelClassName() {
		return BlacklistCustomer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BlacklistCustomer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BlacklistCustomer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BlacklistCustomer, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BlacklistCustomer)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BlacklistCustomer, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BlacklistCustomer, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BlacklistCustomer)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BlacklistCustomer, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BlacklistCustomer, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<BlacklistCustomer, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<BlacklistCustomer, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<BlacklistCustomer, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<BlacklistCustomer, Object>>();
		Map<String, BiConsumer<BlacklistCustomer, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<BlacklistCustomer, ?>>();

		attributeGetterFunctions.put(
			"blacklistCustomerId", BlacklistCustomer::getBlacklistCustomerId);
		attributeSetterBiConsumers.put(
			"blacklistCustomerId",
			(BiConsumer<BlacklistCustomer, Long>)
				BlacklistCustomer::setBlacklistCustomerId);
		attributeGetterFunctions.put(
			"fullName", BlacklistCustomer::getFullName);
		attributeSetterBiConsumers.put(
			"fullName",
			(BiConsumer<BlacklistCustomer, String>)
				BlacklistCustomer::setFullName);
		attributeGetterFunctions.put(
			"firstName", BlacklistCustomer::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName",
			(BiConsumer<BlacklistCustomer, String>)
				BlacklistCustomer::setFirstName);
		attributeGetterFunctions.put(
			"middleName", BlacklistCustomer::getMiddleName);
		attributeSetterBiConsumers.put(
			"middleName",
			(BiConsumer<BlacklistCustomer, String>)
				BlacklistCustomer::setMiddleName);
		attributeGetterFunctions.put(
			"lastName", BlacklistCustomer::getLastName);
		attributeSetterBiConsumers.put(
			"lastName",
			(BiConsumer<BlacklistCustomer, String>)
				BlacklistCustomer::setLastName);
		attributeGetterFunctions.put("ktp", BlacklistCustomer::getKtp);
		attributeSetterBiConsumers.put(
			"ktp",
			(BiConsumer<BlacklistCustomer, String>)BlacklistCustomer::setKtp);
		attributeGetterFunctions.put("kitas", BlacklistCustomer::getKitas);
		attributeSetterBiConsumers.put(
			"kitas",
			(BiConsumer<BlacklistCustomer, String>)BlacklistCustomer::setKitas);
		attributeGetterFunctions.put("email", BlacklistCustomer::getEmail);
		attributeSetterBiConsumers.put(
			"email",
			(BiConsumer<BlacklistCustomer, String>)BlacklistCustomer::setEmail);
		attributeGetterFunctions.put(
			"dateOfBirth", BlacklistCustomer::getDateOfBirth);
		attributeSetterBiConsumers.put(
			"dateOfBirth",
			(BiConsumer<BlacklistCustomer, Date>)
				BlacklistCustomer::setDateOfBirth);
		attributeGetterFunctions.put("active", BlacklistCustomer::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<BlacklistCustomer, Integer>)
				BlacklistCustomer::setActive);
		attributeGetterFunctions.put("groupId", BlacklistCustomer::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<BlacklistCustomer, Long>)BlacklistCustomer::setGroupId);
		attributeGetterFunctions.put(
			"companyId", BlacklistCustomer::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<BlacklistCustomer, Long>)
				BlacklistCustomer::setCompanyId);
		attributeGetterFunctions.put("userId", BlacklistCustomer::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<BlacklistCustomer, Long>)BlacklistCustomer::setUserId);
		attributeGetterFunctions.put(
			"userName", BlacklistCustomer::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<BlacklistCustomer, String>)
				BlacklistCustomer::setUserName);
		attributeGetterFunctions.put(
			"createDate", BlacklistCustomer::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<BlacklistCustomer, Date>)
				BlacklistCustomer::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", BlacklistCustomer::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<BlacklistCustomer, Date>)
				BlacklistCustomer::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getBlacklistCustomerId() {
		return _blacklistCustomerId;
	}

	@Override
	public void setBlacklistCustomerId(long blacklistCustomerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_blacklistCustomerId = blacklistCustomerId;
	}

	@JSON
	@Override
	public String getFullName() {
		if (_fullName == null) {
			return "";
		}
		else {
			return _fullName;
		}
	}

	@Override
	public void setFullName(String fullName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fullName = fullName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFullName() {
		return getColumnOriginalValue("fullName");
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFirstName() {
		return getColumnOriginalValue("firstName");
	}

	@JSON
	@Override
	public String getMiddleName() {
		if (_middleName == null) {
			return "";
		}
		else {
			return _middleName;
		}
	}

	@Override
	public void setMiddleName(String middleName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_middleName = middleName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalMiddleName() {
		return getColumnOriginalValue("middleName");
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLastName() {
		return getColumnOriginalValue("lastName");
	}

	@JSON
	@Override
	public String getKtp() {
		if (_ktp == null) {
			return "";
		}
		else {
			return _ktp;
		}
	}

	@Override
	public void setKtp(String ktp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ktp = ktp;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalKtp() {
		return getColumnOriginalValue("ktp");
	}

	@JSON
	@Override
	public String getKitas() {
		if (_kitas == null) {
			return "";
		}
		else {
			return _kitas;
		}
	}

	@Override
	public void setKitas(String kitas) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kitas = kitas;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalKitas() {
		return getColumnOriginalValue("kitas");
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEmail() {
		return getColumnOriginalValue("email");
	}

	@JSON
	@Override
	public Date getDateOfBirth() {
		return _dateOfBirth;
	}

	@Override
	public void setDateOfBirth(Date dateOfBirth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfBirth = dateOfBirth;
	}

	@JSON
	@Override
	public Integer getActive() {
		return _active;
	}

	@Override
	public void setActive(Integer active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BlacklistCustomer.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BlacklistCustomer toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BlacklistCustomer>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BlacklistCustomerImpl blacklistCustomerImpl =
			new BlacklistCustomerImpl();

		blacklistCustomerImpl.setBlacklistCustomerId(getBlacklistCustomerId());
		blacklistCustomerImpl.setFullName(getFullName());
		blacklistCustomerImpl.setFirstName(getFirstName());
		blacklistCustomerImpl.setMiddleName(getMiddleName());
		blacklistCustomerImpl.setLastName(getLastName());
		blacklistCustomerImpl.setKtp(getKtp());
		blacklistCustomerImpl.setKitas(getKitas());
		blacklistCustomerImpl.setEmail(getEmail());
		blacklistCustomerImpl.setDateOfBirth(getDateOfBirth());
		blacklistCustomerImpl.setActive(getActive());
		blacklistCustomerImpl.setGroupId(getGroupId());
		blacklistCustomerImpl.setCompanyId(getCompanyId());
		blacklistCustomerImpl.setUserId(getUserId());
		blacklistCustomerImpl.setUserName(getUserName());
		blacklistCustomerImpl.setCreateDate(getCreateDate());
		blacklistCustomerImpl.setModifiedDate(getModifiedDate());

		blacklistCustomerImpl.resetOriginalValues();

		return blacklistCustomerImpl;
	}

	@Override
	public int compareTo(BlacklistCustomer blacklistCustomer) {
		long primaryKey = blacklistCustomer.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BlacklistCustomer)) {
			return false;
		}

		BlacklistCustomer blacklistCustomer = (BlacklistCustomer)object;

		long primaryKey = blacklistCustomer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BlacklistCustomer> toCacheModel() {
		BlacklistCustomerCacheModel blacklistCustomerCacheModel =
			new BlacklistCustomerCacheModel();

		blacklistCustomerCacheModel.blacklistCustomerId =
			getBlacklistCustomerId();

		blacklistCustomerCacheModel.fullName = getFullName();

		String fullName = blacklistCustomerCacheModel.fullName;

		if ((fullName != null) && (fullName.length() == 0)) {
			blacklistCustomerCacheModel.fullName = null;
		}

		blacklistCustomerCacheModel.firstName = getFirstName();

		String firstName = blacklistCustomerCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			blacklistCustomerCacheModel.firstName = null;
		}

		blacklistCustomerCacheModel.middleName = getMiddleName();

		String middleName = blacklistCustomerCacheModel.middleName;

		if ((middleName != null) && (middleName.length() == 0)) {
			blacklistCustomerCacheModel.middleName = null;
		}

		blacklistCustomerCacheModel.lastName = getLastName();

		String lastName = blacklistCustomerCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			blacklistCustomerCacheModel.lastName = null;
		}

		blacklistCustomerCacheModel.ktp = getKtp();

		String ktp = blacklistCustomerCacheModel.ktp;

		if ((ktp != null) && (ktp.length() == 0)) {
			blacklistCustomerCacheModel.ktp = null;
		}

		blacklistCustomerCacheModel.kitas = getKitas();

		String kitas = blacklistCustomerCacheModel.kitas;

		if ((kitas != null) && (kitas.length() == 0)) {
			blacklistCustomerCacheModel.kitas = null;
		}

		blacklistCustomerCacheModel.email = getEmail();

		String email = blacklistCustomerCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			blacklistCustomerCacheModel.email = null;
		}

		Date dateOfBirth = getDateOfBirth();

		if (dateOfBirth != null) {
			blacklistCustomerCacheModel.dateOfBirth = dateOfBirth.getTime();
		}
		else {
			blacklistCustomerCacheModel.dateOfBirth = Long.MIN_VALUE;
		}

		Integer active = getActive();

		if (active != null) {
			blacklistCustomerCacheModel.active = active;
		}

		blacklistCustomerCacheModel.groupId = getGroupId();

		blacklistCustomerCacheModel.companyId = getCompanyId();

		blacklistCustomerCacheModel.userId = getUserId();

		blacklistCustomerCacheModel.userName = getUserName();

		String userName = blacklistCustomerCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			blacklistCustomerCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			blacklistCustomerCacheModel.createDate = createDate.getTime();
		}
		else {
			blacklistCustomerCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			blacklistCustomerCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			blacklistCustomerCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return blacklistCustomerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BlacklistCustomer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BlacklistCustomer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BlacklistCustomer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BlacklistCustomer)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<BlacklistCustomer, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<BlacklistCustomer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BlacklistCustomer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((BlacklistCustomer)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BlacklistCustomer>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BlacklistCustomer.class, ModelWrapper.class);

	}

	private long _blacklistCustomerId;
	private String _fullName;
	private String _firstName;
	private String _middleName;
	private String _lastName;
	private String _ktp;
	private String _kitas;
	private String _email;
	private Date _dateOfBirth;
	private Integer _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BlacklistCustomer, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BlacklistCustomer)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("blacklistCustomerId", _blacklistCustomerId);
		_columnOriginalValues.put("fullName", _fullName);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("middleName", _middleName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("ktp", _ktp);
		_columnOriginalValues.put("kitas", _kitas);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("dateOfBirth", _dateOfBirth);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("blacklistCustomerId", 1L);

		columnBitmasks.put("fullName", 2L);

		columnBitmasks.put("firstName", 4L);

		columnBitmasks.put("middleName", 8L);

		columnBitmasks.put("lastName", 16L);

		columnBitmasks.put("ktp", 32L);

		columnBitmasks.put("kitas", 64L);

		columnBitmasks.put("email", 128L);

		columnBitmasks.put("dateOfBirth", 256L);

		columnBitmasks.put("active_", 512L);

		columnBitmasks.put("groupId", 1024L);

		columnBitmasks.put("companyId", 2048L);

		columnBitmasks.put("userId", 4096L);

		columnBitmasks.put("userName", 8192L);

		columnBitmasks.put("createDate", 16384L);

		columnBitmasks.put("modifiedDate", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BlacklistCustomer _escapedModel;

}