/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.HealthIndividuPremi;
import com.mypage.admin.product.model.HealthIndividuPremiModel;
import com.mypage.admin.product.model.HealthIndividuPremiSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the HealthIndividuPremi service. Represents a row in the &quot;HealthIndividuPremi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HealthIndividuPremiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HealthIndividuPremiImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see HealthIndividuPremiImpl
 * @generated
 */
@JSON(strict = true)
public class HealthIndividuPremiModelImpl
	extends BaseModelImpl<HealthIndividuPremi>
	implements HealthIndividuPremiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a health individu premi model instance should use the <code>HealthIndividuPremi</code> interface instead.
	 */
	public static final String TABLE_NAME = "HealthIndividuPremi";

	public static final Object[][] TABLE_COLUMNS = {
		{"healthIndividuPremiId", Types.BIGINT}, {"planId", Types.BIGINT},
		{"age", Types.INTEGER}, {"premi", Types.BIGINT},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("healthIndividuPremiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("planId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("age", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("premi", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HealthIndividuPremi (healthIndividuPremiId LONG not null primary key,planId LONG,age INTEGER,premi LONG,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table HealthIndividuPremi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY healthIndividuPremi.healthIndividuPremiId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HealthIndividuPremi.healthIndividuPremiId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLANID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HEALTHINDIVIDUPREMIID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static HealthIndividuPremi toModel(
		HealthIndividuPremiSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		HealthIndividuPremi model = new HealthIndividuPremiImpl();

		model.setHealthIndividuPremiId(soapModel.getHealthIndividuPremiId());
		model.setPlanId(soapModel.getPlanId());
		model.setAge(soapModel.getAge());
		model.setPremi(soapModel.getPremi());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<HealthIndividuPremi> toModels(
		HealthIndividuPremiSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<HealthIndividuPremi> models = new ArrayList<HealthIndividuPremi>(
			soapModels.length);

		for (HealthIndividuPremiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public HealthIndividuPremiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _healthIndividuPremiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHealthIndividuPremiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _healthIndividuPremiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HealthIndividuPremi.class;
	}

	@Override
	public String getModelClassName() {
		return HealthIndividuPremi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<HealthIndividuPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<HealthIndividuPremi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HealthIndividuPremi, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((HealthIndividuPremi)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<HealthIndividuPremi, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<HealthIndividuPremi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(HealthIndividuPremi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<HealthIndividuPremi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<HealthIndividuPremi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<HealthIndividuPremi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<HealthIndividuPremi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<HealthIndividuPremi, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<HealthIndividuPremi, Object>>();
		Map<String, BiConsumer<HealthIndividuPremi, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<HealthIndividuPremi, ?>>();

		attributeGetterFunctions.put(
			"healthIndividuPremiId",
			HealthIndividuPremi::getHealthIndividuPremiId);
		attributeSetterBiConsumers.put(
			"healthIndividuPremiId",
			(BiConsumer<HealthIndividuPremi, Long>)
				HealthIndividuPremi::setHealthIndividuPremiId);
		attributeGetterFunctions.put("planId", HealthIndividuPremi::getPlanId);
		attributeSetterBiConsumers.put(
			"planId",
			(BiConsumer<HealthIndividuPremi, Long>)
				HealthIndividuPremi::setPlanId);
		attributeGetterFunctions.put("age", HealthIndividuPremi::getAge);
		attributeSetterBiConsumers.put(
			"age",
			(BiConsumer<HealthIndividuPremi, Integer>)
				HealthIndividuPremi::setAge);
		attributeGetterFunctions.put("premi", HealthIndividuPremi::getPremi);
		attributeSetterBiConsumers.put(
			"premi",
			(BiConsumer<HealthIndividuPremi, Long>)
				HealthIndividuPremi::setPremi);
		attributeGetterFunctions.put("active", HealthIndividuPremi::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<HealthIndividuPremi, Integer>)
				HealthIndividuPremi::setActive);
		attributeGetterFunctions.put(
			"groupId", HealthIndividuPremi::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<HealthIndividuPremi, Long>)
				HealthIndividuPremi::setGroupId);
		attributeGetterFunctions.put(
			"companyId", HealthIndividuPremi::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<HealthIndividuPremi, Long>)
				HealthIndividuPremi::setCompanyId);
		attributeGetterFunctions.put("userId", HealthIndividuPremi::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<HealthIndividuPremi, Long>)
				HealthIndividuPremi::setUserId);
		attributeGetterFunctions.put(
			"userName", HealthIndividuPremi::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<HealthIndividuPremi, String>)
				HealthIndividuPremi::setUserName);
		attributeGetterFunctions.put(
			"createDate", HealthIndividuPremi::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<HealthIndividuPremi, Date>)
				HealthIndividuPremi::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", HealthIndividuPremi::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<HealthIndividuPremi, Date>)
				HealthIndividuPremi::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getHealthIndividuPremiId() {
		return _healthIndividuPremiId;
	}

	@Override
	public void setHealthIndividuPremiId(long healthIndividuPremiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_healthIndividuPremiId = healthIndividuPremiId;
	}

	@JSON
	@Override
	public long getPlanId() {
		return _planId;
	}

	@Override
	public void setPlanId(long planId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planId = planId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlanId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("planId"));
	}

	@JSON
	@Override
	public int getAge() {
		return _age;
	}

	@Override
	public void setAge(int age) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_age = age;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalAge() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("age"));
	}

	@JSON
	@Override
	public long getPremi() {
		return _premi;
	}

	@Override
	public void setPremi(long premi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_premi = premi;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), HealthIndividuPremi.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public HealthIndividuPremi toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, HealthIndividuPremi>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HealthIndividuPremiImpl healthIndividuPremiImpl =
			new HealthIndividuPremiImpl();

		healthIndividuPremiImpl.setHealthIndividuPremiId(
			getHealthIndividuPremiId());
		healthIndividuPremiImpl.setPlanId(getPlanId());
		healthIndividuPremiImpl.setAge(getAge());
		healthIndividuPremiImpl.setPremi(getPremi());
		healthIndividuPremiImpl.setActive(getActive());
		healthIndividuPremiImpl.setGroupId(getGroupId());
		healthIndividuPremiImpl.setCompanyId(getCompanyId());
		healthIndividuPremiImpl.setUserId(getUserId());
		healthIndividuPremiImpl.setUserName(getUserName());
		healthIndividuPremiImpl.setCreateDate(getCreateDate());
		healthIndividuPremiImpl.setModifiedDate(getModifiedDate());

		healthIndividuPremiImpl.resetOriginalValues();

		return healthIndividuPremiImpl;
	}

	@Override
	public int compareTo(HealthIndividuPremi healthIndividuPremi) {
		long primaryKey = healthIndividuPremi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof HealthIndividuPremi)) {
			return false;
		}

		HealthIndividuPremi healthIndividuPremi = (HealthIndividuPremi)object;

		long primaryKey = healthIndividuPremi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<HealthIndividuPremi> toCacheModel() {
		HealthIndividuPremiCacheModel healthIndividuPremiCacheModel =
			new HealthIndividuPremiCacheModel();

		healthIndividuPremiCacheModel.healthIndividuPremiId =
			getHealthIndividuPremiId();

		healthIndividuPremiCacheModel.planId = getPlanId();

		healthIndividuPremiCacheModel.age = getAge();

		healthIndividuPremiCacheModel.premi = getPremi();

		healthIndividuPremiCacheModel.active = getActive();

		healthIndividuPremiCacheModel.groupId = getGroupId();

		healthIndividuPremiCacheModel.companyId = getCompanyId();

		healthIndividuPremiCacheModel.userId = getUserId();

		healthIndividuPremiCacheModel.userName = getUserName();

		String userName = healthIndividuPremiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			healthIndividuPremiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			healthIndividuPremiCacheModel.createDate = createDate.getTime();
		}
		else {
			healthIndividuPremiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			healthIndividuPremiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			healthIndividuPremiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return healthIndividuPremiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<HealthIndividuPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<HealthIndividuPremi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HealthIndividuPremi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(HealthIndividuPremi)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<HealthIndividuPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<HealthIndividuPremi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HealthIndividuPremi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((HealthIndividuPremi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, HealthIndividuPremi>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					HealthIndividuPremi.class, ModelWrapper.class);

	}

	private long _healthIndividuPremiId;
	private long _planId;
	private int _age;
	private long _premi;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<HealthIndividuPremi, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((HealthIndividuPremi)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"healthIndividuPremiId", _healthIndividuPremiId);
		_columnOriginalValues.put("planId", _planId);
		_columnOriginalValues.put("age", _age);
		_columnOriginalValues.put("premi", _premi);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("healthIndividuPremiId", 1L);

		columnBitmasks.put("planId", 2L);

		columnBitmasks.put("age", 4L);

		columnBitmasks.put("premi", 8L);

		columnBitmasks.put("active_", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private HealthIndividuPremi _escapedModel;

}