/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.IntTravelStandardNewPremi;
import com.mypage.admin.product.model.IntTravelStandardNewPremiModel;
import com.mypage.admin.product.model.IntTravelStandardNewPremiSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the IntTravelStandardNewPremi service. Represents a row in the &quot;IntTravelStandardNewPremi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>IntTravelStandardNewPremiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IntTravelStandardNewPremiImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see IntTravelStandardNewPremiImpl
 * @generated
 */
@JSON(strict = true)
public class IntTravelStandardNewPremiModelImpl
	extends BaseModelImpl<IntTravelStandardNewPremi>
	implements IntTravelStandardNewPremiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a int travel standard new premi model instance should use the <code>IntTravelStandardNewPremi</code> interface instead.
	 */
	public static final String TABLE_NAME = "IntTravelStandardNewPremi";

	public static final Object[][] TABLE_COLUMNS = {
		{"intTravelStandardNewPremiId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"travelType", Types.VARCHAR}, {"packageType", Types.VARCHAR},
		{"peopleType", Types.VARCHAR}, {"mainInsured", Types.INTEGER},
		{"spouse", Types.INTEGER}, {"child", Types.INTEGER},
		{"currency_", Types.VARCHAR}, {"amount", Types.DECIMAL},
		{"additionalPrice", Types.DECIMAL}, {"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("intTravelStandardNewPremiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("travelType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("packageType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("peopleType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mainInsured", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("spouse", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("child", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("currency_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("amount", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("additionalPrice", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table IntTravelStandardNewPremi (intTravelStandardNewPremiId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,travelType VARCHAR(75) null,packageType VARCHAR(75) null,peopleType VARCHAR(75) null,mainInsured INTEGER,spouse INTEGER,child INTEGER,currency_ VARCHAR(75) null,amount DECIMAL(30, 16) null,additionalPrice DECIMAL(30, 16) null,active_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table IntTravelStandardNewPremi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY intTravelStandardNewPremi.intTravelStandardNewPremiId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY IntTravelStandardNewPremi.intTravelStandardNewPremiId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHILD_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CURRENCY_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MAININSURED_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PACKAGETYPE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PEOPLETYPE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SPOUSE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAVELTYPE_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INTTRAVELSTANDARDNEWPREMIID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static IntTravelStandardNewPremi toModel(
		IntTravelStandardNewPremiSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		IntTravelStandardNewPremi model = new IntTravelStandardNewPremiImpl();

		model.setIntTravelStandardNewPremiId(
			soapModel.getIntTravelStandardNewPremiId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTravelType(soapModel.getTravelType());
		model.setPackageType(soapModel.getPackageType());
		model.setPeopleType(soapModel.getPeopleType());
		model.setMainInsured(soapModel.getMainInsured());
		model.setSpouse(soapModel.getSpouse());
		model.setChild(soapModel.getChild());
		model.setCurrency(soapModel.getCurrency());
		model.setAmount(soapModel.getAmount());
		model.setAdditionalPrice(soapModel.getAdditionalPrice());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<IntTravelStandardNewPremi> toModels(
		IntTravelStandardNewPremiSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<IntTravelStandardNewPremi> models =
			new ArrayList<IntTravelStandardNewPremi>(soapModels.length);

		for (IntTravelStandardNewPremiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public IntTravelStandardNewPremiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _intTravelStandardNewPremiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIntTravelStandardNewPremiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _intTravelStandardNewPremiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return IntTravelStandardNewPremi.class;
	}

	@Override
	public String getModelClassName() {
		return IntTravelStandardNewPremi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<IntTravelStandardNewPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<IntTravelStandardNewPremi, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IntTravelStandardNewPremi, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((IntTravelStandardNewPremi)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<IntTravelStandardNewPremi, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<IntTravelStandardNewPremi, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(IntTravelStandardNewPremi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<IntTravelStandardNewPremi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<IntTravelStandardNewPremi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<IntTravelStandardNewPremi, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<IntTravelStandardNewPremi, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<IntTravelStandardNewPremi, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<IntTravelStandardNewPremi, Object>>();
		Map<String, BiConsumer<IntTravelStandardNewPremi, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<IntTravelStandardNewPremi, ?>>();

		attributeGetterFunctions.put(
			"intTravelStandardNewPremiId",
			IntTravelStandardNewPremi::getIntTravelStandardNewPremiId);
		attributeSetterBiConsumers.put(
			"intTravelStandardNewPremiId",
			(BiConsumer<IntTravelStandardNewPremi, Long>)
				IntTravelStandardNewPremi::setIntTravelStandardNewPremiId);
		attributeGetterFunctions.put(
			"groupId", IntTravelStandardNewPremi::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<IntTravelStandardNewPremi, Long>)
				IntTravelStandardNewPremi::setGroupId);
		attributeGetterFunctions.put(
			"companyId", IntTravelStandardNewPremi::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<IntTravelStandardNewPremi, Long>)
				IntTravelStandardNewPremi::setCompanyId);
		attributeGetterFunctions.put(
			"userId", IntTravelStandardNewPremi::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<IntTravelStandardNewPremi, Long>)
				IntTravelStandardNewPremi::setUserId);
		attributeGetterFunctions.put(
			"userName", IntTravelStandardNewPremi::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<IntTravelStandardNewPremi, String>)
				IntTravelStandardNewPremi::setUserName);
		attributeGetterFunctions.put(
			"createDate", IntTravelStandardNewPremi::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<IntTravelStandardNewPremi, Date>)
				IntTravelStandardNewPremi::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", IntTravelStandardNewPremi::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<IntTravelStandardNewPremi, Date>)
				IntTravelStandardNewPremi::setModifiedDate);
		attributeGetterFunctions.put(
			"travelType", IntTravelStandardNewPremi::getTravelType);
		attributeSetterBiConsumers.put(
			"travelType",
			(BiConsumer<IntTravelStandardNewPremi, String>)
				IntTravelStandardNewPremi::setTravelType);
		attributeGetterFunctions.put(
			"packageType", IntTravelStandardNewPremi::getPackageType);
		attributeSetterBiConsumers.put(
			"packageType",
			(BiConsumer<IntTravelStandardNewPremi, String>)
				IntTravelStandardNewPremi::setPackageType);
		attributeGetterFunctions.put(
			"peopleType", IntTravelStandardNewPremi::getPeopleType);
		attributeSetterBiConsumers.put(
			"peopleType",
			(BiConsumer<IntTravelStandardNewPremi, String>)
				IntTravelStandardNewPremi::setPeopleType);
		attributeGetterFunctions.put(
			"mainInsured", IntTravelStandardNewPremi::getMainInsured);
		attributeSetterBiConsumers.put(
			"mainInsured",
			(BiConsumer<IntTravelStandardNewPremi, Integer>)
				IntTravelStandardNewPremi::setMainInsured);
		attributeGetterFunctions.put(
			"spouse", IntTravelStandardNewPremi::getSpouse);
		attributeSetterBiConsumers.put(
			"spouse",
			(BiConsumer<IntTravelStandardNewPremi, Integer>)
				IntTravelStandardNewPremi::setSpouse);
		attributeGetterFunctions.put(
			"child", IntTravelStandardNewPremi::getChild);
		attributeSetterBiConsumers.put(
			"child",
			(BiConsumer<IntTravelStandardNewPremi, Integer>)
				IntTravelStandardNewPremi::setChild);
		attributeGetterFunctions.put(
			"currency", IntTravelStandardNewPremi::getCurrency);
		attributeSetterBiConsumers.put(
			"currency",
			(BiConsumer<IntTravelStandardNewPremi, String>)
				IntTravelStandardNewPremi::setCurrency);
		attributeGetterFunctions.put(
			"amount", IntTravelStandardNewPremi::getAmount);
		attributeSetterBiConsumers.put(
			"amount",
			(BiConsumer<IntTravelStandardNewPremi, BigDecimal>)
				IntTravelStandardNewPremi::setAmount);
		attributeGetterFunctions.put(
			"additionalPrice", IntTravelStandardNewPremi::getAdditionalPrice);
		attributeSetterBiConsumers.put(
			"additionalPrice",
			(BiConsumer<IntTravelStandardNewPremi, BigDecimal>)
				IntTravelStandardNewPremi::setAdditionalPrice);
		attributeGetterFunctions.put(
			"active", IntTravelStandardNewPremi::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<IntTravelStandardNewPremi, Integer>)
				IntTravelStandardNewPremi::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getIntTravelStandardNewPremiId() {
		return _intTravelStandardNewPremiId;
	}

	@Override
	public void setIntTravelStandardNewPremiId(
		long intTravelStandardNewPremiId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_intTravelStandardNewPremiId = intTravelStandardNewPremiId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTravelType() {
		if (_travelType == null) {
			return "";
		}
		else {
			return _travelType;
		}
	}

	@Override
	public void setTravelType(String travelType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelType = travelType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTravelType() {
		return getColumnOriginalValue("travelType");
	}

	@JSON
	@Override
	public String getPackageType() {
		if (_packageType == null) {
			return "";
		}
		else {
			return _packageType;
		}
	}

	@Override
	public void setPackageType(String packageType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_packageType = packageType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPackageType() {
		return getColumnOriginalValue("packageType");
	}

	@JSON
	@Override
	public String getPeopleType() {
		if (_peopleType == null) {
			return "";
		}
		else {
			return _peopleType;
		}
	}

	@Override
	public void setPeopleType(String peopleType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_peopleType = peopleType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPeopleType() {
		return getColumnOriginalValue("peopleType");
	}

	@JSON
	@Override
	public int getMainInsured() {
		return _mainInsured;
	}

	@Override
	public void setMainInsured(int mainInsured) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mainInsured = mainInsured;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalMainInsured() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("mainInsured"));
	}

	@JSON
	@Override
	public int getSpouse() {
		return _spouse;
	}

	@Override
	public void setSpouse(int spouse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spouse = spouse;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalSpouse() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("spouse"));
	}

	@JSON
	@Override
	public int getChild() {
		return _child;
	}

	@Override
	public void setChild(int child) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_child = child;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalChild() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("child"));
	}

	@JSON
	@Override
	public String getCurrency() {
		if (_currency == null) {
			return "";
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currency = currency;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCurrency() {
		return getColumnOriginalValue("currency_");
	}

	@JSON
	@Override
	public BigDecimal getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(BigDecimal amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@JSON
	@Override
	public BigDecimal getAdditionalPrice() {
		return _additionalPrice;
	}

	@Override
	public void setAdditionalPrice(BigDecimal additionalPrice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_additionalPrice = additionalPrice;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), IntTravelStandardNewPremi.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public IntTravelStandardNewPremi toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, IntTravelStandardNewPremi>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		IntTravelStandardNewPremiImpl intTravelStandardNewPremiImpl =
			new IntTravelStandardNewPremiImpl();

		intTravelStandardNewPremiImpl.setIntTravelStandardNewPremiId(
			getIntTravelStandardNewPremiId());
		intTravelStandardNewPremiImpl.setGroupId(getGroupId());
		intTravelStandardNewPremiImpl.setCompanyId(getCompanyId());
		intTravelStandardNewPremiImpl.setUserId(getUserId());
		intTravelStandardNewPremiImpl.setUserName(getUserName());
		intTravelStandardNewPremiImpl.setCreateDate(getCreateDate());
		intTravelStandardNewPremiImpl.setModifiedDate(getModifiedDate());
		intTravelStandardNewPremiImpl.setTravelType(getTravelType());
		intTravelStandardNewPremiImpl.setPackageType(getPackageType());
		intTravelStandardNewPremiImpl.setPeopleType(getPeopleType());
		intTravelStandardNewPremiImpl.setMainInsured(getMainInsured());
		intTravelStandardNewPremiImpl.setSpouse(getSpouse());
		intTravelStandardNewPremiImpl.setChild(getChild());
		intTravelStandardNewPremiImpl.setCurrency(getCurrency());
		intTravelStandardNewPremiImpl.setAmount(getAmount());
		intTravelStandardNewPremiImpl.setAdditionalPrice(getAdditionalPrice());
		intTravelStandardNewPremiImpl.setActive(getActive());

		intTravelStandardNewPremiImpl.resetOriginalValues();

		return intTravelStandardNewPremiImpl;
	}

	@Override
	public int compareTo(IntTravelStandardNewPremi intTravelStandardNewPremi) {
		long primaryKey = intTravelStandardNewPremi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof IntTravelStandardNewPremi)) {
			return false;
		}

		IntTravelStandardNewPremi intTravelStandardNewPremi =
			(IntTravelStandardNewPremi)object;

		long primaryKey = intTravelStandardNewPremi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<IntTravelStandardNewPremi> toCacheModel() {
		IntTravelStandardNewPremiCacheModel
			intTravelStandardNewPremiCacheModel =
				new IntTravelStandardNewPremiCacheModel();

		intTravelStandardNewPremiCacheModel.intTravelStandardNewPremiId =
			getIntTravelStandardNewPremiId();

		intTravelStandardNewPremiCacheModel.groupId = getGroupId();

		intTravelStandardNewPremiCacheModel.companyId = getCompanyId();

		intTravelStandardNewPremiCacheModel.userId = getUserId();

		intTravelStandardNewPremiCacheModel.userName = getUserName();

		String userName = intTravelStandardNewPremiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			intTravelStandardNewPremiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			intTravelStandardNewPremiCacheModel.createDate =
				createDate.getTime();
		}
		else {
			intTravelStandardNewPremiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			intTravelStandardNewPremiCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			intTravelStandardNewPremiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		intTravelStandardNewPremiCacheModel.travelType = getTravelType();

		String travelType = intTravelStandardNewPremiCacheModel.travelType;

		if ((travelType != null) && (travelType.length() == 0)) {
			intTravelStandardNewPremiCacheModel.travelType = null;
		}

		intTravelStandardNewPremiCacheModel.packageType = getPackageType();

		String packageType = intTravelStandardNewPremiCacheModel.packageType;

		if ((packageType != null) && (packageType.length() == 0)) {
			intTravelStandardNewPremiCacheModel.packageType = null;
		}

		intTravelStandardNewPremiCacheModel.peopleType = getPeopleType();

		String peopleType = intTravelStandardNewPremiCacheModel.peopleType;

		if ((peopleType != null) && (peopleType.length() == 0)) {
			intTravelStandardNewPremiCacheModel.peopleType = null;
		}

		intTravelStandardNewPremiCacheModel.mainInsured = getMainInsured();

		intTravelStandardNewPremiCacheModel.spouse = getSpouse();

		intTravelStandardNewPremiCacheModel.child = getChild();

		intTravelStandardNewPremiCacheModel.currency = getCurrency();

		String currency = intTravelStandardNewPremiCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			intTravelStandardNewPremiCacheModel.currency = null;
		}

		intTravelStandardNewPremiCacheModel.amount = getAmount();

		intTravelStandardNewPremiCacheModel.additionalPrice =
			getAdditionalPrice();

		intTravelStandardNewPremiCacheModel.active = getActive();

		return intTravelStandardNewPremiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<IntTravelStandardNewPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<IntTravelStandardNewPremi, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IntTravelStandardNewPremi, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(IntTravelStandardNewPremi)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<IntTravelStandardNewPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<IntTravelStandardNewPremi, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IntTravelStandardNewPremi, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((IntTravelStandardNewPremi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, IntTravelStandardNewPremi>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						IntTravelStandardNewPremi.class, ModelWrapper.class);

	}

	private long _intTravelStandardNewPremiId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _travelType;
	private String _packageType;
	private String _peopleType;
	private int _mainInsured;
	private int _spouse;
	private int _child;
	private String _currency;
	private BigDecimal _amount;
	private BigDecimal _additionalPrice;
	private int _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<IntTravelStandardNewPremi, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((IntTravelStandardNewPremi)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"intTravelStandardNewPremiId", _intTravelStandardNewPremiId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("travelType", _travelType);
		_columnOriginalValues.put("packageType", _packageType);
		_columnOriginalValues.put("peopleType", _peopleType);
		_columnOriginalValues.put("mainInsured", _mainInsured);
		_columnOriginalValues.put("spouse", _spouse);
		_columnOriginalValues.put("child", _child);
		_columnOriginalValues.put("currency_", _currency);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("additionalPrice", _additionalPrice);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("currency_", "currency");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("intTravelStandardNewPremiId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("travelType", 128L);

		columnBitmasks.put("packageType", 256L);

		columnBitmasks.put("peopleType", 512L);

		columnBitmasks.put("mainInsured", 1024L);

		columnBitmasks.put("spouse", 2048L);

		columnBitmasks.put("child", 4096L);

		columnBitmasks.put("currency_", 8192L);

		columnBitmasks.put("amount", 16384L);

		columnBitmasks.put("additionalPrice", 32768L);

		columnBitmasks.put("active_", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private IntTravelStandardNewPremi _escapedModel;

}