/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.MasterCity;
import com.mypage.admin.product.model.MasterCityModel;
import com.mypage.admin.product.model.MasterCitySoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterCity service. Represents a row in the &quot;MasterCity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterCityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterCityImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see MasterCityImpl
 * @generated
 */
@JSON(strict = true)
public class MasterCityModelImpl
	extends BaseModelImpl<MasterCity> implements MasterCityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master city model instance should use the <code>MasterCity</code> interface instead.
	 */
	public static final String TABLE_NAME = "MasterCity";

	public static final Object[][] TABLE_COLUMNS = {
		{"masterCityId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"provinceId", Types.BIGINT}, {"status", Types.VARCHAR},
		{"parEarthquakeZone", Types.INTEGER}, {"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("masterCityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("provinceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parEarthquakeZone", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MasterCity (masterCityId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,provinceId LONG,status VARCHAR(75) null,parEarthquakeZone INTEGER,active_ INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table MasterCity";

	public static final String ORDER_BY_JPQL = " ORDER BY masterCity.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY MasterCity.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROVINCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MasterCity toModel(MasterCitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MasterCity model = new MasterCityImpl();

		model.setMasterCityId(soapModel.getMasterCityId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setProvinceId(soapModel.getProvinceId());
		model.setStatus(soapModel.getStatus());
		model.setParEarthquakeZone(soapModel.getParEarthquakeZone());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MasterCity> toModels(MasterCitySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MasterCity> models = new ArrayList<MasterCity>(soapModels.length);

		for (MasterCitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MasterCityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _masterCityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMasterCityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _masterCityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterCity.class;
	}

	@Override
	public String getModelClassName() {
		return MasterCity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterCity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterCity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterCity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MasterCity)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterCity, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterCity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterCity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterCity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterCity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterCity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MasterCity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterCity, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MasterCity, Object>>();
		Map<String, BiConsumer<MasterCity, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MasterCity, ?>>();

		attributeGetterFunctions.put(
			"masterCityId", MasterCity::getMasterCityId);
		attributeSetterBiConsumers.put(
			"masterCityId",
			(BiConsumer<MasterCity, Long>)MasterCity::setMasterCityId);
		attributeGetterFunctions.put("groupId", MasterCity::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<MasterCity, Long>)MasterCity::setGroupId);
		attributeGetterFunctions.put("companyId", MasterCity::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MasterCity, Long>)MasterCity::setCompanyId);
		attributeGetterFunctions.put("userId", MasterCity::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MasterCity, Long>)MasterCity::setUserId);
		attributeGetterFunctions.put("userName", MasterCity::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MasterCity, String>)MasterCity::setUserName);
		attributeGetterFunctions.put("createDate", MasterCity::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MasterCity, Date>)MasterCity::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MasterCity::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MasterCity, Date>)MasterCity::setModifiedDate);
		attributeGetterFunctions.put("name", MasterCity::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<MasterCity, String>)MasterCity::setName);
		attributeGetterFunctions.put("provinceId", MasterCity::getProvinceId);
		attributeSetterBiConsumers.put(
			"provinceId",
			(BiConsumer<MasterCity, Long>)MasterCity::setProvinceId);
		attributeGetterFunctions.put("status", MasterCity::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<MasterCity, String>)MasterCity::setStatus);
		attributeGetterFunctions.put(
			"parEarthquakeZone", MasterCity::getParEarthquakeZone);
		attributeSetterBiConsumers.put(
			"parEarthquakeZone",
			(BiConsumer<MasterCity, Integer>)MasterCity::setParEarthquakeZone);
		attributeGetterFunctions.put("active", MasterCity::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<MasterCity, Integer>)MasterCity::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMasterCityId() {
		return _masterCityId;
	}

	@Override
	public void setMasterCityId(long masterCityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_masterCityId = masterCityId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public long getProvinceId() {
		return _provinceId;
	}

	@Override
	public void setProvinceId(long provinceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_provinceId = provinceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalProvinceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("provinceId"));
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public Integer getParEarthquakeZone() {
		return _parEarthquakeZone;
	}

	@Override
	public void setParEarthquakeZone(Integer parEarthquakeZone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parEarthquakeZone = parEarthquakeZone;
	}

	@JSON
	@Override
	public Integer getActive() {
		return _active;
	}

	@Override
	public void setActive(Integer active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Integer getOriginalActive() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("active_"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MasterCity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MasterCity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterCity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterCityImpl masterCityImpl = new MasterCityImpl();

		masterCityImpl.setMasterCityId(getMasterCityId());
		masterCityImpl.setGroupId(getGroupId());
		masterCityImpl.setCompanyId(getCompanyId());
		masterCityImpl.setUserId(getUserId());
		masterCityImpl.setUserName(getUserName());
		masterCityImpl.setCreateDate(getCreateDate());
		masterCityImpl.setModifiedDate(getModifiedDate());
		masterCityImpl.setName(getName());
		masterCityImpl.setProvinceId(getProvinceId());
		masterCityImpl.setStatus(getStatus());
		masterCityImpl.setParEarthquakeZone(getParEarthquakeZone());
		masterCityImpl.setActive(getActive());

		masterCityImpl.resetOriginalValues();

		return masterCityImpl;
	}

	@Override
	public int compareTo(MasterCity masterCity) {
		int value = 0;

		value = getName().compareTo(masterCity.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterCity)) {
			return false;
		}

		MasterCity masterCity = (MasterCity)object;

		long primaryKey = masterCity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterCity> toCacheModel() {
		MasterCityCacheModel masterCityCacheModel = new MasterCityCacheModel();

		masterCityCacheModel.masterCityId = getMasterCityId();

		masterCityCacheModel.groupId = getGroupId();

		masterCityCacheModel.companyId = getCompanyId();

		masterCityCacheModel.userId = getUserId();

		masterCityCacheModel.userName = getUserName();

		String userName = masterCityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			masterCityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			masterCityCacheModel.createDate = createDate.getTime();
		}
		else {
			masterCityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			masterCityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			masterCityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		masterCityCacheModel.name = getName();

		String name = masterCityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			masterCityCacheModel.name = null;
		}

		masterCityCacheModel.provinceId = getProvinceId();

		masterCityCacheModel.status = getStatus();

		String status = masterCityCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			masterCityCacheModel.status = null;
		}

		Integer parEarthquakeZone = getParEarthquakeZone();

		if (parEarthquakeZone != null) {
			masterCityCacheModel.parEarthquakeZone = parEarthquakeZone;
		}

		Integer active = getActive();

		if (active != null) {
			masterCityCacheModel.active = active;
		}

		return masterCityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterCity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterCity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterCity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MasterCity)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MasterCity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MasterCity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterCity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MasterCity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterCity>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterCity.class, ModelWrapper.class);

	}

	private long _masterCityId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private long _provinceId;
	private String _status;
	private Integer _parEarthquakeZone;
	private Integer _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MasterCity, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterCity)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("masterCityId", _masterCityId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("provinceId", _provinceId);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("parEarthquakeZone", _parEarthquakeZone);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("masterCityId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("provinceId", 256L);

		columnBitmasks.put("status", 512L);

		columnBitmasks.put("parEarthquakeZone", 1024L);

		columnBitmasks.put("active_", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterCity _escapedModel;

}