/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.MasterCurrency;
import com.mypage.admin.product.model.MasterCurrencyModel;
import com.mypage.admin.product.model.MasterCurrencySoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterCurrency service. Represents a row in the &quot;MasterCurrency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterCurrencyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterCurrencyImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see MasterCurrencyImpl
 * @generated
 */
@JSON(strict = true)
public class MasterCurrencyModelImpl
	extends BaseModelImpl<MasterCurrency> implements MasterCurrencyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master currency model instance should use the <code>MasterCurrency</code> interface instead.
	 */
	public static final String TABLE_NAME = "MasterCurrency";

	public static final Object[][] TABLE_COLUMNS = {
		{"currencyId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"amount", Types.DOUBLE}, {"isDefault", Types.INTEGER},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("currencyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("amount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("isDefault", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MasterCurrency (currencyId LONG not null primary key,name VARCHAR(75) null,amount DOUBLE,isDefault INTEGER,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table MasterCurrency";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterCurrency.currencyId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MasterCurrency.currencyId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CURRENCYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MasterCurrency toModel(MasterCurrencySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MasterCurrency model = new MasterCurrencyImpl();

		model.setCurrencyId(soapModel.getCurrencyId());
		model.setName(soapModel.getName());
		model.setAmount(soapModel.getAmount());
		model.setIsDefault(soapModel.getIsDefault());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MasterCurrency> toModels(
		MasterCurrencySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<MasterCurrency> models = new ArrayList<MasterCurrency>(
			soapModels.length);

		for (MasterCurrencySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MasterCurrencyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _currencyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCurrencyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _currencyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterCurrency.class;
	}

	@Override
	public String getModelClassName() {
		return MasterCurrency.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterCurrency, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterCurrency, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterCurrency, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MasterCurrency)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterCurrency, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterCurrency, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterCurrency)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterCurrency, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterCurrency, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterCurrency, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MasterCurrency, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterCurrency, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MasterCurrency, Object>>();
		Map<String, BiConsumer<MasterCurrency, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MasterCurrency, ?>>();

		attributeGetterFunctions.put(
			"currencyId", MasterCurrency::getCurrencyId);
		attributeSetterBiConsumers.put(
			"currencyId",
			(BiConsumer<MasterCurrency, Long>)MasterCurrency::setCurrencyId);
		attributeGetterFunctions.put("name", MasterCurrency::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<MasterCurrency, String>)MasterCurrency::setName);
		attributeGetterFunctions.put("amount", MasterCurrency::getAmount);
		attributeSetterBiConsumers.put(
			"amount",
			(BiConsumer<MasterCurrency, Double>)MasterCurrency::setAmount);
		attributeGetterFunctions.put("isDefault", MasterCurrency::getIsDefault);
		attributeSetterBiConsumers.put(
			"isDefault",
			(BiConsumer<MasterCurrency, Integer>)MasterCurrency::setIsDefault);
		attributeGetterFunctions.put("active", MasterCurrency::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<MasterCurrency, Integer>)MasterCurrency::setActive);
		attributeGetterFunctions.put("groupId", MasterCurrency::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MasterCurrency, Long>)MasterCurrency::setGroupId);
		attributeGetterFunctions.put("companyId", MasterCurrency::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MasterCurrency, Long>)MasterCurrency::setCompanyId);
		attributeGetterFunctions.put("userId", MasterCurrency::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MasterCurrency, Long>)MasterCurrency::setUserId);
		attributeGetterFunctions.put("userName", MasterCurrency::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MasterCurrency, String>)MasterCurrency::setUserName);
		attributeGetterFunctions.put(
			"createDate", MasterCurrency::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MasterCurrency, Date>)MasterCurrency::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MasterCurrency::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MasterCurrency, Date>)MasterCurrency::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCurrencyId() {
		return _currencyId;
	}

	@Override
	public void setCurrencyId(long currencyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currencyId = currencyId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@JSON
	@Override
	public Integer getIsDefault() {
		return _isDefault;
	}

	@Override
	public void setIsDefault(Integer isDefault) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isDefault = isDefault;
	}

	@JSON
	@Override
	public Integer getActive() {
		return _active;
	}

	@Override
	public void setActive(Integer active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MasterCurrency.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MasterCurrency toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterCurrency>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterCurrencyImpl masterCurrencyImpl = new MasterCurrencyImpl();

		masterCurrencyImpl.setCurrencyId(getCurrencyId());
		masterCurrencyImpl.setName(getName());
		masterCurrencyImpl.setAmount(getAmount());
		masterCurrencyImpl.setIsDefault(getIsDefault());
		masterCurrencyImpl.setActive(getActive());
		masterCurrencyImpl.setGroupId(getGroupId());
		masterCurrencyImpl.setCompanyId(getCompanyId());
		masterCurrencyImpl.setUserId(getUserId());
		masterCurrencyImpl.setUserName(getUserName());
		masterCurrencyImpl.setCreateDate(getCreateDate());
		masterCurrencyImpl.setModifiedDate(getModifiedDate());

		masterCurrencyImpl.resetOriginalValues();

		return masterCurrencyImpl;
	}

	@Override
	public int compareTo(MasterCurrency masterCurrency) {
		int value = 0;

		if (getCurrencyId() < masterCurrency.getCurrencyId()) {
			value = -1;
		}
		else if (getCurrencyId() > masterCurrency.getCurrencyId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterCurrency)) {
			return false;
		}

		MasterCurrency masterCurrency = (MasterCurrency)object;

		long primaryKey = masterCurrency.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterCurrency> toCacheModel() {
		MasterCurrencyCacheModel masterCurrencyCacheModel =
			new MasterCurrencyCacheModel();

		masterCurrencyCacheModel.currencyId = getCurrencyId();

		masterCurrencyCacheModel.name = getName();

		String name = masterCurrencyCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			masterCurrencyCacheModel.name = null;
		}

		masterCurrencyCacheModel.amount = getAmount();

		Integer isDefault = getIsDefault();

		if (isDefault != null) {
			masterCurrencyCacheModel.isDefault = isDefault;
		}

		Integer active = getActive();

		if (active != null) {
			masterCurrencyCacheModel.active = active;
		}

		masterCurrencyCacheModel.groupId = getGroupId();

		masterCurrencyCacheModel.companyId = getCompanyId();

		masterCurrencyCacheModel.userId = getUserId();

		masterCurrencyCacheModel.userName = getUserName();

		String userName = masterCurrencyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			masterCurrencyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			masterCurrencyCacheModel.createDate = createDate.getTime();
		}
		else {
			masterCurrencyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			masterCurrencyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			masterCurrencyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return masterCurrencyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterCurrency, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterCurrency, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterCurrency, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MasterCurrency)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MasterCurrency, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MasterCurrency, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterCurrency, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MasterCurrency)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterCurrency>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterCurrency.class, ModelWrapper.class);

	}

	private long _currencyId;
	private String _name;
	private double _amount;
	private Integer _isDefault;
	private Integer _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MasterCurrency, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterCurrency)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("currencyId", _currencyId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("isDefault", _isDefault);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("currencyId", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("amount", 4L);

		columnBitmasks.put("isDefault", 8L);

		columnBitmasks.put("active_", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterCurrency _escapedModel;

}