/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.mypage.admin.product.model.MasterProvince;
import com.mypage.admin.product.service.MasterProvinceLocalServiceUtil;

/**
 * The extended model base implementation for the MasterProvince service. Represents a row in the &quot;MasterProvince&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterProvinceImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see MasterProvinceImpl
 * @see MasterProvince
 * @generated
 */
public abstract class MasterProvinceBaseImpl
	extends MasterProvinceModelImpl implements MasterProvince {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master province model instance should use the <code>MasterProvince</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MasterProvinceLocalServiceUtil.addMasterProvince(this);
		}
		else {
			MasterProvinceLocalServiceUtil.updateMasterProvince(this);
		}
	}

}