/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.MasterBank;
import com.mypage.admin.product.model.MasterBankModel;
import com.mypage.admin.product.model.MasterBankSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterBank service. Represents a row in the &quot;MasterBank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterBankModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterBankImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see MasterBankImpl
 * @generated
 */
@JSON(strict = true)
public class MasterBankModelImpl
	extends BaseModelImpl<MasterBank> implements MasterBankModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master bank model instance should use the <code>MasterBank</code> interface instead.
	 */
	public static final String TABLE_NAME = "MasterBank";

	public static final Object[][] TABLE_COLUMNS = {
		{"masterBankId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"bankCode", Types.VARCHAR},
		{"bankDesc", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"detail", Types.VARCHAR}, {"imageURL", Types.VARCHAR},
		{"imageFileEntryId", Types.BIGINT}, {"order_", Types.INTEGER},
		{"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("masterBankId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("bankCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bankDesc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("detail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MasterBank (masterBankId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,bankCode VARCHAR(75) null,bankDesc VARCHAR(75) null,name VARCHAR(75) null,detail VARCHAR(75) null,imageURL VARCHAR(75) null,imageFileEntryId LONG,order_ INTEGER,active_ INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table MasterBank";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterBank.masterBankId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MasterBank.masterBankId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MASTERBANKID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MasterBank toModel(MasterBankSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MasterBank model = new MasterBankImpl();

		model.setMasterBankId(soapModel.getMasterBankId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setBankCode(soapModel.getBankCode());
		model.setBankDesc(soapModel.getBankDesc());
		model.setName(soapModel.getName());
		model.setDetail(soapModel.getDetail());
		model.setImageURL(soapModel.getImageURL());
		model.setImageFileEntryId(soapModel.getImageFileEntryId());
		model.setOrder(soapModel.getOrder());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MasterBank> toModels(MasterBankSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MasterBank> models = new ArrayList<MasterBank>(soapModels.length);

		for (MasterBankSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MasterBankModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _masterBankId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMasterBankId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _masterBankId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterBank.class;
	}

	@Override
	public String getModelClassName() {
		return MasterBank.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterBank, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterBank, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterBank, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MasterBank)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterBank, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterBank, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterBank)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterBank, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterBank, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterBank, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MasterBank, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterBank, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MasterBank, Object>>();
		Map<String, BiConsumer<MasterBank, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MasterBank, ?>>();

		attributeGetterFunctions.put(
			"masterBankId", MasterBank::getMasterBankId);
		attributeSetterBiConsumers.put(
			"masterBankId",
			(BiConsumer<MasterBank, Long>)MasterBank::setMasterBankId);
		attributeGetterFunctions.put("groupId", MasterBank::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<MasterBank, Long>)MasterBank::setGroupId);
		attributeGetterFunctions.put("companyId", MasterBank::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MasterBank, Long>)MasterBank::setCompanyId);
		attributeGetterFunctions.put("userId", MasterBank::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MasterBank, Long>)MasterBank::setUserId);
		attributeGetterFunctions.put("userName", MasterBank::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MasterBank, String>)MasterBank::setUserName);
		attributeGetterFunctions.put("createDate", MasterBank::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MasterBank, Date>)MasterBank::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MasterBank::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MasterBank, Date>)MasterBank::setModifiedDate);
		attributeGetterFunctions.put("bankCode", MasterBank::getBankCode);
		attributeSetterBiConsumers.put(
			"bankCode",
			(BiConsumer<MasterBank, String>)MasterBank::setBankCode);
		attributeGetterFunctions.put("bankDesc", MasterBank::getBankDesc);
		attributeSetterBiConsumers.put(
			"bankDesc",
			(BiConsumer<MasterBank, String>)MasterBank::setBankDesc);
		attributeGetterFunctions.put("name", MasterBank::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<MasterBank, String>)MasterBank::setName);
		attributeGetterFunctions.put("detail", MasterBank::getDetail);
		attributeSetterBiConsumers.put(
			"detail", (BiConsumer<MasterBank, String>)MasterBank::setDetail);
		attributeGetterFunctions.put("imageURL", MasterBank::getImageURL);
		attributeSetterBiConsumers.put(
			"imageURL",
			(BiConsumer<MasterBank, String>)MasterBank::setImageURL);
		attributeGetterFunctions.put(
			"imageFileEntryId", MasterBank::getImageFileEntryId);
		attributeSetterBiConsumers.put(
			"imageFileEntryId",
			(BiConsumer<MasterBank, Long>)MasterBank::setImageFileEntryId);
		attributeGetterFunctions.put("order", MasterBank::getOrder);
		attributeSetterBiConsumers.put(
			"order", (BiConsumer<MasterBank, Integer>)MasterBank::setOrder);
		attributeGetterFunctions.put("active", MasterBank::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<MasterBank, Integer>)MasterBank::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMasterBankId() {
		return _masterBankId;
	}

	@Override
	public void setMasterBankId(long masterBankId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_masterBankId = masterBankId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getBankCode() {
		if (_bankCode == null) {
			return "";
		}
		else {
			return _bankCode;
		}
	}

	@Override
	public void setBankCode(String bankCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankCode = bankCode;
	}

	@JSON
	@Override
	public String getBankDesc() {
		if (_bankDesc == null) {
			return "";
		}
		else {
			return _bankDesc;
		}
	}

	@Override
	public void setBankDesc(String bankDesc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bankDesc = bankDesc;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getDetail() {
		if (_detail == null) {
			return "";
		}
		else {
			return _detail;
		}
	}

	@Override
	public void setDetail(String detail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_detail = detail;
	}

	@JSON
	@Override
	public String getImageURL() {
		if (_imageURL == null) {
			return "";
		}
		else {
			return _imageURL;
		}
	}

	@Override
	public void setImageURL(String imageURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageURL = imageURL;
	}

	@JSON
	@Override
	public Long getImageFileEntryId() {
		return _imageFileEntryId;
	}

	@Override
	public void setImageFileEntryId(Long imageFileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageFileEntryId = imageFileEntryId;
	}

	@JSON
	@Override
	public Integer getOrder() {
		return _order;
	}

	@Override
	public void setOrder(Integer order) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_order = order;
	}

	@JSON
	@Override
	public Integer getActive() {
		return _active;
	}

	@Override
	public void setActive(Integer active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Integer getOriginalActive() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("active_"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MasterBank.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MasterBank toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterBank>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterBankImpl masterBankImpl = new MasterBankImpl();

		masterBankImpl.setMasterBankId(getMasterBankId());
		masterBankImpl.setGroupId(getGroupId());
		masterBankImpl.setCompanyId(getCompanyId());
		masterBankImpl.setUserId(getUserId());
		masterBankImpl.setUserName(getUserName());
		masterBankImpl.setCreateDate(getCreateDate());
		masterBankImpl.setModifiedDate(getModifiedDate());
		masterBankImpl.setBankCode(getBankCode());
		masterBankImpl.setBankDesc(getBankDesc());
		masterBankImpl.setName(getName());
		masterBankImpl.setDetail(getDetail());
		masterBankImpl.setImageURL(getImageURL());
		masterBankImpl.setImageFileEntryId(getImageFileEntryId());
		masterBankImpl.setOrder(getOrder());
		masterBankImpl.setActive(getActive());

		masterBankImpl.resetOriginalValues();

		return masterBankImpl;
	}

	@Override
	public int compareTo(MasterBank masterBank) {
		long primaryKey = masterBank.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterBank)) {
			return false;
		}

		MasterBank masterBank = (MasterBank)object;

		long primaryKey = masterBank.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterBank> toCacheModel() {
		MasterBankCacheModel masterBankCacheModel = new MasterBankCacheModel();

		masterBankCacheModel.masterBankId = getMasterBankId();

		masterBankCacheModel.groupId = getGroupId();

		masterBankCacheModel.companyId = getCompanyId();

		masterBankCacheModel.userId = getUserId();

		masterBankCacheModel.userName = getUserName();

		String userName = masterBankCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			masterBankCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			masterBankCacheModel.createDate = createDate.getTime();
		}
		else {
			masterBankCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			masterBankCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			masterBankCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		masterBankCacheModel.bankCode = getBankCode();

		String bankCode = masterBankCacheModel.bankCode;

		if ((bankCode != null) && (bankCode.length() == 0)) {
			masterBankCacheModel.bankCode = null;
		}

		masterBankCacheModel.bankDesc = getBankDesc();

		String bankDesc = masterBankCacheModel.bankDesc;

		if ((bankDesc != null) && (bankDesc.length() == 0)) {
			masterBankCacheModel.bankDesc = null;
		}

		masterBankCacheModel.name = getName();

		String name = masterBankCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			masterBankCacheModel.name = null;
		}

		masterBankCacheModel.detail = getDetail();

		String detail = masterBankCacheModel.detail;

		if ((detail != null) && (detail.length() == 0)) {
			masterBankCacheModel.detail = null;
		}

		masterBankCacheModel.imageURL = getImageURL();

		String imageURL = masterBankCacheModel.imageURL;

		if ((imageURL != null) && (imageURL.length() == 0)) {
			masterBankCacheModel.imageURL = null;
		}

		Long imageFileEntryId = getImageFileEntryId();

		if (imageFileEntryId != null) {
			masterBankCacheModel.imageFileEntryId = imageFileEntryId;
		}

		Integer order = getOrder();

		if (order != null) {
			masterBankCacheModel.order = order;
		}

		Integer active = getActive();

		if (active != null) {
			masterBankCacheModel.active = active;
		}

		return masterBankCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterBank, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterBank, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterBank, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MasterBank)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MasterBank, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MasterBank, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterBank, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MasterBank)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterBank>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterBank.class, ModelWrapper.class);

	}

	private long _masterBankId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _bankCode;
	private String _bankDesc;
	private String _name;
	private String _detail;
	private String _imageURL;
	private Long _imageFileEntryId;
	private Integer _order;
	private Integer _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MasterBank, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterBank)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("masterBankId", _masterBankId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("bankCode", _bankCode);
		_columnOriginalValues.put("bankDesc", _bankDesc);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("detail", _detail);
		_columnOriginalValues.put("imageURL", _imageURL);
		_columnOriginalValues.put("imageFileEntryId", _imageFileEntryId);
		_columnOriginalValues.put("order_", _order);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("order_", "order");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("masterBankId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("bankCode", 128L);

		columnBitmasks.put("bankDesc", 256L);

		columnBitmasks.put("name", 512L);

		columnBitmasks.put("detail", 1024L);

		columnBitmasks.put("imageURL", 2048L);

		columnBitmasks.put("imageFileEntryId", 4096L);

		columnBitmasks.put("order_", 8192L);

		columnBitmasks.put("active_", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterBank _escapedModel;

}