/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.MasterOccupationCategory;
import com.mypage.admin.product.model.MasterOccupationCategoryModel;
import com.mypage.admin.product.model.MasterOccupationCategorySoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterOccupationCategory service. Represents a row in the &quot;MasterOccupationCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterOccupationCategoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterOccupationCategoryImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see MasterOccupationCategoryImpl
 * @generated
 */
@JSON(strict = true)
public class MasterOccupationCategoryModelImpl
	extends BaseModelImpl<MasterOccupationCategory>
	implements MasterOccupationCategoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master occupation category model instance should use the <code>MasterOccupationCategory</code> interface instead.
	 */
	public static final String TABLE_NAME = "MasterOccupationCategory";

	public static final Object[][] TABLE_COLUMNS = {
		{"masterOccupationCategoryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("masterOccupationCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MasterOccupationCategory (masterOccupationCategoryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,active_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table MasterOccupationCategory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterOccupationCategory.masterOccupationCategoryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MasterOccupationCategory.masterOccupationCategoryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MASTEROCCUPATIONCATEGORYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MasterOccupationCategory toModel(
		MasterOccupationCategorySoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		MasterOccupationCategory model = new MasterOccupationCategoryImpl();

		model.setMasterOccupationCategoryId(
			soapModel.getMasterOccupationCategoryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MasterOccupationCategory> toModels(
		MasterOccupationCategorySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<MasterOccupationCategory> models =
			new ArrayList<MasterOccupationCategory>(soapModels.length);

		for (MasterOccupationCategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MasterOccupationCategoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _masterOccupationCategoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMasterOccupationCategoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _masterOccupationCategoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterOccupationCategory.class;
	}

	@Override
	public String getModelClassName() {
		return MasterOccupationCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterOccupationCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterOccupationCategory, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterOccupationCategory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MasterOccupationCategory)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterOccupationCategory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterOccupationCategory, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterOccupationCategory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterOccupationCategory, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterOccupationCategory, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterOccupationCategory, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<MasterOccupationCategory, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterOccupationCategory, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<MasterOccupationCategory, Object>>();
		Map<String, BiConsumer<MasterOccupationCategory, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<MasterOccupationCategory, ?>>();

		attributeGetterFunctions.put(
			"masterOccupationCategoryId",
			MasterOccupationCategory::getMasterOccupationCategoryId);
		attributeSetterBiConsumers.put(
			"masterOccupationCategoryId",
			(BiConsumer<MasterOccupationCategory, Long>)
				MasterOccupationCategory::setMasterOccupationCategoryId);
		attributeGetterFunctions.put(
			"groupId", MasterOccupationCategory::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MasterOccupationCategory, Long>)
				MasterOccupationCategory::setGroupId);
		attributeGetterFunctions.put(
			"companyId", MasterOccupationCategory::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MasterOccupationCategory, Long>)
				MasterOccupationCategory::setCompanyId);
		attributeGetterFunctions.put(
			"userId", MasterOccupationCategory::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MasterOccupationCategory, Long>)
				MasterOccupationCategory::setUserId);
		attributeGetterFunctions.put(
			"userName", MasterOccupationCategory::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MasterOccupationCategory, String>)
				MasterOccupationCategory::setUserName);
		attributeGetterFunctions.put(
			"createDate", MasterOccupationCategory::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MasterOccupationCategory, Date>)
				MasterOccupationCategory::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MasterOccupationCategory::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MasterOccupationCategory, Date>)
				MasterOccupationCategory::setModifiedDate);
		attributeGetterFunctions.put("name", MasterOccupationCategory::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<MasterOccupationCategory, String>)
				MasterOccupationCategory::setName);
		attributeGetterFunctions.put(
			"active", MasterOccupationCategory::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<MasterOccupationCategory, Integer>)
				MasterOccupationCategory::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMasterOccupationCategoryId() {
		return _masterOccupationCategoryId;
	}

	@Override
	public void setMasterOccupationCategoryId(long masterOccupationCategoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_masterOccupationCategoryId = masterOccupationCategoryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public Integer getActive() {
		return _active;
	}

	@Override
	public void setActive(Integer active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Integer getOriginalActive() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("active_"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MasterOccupationCategory.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MasterOccupationCategory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterOccupationCategory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterOccupationCategoryImpl masterOccupationCategoryImpl =
			new MasterOccupationCategoryImpl();

		masterOccupationCategoryImpl.setMasterOccupationCategoryId(
			getMasterOccupationCategoryId());
		masterOccupationCategoryImpl.setGroupId(getGroupId());
		masterOccupationCategoryImpl.setCompanyId(getCompanyId());
		masterOccupationCategoryImpl.setUserId(getUserId());
		masterOccupationCategoryImpl.setUserName(getUserName());
		masterOccupationCategoryImpl.setCreateDate(getCreateDate());
		masterOccupationCategoryImpl.setModifiedDate(getModifiedDate());
		masterOccupationCategoryImpl.setName(getName());
		masterOccupationCategoryImpl.setActive(getActive());

		masterOccupationCategoryImpl.resetOriginalValues();

		return masterOccupationCategoryImpl;
	}

	@Override
	public int compareTo(MasterOccupationCategory masterOccupationCategory) {
		long primaryKey = masterOccupationCategory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterOccupationCategory)) {
			return false;
		}

		MasterOccupationCategory masterOccupationCategory =
			(MasterOccupationCategory)object;

		long primaryKey = masterOccupationCategory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterOccupationCategory> toCacheModel() {
		MasterOccupationCategoryCacheModel masterOccupationCategoryCacheModel =
			new MasterOccupationCategoryCacheModel();

		masterOccupationCategoryCacheModel.masterOccupationCategoryId =
			getMasterOccupationCategoryId();

		masterOccupationCategoryCacheModel.groupId = getGroupId();

		masterOccupationCategoryCacheModel.companyId = getCompanyId();

		masterOccupationCategoryCacheModel.userId = getUserId();

		masterOccupationCategoryCacheModel.userName = getUserName();

		String userName = masterOccupationCategoryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			masterOccupationCategoryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			masterOccupationCategoryCacheModel.createDate =
				createDate.getTime();
		}
		else {
			masterOccupationCategoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			masterOccupationCategoryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			masterOccupationCategoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		masterOccupationCategoryCacheModel.name = getName();

		String name = masterOccupationCategoryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			masterOccupationCategoryCacheModel.name = null;
		}

		Integer active = getActive();

		if (active != null) {
			masterOccupationCategoryCacheModel.active = active;
		}

		return masterOccupationCategoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterOccupationCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterOccupationCategory, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterOccupationCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MasterOccupationCategory)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MasterOccupationCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MasterOccupationCategory, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterOccupationCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((MasterOccupationCategory)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, MasterOccupationCategory>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						MasterOccupationCategory.class, ModelWrapper.class);

	}

	private long _masterOccupationCategoryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private Integer _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MasterOccupationCategory, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterOccupationCategory)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"masterOccupationCategoryId", _masterOccupationCategoryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("masterOccupationCategoryId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("active_", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterOccupationCategory _escapedModel;

}