/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.MasterPromoCode;
import com.mypage.admin.product.model.MasterPromoCodeModel;
import com.mypage.admin.product.model.MasterPromoCodeSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterPromoCode service. Represents a row in the &quot;MasterPromoCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterPromoCodeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterPromoCodeImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see MasterPromoCodeImpl
 * @generated
 */
@JSON(strict = true)
public class MasterPromoCodeModelImpl
	extends BaseModelImpl<MasterPromoCode> implements MasterPromoCodeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master promo code model instance should use the <code>MasterPromoCode</code> interface instead.
	 */
	public static final String TABLE_NAME = "MasterPromoCode";

	public static final Object[][] TABLE_COLUMNS = {
		{"promoCodeId", Types.BIGINT}, {"isDefault", Types.INTEGER},
		{"productCode", Types.VARCHAR}, {"productName", Types.VARCHAR},
		{"promoType", Types.VARCHAR}, {"promoCode", Types.VARCHAR},
		{"discount", Types.DOUBLE}, {"startDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}, {"activeDay", Types.VARCHAR},
		{"limit_", Types.VARCHAR}, {"network", Types.VARCHAR},
		{"channel", Types.VARCHAR}, {"isB2C", Types.INTEGER},
		{"isB2B2C", Types.INTEGER}, {"isB2B", Types.INTEGER},
		{"payment", Types.VARCHAR}, {"birthdayMonth", Types.VARCHAR},
		{"remarks", Types.VARCHAR}, {"mypageUserId", Types.BIGINT},
		{"agentName", Types.VARCHAR}, {"deptoreCode", Types.VARCHAR},
		{"commission", Types.VARCHAR}, {"plan_", Types.VARCHAR},
		{"promoCodeTerms", Types.VARCHAR}, {"travellerType", Types.VARCHAR},
		{"utmId", Types.VARCHAR}, {"paymentChannelId", Types.VARCHAR},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("promoCodeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isDefault", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("productCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("promoType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("promoCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("discount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("activeDay", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("limit_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("network", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("channel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isB2C", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isB2B2C", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isB2B", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("payment", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("birthdayMonth", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("remarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mypageUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("agentName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deptoreCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commission", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("plan_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("promoCodeTerms", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("travellerType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utmId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paymentChannelId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MasterPromoCode (promoCodeId LONG not null primary key,isDefault INTEGER,productCode VARCHAR(75) null,productName VARCHAR(75) null,promoType VARCHAR(75) null,promoCode VARCHAR(75) null,discount DOUBLE,startDate DATE null,endDate DATE null,activeDay VARCHAR(75) null,limit_ VARCHAR(75) null,network VARCHAR(75) null,channel VARCHAR(75) null,isB2C INTEGER,isB2B2C INTEGER,isB2B INTEGER,payment VARCHAR(75) null,birthdayMonth VARCHAR(75) null,remarks VARCHAR(75) null,mypageUserId LONG,agentName VARCHAR(75) null,deptoreCode VARCHAR(75) null,commission VARCHAR(75) null,plan_ VARCHAR(75) null,promoCodeTerms VARCHAR(75) null,travellerType VARCHAR(75) null,utmId VARCHAR(75) null,paymentChannelId VARCHAR(75) null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table MasterPromoCode";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterPromoCode.promoCodeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MasterPromoCode.promoCodeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEUSERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROMOCODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROMOCODEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static MasterPromoCode toModel(MasterPromoCodeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MasterPromoCode model = new MasterPromoCodeImpl();

		model.setPromoCodeId(soapModel.getPromoCodeId());
		model.setIsDefault(soapModel.getIsDefault());
		model.setProductCode(soapModel.getProductCode());
		model.setProductName(soapModel.getProductName());
		model.setPromoType(soapModel.getPromoType());
		model.setPromoCode(soapModel.getPromoCode());
		model.setDiscount(soapModel.getDiscount());
		model.setStartDate(soapModel.getStartDate());
		model.setEndDate(soapModel.getEndDate());
		model.setActiveDay(soapModel.getActiveDay());
		model.setLimit(soapModel.getLimit());
		model.setNetwork(soapModel.getNetwork());
		model.setChannel(soapModel.getChannel());
		model.setIsB2C(soapModel.getIsB2C());
		model.setIsB2B2C(soapModel.getIsB2B2C());
		model.setIsB2B(soapModel.getIsB2B());
		model.setPayment(soapModel.getPayment());
		model.setBirthdayMonth(soapModel.getBirthdayMonth());
		model.setRemarks(soapModel.getRemarks());
		model.setMypageUserId(soapModel.getMypageUserId());
		model.setAgentName(soapModel.getAgentName());
		model.setDeptoreCode(soapModel.getDeptoreCode());
		model.setCommission(soapModel.getCommission());
		model.setPlan_(soapModel.getPlan_());
		model.setPromoCodeTerms(soapModel.getPromoCodeTerms());
		model.setTravellerType(soapModel.getTravellerType());
		model.setUtmId(soapModel.getUtmId());
		model.setPaymentChannelId(soapModel.getPaymentChannelId());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<MasterPromoCode> toModels(
		MasterPromoCodeSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<MasterPromoCode> models = new ArrayList<MasterPromoCode>(
			soapModels.length);

		for (MasterPromoCodeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MasterPromoCodeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _promoCodeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPromoCodeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _promoCodeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterPromoCode.class;
	}

	@Override
	public String getModelClassName() {
		return MasterPromoCode.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterPromoCode, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterPromoCode, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterPromoCode, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MasterPromoCode)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterPromoCode, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterPromoCode, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterPromoCode)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterPromoCode, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterPromoCode, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterPromoCode, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MasterPromoCode, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterPromoCode, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<MasterPromoCode, Object>>();
		Map<String, BiConsumer<MasterPromoCode, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MasterPromoCode, ?>>();

		attributeGetterFunctions.put(
			"promoCodeId", MasterPromoCode::getPromoCodeId);
		attributeSetterBiConsumers.put(
			"promoCodeId",
			(BiConsumer<MasterPromoCode, Long>)MasterPromoCode::setPromoCodeId);
		attributeGetterFunctions.put(
			"isDefault", MasterPromoCode::getIsDefault);
		attributeSetterBiConsumers.put(
			"isDefault",
			(BiConsumer<MasterPromoCode, Integer>)
				MasterPromoCode::setIsDefault);
		attributeGetterFunctions.put(
			"productCode", MasterPromoCode::getProductCode);
		attributeSetterBiConsumers.put(
			"productCode",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setProductCode);
		attributeGetterFunctions.put(
			"productName", MasterPromoCode::getProductName);
		attributeSetterBiConsumers.put(
			"productName",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setProductName);
		attributeGetterFunctions.put(
			"promoType", MasterPromoCode::getPromoType);
		attributeSetterBiConsumers.put(
			"promoType",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setPromoType);
		attributeGetterFunctions.put(
			"promoCode", MasterPromoCode::getPromoCode);
		attributeSetterBiConsumers.put(
			"promoCode",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setPromoCode);
		attributeGetterFunctions.put("discount", MasterPromoCode::getDiscount);
		attributeSetterBiConsumers.put(
			"discount",
			(BiConsumer<MasterPromoCode, Double>)MasterPromoCode::setDiscount);
		attributeGetterFunctions.put(
			"startDate", MasterPromoCode::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<MasterPromoCode, Date>)MasterPromoCode::setStartDate);
		attributeGetterFunctions.put("endDate", MasterPromoCode::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate",
			(BiConsumer<MasterPromoCode, Date>)MasterPromoCode::setEndDate);
		attributeGetterFunctions.put(
			"activeDay", MasterPromoCode::getActiveDay);
		attributeSetterBiConsumers.put(
			"activeDay",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setActiveDay);
		attributeGetterFunctions.put("limit", MasterPromoCode::getLimit);
		attributeSetterBiConsumers.put(
			"limit",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setLimit);
		attributeGetterFunctions.put("network", MasterPromoCode::getNetwork);
		attributeSetterBiConsumers.put(
			"network",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setNetwork);
		attributeGetterFunctions.put("channel", MasterPromoCode::getChannel);
		attributeSetterBiConsumers.put(
			"channel",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setChannel);
		attributeGetterFunctions.put("isB2C", MasterPromoCode::getIsB2C);
		attributeSetterBiConsumers.put(
			"isB2C",
			(BiConsumer<MasterPromoCode, Integer>)MasterPromoCode::setIsB2C);
		attributeGetterFunctions.put("isB2B2C", MasterPromoCode::getIsB2B2C);
		attributeSetterBiConsumers.put(
			"isB2B2C",
			(BiConsumer<MasterPromoCode, Integer>)MasterPromoCode::setIsB2B2C);
		attributeGetterFunctions.put("isB2B", MasterPromoCode::getIsB2B);
		attributeSetterBiConsumers.put(
			"isB2B",
			(BiConsumer<MasterPromoCode, Integer>)MasterPromoCode::setIsB2B);
		attributeGetterFunctions.put("payment", MasterPromoCode::getPayment);
		attributeSetterBiConsumers.put(
			"payment",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setPayment);
		attributeGetterFunctions.put(
			"birthdayMonth", MasterPromoCode::getBirthdayMonth);
		attributeSetterBiConsumers.put(
			"birthdayMonth",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setBirthdayMonth);
		attributeGetterFunctions.put("remarks", MasterPromoCode::getRemarks);
		attributeSetterBiConsumers.put(
			"remarks",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setRemarks);
		attributeGetterFunctions.put(
			"mypageUserId", MasterPromoCode::getMypageUserId);
		attributeSetterBiConsumers.put(
			"mypageUserId",
			(BiConsumer<MasterPromoCode, Long>)
				MasterPromoCode::setMypageUserId);
		attributeGetterFunctions.put(
			"agentName", MasterPromoCode::getAgentName);
		attributeSetterBiConsumers.put(
			"agentName",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setAgentName);
		attributeGetterFunctions.put(
			"deptoreCode", MasterPromoCode::getDeptoreCode);
		attributeSetterBiConsumers.put(
			"deptoreCode",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setDeptoreCode);
		attributeGetterFunctions.put(
			"commission", MasterPromoCode::getCommission);
		attributeSetterBiConsumers.put(
			"commission",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setCommission);
		attributeGetterFunctions.put("plan_", MasterPromoCode::getPlan_);
		attributeSetterBiConsumers.put(
			"plan_",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setPlan_);
		attributeGetterFunctions.put(
			"promoCodeTerms", MasterPromoCode::getPromoCodeTerms);
		attributeSetterBiConsumers.put(
			"promoCodeTerms",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setPromoCodeTerms);
		attributeGetterFunctions.put(
			"travellerType", MasterPromoCode::getTravellerType);
		attributeSetterBiConsumers.put(
			"travellerType",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setTravellerType);
		attributeGetterFunctions.put("utmId", MasterPromoCode::getUtmId);
		attributeSetterBiConsumers.put(
			"utmId",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setUtmId);
		attributeGetterFunctions.put(
			"paymentChannelId", MasterPromoCode::getPaymentChannelId);
		attributeSetterBiConsumers.put(
			"paymentChannelId",
			(BiConsumer<MasterPromoCode, String>)
				MasterPromoCode::setPaymentChannelId);
		attributeGetterFunctions.put("active", MasterPromoCode::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<MasterPromoCode, Integer>)MasterPromoCode::setActive);
		attributeGetterFunctions.put("groupId", MasterPromoCode::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<MasterPromoCode, Long>)MasterPromoCode::setGroupId);
		attributeGetterFunctions.put(
			"companyId", MasterPromoCode::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MasterPromoCode, Long>)MasterPromoCode::setCompanyId);
		attributeGetterFunctions.put("userId", MasterPromoCode::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<MasterPromoCode, Long>)MasterPromoCode::setUserId);
		attributeGetterFunctions.put("userName", MasterPromoCode::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MasterPromoCode, String>)MasterPromoCode::setUserName);
		attributeGetterFunctions.put(
			"createDate", MasterPromoCode::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MasterPromoCode, Date>)MasterPromoCode::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MasterPromoCode::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MasterPromoCode, Date>)
				MasterPromoCode::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPromoCodeId() {
		return _promoCodeId;
	}

	@Override
	public void setPromoCodeId(long promoCodeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promoCodeId = promoCodeId;
	}

	@JSON
	@Override
	public int getIsDefault() {
		return _isDefault;
	}

	@Override
	public void setIsDefault(int isDefault) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isDefault = isDefault;
	}

	@JSON
	@Override
	public String getProductCode() {
		if (_productCode == null) {
			return "";
		}
		else {
			return _productCode;
		}
	}

	@Override
	public void setProductCode(String productCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productCode = productCode;
	}

	@JSON
	@Override
	public String getProductName() {
		if (_productName == null) {
			return "";
		}
		else {
			return _productName;
		}
	}

	@Override
	public void setProductName(String productName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productName = productName;
	}

	@JSON
	@Override
	public String getPromoType() {
		if (_promoType == null) {
			return "";
		}
		else {
			return _promoType;
		}
	}

	@Override
	public void setPromoType(String promoType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promoType = promoType;
	}

	@JSON
	@Override
	public String getPromoCode() {
		if (_promoCode == null) {
			return "";
		}
		else {
			return _promoCode;
		}
	}

	@Override
	public void setPromoCode(String promoCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promoCode = promoCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPromoCode() {
		return getColumnOriginalValue("promoCode");
	}

	@JSON
	@Override
	public double getDiscount() {
		return _discount;
	}

	@Override
	public void setDiscount(double discount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_discount = discount;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public String getActiveDay() {
		if (_activeDay == null) {
			return "";
		}
		else {
			return _activeDay;
		}
	}

	@Override
	public void setActiveDay(String activeDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_activeDay = activeDay;
	}

	@JSON
	@Override
	public String getLimit() {
		if (_limit == null) {
			return "";
		}
		else {
			return _limit;
		}
	}

	@Override
	public void setLimit(String limit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_limit = limit;
	}

	@JSON
	@Override
	public String getNetwork() {
		if (_network == null) {
			return "";
		}
		else {
			return _network;
		}
	}

	@Override
	public void setNetwork(String network) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_network = network;
	}

	@JSON
	@Override
	public String getChannel() {
		if (_channel == null) {
			return "";
		}
		else {
			return _channel;
		}
	}

	@Override
	public void setChannel(String channel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_channel = channel;
	}

	@JSON
	@Override
	public int getIsB2C() {
		return _isB2C;
	}

	@Override
	public void setIsB2C(int isB2C) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isB2C = isB2C;
	}

	@JSON
	@Override
	public int getIsB2B2C() {
		return _isB2B2C;
	}

	@Override
	public void setIsB2B2C(int isB2B2C) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isB2B2C = isB2B2C;
	}

	@JSON
	@Override
	public int getIsB2B() {
		return _isB2B;
	}

	@Override
	public void setIsB2B(int isB2B) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isB2B = isB2B;
	}

	@JSON
	@Override
	public String getPayment() {
		if (_payment == null) {
			return "";
		}
		else {
			return _payment;
		}
	}

	@Override
	public void setPayment(String payment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_payment = payment;
	}

	@JSON
	@Override
	public String getBirthdayMonth() {
		if (_birthdayMonth == null) {
			return "";
		}
		else {
			return _birthdayMonth;
		}
	}

	@Override
	public void setBirthdayMonth(String birthdayMonth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_birthdayMonth = birthdayMonth;
	}

	@JSON
	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return "";
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_remarks = remarks;
	}

	@JSON
	@Override
	public long getMypageUserId() {
		return _mypageUserId;
	}

	@Override
	public void setMypageUserId(long mypageUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserId = mypageUserId;
	}

	@Override
	public String getMypageUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getMypageUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setMypageUserUuid(String mypageUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMypageUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("mypageUserId"));
	}

	@JSON
	@Override
	public String getAgentName() {
		if (_agentName == null) {
			return "";
		}
		else {
			return _agentName;
		}
	}

	@Override
	public void setAgentName(String agentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agentName = agentName;
	}

	@JSON
	@Override
	public String getDeptoreCode() {
		if (_deptoreCode == null) {
			return "";
		}
		else {
			return _deptoreCode;
		}
	}

	@Override
	public void setDeptoreCode(String deptoreCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deptoreCode = deptoreCode;
	}

	@JSON
	@Override
	public String getCommission() {
		if (_commission == null) {
			return "";
		}
		else {
			return _commission;
		}
	}

	@Override
	public void setCommission(String commission) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commission = commission;
	}

	@JSON
	@Override
	public String getPlan_() {
		if (_plan_ == null) {
			return "";
		}
		else {
			return _plan_;
		}
	}

	@Override
	public void setPlan_(String plan_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_plan_ = plan_;
	}

	@JSON
	@Override
	public String getPromoCodeTerms() {
		if (_promoCodeTerms == null) {
			return "";
		}
		else {
			return _promoCodeTerms;
		}
	}

	@Override
	public void setPromoCodeTerms(String promoCodeTerms) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_promoCodeTerms = promoCodeTerms;
	}

	@JSON
	@Override
	public String getTravellerType() {
		if (_travellerType == null) {
			return "";
		}
		else {
			return _travellerType;
		}
	}

	@Override
	public void setTravellerType(String travellerType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travellerType = travellerType;
	}

	@JSON
	@Override
	public String getUtmId() {
		if (_utmId == null) {
			return "";
		}
		else {
			return _utmId;
		}
	}

	@Override
	public void setUtmId(String utmId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utmId = utmId;
	}

	@JSON
	@Override
	public String getPaymentChannelId() {
		if (_paymentChannelId == null) {
			return "";
		}
		else {
			return _paymentChannelId;
		}
	}

	@Override
	public void setPaymentChannelId(String paymentChannelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentChannelId = paymentChannelId;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MasterPromoCode.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MasterPromoCode toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterPromoCode>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterPromoCodeImpl masterPromoCodeImpl = new MasterPromoCodeImpl();

		masterPromoCodeImpl.setPromoCodeId(getPromoCodeId());
		masterPromoCodeImpl.setIsDefault(getIsDefault());
		masterPromoCodeImpl.setProductCode(getProductCode());
		masterPromoCodeImpl.setProductName(getProductName());
		masterPromoCodeImpl.setPromoType(getPromoType());
		masterPromoCodeImpl.setPromoCode(getPromoCode());
		masterPromoCodeImpl.setDiscount(getDiscount());
		masterPromoCodeImpl.setStartDate(getStartDate());
		masterPromoCodeImpl.setEndDate(getEndDate());
		masterPromoCodeImpl.setActiveDay(getActiveDay());
		masterPromoCodeImpl.setLimit(getLimit());
		masterPromoCodeImpl.setNetwork(getNetwork());
		masterPromoCodeImpl.setChannel(getChannel());
		masterPromoCodeImpl.setIsB2C(getIsB2C());
		masterPromoCodeImpl.setIsB2B2C(getIsB2B2C());
		masterPromoCodeImpl.setIsB2B(getIsB2B());
		masterPromoCodeImpl.setPayment(getPayment());
		masterPromoCodeImpl.setBirthdayMonth(getBirthdayMonth());
		masterPromoCodeImpl.setRemarks(getRemarks());
		masterPromoCodeImpl.setMypageUserId(getMypageUserId());
		masterPromoCodeImpl.setAgentName(getAgentName());
		masterPromoCodeImpl.setDeptoreCode(getDeptoreCode());
		masterPromoCodeImpl.setCommission(getCommission());
		masterPromoCodeImpl.setPlan_(getPlan_());
		masterPromoCodeImpl.setPromoCodeTerms(getPromoCodeTerms());
		masterPromoCodeImpl.setTravellerType(getTravellerType());
		masterPromoCodeImpl.setUtmId(getUtmId());
		masterPromoCodeImpl.setPaymentChannelId(getPaymentChannelId());
		masterPromoCodeImpl.setActive(getActive());
		masterPromoCodeImpl.setGroupId(getGroupId());
		masterPromoCodeImpl.setCompanyId(getCompanyId());
		masterPromoCodeImpl.setUserId(getUserId());
		masterPromoCodeImpl.setUserName(getUserName());
		masterPromoCodeImpl.setCreateDate(getCreateDate());
		masterPromoCodeImpl.setModifiedDate(getModifiedDate());

		masterPromoCodeImpl.resetOriginalValues();

		return masterPromoCodeImpl;
	}

	@Override
	public int compareTo(MasterPromoCode masterPromoCode) {
		long primaryKey = masterPromoCode.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterPromoCode)) {
			return false;
		}

		MasterPromoCode masterPromoCode = (MasterPromoCode)object;

		long primaryKey = masterPromoCode.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterPromoCode> toCacheModel() {
		MasterPromoCodeCacheModel masterPromoCodeCacheModel =
			new MasterPromoCodeCacheModel();

		masterPromoCodeCacheModel.promoCodeId = getPromoCodeId();

		masterPromoCodeCacheModel.isDefault = getIsDefault();

		masterPromoCodeCacheModel.productCode = getProductCode();

		String productCode = masterPromoCodeCacheModel.productCode;

		if ((productCode != null) && (productCode.length() == 0)) {
			masterPromoCodeCacheModel.productCode = null;
		}

		masterPromoCodeCacheModel.productName = getProductName();

		String productName = masterPromoCodeCacheModel.productName;

		if ((productName != null) && (productName.length() == 0)) {
			masterPromoCodeCacheModel.productName = null;
		}

		masterPromoCodeCacheModel.promoType = getPromoType();

		String promoType = masterPromoCodeCacheModel.promoType;

		if ((promoType != null) && (promoType.length() == 0)) {
			masterPromoCodeCacheModel.promoType = null;
		}

		masterPromoCodeCacheModel.promoCode = getPromoCode();

		String promoCode = masterPromoCodeCacheModel.promoCode;

		if ((promoCode != null) && (promoCode.length() == 0)) {
			masterPromoCodeCacheModel.promoCode = null;
		}

		masterPromoCodeCacheModel.discount = getDiscount();

		Date startDate = getStartDate();

		if (startDate != null) {
			masterPromoCodeCacheModel.startDate = startDate.getTime();
		}
		else {
			masterPromoCodeCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			masterPromoCodeCacheModel.endDate = endDate.getTime();
		}
		else {
			masterPromoCodeCacheModel.endDate = Long.MIN_VALUE;
		}

		masterPromoCodeCacheModel.activeDay = getActiveDay();

		String activeDay = masterPromoCodeCacheModel.activeDay;

		if ((activeDay != null) && (activeDay.length() == 0)) {
			masterPromoCodeCacheModel.activeDay = null;
		}

		masterPromoCodeCacheModel.limit = getLimit();

		String limit = masterPromoCodeCacheModel.limit;

		if ((limit != null) && (limit.length() == 0)) {
			masterPromoCodeCacheModel.limit = null;
		}

		masterPromoCodeCacheModel.network = getNetwork();

		String network = masterPromoCodeCacheModel.network;

		if ((network != null) && (network.length() == 0)) {
			masterPromoCodeCacheModel.network = null;
		}

		masterPromoCodeCacheModel.channel = getChannel();

		String channel = masterPromoCodeCacheModel.channel;

		if ((channel != null) && (channel.length() == 0)) {
			masterPromoCodeCacheModel.channel = null;
		}

		masterPromoCodeCacheModel.isB2C = getIsB2C();

		masterPromoCodeCacheModel.isB2B2C = getIsB2B2C();

		masterPromoCodeCacheModel.isB2B = getIsB2B();

		masterPromoCodeCacheModel.payment = getPayment();

		String payment = masterPromoCodeCacheModel.payment;

		if ((payment != null) && (payment.length() == 0)) {
			masterPromoCodeCacheModel.payment = null;
		}

		masterPromoCodeCacheModel.birthdayMonth = getBirthdayMonth();

		String birthdayMonth = masterPromoCodeCacheModel.birthdayMonth;

		if ((birthdayMonth != null) && (birthdayMonth.length() == 0)) {
			masterPromoCodeCacheModel.birthdayMonth = null;
		}

		masterPromoCodeCacheModel.remarks = getRemarks();

		String remarks = masterPromoCodeCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			masterPromoCodeCacheModel.remarks = null;
		}

		masterPromoCodeCacheModel.mypageUserId = getMypageUserId();

		masterPromoCodeCacheModel.agentName = getAgentName();

		String agentName = masterPromoCodeCacheModel.agentName;

		if ((agentName != null) && (agentName.length() == 0)) {
			masterPromoCodeCacheModel.agentName = null;
		}

		masterPromoCodeCacheModel.deptoreCode = getDeptoreCode();

		String deptoreCode = masterPromoCodeCacheModel.deptoreCode;

		if ((deptoreCode != null) && (deptoreCode.length() == 0)) {
			masterPromoCodeCacheModel.deptoreCode = null;
		}

		masterPromoCodeCacheModel.commission = getCommission();

		String commission = masterPromoCodeCacheModel.commission;

		if ((commission != null) && (commission.length() == 0)) {
			masterPromoCodeCacheModel.commission = null;
		}

		masterPromoCodeCacheModel.plan_ = getPlan_();

		String plan_ = masterPromoCodeCacheModel.plan_;

		if ((plan_ != null) && (plan_.length() == 0)) {
			masterPromoCodeCacheModel.plan_ = null;
		}

		masterPromoCodeCacheModel.promoCodeTerms = getPromoCodeTerms();

		String promoCodeTerms = masterPromoCodeCacheModel.promoCodeTerms;

		if ((promoCodeTerms != null) && (promoCodeTerms.length() == 0)) {
			masterPromoCodeCacheModel.promoCodeTerms = null;
		}

		masterPromoCodeCacheModel.travellerType = getTravellerType();

		String travellerType = masterPromoCodeCacheModel.travellerType;

		if ((travellerType != null) && (travellerType.length() == 0)) {
			masterPromoCodeCacheModel.travellerType = null;
		}

		masterPromoCodeCacheModel.utmId = getUtmId();

		String utmId = masterPromoCodeCacheModel.utmId;

		if ((utmId != null) && (utmId.length() == 0)) {
			masterPromoCodeCacheModel.utmId = null;
		}

		masterPromoCodeCacheModel.paymentChannelId = getPaymentChannelId();

		String paymentChannelId = masterPromoCodeCacheModel.paymentChannelId;

		if ((paymentChannelId != null) && (paymentChannelId.length() == 0)) {
			masterPromoCodeCacheModel.paymentChannelId = null;
		}

		masterPromoCodeCacheModel.active = getActive();

		masterPromoCodeCacheModel.groupId = getGroupId();

		masterPromoCodeCacheModel.companyId = getCompanyId();

		masterPromoCodeCacheModel.userId = getUserId();

		masterPromoCodeCacheModel.userName = getUserName();

		String userName = masterPromoCodeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			masterPromoCodeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			masterPromoCodeCacheModel.createDate = createDate.getTime();
		}
		else {
			masterPromoCodeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			masterPromoCodeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			masterPromoCodeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return masterPromoCodeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterPromoCode, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterPromoCode, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterPromoCode, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MasterPromoCode)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MasterPromoCode, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MasterPromoCode, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterPromoCode, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MasterPromoCode)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterPromoCode>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterPromoCode.class, ModelWrapper.class);

	}

	private long _promoCodeId;
	private int _isDefault;
	private String _productCode;
	private String _productName;
	private String _promoType;
	private String _promoCode;
	private double _discount;
	private Date _startDate;
	private Date _endDate;
	private String _activeDay;
	private String _limit;
	private String _network;
	private String _channel;
	private int _isB2C;
	private int _isB2B2C;
	private int _isB2B;
	private String _payment;
	private String _birthdayMonth;
	private String _remarks;
	private long _mypageUserId;
	private String _agentName;
	private String _deptoreCode;
	private String _commission;
	private String _plan_;
	private String _promoCodeTerms;
	private String _travellerType;
	private String _utmId;
	private String _paymentChannelId;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<MasterPromoCode, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterPromoCode)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("promoCodeId", _promoCodeId);
		_columnOriginalValues.put("isDefault", _isDefault);
		_columnOriginalValues.put("productCode", _productCode);
		_columnOriginalValues.put("productName", _productName);
		_columnOriginalValues.put("promoType", _promoType);
		_columnOriginalValues.put("promoCode", _promoCode);
		_columnOriginalValues.put("discount", _discount);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("activeDay", _activeDay);
		_columnOriginalValues.put("limit_", _limit);
		_columnOriginalValues.put("network", _network);
		_columnOriginalValues.put("channel", _channel);
		_columnOriginalValues.put("isB2C", _isB2C);
		_columnOriginalValues.put("isB2B2C", _isB2B2C);
		_columnOriginalValues.put("isB2B", _isB2B);
		_columnOriginalValues.put("payment", _payment);
		_columnOriginalValues.put("birthdayMonth", _birthdayMonth);
		_columnOriginalValues.put("remarks", _remarks);
		_columnOriginalValues.put("mypageUserId", _mypageUserId);
		_columnOriginalValues.put("agentName", _agentName);
		_columnOriginalValues.put("deptoreCode", _deptoreCode);
		_columnOriginalValues.put("commission", _commission);
		_columnOriginalValues.put("plan_", _plan_);
		_columnOriginalValues.put("promoCodeTerms", _promoCodeTerms);
		_columnOriginalValues.put("travellerType", _travellerType);
		_columnOriginalValues.put("utmId", _utmId);
		_columnOriginalValues.put("paymentChannelId", _paymentChannelId);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("limit_", "limit");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("promoCodeId", 1L);

		columnBitmasks.put("isDefault", 2L);

		columnBitmasks.put("productCode", 4L);

		columnBitmasks.put("productName", 8L);

		columnBitmasks.put("promoType", 16L);

		columnBitmasks.put("promoCode", 32L);

		columnBitmasks.put("discount", 64L);

		columnBitmasks.put("startDate", 128L);

		columnBitmasks.put("endDate", 256L);

		columnBitmasks.put("activeDay", 512L);

		columnBitmasks.put("limit_", 1024L);

		columnBitmasks.put("network", 2048L);

		columnBitmasks.put("channel", 4096L);

		columnBitmasks.put("isB2C", 8192L);

		columnBitmasks.put("isB2B2C", 16384L);

		columnBitmasks.put("isB2B", 32768L);

		columnBitmasks.put("payment", 65536L);

		columnBitmasks.put("birthdayMonth", 131072L);

		columnBitmasks.put("remarks", 262144L);

		columnBitmasks.put("mypageUserId", 524288L);

		columnBitmasks.put("agentName", 1048576L);

		columnBitmasks.put("deptoreCode", 2097152L);

		columnBitmasks.put("commission", 4194304L);

		columnBitmasks.put("plan_", 8388608L);

		columnBitmasks.put("promoCodeTerms", 16777216L);

		columnBitmasks.put("travellerType", 33554432L);

		columnBitmasks.put("utmId", 67108864L);

		columnBitmasks.put("paymentChannelId", 134217728L);

		columnBitmasks.put("active_", 268435456L);

		columnBitmasks.put("groupId", 536870912L);

		columnBitmasks.put("companyId", 1073741824L);

		columnBitmasks.put("userId", 2147483648L);

		columnBitmasks.put("userName", 4294967296L);

		columnBitmasks.put("createDate", 8589934592L);

		columnBitmasks.put("modifiedDate", 17179869184L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterPromoCode _escapedModel;

}