/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.mypage.admin.product.model.PetPlan;
import com.mypage.admin.product.model.PetPlanModel;
import com.mypage.admin.product.model.PetPlanSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PetPlan service. Represents a row in the &quot;PetPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PetPlanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PetPlanImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see PetPlanImpl
 * @generated
 */
@JSON(strict = true)
public class PetPlanModelImpl
	extends BaseModelImpl<PetPlan> implements PetPlanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pet plan model instance should use the <code>PetPlan</code> interface instead.
	 */
	public static final String TABLE_NAME = "PetPlan";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"petPlanId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"limitDisability", Types.BIGINT},
		{"limitMedical", Types.BIGINT}, {"limitThirdParty", Types.BIGINT},
		{"limitCustody", Types.BIGINT}, {"recommended", Types.INTEGER},
		{"customPlan", Types.INTEGER}, {"benefit", Types.VARCHAR},
		{"pimcorePlanId", Types.BIGINT}, {"active_", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petPlanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("limitDisability", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("limitMedical", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("limitThirdParty", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("limitCustody", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("recommended", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("customPlan", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("benefit", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pimcorePlanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PetPlan (uuid_ VARCHAR(75) null,petPlanId LONG not null primary key,name VARCHAR(75) null,limitDisability LONG,limitMedical LONG,limitThirdParty LONG,limitCustody LONG,recommended INTEGER,customPlan INTEGER,benefit VARCHAR(75) null,pimcorePlanId LONG,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table PetPlan";

	public static final String ORDER_BY_JPQL = " ORDER BY petPlan.name DESC";

	public static final String ORDER_BY_SQL = " ORDER BY PetPlan.name DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PETPLANID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RECOMMENDED_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static PetPlan toModel(PetPlanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PetPlan model = new PetPlanImpl();

		model.setUuid(soapModel.getUuid());
		model.setPetPlanId(soapModel.getPetPlanId());
		model.setName(soapModel.getName());
		model.setLimitDisability(soapModel.getLimitDisability());
		model.setLimitMedical(soapModel.getLimitMedical());
		model.setLimitThirdParty(soapModel.getLimitThirdParty());
		model.setLimitCustody(soapModel.getLimitCustody());
		model.setRecommended(soapModel.getRecommended());
		model.setCustomPlan(soapModel.getCustomPlan());
		model.setBenefit(soapModel.getBenefit());
		model.setPimcorePlanId(soapModel.getPimcorePlanId());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<PetPlan> toModels(PetPlanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PetPlan> models = new ArrayList<PetPlan>(soapModels.length);

		for (PetPlanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PetPlanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _petPlanId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPetPlanId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _petPlanId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PetPlan.class;
	}

	@Override
	public String getModelClassName() {
		return PetPlan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PetPlan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PetPlan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PetPlan, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((PetPlan)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PetPlan, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PetPlan, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PetPlan)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PetPlan, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PetPlan, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<PetPlan, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PetPlan, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PetPlan, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PetPlan, Object>>();
		Map<String, BiConsumer<PetPlan, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PetPlan, ?>>();

		attributeGetterFunctions.put("uuid", PetPlan::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<PetPlan, String>)PetPlan::setUuid);
		attributeGetterFunctions.put("petPlanId", PetPlan::getPetPlanId);
		attributeSetterBiConsumers.put(
			"petPlanId", (BiConsumer<PetPlan, Long>)PetPlan::setPetPlanId);
		attributeGetterFunctions.put("name", PetPlan::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<PetPlan, String>)PetPlan::setName);
		attributeGetterFunctions.put(
			"limitDisability", PetPlan::getLimitDisability);
		attributeSetterBiConsumers.put(
			"limitDisability",
			(BiConsumer<PetPlan, Long>)PetPlan::setLimitDisability);
		attributeGetterFunctions.put("limitMedical", PetPlan::getLimitMedical);
		attributeSetterBiConsumers.put(
			"limitMedical",
			(BiConsumer<PetPlan, Long>)PetPlan::setLimitMedical);
		attributeGetterFunctions.put(
			"limitThirdParty", PetPlan::getLimitThirdParty);
		attributeSetterBiConsumers.put(
			"limitThirdParty",
			(BiConsumer<PetPlan, Long>)PetPlan::setLimitThirdParty);
		attributeGetterFunctions.put("limitCustody", PetPlan::getLimitCustody);
		attributeSetterBiConsumers.put(
			"limitCustody",
			(BiConsumer<PetPlan, Long>)PetPlan::setLimitCustody);
		attributeGetterFunctions.put("recommended", PetPlan::getRecommended);
		attributeSetterBiConsumers.put(
			"recommended",
			(BiConsumer<PetPlan, Integer>)PetPlan::setRecommended);
		attributeGetterFunctions.put("customPlan", PetPlan::getCustomPlan);
		attributeSetterBiConsumers.put(
			"customPlan", (BiConsumer<PetPlan, Integer>)PetPlan::setCustomPlan);
		attributeGetterFunctions.put("benefit", PetPlan::getBenefit);
		attributeSetterBiConsumers.put(
			"benefit", (BiConsumer<PetPlan, String>)PetPlan::setBenefit);
		attributeGetterFunctions.put(
			"pimcorePlanId", PetPlan::getPimcorePlanId);
		attributeSetterBiConsumers.put(
			"pimcorePlanId",
			(BiConsumer<PetPlan, Long>)PetPlan::setPimcorePlanId);
		attributeGetterFunctions.put("active", PetPlan::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<PetPlan, Integer>)PetPlan::setActive);
		attributeGetterFunctions.put("groupId", PetPlan::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<PetPlan, Long>)PetPlan::setGroupId);
		attributeGetterFunctions.put("companyId", PetPlan::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<PetPlan, Long>)PetPlan::setCompanyId);
		attributeGetterFunctions.put("userId", PetPlan::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<PetPlan, Long>)PetPlan::setUserId);
		attributeGetterFunctions.put("userName", PetPlan::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<PetPlan, String>)PetPlan::setUserName);
		attributeGetterFunctions.put("createDate", PetPlan::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<PetPlan, Date>)PetPlan::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", PetPlan::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<PetPlan, Date>)PetPlan::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPetPlanId() {
		return _petPlanId;
	}

	@Override
	public void setPetPlanId(long petPlanId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petPlanId = petPlanId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPetPlanId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("petPlanId"));
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public long getLimitDisability() {
		return _limitDisability;
	}

	@Override
	public void setLimitDisability(long limitDisability) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_limitDisability = limitDisability;
	}

	@JSON
	@Override
	public long getLimitMedical() {
		return _limitMedical;
	}

	@Override
	public void setLimitMedical(long limitMedical) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_limitMedical = limitMedical;
	}

	@JSON
	@Override
	public long getLimitThirdParty() {
		return _limitThirdParty;
	}

	@Override
	public void setLimitThirdParty(long limitThirdParty) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_limitThirdParty = limitThirdParty;
	}

	@JSON
	@Override
	public long getLimitCustody() {
		return _limitCustody;
	}

	@Override
	public void setLimitCustody(long limitCustody) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_limitCustody = limitCustody;
	}

	@JSON
	@Override
	public int getRecommended() {
		return _recommended;
	}

	@Override
	public void setRecommended(int recommended) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recommended = recommended;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalRecommended() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("recommended"));
	}

	@JSON
	@Override
	public int getCustomPlan() {
		return _customPlan;
	}

	@Override
	public void setCustomPlan(int customPlan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customPlan = customPlan;
	}

	@JSON
	@Override
	public String getBenefit() {
		if (_benefit == null) {
			return "";
		}
		else {
			return _benefit;
		}
	}

	@Override
	public void setBenefit(String benefit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefit = benefit;
	}

	@JSON
	@Override
	public long getPimcorePlanId() {
		return _pimcorePlanId;
	}

	@Override
	public void setPimcorePlanId(long pimcorePlanId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pimcorePlanId = pimcorePlanId;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(PetPlan.class.getName()));
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PetPlan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PetPlan toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PetPlan>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PetPlanImpl petPlanImpl = new PetPlanImpl();

		petPlanImpl.setUuid(getUuid());
		petPlanImpl.setPetPlanId(getPetPlanId());
		petPlanImpl.setName(getName());
		petPlanImpl.setLimitDisability(getLimitDisability());
		petPlanImpl.setLimitMedical(getLimitMedical());
		petPlanImpl.setLimitThirdParty(getLimitThirdParty());
		petPlanImpl.setLimitCustody(getLimitCustody());
		petPlanImpl.setRecommended(getRecommended());
		petPlanImpl.setCustomPlan(getCustomPlan());
		petPlanImpl.setBenefit(getBenefit());
		petPlanImpl.setPimcorePlanId(getPimcorePlanId());
		petPlanImpl.setActive(getActive());
		petPlanImpl.setGroupId(getGroupId());
		petPlanImpl.setCompanyId(getCompanyId());
		petPlanImpl.setUserId(getUserId());
		petPlanImpl.setUserName(getUserName());
		petPlanImpl.setCreateDate(getCreateDate());
		petPlanImpl.setModifiedDate(getModifiedDate());

		petPlanImpl.resetOriginalValues();

		return petPlanImpl;
	}

	@Override
	public int compareTo(PetPlan petPlan) {
		int value = 0;

		value = getName().compareTo(petPlan.getName());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PetPlan)) {
			return false;
		}

		PetPlan petPlan = (PetPlan)object;

		long primaryKey = petPlan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PetPlan> toCacheModel() {
		PetPlanCacheModel petPlanCacheModel = new PetPlanCacheModel();

		petPlanCacheModel.uuid = getUuid();

		String uuid = petPlanCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			petPlanCacheModel.uuid = null;
		}

		petPlanCacheModel.petPlanId = getPetPlanId();

		petPlanCacheModel.name = getName();

		String name = petPlanCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			petPlanCacheModel.name = null;
		}

		petPlanCacheModel.limitDisability = getLimitDisability();

		petPlanCacheModel.limitMedical = getLimitMedical();

		petPlanCacheModel.limitThirdParty = getLimitThirdParty();

		petPlanCacheModel.limitCustody = getLimitCustody();

		petPlanCacheModel.recommended = getRecommended();

		petPlanCacheModel.customPlan = getCustomPlan();

		petPlanCacheModel.benefit = getBenefit();

		String benefit = petPlanCacheModel.benefit;

		if ((benefit != null) && (benefit.length() == 0)) {
			petPlanCacheModel.benefit = null;
		}

		petPlanCacheModel.pimcorePlanId = getPimcorePlanId();

		petPlanCacheModel.active = getActive();

		petPlanCacheModel.groupId = getGroupId();

		petPlanCacheModel.companyId = getCompanyId();

		petPlanCacheModel.userId = getUserId();

		petPlanCacheModel.userName = getUserName();

		String userName = petPlanCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			petPlanCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			petPlanCacheModel.createDate = createDate.getTime();
		}
		else {
			petPlanCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			petPlanCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			petPlanCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return petPlanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PetPlan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PetPlan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PetPlan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PetPlan)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PetPlan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PetPlan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PetPlan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PetPlan)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PetPlan>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PetPlan.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _petPlanId;
	private String _name;
	private long _limitDisability;
	private long _limitMedical;
	private long _limitThirdParty;
	private long _limitCustody;
	private int _recommended;
	private int _customPlan;
	private String _benefit;
	private long _pimcorePlanId;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PetPlan, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PetPlan)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("petPlanId", _petPlanId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("limitDisability", _limitDisability);
		_columnOriginalValues.put("limitMedical", _limitMedical);
		_columnOriginalValues.put("limitThirdParty", _limitThirdParty);
		_columnOriginalValues.put("limitCustody", _limitCustody);
		_columnOriginalValues.put("recommended", _recommended);
		_columnOriginalValues.put("customPlan", _customPlan);
		_columnOriginalValues.put("benefit", _benefit);
		_columnOriginalValues.put("pimcorePlanId", _pimcorePlanId);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("petPlanId", 2L);

		columnBitmasks.put("name", 4L);

		columnBitmasks.put("limitDisability", 8L);

		columnBitmasks.put("limitMedical", 16L);

		columnBitmasks.put("limitThirdParty", 32L);

		columnBitmasks.put("limitCustody", 64L);

		columnBitmasks.put("recommended", 128L);

		columnBitmasks.put("customPlan", 256L);

		columnBitmasks.put("benefit", 512L);

		columnBitmasks.put("pimcorePlanId", 1024L);

		columnBitmasks.put("active_", 2048L);

		columnBitmasks.put("groupId", 4096L);

		columnBitmasks.put("companyId", 8192L);

		columnBitmasks.put("userId", 16384L);

		columnBitmasks.put("userName", 32768L);

		columnBitmasks.put("createDate", 65536L);

		columnBitmasks.put("modifiedDate", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PetPlan _escapedModel;

}