/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.Plan;
import com.mypage.admin.product.model.PlanModel;
import com.mypage.admin.product.model.PlanSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Plan service. Represents a row in the &quot;Plan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PlanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlanImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see PlanImpl
 * @generated
 */
@JSON(strict = true)
public class PlanModelImpl extends BaseModelImpl<Plan> implements PlanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a plan model instance should use the <code>Plan</code> interface instead.
	 */
	public static final String TABLE_NAME = "Plan";

	public static final Object[][] TABLE_COLUMNS = {
		{"planId", Types.BIGINT}, {"nameId", Types.VARCHAR},
		{"nameEn", Types.VARCHAR}, {"sort", Types.INTEGER},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("planId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nameId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nameEn", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sort", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Plan (planId LONG not null primary key,nameId VARCHAR(75) null,nameEn VARCHAR(75) null,sort INTEGER,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Plan";

	public static final String ORDER_BY_JPQL = " ORDER BY plan.planId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Plan.planId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLANID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Plan toModel(PlanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Plan model = new PlanImpl();

		model.setPlanId(soapModel.getPlanId());
		model.setNameId(soapModel.getNameId());
		model.setNameEn(soapModel.getNameEn());
		model.setSort(soapModel.getSort());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Plan> toModels(PlanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Plan> models = new ArrayList<Plan>(soapModels.length);

		for (PlanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PlanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _planId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPlanId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _planId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Plan.class;
	}

	@Override
	public String getModelClassName() {
		return Plan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Plan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Plan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Plan, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Plan)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Plan, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Plan, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Plan)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Plan, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Plan, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Plan, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Plan, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Plan, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Plan, Object>>();
		Map<String, BiConsumer<Plan, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Plan, ?>>();

		attributeGetterFunctions.put("planId", Plan::getPlanId);
		attributeSetterBiConsumers.put(
			"planId", (BiConsumer<Plan, Long>)Plan::setPlanId);
		attributeGetterFunctions.put("nameId", Plan::getNameId);
		attributeSetterBiConsumers.put(
			"nameId", (BiConsumer<Plan, String>)Plan::setNameId);
		attributeGetterFunctions.put("nameEn", Plan::getNameEn);
		attributeSetterBiConsumers.put(
			"nameEn", (BiConsumer<Plan, String>)Plan::setNameEn);
		attributeGetterFunctions.put("sort", Plan::getSort);
		attributeSetterBiConsumers.put(
			"sort", (BiConsumer<Plan, Integer>)Plan::setSort);
		attributeGetterFunctions.put("active", Plan::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<Plan, Integer>)Plan::setActive);
		attributeGetterFunctions.put("groupId", Plan::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Plan, Long>)Plan::setGroupId);
		attributeGetterFunctions.put("companyId", Plan::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Plan, Long>)Plan::setCompanyId);
		attributeGetterFunctions.put("userId", Plan::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Plan, Long>)Plan::setUserId);
		attributeGetterFunctions.put("userName", Plan::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Plan, String>)Plan::setUserName);
		attributeGetterFunctions.put("createDate", Plan::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Plan, Date>)Plan::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Plan::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Plan, Date>)Plan::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPlanId() {
		return _planId;
	}

	@Override
	public void setPlanId(long planId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planId = planId;
	}

	@JSON
	@Override
	public String getNameId() {
		if (_nameId == null) {
			return "";
		}
		else {
			return _nameId;
		}
	}

	@Override
	public void setNameId(String nameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameId = nameId;
	}

	@JSON
	@Override
	public String getNameEn() {
		if (_nameEn == null) {
			return "";
		}
		else {
			return _nameEn;
		}
	}

	@Override
	public void setNameEn(String nameEn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameEn = nameEn;
	}

	@JSON
	@Override
	public int getSort() {
		return _sort;
	}

	@Override
	public void setSort(int sort) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sort = sort;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Plan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Plan toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Plan>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PlanImpl planImpl = new PlanImpl();

		planImpl.setPlanId(getPlanId());
		planImpl.setNameId(getNameId());
		planImpl.setNameEn(getNameEn());
		planImpl.setSort(getSort());
		planImpl.setActive(getActive());
		planImpl.setGroupId(getGroupId());
		planImpl.setCompanyId(getCompanyId());
		planImpl.setUserId(getUserId());
		planImpl.setUserName(getUserName());
		planImpl.setCreateDate(getCreateDate());
		planImpl.setModifiedDate(getModifiedDate());

		planImpl.resetOriginalValues();

		return planImpl;
	}

	@Override
	public int compareTo(Plan plan) {
		long primaryKey = plan.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Plan)) {
			return false;
		}

		Plan plan = (Plan)object;

		long primaryKey = plan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Plan> toCacheModel() {
		PlanCacheModel planCacheModel = new PlanCacheModel();

		planCacheModel.planId = getPlanId();

		planCacheModel.nameId = getNameId();

		String nameId = planCacheModel.nameId;

		if ((nameId != null) && (nameId.length() == 0)) {
			planCacheModel.nameId = null;
		}

		planCacheModel.nameEn = getNameEn();

		String nameEn = planCacheModel.nameEn;

		if ((nameEn != null) && (nameEn.length() == 0)) {
			planCacheModel.nameEn = null;
		}

		planCacheModel.sort = getSort();

		planCacheModel.active = getActive();

		planCacheModel.groupId = getGroupId();

		planCacheModel.companyId = getCompanyId();

		planCacheModel.userId = getUserId();

		planCacheModel.userName = getUserName();

		String userName = planCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			planCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			planCacheModel.createDate = createDate.getTime();
		}
		else {
			planCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			planCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			planCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return planCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Plan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Plan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Plan, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Plan)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Plan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Plan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Plan, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Plan)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Plan>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Plan.class, ModelWrapper.class);

	}

	private long _planId;
	private String _nameId;
	private String _nameEn;
	private int _sort;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Plan, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Plan)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("planId", _planId);
		_columnOriginalValues.put("nameId", _nameId);
		_columnOriginalValues.put("nameEn", _nameEn);
		_columnOriginalValues.put("sort", _sort);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("planId", 1L);

		columnBitmasks.put("nameId", 2L);

		columnBitmasks.put("nameEn", 4L);

		columnBitmasks.put("sort", 8L);

		columnBitmasks.put("active_", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Plan _escapedModel;

}