/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.Premi;
import com.mypage.admin.product.model.PremiModel;
import com.mypage.admin.product.model.PremiSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Premi service. Represents a row in the &quot;Premi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PremiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PremiImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see PremiImpl
 * @generated
 */
@JSON(strict = true)
public class PremiModelImpl extends BaseModelImpl<Premi> implements PremiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a premi model instance should use the <code>Premi</code> interface instead.
	 */
	public static final String TABLE_NAME = "Premi";

	public static final Object[][] TABLE_COLUMNS = {
		{"premiId", Types.BIGINT}, {"travellerType", Types.VARCHAR},
		{"currency_", Types.VARCHAR}, {"basic", Types.DECIMAL},
		{"additional", Types.DECIMAL}, {"annual", Types.DECIMAL},
		{"active_", Types.INTEGER}, {"benefitId", Types.BIGINT},
		{"planId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("premiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("travellerType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("currency_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("basic", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("additional", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("annual", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("benefitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("planId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Premi (premiId LONG not null primary key,travellerType VARCHAR(75) null,currency_ VARCHAR(75) null,basic DECIMAL(30, 16) null,additional DECIMAL(30, 16) null,annual DECIMAL(30, 16) null,active_ INTEGER,benefitId LONG,planId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Premi";

	public static final String ORDER_BY_JPQL = " ORDER BY premi.premiId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Premi.premiId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CURRENCY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAVELLERTYPE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PREMIID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Premi toModel(PremiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Premi model = new PremiImpl();

		model.setPremiId(soapModel.getPremiId());
		model.setTravellerType(soapModel.getTravellerType());
		model.setCurrency(soapModel.getCurrency());
		model.setBasic(soapModel.getBasic());
		model.setAdditional(soapModel.getAdditional());
		model.setAnnual(soapModel.getAnnual());
		model.setActive(soapModel.getActive());
		model.setBenefitId(soapModel.getBenefitId());
		model.setPlanId(soapModel.getPlanId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Premi> toModels(PremiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Premi> models = new ArrayList<Premi>(soapModels.length);

		for (PremiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PremiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _premiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPremiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _premiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Premi.class;
	}

	@Override
	public String getModelClassName() {
		return Premi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Premi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Premi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Premi, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Premi)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Premi, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Premi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Premi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Premi, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Premi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Premi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Premi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Premi, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Premi, Object>>();
		Map<String, BiConsumer<Premi, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Premi, ?>>();

		attributeGetterFunctions.put("premiId", Premi::getPremiId);
		attributeSetterBiConsumers.put(
			"premiId", (BiConsumer<Premi, Long>)Premi::setPremiId);
		attributeGetterFunctions.put("travellerType", Premi::getTravellerType);
		attributeSetterBiConsumers.put(
			"travellerType",
			(BiConsumer<Premi, String>)Premi::setTravellerType);
		attributeGetterFunctions.put("currency", Premi::getCurrency);
		attributeSetterBiConsumers.put(
			"currency", (BiConsumer<Premi, String>)Premi::setCurrency);
		attributeGetterFunctions.put("basic", Premi::getBasic);
		attributeSetterBiConsumers.put(
			"basic", (BiConsumer<Premi, BigDecimal>)Premi::setBasic);
		attributeGetterFunctions.put("additional", Premi::getAdditional);
		attributeSetterBiConsumers.put(
			"additional", (BiConsumer<Premi, BigDecimal>)Premi::setAdditional);
		attributeGetterFunctions.put("annual", Premi::getAnnual);
		attributeSetterBiConsumers.put(
			"annual", (BiConsumer<Premi, BigDecimal>)Premi::setAnnual);
		attributeGetterFunctions.put("active", Premi::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<Premi, Integer>)Premi::setActive);
		attributeGetterFunctions.put("benefitId", Premi::getBenefitId);
		attributeSetterBiConsumers.put(
			"benefitId", (BiConsumer<Premi, Long>)Premi::setBenefitId);
		attributeGetterFunctions.put("planId", Premi::getPlanId);
		attributeSetterBiConsumers.put(
			"planId", (BiConsumer<Premi, Long>)Premi::setPlanId);
		attributeGetterFunctions.put("groupId", Premi::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Premi, Long>)Premi::setGroupId);
		attributeGetterFunctions.put("companyId", Premi::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Premi, Long>)Premi::setCompanyId);
		attributeGetterFunctions.put("userId", Premi::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Premi, Long>)Premi::setUserId);
		attributeGetterFunctions.put("userName", Premi::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Premi, String>)Premi::setUserName);
		attributeGetterFunctions.put("createDate", Premi::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Premi, Date>)Premi::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Premi::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Premi, Date>)Premi::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPremiId() {
		return _premiId;
	}

	@Override
	public void setPremiId(long premiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_premiId = premiId;
	}

	@JSON
	@Override
	public String getTravellerType() {
		if (_travellerType == null) {
			return "";
		}
		else {
			return _travellerType;
		}
	}

	@Override
	public void setTravellerType(String travellerType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travellerType = travellerType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTravellerType() {
		return getColumnOriginalValue("travellerType");
	}

	@JSON
	@Override
	public String getCurrency() {
		if (_currency == null) {
			return "";
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currency = currency;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCurrency() {
		return getColumnOriginalValue("currency_");
	}

	@JSON
	@Override
	public BigDecimal getBasic() {
		return _basic;
	}

	@Override
	public void setBasic(BigDecimal basic) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_basic = basic;
	}

	@JSON
	@Override
	public BigDecimal getAdditional() {
		return _additional;
	}

	@Override
	public void setAdditional(BigDecimal additional) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_additional = additional;
	}

	@JSON
	@Override
	public BigDecimal getAnnual() {
		return _annual;
	}

	@Override
	public void setAnnual(BigDecimal annual) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annual = annual;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getBenefitId() {
		return _benefitId;
	}

	@Override
	public void setBenefitId(long benefitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitId = benefitId;
	}

	@JSON
	@Override
	public long getPlanId() {
		return _planId;
	}

	@Override
	public void setPlanId(long planId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planId = planId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Premi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Premi toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Premi>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PremiImpl premiImpl = new PremiImpl();

		premiImpl.setPremiId(getPremiId());
		premiImpl.setTravellerType(getTravellerType());
		premiImpl.setCurrency(getCurrency());
		premiImpl.setBasic(getBasic());
		premiImpl.setAdditional(getAdditional());
		premiImpl.setAnnual(getAnnual());
		premiImpl.setActive(getActive());
		premiImpl.setBenefitId(getBenefitId());
		premiImpl.setPlanId(getPlanId());
		premiImpl.setGroupId(getGroupId());
		premiImpl.setCompanyId(getCompanyId());
		premiImpl.setUserId(getUserId());
		premiImpl.setUserName(getUserName());
		premiImpl.setCreateDate(getCreateDate());
		premiImpl.setModifiedDate(getModifiedDate());

		premiImpl.resetOriginalValues();

		return premiImpl;
	}

	@Override
	public int compareTo(Premi premi) {
		long primaryKey = premi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Premi)) {
			return false;
		}

		Premi premi = (Premi)object;

		long primaryKey = premi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Premi> toCacheModel() {
		PremiCacheModel premiCacheModel = new PremiCacheModel();

		premiCacheModel.premiId = getPremiId();

		premiCacheModel.travellerType = getTravellerType();

		String travellerType = premiCacheModel.travellerType;

		if ((travellerType != null) && (travellerType.length() == 0)) {
			premiCacheModel.travellerType = null;
		}

		premiCacheModel.currency = getCurrency();

		String currency = premiCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			premiCacheModel.currency = null;
		}

		premiCacheModel.basic = getBasic();

		premiCacheModel.additional = getAdditional();

		premiCacheModel.annual = getAnnual();

		premiCacheModel.active = getActive();

		premiCacheModel.benefitId = getBenefitId();

		premiCacheModel.planId = getPlanId();

		premiCacheModel.groupId = getGroupId();

		premiCacheModel.companyId = getCompanyId();

		premiCacheModel.userId = getUserId();

		premiCacheModel.userName = getUserName();

		String userName = premiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			premiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			premiCacheModel.createDate = createDate.getTime();
		}
		else {
			premiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			premiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			premiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return premiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Premi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Premi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Premi, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Premi)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Premi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Premi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Premi, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Premi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Premi>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Premi.class, ModelWrapper.class);

	}

	private long _premiId;
	private String _travellerType;
	private String _currency;
	private BigDecimal _basic;
	private BigDecimal _additional;
	private BigDecimal _annual;
	private int _active;
	private long _benefitId;
	private long _planId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Premi, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Premi)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("premiId", _premiId);
		_columnOriginalValues.put("travellerType", _travellerType);
		_columnOriginalValues.put("currency_", _currency);
		_columnOriginalValues.put("basic", _basic);
		_columnOriginalValues.put("additional", _additional);
		_columnOriginalValues.put("annual", _annual);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("benefitId", _benefitId);
		_columnOriginalValues.put("planId", _planId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("currency_", "currency");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("premiId", 1L);

		columnBitmasks.put("travellerType", 2L);

		columnBitmasks.put("currency_", 4L);

		columnBitmasks.put("basic", 8L);

		columnBitmasks.put("additional", 16L);

		columnBitmasks.put("annual", 32L);

		columnBitmasks.put("active_", 64L);

		columnBitmasks.put("benefitId", 128L);

		columnBitmasks.put("planId", 256L);

		columnBitmasks.put("groupId", 512L);

		columnBitmasks.put("companyId", 1024L);

		columnBitmasks.put("userId", 2048L);

		columnBitmasks.put("userName", 4096L);

		columnBitmasks.put("createDate", 8192L);

		columnBitmasks.put("modifiedDate", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Premi _escapedModel;

}