/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.SmartTravelIntLink;
import com.mypage.admin.product.model.SmartTravelIntLinkModel;
import com.mypage.admin.product.model.SmartTravelIntLinkSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmartTravelIntLink service. Represents a row in the &quot;SmartTravelIntLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SmartTravelIntLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmartTravelIntLinkImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see SmartTravelIntLinkImpl
 * @generated
 */
@JSON(strict = true)
public class SmartTravelIntLinkModelImpl
	extends BaseModelImpl<SmartTravelIntLink>
	implements SmartTravelIntLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a smart travel int link model instance should use the <code>SmartTravelIntLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "SmartTravelIntLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"smartTravelIntLinkId", Types.BIGINT}, {"linkType", Types.VARCHAR},
		{"linkTitle", Types.VARCHAR}, {"linkHref", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("smartTravelIntLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("linkType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkHref", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SmartTravelIntLink (smartTravelIntLinkId LONG not null primary key,linkType VARCHAR(75) null,linkTitle VARCHAR(75) null,linkHref VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table SmartTravelIntLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smartTravelIntLink.smartTravelIntLinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SmartTravelIntLink.smartTravelIntLinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LINKTYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTTRAVELINTLINKID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SmartTravelIntLink toModel(SmartTravelIntLinkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SmartTravelIntLink model = new SmartTravelIntLinkImpl();

		model.setSmartTravelIntLinkId(soapModel.getSmartTravelIntLinkId());
		model.setLinkType(soapModel.getLinkType());
		model.setLinkTitle(soapModel.getLinkTitle());
		model.setLinkHref(soapModel.getLinkHref());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SmartTravelIntLink> toModels(
		SmartTravelIntLinkSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmartTravelIntLink> models = new ArrayList<SmartTravelIntLink>(
			soapModels.length);

		for (SmartTravelIntLinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SmartTravelIntLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _smartTravelIntLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSmartTravelIntLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _smartTravelIntLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SmartTravelIntLink.class;
	}

	@Override
	public String getModelClassName() {
		return SmartTravelIntLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmartTravelIntLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmartTravelIntLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartTravelIntLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SmartTravelIntLink)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmartTravelIntLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmartTravelIntLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmartTravelIntLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmartTravelIntLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmartTravelIntLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SmartTravelIntLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SmartTravelIntLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmartTravelIntLink, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SmartTravelIntLink, Object>>();
		Map<String, BiConsumer<SmartTravelIntLink, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SmartTravelIntLink, ?>>();

		attributeGetterFunctions.put(
			"smartTravelIntLinkId",
			SmartTravelIntLink::getSmartTravelIntLinkId);
		attributeSetterBiConsumers.put(
			"smartTravelIntLinkId",
			(BiConsumer<SmartTravelIntLink, Long>)
				SmartTravelIntLink::setSmartTravelIntLinkId);
		attributeGetterFunctions.put(
			"linkType", SmartTravelIntLink::getLinkType);
		attributeSetterBiConsumers.put(
			"linkType",
			(BiConsumer<SmartTravelIntLink, String>)
				SmartTravelIntLink::setLinkType);
		attributeGetterFunctions.put(
			"linkTitle", SmartTravelIntLink::getLinkTitle);
		attributeSetterBiConsumers.put(
			"linkTitle",
			(BiConsumer<SmartTravelIntLink, String>)
				SmartTravelIntLink::setLinkTitle);
		attributeGetterFunctions.put(
			"linkHref", SmartTravelIntLink::getLinkHref);
		attributeSetterBiConsumers.put(
			"linkHref",
			(BiConsumer<SmartTravelIntLink, String>)
				SmartTravelIntLink::setLinkHref);
		attributeGetterFunctions.put("groupId", SmartTravelIntLink::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SmartTravelIntLink, Long>)
				SmartTravelIntLink::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SmartTravelIntLink::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SmartTravelIntLink, Long>)
				SmartTravelIntLink::setCompanyId);
		attributeGetterFunctions.put("userId", SmartTravelIntLink::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SmartTravelIntLink, Long>)
				SmartTravelIntLink::setUserId);
		attributeGetterFunctions.put(
			"userName", SmartTravelIntLink::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SmartTravelIntLink, String>)
				SmartTravelIntLink::setUserName);
		attributeGetterFunctions.put(
			"createDate", SmartTravelIntLink::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SmartTravelIntLink, Date>)
				SmartTravelIntLink::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SmartTravelIntLink::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SmartTravelIntLink, Date>)
				SmartTravelIntLink::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSmartTravelIntLinkId() {
		return _smartTravelIntLinkId;
	}

	@Override
	public void setSmartTravelIntLinkId(long smartTravelIntLinkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartTravelIntLinkId = smartTravelIntLinkId;
	}

	@JSON
	@Override
	public String getLinkType() {
		if (_linkType == null) {
			return "";
		}
		else {
			return _linkType;
		}
	}

	@Override
	public void setLinkType(String linkType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkType = linkType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLinkType() {
		return getColumnOriginalValue("linkType");
	}

	@JSON
	@Override
	public String getLinkTitle() {
		if (_linkTitle == null) {
			return "";
		}
		else {
			return _linkTitle;
		}
	}

	@Override
	public void setLinkTitle(String linkTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkTitle = linkTitle;
	}

	@JSON
	@Override
	public String getLinkHref() {
		if (_linkHref == null) {
			return "";
		}
		else {
			return _linkHref;
		}
	}

	@Override
	public void setLinkHref(String linkHref) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkHref = linkHref;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SmartTravelIntLink.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SmartTravelIntLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SmartTravelIntLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmartTravelIntLinkImpl smartTravelIntLinkImpl =
			new SmartTravelIntLinkImpl();

		smartTravelIntLinkImpl.setSmartTravelIntLinkId(
			getSmartTravelIntLinkId());
		smartTravelIntLinkImpl.setLinkType(getLinkType());
		smartTravelIntLinkImpl.setLinkTitle(getLinkTitle());
		smartTravelIntLinkImpl.setLinkHref(getLinkHref());
		smartTravelIntLinkImpl.setGroupId(getGroupId());
		smartTravelIntLinkImpl.setCompanyId(getCompanyId());
		smartTravelIntLinkImpl.setUserId(getUserId());
		smartTravelIntLinkImpl.setUserName(getUserName());
		smartTravelIntLinkImpl.setCreateDate(getCreateDate());
		smartTravelIntLinkImpl.setModifiedDate(getModifiedDate());

		smartTravelIntLinkImpl.resetOriginalValues();

		return smartTravelIntLinkImpl;
	}

	@Override
	public int compareTo(SmartTravelIntLink smartTravelIntLink) {
		long primaryKey = smartTravelIntLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SmartTravelIntLink)) {
			return false;
		}

		SmartTravelIntLink smartTravelIntLink = (SmartTravelIntLink)object;

		long primaryKey = smartTravelIntLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SmartTravelIntLink> toCacheModel() {
		SmartTravelIntLinkCacheModel smartTravelIntLinkCacheModel =
			new SmartTravelIntLinkCacheModel();

		smartTravelIntLinkCacheModel.smartTravelIntLinkId =
			getSmartTravelIntLinkId();

		smartTravelIntLinkCacheModel.linkType = getLinkType();

		String linkType = smartTravelIntLinkCacheModel.linkType;

		if ((linkType != null) && (linkType.length() == 0)) {
			smartTravelIntLinkCacheModel.linkType = null;
		}

		smartTravelIntLinkCacheModel.linkTitle = getLinkTitle();

		String linkTitle = smartTravelIntLinkCacheModel.linkTitle;

		if ((linkTitle != null) && (linkTitle.length() == 0)) {
			smartTravelIntLinkCacheModel.linkTitle = null;
		}

		smartTravelIntLinkCacheModel.linkHref = getLinkHref();

		String linkHref = smartTravelIntLinkCacheModel.linkHref;

		if ((linkHref != null) && (linkHref.length() == 0)) {
			smartTravelIntLinkCacheModel.linkHref = null;
		}

		smartTravelIntLinkCacheModel.groupId = getGroupId();

		smartTravelIntLinkCacheModel.companyId = getCompanyId();

		smartTravelIntLinkCacheModel.userId = getUserId();

		smartTravelIntLinkCacheModel.userName = getUserName();

		String userName = smartTravelIntLinkCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			smartTravelIntLinkCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			smartTravelIntLinkCacheModel.createDate = createDate.getTime();
		}
		else {
			smartTravelIntLinkCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			smartTravelIntLinkCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			smartTravelIntLinkCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return smartTravelIntLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmartTravelIntLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmartTravelIntLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartTravelIntLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SmartTravelIntLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmartTravelIntLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmartTravelIntLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartTravelIntLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SmartTravelIntLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SmartTravelIntLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SmartTravelIntLink.class, ModelWrapper.class);

	}

	private long _smartTravelIntLinkId;
	private String _linkType;
	private String _linkTitle;
	private String _linkHref;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<SmartTravelIntLink, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SmartTravelIntLink)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"smartTravelIntLinkId", _smartTravelIntLinkId);
		_columnOriginalValues.put("linkType", _linkType);
		_columnOriginalValues.put("linkTitle", _linkTitle);
		_columnOriginalValues.put("linkHref", _linkHref);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("smartTravelIntLinkId", 1L);

		columnBitmasks.put("linkType", 2L);

		columnBitmasks.put("linkTitle", 4L);

		columnBitmasks.put("linkHref", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SmartTravelIntLink _escapedModel;

}