/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.SmartHealthBenefit;
import com.mypage.admin.product.model.SmartHealthBenefitModel;
import com.mypage.admin.product.model.SmartHealthBenefitSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmartHealthBenefit service. Represents a row in the &quot;SmartHealthBenefit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SmartHealthBenefitModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmartHealthBenefitImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see SmartHealthBenefitImpl
 * @generated
 */
@JSON(strict = true)
public class SmartHealthBenefitModelImpl
	extends BaseModelImpl<SmartHealthBenefit>
	implements SmartHealthBenefitModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a smart health benefit model instance should use the <code>SmartHealthBenefit</code> interface instead.
	 */
	public static final String TABLE_NAME = "SmartHealthBenefit";

	public static final Object[][] TABLE_COLUMNS = {
		{"smartHealthBenefitId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"benefitTitle", Types.VARCHAR},
		{"benefitContent", Types.VARCHAR},
		{"smartHealthBenefitGroupId", Types.BIGINT},
		{"smartHealthPlanId", Types.BIGINT}, {"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("smartHealthBenefitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("benefitTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("benefitContent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("smartHealthBenefitGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("smartHealthPlanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SmartHealthBenefit (smartHealthBenefitId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,benefitTitle VARCHAR(75) null,benefitContent VARCHAR(75) null,smartHealthBenefitGroupId LONG,smartHealthPlanId LONG,active_ INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table SmartHealthBenefit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smartHealthBenefit.smartHealthBenefitId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SmartHealthBenefit.smartHealthBenefitId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTHEALTHPLANID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTHEALTHBENEFITID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SmartHealthBenefit toModel(SmartHealthBenefitSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SmartHealthBenefit model = new SmartHealthBenefitImpl();

		model.setSmartHealthBenefitId(soapModel.getSmartHealthBenefitId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setBenefitTitle(soapModel.getBenefitTitle());
		model.setBenefitContent(soapModel.getBenefitContent());
		model.setSmartHealthBenefitGroupId(
			soapModel.getSmartHealthBenefitGroupId());
		model.setSmartHealthPlanId(soapModel.getSmartHealthPlanId());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SmartHealthBenefit> toModels(
		SmartHealthBenefitSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmartHealthBenefit> models = new ArrayList<SmartHealthBenefit>(
			soapModels.length);

		for (SmartHealthBenefitSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SmartHealthBenefitModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _smartHealthBenefitId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSmartHealthBenefitId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _smartHealthBenefitId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SmartHealthBenefit.class;
	}

	@Override
	public String getModelClassName() {
		return SmartHealthBenefit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmartHealthBenefit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmartHealthBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartHealthBenefit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SmartHealthBenefit)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmartHealthBenefit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmartHealthBenefit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmartHealthBenefit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmartHealthBenefit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmartHealthBenefit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SmartHealthBenefit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SmartHealthBenefit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmartHealthBenefit, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SmartHealthBenefit, Object>>();
		Map<String, BiConsumer<SmartHealthBenefit, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SmartHealthBenefit, ?>>();

		attributeGetterFunctions.put(
			"smartHealthBenefitId",
			SmartHealthBenefit::getSmartHealthBenefitId);
		attributeSetterBiConsumers.put(
			"smartHealthBenefitId",
			(BiConsumer<SmartHealthBenefit, Long>)
				SmartHealthBenefit::setSmartHealthBenefitId);
		attributeGetterFunctions.put("groupId", SmartHealthBenefit::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SmartHealthBenefit, Long>)
				SmartHealthBenefit::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SmartHealthBenefit::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SmartHealthBenefit, Long>)
				SmartHealthBenefit::setCompanyId);
		attributeGetterFunctions.put("userId", SmartHealthBenefit::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SmartHealthBenefit, Long>)
				SmartHealthBenefit::setUserId);
		attributeGetterFunctions.put(
			"userName", SmartHealthBenefit::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SmartHealthBenefit, String>)
				SmartHealthBenefit::setUserName);
		attributeGetterFunctions.put(
			"createDate", SmartHealthBenefit::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SmartHealthBenefit, Date>)
				SmartHealthBenefit::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SmartHealthBenefit::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SmartHealthBenefit, Date>)
				SmartHealthBenefit::setModifiedDate);
		attributeGetterFunctions.put(
			"benefitTitle", SmartHealthBenefit::getBenefitTitle);
		attributeSetterBiConsumers.put(
			"benefitTitle",
			(BiConsumer<SmartHealthBenefit, String>)
				SmartHealthBenefit::setBenefitTitle);
		attributeGetterFunctions.put(
			"benefitContent", SmartHealthBenefit::getBenefitContent);
		attributeSetterBiConsumers.put(
			"benefitContent",
			(BiConsumer<SmartHealthBenefit, String>)
				SmartHealthBenefit::setBenefitContent);
		attributeGetterFunctions.put(
			"smartHealthBenefitGroupId",
			SmartHealthBenefit::getSmartHealthBenefitGroupId);
		attributeSetterBiConsumers.put(
			"smartHealthBenefitGroupId",
			(BiConsumer<SmartHealthBenefit, Long>)
				SmartHealthBenefit::setSmartHealthBenefitGroupId);
		attributeGetterFunctions.put(
			"smartHealthPlanId", SmartHealthBenefit::getSmartHealthPlanId);
		attributeSetterBiConsumers.put(
			"smartHealthPlanId",
			(BiConsumer<SmartHealthBenefit, Long>)
				SmartHealthBenefit::setSmartHealthPlanId);
		attributeGetterFunctions.put("active", SmartHealthBenefit::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<SmartHealthBenefit, Integer>)
				SmartHealthBenefit::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSmartHealthBenefitId() {
		return _smartHealthBenefitId;
	}

	@Override
	public void setSmartHealthBenefitId(long smartHealthBenefitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartHealthBenefitId = smartHealthBenefitId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getBenefitTitle() {
		if (_benefitTitle == null) {
			return "";
		}
		else {
			return _benefitTitle;
		}
	}

	@Override
	public void setBenefitTitle(String benefitTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitTitle = benefitTitle;
	}

	@JSON
	@Override
	public String getBenefitContent() {
		if (_benefitContent == null) {
			return "";
		}
		else {
			return _benefitContent;
		}
	}

	@Override
	public void setBenefitContent(String benefitContent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitContent = benefitContent;
	}

	@JSON
	@Override
	public long getSmartHealthBenefitGroupId() {
		return _smartHealthBenefitGroupId;
	}

	@Override
	public void setSmartHealthBenefitGroupId(long smartHealthBenefitGroupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartHealthBenefitGroupId = smartHealthBenefitGroupId;
	}

	@JSON
	@Override
	public long getSmartHealthPlanId() {
		return _smartHealthPlanId;
	}

	@Override
	public void setSmartHealthPlanId(long smartHealthPlanId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartHealthPlanId = smartHealthPlanId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSmartHealthPlanId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("smartHealthPlanId"));
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SmartHealthBenefit.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SmartHealthBenefit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SmartHealthBenefit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmartHealthBenefitImpl smartHealthBenefitImpl =
			new SmartHealthBenefitImpl();

		smartHealthBenefitImpl.setSmartHealthBenefitId(
			getSmartHealthBenefitId());
		smartHealthBenefitImpl.setGroupId(getGroupId());
		smartHealthBenefitImpl.setCompanyId(getCompanyId());
		smartHealthBenefitImpl.setUserId(getUserId());
		smartHealthBenefitImpl.setUserName(getUserName());
		smartHealthBenefitImpl.setCreateDate(getCreateDate());
		smartHealthBenefitImpl.setModifiedDate(getModifiedDate());
		smartHealthBenefitImpl.setBenefitTitle(getBenefitTitle());
		smartHealthBenefitImpl.setBenefitContent(getBenefitContent());
		smartHealthBenefitImpl.setSmartHealthBenefitGroupId(
			getSmartHealthBenefitGroupId());
		smartHealthBenefitImpl.setSmartHealthPlanId(getSmartHealthPlanId());
		smartHealthBenefitImpl.setActive(getActive());

		smartHealthBenefitImpl.resetOriginalValues();

		return smartHealthBenefitImpl;
	}

	@Override
	public int compareTo(SmartHealthBenefit smartHealthBenefit) {
		long primaryKey = smartHealthBenefit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SmartHealthBenefit)) {
			return false;
		}

		SmartHealthBenefit smartHealthBenefit = (SmartHealthBenefit)object;

		long primaryKey = smartHealthBenefit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SmartHealthBenefit> toCacheModel() {
		SmartHealthBenefitCacheModel smartHealthBenefitCacheModel =
			new SmartHealthBenefitCacheModel();

		smartHealthBenefitCacheModel.smartHealthBenefitId =
			getSmartHealthBenefitId();

		smartHealthBenefitCacheModel.groupId = getGroupId();

		smartHealthBenefitCacheModel.companyId = getCompanyId();

		smartHealthBenefitCacheModel.userId = getUserId();

		smartHealthBenefitCacheModel.userName = getUserName();

		String userName = smartHealthBenefitCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			smartHealthBenefitCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			smartHealthBenefitCacheModel.createDate = createDate.getTime();
		}
		else {
			smartHealthBenefitCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			smartHealthBenefitCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			smartHealthBenefitCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		smartHealthBenefitCacheModel.benefitTitle = getBenefitTitle();

		String benefitTitle = smartHealthBenefitCacheModel.benefitTitle;

		if ((benefitTitle != null) && (benefitTitle.length() == 0)) {
			smartHealthBenefitCacheModel.benefitTitle = null;
		}

		smartHealthBenefitCacheModel.benefitContent = getBenefitContent();

		String benefitContent = smartHealthBenefitCacheModel.benefitContent;

		if ((benefitContent != null) && (benefitContent.length() == 0)) {
			smartHealthBenefitCacheModel.benefitContent = null;
		}

		smartHealthBenefitCacheModel.smartHealthBenefitGroupId =
			getSmartHealthBenefitGroupId();

		smartHealthBenefitCacheModel.smartHealthPlanId = getSmartHealthPlanId();

		smartHealthBenefitCacheModel.active = getActive();

		return smartHealthBenefitCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmartHealthBenefit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmartHealthBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartHealthBenefit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SmartHealthBenefit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmartHealthBenefit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmartHealthBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartHealthBenefit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SmartHealthBenefit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SmartHealthBenefit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SmartHealthBenefit.class, ModelWrapper.class);

	}

	private long _smartHealthBenefitId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _benefitTitle;
	private String _benefitContent;
	private long _smartHealthBenefitGroupId;
	private long _smartHealthPlanId;
	private int _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SmartHealthBenefit, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SmartHealthBenefit)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"smartHealthBenefitId", _smartHealthBenefitId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("benefitTitle", _benefitTitle);
		_columnOriginalValues.put("benefitContent", _benefitContent);
		_columnOriginalValues.put(
			"smartHealthBenefitGroupId", _smartHealthBenefitGroupId);
		_columnOriginalValues.put("smartHealthPlanId", _smartHealthPlanId);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("smartHealthBenefitId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("benefitTitle", 128L);

		columnBitmasks.put("benefitContent", 256L);

		columnBitmasks.put("smartHealthBenefitGroupId", 512L);

		columnBitmasks.put("smartHealthPlanId", 1024L);

		columnBitmasks.put("active_", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SmartHealthBenefit _escapedModel;

}