/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.SmartActiveLink;
import com.mypage.admin.product.model.SmartActiveLinkModel;
import com.mypage.admin.product.model.SmartActiveLinkSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmartActiveLink service. Represents a row in the &quot;SmartActiveLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SmartActiveLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmartActiveLinkImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see SmartActiveLinkImpl
 * @generated
 */
@JSON(strict = true)
public class SmartActiveLinkModelImpl
	extends BaseModelImpl<SmartActiveLink> implements SmartActiveLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a smart active link model instance should use the <code>SmartActiveLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "SmartActiveLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"smartActiveLinkId", Types.BIGINT}, {"category", Types.VARCHAR},
		{"title", Types.VARCHAR}, {"fileUploadEntryId", Types.BIGINT},
		{"fileUploadUrl", Types.VARCHAR}, {"active_", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("smartActiveLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("category", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileUploadEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileUploadUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SmartActiveLink (smartActiveLinkId LONG not null primary key,category VARCHAR(75) null,title VARCHAR(75) null,fileUploadEntryId LONG,fileUploadUrl VARCHAR(75) null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table SmartActiveLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smartActiveLink.smartActiveLinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SmartActiveLink.smartActiveLinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CATEGORY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVELINKID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SmartActiveLink toModel(SmartActiveLinkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SmartActiveLink model = new SmartActiveLinkImpl();

		model.setSmartActiveLinkId(soapModel.getSmartActiveLinkId());
		model.setCategory(soapModel.getCategory());
		model.setTitle(soapModel.getTitle());
		model.setFileUploadEntryId(soapModel.getFileUploadEntryId());
		model.setFileUploadUrl(soapModel.getFileUploadUrl());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SmartActiveLink> toModels(
		SmartActiveLinkSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmartActiveLink> models = new ArrayList<SmartActiveLink>(
			soapModels.length);

		for (SmartActiveLinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SmartActiveLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _smartActiveLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSmartActiveLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _smartActiveLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SmartActiveLink.class;
	}

	@Override
	public String getModelClassName() {
		return SmartActiveLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmartActiveLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmartActiveLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SmartActiveLink)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmartActiveLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmartActiveLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmartActiveLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmartActiveLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmartActiveLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SmartActiveLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SmartActiveLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmartActiveLink, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<SmartActiveLink, Object>>();
		Map<String, BiConsumer<SmartActiveLink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SmartActiveLink, ?>>();

		attributeGetterFunctions.put(
			"smartActiveLinkId", SmartActiveLink::getSmartActiveLinkId);
		attributeSetterBiConsumers.put(
			"smartActiveLinkId",
			(BiConsumer<SmartActiveLink, Long>)
				SmartActiveLink::setSmartActiveLinkId);
		attributeGetterFunctions.put("category", SmartActiveLink::getCategory);
		attributeSetterBiConsumers.put(
			"category",
			(BiConsumer<SmartActiveLink, String>)SmartActiveLink::setCategory);
		attributeGetterFunctions.put("title", SmartActiveLink::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<SmartActiveLink, String>)SmartActiveLink::setTitle);
		attributeGetterFunctions.put(
			"fileUploadEntryId", SmartActiveLink::getFileUploadEntryId);
		attributeSetterBiConsumers.put(
			"fileUploadEntryId",
			(BiConsumer<SmartActiveLink, Long>)
				SmartActiveLink::setFileUploadEntryId);
		attributeGetterFunctions.put(
			"fileUploadUrl", SmartActiveLink::getFileUploadUrl);
		attributeSetterBiConsumers.put(
			"fileUploadUrl",
			(BiConsumer<SmartActiveLink, String>)
				SmartActiveLink::setFileUploadUrl);
		attributeGetterFunctions.put("active", SmartActiveLink::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<SmartActiveLink, Integer>)SmartActiveLink::setActive);
		attributeGetterFunctions.put("groupId", SmartActiveLink::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SmartActiveLink, Long>)SmartActiveLink::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SmartActiveLink::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SmartActiveLink, Long>)SmartActiveLink::setCompanyId);
		attributeGetterFunctions.put("userId", SmartActiveLink::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SmartActiveLink, Long>)SmartActiveLink::setUserId);
		attributeGetterFunctions.put("userName", SmartActiveLink::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SmartActiveLink, String>)SmartActiveLink::setUserName);
		attributeGetterFunctions.put(
			"createDate", SmartActiveLink::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SmartActiveLink, Date>)SmartActiveLink::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SmartActiveLink::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SmartActiveLink, Date>)
				SmartActiveLink::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSmartActiveLinkId() {
		return _smartActiveLinkId;
	}

	@Override
	public void setSmartActiveLinkId(long smartActiveLinkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveLinkId = smartActiveLinkId;
	}

	@JSON
	@Override
	public String getCategory() {
		if (_category == null) {
			return "";
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_category = category;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCategory() {
		return getColumnOriginalValue("category");
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public long getFileUploadEntryId() {
		return _fileUploadEntryId;
	}

	@Override
	public void setFileUploadEntryId(long fileUploadEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileUploadEntryId = fileUploadEntryId;
	}

	@JSON
	@Override
	public String getFileUploadUrl() {
		if (_fileUploadUrl == null) {
			return "";
		}
		else {
			return _fileUploadUrl;
		}
	}

	@Override
	public void setFileUploadUrl(String fileUploadUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileUploadUrl = fileUploadUrl;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SmartActiveLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SmartActiveLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SmartActiveLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmartActiveLinkImpl smartActiveLinkImpl = new SmartActiveLinkImpl();

		smartActiveLinkImpl.setSmartActiveLinkId(getSmartActiveLinkId());
		smartActiveLinkImpl.setCategory(getCategory());
		smartActiveLinkImpl.setTitle(getTitle());
		smartActiveLinkImpl.setFileUploadEntryId(getFileUploadEntryId());
		smartActiveLinkImpl.setFileUploadUrl(getFileUploadUrl());
		smartActiveLinkImpl.setActive(getActive());
		smartActiveLinkImpl.setGroupId(getGroupId());
		smartActiveLinkImpl.setCompanyId(getCompanyId());
		smartActiveLinkImpl.setUserId(getUserId());
		smartActiveLinkImpl.setUserName(getUserName());
		smartActiveLinkImpl.setCreateDate(getCreateDate());
		smartActiveLinkImpl.setModifiedDate(getModifiedDate());

		smartActiveLinkImpl.resetOriginalValues();

		return smartActiveLinkImpl;
	}

	@Override
	public int compareTo(SmartActiveLink smartActiveLink) {
		long primaryKey = smartActiveLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SmartActiveLink)) {
			return false;
		}

		SmartActiveLink smartActiveLink = (SmartActiveLink)object;

		long primaryKey = smartActiveLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SmartActiveLink> toCacheModel() {
		SmartActiveLinkCacheModel smartActiveLinkCacheModel =
			new SmartActiveLinkCacheModel();

		smartActiveLinkCacheModel.smartActiveLinkId = getSmartActiveLinkId();

		smartActiveLinkCacheModel.category = getCategory();

		String category = smartActiveLinkCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			smartActiveLinkCacheModel.category = null;
		}

		smartActiveLinkCacheModel.title = getTitle();

		String title = smartActiveLinkCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			smartActiveLinkCacheModel.title = null;
		}

		smartActiveLinkCacheModel.fileUploadEntryId = getFileUploadEntryId();

		smartActiveLinkCacheModel.fileUploadUrl = getFileUploadUrl();

		String fileUploadUrl = smartActiveLinkCacheModel.fileUploadUrl;

		if ((fileUploadUrl != null) && (fileUploadUrl.length() == 0)) {
			smartActiveLinkCacheModel.fileUploadUrl = null;
		}

		smartActiveLinkCacheModel.active = getActive();

		smartActiveLinkCacheModel.groupId = getGroupId();

		smartActiveLinkCacheModel.companyId = getCompanyId();

		smartActiveLinkCacheModel.userId = getUserId();

		smartActiveLinkCacheModel.userName = getUserName();

		String userName = smartActiveLinkCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			smartActiveLinkCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			smartActiveLinkCacheModel.createDate = createDate.getTime();
		}
		else {
			smartActiveLinkCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			smartActiveLinkCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			smartActiveLinkCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return smartActiveLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmartActiveLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmartActiveLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SmartActiveLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmartActiveLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmartActiveLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SmartActiveLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SmartActiveLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SmartActiveLink.class, ModelWrapper.class);

	}

	private long _smartActiveLinkId;
	private String _category;
	private String _title;
	private long _fileUploadEntryId;
	private String _fileUploadUrl;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SmartActiveLink, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SmartActiveLink)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("smartActiveLinkId", _smartActiveLinkId);
		_columnOriginalValues.put("category", _category);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("fileUploadEntryId", _fileUploadEntryId);
		_columnOriginalValues.put("fileUploadUrl", _fileUploadUrl);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("smartActiveLinkId", 1L);

		columnBitmasks.put("category", 2L);

		columnBitmasks.put("title", 4L);

		columnBitmasks.put("fileUploadEntryId", 8L);

		columnBitmasks.put("fileUploadUrl", 16L);

		columnBitmasks.put("active_", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SmartActiveLink _escapedModel;

}