/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.SmartActiveBenefitValue;
import com.mypage.admin.product.model.SmartActiveBenefitValueModel;
import com.mypage.admin.product.model.SmartActiveBenefitValueSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmartActiveBenefitValue service. Represents a row in the &quot;SmartActiveBenefitValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SmartActiveBenefitValueModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmartActiveBenefitValueImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see SmartActiveBenefitValueImpl
 * @generated
 */
@JSON(strict = true)
public class SmartActiveBenefitValueModelImpl
	extends BaseModelImpl<SmartActiveBenefitValue>
	implements SmartActiveBenefitValueModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a smart active benefit value model instance should use the <code>SmartActiveBenefitValue</code> interface instead.
	 */
	public static final String TABLE_NAME = "SmartActiveBenefitValue";

	public static final Object[][] TABLE_COLUMNS = {
		{"smartActiveBenefitValueId", Types.BIGINT}, {"value", Types.BIGINT},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("smartActiveBenefitValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("value", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SmartActiveBenefitValue (smartActiveBenefitValueId LONG not null primary key,value LONG,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table SmartActiveBenefitValue";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smartActiveBenefitValue.smartActiveBenefitValueId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SmartActiveBenefitValue.smartActiveBenefitValueId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VALUE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVEBENEFITVALUEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SmartActiveBenefitValue toModel(
		SmartActiveBenefitValueSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		SmartActiveBenefitValue model = new SmartActiveBenefitValueImpl();

		model.setSmartActiveBenefitValueId(
			soapModel.getSmartActiveBenefitValueId());
		model.setValue(soapModel.getValue());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SmartActiveBenefitValue> toModels(
		SmartActiveBenefitValueSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmartActiveBenefitValue> models =
			new ArrayList<SmartActiveBenefitValue>(soapModels.length);

		for (SmartActiveBenefitValueSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SmartActiveBenefitValueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _smartActiveBenefitValueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSmartActiveBenefitValueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _smartActiveBenefitValueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SmartActiveBenefitValue.class;
	}

	@Override
	public String getModelClassName() {
		return SmartActiveBenefitValue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmartActiveBenefitValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmartActiveBenefitValue, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefitValue, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SmartActiveBenefitValue)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmartActiveBenefitValue, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmartActiveBenefitValue, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmartActiveBenefitValue)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmartActiveBenefitValue, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmartActiveBenefitValue, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SmartActiveBenefitValue, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<SmartActiveBenefitValue, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmartActiveBenefitValue, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SmartActiveBenefitValue, Object>>();
		Map<String, BiConsumer<SmartActiveBenefitValue, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<SmartActiveBenefitValue, ?>>();

		attributeGetterFunctions.put(
			"smartActiveBenefitValueId",
			SmartActiveBenefitValue::getSmartActiveBenefitValueId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitValueId",
			(BiConsumer<SmartActiveBenefitValue, Long>)
				SmartActiveBenefitValue::setSmartActiveBenefitValueId);
		attributeGetterFunctions.put(
			"value", SmartActiveBenefitValue::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<SmartActiveBenefitValue, Long>)
				SmartActiveBenefitValue::setValue);
		attributeGetterFunctions.put(
			"active", SmartActiveBenefitValue::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<SmartActiveBenefitValue, Integer>)
				SmartActiveBenefitValue::setActive);
		attributeGetterFunctions.put(
			"groupId", SmartActiveBenefitValue::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SmartActiveBenefitValue, Long>)
				SmartActiveBenefitValue::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SmartActiveBenefitValue::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SmartActiveBenefitValue, Long>)
				SmartActiveBenefitValue::setCompanyId);
		attributeGetterFunctions.put(
			"userId", SmartActiveBenefitValue::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SmartActiveBenefitValue, Long>)
				SmartActiveBenefitValue::setUserId);
		attributeGetterFunctions.put(
			"userName", SmartActiveBenefitValue::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SmartActiveBenefitValue, String>)
				SmartActiveBenefitValue::setUserName);
		attributeGetterFunctions.put(
			"createDate", SmartActiveBenefitValue::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SmartActiveBenefitValue, Date>)
				SmartActiveBenefitValue::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SmartActiveBenefitValue::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SmartActiveBenefitValue, Date>)
				SmartActiveBenefitValue::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSmartActiveBenefitValueId() {
		return _smartActiveBenefitValueId;
	}

	@Override
	public void setSmartActiveBenefitValueId(long smartActiveBenefitValueId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitValueId = smartActiveBenefitValueId;
	}

	@JSON
	@Override
	public long getValue() {
		return _value;
	}

	@Override
	public void setValue(long value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalValue() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("value"));
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SmartActiveBenefitValue.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SmartActiveBenefitValue toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SmartActiveBenefitValue>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmartActiveBenefitValueImpl smartActiveBenefitValueImpl =
			new SmartActiveBenefitValueImpl();

		smartActiveBenefitValueImpl.setSmartActiveBenefitValueId(
			getSmartActiveBenefitValueId());
		smartActiveBenefitValueImpl.setValue(getValue());
		smartActiveBenefitValueImpl.setActive(getActive());
		smartActiveBenefitValueImpl.setGroupId(getGroupId());
		smartActiveBenefitValueImpl.setCompanyId(getCompanyId());
		smartActiveBenefitValueImpl.setUserId(getUserId());
		smartActiveBenefitValueImpl.setUserName(getUserName());
		smartActiveBenefitValueImpl.setCreateDate(getCreateDate());
		smartActiveBenefitValueImpl.setModifiedDate(getModifiedDate());

		smartActiveBenefitValueImpl.resetOriginalValues();

		return smartActiveBenefitValueImpl;
	}

	@Override
	public int compareTo(SmartActiveBenefitValue smartActiveBenefitValue) {
		long primaryKey = smartActiveBenefitValue.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SmartActiveBenefitValue)) {
			return false;
		}

		SmartActiveBenefitValue smartActiveBenefitValue =
			(SmartActiveBenefitValue)object;

		long primaryKey = smartActiveBenefitValue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SmartActiveBenefitValue> toCacheModel() {
		SmartActiveBenefitValueCacheModel smartActiveBenefitValueCacheModel =
			new SmartActiveBenefitValueCacheModel();

		smartActiveBenefitValueCacheModel.smartActiveBenefitValueId =
			getSmartActiveBenefitValueId();

		smartActiveBenefitValueCacheModel.value = getValue();

		smartActiveBenefitValueCacheModel.active = getActive();

		smartActiveBenefitValueCacheModel.groupId = getGroupId();

		smartActiveBenefitValueCacheModel.companyId = getCompanyId();

		smartActiveBenefitValueCacheModel.userId = getUserId();

		smartActiveBenefitValueCacheModel.userName = getUserName();

		String userName = smartActiveBenefitValueCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			smartActiveBenefitValueCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			smartActiveBenefitValueCacheModel.createDate = createDate.getTime();
		}
		else {
			smartActiveBenefitValueCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			smartActiveBenefitValueCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			smartActiveBenefitValueCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return smartActiveBenefitValueCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmartActiveBenefitValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmartActiveBenefitValue, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefitValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SmartActiveBenefitValue)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmartActiveBenefitValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmartActiveBenefitValue, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefitValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((SmartActiveBenefitValue)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, SmartActiveBenefitValue>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						SmartActiveBenefitValue.class, ModelWrapper.class);

	}

	private long _smartActiveBenefitValueId;
	private long _value;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SmartActiveBenefitValue, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SmartActiveBenefitValue)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"smartActiveBenefitValueId", _smartActiveBenefitValueId);
		_columnOriginalValues.put("value", _value);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("smartActiveBenefitValueId", 1L);

		columnBitmasks.put("value", 2L);

		columnBitmasks.put("active_", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SmartActiveBenefitValue _escapedModel;

}