/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.SmartActiveBenefitValueMapping;
import com.mypage.admin.product.model.SmartActiveBenefitValueMappingModel;
import com.mypage.admin.product.model.SmartActiveBenefitValueMappingSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmartActiveBenefitValueMapping service. Represents a row in the &quot;SmartActiveBenefitValueMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SmartActiveBenefitValueMappingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmartActiveBenefitValueMappingImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see SmartActiveBenefitValueMappingImpl
 * @generated
 */
@JSON(strict = true)
public class SmartActiveBenefitValueMappingModelImpl
	extends BaseModelImpl<SmartActiveBenefitValueMapping>
	implements SmartActiveBenefitValueMappingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a smart active benefit value mapping model instance should use the <code>SmartActiveBenefitValueMapping</code> interface instead.
	 */
	public static final String TABLE_NAME = "SmartActiveBenefitValueMapping";

	public static final Object[][] TABLE_COLUMNS = {
		{"smartActiveBenefitValueMappingId", Types.BIGINT},
		{"smartActiveBenefitTypeId", Types.BIGINT},
		{"smartActiveBenefitId", Types.BIGINT},
		{"smartActiveBenefitValueId", Types.BIGINT}, {"value", Types.VARCHAR},
		{"limitValue", Types.DECIMAL}, {"active_", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("smartActiveBenefitValueMappingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("smartActiveBenefitTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("smartActiveBenefitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("smartActiveBenefitValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("limitValue", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SmartActiveBenefitValueMapping (smartActiveBenefitValueMappingId LONG not null primary key,smartActiveBenefitTypeId LONG,smartActiveBenefitId LONG,smartActiveBenefitValueId LONG,value VARCHAR(75) null,limitValue DECIMAL(30, 16) null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table SmartActiveBenefitValueMapping";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smartActiveBenefitValueMapping.smartActiveBenefitValueMappingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SmartActiveBenefitValueMapping.smartActiveBenefitValueMappingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVEBENEFITID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVEBENEFITVALUEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVEBENEFITVALUEMAPPINGID_COLUMN_BITMASK =
		4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SmartActiveBenefitValueMapping toModel(
		SmartActiveBenefitValueMappingSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		SmartActiveBenefitValueMapping model =
			new SmartActiveBenefitValueMappingImpl();

		model.setSmartActiveBenefitValueMappingId(
			soapModel.getSmartActiveBenefitValueMappingId());
		model.setSmartActiveBenefitTypeId(
			soapModel.getSmartActiveBenefitTypeId());
		model.setSmartActiveBenefitId(soapModel.getSmartActiveBenefitId());
		model.setSmartActiveBenefitValueId(
			soapModel.getSmartActiveBenefitValueId());
		model.setValue(soapModel.getValue());
		model.setLimitValue(soapModel.getLimitValue());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SmartActiveBenefitValueMapping> toModels(
		SmartActiveBenefitValueMappingSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmartActiveBenefitValueMapping> models =
			new ArrayList<SmartActiveBenefitValueMapping>(soapModels.length);

		for (SmartActiveBenefitValueMappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SmartActiveBenefitValueMappingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _smartActiveBenefitValueMappingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSmartActiveBenefitValueMappingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _smartActiveBenefitValueMappingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SmartActiveBenefitValueMapping.class;
	}

	@Override
	public String getModelClassName() {
		return SmartActiveBenefitValueMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmartActiveBenefitValueMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmartActiveBenefitValueMapping, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefitValueMapping, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(SmartActiveBenefitValueMapping)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmartActiveBenefitValueMapping, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmartActiveBenefitValueMapping, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmartActiveBenefitValueMapping)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmartActiveBenefitValueMapping, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmartActiveBenefitValueMapping, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<SmartActiveBenefitValueMapping, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<SmartActiveBenefitValueMapping, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmartActiveBenefitValueMapping, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function<SmartActiveBenefitValueMapping, Object>>();
		Map<String, BiConsumer<SmartActiveBenefitValueMapping, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<SmartActiveBenefitValueMapping, ?>>();

		attributeGetterFunctions.put(
			"smartActiveBenefitValueMappingId",
			SmartActiveBenefitValueMapping::
				getSmartActiveBenefitValueMappingId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitValueMappingId",
			(BiConsumer<SmartActiveBenefitValueMapping, Long>)
				SmartActiveBenefitValueMapping::
					setSmartActiveBenefitValueMappingId);
		attributeGetterFunctions.put(
			"smartActiveBenefitTypeId",
			SmartActiveBenefitValueMapping::getSmartActiveBenefitTypeId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitTypeId",
			(BiConsumer<SmartActiveBenefitValueMapping, Long>)
				SmartActiveBenefitValueMapping::setSmartActiveBenefitTypeId);
		attributeGetterFunctions.put(
			"smartActiveBenefitId",
			SmartActiveBenefitValueMapping::getSmartActiveBenefitId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitId",
			(BiConsumer<SmartActiveBenefitValueMapping, Long>)
				SmartActiveBenefitValueMapping::setSmartActiveBenefitId);
		attributeGetterFunctions.put(
			"smartActiveBenefitValueId",
			SmartActiveBenefitValueMapping::getSmartActiveBenefitValueId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitValueId",
			(BiConsumer<SmartActiveBenefitValueMapping, Long>)
				SmartActiveBenefitValueMapping::setSmartActiveBenefitValueId);
		attributeGetterFunctions.put(
			"value", SmartActiveBenefitValueMapping::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<SmartActiveBenefitValueMapping, String>)
				SmartActiveBenefitValueMapping::setValue);
		attributeGetterFunctions.put(
			"limitValue", SmartActiveBenefitValueMapping::getLimitValue);
		attributeSetterBiConsumers.put(
			"limitValue",
			(BiConsumer<SmartActiveBenefitValueMapping, BigDecimal>)
				SmartActiveBenefitValueMapping::setLimitValue);
		attributeGetterFunctions.put(
			"active", SmartActiveBenefitValueMapping::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<SmartActiveBenefitValueMapping, Integer>)
				SmartActiveBenefitValueMapping::setActive);
		attributeGetterFunctions.put(
			"groupId", SmartActiveBenefitValueMapping::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SmartActiveBenefitValueMapping, Long>)
				SmartActiveBenefitValueMapping::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SmartActiveBenefitValueMapping::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SmartActiveBenefitValueMapping, Long>)
				SmartActiveBenefitValueMapping::setCompanyId);
		attributeGetterFunctions.put(
			"userId", SmartActiveBenefitValueMapping::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SmartActiveBenefitValueMapping, Long>)
				SmartActiveBenefitValueMapping::setUserId);
		attributeGetterFunctions.put(
			"userName", SmartActiveBenefitValueMapping::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SmartActiveBenefitValueMapping, String>)
				SmartActiveBenefitValueMapping::setUserName);
		attributeGetterFunctions.put(
			"createDate", SmartActiveBenefitValueMapping::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SmartActiveBenefitValueMapping, Date>)
				SmartActiveBenefitValueMapping::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SmartActiveBenefitValueMapping::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SmartActiveBenefitValueMapping, Date>)
				SmartActiveBenefitValueMapping::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSmartActiveBenefitValueMappingId() {
		return _smartActiveBenefitValueMappingId;
	}

	@Override
	public void setSmartActiveBenefitValueMappingId(
		long smartActiveBenefitValueMappingId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitValueMappingId = smartActiveBenefitValueMappingId;
	}

	@JSON
	@Override
	public long getSmartActiveBenefitTypeId() {
		return _smartActiveBenefitTypeId;
	}

	@Override
	public void setSmartActiveBenefitTypeId(long smartActiveBenefitTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitTypeId = smartActiveBenefitTypeId;
	}

	@JSON
	@Override
	public long getSmartActiveBenefitId() {
		return _smartActiveBenefitId;
	}

	@Override
	public void setSmartActiveBenefitId(long smartActiveBenefitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitId = smartActiveBenefitId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSmartActiveBenefitId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("smartActiveBenefitId"));
	}

	@JSON
	@Override
	public long getSmartActiveBenefitValueId() {
		return _smartActiveBenefitValueId;
	}

	@Override
	public void setSmartActiveBenefitValueId(long smartActiveBenefitValueId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitValueId = smartActiveBenefitValueId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSmartActiveBenefitValueId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("smartActiveBenefitValueId"));
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	@JSON
	@Override
	public BigDecimal getLimitValue() {
		return _limitValue;
	}

	@Override
	public void setLimitValue(BigDecimal limitValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_limitValue = limitValue;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SmartActiveBenefitValueMapping.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SmartActiveBenefitValueMapping toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SmartActiveBenefitValueMapping>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmartActiveBenefitValueMappingImpl smartActiveBenefitValueMappingImpl =
			new SmartActiveBenefitValueMappingImpl();

		smartActiveBenefitValueMappingImpl.setSmartActiveBenefitValueMappingId(
			getSmartActiveBenefitValueMappingId());
		smartActiveBenefitValueMappingImpl.setSmartActiveBenefitTypeId(
			getSmartActiveBenefitTypeId());
		smartActiveBenefitValueMappingImpl.setSmartActiveBenefitId(
			getSmartActiveBenefitId());
		smartActiveBenefitValueMappingImpl.setSmartActiveBenefitValueId(
			getSmartActiveBenefitValueId());
		smartActiveBenefitValueMappingImpl.setValue(getValue());
		smartActiveBenefitValueMappingImpl.setLimitValue(getLimitValue());
		smartActiveBenefitValueMappingImpl.setActive(getActive());
		smartActiveBenefitValueMappingImpl.setGroupId(getGroupId());
		smartActiveBenefitValueMappingImpl.setCompanyId(getCompanyId());
		smartActiveBenefitValueMappingImpl.setUserId(getUserId());
		smartActiveBenefitValueMappingImpl.setUserName(getUserName());
		smartActiveBenefitValueMappingImpl.setCreateDate(getCreateDate());
		smartActiveBenefitValueMappingImpl.setModifiedDate(getModifiedDate());

		smartActiveBenefitValueMappingImpl.resetOriginalValues();

		return smartActiveBenefitValueMappingImpl;
	}

	@Override
	public int compareTo(
		SmartActiveBenefitValueMapping smartActiveBenefitValueMapping) {

		long primaryKey = smartActiveBenefitValueMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SmartActiveBenefitValueMapping)) {
			return false;
		}

		SmartActiveBenefitValueMapping smartActiveBenefitValueMapping =
			(SmartActiveBenefitValueMapping)object;

		long primaryKey = smartActiveBenefitValueMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SmartActiveBenefitValueMapping> toCacheModel() {
		SmartActiveBenefitValueMappingCacheModel
			smartActiveBenefitValueMappingCacheModel =
				new SmartActiveBenefitValueMappingCacheModel();

		smartActiveBenefitValueMappingCacheModel.
			smartActiveBenefitValueMappingId =
				getSmartActiveBenefitValueMappingId();

		smartActiveBenefitValueMappingCacheModel.smartActiveBenefitTypeId =
			getSmartActiveBenefitTypeId();

		smartActiveBenefitValueMappingCacheModel.smartActiveBenefitId =
			getSmartActiveBenefitId();

		smartActiveBenefitValueMappingCacheModel.smartActiveBenefitValueId =
			getSmartActiveBenefitValueId();

		smartActiveBenefitValueMappingCacheModel.value = getValue();

		String value = smartActiveBenefitValueMappingCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			smartActiveBenefitValueMappingCacheModel.value = null;
		}

		smartActiveBenefitValueMappingCacheModel.limitValue = getLimitValue();

		smartActiveBenefitValueMappingCacheModel.active = getActive();

		smartActiveBenefitValueMappingCacheModel.groupId = getGroupId();

		smartActiveBenefitValueMappingCacheModel.companyId = getCompanyId();

		smartActiveBenefitValueMappingCacheModel.userId = getUserId();

		smartActiveBenefitValueMappingCacheModel.userName = getUserName();

		String userName = smartActiveBenefitValueMappingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			smartActiveBenefitValueMappingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			smartActiveBenefitValueMappingCacheModel.createDate =
				createDate.getTime();
		}
		else {
			smartActiveBenefitValueMappingCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			smartActiveBenefitValueMappingCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			smartActiveBenefitValueMappingCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		return smartActiveBenefitValueMappingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmartActiveBenefitValueMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmartActiveBenefitValueMapping, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefitValueMapping, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SmartActiveBenefitValueMapping)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmartActiveBenefitValueMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmartActiveBenefitValueMapping, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefitValueMapping, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(SmartActiveBenefitValueMapping)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, SmartActiveBenefitValueMapping>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						SmartActiveBenefitValueMapping.class,
						ModelWrapper.class);

	}

	private long _smartActiveBenefitValueMappingId;
	private long _smartActiveBenefitTypeId;
	private long _smartActiveBenefitId;
	private long _smartActiveBenefitValueId;
	private String _value;
	private BigDecimal _limitValue;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SmartActiveBenefitValueMapping, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SmartActiveBenefitValueMapping)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"smartActiveBenefitValueMappingId",
			_smartActiveBenefitValueMappingId);
		_columnOriginalValues.put(
			"smartActiveBenefitTypeId", _smartActiveBenefitTypeId);
		_columnOriginalValues.put(
			"smartActiveBenefitId", _smartActiveBenefitId);
		_columnOriginalValues.put(
			"smartActiveBenefitValueId", _smartActiveBenefitValueId);
		_columnOriginalValues.put("value", _value);
		_columnOriginalValues.put("limitValue", _limitValue);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("smartActiveBenefitValueMappingId", 1L);

		columnBitmasks.put("smartActiveBenefitTypeId", 2L);

		columnBitmasks.put("smartActiveBenefitId", 4L);

		columnBitmasks.put("smartActiveBenefitValueId", 8L);

		columnBitmasks.put("value", 16L);

		columnBitmasks.put("limitValue", 32L);

		columnBitmasks.put("active_", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("companyId", 256L);

		columnBitmasks.put("userId", 512L);

		columnBitmasks.put("userName", 1024L);

		columnBitmasks.put("createDate", 2048L);

		columnBitmasks.put("modifiedDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SmartActiveBenefitValueMapping _escapedModel;

}