/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.SmartActiveTopro;
import com.mypage.admin.product.model.SmartActiveToproModel;
import com.mypage.admin.product.model.SmartActiveToproSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmartActiveTopro service. Represents a row in the &quot;SmartActiveTopro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SmartActiveToproModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmartActiveToproImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see SmartActiveToproImpl
 * @generated
 */
@JSON(strict = true)
public class SmartActiveToproModelImpl
	extends BaseModelImpl<SmartActiveTopro> implements SmartActiveToproModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a smart active topro model instance should use the <code>SmartActiveTopro</code> interface instead.
	 */
	public static final String TABLE_NAME = "SmartActiveTopro";

	public static final Object[][] TABLE_COLUMNS = {
		{"smartActiveToproId", Types.BIGINT}, {"topro", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"annotations", Types.VARCHAR},
		{"smartActiveBenefitValueId", Types.BIGINT}, {"toc", Types.VARCHAR},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("smartActiveToproId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("topro", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("annotations", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("smartActiveBenefitValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("toc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SmartActiveTopro (smartActiveToproId LONG not null primary key,topro VARCHAR(75) null,description VARCHAR(75) null,annotations VARCHAR(75) null,smartActiveBenefitValueId LONG,toc VARCHAR(75) null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table SmartActiveTopro";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smartActiveTopro.smartActiveToproId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SmartActiveTopro.smartActiveToproId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVEBENEFITVALUEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TOPRO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVETOPROID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SmartActiveTopro toModel(SmartActiveToproSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SmartActiveTopro model = new SmartActiveToproImpl();

		model.setSmartActiveToproId(soapModel.getSmartActiveToproId());
		model.setTopro(soapModel.getTopro());
		model.setDescription(soapModel.getDescription());
		model.setAnnotations(soapModel.getAnnotations());
		model.setSmartActiveBenefitValueId(
			soapModel.getSmartActiveBenefitValueId());
		model.setToc(soapModel.getToc());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SmartActiveTopro> toModels(
		SmartActiveToproSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmartActiveTopro> models = new ArrayList<SmartActiveTopro>(
			soapModels.length);

		for (SmartActiveToproSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SmartActiveToproModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _smartActiveToproId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSmartActiveToproId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _smartActiveToproId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SmartActiveTopro.class;
	}

	@Override
	public String getModelClassName() {
		return SmartActiveTopro.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmartActiveTopro, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmartActiveTopro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveTopro, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SmartActiveTopro)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmartActiveTopro, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmartActiveTopro, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmartActiveTopro)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmartActiveTopro, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmartActiveTopro, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SmartActiveTopro, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SmartActiveTopro, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmartActiveTopro, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<SmartActiveTopro, Object>>();
		Map<String, BiConsumer<SmartActiveTopro, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SmartActiveTopro, ?>>();

		attributeGetterFunctions.put(
			"smartActiveToproId", SmartActiveTopro::getSmartActiveToproId);
		attributeSetterBiConsumers.put(
			"smartActiveToproId",
			(BiConsumer<SmartActiveTopro, Long>)
				SmartActiveTopro::setSmartActiveToproId);
		attributeGetterFunctions.put("topro", SmartActiveTopro::getTopro);
		attributeSetterBiConsumers.put(
			"topro",
			(BiConsumer<SmartActiveTopro, String>)SmartActiveTopro::setTopro);
		attributeGetterFunctions.put(
			"description", SmartActiveTopro::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<SmartActiveTopro, String>)
				SmartActiveTopro::setDescription);
		attributeGetterFunctions.put(
			"annotations", SmartActiveTopro::getAnnotations);
		attributeSetterBiConsumers.put(
			"annotations",
			(BiConsumer<SmartActiveTopro, String>)
				SmartActiveTopro::setAnnotations);
		attributeGetterFunctions.put(
			"smartActiveBenefitValueId",
			SmartActiveTopro::getSmartActiveBenefitValueId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitValueId",
			(BiConsumer<SmartActiveTopro, Long>)
				SmartActiveTopro::setSmartActiveBenefitValueId);
		attributeGetterFunctions.put("toc", SmartActiveTopro::getToc);
		attributeSetterBiConsumers.put(
			"toc",
			(BiConsumer<SmartActiveTopro, String>)SmartActiveTopro::setToc);
		attributeGetterFunctions.put("active", SmartActiveTopro::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<SmartActiveTopro, Integer>)SmartActiveTopro::setActive);
		attributeGetterFunctions.put("groupId", SmartActiveTopro::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SmartActiveTopro, Long>)SmartActiveTopro::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SmartActiveTopro::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SmartActiveTopro, Long>)SmartActiveTopro::setCompanyId);
		attributeGetterFunctions.put("userId", SmartActiveTopro::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SmartActiveTopro, Long>)SmartActiveTopro::setUserId);
		attributeGetterFunctions.put("userName", SmartActiveTopro::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SmartActiveTopro, String>)
				SmartActiveTopro::setUserName);
		attributeGetterFunctions.put(
			"createDate", SmartActiveTopro::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SmartActiveTopro, Date>)
				SmartActiveTopro::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SmartActiveTopro::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SmartActiveTopro, Date>)
				SmartActiveTopro::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSmartActiveToproId() {
		return _smartActiveToproId;
	}

	@Override
	public void setSmartActiveToproId(long smartActiveToproId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveToproId = smartActiveToproId;
	}

	@JSON
	@Override
	public String getTopro() {
		if (_topro == null) {
			return "";
		}
		else {
			return _topro;
		}
	}

	@Override
	public void setTopro(String topro) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_topro = topro;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTopro() {
		return getColumnOriginalValue("topro");
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getAnnotations() {
		if (_annotations == null) {
			return "";
		}
		else {
			return _annotations;
		}
	}

	@Override
	public void setAnnotations(String annotations) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_annotations = annotations;
	}

	@JSON
	@Override
	public long getSmartActiveBenefitValueId() {
		return _smartActiveBenefitValueId;
	}

	@Override
	public void setSmartActiveBenefitValueId(long smartActiveBenefitValueId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitValueId = smartActiveBenefitValueId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSmartActiveBenefitValueId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("smartActiveBenefitValueId"));
	}

	@JSON
	@Override
	public String getToc() {
		if (_toc == null) {
			return "";
		}
		else {
			return _toc;
		}
	}

	@Override
	public void setToc(String toc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toc = toc;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SmartActiveTopro.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SmartActiveTopro toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SmartActiveTopro>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmartActiveToproImpl smartActiveToproImpl = new SmartActiveToproImpl();

		smartActiveToproImpl.setSmartActiveToproId(getSmartActiveToproId());
		smartActiveToproImpl.setTopro(getTopro());
		smartActiveToproImpl.setDescription(getDescription());
		smartActiveToproImpl.setAnnotations(getAnnotations());
		smartActiveToproImpl.setSmartActiveBenefitValueId(
			getSmartActiveBenefitValueId());
		smartActiveToproImpl.setToc(getToc());
		smartActiveToproImpl.setActive(getActive());
		smartActiveToproImpl.setGroupId(getGroupId());
		smartActiveToproImpl.setCompanyId(getCompanyId());
		smartActiveToproImpl.setUserId(getUserId());
		smartActiveToproImpl.setUserName(getUserName());
		smartActiveToproImpl.setCreateDate(getCreateDate());
		smartActiveToproImpl.setModifiedDate(getModifiedDate());

		smartActiveToproImpl.resetOriginalValues();

		return smartActiveToproImpl;
	}

	@Override
	public int compareTo(SmartActiveTopro smartActiveTopro) {
		long primaryKey = smartActiveTopro.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SmartActiveTopro)) {
			return false;
		}

		SmartActiveTopro smartActiveTopro = (SmartActiveTopro)object;

		long primaryKey = smartActiveTopro.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SmartActiveTopro> toCacheModel() {
		SmartActiveToproCacheModel smartActiveToproCacheModel =
			new SmartActiveToproCacheModel();

		smartActiveToproCacheModel.smartActiveToproId = getSmartActiveToproId();

		smartActiveToproCacheModel.topro = getTopro();

		String topro = smartActiveToproCacheModel.topro;

		if ((topro != null) && (topro.length() == 0)) {
			smartActiveToproCacheModel.topro = null;
		}

		smartActiveToproCacheModel.description = getDescription();

		String description = smartActiveToproCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			smartActiveToproCacheModel.description = null;
		}

		smartActiveToproCacheModel.annotations = getAnnotations();

		String annotations = smartActiveToproCacheModel.annotations;

		if ((annotations != null) && (annotations.length() == 0)) {
			smartActiveToproCacheModel.annotations = null;
		}

		smartActiveToproCacheModel.smartActiveBenefitValueId =
			getSmartActiveBenefitValueId();

		smartActiveToproCacheModel.toc = getToc();

		String toc = smartActiveToproCacheModel.toc;

		if ((toc != null) && (toc.length() == 0)) {
			smartActiveToproCacheModel.toc = null;
		}

		smartActiveToproCacheModel.active = getActive();

		smartActiveToproCacheModel.groupId = getGroupId();

		smartActiveToproCacheModel.companyId = getCompanyId();

		smartActiveToproCacheModel.userId = getUserId();

		smartActiveToproCacheModel.userName = getUserName();

		String userName = smartActiveToproCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			smartActiveToproCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			smartActiveToproCacheModel.createDate = createDate.getTime();
		}
		else {
			smartActiveToproCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			smartActiveToproCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			smartActiveToproCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return smartActiveToproCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmartActiveTopro, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmartActiveTopro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveTopro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SmartActiveTopro)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmartActiveTopro, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmartActiveTopro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveTopro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SmartActiveTopro)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SmartActiveTopro>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SmartActiveTopro.class, ModelWrapper.class);

	}

	private long _smartActiveToproId;
	private String _topro;
	private String _description;
	private String _annotations;
	private long _smartActiveBenefitValueId;
	private String _toc;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SmartActiveTopro, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SmartActiveTopro)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("smartActiveToproId", _smartActiveToproId);
		_columnOriginalValues.put("topro", _topro);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("annotations", _annotations);
		_columnOriginalValues.put(
			"smartActiveBenefitValueId", _smartActiveBenefitValueId);
		_columnOriginalValues.put("toc", _toc);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("smartActiveToproId", 1L);

		columnBitmasks.put("topro", 2L);

		columnBitmasks.put("description", 4L);

		columnBitmasks.put("annotations", 8L);

		columnBitmasks.put("smartActiveBenefitValueId", 16L);

		columnBitmasks.put("toc", 32L);

		columnBitmasks.put("active_", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("companyId", 256L);

		columnBitmasks.put("userId", 512L);

		columnBitmasks.put("userName", 1024L);

		columnBitmasks.put("createDate", 2048L);

		columnBitmasks.put("modifiedDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SmartActiveTopro _escapedModel;

}