/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.SmartActiveBenefit;
import com.mypage.admin.product.model.SmartActiveBenefitModel;
import com.mypage.admin.product.model.SmartActiveBenefitSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmartActiveBenefit service. Represents a row in the &quot;SmartActiveBenefit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SmartActiveBenefitModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmartActiveBenefitImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see SmartActiveBenefitImpl
 * @generated
 */
@JSON(strict = true)
public class SmartActiveBenefitModelImpl
	extends BaseModelImpl<SmartActiveBenefit>
	implements SmartActiveBenefitModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a smart active benefit model instance should use the <code>SmartActiveBenefit</code> interface instead.
	 */
	public static final String TABLE_NAME = "SmartActiveBenefit";

	public static final Object[][] TABLE_COLUMNS = {
		{"smartActiveBenefitId", Types.BIGINT}, {"nameId", Types.VARCHAR},
		{"nameEn", Types.VARCHAR}, {"sort", Types.INTEGER},
		{"smartActiveBenefitTypeId", Types.BIGINT}, {"active_", Types.INTEGER},
		{"description", Types.VARCHAR}, {"limit_", Types.VARCHAR},
		{"externalCode", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("smartActiveBenefitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nameId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nameEn", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sort", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("smartActiveBenefitTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("limit_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SmartActiveBenefit (smartActiveBenefitId LONG not null primary key,nameId VARCHAR(75) null,nameEn VARCHAR(75) null,sort INTEGER,smartActiveBenefitTypeId LONG,active_ INTEGER,description VARCHAR(75) null,limit_ VARCHAR(75) null,externalCode VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table SmartActiveBenefit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smartActiveBenefit.smartActiveBenefitId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SmartActiveBenefit.smartActiveBenefitId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALCODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVEBENEFITTYPEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SMARTACTIVEBENEFITID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SmartActiveBenefit toModel(SmartActiveBenefitSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SmartActiveBenefit model = new SmartActiveBenefitImpl();

		model.setSmartActiveBenefitId(soapModel.getSmartActiveBenefitId());
		model.setNameId(soapModel.getNameId());
		model.setNameEn(soapModel.getNameEn());
		model.setSort(soapModel.getSort());
		model.setSmartActiveBenefitTypeId(
			soapModel.getSmartActiveBenefitTypeId());
		model.setActive(soapModel.getActive());
		model.setDescription(soapModel.getDescription());
		model.setLimit_(soapModel.getLimit_());
		model.setExternalCode(soapModel.getExternalCode());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SmartActiveBenefit> toModels(
		SmartActiveBenefitSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmartActiveBenefit> models = new ArrayList<SmartActiveBenefit>(
			soapModels.length);

		for (SmartActiveBenefitSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SmartActiveBenefitModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _smartActiveBenefitId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSmartActiveBenefitId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _smartActiveBenefitId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SmartActiveBenefit.class;
	}

	@Override
	public String getModelClassName() {
		return SmartActiveBenefit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmartActiveBenefit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmartActiveBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SmartActiveBenefit)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmartActiveBenefit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmartActiveBenefit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmartActiveBenefit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmartActiveBenefit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmartActiveBenefit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SmartActiveBenefit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SmartActiveBenefit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmartActiveBenefit, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SmartActiveBenefit, Object>>();
		Map<String, BiConsumer<SmartActiveBenefit, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SmartActiveBenefit, ?>>();

		attributeGetterFunctions.put(
			"smartActiveBenefitId",
			SmartActiveBenefit::getSmartActiveBenefitId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitId",
			(BiConsumer<SmartActiveBenefit, Long>)
				SmartActiveBenefit::setSmartActiveBenefitId);
		attributeGetterFunctions.put("nameId", SmartActiveBenefit::getNameId);
		attributeSetterBiConsumers.put(
			"nameId",
			(BiConsumer<SmartActiveBenefit, String>)
				SmartActiveBenefit::setNameId);
		attributeGetterFunctions.put("nameEn", SmartActiveBenefit::getNameEn);
		attributeSetterBiConsumers.put(
			"nameEn",
			(BiConsumer<SmartActiveBenefit, String>)
				SmartActiveBenefit::setNameEn);
		attributeGetterFunctions.put("sort", SmartActiveBenefit::getSort);
		attributeSetterBiConsumers.put(
			"sort",
			(BiConsumer<SmartActiveBenefit, Integer>)
				SmartActiveBenefit::setSort);
		attributeGetterFunctions.put(
			"smartActiveBenefitTypeId",
			SmartActiveBenefit::getSmartActiveBenefitTypeId);
		attributeSetterBiConsumers.put(
			"smartActiveBenefitTypeId",
			(BiConsumer<SmartActiveBenefit, Long>)
				SmartActiveBenefit::setSmartActiveBenefitTypeId);
		attributeGetterFunctions.put("active", SmartActiveBenefit::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<SmartActiveBenefit, Integer>)
				SmartActiveBenefit::setActive);
		attributeGetterFunctions.put(
			"description", SmartActiveBenefit::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<SmartActiveBenefit, String>)
				SmartActiveBenefit::setDescription);
		attributeGetterFunctions.put("limit_", SmartActiveBenefit::getLimit_);
		attributeSetterBiConsumers.put(
			"limit_",
			(BiConsumer<SmartActiveBenefit, String>)
				SmartActiveBenefit::setLimit_);
		attributeGetterFunctions.put(
			"externalCode", SmartActiveBenefit::getExternalCode);
		attributeSetterBiConsumers.put(
			"externalCode",
			(BiConsumer<SmartActiveBenefit, String>)
				SmartActiveBenefit::setExternalCode);
		attributeGetterFunctions.put("groupId", SmartActiveBenefit::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SmartActiveBenefit, Long>)
				SmartActiveBenefit::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SmartActiveBenefit::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SmartActiveBenefit, Long>)
				SmartActiveBenefit::setCompanyId);
		attributeGetterFunctions.put("userId", SmartActiveBenefit::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SmartActiveBenefit, Long>)
				SmartActiveBenefit::setUserId);
		attributeGetterFunctions.put(
			"userName", SmartActiveBenefit::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SmartActiveBenefit, String>)
				SmartActiveBenefit::setUserName);
		attributeGetterFunctions.put(
			"createDate", SmartActiveBenefit::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SmartActiveBenefit, Date>)
				SmartActiveBenefit::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SmartActiveBenefit::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SmartActiveBenefit, Date>)
				SmartActiveBenefit::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSmartActiveBenefitId() {
		return _smartActiveBenefitId;
	}

	@Override
	public void setSmartActiveBenefitId(long smartActiveBenefitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitId = smartActiveBenefitId;
	}

	@JSON
	@Override
	public String getNameId() {
		if (_nameId == null) {
			return "";
		}
		else {
			return _nameId;
		}
	}

	@Override
	public void setNameId(String nameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameId = nameId;
	}

	@JSON
	@Override
	public String getNameEn() {
		if (_nameEn == null) {
			return "";
		}
		else {
			return _nameEn;
		}
	}

	@Override
	public void setNameEn(String nameEn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameEn = nameEn;
	}

	@JSON
	@Override
	public int getSort() {
		return _sort;
	}

	@Override
	public void setSort(int sort) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sort = sort;
	}

	@JSON
	@Override
	public long getSmartActiveBenefitTypeId() {
		return _smartActiveBenefitTypeId;
	}

	@Override
	public void setSmartActiveBenefitTypeId(long smartActiveBenefitTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_smartActiveBenefitTypeId = smartActiveBenefitTypeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSmartActiveBenefitTypeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("smartActiveBenefitTypeId"));
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getLimit_() {
		if (_limit_ == null) {
			return "";
		}
		else {
			return _limit_;
		}
	}

	@Override
	public void setLimit_(String limit_) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_limit_ = limit_;
	}

	@JSON
	@Override
	public String getExternalCode() {
		if (_externalCode == null) {
			return "";
		}
		else {
			return _externalCode;
		}
	}

	@Override
	public void setExternalCode(String externalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalCode = externalCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalCode() {
		return getColumnOriginalValue("externalCode");
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SmartActiveBenefit.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SmartActiveBenefit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SmartActiveBenefit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmartActiveBenefitImpl smartActiveBenefitImpl =
			new SmartActiveBenefitImpl();

		smartActiveBenefitImpl.setSmartActiveBenefitId(
			getSmartActiveBenefitId());
		smartActiveBenefitImpl.setNameId(getNameId());
		smartActiveBenefitImpl.setNameEn(getNameEn());
		smartActiveBenefitImpl.setSort(getSort());
		smartActiveBenefitImpl.setSmartActiveBenefitTypeId(
			getSmartActiveBenefitTypeId());
		smartActiveBenefitImpl.setActive(getActive());
		smartActiveBenefitImpl.setDescription(getDescription());
		smartActiveBenefitImpl.setLimit_(getLimit_());
		smartActiveBenefitImpl.setExternalCode(getExternalCode());
		smartActiveBenefitImpl.setGroupId(getGroupId());
		smartActiveBenefitImpl.setCompanyId(getCompanyId());
		smartActiveBenefitImpl.setUserId(getUserId());
		smartActiveBenefitImpl.setUserName(getUserName());
		smartActiveBenefitImpl.setCreateDate(getCreateDate());
		smartActiveBenefitImpl.setModifiedDate(getModifiedDate());

		smartActiveBenefitImpl.resetOriginalValues();

		return smartActiveBenefitImpl;
	}

	@Override
	public int compareTo(SmartActiveBenefit smartActiveBenefit) {
		long primaryKey = smartActiveBenefit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SmartActiveBenefit)) {
			return false;
		}

		SmartActiveBenefit smartActiveBenefit = (SmartActiveBenefit)object;

		long primaryKey = smartActiveBenefit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SmartActiveBenefit> toCacheModel() {
		SmartActiveBenefitCacheModel smartActiveBenefitCacheModel =
			new SmartActiveBenefitCacheModel();

		smartActiveBenefitCacheModel.smartActiveBenefitId =
			getSmartActiveBenefitId();

		smartActiveBenefitCacheModel.nameId = getNameId();

		String nameId = smartActiveBenefitCacheModel.nameId;

		if ((nameId != null) && (nameId.length() == 0)) {
			smartActiveBenefitCacheModel.nameId = null;
		}

		smartActiveBenefitCacheModel.nameEn = getNameEn();

		String nameEn = smartActiveBenefitCacheModel.nameEn;

		if ((nameEn != null) && (nameEn.length() == 0)) {
			smartActiveBenefitCacheModel.nameEn = null;
		}

		smartActiveBenefitCacheModel.sort = getSort();

		smartActiveBenefitCacheModel.smartActiveBenefitTypeId =
			getSmartActiveBenefitTypeId();

		smartActiveBenefitCacheModel.active = getActive();

		smartActiveBenefitCacheModel.description = getDescription();

		String description = smartActiveBenefitCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			smartActiveBenefitCacheModel.description = null;
		}

		smartActiveBenefitCacheModel.limit_ = getLimit_();

		String limit_ = smartActiveBenefitCacheModel.limit_;

		if ((limit_ != null) && (limit_.length() == 0)) {
			smartActiveBenefitCacheModel.limit_ = null;
		}

		smartActiveBenefitCacheModel.externalCode = getExternalCode();

		String externalCode = smartActiveBenefitCacheModel.externalCode;

		if ((externalCode != null) && (externalCode.length() == 0)) {
			smartActiveBenefitCacheModel.externalCode = null;
		}

		smartActiveBenefitCacheModel.groupId = getGroupId();

		smartActiveBenefitCacheModel.companyId = getCompanyId();

		smartActiveBenefitCacheModel.userId = getUserId();

		smartActiveBenefitCacheModel.userName = getUserName();

		String userName = smartActiveBenefitCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			smartActiveBenefitCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			smartActiveBenefitCacheModel.createDate = createDate.getTime();
		}
		else {
			smartActiveBenefitCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			smartActiveBenefitCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			smartActiveBenefitCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return smartActiveBenefitCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmartActiveBenefit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmartActiveBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SmartActiveBenefit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmartActiveBenefit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmartActiveBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmartActiveBenefit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SmartActiveBenefit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SmartActiveBenefit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SmartActiveBenefit.class, ModelWrapper.class);

	}

	private long _smartActiveBenefitId;
	private String _nameId;
	private String _nameEn;
	private int _sort;
	private long _smartActiveBenefitTypeId;
	private int _active;
	private String _description;
	private String _limit_;
	private String _externalCode;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SmartActiveBenefit, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SmartActiveBenefit)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"smartActiveBenefitId", _smartActiveBenefitId);
		_columnOriginalValues.put("nameId", _nameId);
		_columnOriginalValues.put("nameEn", _nameEn);
		_columnOriginalValues.put("sort", _sort);
		_columnOriginalValues.put(
			"smartActiveBenefitTypeId", _smartActiveBenefitTypeId);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("limit_", _limit_);
		_columnOriginalValues.put("externalCode", _externalCode);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("smartActiveBenefitId", 1L);

		columnBitmasks.put("nameId", 2L);

		columnBitmasks.put("nameEn", 4L);

		columnBitmasks.put("sort", 8L);

		columnBitmasks.put("smartActiveBenefitTypeId", 16L);

		columnBitmasks.put("active_", 32L);

		columnBitmasks.put("description", 64L);

		columnBitmasks.put("limit_", 128L);

		columnBitmasks.put("externalCode", 256L);

		columnBitmasks.put("groupId", 512L);

		columnBitmasks.put("companyId", 1024L);

		columnBitmasks.put("userId", 2048L);

		columnBitmasks.put("userName", 4096L);

		columnBitmasks.put("createDate", 8192L);

		columnBitmasks.put("modifiedDate", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SmartActiveBenefit _escapedModel;

}