/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.StiBenefitValueMapping;
import com.mypage.admin.product.model.StiBenefitValueMappingModel;
import com.mypage.admin.product.model.StiBenefitValueMappingSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the StiBenefitValueMapping service. Represents a row in the &quot;StiBenefitValueMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StiBenefitValueMappingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StiBenefitValueMappingImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see StiBenefitValueMappingImpl
 * @generated
 */
@JSON(strict = true)
public class StiBenefitValueMappingModelImpl
	extends BaseModelImpl<StiBenefitValueMapping>
	implements StiBenefitValueMappingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sti benefit value mapping model instance should use the <code>StiBenefitValueMapping</code> interface instead.
	 */
	public static final String TABLE_NAME = "StiBenefitValueMapping";

	public static final Object[][] TABLE_COLUMNS = {
		{"benefitValueMappingId", Types.BIGINT},
		{"benefitTypeId", Types.BIGINT}, {"benefitId", Types.BIGINT},
		{"planId", Types.BIGINT}, {"benefitValue", Types.VARCHAR},
		{"benefitValueUSD", Types.VARCHAR}, {"sort", Types.INTEGER},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("benefitValueMappingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("benefitTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("benefitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("planId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("benefitValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("benefitValueUSD", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sort", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table StiBenefitValueMapping (benefitValueMappingId LONG not null primary key,benefitTypeId LONG,benefitId LONG,planId LONG,benefitValue VARCHAR(75) null,benefitValueUSD VARCHAR(75) null,sort INTEGER,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table StiBenefitValueMapping";

	public static final String ORDER_BY_JPQL =
		" ORDER BY stiBenefitValueMapping.benefitValueMappingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY StiBenefitValueMapping.benefitValueMappingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BENEFITID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BENEFITTYPEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLANID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BENEFITVALUEMAPPINGID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static StiBenefitValueMapping toModel(
		StiBenefitValueMappingSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		StiBenefitValueMapping model = new StiBenefitValueMappingImpl();

		model.setBenefitValueMappingId(soapModel.getBenefitValueMappingId());
		model.setBenefitTypeId(soapModel.getBenefitTypeId());
		model.setBenefitId(soapModel.getBenefitId());
		model.setPlanId(soapModel.getPlanId());
		model.setBenefitValue(soapModel.getBenefitValue());
		model.setBenefitValueUSD(soapModel.getBenefitValueUSD());
		model.setSort(soapModel.getSort());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<StiBenefitValueMapping> toModels(
		StiBenefitValueMappingSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<StiBenefitValueMapping> models =
			new ArrayList<StiBenefitValueMapping>(soapModels.length);

		for (StiBenefitValueMappingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public StiBenefitValueMappingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _benefitValueMappingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBenefitValueMappingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _benefitValueMappingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StiBenefitValueMapping.class;
	}

	@Override
	public String getModelClassName() {
		return StiBenefitValueMapping.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<StiBenefitValueMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<StiBenefitValueMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StiBenefitValueMapping, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((StiBenefitValueMapping)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<StiBenefitValueMapping, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<StiBenefitValueMapping, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(StiBenefitValueMapping)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<StiBenefitValueMapping, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<StiBenefitValueMapping, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<StiBenefitValueMapping, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<StiBenefitValueMapping, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<StiBenefitValueMapping, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<StiBenefitValueMapping, Object>>();
		Map<String, BiConsumer<StiBenefitValueMapping, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<StiBenefitValueMapping, ?>>();

		attributeGetterFunctions.put(
			"benefitValueMappingId",
			StiBenefitValueMapping::getBenefitValueMappingId);
		attributeSetterBiConsumers.put(
			"benefitValueMappingId",
			(BiConsumer<StiBenefitValueMapping, Long>)
				StiBenefitValueMapping::setBenefitValueMappingId);
		attributeGetterFunctions.put(
			"benefitTypeId", StiBenefitValueMapping::getBenefitTypeId);
		attributeSetterBiConsumers.put(
			"benefitTypeId",
			(BiConsumer<StiBenefitValueMapping, Long>)
				StiBenefitValueMapping::setBenefitTypeId);
		attributeGetterFunctions.put(
			"benefitId", StiBenefitValueMapping::getBenefitId);
		attributeSetterBiConsumers.put(
			"benefitId",
			(BiConsumer<StiBenefitValueMapping, Long>)
				StiBenefitValueMapping::setBenefitId);
		attributeGetterFunctions.put(
			"planId", StiBenefitValueMapping::getPlanId);
		attributeSetterBiConsumers.put(
			"planId",
			(BiConsumer<StiBenefitValueMapping, Long>)
				StiBenefitValueMapping::setPlanId);
		attributeGetterFunctions.put(
			"benefitValue", StiBenefitValueMapping::getBenefitValue);
		attributeSetterBiConsumers.put(
			"benefitValue",
			(BiConsumer<StiBenefitValueMapping, String>)
				StiBenefitValueMapping::setBenefitValue);
		attributeGetterFunctions.put(
			"benefitValueUSD", StiBenefitValueMapping::getBenefitValueUSD);
		attributeSetterBiConsumers.put(
			"benefitValueUSD",
			(BiConsumer<StiBenefitValueMapping, String>)
				StiBenefitValueMapping::setBenefitValueUSD);
		attributeGetterFunctions.put("sort", StiBenefitValueMapping::getSort);
		attributeSetterBiConsumers.put(
			"sort",
			(BiConsumer<StiBenefitValueMapping, Integer>)
				StiBenefitValueMapping::setSort);
		attributeGetterFunctions.put(
			"active", StiBenefitValueMapping::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<StiBenefitValueMapping, Integer>)
				StiBenefitValueMapping::setActive);
		attributeGetterFunctions.put(
			"groupId", StiBenefitValueMapping::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<StiBenefitValueMapping, Long>)
				StiBenefitValueMapping::setGroupId);
		attributeGetterFunctions.put(
			"companyId", StiBenefitValueMapping::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<StiBenefitValueMapping, Long>)
				StiBenefitValueMapping::setCompanyId);
		attributeGetterFunctions.put(
			"userId", StiBenefitValueMapping::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<StiBenefitValueMapping, Long>)
				StiBenefitValueMapping::setUserId);
		attributeGetterFunctions.put(
			"userName", StiBenefitValueMapping::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<StiBenefitValueMapping, String>)
				StiBenefitValueMapping::setUserName);
		attributeGetterFunctions.put(
			"createDate", StiBenefitValueMapping::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<StiBenefitValueMapping, Date>)
				StiBenefitValueMapping::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", StiBenefitValueMapping::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<StiBenefitValueMapping, Date>)
				StiBenefitValueMapping::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getBenefitValueMappingId() {
		return _benefitValueMappingId;
	}

	@Override
	public void setBenefitValueMappingId(long benefitValueMappingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitValueMappingId = benefitValueMappingId;
	}

	@JSON
	@Override
	public long getBenefitTypeId() {
		return _benefitTypeId;
	}

	@Override
	public void setBenefitTypeId(long benefitTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitTypeId = benefitTypeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBenefitTypeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("benefitTypeId"));
	}

	@JSON
	@Override
	public long getBenefitId() {
		return _benefitId;
	}

	@Override
	public void setBenefitId(long benefitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitId = benefitId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBenefitId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("benefitId"));
	}

	@JSON
	@Override
	public long getPlanId() {
		return _planId;
	}

	@Override
	public void setPlanId(long planId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planId = planId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlanId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("planId"));
	}

	@JSON
	@Override
	public String getBenefitValue() {
		if (_benefitValue == null) {
			return "";
		}
		else {
			return _benefitValue;
		}
	}

	@Override
	public void setBenefitValue(String benefitValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitValue = benefitValue;
	}

	@JSON
	@Override
	public String getBenefitValueUSD() {
		if (_benefitValueUSD == null) {
			return "";
		}
		else {
			return _benefitValueUSD;
		}
	}

	@Override
	public void setBenefitValueUSD(String benefitValueUSD) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitValueUSD = benefitValueUSD;
	}

	@JSON
	@Override
	public int getSort() {
		return _sort;
	}

	@Override
	public void setSort(int sort) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sort = sort;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), StiBenefitValueMapping.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StiBenefitValueMapping toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, StiBenefitValueMapping>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StiBenefitValueMappingImpl stiBenefitValueMappingImpl =
			new StiBenefitValueMappingImpl();

		stiBenefitValueMappingImpl.setBenefitValueMappingId(
			getBenefitValueMappingId());
		stiBenefitValueMappingImpl.setBenefitTypeId(getBenefitTypeId());
		stiBenefitValueMappingImpl.setBenefitId(getBenefitId());
		stiBenefitValueMappingImpl.setPlanId(getPlanId());
		stiBenefitValueMappingImpl.setBenefitValue(getBenefitValue());
		stiBenefitValueMappingImpl.setBenefitValueUSD(getBenefitValueUSD());
		stiBenefitValueMappingImpl.setSort(getSort());
		stiBenefitValueMappingImpl.setActive(getActive());
		stiBenefitValueMappingImpl.setGroupId(getGroupId());
		stiBenefitValueMappingImpl.setCompanyId(getCompanyId());
		stiBenefitValueMappingImpl.setUserId(getUserId());
		stiBenefitValueMappingImpl.setUserName(getUserName());
		stiBenefitValueMappingImpl.setCreateDate(getCreateDate());
		stiBenefitValueMappingImpl.setModifiedDate(getModifiedDate());

		stiBenefitValueMappingImpl.resetOriginalValues();

		return stiBenefitValueMappingImpl;
	}

	@Override
	public int compareTo(StiBenefitValueMapping stiBenefitValueMapping) {
		long primaryKey = stiBenefitValueMapping.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof StiBenefitValueMapping)) {
			return false;
		}

		StiBenefitValueMapping stiBenefitValueMapping =
			(StiBenefitValueMapping)object;

		long primaryKey = stiBenefitValueMapping.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<StiBenefitValueMapping> toCacheModel() {
		StiBenefitValueMappingCacheModel stiBenefitValueMappingCacheModel =
			new StiBenefitValueMappingCacheModel();

		stiBenefitValueMappingCacheModel.benefitValueMappingId =
			getBenefitValueMappingId();

		stiBenefitValueMappingCacheModel.benefitTypeId = getBenefitTypeId();

		stiBenefitValueMappingCacheModel.benefitId = getBenefitId();

		stiBenefitValueMappingCacheModel.planId = getPlanId();

		stiBenefitValueMappingCacheModel.benefitValue = getBenefitValue();

		String benefitValue = stiBenefitValueMappingCacheModel.benefitValue;

		if ((benefitValue != null) && (benefitValue.length() == 0)) {
			stiBenefitValueMappingCacheModel.benefitValue = null;
		}

		stiBenefitValueMappingCacheModel.benefitValueUSD = getBenefitValueUSD();

		String benefitValueUSD =
			stiBenefitValueMappingCacheModel.benefitValueUSD;

		if ((benefitValueUSD != null) && (benefitValueUSD.length() == 0)) {
			stiBenefitValueMappingCacheModel.benefitValueUSD = null;
		}

		stiBenefitValueMappingCacheModel.sort = getSort();

		stiBenefitValueMappingCacheModel.active = getActive();

		stiBenefitValueMappingCacheModel.groupId = getGroupId();

		stiBenefitValueMappingCacheModel.companyId = getCompanyId();

		stiBenefitValueMappingCacheModel.userId = getUserId();

		stiBenefitValueMappingCacheModel.userName = getUserName();

		String userName = stiBenefitValueMappingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			stiBenefitValueMappingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			stiBenefitValueMappingCacheModel.createDate = createDate.getTime();
		}
		else {
			stiBenefitValueMappingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			stiBenefitValueMappingCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			stiBenefitValueMappingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return stiBenefitValueMappingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<StiBenefitValueMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<StiBenefitValueMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StiBenefitValueMapping, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(StiBenefitValueMapping)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<StiBenefitValueMapping, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<StiBenefitValueMapping, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StiBenefitValueMapping, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((StiBenefitValueMapping)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, StiBenefitValueMapping>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					StiBenefitValueMapping.class, ModelWrapper.class);

	}

	private long _benefitValueMappingId;
	private long _benefitTypeId;
	private long _benefitId;
	private long _planId;
	private String _benefitValue;
	private String _benefitValueUSD;
	private int _sort;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<StiBenefitValueMapping, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((StiBenefitValueMapping)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"benefitValueMappingId", _benefitValueMappingId);
		_columnOriginalValues.put("benefitTypeId", _benefitTypeId);
		_columnOriginalValues.put("benefitId", _benefitId);
		_columnOriginalValues.put("planId", _planId);
		_columnOriginalValues.put("benefitValue", _benefitValue);
		_columnOriginalValues.put("benefitValueUSD", _benefitValueUSD);
		_columnOriginalValues.put("sort", _sort);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("benefitValueMappingId", 1L);

		columnBitmasks.put("benefitTypeId", 2L);

		columnBitmasks.put("benefitId", 4L);

		columnBitmasks.put("planId", 8L);

		columnBitmasks.put("benefitValue", 16L);

		columnBitmasks.put("benefitValueUSD", 32L);

		columnBitmasks.put("sort", 64L);

		columnBitmasks.put("active_", 128L);

		columnBitmasks.put("groupId", 256L);

		columnBitmasks.put("companyId", 512L);

		columnBitmasks.put("userId", 1024L);

		columnBitmasks.put("userName", 2048L);

		columnBitmasks.put("createDate", 4096L);

		columnBitmasks.put("modifiedDate", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private StiBenefitValueMapping _escapedModel;

}