/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.StiBenefit;
import com.mypage.admin.product.model.StiBenefitModel;
import com.mypage.admin.product.model.StiBenefitSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the StiBenefit service. Represents a row in the &quot;StiBenefit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StiBenefitModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StiBenefitImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see StiBenefitImpl
 * @generated
 */
@JSON(strict = true)
public class StiBenefitModelImpl
	extends BaseModelImpl<StiBenefit> implements StiBenefitModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sti benefit model instance should use the <code>StiBenefit</code> interface instead.
	 */
	public static final String TABLE_NAME = "StiBenefit";

	public static final Object[][] TABLE_COLUMNS = {
		{"benefitId", Types.BIGINT}, {"nameId", Types.VARCHAR},
		{"nameEn", Types.VARCHAR}, {"sort", Types.INTEGER},
		{"benefitTypeId", Types.BIGINT}, {"active_", Types.INTEGER},
		{"planName", Types.VARCHAR}, {"benefitValue", Types.VARCHAR},
		{"externalCode", Types.VARCHAR}, {"benefitDescription", Types.VARCHAR},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("benefitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nameId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nameEn", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sort", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("benefitTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("planName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("benefitValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("benefitDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table StiBenefit (benefitId LONG not null primary key,nameId VARCHAR(75) null,nameEn VARCHAR(75) null,sort INTEGER,benefitTypeId LONG,active_ INTEGER,planName VARCHAR(75) null,benefitValue VARCHAR(75) null,externalCode VARCHAR(75) null,benefitDescription VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table StiBenefit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY stiBenefit.benefitId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY StiBenefit.benefitId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BENEFITID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static StiBenefit toModel(StiBenefitSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StiBenefit model = new StiBenefitImpl();

		model.setBenefitId(soapModel.getBenefitId());
		model.setNameId(soapModel.getNameId());
		model.setNameEn(soapModel.getNameEn());
		model.setSort(soapModel.getSort());
		model.setBenefitTypeId(soapModel.getBenefitTypeId());
		model.setActive(soapModel.getActive());
		model.setPlanName(soapModel.getPlanName());
		model.setBenefitValue(soapModel.getBenefitValue());
		model.setExternalCode(soapModel.getExternalCode());
		model.setBenefitDescription(soapModel.getBenefitDescription());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<StiBenefit> toModels(StiBenefitSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StiBenefit> models = new ArrayList<StiBenefit>(soapModels.length);

		for (StiBenefitSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public StiBenefitModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _benefitId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBenefitId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _benefitId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StiBenefit.class;
	}

	@Override
	public String getModelClassName() {
		return StiBenefit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<StiBenefit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<StiBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StiBenefit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((StiBenefit)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<StiBenefit, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<StiBenefit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(StiBenefit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<StiBenefit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<StiBenefit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<StiBenefit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<StiBenefit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<StiBenefit, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<StiBenefit, Object>>();
		Map<String, BiConsumer<StiBenefit, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<StiBenefit, ?>>();

		attributeGetterFunctions.put("benefitId", StiBenefit::getBenefitId);
		attributeSetterBiConsumers.put(
			"benefitId",
			(BiConsumer<StiBenefit, Long>)StiBenefit::setBenefitId);
		attributeGetterFunctions.put("nameId", StiBenefit::getNameId);
		attributeSetterBiConsumers.put(
			"nameId", (BiConsumer<StiBenefit, String>)StiBenefit::setNameId);
		attributeGetterFunctions.put("nameEn", StiBenefit::getNameEn);
		attributeSetterBiConsumers.put(
			"nameEn", (BiConsumer<StiBenefit, String>)StiBenefit::setNameEn);
		attributeGetterFunctions.put("sort", StiBenefit::getSort);
		attributeSetterBiConsumers.put(
			"sort", (BiConsumer<StiBenefit, Integer>)StiBenefit::setSort);
		attributeGetterFunctions.put(
			"benefitTypeId", StiBenefit::getBenefitTypeId);
		attributeSetterBiConsumers.put(
			"benefitTypeId",
			(BiConsumer<StiBenefit, Long>)StiBenefit::setBenefitTypeId);
		attributeGetterFunctions.put("active", StiBenefit::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<StiBenefit, Integer>)StiBenefit::setActive);
		attributeGetterFunctions.put("planName", StiBenefit::getPlanName);
		attributeSetterBiConsumers.put(
			"planName",
			(BiConsumer<StiBenefit, String>)StiBenefit::setPlanName);
		attributeGetterFunctions.put(
			"benefitValue", StiBenefit::getBenefitValue);
		attributeSetterBiConsumers.put(
			"benefitValue",
			(BiConsumer<StiBenefit, String>)StiBenefit::setBenefitValue);
		attributeGetterFunctions.put(
			"externalCode", StiBenefit::getExternalCode);
		attributeSetterBiConsumers.put(
			"externalCode",
			(BiConsumer<StiBenefit, String>)StiBenefit::setExternalCode);
		attributeGetterFunctions.put(
			"benefitDescription", StiBenefit::getBenefitDescription);
		attributeSetterBiConsumers.put(
			"benefitDescription",
			(BiConsumer<StiBenefit, String>)StiBenefit::setBenefitDescription);
		attributeGetterFunctions.put("groupId", StiBenefit::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<StiBenefit, Long>)StiBenefit::setGroupId);
		attributeGetterFunctions.put("companyId", StiBenefit::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<StiBenefit, Long>)StiBenefit::setCompanyId);
		attributeGetterFunctions.put("userId", StiBenefit::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<StiBenefit, Long>)StiBenefit::setUserId);
		attributeGetterFunctions.put("userName", StiBenefit::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<StiBenefit, String>)StiBenefit::setUserName);
		attributeGetterFunctions.put("createDate", StiBenefit::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<StiBenefit, Date>)StiBenefit::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", StiBenefit::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<StiBenefit, Date>)StiBenefit::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getBenefitId() {
		return _benefitId;
	}

	@Override
	public void setBenefitId(long benefitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitId = benefitId;
	}

	@JSON
	@Override
	public String getNameId() {
		if (_nameId == null) {
			return "";
		}
		else {
			return _nameId;
		}
	}

	@Override
	public void setNameId(String nameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameId = nameId;
	}

	@JSON
	@Override
	public String getNameEn() {
		if (_nameEn == null) {
			return "";
		}
		else {
			return _nameEn;
		}
	}

	@Override
	public void setNameEn(String nameEn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nameEn = nameEn;
	}

	@JSON
	@Override
	public int getSort() {
		return _sort;
	}

	@Override
	public void setSort(int sort) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sort = sort;
	}

	@JSON
	@Override
	public long getBenefitTypeId() {
		return _benefitTypeId;
	}

	@Override
	public void setBenefitTypeId(long benefitTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitTypeId = benefitTypeId;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public String getPlanName() {
		if (_planName == null) {
			return "";
		}
		else {
			return _planName;
		}
	}

	@Override
	public void setPlanName(String planName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_planName = planName;
	}

	@JSON
	@Override
	public String getBenefitValue() {
		if (_benefitValue == null) {
			return "";
		}
		else {
			return _benefitValue;
		}
	}

	@Override
	public void setBenefitValue(String benefitValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitValue = benefitValue;
	}

	@JSON
	@Override
	public String getExternalCode() {
		if (_externalCode == null) {
			return "";
		}
		else {
			return _externalCode;
		}
	}

	@Override
	public void setExternalCode(String externalCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalCode = externalCode;
	}

	@JSON
	@Override
	public String getBenefitDescription() {
		if (_benefitDescription == null) {
			return "";
		}
		else {
			return _benefitDescription;
		}
	}

	@Override
	public void setBenefitDescription(String benefitDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitDescription = benefitDescription;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), StiBenefit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StiBenefit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, StiBenefit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StiBenefitImpl stiBenefitImpl = new StiBenefitImpl();

		stiBenefitImpl.setBenefitId(getBenefitId());
		stiBenefitImpl.setNameId(getNameId());
		stiBenefitImpl.setNameEn(getNameEn());
		stiBenefitImpl.setSort(getSort());
		stiBenefitImpl.setBenefitTypeId(getBenefitTypeId());
		stiBenefitImpl.setActive(getActive());
		stiBenefitImpl.setPlanName(getPlanName());
		stiBenefitImpl.setBenefitValue(getBenefitValue());
		stiBenefitImpl.setExternalCode(getExternalCode());
		stiBenefitImpl.setBenefitDescription(getBenefitDescription());
		stiBenefitImpl.setGroupId(getGroupId());
		stiBenefitImpl.setCompanyId(getCompanyId());
		stiBenefitImpl.setUserId(getUserId());
		stiBenefitImpl.setUserName(getUserName());
		stiBenefitImpl.setCreateDate(getCreateDate());
		stiBenefitImpl.setModifiedDate(getModifiedDate());

		stiBenefitImpl.resetOriginalValues();

		return stiBenefitImpl;
	}

	@Override
	public int compareTo(StiBenefit stiBenefit) {
		long primaryKey = stiBenefit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof StiBenefit)) {
			return false;
		}

		StiBenefit stiBenefit = (StiBenefit)object;

		long primaryKey = stiBenefit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<StiBenefit> toCacheModel() {
		StiBenefitCacheModel stiBenefitCacheModel = new StiBenefitCacheModel();

		stiBenefitCacheModel.benefitId = getBenefitId();

		stiBenefitCacheModel.nameId = getNameId();

		String nameId = stiBenefitCacheModel.nameId;

		if ((nameId != null) && (nameId.length() == 0)) {
			stiBenefitCacheModel.nameId = null;
		}

		stiBenefitCacheModel.nameEn = getNameEn();

		String nameEn = stiBenefitCacheModel.nameEn;

		if ((nameEn != null) && (nameEn.length() == 0)) {
			stiBenefitCacheModel.nameEn = null;
		}

		stiBenefitCacheModel.sort = getSort();

		stiBenefitCacheModel.benefitTypeId = getBenefitTypeId();

		stiBenefitCacheModel.active = getActive();

		stiBenefitCacheModel.planName = getPlanName();

		String planName = stiBenefitCacheModel.planName;

		if ((planName != null) && (planName.length() == 0)) {
			stiBenefitCacheModel.planName = null;
		}

		stiBenefitCacheModel.benefitValue = getBenefitValue();

		String benefitValue = stiBenefitCacheModel.benefitValue;

		if ((benefitValue != null) && (benefitValue.length() == 0)) {
			stiBenefitCacheModel.benefitValue = null;
		}

		stiBenefitCacheModel.externalCode = getExternalCode();

		String externalCode = stiBenefitCacheModel.externalCode;

		if ((externalCode != null) && (externalCode.length() == 0)) {
			stiBenefitCacheModel.externalCode = null;
		}

		stiBenefitCacheModel.benefitDescription = getBenefitDescription();

		String benefitDescription = stiBenefitCacheModel.benefitDescription;

		if ((benefitDescription != null) &&
			(benefitDescription.length() == 0)) {

			stiBenefitCacheModel.benefitDescription = null;
		}

		stiBenefitCacheModel.groupId = getGroupId();

		stiBenefitCacheModel.companyId = getCompanyId();

		stiBenefitCacheModel.userId = getUserId();

		stiBenefitCacheModel.userName = getUserName();

		String userName = stiBenefitCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			stiBenefitCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			stiBenefitCacheModel.createDate = createDate.getTime();
		}
		else {
			stiBenefitCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			stiBenefitCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			stiBenefitCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return stiBenefitCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<StiBenefit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<StiBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StiBenefit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((StiBenefit)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<StiBenefit, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<StiBenefit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<StiBenefit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((StiBenefit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, StiBenefit>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					StiBenefit.class, ModelWrapper.class);

	}

	private long _benefitId;
	private String _nameId;
	private String _nameEn;
	private int _sort;
	private long _benefitTypeId;
	private int _active;
	private String _planName;
	private String _benefitValue;
	private String _externalCode;
	private String _benefitDescription;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<StiBenefit, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((StiBenefit)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("benefitId", _benefitId);
		_columnOriginalValues.put("nameId", _nameId);
		_columnOriginalValues.put("nameEn", _nameEn);
		_columnOriginalValues.put("sort", _sort);
		_columnOriginalValues.put("benefitTypeId", _benefitTypeId);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("planName", _planName);
		_columnOriginalValues.put("benefitValue", _benefitValue);
		_columnOriginalValues.put("externalCode", _externalCode);
		_columnOriginalValues.put("benefitDescription", _benefitDescription);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("benefitId", 1L);

		columnBitmasks.put("nameId", 2L);

		columnBitmasks.put("nameEn", 4L);

		columnBitmasks.put("sort", 8L);

		columnBitmasks.put("benefitTypeId", 16L);

		columnBitmasks.put("active_", 32L);

		columnBitmasks.put("planName", 64L);

		columnBitmasks.put("benefitValue", 128L);

		columnBitmasks.put("externalCode", 256L);

		columnBitmasks.put("benefitDescription", 512L);

		columnBitmasks.put("groupId", 1024L);

		columnBitmasks.put("companyId", 2048L);

		columnBitmasks.put("userId", 4096L);

		columnBitmasks.put("userName", 8192L);

		columnBitmasks.put("createDate", 16384L);

		columnBitmasks.put("modifiedDate", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private StiBenefit _escapedModel;

}