/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.TravelDomesticPremi;
import com.mypage.admin.product.model.TravelDomesticPremiModel;
import com.mypage.admin.product.model.TravelDomesticPremiSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TravelDomesticPremi service. Represents a row in the &quot;TravelDomesticPremi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TravelDomesticPremiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TravelDomesticPremiImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see TravelDomesticPremiImpl
 * @generated
 */
@JSON(strict = true)
public class TravelDomesticPremiModelImpl
	extends BaseModelImpl<TravelDomesticPremi>
	implements TravelDomesticPremiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a travel domestic premi model instance should use the <code>TravelDomesticPremi</code> interface instead.
	 */
	public static final String TABLE_NAME = "TravelDomesticPremi";

	public static final Object[][] TABLE_COLUMNS = {
		{"travelDomesticPremiId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"duration", Types.INTEGER},
		{"plan", Types.VARCHAR}, {"insuredType", Types.VARCHAR},
		{"currency_", Types.VARCHAR}, {"amount", Types.BIGINT},
		{"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("travelDomesticPremiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("duration", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("plan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("insuredType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("currency_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("amount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TravelDomesticPremi (travelDomesticPremiId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,duration INTEGER,plan VARCHAR(75) null,insuredType VARCHAR(75) null,currency_ VARCHAR(75) null,amount LONG,active_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table TravelDomesticPremi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY travelDomesticPremi.travelDomesticPremiId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TravelDomesticPremi.travelDomesticPremiId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DURATION_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INSUREDTYPE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PLAN_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAVELDOMESTICPREMIID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static TravelDomesticPremi toModel(
		TravelDomesticPremiSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		TravelDomesticPremi model = new TravelDomesticPremiImpl();

		model.setTravelDomesticPremiId(soapModel.getTravelDomesticPremiId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDuration(soapModel.getDuration());
		model.setPlan(soapModel.getPlan());
		model.setInsuredType(soapModel.getInsuredType());
		model.setCurrency(soapModel.getCurrency());
		model.setAmount(soapModel.getAmount());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<TravelDomesticPremi> toModels(
		TravelDomesticPremiSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<TravelDomesticPremi> models = new ArrayList<TravelDomesticPremi>(
			soapModels.length);

		for (TravelDomesticPremiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TravelDomesticPremiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _travelDomesticPremiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTravelDomesticPremiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _travelDomesticPremiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TravelDomesticPremi.class;
	}

	@Override
	public String getModelClassName() {
		return TravelDomesticPremi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TravelDomesticPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TravelDomesticPremi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelDomesticPremi, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TravelDomesticPremi)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TravelDomesticPremi, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TravelDomesticPremi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TravelDomesticPremi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TravelDomesticPremi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TravelDomesticPremi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TravelDomesticPremi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TravelDomesticPremi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TravelDomesticPremi, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TravelDomesticPremi, Object>>();
		Map<String, BiConsumer<TravelDomesticPremi, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TravelDomesticPremi, ?>>();

		attributeGetterFunctions.put(
			"travelDomesticPremiId",
			TravelDomesticPremi::getTravelDomesticPremiId);
		attributeSetterBiConsumers.put(
			"travelDomesticPremiId",
			(BiConsumer<TravelDomesticPremi, Long>)
				TravelDomesticPremi::setTravelDomesticPremiId);
		attributeGetterFunctions.put(
			"groupId", TravelDomesticPremi::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TravelDomesticPremi, Long>)
				TravelDomesticPremi::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TravelDomesticPremi::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TravelDomesticPremi, Long>)
				TravelDomesticPremi::setCompanyId);
		attributeGetterFunctions.put("userId", TravelDomesticPremi::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<TravelDomesticPremi, Long>)
				TravelDomesticPremi::setUserId);
		attributeGetterFunctions.put(
			"userName", TravelDomesticPremi::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TravelDomesticPremi, String>)
				TravelDomesticPremi::setUserName);
		attributeGetterFunctions.put(
			"createDate", TravelDomesticPremi::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TravelDomesticPremi, Date>)
				TravelDomesticPremi::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TravelDomesticPremi::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TravelDomesticPremi, Date>)
				TravelDomesticPremi::setModifiedDate);
		attributeGetterFunctions.put(
			"duration", TravelDomesticPremi::getDuration);
		attributeSetterBiConsumers.put(
			"duration",
			(BiConsumer<TravelDomesticPremi, Integer>)
				TravelDomesticPremi::setDuration);
		attributeGetterFunctions.put("plan", TravelDomesticPremi::getPlan);
		attributeSetterBiConsumers.put(
			"plan",
			(BiConsumer<TravelDomesticPremi, String>)
				TravelDomesticPremi::setPlan);
		attributeGetterFunctions.put(
			"insuredType", TravelDomesticPremi::getInsuredType);
		attributeSetterBiConsumers.put(
			"insuredType",
			(BiConsumer<TravelDomesticPremi, String>)
				TravelDomesticPremi::setInsuredType);
		attributeGetterFunctions.put(
			"currency", TravelDomesticPremi::getCurrency);
		attributeSetterBiConsumers.put(
			"currency",
			(BiConsumer<TravelDomesticPremi, String>)
				TravelDomesticPremi::setCurrency);
		attributeGetterFunctions.put("amount", TravelDomesticPremi::getAmount);
		attributeSetterBiConsumers.put(
			"amount",
			(BiConsumer<TravelDomesticPremi, Long>)
				TravelDomesticPremi::setAmount);
		attributeGetterFunctions.put("active", TravelDomesticPremi::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<TravelDomesticPremi, Integer>)
				TravelDomesticPremi::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTravelDomesticPremiId() {
		return _travelDomesticPremiId;
	}

	@Override
	public void setTravelDomesticPremiId(long travelDomesticPremiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelDomesticPremiId = travelDomesticPremiId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getDuration() {
		return _duration;
	}

	@Override
	public void setDuration(int duration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_duration = duration;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalDuration() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("duration"));
	}

	@JSON
	@Override
	public String getPlan() {
		if (_plan == null) {
			return "";
		}
		else {
			return _plan;
		}
	}

	@Override
	public void setPlan(String plan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_plan = plan;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPlan() {
		return getColumnOriginalValue("plan");
	}

	@JSON
	@Override
	public String getInsuredType() {
		if (_insuredType == null) {
			return "";
		}
		else {
			return _insuredType;
		}
	}

	@Override
	public void setInsuredType(String insuredType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuredType = insuredType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalInsuredType() {
		return getColumnOriginalValue("insuredType");
	}

	@JSON
	@Override
	public String getCurrency() {
		if (_currency == null) {
			return "";
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currency = currency;
	}

	@JSON
	@Override
	public Long getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(Long amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TravelDomesticPremi.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TravelDomesticPremi toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TravelDomesticPremi>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TravelDomesticPremiImpl travelDomesticPremiImpl =
			new TravelDomesticPremiImpl();

		travelDomesticPremiImpl.setTravelDomesticPremiId(
			getTravelDomesticPremiId());
		travelDomesticPremiImpl.setGroupId(getGroupId());
		travelDomesticPremiImpl.setCompanyId(getCompanyId());
		travelDomesticPremiImpl.setUserId(getUserId());
		travelDomesticPremiImpl.setUserName(getUserName());
		travelDomesticPremiImpl.setCreateDate(getCreateDate());
		travelDomesticPremiImpl.setModifiedDate(getModifiedDate());
		travelDomesticPremiImpl.setDuration(getDuration());
		travelDomesticPremiImpl.setPlan(getPlan());
		travelDomesticPremiImpl.setInsuredType(getInsuredType());
		travelDomesticPremiImpl.setCurrency(getCurrency());
		travelDomesticPremiImpl.setAmount(getAmount());
		travelDomesticPremiImpl.setActive(getActive());

		travelDomesticPremiImpl.resetOriginalValues();

		return travelDomesticPremiImpl;
	}

	@Override
	public int compareTo(TravelDomesticPremi travelDomesticPremi) {
		int value = 0;

		if (getTravelDomesticPremiId() <
				travelDomesticPremi.getTravelDomesticPremiId()) {

			value = -1;
		}
		else if (getTravelDomesticPremiId() >
					travelDomesticPremi.getTravelDomesticPremiId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TravelDomesticPremi)) {
			return false;
		}

		TravelDomesticPremi travelDomesticPremi = (TravelDomesticPremi)object;

		long primaryKey = travelDomesticPremi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TravelDomesticPremi> toCacheModel() {
		TravelDomesticPremiCacheModel travelDomesticPremiCacheModel =
			new TravelDomesticPremiCacheModel();

		travelDomesticPremiCacheModel.travelDomesticPremiId =
			getTravelDomesticPremiId();

		travelDomesticPremiCacheModel.groupId = getGroupId();

		travelDomesticPremiCacheModel.companyId = getCompanyId();

		travelDomesticPremiCacheModel.userId = getUserId();

		travelDomesticPremiCacheModel.userName = getUserName();

		String userName = travelDomesticPremiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			travelDomesticPremiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			travelDomesticPremiCacheModel.createDate = createDate.getTime();
		}
		else {
			travelDomesticPremiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			travelDomesticPremiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			travelDomesticPremiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		travelDomesticPremiCacheModel.duration = getDuration();

		travelDomesticPremiCacheModel.plan = getPlan();

		String plan = travelDomesticPremiCacheModel.plan;

		if ((plan != null) && (plan.length() == 0)) {
			travelDomesticPremiCacheModel.plan = null;
		}

		travelDomesticPremiCacheModel.insuredType = getInsuredType();

		String insuredType = travelDomesticPremiCacheModel.insuredType;

		if ((insuredType != null) && (insuredType.length() == 0)) {
			travelDomesticPremiCacheModel.insuredType = null;
		}

		travelDomesticPremiCacheModel.currency = getCurrency();

		String currency = travelDomesticPremiCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			travelDomesticPremiCacheModel.currency = null;
		}

		Long amount = getAmount();

		if (amount != null) {
			travelDomesticPremiCacheModel.amount = amount;
		}

		travelDomesticPremiCacheModel.active = getActive();

		return travelDomesticPremiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TravelDomesticPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TravelDomesticPremi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelDomesticPremi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TravelDomesticPremi)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TravelDomesticPremi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TravelDomesticPremi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelDomesticPremi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TravelDomesticPremi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TravelDomesticPremi>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TravelDomesticPremi.class, ModelWrapper.class);

	}

	private long _travelDomesticPremiId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _duration;
	private String _plan;
	private String _insuredType;
	private String _currency;
	private Long _amount;
	private int _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TravelDomesticPremi, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TravelDomesticPremi)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"travelDomesticPremiId", _travelDomesticPremiId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("duration", _duration);
		_columnOriginalValues.put("plan", _plan);
		_columnOriginalValues.put("insuredType", _insuredType);
		_columnOriginalValues.put("currency_", _currency);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("currency_", "currency");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("travelDomesticPremiId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("duration", 128L);

		columnBitmasks.put("plan", 256L);

		columnBitmasks.put("insuredType", 512L);

		columnBitmasks.put("currency_", 1024L);

		columnBitmasks.put("amount", 2048L);

		columnBitmasks.put("active_", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TravelDomesticPremi _escapedModel;

}