/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.TravelDomesticInsuredType;
import com.mypage.admin.product.model.TravelDomesticInsuredTypeModel;
import com.mypage.admin.product.model.TravelDomesticInsuredTypeSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TravelDomesticInsuredType service. Represents a row in the &quot;TravelDomesticInsuredType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TravelDomesticInsuredTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TravelDomesticInsuredTypeImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see TravelDomesticInsuredTypeImpl
 * @generated
 */
@JSON(strict = true)
public class TravelDomesticInsuredTypeModelImpl
	extends BaseModelImpl<TravelDomesticInsuredType>
	implements TravelDomesticInsuredTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a travel domestic insured type model instance should use the <code>TravelDomesticInsuredType</code> interface instead.
	 */
	public static final String TABLE_NAME = "TravelDomesticInsuredType";

	public static final Object[][] TABLE_COLUMNS = {
		{"travelDomesticInsuredTypeId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"code_", Types.VARCHAR},
		{"active_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("travelDomesticInsuredTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TravelDomesticInsuredType (travelDomesticInsuredTypeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,code_ VARCHAR(75) null,active_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table TravelDomesticInsuredType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY travelDomesticInsuredType.travelDomesticInsuredTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TravelDomesticInsuredType.travelDomesticInsuredTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAVELDOMESTICINSUREDTYPEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static TravelDomesticInsuredType toModel(
		TravelDomesticInsuredTypeSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		TravelDomesticInsuredType model = new TravelDomesticInsuredTypeImpl();

		model.setTravelDomesticInsuredTypeId(
			soapModel.getTravelDomesticInsuredTypeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setCode(soapModel.getCode());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<TravelDomesticInsuredType> toModels(
		TravelDomesticInsuredTypeSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<TravelDomesticInsuredType> models =
			new ArrayList<TravelDomesticInsuredType>(soapModels.length);

		for (TravelDomesticInsuredTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TravelDomesticInsuredTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _travelDomesticInsuredTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTravelDomesticInsuredTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _travelDomesticInsuredTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TravelDomesticInsuredType.class;
	}

	@Override
	public String getModelClassName() {
		return TravelDomesticInsuredType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TravelDomesticInsuredType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TravelDomesticInsuredType, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelDomesticInsuredType, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TravelDomesticInsuredType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TravelDomesticInsuredType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TravelDomesticInsuredType, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TravelDomesticInsuredType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TravelDomesticInsuredType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TravelDomesticInsuredType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<TravelDomesticInsuredType, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<TravelDomesticInsuredType, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<TravelDomesticInsuredType, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TravelDomesticInsuredType, Object>>();
		Map<String, BiConsumer<TravelDomesticInsuredType, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TravelDomesticInsuredType, ?>>();

		attributeGetterFunctions.put(
			"travelDomesticInsuredTypeId",
			TravelDomesticInsuredType::getTravelDomesticInsuredTypeId);
		attributeSetterBiConsumers.put(
			"travelDomesticInsuredTypeId",
			(BiConsumer<TravelDomesticInsuredType, Long>)
				TravelDomesticInsuredType::setTravelDomesticInsuredTypeId);
		attributeGetterFunctions.put(
			"groupId", TravelDomesticInsuredType::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TravelDomesticInsuredType, Long>)
				TravelDomesticInsuredType::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TravelDomesticInsuredType::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TravelDomesticInsuredType, Long>)
				TravelDomesticInsuredType::setCompanyId);
		attributeGetterFunctions.put(
			"userId", TravelDomesticInsuredType::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<TravelDomesticInsuredType, Long>)
				TravelDomesticInsuredType::setUserId);
		attributeGetterFunctions.put(
			"userName", TravelDomesticInsuredType::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TravelDomesticInsuredType, String>)
				TravelDomesticInsuredType::setUserName);
		attributeGetterFunctions.put(
			"createDate", TravelDomesticInsuredType::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TravelDomesticInsuredType, Date>)
				TravelDomesticInsuredType::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TravelDomesticInsuredType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TravelDomesticInsuredType, Date>)
				TravelDomesticInsuredType::setModifiedDate);
		attributeGetterFunctions.put(
			"name", TravelDomesticInsuredType::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<TravelDomesticInsuredType, String>)
				TravelDomesticInsuredType::setName);
		attributeGetterFunctions.put(
			"code", TravelDomesticInsuredType::getCode);
		attributeSetterBiConsumers.put(
			"code",
			(BiConsumer<TravelDomesticInsuredType, String>)
				TravelDomesticInsuredType::setCode);
		attributeGetterFunctions.put(
			"active", TravelDomesticInsuredType::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<TravelDomesticInsuredType, Integer>)
				TravelDomesticInsuredType::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTravelDomesticInsuredTypeId() {
		return _travelDomesticInsuredTypeId;
	}

	@Override
	public void setTravelDomesticInsuredTypeId(
		long travelDomesticInsuredTypeId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelDomesticInsuredTypeId = travelDomesticInsuredTypeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTravelDomesticInsuredTypeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("travelDomesticInsuredTypeId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCode() {
		return getColumnOriginalValue("code_");
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TravelDomesticInsuredType.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TravelDomesticInsuredType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TravelDomesticInsuredType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TravelDomesticInsuredTypeImpl travelDomesticInsuredTypeImpl =
			new TravelDomesticInsuredTypeImpl();

		travelDomesticInsuredTypeImpl.setTravelDomesticInsuredTypeId(
			getTravelDomesticInsuredTypeId());
		travelDomesticInsuredTypeImpl.setGroupId(getGroupId());
		travelDomesticInsuredTypeImpl.setCompanyId(getCompanyId());
		travelDomesticInsuredTypeImpl.setUserId(getUserId());
		travelDomesticInsuredTypeImpl.setUserName(getUserName());
		travelDomesticInsuredTypeImpl.setCreateDate(getCreateDate());
		travelDomesticInsuredTypeImpl.setModifiedDate(getModifiedDate());
		travelDomesticInsuredTypeImpl.setName(getName());
		travelDomesticInsuredTypeImpl.setCode(getCode());
		travelDomesticInsuredTypeImpl.setActive(getActive());

		travelDomesticInsuredTypeImpl.resetOriginalValues();

		return travelDomesticInsuredTypeImpl;
	}

	@Override
	public int compareTo(TravelDomesticInsuredType travelDomesticInsuredType) {
		long primaryKey = travelDomesticInsuredType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TravelDomesticInsuredType)) {
			return false;
		}

		TravelDomesticInsuredType travelDomesticInsuredType =
			(TravelDomesticInsuredType)object;

		long primaryKey = travelDomesticInsuredType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TravelDomesticInsuredType> toCacheModel() {
		TravelDomesticInsuredTypeCacheModel
			travelDomesticInsuredTypeCacheModel =
				new TravelDomesticInsuredTypeCacheModel();

		travelDomesticInsuredTypeCacheModel.travelDomesticInsuredTypeId =
			getTravelDomesticInsuredTypeId();

		travelDomesticInsuredTypeCacheModel.groupId = getGroupId();

		travelDomesticInsuredTypeCacheModel.companyId = getCompanyId();

		travelDomesticInsuredTypeCacheModel.userId = getUserId();

		travelDomesticInsuredTypeCacheModel.userName = getUserName();

		String userName = travelDomesticInsuredTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			travelDomesticInsuredTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			travelDomesticInsuredTypeCacheModel.createDate =
				createDate.getTime();
		}
		else {
			travelDomesticInsuredTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			travelDomesticInsuredTypeCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			travelDomesticInsuredTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		travelDomesticInsuredTypeCacheModel.name = getName();

		String name = travelDomesticInsuredTypeCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			travelDomesticInsuredTypeCacheModel.name = null;
		}

		travelDomesticInsuredTypeCacheModel.code = getCode();

		String code = travelDomesticInsuredTypeCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			travelDomesticInsuredTypeCacheModel.code = null;
		}

		travelDomesticInsuredTypeCacheModel.active = getActive();

		return travelDomesticInsuredTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TravelDomesticInsuredType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TravelDomesticInsuredType, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelDomesticInsuredType, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TravelDomesticInsuredType)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TravelDomesticInsuredType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TravelDomesticInsuredType, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelDomesticInsuredType, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((TravelDomesticInsuredType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, TravelDomesticInsuredType>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						TravelDomesticInsuredType.class, ModelWrapper.class);

	}

	private long _travelDomesticInsuredTypeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _code;
	private int _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TravelDomesticInsuredType, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TravelDomesticInsuredType)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"travelDomesticInsuredTypeId", _travelDomesticInsuredTypeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("code_", _code);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("code_", "code");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("travelDomesticInsuredTypeId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("code_", 256L);

		columnBitmasks.put("active_", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TravelDomesticInsuredType _escapedModel;

}