/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.mypage.admin.product.model.TravelInternationalPremi;
import com.mypage.admin.product.service.TravelInternationalPremiLocalServiceUtil;

/**
 * The extended model base implementation for the TravelInternationalPremi service. Represents a row in the &quot;TravelInternationalPremi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TravelInternationalPremiImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see TravelInternationalPremiImpl
 * @see TravelInternationalPremi
 * @generated
 */
public abstract class TravelInternationalPremiBaseImpl
	extends TravelInternationalPremiModelImpl
	implements TravelInternationalPremi {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a travel international premi model instance should use the <code>TravelInternationalPremi</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TravelInternationalPremiLocalServiceUtil.
				addTravelInternationalPremi(this);
		}
		else {
			TravelInternationalPremiLocalServiceUtil.
				updateTravelInternationalPremi(this);
		}
	}

}