/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mypage.admin.product.model.TravelIntBenefitValue;
import com.mypage.admin.product.model.TravelIntBenefitValueModel;
import com.mypage.admin.product.model.TravelIntBenefitValueSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TravelIntBenefitValue service. Represents a row in the &quot;TravelIntBenefitValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TravelIntBenefitValueModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TravelIntBenefitValueImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see TravelIntBenefitValueImpl
 * @generated
 */
@JSON(strict = true)
public class TravelIntBenefitValueModelImpl
	extends BaseModelImpl<TravelIntBenefitValue>
	implements TravelIntBenefitValueModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a travel int benefit value model instance should use the <code>TravelIntBenefitValue</code> interface instead.
	 */
	public static final String TABLE_NAME = "TravelIntBenefitValue";

	public static final Object[][] TABLE_COLUMNS = {
		{"travelIntBenefitValueId", Types.BIGINT},
		{"travelIntBenefitId", Types.BIGINT}, {"currencyName", Types.VARCHAR},
		{"packageType", Types.VARCHAR}, {"benefitValue", Types.VARCHAR},
		{"active_", Types.INTEGER}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("travelIntBenefitValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("travelIntBenefitId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("currencyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("packageType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("benefitValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TravelIntBenefitValue (travelIntBenefitValueId LONG not null primary key,travelIntBenefitId LONG,currencyName VARCHAR(75) null,packageType VARCHAR(75) null,benefitValue VARCHAR(75) null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table TravelIntBenefitValue";

	public static final String ORDER_BY_JPQL =
		" ORDER BY travelIntBenefitValue.travelIntBenefitValueId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TravelIntBenefitValue.travelIntBenefitValueId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PACKAGETYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRAVELINTBENEFITVALUEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static TravelIntBenefitValue toModel(
		TravelIntBenefitValueSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		TravelIntBenefitValue model = new TravelIntBenefitValueImpl();

		model.setTravelIntBenefitValueId(
			soapModel.getTravelIntBenefitValueId());
		model.setTravelIntBenefitId(soapModel.getTravelIntBenefitId());
		model.setCurrencyName(soapModel.getCurrencyName());
		model.setPackageType(soapModel.getPackageType());
		model.setBenefitValue(soapModel.getBenefitValue());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<TravelIntBenefitValue> toModels(
		TravelIntBenefitValueSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<TravelIntBenefitValue> models =
			new ArrayList<TravelIntBenefitValue>(soapModels.length);

		for (TravelIntBenefitValueSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TravelIntBenefitValueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _travelIntBenefitValueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTravelIntBenefitValueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _travelIntBenefitValueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TravelIntBenefitValue.class;
	}

	@Override
	public String getModelClassName() {
		return TravelIntBenefitValue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TravelIntBenefitValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TravelIntBenefitValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelIntBenefitValue, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TravelIntBenefitValue)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TravelIntBenefitValue, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TravelIntBenefitValue, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TravelIntBenefitValue)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TravelIntBenefitValue, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TravelIntBenefitValue, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TravelIntBenefitValue, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TravelIntBenefitValue, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TravelIntBenefitValue, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TravelIntBenefitValue, Object>>();
		Map<String, BiConsumer<TravelIntBenefitValue, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TravelIntBenefitValue, ?>>();

		attributeGetterFunctions.put(
			"travelIntBenefitValueId",
			TravelIntBenefitValue::getTravelIntBenefitValueId);
		attributeSetterBiConsumers.put(
			"travelIntBenefitValueId",
			(BiConsumer<TravelIntBenefitValue, Long>)
				TravelIntBenefitValue::setTravelIntBenefitValueId);
		attributeGetterFunctions.put(
			"travelIntBenefitId", TravelIntBenefitValue::getTravelIntBenefitId);
		attributeSetterBiConsumers.put(
			"travelIntBenefitId",
			(BiConsumer<TravelIntBenefitValue, Long>)
				TravelIntBenefitValue::setTravelIntBenefitId);
		attributeGetterFunctions.put(
			"currencyName", TravelIntBenefitValue::getCurrencyName);
		attributeSetterBiConsumers.put(
			"currencyName",
			(BiConsumer<TravelIntBenefitValue, String>)
				TravelIntBenefitValue::setCurrencyName);
		attributeGetterFunctions.put(
			"packageType", TravelIntBenefitValue::getPackageType);
		attributeSetterBiConsumers.put(
			"packageType",
			(BiConsumer<TravelIntBenefitValue, String>)
				TravelIntBenefitValue::setPackageType);
		attributeGetterFunctions.put(
			"benefitValue", TravelIntBenefitValue::getBenefitValue);
		attributeSetterBiConsumers.put(
			"benefitValue",
			(BiConsumer<TravelIntBenefitValue, String>)
				TravelIntBenefitValue::setBenefitValue);
		attributeGetterFunctions.put(
			"active", TravelIntBenefitValue::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<TravelIntBenefitValue, Integer>)
				TravelIntBenefitValue::setActive);
		attributeGetterFunctions.put(
			"groupId", TravelIntBenefitValue::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TravelIntBenefitValue, Long>)
				TravelIntBenefitValue::setGroupId);
		attributeGetterFunctions.put(
			"companyId", TravelIntBenefitValue::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TravelIntBenefitValue, Long>)
				TravelIntBenefitValue::setCompanyId);
		attributeGetterFunctions.put(
			"userId", TravelIntBenefitValue::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<TravelIntBenefitValue, Long>)
				TravelIntBenefitValue::setUserId);
		attributeGetterFunctions.put(
			"userName", TravelIntBenefitValue::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TravelIntBenefitValue, String>)
				TravelIntBenefitValue::setUserName);
		attributeGetterFunctions.put(
			"createDate", TravelIntBenefitValue::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TravelIntBenefitValue, Date>)
				TravelIntBenefitValue::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TravelIntBenefitValue::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TravelIntBenefitValue, Date>)
				TravelIntBenefitValue::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTravelIntBenefitValueId() {
		return _travelIntBenefitValueId;
	}

	@Override
	public void setTravelIntBenefitValueId(long travelIntBenefitValueId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelIntBenefitValueId = travelIntBenefitValueId;
	}

	@JSON
	@Override
	public long getTravelIntBenefitId() {
		return _travelIntBenefitId;
	}

	@Override
	public void setTravelIntBenefitId(long travelIntBenefitId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_travelIntBenefitId = travelIntBenefitId;
	}

	@JSON
	@Override
	public String getCurrencyName() {
		if (_currencyName == null) {
			return "";
		}
		else {
			return _currencyName;
		}
	}

	@Override
	public void setCurrencyName(String currencyName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currencyName = currencyName;
	}

	@JSON
	@Override
	public String getPackageType() {
		if (_packageType == null) {
			return "";
		}
		else {
			return _packageType;
		}
	}

	@Override
	public void setPackageType(String packageType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_packageType = packageType;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPackageType() {
		return getColumnOriginalValue("packageType");
	}

	@JSON
	@Override
	public String getBenefitValue() {
		if (_benefitValue == null) {
			return "";
		}
		else {
			return _benefitValue;
		}
	}

	@Override
	public void setBenefitValue(String benefitValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_benefitValue = benefitValue;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TravelIntBenefitValue.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TravelIntBenefitValue toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TravelIntBenefitValue>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TravelIntBenefitValueImpl travelIntBenefitValueImpl =
			new TravelIntBenefitValueImpl();

		travelIntBenefitValueImpl.setTravelIntBenefitValueId(
			getTravelIntBenefitValueId());
		travelIntBenefitValueImpl.setTravelIntBenefitId(
			getTravelIntBenefitId());
		travelIntBenefitValueImpl.setCurrencyName(getCurrencyName());
		travelIntBenefitValueImpl.setPackageType(getPackageType());
		travelIntBenefitValueImpl.setBenefitValue(getBenefitValue());
		travelIntBenefitValueImpl.setActive(getActive());
		travelIntBenefitValueImpl.setGroupId(getGroupId());
		travelIntBenefitValueImpl.setCompanyId(getCompanyId());
		travelIntBenefitValueImpl.setUserId(getUserId());
		travelIntBenefitValueImpl.setUserName(getUserName());
		travelIntBenefitValueImpl.setCreateDate(getCreateDate());
		travelIntBenefitValueImpl.setModifiedDate(getModifiedDate());

		travelIntBenefitValueImpl.resetOriginalValues();

		return travelIntBenefitValueImpl;
	}

	@Override
	public int compareTo(TravelIntBenefitValue travelIntBenefitValue) {
		long primaryKey = travelIntBenefitValue.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TravelIntBenefitValue)) {
			return false;
		}

		TravelIntBenefitValue travelIntBenefitValue =
			(TravelIntBenefitValue)object;

		long primaryKey = travelIntBenefitValue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TravelIntBenefitValue> toCacheModel() {
		TravelIntBenefitValueCacheModel travelIntBenefitValueCacheModel =
			new TravelIntBenefitValueCacheModel();

		travelIntBenefitValueCacheModel.travelIntBenefitValueId =
			getTravelIntBenefitValueId();

		travelIntBenefitValueCacheModel.travelIntBenefitId =
			getTravelIntBenefitId();

		travelIntBenefitValueCacheModel.currencyName = getCurrencyName();

		String currencyName = travelIntBenefitValueCacheModel.currencyName;

		if ((currencyName != null) && (currencyName.length() == 0)) {
			travelIntBenefitValueCacheModel.currencyName = null;
		}

		travelIntBenefitValueCacheModel.packageType = getPackageType();

		String packageType = travelIntBenefitValueCacheModel.packageType;

		if ((packageType != null) && (packageType.length() == 0)) {
			travelIntBenefitValueCacheModel.packageType = null;
		}

		travelIntBenefitValueCacheModel.benefitValue = getBenefitValue();

		String benefitValue = travelIntBenefitValueCacheModel.benefitValue;

		if ((benefitValue != null) && (benefitValue.length() == 0)) {
			travelIntBenefitValueCacheModel.benefitValue = null;
		}

		travelIntBenefitValueCacheModel.active = getActive();

		travelIntBenefitValueCacheModel.groupId = getGroupId();

		travelIntBenefitValueCacheModel.companyId = getCompanyId();

		travelIntBenefitValueCacheModel.userId = getUserId();

		travelIntBenefitValueCacheModel.userName = getUserName();

		String userName = travelIntBenefitValueCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			travelIntBenefitValueCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			travelIntBenefitValueCacheModel.createDate = createDate.getTime();
		}
		else {
			travelIntBenefitValueCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			travelIntBenefitValueCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			travelIntBenefitValueCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return travelIntBenefitValueCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TravelIntBenefitValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TravelIntBenefitValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelIntBenefitValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TravelIntBenefitValue)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TravelIntBenefitValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TravelIntBenefitValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TravelIntBenefitValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((TravelIntBenefitValue)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TravelIntBenefitValue>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TravelIntBenefitValue.class, ModelWrapper.class);

	}

	private long _travelIntBenefitValueId;
	private long _travelIntBenefitId;
	private String _currencyName;
	private String _packageType;
	private String _benefitValue;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TravelIntBenefitValue, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TravelIntBenefitValue)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"travelIntBenefitValueId", _travelIntBenefitValueId);
		_columnOriginalValues.put("travelIntBenefitId", _travelIntBenefitId);
		_columnOriginalValues.put("currencyName", _currencyName);
		_columnOriginalValues.put("packageType", _packageType);
		_columnOriginalValues.put("benefitValue", _benefitValue);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("travelIntBenefitValueId", 1L);

		columnBitmasks.put("travelIntBenefitId", 2L);

		columnBitmasks.put("currencyName", 4L);

		columnBitmasks.put("packageType", 8L);

		columnBitmasks.put("benefitValue", 16L);

		columnBitmasks.put("active_", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TravelIntBenefitValue _escapedModel;

}