name=myPage-Product-V1
module-group-id=liferay
module-incremental-version=1
tags=
short-description=
long-description=
change-log=
page-url=https://mypage.axa.co.id/
author=Gositus
licenses=LGPL
liferay-versions=7.3.0+

resources-importer-developer-mode-enabled=true
