/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BlacklistCustomer service. Represents a row in the &quot;BlacklistCustomer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.BlacklistCustomerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.BlacklistCustomerImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see BlacklistCustomer
 * @generated
 */
@ProviderType
public interface BlacklistCustomerModel
	extends BaseModel<BlacklistCustomer>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a blacklist customer model instance should use the {@link BlacklistCustomer} interface instead.
	 */

	/**
	 * Returns the primary key of this blacklist customer.
	 *
	 * @return the primary key of this blacklist customer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this blacklist customer.
	 *
	 * @param primaryKey the primary key of this blacklist customer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the blacklist customer ID of this blacklist customer.
	 *
	 * @return the blacklist customer ID of this blacklist customer
	 */
	public long getBlacklistCustomerId();

	/**
	 * Sets the blacklist customer ID of this blacklist customer.
	 *
	 * @param blacklistCustomerId the blacklist customer ID of this blacklist customer
	 */
	public void setBlacklistCustomerId(long blacklistCustomerId);

	/**
	 * Returns the full name of this blacklist customer.
	 *
	 * @return the full name of this blacklist customer
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this blacklist customer.
	 *
	 * @param fullName the full name of this blacklist customer
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the first name of this blacklist customer.
	 *
	 * @return the first name of this blacklist customer
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this blacklist customer.
	 *
	 * @param firstName the first name of this blacklist customer
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this blacklist customer.
	 *
	 * @return the middle name of this blacklist customer
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this blacklist customer.
	 *
	 * @param middleName the middle name of this blacklist customer
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this blacklist customer.
	 *
	 * @return the last name of this blacklist customer
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this blacklist customer.
	 *
	 * @param lastName the last name of this blacklist customer
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the ktp of this blacklist customer.
	 *
	 * @return the ktp of this blacklist customer
	 */
	@AutoEscape
	public String getKtp();

	/**
	 * Sets the ktp of this blacklist customer.
	 *
	 * @param ktp the ktp of this blacklist customer
	 */
	public void setKtp(String ktp);

	/**
	 * Returns the kitas of this blacklist customer.
	 *
	 * @return the kitas of this blacklist customer
	 */
	@AutoEscape
	public String getKitas();

	/**
	 * Sets the kitas of this blacklist customer.
	 *
	 * @param kitas the kitas of this blacklist customer
	 */
	public void setKitas(String kitas);

	/**
	 * Returns the email of this blacklist customer.
	 *
	 * @return the email of this blacklist customer
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this blacklist customer.
	 *
	 * @param email the email of this blacklist customer
	 */
	public void setEmail(String email);

	/**
	 * Returns the date of birth of this blacklist customer.
	 *
	 * @return the date of birth of this blacklist customer
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this blacklist customer.
	 *
	 * @param dateOfBirth the date of birth of this blacklist customer
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the active of this blacklist customer.
	 *
	 * @return the active of this blacklist customer
	 */
	public Integer getActive();

	/**
	 * Sets the active of this blacklist customer.
	 *
	 * @param active the active of this blacklist customer
	 */
	public void setActive(Integer active);

	/**
	 * Returns the group ID of this blacklist customer.
	 *
	 * @return the group ID of this blacklist customer
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this blacklist customer.
	 *
	 * @param groupId the group ID of this blacklist customer
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this blacklist customer.
	 *
	 * @return the company ID of this blacklist customer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this blacklist customer.
	 *
	 * @param companyId the company ID of this blacklist customer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this blacklist customer.
	 *
	 * @return the user ID of this blacklist customer
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this blacklist customer.
	 *
	 * @param userId the user ID of this blacklist customer
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this blacklist customer.
	 *
	 * @return the user uuid of this blacklist customer
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this blacklist customer.
	 *
	 * @param userUuid the user uuid of this blacklist customer
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this blacklist customer.
	 *
	 * @return the user name of this blacklist customer
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this blacklist customer.
	 *
	 * @param userName the user name of this blacklist customer
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this blacklist customer.
	 *
	 * @return the create date of this blacklist customer
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this blacklist customer.
	 *
	 * @param createDate the create date of this blacklist customer
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this blacklist customer.
	 *
	 * @return the modified date of this blacklist customer
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this blacklist customer.
	 *
	 * @param modifiedDate the modified date of this blacklist customer
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}