/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CompanyType service. Represents a row in the &quot;CompanyType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.CompanyTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.CompanyTypeImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see CompanyType
 * @generated
 */
@ProviderType
public interface CompanyTypeModel
	extends BaseModel<CompanyType>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a company type model instance should use the {@link CompanyType} interface instead.
	 */

	/**
	 * Returns the primary key of this company type.
	 *
	 * @return the primary key of this company type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this company type.
	 *
	 * @param primaryKey the primary key of this company type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company type ID of this company type.
	 *
	 * @return the company type ID of this company type
	 */
	public long getCompanyTypeId();

	/**
	 * Sets the company type ID of this company type.
	 *
	 * @param companyTypeId the company type ID of this company type
	 */
	public void setCompanyTypeId(long companyTypeId);

	/**
	 * Returns the name of this company type.
	 *
	 * @return the name of this company type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this company type.
	 *
	 * @param name the name of this company type
	 */
	public void setName(String name);

	/**
	 * Returns the label of this company type.
	 *
	 * @return the label of this company type
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this company type.
	 *
	 * @param label the label of this company type
	 */
	public void setLabel(String label);

	/**
	 * Returns the sort of this company type.
	 *
	 * @return the sort of this company type
	 */
	public int getSort();

	/**
	 * Sets the sort of this company type.
	 *
	 * @param sort the sort of this company type
	 */
	public void setSort(int sort);

	/**
	 * Returns the active of this company type.
	 *
	 * @return the active of this company type
	 */
	public int getActive();

	/**
	 * Sets the active of this company type.
	 *
	 * @param active the active of this company type
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this company type.
	 *
	 * @return the group ID of this company type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this company type.
	 *
	 * @param groupId the group ID of this company type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this company type.
	 *
	 * @return the company ID of this company type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this company type.
	 *
	 * @param companyId the company ID of this company type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this company type.
	 *
	 * @return the user ID of this company type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this company type.
	 *
	 * @param userId the user ID of this company type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this company type.
	 *
	 * @return the user uuid of this company type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this company type.
	 *
	 * @param userUuid the user uuid of this company type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this company type.
	 *
	 * @return the user name of this company type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this company type.
	 *
	 * @param userName the user name of this company type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this company type.
	 *
	 * @return the create date of this company type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this company type.
	 *
	 * @param createDate the create date of this company type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this company type.
	 *
	 * @return the modified date of this company type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this company type.
	 *
	 * @param modifiedDate the modified date of this company type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}