/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HealthIndividuPlan service. Represents a row in the &quot;HealthIndividuPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.HealthIndividuPlanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.HealthIndividuPlanImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see HealthIndividuPlan
 * @generated
 */
@ProviderType
public interface HealthIndividuPlanModel
	extends BaseModel<HealthIndividuPlan>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a health individu plan model instance should use the {@link HealthIndividuPlan} interface instead.
	 */

	/**
	 * Returns the primary key of this health individu plan.
	 *
	 * @return the primary key of this health individu plan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this health individu plan.
	 *
	 * @param primaryKey the primary key of this health individu plan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the health individu plan ID of this health individu plan.
	 *
	 * @return the health individu plan ID of this health individu plan
	 */
	public long getHealthIndividuPlanId();

	/**
	 * Sets the health individu plan ID of this health individu plan.
	 *
	 * @param healthIndividuPlanId the health individu plan ID of this health individu plan
	 */
	public void setHealthIndividuPlanId(long healthIndividuPlanId);

	/**
	 * Returns the group ID of this health individu plan.
	 *
	 * @return the group ID of this health individu plan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this health individu plan.
	 *
	 * @param groupId the group ID of this health individu plan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this health individu plan.
	 *
	 * @return the company ID of this health individu plan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this health individu plan.
	 *
	 * @param companyId the company ID of this health individu plan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this health individu plan.
	 *
	 * @return the user ID of this health individu plan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this health individu plan.
	 *
	 * @param userId the user ID of this health individu plan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this health individu plan.
	 *
	 * @return the user uuid of this health individu plan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this health individu plan.
	 *
	 * @param userUuid the user uuid of this health individu plan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this health individu plan.
	 *
	 * @return the user name of this health individu plan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this health individu plan.
	 *
	 * @param userName the user name of this health individu plan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this health individu plan.
	 *
	 * @return the create date of this health individu plan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this health individu plan.
	 *
	 * @param createDate the create date of this health individu plan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this health individu plan.
	 *
	 * @return the modified date of this health individu plan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this health individu plan.
	 *
	 * @param modifiedDate the modified date of this health individu plan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this health individu plan.
	 *
	 * @return the name of this health individu plan
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this health individu plan.
	 *
	 * @param name the name of this health individu plan
	 */
	public void setName(String name);

	/**
	 * Returns the limit year of this health individu plan.
	 *
	 * @return the limit year of this health individu plan
	 */
	public long getLimitYear();

	/**
	 * Sets the limit year of this health individu plan.
	 *
	 * @param limitYear the limit year of this health individu plan
	 */
	public void setLimitYear(long limitYear);

	/**
	 * Returns the limit disability of this health individu plan.
	 *
	 * @return the limit disability of this health individu plan
	 */
	public long getLimitDisability();

	/**
	 * Sets the limit disability of this health individu plan.
	 *
	 * @param limitDisability the limit disability of this health individu plan
	 */
	public void setLimitDisability(long limitDisability);

	/**
	 * Returns the inpatient of this health individu plan.
	 *
	 * @return the inpatient of this health individu plan
	 */
	public long getInpatient();

	/**
	 * Sets the inpatient of this health individu plan.
	 *
	 * @param inpatient the inpatient of this health individu plan
	 */
	public void setInpatient(long inpatient);

	/**
	 * Returns the outpatient of this health individu plan.
	 *
	 * @return the outpatient of this health individu plan
	 */
	public long getOutpatient();

	/**
	 * Sets the outpatient of this health individu plan.
	 *
	 * @param outpatient the outpatient of this health individu plan
	 */
	public void setOutpatient(long outpatient);

	/**
	 * Returns the ambulance service of this health individu plan.
	 *
	 * @return the ambulance service of this health individu plan
	 */
	public long getAmbulanceService();

	/**
	 * Sets the ambulance service of this health individu plan.
	 *
	 * @param ambulanceService the ambulance service of this health individu plan
	 */
	public void setAmbulanceService(long ambulanceService);

	/**
	 * Returns the personal accident of this health individu plan.
	 *
	 * @return the personal accident of this health individu plan
	 */
	public long getPersonalAccident();

	/**
	 * Sets the personal accident of this health individu plan.
	 *
	 * @param personalAccident the personal accident of this health individu plan
	 */
	public void setPersonalAccident(long personalAccident);

	/**
	 * Returns the detail of this health individu plan.
	 *
	 * @return the detail of this health individu plan
	 */
	@AutoEscape
	public String getDetail();

	/**
	 * Sets the detail of this health individu plan.
	 *
	 * @param detail the detail of this health individu plan
	 */
	public void setDetail(String detail);

	/**
	 * Returns the benefit of this health individu plan.
	 *
	 * @return the benefit of this health individu plan
	 */
	@AutoEscape
	public String getBenefit();

	/**
	 * Sets the benefit of this health individu plan.
	 *
	 * @param benefit the benefit of this health individu plan
	 */
	public void setBenefit(String benefit);

	/**
	 * Returns the benefit icon of this health individu plan.
	 *
	 * @return the benefit icon of this health individu plan
	 */
	@AutoEscape
	public String getBenefitIcon();

	/**
	 * Sets the benefit icon of this health individu plan.
	 *
	 * @param benefitIcon the benefit icon of this health individu plan
	 */
	public void setBenefitIcon(String benefitIcon);

	/**
	 * Returns the recommended of this health individu plan.
	 *
	 * @return the recommended of this health individu plan
	 */
	public int getRecommended();

	/**
	 * Sets the recommended of this health individu plan.
	 *
	 * @param recommended the recommended of this health individu plan
	 */
	public void setRecommended(int recommended);

	/**
	 * Returns the active of this health individu plan.
	 *
	 * @return the active of this health individu plan
	 */
	public int getActive();

	/**
	 * Sets the active of this health individu plan.
	 *
	 * @param active the active of this health individu plan
	 */
	public void setActive(int active);

}