/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HealthSmeType service. Represents a row in the &quot;HealthSmeType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.HealthSmeTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.HealthSmeTypeImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see HealthSmeType
 * @generated
 */
@ProviderType
public interface HealthSmeTypeModel
	extends BaseModel<HealthSmeType>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a health sme type model instance should use the {@link HealthSmeType} interface instead.
	 */

	/**
	 * Returns the primary key of this health sme type.
	 *
	 * @return the primary key of this health sme type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this health sme type.
	 *
	 * @param primaryKey the primary key of this health sme type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the health sme type ID of this health sme type.
	 *
	 * @return the health sme type ID of this health sme type
	 */
	public long getHealthSmeTypeId();

	/**
	 * Sets the health sme type ID of this health sme type.
	 *
	 * @param healthSmeTypeId the health sme type ID of this health sme type
	 */
	public void setHealthSmeTypeId(long healthSmeTypeId);

	/**
	 * Returns the group ID of this health sme type.
	 *
	 * @return the group ID of this health sme type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this health sme type.
	 *
	 * @param groupId the group ID of this health sme type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this health sme type.
	 *
	 * @return the company ID of this health sme type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this health sme type.
	 *
	 * @param companyId the company ID of this health sme type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this health sme type.
	 *
	 * @return the user ID of this health sme type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this health sme type.
	 *
	 * @param userId the user ID of this health sme type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this health sme type.
	 *
	 * @return the user uuid of this health sme type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this health sme type.
	 *
	 * @param userUuid the user uuid of this health sme type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this health sme type.
	 *
	 * @return the user name of this health sme type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this health sme type.
	 *
	 * @param userName the user name of this health sme type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this health sme type.
	 *
	 * @return the create date of this health sme type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this health sme type.
	 *
	 * @param createDate the create date of this health sme type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this health sme type.
	 *
	 * @return the modified date of this health sme type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this health sme type.
	 *
	 * @param modifiedDate the modified date of this health sme type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type name of this health sme type.
	 *
	 * @return the type name of this health sme type
	 */
	@AutoEscape
	public String getTypeName();

	/**
	 * Sets the type name of this health sme type.
	 *
	 * @param typeName the type name of this health sme type
	 */
	public void setTypeName(String typeName);

	/**
	 * Returns the type code of this health sme type.
	 *
	 * @return the type code of this health sme type
	 */
	@AutoEscape
	public String getTypeCode();

	/**
	 * Sets the type code of this health sme type.
	 *
	 * @param typeCode the type code of this health sme type
	 */
	public void setTypeCode(String typeCode);

	/**
	 * Returns the type description of this health sme type.
	 *
	 * @return the type description of this health sme type
	 */
	@AutoEscape
	public String getTypeDescription();

	/**
	 * Sets the type description of this health sme type.
	 *
	 * @param typeDescription the type description of this health sme type
	 */
	public void setTypeDescription(String typeDescription);

	/**
	 * Returns the active of this health sme type.
	 *
	 * @return the active of this health sme type
	 */
	public int getActive();

	/**
	 * Sets the active of this health sme type.
	 *
	 * @param active the active of this health sme type
	 */
	public void setActive(int active);

}