/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HealthSmeTemplate service. Represents a row in the &quot;HealthSmeTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.HealthSmeTemplateModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.HealthSmeTemplateImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see HealthSmeTemplate
 * @generated
 */
@ProviderType
public interface HealthSmeTemplateModel
	extends BaseModel<HealthSmeTemplate>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a health sme template model instance should use the {@link HealthSmeTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this health sme template.
	 *
	 * @return the primary key of this health sme template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this health sme template.
	 *
	 * @param primaryKey the primary key of this health sme template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the health sme template ID of this health sme template.
	 *
	 * @return the health sme template ID of this health sme template
	 */
	public long getHealthSmeTemplateId();

	/**
	 * Sets the health sme template ID of this health sme template.
	 *
	 * @param healthSmeTemplateId the health sme template ID of this health sme template
	 */
	public void setHealthSmeTemplateId(long healthSmeTemplateId);

	/**
	 * Returns the group ID of this health sme template.
	 *
	 * @return the group ID of this health sme template
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this health sme template.
	 *
	 * @param groupId the group ID of this health sme template
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this health sme template.
	 *
	 * @return the company ID of this health sme template
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this health sme template.
	 *
	 * @param companyId the company ID of this health sme template
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this health sme template.
	 *
	 * @return the user ID of this health sme template
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this health sme template.
	 *
	 * @param userId the user ID of this health sme template
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this health sme template.
	 *
	 * @return the user uuid of this health sme template
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this health sme template.
	 *
	 * @param userUuid the user uuid of this health sme template
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this health sme template.
	 *
	 * @return the user name of this health sme template
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this health sme template.
	 *
	 * @param userName the user name of this health sme template
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this health sme template.
	 *
	 * @return the create date of this health sme template
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this health sme template.
	 *
	 * @param createDate the create date of this health sme template
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this health sme template.
	 *
	 * @return the modified date of this health sme template
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this health sme template.
	 *
	 * @param modifiedDate the modified date of this health sme template
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this health sme template.
	 *
	 * @return the name of this health sme template
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this health sme template.
	 *
	 * @param name the name of this health sme template
	 */
	public void setName(String name);

	/**
	 * Returns the code of this health sme template.
	 *
	 * @return the code of this health sme template
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this health sme template.
	 *
	 * @param code the code of this health sme template
	 */
	public void setCode(String code);

	/**
	 * Returns the description of this health sme template.
	 *
	 * @return the description of this health sme template
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this health sme template.
	 *
	 * @param description the description of this health sme template
	 */
	public void setDescription(String description);

	/**
	 * Returns the amount of this health sme template.
	 *
	 * @return the amount of this health sme template
	 */
	public long getAmount();

	/**
	 * Sets the amount of this health sme template.
	 *
	 * @param amount the amount of this health sme template
	 */
	public void setAmount(long amount);

	/**
	 * Returns the annual limit of this health sme template.
	 *
	 * @return the annual limit of this health sme template
	 */
	public long getAnnualLimit();

	/**
	 * Sets the annual limit of this health sme template.
	 *
	 * @param annualLimit the annual limit of this health sme template
	 */
	public void setAnnualLimit(long annualLimit);

	/**
	 * Returns the health sme type ID of this health sme template.
	 *
	 * @return the health sme type ID of this health sme template
	 */
	public long getHealthSmeTypeId();

	/**
	 * Sets the health sme type ID of this health sme template.
	 *
	 * @param healthSmeTypeId the health sme type ID of this health sme template
	 */
	public void setHealthSmeTypeId(long healthSmeTypeId);

	/**
	 * Returns the active of this health sme template.
	 *
	 * @return the active of this health sme template
	 */
	public int getActive();

	/**
	 * Sets the active of this health sme template.
	 *
	 * @param active the active of this health sme template
	 */
	public void setActive(int active);

}