/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IndustryCategory service. Represents a row in the &quot;IndustryCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.IndustryCategoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.IndustryCategoryImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see IndustryCategory
 * @generated
 */
@ProviderType
public interface IndustryCategoryModel
	extends BaseModel<IndustryCategory>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a industry category model instance should use the {@link IndustryCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this industry category.
	 *
	 * @return the primary key of this industry category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this industry category.
	 *
	 * @param primaryKey the primary key of this industry category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the industry category ID of this industry category.
	 *
	 * @return the industry category ID of this industry category
	 */
	public long getIndustryCategoryId();

	/**
	 * Sets the industry category ID of this industry category.
	 *
	 * @param industryCategoryId the industry category ID of this industry category
	 */
	public void setIndustryCategoryId(long industryCategoryId);

	/**
	 * Returns the name of this industry category.
	 *
	 * @return the name of this industry category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this industry category.
	 *
	 * @param name the name of this industry category
	 */
	public void setName(String name);

	/**
	 * Returns the active of this industry category.
	 *
	 * @return the active of this industry category
	 */
	public int getActive();

	/**
	 * Sets the active of this industry category.
	 *
	 * @param active the active of this industry category
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this industry category.
	 *
	 * @return the group ID of this industry category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this industry category.
	 *
	 * @param groupId the group ID of this industry category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this industry category.
	 *
	 * @return the company ID of this industry category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this industry category.
	 *
	 * @param companyId the company ID of this industry category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this industry category.
	 *
	 * @return the user ID of this industry category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this industry category.
	 *
	 * @param userId the user ID of this industry category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this industry category.
	 *
	 * @return the user uuid of this industry category
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this industry category.
	 *
	 * @param userUuid the user uuid of this industry category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this industry category.
	 *
	 * @return the user name of this industry category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this industry category.
	 *
	 * @param userName the user name of this industry category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this industry category.
	 *
	 * @return the create date of this industry category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this industry category.
	 *
	 * @param createDate the create date of this industry category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this industry category.
	 *
	 * @return the modified date of this industry category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this industry category.
	 *
	 * @param modifiedDate the modified date of this industry category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}