/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MasterGlobalVariable service. Represents a row in the &quot;MasterGlobalVariable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.MasterGlobalVariableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.MasterGlobalVariableImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see MasterGlobalVariable
 * @generated
 */
@ProviderType
public interface MasterGlobalVariableModel
	extends BaseModel<MasterGlobalVariable>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master global variable model instance should use the {@link MasterGlobalVariable} interface instead.
	 */

	/**
	 * Returns the primary key of this master global variable.
	 *
	 * @return the primary key of this master global variable
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this master global variable.
	 *
	 * @param primaryKey the primary key of this master global variable
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the master global variable ID of this master global variable.
	 *
	 * @return the master global variable ID of this master global variable
	 */
	public long getMasterGlobalVariableId();

	/**
	 * Sets the master global variable ID of this master global variable.
	 *
	 * @param masterGlobalVariableId the master global variable ID of this master global variable
	 */
	public void setMasterGlobalVariableId(long masterGlobalVariableId);

	/**
	 * Returns the group ID of this master global variable.
	 *
	 * @return the group ID of this master global variable
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this master global variable.
	 *
	 * @param groupId the group ID of this master global variable
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this master global variable.
	 *
	 * @return the company ID of this master global variable
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this master global variable.
	 *
	 * @param companyId the company ID of this master global variable
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this master global variable.
	 *
	 * @return the user ID of this master global variable
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this master global variable.
	 *
	 * @param userId the user ID of this master global variable
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this master global variable.
	 *
	 * @return the user uuid of this master global variable
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this master global variable.
	 *
	 * @param userUuid the user uuid of this master global variable
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this master global variable.
	 *
	 * @return the user name of this master global variable
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this master global variable.
	 *
	 * @param userName the user name of this master global variable
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this master global variable.
	 *
	 * @return the create date of this master global variable
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this master global variable.
	 *
	 * @param createDate the create date of this master global variable
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this master global variable.
	 *
	 * @return the modified date of this master global variable
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this master global variable.
	 *
	 * @param modifiedDate the modified date of this master global variable
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group of this master global variable.
	 *
	 * @return the group of this master global variable
	 */
	@AutoEscape
	public String getGroup();

	/**
	 * Sets the group of this master global variable.
	 *
	 * @param group the group of this master global variable
	 */
	public void setGroup(String group);

	/**
	 * Returns the name of this master global variable.
	 *
	 * @return the name of this master global variable
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this master global variable.
	 *
	 * @param name the name of this master global variable
	 */
	public void setName(String name);

	/**
	 * Returns the value of this master global variable.
	 *
	 * @return the value of this master global variable
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this master global variable.
	 *
	 * @param value the value of this master global variable
	 */
	public void setValue(String value);

	/**
	 * Returns the image file entry ID of this master global variable.
	 *
	 * @return the image file entry ID of this master global variable
	 */
	public Long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this master global variable.
	 *
	 * @param imageFileEntryId the image file entry ID of this master global variable
	 */
	public void setImageFileEntryId(Long imageFileEntryId);

	/**
	 * Returns the active of this master global variable.
	 *
	 * @return the active of this master global variable
	 */
	public int getActive();

	/**
	 * Sets the active of this master global variable.
	 *
	 * @param active the active of this master global variable
	 */
	public void setActive(int active);

}