/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MasterPromoCode service. Represents a row in the &quot;MasterPromoCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.MasterPromoCodeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.MasterPromoCodeImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see MasterPromoCode
 * @generated
 */
@ProviderType
public interface MasterPromoCodeModel
	extends BaseModel<MasterPromoCode>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master promo code model instance should use the {@link MasterPromoCode} interface instead.
	 */

	/**
	 * Returns the primary key of this master promo code.
	 *
	 * @return the primary key of this master promo code
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this master promo code.
	 *
	 * @param primaryKey the primary key of this master promo code
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the promo code ID of this master promo code.
	 *
	 * @return the promo code ID of this master promo code
	 */
	public long getPromoCodeId();

	/**
	 * Sets the promo code ID of this master promo code.
	 *
	 * @param promoCodeId the promo code ID of this master promo code
	 */
	public void setPromoCodeId(long promoCodeId);

	/**
	 * Returns the is default of this master promo code.
	 *
	 * @return the is default of this master promo code
	 */
	public int getIsDefault();

	/**
	 * Sets the is default of this master promo code.
	 *
	 * @param isDefault the is default of this master promo code
	 */
	public void setIsDefault(int isDefault);

	/**
	 * Returns the product code of this master promo code.
	 *
	 * @return the product code of this master promo code
	 */
	@AutoEscape
	public String getProductCode();

	/**
	 * Sets the product code of this master promo code.
	 *
	 * @param productCode the product code of this master promo code
	 */
	public void setProductCode(String productCode);

	/**
	 * Returns the product name of this master promo code.
	 *
	 * @return the product name of this master promo code
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this master promo code.
	 *
	 * @param productName the product name of this master promo code
	 */
	public void setProductName(String productName);

	/**
	 * Returns the promo type of this master promo code.
	 *
	 * @return the promo type of this master promo code
	 */
	@AutoEscape
	public String getPromoType();

	/**
	 * Sets the promo type of this master promo code.
	 *
	 * @param promoType the promo type of this master promo code
	 */
	public void setPromoType(String promoType);

	/**
	 * Returns the promo code of this master promo code.
	 *
	 * @return the promo code of this master promo code
	 */
	@AutoEscape
	public String getPromoCode();

	/**
	 * Sets the promo code of this master promo code.
	 *
	 * @param promoCode the promo code of this master promo code
	 */
	public void setPromoCode(String promoCode);

	/**
	 * Returns the discount of this master promo code.
	 *
	 * @return the discount of this master promo code
	 */
	public double getDiscount();

	/**
	 * Sets the discount of this master promo code.
	 *
	 * @param discount the discount of this master promo code
	 */
	public void setDiscount(double discount);

	/**
	 * Returns the start date of this master promo code.
	 *
	 * @return the start date of this master promo code
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this master promo code.
	 *
	 * @param startDate the start date of this master promo code
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this master promo code.
	 *
	 * @return the end date of this master promo code
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this master promo code.
	 *
	 * @param endDate the end date of this master promo code
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the active day of this master promo code.
	 *
	 * @return the active day of this master promo code
	 */
	@AutoEscape
	public String getActiveDay();

	/**
	 * Sets the active day of this master promo code.
	 *
	 * @param activeDay the active day of this master promo code
	 */
	public void setActiveDay(String activeDay);

	/**
	 * Returns the limit of this master promo code.
	 *
	 * @return the limit of this master promo code
	 */
	@AutoEscape
	public String getLimit();

	/**
	 * Sets the limit of this master promo code.
	 *
	 * @param limit the limit of this master promo code
	 */
	public void setLimit(String limit);

	/**
	 * Returns the network of this master promo code.
	 *
	 * @return the network of this master promo code
	 */
	@AutoEscape
	public String getNetwork();

	/**
	 * Sets the network of this master promo code.
	 *
	 * @param network the network of this master promo code
	 */
	public void setNetwork(String network);

	/**
	 * Returns the channel of this master promo code.
	 *
	 * @return the channel of this master promo code
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this master promo code.
	 *
	 * @param channel the channel of this master promo code
	 */
	public void setChannel(String channel);

	/**
	 * Returns the is b2c of this master promo code.
	 *
	 * @return the is b2c of this master promo code
	 */
	public int getIsB2C();

	/**
	 * Sets the is b2c of this master promo code.
	 *
	 * @param isB2C the is b2c of this master promo code
	 */
	public void setIsB2C(int isB2C);

	/**
	 * Returns the is b2b2c of this master promo code.
	 *
	 * @return the is b2b2c of this master promo code
	 */
	public int getIsB2B2C();

	/**
	 * Sets the is b2b2c of this master promo code.
	 *
	 * @param isB2B2C the is b2b2c of this master promo code
	 */
	public void setIsB2B2C(int isB2B2C);

	/**
	 * Returns the is b2b of this master promo code.
	 *
	 * @return the is b2b of this master promo code
	 */
	public int getIsB2B();

	/**
	 * Sets the is b2b of this master promo code.
	 *
	 * @param isB2B the is b2b of this master promo code
	 */
	public void setIsB2B(int isB2B);

	/**
	 * Returns the payment of this master promo code.
	 *
	 * @return the payment of this master promo code
	 */
	@AutoEscape
	public String getPayment();

	/**
	 * Sets the payment of this master promo code.
	 *
	 * @param payment the payment of this master promo code
	 */
	public void setPayment(String payment);

	/**
	 * Returns the birthday month of this master promo code.
	 *
	 * @return the birthday month of this master promo code
	 */
	@AutoEscape
	public String getBirthdayMonth();

	/**
	 * Sets the birthday month of this master promo code.
	 *
	 * @param birthdayMonth the birthday month of this master promo code
	 */
	public void setBirthdayMonth(String birthdayMonth);

	/**
	 * Returns the remarks of this master promo code.
	 *
	 * @return the remarks of this master promo code
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this master promo code.
	 *
	 * @param remarks the remarks of this master promo code
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the mypage user ID of this master promo code.
	 *
	 * @return the mypage user ID of this master promo code
	 */
	public long getMypageUserId();

	/**
	 * Sets the mypage user ID of this master promo code.
	 *
	 * @param mypageUserId the mypage user ID of this master promo code
	 */
	public void setMypageUserId(long mypageUserId);

	/**
	 * Returns the mypage user uuid of this master promo code.
	 *
	 * @return the mypage user uuid of this master promo code
	 */
	public String getMypageUserUuid();

	/**
	 * Sets the mypage user uuid of this master promo code.
	 *
	 * @param mypageUserUuid the mypage user uuid of this master promo code
	 */
	public void setMypageUserUuid(String mypageUserUuid);

	/**
	 * Returns the agent name of this master promo code.
	 *
	 * @return the agent name of this master promo code
	 */
	@AutoEscape
	public String getAgentName();

	/**
	 * Sets the agent name of this master promo code.
	 *
	 * @param agentName the agent name of this master promo code
	 */
	public void setAgentName(String agentName);

	/**
	 * Returns the deptore code of this master promo code.
	 *
	 * @return the deptore code of this master promo code
	 */
	@AutoEscape
	public String getDeptoreCode();

	/**
	 * Sets the deptore code of this master promo code.
	 *
	 * @param deptoreCode the deptore code of this master promo code
	 */
	public void setDeptoreCode(String deptoreCode);

	/**
	 * Returns the commission of this master promo code.
	 *
	 * @return the commission of this master promo code
	 */
	@AutoEscape
	public String getCommission();

	/**
	 * Sets the commission of this master promo code.
	 *
	 * @param commission the commission of this master promo code
	 */
	public void setCommission(String commission);

	/**
	 * Returns the plan_ of this master promo code.
	 *
	 * @return the plan_ of this master promo code
	 */
	@AutoEscape
	public String getPlan_();

	/**
	 * Sets the plan_ of this master promo code.
	 *
	 * @param plan_ the plan_ of this master promo code
	 */
	public void setPlan_(String plan_);

	/**
	 * Returns the promo code terms of this master promo code.
	 *
	 * @return the promo code terms of this master promo code
	 */
	@AutoEscape
	public String getPromoCodeTerms();

	/**
	 * Sets the promo code terms of this master promo code.
	 *
	 * @param promoCodeTerms the promo code terms of this master promo code
	 */
	public void setPromoCodeTerms(String promoCodeTerms);

	/**
	 * Returns the traveller type of this master promo code.
	 *
	 * @return the traveller type of this master promo code
	 */
	@AutoEscape
	public String getTravellerType();

	/**
	 * Sets the traveller type of this master promo code.
	 *
	 * @param travellerType the traveller type of this master promo code
	 */
	public void setTravellerType(String travellerType);

	/**
	 * Returns the utm ID of this master promo code.
	 *
	 * @return the utm ID of this master promo code
	 */
	@AutoEscape
	public String getUtmId();

	/**
	 * Sets the utm ID of this master promo code.
	 *
	 * @param utmId the utm ID of this master promo code
	 */
	public void setUtmId(String utmId);

	/**
	 * Returns the payment channel ID of this master promo code.
	 *
	 * @return the payment channel ID of this master promo code
	 */
	@AutoEscape
	public String getPaymentChannelId();

	/**
	 * Sets the payment channel ID of this master promo code.
	 *
	 * @param paymentChannelId the payment channel ID of this master promo code
	 */
	public void setPaymentChannelId(String paymentChannelId);

	/**
	 * Returns the active of this master promo code.
	 *
	 * @return the active of this master promo code
	 */
	public int getActive();

	/**
	 * Sets the active of this master promo code.
	 *
	 * @param active the active of this master promo code
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this master promo code.
	 *
	 * @return the group ID of this master promo code
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this master promo code.
	 *
	 * @param groupId the group ID of this master promo code
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this master promo code.
	 *
	 * @return the company ID of this master promo code
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this master promo code.
	 *
	 * @param companyId the company ID of this master promo code
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this master promo code.
	 *
	 * @return the user ID of this master promo code
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this master promo code.
	 *
	 * @param userId the user ID of this master promo code
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this master promo code.
	 *
	 * @return the user uuid of this master promo code
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this master promo code.
	 *
	 * @param userUuid the user uuid of this master promo code
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this master promo code.
	 *
	 * @return the user name of this master promo code
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this master promo code.
	 *
	 * @param userName the user name of this master promo code
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this master promo code.
	 *
	 * @return the create date of this master promo code
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this master promo code.
	 *
	 * @param createDate the create date of this master promo code
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this master promo code.
	 *
	 * @return the modified date of this master promo code
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this master promo code.
	 *
	 * @param modifiedDate the modified date of this master promo code
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}