/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MasterBank service. Represents a row in the &quot;MasterBank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.MasterBankModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.MasterBankImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see MasterBank
 * @generated
 */
@ProviderType
public interface MasterBankModel
	extends BaseModel<MasterBank>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master bank model instance should use the {@link MasterBank} interface instead.
	 */

	/**
	 * Returns the primary key of this master bank.
	 *
	 * @return the primary key of this master bank
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this master bank.
	 *
	 * @param primaryKey the primary key of this master bank
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the master bank ID of this master bank.
	 *
	 * @return the master bank ID of this master bank
	 */
	public long getMasterBankId();

	/**
	 * Sets the master bank ID of this master bank.
	 *
	 * @param masterBankId the master bank ID of this master bank
	 */
	public void setMasterBankId(long masterBankId);

	/**
	 * Returns the group ID of this master bank.
	 *
	 * @return the group ID of this master bank
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this master bank.
	 *
	 * @param groupId the group ID of this master bank
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this master bank.
	 *
	 * @return the company ID of this master bank
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this master bank.
	 *
	 * @param companyId the company ID of this master bank
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this master bank.
	 *
	 * @return the user ID of this master bank
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this master bank.
	 *
	 * @param userId the user ID of this master bank
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this master bank.
	 *
	 * @return the user uuid of this master bank
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this master bank.
	 *
	 * @param userUuid the user uuid of this master bank
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this master bank.
	 *
	 * @return the user name of this master bank
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this master bank.
	 *
	 * @param userName the user name of this master bank
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this master bank.
	 *
	 * @return the create date of this master bank
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this master bank.
	 *
	 * @param createDate the create date of this master bank
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this master bank.
	 *
	 * @return the modified date of this master bank
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this master bank.
	 *
	 * @param modifiedDate the modified date of this master bank
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the bank code of this master bank.
	 *
	 * @return the bank code of this master bank
	 */
	@AutoEscape
	public String getBankCode();

	/**
	 * Sets the bank code of this master bank.
	 *
	 * @param bankCode the bank code of this master bank
	 */
	public void setBankCode(String bankCode);

	/**
	 * Returns the bank desc of this master bank.
	 *
	 * @return the bank desc of this master bank
	 */
	@AutoEscape
	public String getBankDesc();

	/**
	 * Sets the bank desc of this master bank.
	 *
	 * @param bankDesc the bank desc of this master bank
	 */
	public void setBankDesc(String bankDesc);

	/**
	 * Returns the name of this master bank.
	 *
	 * @return the name of this master bank
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this master bank.
	 *
	 * @param name the name of this master bank
	 */
	public void setName(String name);

	/**
	 * Returns the detail of this master bank.
	 *
	 * @return the detail of this master bank
	 */
	@AutoEscape
	public String getDetail();

	/**
	 * Sets the detail of this master bank.
	 *
	 * @param detail the detail of this master bank
	 */
	public void setDetail(String detail);

	/**
	 * Returns the image url of this master bank.
	 *
	 * @return the image url of this master bank
	 */
	@AutoEscape
	public String getImageURL();

	/**
	 * Sets the image url of this master bank.
	 *
	 * @param imageURL the image url of this master bank
	 */
	public void setImageURL(String imageURL);

	/**
	 * Returns the image file entry ID of this master bank.
	 *
	 * @return the image file entry ID of this master bank
	 */
	public Long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this master bank.
	 *
	 * @param imageFileEntryId the image file entry ID of this master bank
	 */
	public void setImageFileEntryId(Long imageFileEntryId);

	/**
	 * Returns the order of this master bank.
	 *
	 * @return the order of this master bank
	 */
	public Integer getOrder();

	/**
	 * Sets the order of this master bank.
	 *
	 * @param order the order of this master bank
	 */
	public void setOrder(Integer order);

	/**
	 * Returns the active of this master bank.
	 *
	 * @return the active of this master bank
	 */
	public Integer getActive();

	/**
	 * Sets the active of this master bank.
	 *
	 * @param active the active of this master bank
	 */
	public void setActive(Integer active);

}