/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MasterOccupation service. Represents a row in the &quot;MasterOccupation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.MasterOccupationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.MasterOccupationImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see MasterOccupation
 * @generated
 */
@ProviderType
public interface MasterOccupationModel
	extends BaseModel<MasterOccupation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master occupation model instance should use the {@link MasterOccupation} interface instead.
	 */

	/**
	 * Returns the primary key of this master occupation.
	 *
	 * @return the primary key of this master occupation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this master occupation.
	 *
	 * @param primaryKey the primary key of this master occupation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the master occupation ID of this master occupation.
	 *
	 * @return the master occupation ID of this master occupation
	 */
	public long getMasterOccupationId();

	/**
	 * Sets the master occupation ID of this master occupation.
	 *
	 * @param masterOccupationId the master occupation ID of this master occupation
	 */
	public void setMasterOccupationId(long masterOccupationId);

	/**
	 * Returns the group ID of this master occupation.
	 *
	 * @return the group ID of this master occupation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this master occupation.
	 *
	 * @param groupId the group ID of this master occupation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this master occupation.
	 *
	 * @return the company ID of this master occupation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this master occupation.
	 *
	 * @param companyId the company ID of this master occupation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this master occupation.
	 *
	 * @return the user ID of this master occupation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this master occupation.
	 *
	 * @param userId the user ID of this master occupation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this master occupation.
	 *
	 * @return the user uuid of this master occupation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this master occupation.
	 *
	 * @param userUuid the user uuid of this master occupation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this master occupation.
	 *
	 * @return the user name of this master occupation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this master occupation.
	 *
	 * @param userName the user name of this master occupation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this master occupation.
	 *
	 * @return the create date of this master occupation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this master occupation.
	 *
	 * @param createDate the create date of this master occupation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this master occupation.
	 *
	 * @return the modified date of this master occupation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this master occupation.
	 *
	 * @param modifiedDate the modified date of this master occupation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this master occupation.
	 *
	 * @return the name of this master occupation
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this master occupation.
	 *
	 * @param name the name of this master occupation
	 */
	public void setName(String name);

	/**
	 * Returns the master occupation category ID of this master occupation.
	 *
	 * @return the master occupation category ID of this master occupation
	 */
	public long getMasterOccupationCategoryId();

	/**
	 * Sets the master occupation category ID of this master occupation.
	 *
	 * @param masterOccupationCategoryId the master occupation category ID of this master occupation
	 */
	public void setMasterOccupationCategoryId(long masterOccupationCategoryId);

	/**
	 * Returns the active of this master occupation.
	 *
	 * @return the active of this master occupation
	 */
	public Integer getActive();

	/**
	 * Sets the active of this master occupation.
	 *
	 * @param active the active of this master occupation
	 */
	public void setActive(Integer active);

}