/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PaymentChannel service. Represents a row in the &quot;PaymentChannel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.PaymentChannelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.PaymentChannelImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see PaymentChannel
 * @generated
 */
@ProviderType
public interface PaymentChannelModel
	extends BaseModel<PaymentChannel>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment channel model instance should use the {@link PaymentChannel} interface instead.
	 */

	/**
	 * Returns the primary key of this payment channel.
	 *
	 * @return the primary key of this payment channel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payment channel.
	 *
	 * @param primaryKey the primary key of this payment channel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the payment channel ID of this payment channel.
	 *
	 * @return the payment channel ID of this payment channel
	 */
	public long getPaymentChannelId();

	/**
	 * Sets the payment channel ID of this payment channel.
	 *
	 * @param paymentChannelId the payment channel ID of this payment channel
	 */
	public void setPaymentChannelId(long paymentChannelId);

	/**
	 * Returns the group ID of this payment channel.
	 *
	 * @return the group ID of this payment channel
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this payment channel.
	 *
	 * @param groupId the group ID of this payment channel
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this payment channel.
	 *
	 * @return the company ID of this payment channel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this payment channel.
	 *
	 * @param companyId the company ID of this payment channel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this payment channel.
	 *
	 * @return the user ID of this payment channel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this payment channel.
	 *
	 * @param userId the user ID of this payment channel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this payment channel.
	 *
	 * @return the user uuid of this payment channel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this payment channel.
	 *
	 * @param userUuid the user uuid of this payment channel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this payment channel.
	 *
	 * @return the user name of this payment channel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this payment channel.
	 *
	 * @param userName the user name of this payment channel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this payment channel.
	 *
	 * @return the create date of this payment channel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this payment channel.
	 *
	 * @param createDate the create date of this payment channel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this payment channel.
	 *
	 * @return the modified date of this payment channel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment channel.
	 *
	 * @param modifiedDate the modified date of this payment channel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this payment channel.
	 *
	 * @return the code of this payment channel
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this payment channel.
	 *
	 * @param code the code of this payment channel
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this payment channel.
	 *
	 * @return the name of this payment channel
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this payment channel.
	 *
	 * @param name the name of this payment channel
	 */
	public void setName(String name);

	/**
	 * Returns the min payment of this payment channel.
	 *
	 * @return the min payment of this payment channel
	 */
	public Double getMinPayment();

	/**
	 * Sets the min payment of this payment channel.
	 *
	 * @param minPayment the min payment of this payment channel
	 */
	public void setMinPayment(Double minPayment);

	/**
	 * Returns the max payment of this payment channel.
	 *
	 * @return the max payment of this payment channel
	 */
	public Double getMaxPayment();

	/**
	 * Sets the max payment of this payment channel.
	 *
	 * @param maxPayment the max payment of this payment channel
	 */
	public void setMaxPayment(Double maxPayment);

	/**
	 * Returns the description of this payment channel.
	 *
	 * @return the description of this payment channel
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this payment channel.
	 *
	 * @param description the description of this payment channel
	 */
	public void setDescription(String description);

	/**
	 * Returns the master bank ID of this payment channel.
	 *
	 * @return the master bank ID of this payment channel
	 */
	public long getMasterBankId();

	/**
	 * Sets the master bank ID of this payment channel.
	 *
	 * @param masterBankId the master bank ID of this payment channel
	 */
	public void setMasterBankId(long masterBankId);

	/**
	 * Returns the mdr axa of this payment channel.
	 *
	 * @return the mdr axa of this payment channel
	 */
	@AutoEscape
	public String getMdrAxa();

	/**
	 * Sets the mdr axa of this payment channel.
	 *
	 * @param mdrAxa the mdr axa of this payment channel
	 */
	public void setMdrAxa(String mdrAxa);

	/**
	 * Returns the mdr user of this payment channel.
	 *
	 * @return the mdr user of this payment channel
	 */
	@AutoEscape
	public String getMdrUser();

	/**
	 * Sets the mdr user of this payment channel.
	 *
	 * @param mdrUser the mdr user of this payment channel
	 */
	public void setMdrUser(String mdrUser);

	/**
	 * Returns the pg fee pct of this payment channel.
	 *
	 * @return the pg fee pct of this payment channel
	 */
	@AutoEscape
	public String getPgFeePct();

	/**
	 * Sets the pg fee pct of this payment channel.
	 *
	 * @param pgFeePct the pg fee pct of this payment channel
	 */
	public void setPgFeePct(String pgFeePct);

	/**
	 * Returns the pg fee amt of this payment channel.
	 *
	 * @return the pg fee amt of this payment channel
	 */
	@AutoEscape
	public String getPgFeeAmt();

	/**
	 * Sets the pg fee amt of this payment channel.
	 *
	 * @param pgFeeAmt the pg fee amt of this payment channel
	 */
	public void setPgFeeAmt(String pgFeeAmt);

	/**
	 * Returns the image file entry ID of this payment channel.
	 *
	 * @return the image file entry ID of this payment channel
	 */
	public long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this payment channel.
	 *
	 * @param imageFileEntryId the image file entry ID of this payment channel
	 */
	public void setImageFileEntryId(long imageFileEntryId);

	/**
	 * Returns the image url of this payment channel.
	 *
	 * @return the image url of this payment channel
	 */
	@AutoEscape
	public String getImageURL();

	/**
	 * Sets the image url of this payment channel.
	 *
	 * @param imageURL the image url of this payment channel
	 */
	public void setImageURL(String imageURL);

	/**
	 * Returns the utm only of this payment channel.
	 *
	 * @return the utm only of this payment channel
	 */
	public Integer getUtmOnly();

	/**
	 * Sets the utm only of this payment channel.
	 *
	 * @param utmOnly the utm only of this payment channel
	 */
	public void setUtmOnly(Integer utmOnly);

	/**
	 * Returns the mall ID of this payment channel.
	 *
	 * @return the mall ID of this payment channel
	 */
	@AutoEscape
	public String getMallId();

	/**
	 * Sets the mall ID of this payment channel.
	 *
	 * @param mallId the mall ID of this payment channel
	 */
	public void setMallId(String mallId);

	/**
	 * Returns the shared key of this payment channel.
	 *
	 * @return the shared key of this payment channel
	 */
	@AutoEscape
	public String getSharedKey();

	/**
	 * Sets the shared key of this payment channel.
	 *
	 * @param sharedKey the shared key of this payment channel
	 */
	public void setSharedKey(String sharedKey);

	/**
	 * Returns the active of this payment channel.
	 *
	 * @return the active of this payment channel
	 */
	public Integer getActive();

	/**
	 * Sets the active of this payment channel.
	 *
	 * @param active the active of this payment channel
	 */
	public void setActive(Integer active);

}