/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PaymentChannelTenor service. Represents a row in the &quot;PaymentChannelTenor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.PaymentChannelTenorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.PaymentChannelTenorImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see PaymentChannelTenor
 * @generated
 */
@ProviderType
public interface PaymentChannelTenorModel
	extends BaseModel<PaymentChannelTenor>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment channel tenor model instance should use the {@link PaymentChannelTenor} interface instead.
	 */

	/**
	 * Returns the primary key of this payment channel tenor.
	 *
	 * @return the primary key of this payment channel tenor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payment channel tenor.
	 *
	 * @param primaryKey the primary key of this payment channel tenor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the payment channel tenor ID of this payment channel tenor.
	 *
	 * @return the payment channel tenor ID of this payment channel tenor
	 */
	public long getPaymentChannelTenorId();

	/**
	 * Sets the payment channel tenor ID of this payment channel tenor.
	 *
	 * @param paymentChannelTenorId the payment channel tenor ID of this payment channel tenor
	 */
	public void setPaymentChannelTenorId(long paymentChannelTenorId);

	/**
	 * Returns the group ID of this payment channel tenor.
	 *
	 * @return the group ID of this payment channel tenor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this payment channel tenor.
	 *
	 * @param groupId the group ID of this payment channel tenor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this payment channel tenor.
	 *
	 * @return the company ID of this payment channel tenor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this payment channel tenor.
	 *
	 * @param companyId the company ID of this payment channel tenor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this payment channel tenor.
	 *
	 * @return the user ID of this payment channel tenor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this payment channel tenor.
	 *
	 * @param userId the user ID of this payment channel tenor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this payment channel tenor.
	 *
	 * @return the user uuid of this payment channel tenor
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this payment channel tenor.
	 *
	 * @param userUuid the user uuid of this payment channel tenor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this payment channel tenor.
	 *
	 * @return the user name of this payment channel tenor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this payment channel tenor.
	 *
	 * @param userName the user name of this payment channel tenor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this payment channel tenor.
	 *
	 * @return the create date of this payment channel tenor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this payment channel tenor.
	 *
	 * @param createDate the create date of this payment channel tenor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this payment channel tenor.
	 *
	 * @return the modified date of this payment channel tenor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this payment channel tenor.
	 *
	 * @param modifiedDate the modified date of this payment channel tenor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the payment channel ID of this payment channel tenor.
	 *
	 * @return the payment channel ID of this payment channel tenor
	 */
	public long getPaymentChannelId();

	/**
	 * Sets the payment channel ID of this payment channel tenor.
	 *
	 * @param paymentChannelId the payment channel ID of this payment channel tenor
	 */
	public void setPaymentChannelId(long paymentChannelId);

	/**
	 * Returns the promoid of this payment channel tenor.
	 *
	 * @return the promoid of this payment channel tenor
	 */
	@AutoEscape
	public String getPromoid();

	/**
	 * Sets the promoid of this payment channel tenor.
	 *
	 * @param promoid the promoid of this payment channel tenor
	 */
	public void setPromoid(String promoid);

	/**
	 * Returns the tenor of this payment channel tenor.
	 *
	 * @return the tenor of this payment channel tenor
	 */
	@AutoEscape
	public String getTenor();

	/**
	 * Sets the tenor of this payment channel tenor.
	 *
	 * @param tenor the tenor of this payment channel tenor
	 */
	public void setTenor(String tenor);

	/**
	 * Returns the tenorid of this payment channel tenor.
	 *
	 * @return the tenorid of this payment channel tenor
	 */
	@AutoEscape
	public String getTenorid();

	/**
	 * Sets the tenorid of this payment channel tenor.
	 *
	 * @param tenorid the tenorid of this payment channel tenor
	 */
	public void setTenorid(String tenorid);

	/**
	 * Returns the acquirer of this payment channel tenor.
	 *
	 * @return the acquirer of this payment channel tenor
	 */
	@AutoEscape
	public String getAcquirer();

	/**
	 * Sets the acquirer of this payment channel tenor.
	 *
	 * @param acquirer the acquirer of this payment channel tenor
	 */
	public void setAcquirer(String acquirer);

	/**
	 * Returns the active of this payment channel tenor.
	 *
	 * @return the active of this payment channel tenor
	 */
	public Integer getActive();

	/**
	 * Sets the active of this payment channel tenor.
	 *
	 * @param active the active of this payment channel tenor
	 */
	public void setActive(Integer active);

}