/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersonalAccidentPremi service. Represents a row in the &quot;PersonalAccidentPremi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.PersonalAccidentPremiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.PersonalAccidentPremiImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see PersonalAccidentPremi
 * @generated
 */
@ProviderType
public interface PersonalAccidentPremiModel
	extends BaseModel<PersonalAccidentPremi>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a personal accident premi model instance should use the {@link PersonalAccidentPremi} interface instead.
	 */

	/**
	 * Returns the primary key of this personal accident premi.
	 *
	 * @return the primary key of this personal accident premi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this personal accident premi.
	 *
	 * @param primaryKey the primary key of this personal accident premi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the personal accident premi ID of this personal accident premi.
	 *
	 * @return the personal accident premi ID of this personal accident premi
	 */
	public long getPersonalAccidentPremiId();

	/**
	 * Sets the personal accident premi ID of this personal accident premi.
	 *
	 * @param personalAccidentPremiId the personal accident premi ID of this personal accident premi
	 */
	public void setPersonalAccidentPremiId(long personalAccidentPremiId);

	/**
	 * Returns the group ID of this personal accident premi.
	 *
	 * @return the group ID of this personal accident premi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this personal accident premi.
	 *
	 * @param groupId the group ID of this personal accident premi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this personal accident premi.
	 *
	 * @return the company ID of this personal accident premi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this personal accident premi.
	 *
	 * @param companyId the company ID of this personal accident premi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this personal accident premi.
	 *
	 * @return the user ID of this personal accident premi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this personal accident premi.
	 *
	 * @param userId the user ID of this personal accident premi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this personal accident premi.
	 *
	 * @return the user uuid of this personal accident premi
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this personal accident premi.
	 *
	 * @param userUuid the user uuid of this personal accident premi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this personal accident premi.
	 *
	 * @return the user name of this personal accident premi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this personal accident premi.
	 *
	 * @param userName the user name of this personal accident premi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this personal accident premi.
	 *
	 * @return the create date of this personal accident premi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this personal accident premi.
	 *
	 * @param createDate the create date of this personal accident premi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this personal accident premi.
	 *
	 * @return the modified date of this personal accident premi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this personal accident premi.
	 *
	 * @param modifiedDate the modified date of this personal accident premi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the premi type of this personal accident premi.
	 *
	 * @return the premi type of this personal accident premi
	 */
	@AutoEscape
	public String getPremiType();

	/**
	 * Sets the premi type of this personal accident premi.
	 *
	 * @param premiType the premi type of this personal accident premi
	 */
	public void setPremiType(String premiType);

	/**
	 * Returns the amount of this personal accident premi.
	 *
	 * @return the amount of this personal accident premi
	 */
	public double getAmount();

	/**
	 * Sets the amount of this personal accident premi.
	 *
	 * @param amount the amount of this personal accident premi
	 */
	public void setAmount(double amount);

	/**
	 * Returns the active of this personal accident premi.
	 *
	 * @return the active of this personal accident premi
	 */
	public int getActive();

	/**
	 * Sets the active of this personal accident premi.
	 *
	 * @param active the active of this personal accident premi
	 */
	public void setActive(int active);

}