/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PetAnimalType service. Represents a row in the &quot;PetAnimalType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.PetAnimalTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.PetAnimalTypeImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see PetAnimalType
 * @generated
 */
@ProviderType
public interface PetAnimalTypeModel
	extends BaseModel<PetAnimalType>, GroupedModel, ShardedModel, TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pet animal type model instance should use the {@link PetAnimalType} interface instead.
	 */

	/**
	 * Returns the primary key of this pet animal type.
	 *
	 * @return the primary key of this pet animal type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pet animal type.
	 *
	 * @param primaryKey the primary key of this pet animal type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pet animal type ID of this pet animal type.
	 *
	 * @return the pet animal type ID of this pet animal type
	 */
	public long getPetAnimalTypeId();

	/**
	 * Sets the pet animal type ID of this pet animal type.
	 *
	 * @param petAnimalTypeId the pet animal type ID of this pet animal type
	 */
	public void setPetAnimalTypeId(long petAnimalTypeId);

	/**
	 * Returns the name of this pet animal type.
	 *
	 * @return the name of this pet animal type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this pet animal type.
	 *
	 * @param name the name of this pet animal type
	 */
	public void setName(String name);

	/**
	 * Returns the active of this pet animal type.
	 *
	 * @return the active of this pet animal type
	 */
	public int getActive();

	/**
	 * Sets the active of this pet animal type.
	 *
	 * @param active the active of this pet animal type
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this pet animal type.
	 *
	 * @return the group ID of this pet animal type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pet animal type.
	 *
	 * @param groupId the group ID of this pet animal type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pet animal type.
	 *
	 * @return the company ID of this pet animal type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pet animal type.
	 *
	 * @param companyId the company ID of this pet animal type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pet animal type.
	 *
	 * @return the user ID of this pet animal type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pet animal type.
	 *
	 * @param userId the user ID of this pet animal type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pet animal type.
	 *
	 * @return the user uuid of this pet animal type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pet animal type.
	 *
	 * @param userUuid the user uuid of this pet animal type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pet animal type.
	 *
	 * @return the user name of this pet animal type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pet animal type.
	 *
	 * @param userName the user name of this pet animal type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pet animal type.
	 *
	 * @return the create date of this pet animal type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pet animal type.
	 *
	 * @param createDate the create date of this pet animal type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pet animal type.
	 *
	 * @return the modified date of this pet animal type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pet animal type.
	 *
	 * @param modifiedDate the modified date of this pet animal type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this pet animal type.
	 *
	 * @return the status of this pet animal type
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this pet animal type was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this pet animal type.
	 *
	 * @return the trash entry created when this pet animal type was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this pet animal type.
	 *
	 * @return the class primary key of the trash entry for this pet animal type
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this pet animal type.
	 *
	 * @return the trash handler for this pet animal type
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this pet animal type is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this pet animal type is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this pet animal type is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this pet animal type is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}