/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PetDetail service. Represents a row in the &quot;PetDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.PetDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.PetDetailImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see PetDetail
 * @generated
 */
@ProviderType
public interface PetDetailModel
	extends BaseModel<PetDetail>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pet detail model instance should use the {@link PetDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this pet detail.
	 *
	 * @return the primary key of this pet detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pet detail.
	 *
	 * @param primaryKey the primary key of this pet detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pet detail ID of this pet detail.
	 *
	 * @return the pet detail ID of this pet detail
	 */
	public long getPetDetailId();

	/**
	 * Sets the pet detail ID of this pet detail.
	 *
	 * @param petDetailId the pet detail ID of this pet detail
	 */
	public void setPetDetailId(long petDetailId);

	/**
	 * Returns the group ID of this pet detail.
	 *
	 * @return the group ID of this pet detail
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pet detail.
	 *
	 * @param groupId the group ID of this pet detail
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pet detail.
	 *
	 * @return the company ID of this pet detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pet detail.
	 *
	 * @param companyId the company ID of this pet detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pet detail.
	 *
	 * @return the user ID of this pet detail
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pet detail.
	 *
	 * @param userId the user ID of this pet detail
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pet detail.
	 *
	 * @return the user uuid of this pet detail
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pet detail.
	 *
	 * @param userUuid the user uuid of this pet detail
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pet detail.
	 *
	 * @return the user name of this pet detail
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pet detail.
	 *
	 * @param userName the user name of this pet detail
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pet detail.
	 *
	 * @return the create date of this pet detail
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pet detail.
	 *
	 * @param createDate the create date of this pet detail
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pet detail.
	 *
	 * @return the modified date of this pet detail
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pet detail.
	 *
	 * @param modifiedDate the modified date of this pet detail
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the remarks a value of this pet detail.
	 *
	 * @return the remarks a value of this pet detail
	 */
	@AutoEscape
	public String getRemarksAValue();

	/**
	 * Sets the remarks a value of this pet detail.
	 *
	 * @param remarksAValue the remarks a value of this pet detail
	 */
	public void setRemarksAValue(String remarksAValue);

	/**
	 * Returns the remarks b value of this pet detail.
	 *
	 * @return the remarks b value of this pet detail
	 */
	@AutoEscape
	public String getRemarksBValue();

	/**
	 * Sets the remarks b value of this pet detail.
	 *
	 * @param remarksBValue the remarks b value of this pet detail
	 */
	public void setRemarksBValue(String remarksBValue);

	/**
	 * Returns the remarks c value of this pet detail.
	 *
	 * @return the remarks c value of this pet detail
	 */
	@AutoEscape
	public String getRemarksCValue();

	/**
	 * Sets the remarks c value of this pet detail.
	 *
	 * @param remarksCValue the remarks c value of this pet detail
	 */
	public void setRemarksCValue(String remarksCValue);

	/**
	 * Returns the remarks d value of this pet detail.
	 *
	 * @return the remarks d value of this pet detail
	 */
	@AutoEscape
	public String getRemarksDValue();

	/**
	 * Sets the remarks d value of this pet detail.
	 *
	 * @param remarksDValue the remarks d value of this pet detail
	 */
	public void setRemarksDValue(String remarksDValue);

	/**
	 * Returns the pet name of this pet detail.
	 *
	 * @return the pet name of this pet detail
	 */
	@AutoEscape
	public String getPetName();

	/**
	 * Sets the pet name of this pet detail.
	 *
	 * @param petName the pet name of this pet detail
	 */
	public void setPetName(String petName);

	/**
	 * Returns the pet type of this pet detail.
	 *
	 * @return the pet type of this pet detail
	 */
	public int getPetType();

	/**
	 * Sets the pet type of this pet detail.
	 *
	 * @param petType the pet type of this pet detail
	 */
	public void setPetType(int petType);

	/**
	 * Returns the pet gender of this pet detail.
	 *
	 * @return the pet gender of this pet detail
	 */
	public int getPetGender();

	/**
	 * Sets the pet gender of this pet detail.
	 *
	 * @param petGender the pet gender of this pet detail
	 */
	public void setPetGender(int petGender);

	/**
	 * Returns the pet dob of this pet detail.
	 *
	 * @return the pet dob of this pet detail
	 */
	public Date getPetDob();

	/**
	 * Sets the pet dob of this pet detail.
	 *
	 * @param petDob the pet dob of this pet detail
	 */
	public void setPetDob(Date petDob);

	/**
	 * Returns the pet ID number of this pet detail.
	 *
	 * @return the pet ID number of this pet detail
	 */
	@AutoEscape
	public String getPetIdNumber();

	/**
	 * Sets the pet ID number of this pet detail.
	 *
	 * @param petIdNumber the pet ID number of this pet detail
	 */
	public void setPetIdNumber(String petIdNumber);

	/**
	 * Returns the pet ID number issuing of this pet detail.
	 *
	 * @return the pet ID number issuing of this pet detail
	 */
	@AutoEscape
	public String getPetIdNumberIssuing();

	/**
	 * Sets the pet ID number issuing of this pet detail.
	 *
	 * @param petIdNumberIssuing the pet ID number issuing of this pet detail
	 */
	public void setPetIdNumberIssuing(String petIdNumberIssuing);

	/**
	 * Returns the pet ID number file of this pet detail.
	 *
	 * @return the pet ID number file of this pet detail
	 */
	@AutoEscape
	public String getPetIdNumberFile();

	/**
	 * Sets the pet ID number file of this pet detail.
	 *
	 * @param petIdNumberFile the pet ID number file of this pet detail
	 */
	public void setPetIdNumberFile(String petIdNumberFile);

	/**
	 * Returns the pet photo of this pet detail.
	 *
	 * @return the pet photo of this pet detail
	 */
	@AutoEscape
	public String getPetPhoto();

	/**
	 * Sets the pet photo of this pet detail.
	 *
	 * @param petPhoto the pet photo of this pet detail
	 */
	public void setPetPhoto(String petPhoto);

	/**
	 * Returns the pet location of this pet detail.
	 *
	 * @return the pet location of this pet detail
	 */
	@AutoEscape
	public String getPetLocation();

	/**
	 * Sets the pet location of this pet detail.
	 *
	 * @param petLocation the pet location of this pet detail
	 */
	public void setPetLocation(String petLocation);

	/**
	 * Returns the pet vaccine of this pet detail.
	 *
	 * @return the pet vaccine of this pet detail
	 */
	public int getPetVaccine();

	/**
	 * Sets the pet vaccine of this pet detail.
	 *
	 * @param petVaccine the pet vaccine of this pet detail
	 */
	public void setPetVaccine(int petVaccine);

	/**
	 * Returns the pet authorized certificate of this pet detail.
	 *
	 * @return the pet authorized certificate of this pet detail
	 */
	public int getPetAuthorizedCertificate();

	/**
	 * Sets the pet authorized certificate of this pet detail.
	 *
	 * @param petAuthorizedCertificate the pet authorized certificate of this pet detail
	 */
	public void setPetAuthorizedCertificate(int petAuthorizedCertificate);

}