/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PetPlan service. Represents a row in the &quot;PetPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.PetPlanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.PetPlanImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see PetPlan
 * @generated
 */
@ProviderType
public interface PetPlanModel
	extends BaseModel<PetPlan>, GroupedModel, ShardedModel, StagedAuditedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pet plan model instance should use the {@link PetPlan} interface instead.
	 */

	/**
	 * Returns the primary key of this pet plan.
	 *
	 * @return the primary key of this pet plan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pet plan.
	 *
	 * @param primaryKey the primary key of this pet plan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this pet plan.
	 *
	 * @return the uuid of this pet plan
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this pet plan.
	 *
	 * @param uuid the uuid of this pet plan
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the pet plan ID of this pet plan.
	 *
	 * @return the pet plan ID of this pet plan
	 */
	public long getPetPlanId();

	/**
	 * Sets the pet plan ID of this pet plan.
	 *
	 * @param petPlanId the pet plan ID of this pet plan
	 */
	public void setPetPlanId(long petPlanId);

	/**
	 * Returns the name of this pet plan.
	 *
	 * @return the name of this pet plan
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this pet plan.
	 *
	 * @param name the name of this pet plan
	 */
	public void setName(String name);

	/**
	 * Returns the limit disability of this pet plan.
	 *
	 * @return the limit disability of this pet plan
	 */
	public long getLimitDisability();

	/**
	 * Sets the limit disability of this pet plan.
	 *
	 * @param limitDisability the limit disability of this pet plan
	 */
	public void setLimitDisability(long limitDisability);

	/**
	 * Returns the limit medical of this pet plan.
	 *
	 * @return the limit medical of this pet plan
	 */
	public long getLimitMedical();

	/**
	 * Sets the limit medical of this pet plan.
	 *
	 * @param limitMedical the limit medical of this pet plan
	 */
	public void setLimitMedical(long limitMedical);

	/**
	 * Returns the limit third party of this pet plan.
	 *
	 * @return the limit third party of this pet plan
	 */
	public long getLimitThirdParty();

	/**
	 * Sets the limit third party of this pet plan.
	 *
	 * @param limitThirdParty the limit third party of this pet plan
	 */
	public void setLimitThirdParty(long limitThirdParty);

	/**
	 * Returns the limit custody of this pet plan.
	 *
	 * @return the limit custody of this pet plan
	 */
	public long getLimitCustody();

	/**
	 * Sets the limit custody of this pet plan.
	 *
	 * @param limitCustody the limit custody of this pet plan
	 */
	public void setLimitCustody(long limitCustody);

	/**
	 * Returns the recommended of this pet plan.
	 *
	 * @return the recommended of this pet plan
	 */
	public int getRecommended();

	/**
	 * Sets the recommended of this pet plan.
	 *
	 * @param recommended the recommended of this pet plan
	 */
	public void setRecommended(int recommended);

	/**
	 * Returns the custom plan of this pet plan.
	 *
	 * @return the custom plan of this pet plan
	 */
	public int getCustomPlan();

	/**
	 * Sets the custom plan of this pet plan.
	 *
	 * @param customPlan the custom plan of this pet plan
	 */
	public void setCustomPlan(int customPlan);

	/**
	 * Returns the benefit of this pet plan.
	 *
	 * @return the benefit of this pet plan
	 */
	@AutoEscape
	public String getBenefit();

	/**
	 * Sets the benefit of this pet plan.
	 *
	 * @param benefit the benefit of this pet plan
	 */
	public void setBenefit(String benefit);

	/**
	 * Returns the pimcore plan ID of this pet plan.
	 *
	 * @return the pimcore plan ID of this pet plan
	 */
	public long getPimcorePlanId();

	/**
	 * Sets the pimcore plan ID of this pet plan.
	 *
	 * @param pimcorePlanId the pimcore plan ID of this pet plan
	 */
	public void setPimcorePlanId(long pimcorePlanId);

	/**
	 * Returns the active of this pet plan.
	 *
	 * @return the active of this pet plan
	 */
	public int getActive();

	/**
	 * Sets the active of this pet plan.
	 *
	 * @param active the active of this pet plan
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this pet plan.
	 *
	 * @return the group ID of this pet plan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pet plan.
	 *
	 * @param groupId the group ID of this pet plan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pet plan.
	 *
	 * @return the company ID of this pet plan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pet plan.
	 *
	 * @param companyId the company ID of this pet plan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pet plan.
	 *
	 * @return the user ID of this pet plan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pet plan.
	 *
	 * @param userId the user ID of this pet plan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pet plan.
	 *
	 * @return the user uuid of this pet plan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pet plan.
	 *
	 * @param userUuid the user uuid of this pet plan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pet plan.
	 *
	 * @return the user name of this pet plan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pet plan.
	 *
	 * @param userName the user name of this pet plan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pet plan.
	 *
	 * @return the create date of this pet plan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pet plan.
	 *
	 * @param createDate the create date of this pet plan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pet plan.
	 *
	 * @return the modified date of this pet plan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pet plan.
	 *
	 * @param modifiedDate the modified date of this pet plan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this pet plan.
	 *
	 * @return the status of this pet plan
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this pet plan was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this pet plan.
	 *
	 * @return the trash entry created when this pet plan was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this pet plan.
	 *
	 * @return the class primary key of the trash entry for this pet plan
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this pet plan.
	 *
	 * @return the trash handler for this pet plan
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this pet plan is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this pet plan is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this pet plan is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this pet plan is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}