/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PetRemarks service. Represents a row in the &quot;PetRemarks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.PetRemarksModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.PetRemarksImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see PetRemarks
 * @generated
 */
@ProviderType
public interface PetRemarksModel
	extends BaseModel<PetRemarks>, GroupedModel, ShardedModel, TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pet remarks model instance should use the {@link PetRemarks} interface instead.
	 */

	/**
	 * Returns the primary key of this pet remarks.
	 *
	 * @return the primary key of this pet remarks
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pet remarks.
	 *
	 * @param primaryKey the primary key of this pet remarks
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pet remarks ID of this pet remarks.
	 *
	 * @return the pet remarks ID of this pet remarks
	 */
	public long getPetRemarksId();

	/**
	 * Sets the pet remarks ID of this pet remarks.
	 *
	 * @param petRemarksId the pet remarks ID of this pet remarks
	 */
	public void setPetRemarksId(long petRemarksId);

	/**
	 * Returns the name of this pet remarks.
	 *
	 * @return the name of this pet remarks
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this pet remarks.
	 *
	 * @param name the name of this pet remarks
	 */
	public void setName(String name);

	/**
	 * Returns the code of this pet remarks.
	 *
	 * @return the code of this pet remarks
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this pet remarks.
	 *
	 * @param code the code of this pet remarks
	 */
	public void setCode(String code);

	/**
	 * Returns the active of this pet remarks.
	 *
	 * @return the active of this pet remarks
	 */
	public int getActive();

	/**
	 * Sets the active of this pet remarks.
	 *
	 * @param active the active of this pet remarks
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this pet remarks.
	 *
	 * @return the group ID of this pet remarks
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pet remarks.
	 *
	 * @param groupId the group ID of this pet remarks
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pet remarks.
	 *
	 * @return the company ID of this pet remarks
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pet remarks.
	 *
	 * @param companyId the company ID of this pet remarks
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pet remarks.
	 *
	 * @return the user ID of this pet remarks
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pet remarks.
	 *
	 * @param userId the user ID of this pet remarks
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pet remarks.
	 *
	 * @return the user uuid of this pet remarks
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pet remarks.
	 *
	 * @param userUuid the user uuid of this pet remarks
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pet remarks.
	 *
	 * @return the user name of this pet remarks
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pet remarks.
	 *
	 * @param userName the user name of this pet remarks
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pet remarks.
	 *
	 * @return the create date of this pet remarks
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pet remarks.
	 *
	 * @param createDate the create date of this pet remarks
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pet remarks.
	 *
	 * @return the modified date of this pet remarks
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pet remarks.
	 *
	 * @param modifiedDate the modified date of this pet remarks
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this pet remarks.
	 *
	 * @return the status of this pet remarks
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this pet remarks was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this pet remarks.
	 *
	 * @return the trash entry created when this pet remarks was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this pet remarks.
	 *
	 * @return the class primary key of the trash entry for this pet remarks
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this pet remarks.
	 *
	 * @return the trash handler for this pet remarks
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this pet remarks is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this pet remarks is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this pet remarks is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this pet remarks is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}