/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.TrashedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductConfiguration service. Represents a row in the &quot;ProductConfiguration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.ProductConfigurationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.ProductConfigurationImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see ProductConfiguration
 * @generated
 */
@ProviderType
public interface ProductConfigurationModel
	extends BaseModel<ProductConfiguration>, TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product configuration model instance should use the {@link ProductConfiguration} interface instead.
	 */

	/**
	 * Returns the primary key of this product configuration.
	 *
	 * @return the primary key of this product configuration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product configuration.
	 *
	 * @param primaryKey the primary key of this product configuration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product ID of this product configuration.
	 *
	 * @return the product ID of this product configuration
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product configuration.
	 *
	 * @param productId the product ID of this product configuration
	 */
	public void setProductId(long productId);

	/**
	 * Returns the product code of this product configuration.
	 *
	 * @return the product code of this product configuration
	 */
	@AutoEscape
	public String getProductCode();

	/**
	 * Sets the product code of this product configuration.
	 *
	 * @param productCode the product code of this product configuration
	 */
	public void setProductCode(String productCode);

	/**
	 * Returns the product name of this product configuration.
	 *
	 * @return the product name of this product configuration
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this product configuration.
	 *
	 * @param productName the product name of this product configuration
	 */
	public void setProductName(String productName);

	/**
	 * Returns the ojk name of this product configuration.
	 *
	 * @return the ojk name of this product configuration
	 */
	@AutoEscape
	public String getOjkName();

	/**
	 * Sets the ojk name of this product configuration.
	 *
	 * @param ojkName the ojk name of this product configuration
	 */
	public void setOjkName(String ojkName);

	/**
	 * Returns the stampduty idr of this product configuration.
	 *
	 * @return the stampduty idr of this product configuration
	 */
	public Double getStampdutyIDR();

	/**
	 * Sets the stampduty idr of this product configuration.
	 *
	 * @param stampdutyIDR the stampduty idr of this product configuration
	 */
	public void setStampdutyIDR(Double stampdutyIDR);

	/**
	 * Returns the stampduty usd of this product configuration.
	 *
	 * @return the stampduty usd of this product configuration
	 */
	public Double getStampdutyUSD();

	/**
	 * Sets the stampduty usd of this product configuration.
	 *
	 * @param stampdutyUSD the stampduty usd of this product configuration
	 */
	public void setStampdutyUSD(Double stampdutyUSD);

	/**
	 * Returns the policy cost idr of this product configuration.
	 *
	 * @return the policy cost idr of this product configuration
	 */
	public Double getPolicyCostIDR();

	/**
	 * Sets the policy cost idr of this product configuration.
	 *
	 * @param policyCostIDR the policy cost idr of this product configuration
	 */
	public void setPolicyCostIDR(Double policyCostIDR);

	/**
	 * Returns the policy cost usd of this product configuration.
	 *
	 * @return the policy cost usd of this product configuration
	 */
	public Double getPolicyCostUSD();

	/**
	 * Sets the policy cost usd of this product configuration.
	 *
	 * @param policyCostUSD the policy cost usd of this product configuration
	 */
	public void setPolicyCostUSD(Double policyCostUSD);

	/**
	 * Returns the acl status of this product configuration.
	 *
	 * @return the acl status of this product configuration
	 */
	public int getAclStatus();

	/**
	 * Sets the acl status of this product configuration.
	 *
	 * @param aclStatus the acl status of this product configuration
	 */
	public void setAclStatus(int aclStatus);

	/**
	 * Returns the acl grace period of this product configuration.
	 *
	 * @return the acl grace period of this product configuration
	 */
	public int getAclGracePeriod();

	/**
	 * Sets the acl grace period of this product configuration.
	 *
	 * @param aclGracePeriod the acl grace period of this product configuration
	 */
	public void setAclGracePeriod(int aclGracePeriod);

	/**
	 * Returns the commission of this product configuration.
	 *
	 * @return the commission of this product configuration
	 */
	public Double getCommission();

	/**
	 * Sets the commission of this product configuration.
	 *
	 * @param commission the commission of this product configuration
	 */
	public void setCommission(Double commission);

	/**
	 * Returns the web content folder ID of this product configuration.
	 *
	 * @return the web content folder ID of this product configuration
	 */
	public int getWebContentFolderId();

	/**
	 * Sets the web content folder ID of this product configuration.
	 *
	 * @param webContentFolderId the web content folder ID of this product configuration
	 */
	public void setWebContentFolderId(int webContentFolderId);

	/**
	 * Returns the link of this product configuration.
	 *
	 * @return the link of this product configuration
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this product configuration.
	 *
	 * @param link the link of this product configuration
	 */
	public void setLink(String link);

	/**
	 * Returns the is b2c of this product configuration.
	 *
	 * @return the is b2c of this product configuration
	 */
	public int getIsB2C();

	/**
	 * Sets the is b2c of this product configuration.
	 *
	 * @param isB2C the is b2c of this product configuration
	 */
	public void setIsB2C(int isB2C);

	/**
	 * Returns the is b2b of this product configuration.
	 *
	 * @return the is b2b of this product configuration
	 */
	public int getIsB2B();

	/**
	 * Sets the is b2b of this product configuration.
	 *
	 * @param isB2B the is b2b of this product configuration
	 */
	public void setIsB2B(int isB2B);

	/**
	 * Returns the is b2b2c of this product configuration.
	 *
	 * @return the is b2b2c of this product configuration
	 */
	public int getIsB2B2C();

	/**
	 * Sets the is b2b2c of this product configuration.
	 *
	 * @param isB2B2C the is b2b2c of this product configuration
	 */
	public void setIsB2B2C(int isB2B2C);

	/**
	 * Returns the icon file entry ID of this product configuration.
	 *
	 * @return the icon file entry ID of this product configuration
	 */
	public Long getIconFileEntryId();

	/**
	 * Sets the icon file entry ID of this product configuration.
	 *
	 * @param iconFileEntryId the icon file entry ID of this product configuration
	 */
	public void setIconFileEntryId(Long iconFileEntryId);

	/**
	 * Returns the image file entry ID of this product configuration.
	 *
	 * @return the image file entry ID of this product configuration
	 */
	public Long getImageFileEntryId();

	/**
	 * Sets the image file entry ID of this product configuration.
	 *
	 * @param imageFileEntryId the image file entry ID of this product configuration
	 */
	public void setImageFileEntryId(Long imageFileEntryId);

	/**
	 * Returns the pep enable of this product configuration.
	 *
	 * @return the pep enable of this product configuration
	 */
	public int getPepEnable();

	/**
	 * Sets the pep enable of this product configuration.
	 *
	 * @param pepEnable the pep enable of this product configuration
	 */
	public void setPepEnable(int pepEnable);

	/**
	 * Returns the policy wording entry ID of this product configuration.
	 *
	 * @return the policy wording entry ID of this product configuration
	 */
	public Long getPolicyWordingEntryId();

	/**
	 * Sets the policy wording entry ID of this product configuration.
	 *
	 * @param policyWordingEntryId the policy wording entry ID of this product configuration
	 */
	public void setPolicyWordingEntryId(Long policyWordingEntryId);

	/**
	 * Returns the meta title of this product configuration.
	 *
	 * @return the meta title of this product configuration
	 */
	@AutoEscape
	public String getMetaTitle();

	/**
	 * Sets the meta title of this product configuration.
	 *
	 * @param metaTitle the meta title of this product configuration
	 */
	public void setMetaTitle(String metaTitle);

	/**
	 * Returns the meta description of this product configuration.
	 *
	 * @return the meta description of this product configuration
	 */
	@AutoEscape
	public String getMetaDescription();

	/**
	 * Sets the meta description of this product configuration.
	 *
	 * @param metaDescription the meta description of this product configuration
	 */
	public void setMetaDescription(String metaDescription);

	/**
	 * Returns the meta keywords of this product configuration.
	 *
	 * @return the meta keywords of this product configuration
	 */
	@AutoEscape
	public String getMetaKeywords();

	/**
	 * Sets the meta keywords of this product configuration.
	 *
	 * @param metaKeywords the meta keywords of this product configuration
	 */
	public void setMetaKeywords(String metaKeywords);

	/**
	 * Returns the status of this product configuration.
	 *
	 * @return the status of this product configuration
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this product configuration was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this product configuration.
	 *
	 * @return the trash entry created when this product configuration was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this product configuration.
	 *
	 * @return the class primary key of the trash entry for this product configuration
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this product configuration.
	 *
	 * @return the trash handler for this product configuration
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this product configuration is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this product configuration is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this product configuration is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this product configuration is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}