/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ReferenceNumber service. Represents a row in the &quot;ReferenceNumber&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.ReferenceNumberModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.ReferenceNumberImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see ReferenceNumber
 * @generated
 */
@ProviderType
public interface ReferenceNumberModel
	extends BaseModel<ReferenceNumber>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reference number model instance should use the {@link ReferenceNumber} interface instead.
	 */

	/**
	 * Returns the primary key of this reference number.
	 *
	 * @return the primary key of this reference number
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reference number.
	 *
	 * @param primaryKey the primary key of this reference number
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reference number ID of this reference number.
	 *
	 * @return the reference number ID of this reference number
	 */
	public long getReferenceNumberId();

	/**
	 * Sets the reference number ID of this reference number.
	 *
	 * @param referenceNumberId the reference number ID of this reference number
	 */
	public void setReferenceNumberId(long referenceNumberId);

	/**
	 * Returns the group ID of this reference number.
	 *
	 * @return the group ID of this reference number
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this reference number.
	 *
	 * @param groupId the group ID of this reference number
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reference number.
	 *
	 * @return the company ID of this reference number
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reference number.
	 *
	 * @param companyId the company ID of this reference number
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this reference number.
	 *
	 * @return the user ID of this reference number
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this reference number.
	 *
	 * @param userId the user ID of this reference number
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this reference number.
	 *
	 * @return the user uuid of this reference number
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this reference number.
	 *
	 * @param userUuid the user uuid of this reference number
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this reference number.
	 *
	 * @return the user name of this reference number
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this reference number.
	 *
	 * @param userName the user name of this reference number
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this reference number.
	 *
	 * @return the create date of this reference number
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this reference number.
	 *
	 * @param createDate the create date of this reference number
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this reference number.
	 *
	 * @return the modified date of this reference number
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this reference number.
	 *
	 * @param modifiedDate the modified date of this reference number
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user role of this reference number.
	 *
	 * @return the user role of this reference number
	 */
	@AutoEscape
	public String getUserRole();

	/**
	 * Sets the user role of this reference number.
	 *
	 * @param userRole the user role of this reference number
	 */
	public void setUserRole(String userRole);

	/**
	 * Returns the channel of this reference number.
	 *
	 * @return the channel of this reference number
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this reference number.
	 *
	 * @param channel the channel of this reference number
	 */
	public void setChannel(String channel);

	/**
	 * Returns the type of this reference number.
	 *
	 * @return the type of this reference number
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this reference number.
	 *
	 * @param type the type of this reference number
	 */
	public void setType(String type);

	/**
	 * Returns the product code of this reference number.
	 *
	 * @return the product code of this reference number
	 */
	@AutoEscape
	public String getProductCode();

	/**
	 * Sets the product code of this reference number.
	 *
	 * @param productCode the product code of this reference number
	 */
	public void setProductCode(String productCode);

	/**
	 * Returns the business type of this reference number.
	 *
	 * @return the business type of this reference number
	 */
	@AutoEscape
	public String getBusinessType();

	/**
	 * Sets the business type of this reference number.
	 *
	 * @param businessType the business type of this reference number
	 */
	public void setBusinessType(String businessType);

	/**
	 * Returns the currency of this reference number.
	 *
	 * @return the currency of this reference number
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this reference number.
	 *
	 * @param currency the currency of this reference number
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the prefix of this reference number.
	 *
	 * @return the prefix of this reference number
	 */
	@AutoEscape
	public String getPrefix();

	/**
	 * Sets the prefix of this reference number.
	 *
	 * @param prefix the prefix of this reference number
	 */
	public void setPrefix(String prefix);

	/**
	 * Returns the active of this reference number.
	 *
	 * @return the active of this reference number
	 */
	public int getActive();

	/**
	 * Sets the active of this reference number.
	 *
	 * @param active the active of this reference number
	 */
	public void setActive(int active);

}