/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SmartActivePremi service. Represents a row in the &quot;SmartActivePremi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.SmartActivePremiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.SmartActivePremiImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see SmartActivePremi
 * @generated
 */
@ProviderType
public interface SmartActivePremiModel
	extends BaseModel<SmartActivePremi>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a smart active premi model instance should use the {@link SmartActivePremi} interface instead.
	 */

	/**
	 * Returns the primary key of this smart active premi.
	 *
	 * @return the primary key of this smart active premi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this smart active premi.
	 *
	 * @param primaryKey the primary key of this smart active premi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the smart active premi ID of this smart active premi.
	 *
	 * @return the smart active premi ID of this smart active premi
	 */
	public long getSmartActivePremiId();

	/**
	 * Sets the smart active premi ID of this smart active premi.
	 *
	 * @param smartActivePremiId the smart active premi ID of this smart active premi
	 */
	public void setSmartActivePremiId(long smartActivePremiId);

	/**
	 * Returns the rate of this smart active premi.
	 *
	 * @return the rate of this smart active premi
	 */
	public double getRate();

	/**
	 * Sets the rate of this smart active premi.
	 *
	 * @param rate the rate of this smart active premi
	 */
	public void setRate(double rate);

	/**
	 * Returns the active of this smart active premi.
	 *
	 * @return the active of this smart active premi
	 */
	public int getActive();

	/**
	 * Sets the active of this smart active premi.
	 *
	 * @param active the active of this smart active premi
	 */
	public void setActive(int active);

	/**
	 * Returns the smart active class rate ID of this smart active premi.
	 *
	 * @return the smart active class rate ID of this smart active premi
	 */
	public long getSmartActiveClassRateId();

	/**
	 * Sets the smart active class rate ID of this smart active premi.
	 *
	 * @param smartActiveClassRateId the smart active class rate ID of this smart active premi
	 */
	public void setSmartActiveClassRateId(long smartActiveClassRateId);

	/**
	 * Returns the smart active benefit ID of this smart active premi.
	 *
	 * @return the smart active benefit ID of this smart active premi
	 */
	public long getSmartActiveBenefitId();

	/**
	 * Sets the smart active benefit ID of this smart active premi.
	 *
	 * @param smartActiveBenefitId the smart active benefit ID of this smart active premi
	 */
	public void setSmartActiveBenefitId(long smartActiveBenefitId);

	/**
	 * Returns the group ID of this smart active premi.
	 *
	 * @return the group ID of this smart active premi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this smart active premi.
	 *
	 * @param groupId the group ID of this smart active premi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this smart active premi.
	 *
	 * @return the company ID of this smart active premi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this smart active premi.
	 *
	 * @param companyId the company ID of this smart active premi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this smart active premi.
	 *
	 * @return the user ID of this smart active premi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this smart active premi.
	 *
	 * @param userId the user ID of this smart active premi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this smart active premi.
	 *
	 * @return the user uuid of this smart active premi
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this smart active premi.
	 *
	 * @param userUuid the user uuid of this smart active premi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this smart active premi.
	 *
	 * @return the user name of this smart active premi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this smart active premi.
	 *
	 * @param userName the user name of this smart active premi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this smart active premi.
	 *
	 * @return the create date of this smart active premi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this smart active premi.
	 *
	 * @param createDate the create date of this smart active premi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this smart active premi.
	 *
	 * @return the modified date of this smart active premi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this smart active premi.
	 *
	 * @param modifiedDate the modified date of this smart active premi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}