/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SmartActiveTopro service. Represents a row in the &quot;SmartActiveTopro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.SmartActiveToproModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.SmartActiveToproImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see SmartActiveTopro
 * @generated
 */
@ProviderType
public interface SmartActiveToproModel
	extends BaseModel<SmartActiveTopro>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a smart active topro model instance should use the {@link SmartActiveTopro} interface instead.
	 */

	/**
	 * Returns the primary key of this smart active topro.
	 *
	 * @return the primary key of this smart active topro
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this smart active topro.
	 *
	 * @param primaryKey the primary key of this smart active topro
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the smart active topro ID of this smart active topro.
	 *
	 * @return the smart active topro ID of this smart active topro
	 */
	public long getSmartActiveToproId();

	/**
	 * Sets the smart active topro ID of this smart active topro.
	 *
	 * @param smartActiveToproId the smart active topro ID of this smart active topro
	 */
	public void setSmartActiveToproId(long smartActiveToproId);

	/**
	 * Returns the topro of this smart active topro.
	 *
	 * @return the topro of this smart active topro
	 */
	@AutoEscape
	public String getTopro();

	/**
	 * Sets the topro of this smart active topro.
	 *
	 * @param topro the topro of this smart active topro
	 */
	public void setTopro(String topro);

	/**
	 * Returns the description of this smart active topro.
	 *
	 * @return the description of this smart active topro
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this smart active topro.
	 *
	 * @param description the description of this smart active topro
	 */
	public void setDescription(String description);

	/**
	 * Returns the annotations of this smart active topro.
	 *
	 * @return the annotations of this smart active topro
	 */
	@AutoEscape
	public String getAnnotations();

	/**
	 * Sets the annotations of this smart active topro.
	 *
	 * @param annotations the annotations of this smart active topro
	 */
	public void setAnnotations(String annotations);

	/**
	 * Returns the smart active benefit value ID of this smart active topro.
	 *
	 * @return the smart active benefit value ID of this smart active topro
	 */
	public long getSmartActiveBenefitValueId();

	/**
	 * Sets the smart active benefit value ID of this smart active topro.
	 *
	 * @param smartActiveBenefitValueId the smart active benefit value ID of this smart active topro
	 */
	public void setSmartActiveBenefitValueId(long smartActiveBenefitValueId);

	/**
	 * Returns the toc of this smart active topro.
	 *
	 * @return the toc of this smart active topro
	 */
	@AutoEscape
	public String getToc();

	/**
	 * Sets the toc of this smart active topro.
	 *
	 * @param toc the toc of this smart active topro
	 */
	public void setToc(String toc);

	/**
	 * Returns the active of this smart active topro.
	 *
	 * @return the active of this smart active topro
	 */
	public int getActive();

	/**
	 * Sets the active of this smart active topro.
	 *
	 * @param active the active of this smart active topro
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this smart active topro.
	 *
	 * @return the group ID of this smart active topro
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this smart active topro.
	 *
	 * @param groupId the group ID of this smart active topro
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this smart active topro.
	 *
	 * @return the company ID of this smart active topro
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this smart active topro.
	 *
	 * @param companyId the company ID of this smart active topro
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this smart active topro.
	 *
	 * @return the user ID of this smart active topro
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this smart active topro.
	 *
	 * @param userId the user ID of this smart active topro
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this smart active topro.
	 *
	 * @return the user uuid of this smart active topro
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this smart active topro.
	 *
	 * @param userUuid the user uuid of this smart active topro
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this smart active topro.
	 *
	 * @return the user name of this smart active topro
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this smart active topro.
	 *
	 * @param userName the user name of this smart active topro
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this smart active topro.
	 *
	 * @return the create date of this smart active topro
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this smart active topro.
	 *
	 * @param createDate the create date of this smart active topro
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this smart active topro.
	 *
	 * @return the modified date of this smart active topro
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this smart active topro.
	 *
	 * @param modifiedDate the modified date of this smart active topro
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}