/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SmartTravelIntPlan service. Represents a row in the &quot;SmartTravelIntPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.SmartTravelIntPlanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.SmartTravelIntPlanImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see SmartTravelIntPlan
 * @generated
 */
@ProviderType
public interface SmartTravelIntPlanModel
	extends BaseModel<SmartTravelIntPlan>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a smart travel int plan model instance should use the {@link SmartTravelIntPlan} interface instead.
	 */

	/**
	 * Returns the primary key of this smart travel int plan.
	 *
	 * @return the primary key of this smart travel int plan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this smart travel int plan.
	 *
	 * @param primaryKey the primary key of this smart travel int plan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the smart travel int plan ID of this smart travel int plan.
	 *
	 * @return the smart travel int plan ID of this smart travel int plan
	 */
	public long getSmartTravelIntPlanId();

	/**
	 * Sets the smart travel int plan ID of this smart travel int plan.
	 *
	 * @param smartTravelIntPlanId the smart travel int plan ID of this smart travel int plan
	 */
	public void setSmartTravelIntPlanId(long smartTravelIntPlanId);

	/**
	 * Returns the name ID of this smart travel int plan.
	 *
	 * @return the name ID of this smart travel int plan
	 */
	@AutoEscape
	public String getNameId();

	/**
	 * Sets the name ID of this smart travel int plan.
	 *
	 * @param nameId the name ID of this smart travel int plan
	 */
	public void setNameId(String nameId);

	/**
	 * Returns the name en of this smart travel int plan.
	 *
	 * @return the name en of this smart travel int plan
	 */
	@AutoEscape
	public String getNameEn();

	/**
	 * Sets the name en of this smart travel int plan.
	 *
	 * @param nameEn the name en of this smart travel int plan
	 */
	public void setNameEn(String nameEn);

	/**
	 * Returns the sort of this smart travel int plan.
	 *
	 * @return the sort of this smart travel int plan
	 */
	public int getSort();

	/**
	 * Sets the sort of this smart travel int plan.
	 *
	 * @param sort the sort of this smart travel int plan
	 */
	public void setSort(int sort);

	/**
	 * Returns the active of this smart travel int plan.
	 *
	 * @return the active of this smart travel int plan
	 */
	public int getActive();

	/**
	 * Sets the active of this smart travel int plan.
	 *
	 * @param active the active of this smart travel int plan
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this smart travel int plan.
	 *
	 * @return the group ID of this smart travel int plan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this smart travel int plan.
	 *
	 * @param groupId the group ID of this smart travel int plan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this smart travel int plan.
	 *
	 * @return the company ID of this smart travel int plan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this smart travel int plan.
	 *
	 * @param companyId the company ID of this smart travel int plan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this smart travel int plan.
	 *
	 * @return the user ID of this smart travel int plan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this smart travel int plan.
	 *
	 * @param userId the user ID of this smart travel int plan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this smart travel int plan.
	 *
	 * @return the user uuid of this smart travel int plan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this smart travel int plan.
	 *
	 * @param userUuid the user uuid of this smart travel int plan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this smart travel int plan.
	 *
	 * @return the user name of this smart travel int plan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this smart travel int plan.
	 *
	 * @param userName the user name of this smart travel int plan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this smart travel int plan.
	 *
	 * @return the create date of this smart travel int plan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this smart travel int plan.
	 *
	 * @param createDate the create date of this smart travel int plan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this smart travel int plan.
	 *
	 * @return the modified date of this smart travel int plan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this smart travel int plan.
	 *
	 * @param modifiedDate the modified date of this smart travel int plan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}