/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SmartHealthPremi service. Represents a row in the &quot;SmartHealthPremi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.SmartHealthPremiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.SmartHealthPremiImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see SmartHealthPremi
 * @generated
 */
@ProviderType
public interface SmartHealthPremiModel
	extends BaseModel<SmartHealthPremi>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a smart health premi model instance should use the {@link SmartHealthPremi} interface instead.
	 */

	/**
	 * Returns the primary key of this smart health premi.
	 *
	 * @return the primary key of this smart health premi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this smart health premi.
	 *
	 * @param primaryKey the primary key of this smart health premi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the smart health premi ID of this smart health premi.
	 *
	 * @return the smart health premi ID of this smart health premi
	 */
	public long getSmartHealthPremiId();

	/**
	 * Sets the smart health premi ID of this smart health premi.
	 *
	 * @param smartHealthPremiId the smart health premi ID of this smart health premi
	 */
	public void setSmartHealthPremiId(long smartHealthPremiId);

	/**
	 * Returns the group ID of this smart health premi.
	 *
	 * @return the group ID of this smart health premi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this smart health premi.
	 *
	 * @param groupId the group ID of this smart health premi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this smart health premi.
	 *
	 * @return the company ID of this smart health premi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this smart health premi.
	 *
	 * @param companyId the company ID of this smart health premi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this smart health premi.
	 *
	 * @return the user ID of this smart health premi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this smart health premi.
	 *
	 * @param userId the user ID of this smart health premi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this smart health premi.
	 *
	 * @return the user uuid of this smart health premi
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this smart health premi.
	 *
	 * @param userUuid the user uuid of this smart health premi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this smart health premi.
	 *
	 * @return the user name of this smart health premi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this smart health premi.
	 *
	 * @param userName the user name of this smart health premi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this smart health premi.
	 *
	 * @return the create date of this smart health premi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this smart health premi.
	 *
	 * @param createDate the create date of this smart health premi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this smart health premi.
	 *
	 * @return the modified date of this smart health premi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this smart health premi.
	 *
	 * @param modifiedDate the modified date of this smart health premi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the age of this smart health premi.
	 *
	 * @return the age of this smart health premi
	 */
	public int getAge();

	/**
	 * Sets the age of this smart health premi.
	 *
	 * @param age the age of this smart health premi
	 */
	public void setAge(int age);

	/**
	 * Returns the gender of this smart health premi.
	 *
	 * @return the gender of this smart health premi
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this smart health premi.
	 *
	 * @param gender the gender of this smart health premi
	 */
	public void setGender(String gender);

	/**
	 * Returns the currency of this smart health premi.
	 *
	 * @return the currency of this smart health premi
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this smart health premi.
	 *
	 * @param currency the currency of this smart health premi
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the amount of this smart health premi.
	 *
	 * @return the amount of this smart health premi
	 */
	public double getAmount();

	/**
	 * Sets the amount of this smart health premi.
	 *
	 * @param amount the amount of this smart health premi
	 */
	public void setAmount(double amount);

	/**
	 * Returns the plan ID of this smart health premi.
	 *
	 * @return the plan ID of this smart health premi
	 */
	public long getPlanId();

	/**
	 * Sets the plan ID of this smart health premi.
	 *
	 * @param planId the plan ID of this smart health premi
	 */
	public void setPlanId(long planId);

	/**
	 * Returns the status of this smart health premi.
	 *
	 * @return the status of this smart health premi
	 */
	public int getStatus();

	/**
	 * Sets the status of this smart health premi.
	 *
	 * @param status the status of this smart health premi
	 */
	public void setStatus(int status);

}