/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SmartTravelIntLink service. Represents a row in the &quot;SmartTravelIntLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.SmartTravelIntLinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.SmartTravelIntLinkImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see SmartTravelIntLink
 * @generated
 */
@ProviderType
public interface SmartTravelIntLinkModel
	extends BaseModel<SmartTravelIntLink>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a smart travel int link model instance should use the {@link SmartTravelIntLink} interface instead.
	 */

	/**
	 * Returns the primary key of this smart travel int link.
	 *
	 * @return the primary key of this smart travel int link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this smart travel int link.
	 *
	 * @param primaryKey the primary key of this smart travel int link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the smart travel int link ID of this smart travel int link.
	 *
	 * @return the smart travel int link ID of this smart travel int link
	 */
	public long getSmartTravelIntLinkId();

	/**
	 * Sets the smart travel int link ID of this smart travel int link.
	 *
	 * @param smartTravelIntLinkId the smart travel int link ID of this smart travel int link
	 */
	public void setSmartTravelIntLinkId(long smartTravelIntLinkId);

	/**
	 * Returns the link type of this smart travel int link.
	 *
	 * @return the link type of this smart travel int link
	 */
	@AutoEscape
	public String getLinkType();

	/**
	 * Sets the link type of this smart travel int link.
	 *
	 * @param linkType the link type of this smart travel int link
	 */
	public void setLinkType(String linkType);

	/**
	 * Returns the link title of this smart travel int link.
	 *
	 * @return the link title of this smart travel int link
	 */
	@AutoEscape
	public String getLinkTitle();

	/**
	 * Sets the link title of this smart travel int link.
	 *
	 * @param linkTitle the link title of this smart travel int link
	 */
	public void setLinkTitle(String linkTitle);

	/**
	 * Returns the link href of this smart travel int link.
	 *
	 * @return the link href of this smart travel int link
	 */
	@AutoEscape
	public String getLinkHref();

	/**
	 * Sets the link href of this smart travel int link.
	 *
	 * @param linkHref the link href of this smart travel int link
	 */
	public void setLinkHref(String linkHref);

	/**
	 * Returns the group ID of this smart travel int link.
	 *
	 * @return the group ID of this smart travel int link
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this smart travel int link.
	 *
	 * @param groupId the group ID of this smart travel int link
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this smart travel int link.
	 *
	 * @return the company ID of this smart travel int link
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this smart travel int link.
	 *
	 * @param companyId the company ID of this smart travel int link
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this smart travel int link.
	 *
	 * @return the user ID of this smart travel int link
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this smart travel int link.
	 *
	 * @param userId the user ID of this smart travel int link
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this smart travel int link.
	 *
	 * @return the user uuid of this smart travel int link
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this smart travel int link.
	 *
	 * @param userUuid the user uuid of this smart travel int link
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this smart travel int link.
	 *
	 * @return the user name of this smart travel int link
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this smart travel int link.
	 *
	 * @param userName the user name of this smart travel int link
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this smart travel int link.
	 *
	 * @return the create date of this smart travel int link
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this smart travel int link.
	 *
	 * @param createDate the create date of this smart travel int link
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this smart travel int link.
	 *
	 * @return the modified date of this smart travel int link
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this smart travel int link.
	 *
	 * @param modifiedDate the modified date of this smart travel int link
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}