/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StiBenefit service. Represents a row in the &quot;StiBenefit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.StiBenefitModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.StiBenefitImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see StiBenefit
 * @generated
 */
@ProviderType
public interface StiBenefitModel
	extends BaseModel<StiBenefit>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sti benefit model instance should use the {@link StiBenefit} interface instead.
	 */

	/**
	 * Returns the primary key of this sti benefit.
	 *
	 * @return the primary key of this sti benefit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sti benefit.
	 *
	 * @param primaryKey the primary key of this sti benefit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the benefit ID of this sti benefit.
	 *
	 * @return the benefit ID of this sti benefit
	 */
	public long getBenefitId();

	/**
	 * Sets the benefit ID of this sti benefit.
	 *
	 * @param benefitId the benefit ID of this sti benefit
	 */
	public void setBenefitId(long benefitId);

	/**
	 * Returns the name ID of this sti benefit.
	 *
	 * @return the name ID of this sti benefit
	 */
	@AutoEscape
	public String getNameId();

	/**
	 * Sets the name ID of this sti benefit.
	 *
	 * @param nameId the name ID of this sti benefit
	 */
	public void setNameId(String nameId);

	/**
	 * Returns the name en of this sti benefit.
	 *
	 * @return the name en of this sti benefit
	 */
	@AutoEscape
	public String getNameEn();

	/**
	 * Sets the name en of this sti benefit.
	 *
	 * @param nameEn the name en of this sti benefit
	 */
	public void setNameEn(String nameEn);

	/**
	 * Returns the sort of this sti benefit.
	 *
	 * @return the sort of this sti benefit
	 */
	public int getSort();

	/**
	 * Sets the sort of this sti benefit.
	 *
	 * @param sort the sort of this sti benefit
	 */
	public void setSort(int sort);

	/**
	 * Returns the benefit type ID of this sti benefit.
	 *
	 * @return the benefit type ID of this sti benefit
	 */
	public long getBenefitTypeId();

	/**
	 * Sets the benefit type ID of this sti benefit.
	 *
	 * @param benefitTypeId the benefit type ID of this sti benefit
	 */
	public void setBenefitTypeId(long benefitTypeId);

	/**
	 * Returns the active of this sti benefit.
	 *
	 * @return the active of this sti benefit
	 */
	public int getActive();

	/**
	 * Sets the active of this sti benefit.
	 *
	 * @param active the active of this sti benefit
	 */
	public void setActive(int active);

	/**
	 * Returns the plan name of this sti benefit.
	 *
	 * @return the plan name of this sti benefit
	 */
	@AutoEscape
	public String getPlanName();

	/**
	 * Sets the plan name of this sti benefit.
	 *
	 * @param planName the plan name of this sti benefit
	 */
	public void setPlanName(String planName);

	/**
	 * Returns the benefit value of this sti benefit.
	 *
	 * @return the benefit value of this sti benefit
	 */
	@AutoEscape
	public String getBenefitValue();

	/**
	 * Sets the benefit value of this sti benefit.
	 *
	 * @param benefitValue the benefit value of this sti benefit
	 */
	public void setBenefitValue(String benefitValue);

	/**
	 * Returns the external code of this sti benefit.
	 *
	 * @return the external code of this sti benefit
	 */
	@AutoEscape
	public String getExternalCode();

	/**
	 * Sets the external code of this sti benefit.
	 *
	 * @param externalCode the external code of this sti benefit
	 */
	public void setExternalCode(String externalCode);

	/**
	 * Returns the benefit description of this sti benefit.
	 *
	 * @return the benefit description of this sti benefit
	 */
	@AutoEscape
	public String getBenefitDescription();

	/**
	 * Sets the benefit description of this sti benefit.
	 *
	 * @param benefitDescription the benefit description of this sti benefit
	 */
	public void setBenefitDescription(String benefitDescription);

	/**
	 * Returns the group ID of this sti benefit.
	 *
	 * @return the group ID of this sti benefit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this sti benefit.
	 *
	 * @param groupId the group ID of this sti benefit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sti benefit.
	 *
	 * @return the company ID of this sti benefit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sti benefit.
	 *
	 * @param companyId the company ID of this sti benefit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this sti benefit.
	 *
	 * @return the user ID of this sti benefit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this sti benefit.
	 *
	 * @param userId the user ID of this sti benefit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sti benefit.
	 *
	 * @return the user uuid of this sti benefit
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sti benefit.
	 *
	 * @param userUuid the user uuid of this sti benefit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this sti benefit.
	 *
	 * @return the user name of this sti benefit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this sti benefit.
	 *
	 * @param userName the user name of this sti benefit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sti benefit.
	 *
	 * @return the create date of this sti benefit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sti benefit.
	 *
	 * @param createDate the create date of this sti benefit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sti benefit.
	 *
	 * @return the modified date of this sti benefit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sti benefit.
	 *
	 * @param modifiedDate the modified date of this sti benefit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}