/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TravelDomesticDuration service. Represents a row in the &quot;TravelDomesticDuration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.TravelDomesticDurationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.TravelDomesticDurationImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see TravelDomesticDuration
 * @generated
 */
@ProviderType
public interface TravelDomesticDurationModel
	extends BaseModel<TravelDomesticDuration>, GroupedModel, ShardedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a travel domestic duration model instance should use the {@link TravelDomesticDuration} interface instead.
	 */

	/**
	 * Returns the primary key of this travel domestic duration.
	 *
	 * @return the primary key of this travel domestic duration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this travel domestic duration.
	 *
	 * @param primaryKey the primary key of this travel domestic duration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the travel domestic duration ID of this travel domestic duration.
	 *
	 * @return the travel domestic duration ID of this travel domestic duration
	 */
	public long getTravelDomesticDurationId();

	/**
	 * Sets the travel domestic duration ID of this travel domestic duration.
	 *
	 * @param travelDomesticDurationId the travel domestic duration ID of this travel domestic duration
	 */
	public void setTravelDomesticDurationId(long travelDomesticDurationId);

	/**
	 * Returns the group ID of this travel domestic duration.
	 *
	 * @return the group ID of this travel domestic duration
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this travel domestic duration.
	 *
	 * @param groupId the group ID of this travel domestic duration
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this travel domestic duration.
	 *
	 * @return the company ID of this travel domestic duration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this travel domestic duration.
	 *
	 * @param companyId the company ID of this travel domestic duration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this travel domestic duration.
	 *
	 * @return the user ID of this travel domestic duration
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this travel domestic duration.
	 *
	 * @param userId the user ID of this travel domestic duration
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this travel domestic duration.
	 *
	 * @return the user uuid of this travel domestic duration
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this travel domestic duration.
	 *
	 * @param userUuid the user uuid of this travel domestic duration
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this travel domestic duration.
	 *
	 * @return the user name of this travel domestic duration
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this travel domestic duration.
	 *
	 * @param userName the user name of this travel domestic duration
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this travel domestic duration.
	 *
	 * @return the create date of this travel domestic duration
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this travel domestic duration.
	 *
	 * @param createDate the create date of this travel domestic duration
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this travel domestic duration.
	 *
	 * @return the modified date of this travel domestic duration
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this travel domestic duration.
	 *
	 * @param modifiedDate the modified date of this travel domestic duration
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this travel domestic duration.
	 *
	 * @return the code of this travel domestic duration
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this travel domestic duration.
	 *
	 * @param code the code of this travel domestic duration
	 */
	public void setCode(String code);

	/**
	 * Returns the day from of this travel domestic duration.
	 *
	 * @return the day from of this travel domestic duration
	 */
	public int getDayFrom();

	/**
	 * Sets the day from of this travel domestic duration.
	 *
	 * @param dayFrom the day from of this travel domestic duration
	 */
	public void setDayFrom(int dayFrom);

	/**
	 * Returns the day to of this travel domestic duration.
	 *
	 * @return the day to of this travel domestic duration
	 */
	public int getDayTo();

	/**
	 * Sets the day to of this travel domestic duration.
	 *
	 * @param dayTo the day to of this travel domestic duration
	 */
	public void setDayTo(int dayTo);

	/**
	 * Returns the label of this travel domestic duration.
	 *
	 * @return the label of this travel domestic duration
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this travel domestic duration.
	 *
	 * @param label the label of this travel domestic duration
	 */
	public void setLabel(String label);

	/**
	 * Returns the active of this travel domestic duration.
	 *
	 * @return the active of this travel domestic duration
	 */
	public int getActive();

	/**
	 * Sets the active of this travel domestic duration.
	 *
	 * @param active the active of this travel domestic duration
	 */
	public void setActive(int active);

	/**
	 * Returns the status of this travel domestic duration.
	 *
	 * @return the status of this travel domestic duration
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this travel domestic duration was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this travel domestic duration.
	 *
	 * @return the trash entry created when this travel domestic duration was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this travel domestic duration.
	 *
	 * @return the class primary key of the trash entry for this travel domestic duration
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this travel domestic duration.
	 *
	 * @return the trash handler for this travel domestic duration
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this travel domestic duration is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this travel domestic duration is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this travel domestic duration is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this travel domestic duration is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}