/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TravelDomesticPlan service. Represents a row in the &quot;TravelDomesticPlan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.TravelDomesticPlanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.TravelDomesticPlanImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see TravelDomesticPlan
 * @generated
 */
@ProviderType
public interface TravelDomesticPlanModel
	extends BaseModel<TravelDomesticPlan>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a travel domestic plan model instance should use the {@link TravelDomesticPlan} interface instead.
	 */

	/**
	 * Returns the primary key of this travel domestic plan.
	 *
	 * @return the primary key of this travel domestic plan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this travel domestic plan.
	 *
	 * @param primaryKey the primary key of this travel domestic plan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the travel domestic plan ID of this travel domestic plan.
	 *
	 * @return the travel domestic plan ID of this travel domestic plan
	 */
	public long getTravelDomesticPlanId();

	/**
	 * Sets the travel domestic plan ID of this travel domestic plan.
	 *
	 * @param travelDomesticPlanId the travel domestic plan ID of this travel domestic plan
	 */
	public void setTravelDomesticPlanId(long travelDomesticPlanId);

	/**
	 * Returns the group ID of this travel domestic plan.
	 *
	 * @return the group ID of this travel domestic plan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this travel domestic plan.
	 *
	 * @param groupId the group ID of this travel domestic plan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this travel domestic plan.
	 *
	 * @return the company ID of this travel domestic plan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this travel domestic plan.
	 *
	 * @param companyId the company ID of this travel domestic plan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this travel domestic plan.
	 *
	 * @return the user ID of this travel domestic plan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this travel domestic plan.
	 *
	 * @param userId the user ID of this travel domestic plan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this travel domestic plan.
	 *
	 * @return the user uuid of this travel domestic plan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this travel domestic plan.
	 *
	 * @param userUuid the user uuid of this travel domestic plan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this travel domestic plan.
	 *
	 * @return the user name of this travel domestic plan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this travel domestic plan.
	 *
	 * @param userName the user name of this travel domestic plan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this travel domestic plan.
	 *
	 * @return the create date of this travel domestic plan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this travel domestic plan.
	 *
	 * @param createDate the create date of this travel domestic plan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this travel domestic plan.
	 *
	 * @return the modified date of this travel domestic plan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this travel domestic plan.
	 *
	 * @param modifiedDate the modified date of this travel domestic plan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this travel domestic plan.
	 *
	 * @return the name of this travel domestic plan
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this travel domestic plan.
	 *
	 * @param name the name of this travel domestic plan
	 */
	public void setName(String name);

	/**
	 * Returns the code of this travel domestic plan.
	 *
	 * @return the code of this travel domestic plan
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this travel domestic plan.
	 *
	 * @param code the code of this travel domestic plan
	 */
	public void setCode(String code);

	/**
	 * Returns the topro tsi of this travel domestic plan.
	 *
	 * @return the topro tsi of this travel domestic plan
	 */
	public int getToproTsi();

	/**
	 * Sets the topro tsi of this travel domestic plan.
	 *
	 * @param toproTsi the topro tsi of this travel domestic plan
	 */
	public void setToproTsi(int toproTsi);

	/**
	 * Returns the topro atsi of this travel domestic plan.
	 *
	 * @return the topro atsi of this travel domestic plan
	 */
	public int getToproAtsi();

	/**
	 * Sets the topro atsi of this travel domestic plan.
	 *
	 * @param toproAtsi the topro atsi of this travel domestic plan
	 */
	public void setToproAtsi(int toproAtsi);

	/**
	 * Returns the sort of this travel domestic plan.
	 *
	 * @return the sort of this travel domestic plan
	 */
	public int getSort();

	/**
	 * Sets the sort of this travel domestic plan.
	 *
	 * @param sort the sort of this travel domestic plan
	 */
	public void setSort(int sort);

	/**
	 * Returns the active of this travel domestic plan.
	 *
	 * @return the active of this travel domestic plan
	 */
	public int getActive();

	/**
	 * Sets the active of this travel domestic plan.
	 *
	 * @param active the active of this travel domestic plan
	 */
	public void setActive(int active);

}