/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.TrashedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TravelDomesticBenefit service. Represents a row in the &quot;TravelDomesticBenefit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.TravelDomesticBenefitModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.TravelDomesticBenefitImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see TravelDomesticBenefit
 * @generated
 */
@ProviderType
public interface TravelDomesticBenefitModel
	extends BaseModel<TravelDomesticBenefit>, GroupedModel, ShardedModel,
			TrashedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a travel domestic benefit model instance should use the {@link TravelDomesticBenefit} interface instead.
	 */

	/**
	 * Returns the primary key of this travel domestic benefit.
	 *
	 * @return the primary key of this travel domestic benefit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this travel domestic benefit.
	 *
	 * @param primaryKey the primary key of this travel domestic benefit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the travel domestic benefit ID of this travel domestic benefit.
	 *
	 * @return the travel domestic benefit ID of this travel domestic benefit
	 */
	public long getTravelDomesticBenefitId();

	/**
	 * Sets the travel domestic benefit ID of this travel domestic benefit.
	 *
	 * @param travelDomesticBenefitId the travel domestic benefit ID of this travel domestic benefit
	 */
	public void setTravelDomesticBenefitId(long travelDomesticBenefitId);

	/**
	 * Returns the group ID of this travel domestic benefit.
	 *
	 * @return the group ID of this travel domestic benefit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this travel domestic benefit.
	 *
	 * @param groupId the group ID of this travel domestic benefit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this travel domestic benefit.
	 *
	 * @return the company ID of this travel domestic benefit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this travel domestic benefit.
	 *
	 * @param companyId the company ID of this travel domestic benefit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this travel domestic benefit.
	 *
	 * @return the user ID of this travel domestic benefit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this travel domestic benefit.
	 *
	 * @param userId the user ID of this travel domestic benefit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this travel domestic benefit.
	 *
	 * @return the user uuid of this travel domestic benefit
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this travel domestic benefit.
	 *
	 * @param userUuid the user uuid of this travel domestic benefit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this travel domestic benefit.
	 *
	 * @return the user name of this travel domestic benefit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this travel domestic benefit.
	 *
	 * @param userName the user name of this travel domestic benefit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this travel domestic benefit.
	 *
	 * @return the create date of this travel domestic benefit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this travel domestic benefit.
	 *
	 * @param createDate the create date of this travel domestic benefit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this travel domestic benefit.
	 *
	 * @return the modified date of this travel domestic benefit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this travel domestic benefit.
	 *
	 * @param modifiedDate the modified date of this travel domestic benefit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the plan of this travel domestic benefit.
	 *
	 * @return the plan of this travel domestic benefit
	 */
	@AutoEscape
	public String getPlan();

	/**
	 * Sets the plan of this travel domestic benefit.
	 *
	 * @param plan the plan of this travel domestic benefit
	 */
	public void setPlan(String plan);

	/**
	 * Returns the amount of this travel domestic benefit.
	 *
	 * @return the amount of this travel domestic benefit
	 */
	@AutoEscape
	public String getAmount();

	/**
	 * Sets the amount of this travel domestic benefit.
	 *
	 * @param amount the amount of this travel domestic benefit
	 */
	public void setAmount(String amount);

	/**
	 * Returns the benefit of this travel domestic benefit.
	 *
	 * @return the benefit of this travel domestic benefit
	 */
	@AutoEscape
	public String getBenefit();

	/**
	 * Sets the benefit of this travel domestic benefit.
	 *
	 * @param benefit the benefit of this travel domestic benefit
	 */
	public void setBenefit(String benefit);

	/**
	 * Returns the benefit value of this travel domestic benefit.
	 *
	 * @return the benefit value of this travel domestic benefit
	 */
	public Long getBenefitValue();

	/**
	 * Sets the benefit value of this travel domestic benefit.
	 *
	 * @param benefitValue the benefit value of this travel domestic benefit
	 */
	public void setBenefitValue(Long benefitValue);

	/**
	 * Returns the group of this travel domestic benefit.
	 *
	 * @return the group of this travel domestic benefit
	 */
	@AutoEscape
	public String getGroup();

	/**
	 * Sets the group of this travel domestic benefit.
	 *
	 * @param group the group of this travel domestic benefit
	 */
	public void setGroup(String group);

	/**
	 * Returns the sort of this travel domestic benefit.
	 *
	 * @return the sort of this travel domestic benefit
	 */
	public int getSort();

	/**
	 * Sets the sort of this travel domestic benefit.
	 *
	 * @param sort the sort of this travel domestic benefit
	 */
	public void setSort(int sort);

	/**
	 * Returns the active of this travel domestic benefit.
	 *
	 * @return the active of this travel domestic benefit
	 */
	public int getActive();

	/**
	 * Sets the active of this travel domestic benefit.
	 *
	 * @param active the active of this travel domestic benefit
	 */
	public void setActive(int active);

	/**
	 * Returns the status of this travel domestic benefit.
	 *
	 * @return the status of this travel domestic benefit
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this travel domestic benefit was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this travel domestic benefit.
	 *
	 * @return the trash entry created when this travel domestic benefit was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this travel domestic benefit.
	 *
	 * @return the class primary key of the trash entry for this travel domestic benefit
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this travel domestic benefit.
	 *
	 * @return the trash handler for this travel domestic benefit
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this travel domestic benefit is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this travel domestic benefit is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this travel domestic benefit is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this travel domestic benefit is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

}