/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.admin.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TravelIntBenefit service. Represents a row in the &quot;TravelIntBenefit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mypage.admin.product.model.impl.TravelIntBenefitModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mypage.admin.product.model.impl.TravelIntBenefitImpl</code>.
 * </p>
 *
 * @author Gositus Team
 * @see TravelIntBenefit
 * @generated
 */
@ProviderType
public interface TravelIntBenefitModel
	extends BaseModel<TravelIntBenefit>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a travel int benefit model instance should use the {@link TravelIntBenefit} interface instead.
	 */

	/**
	 * Returns the primary key of this travel int benefit.
	 *
	 * @return the primary key of this travel int benefit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this travel int benefit.
	 *
	 * @param primaryKey the primary key of this travel int benefit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the travel int benefit ID of this travel int benefit.
	 *
	 * @return the travel int benefit ID of this travel int benefit
	 */
	public long getTravelIntBenefitId();

	/**
	 * Sets the travel int benefit ID of this travel int benefit.
	 *
	 * @param travelIntBenefitId the travel int benefit ID of this travel int benefit
	 */
	public void setTravelIntBenefitId(long travelIntBenefitId);

	/**
	 * Returns the benefit name of this travel int benefit.
	 *
	 * @return the benefit name of this travel int benefit
	 */
	@AutoEscape
	public String getBenefitName();

	/**
	 * Sets the benefit name of this travel int benefit.
	 *
	 * @param benefitName the benefit name of this travel int benefit
	 */
	public void setBenefitName(String benefitName);

	/**
	 * Returns the active of this travel int benefit.
	 *
	 * @return the active of this travel int benefit
	 */
	public int getActive();

	/**
	 * Sets the active of this travel int benefit.
	 *
	 * @param active the active of this travel int benefit
	 */
	public void setActive(int active);

	/**
	 * Returns the group ID of this travel int benefit.
	 *
	 * @return the group ID of this travel int benefit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this travel int benefit.
	 *
	 * @param groupId the group ID of this travel int benefit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this travel int benefit.
	 *
	 * @return the company ID of this travel int benefit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this travel int benefit.
	 *
	 * @param companyId the company ID of this travel int benefit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this travel int benefit.
	 *
	 * @return the user ID of this travel int benefit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this travel int benefit.
	 *
	 * @param userId the user ID of this travel int benefit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this travel int benefit.
	 *
	 * @return the user uuid of this travel int benefit
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this travel int benefit.
	 *
	 * @param userUuid the user uuid of this travel int benefit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this travel int benefit.
	 *
	 * @return the user name of this travel int benefit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this travel int benefit.
	 *
	 * @param userName the user name of this travel int benefit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this travel int benefit.
	 *
	 * @return the create date of this travel int benefit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this travel int benefit.
	 *
	 * @param createDate the create date of this travel int benefit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this travel int benefit.
	 *
	 * @return the modified date of this travel int benefit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this travel int benefit.
	 *
	 * @param modifiedDate the modified date of this travel int benefit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}