create table MSPPK_SppkDebitur (
	sppkDebiturId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	applicationNumber VARCHAR(75) null,
	fullName VARCHAR(75) null,
	birthPlace VARCHAR(75) null,
	birthDate DATE null,
	idNumber VARCHAR(75) null,
	address VARCHAR(75) null,
	occupation VARCHAR(75) null,
	email VARCHAR(75) null,
	phoneNumber VARCHAR(75) null,
	gender VARCHAR(75) null,
	sumInsured DECIMAL(30, 16) null,
	product VARCHAR(75) null,
	esppkToken VARCHAR(75) null,
	esppkTokenExpiry DATE null,
	esppkQ1 INTEGER,
	esppkQ2 INTEGER,
	esppkQ3 INTEGER,
	agreeRiplay INTEGER,
	agreeStatement INTEGER,
	needAssistance INTEGER,
	submitEsppkDate DATE null,
	submissionNumber VARCHAR(75) null
);

create table MSPPK_SppkUser (
	sppkUserId LONG not null primary key,
	sppkLoginCode VARCHAR(75) null,
	password_ VARCHAR(75) null,
	fullName VARCHAR(75) null,
	roleCode VARCHAR(75) null,
	email VARCHAR(75) null,
	allAccess INTEGER,
	accessData INTEGER,
	accessMonitoring INTEGER,
	active_ INTEGER,
	expireDate DATE null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	otpCode VARCHAR(75) null,
	otpExpired DATE null
);