/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.leads.model.DetailDrive;
import com.mypage.leads.service.DetailDriveLocalService;
import com.mypage.leads.service.DetailDriveLocalServiceUtil;
import com.mypage.leads.service.persistence.CustomerPersistence;
import com.mypage.leads.service.persistence.DetailDomesticTravelPersistence;
import com.mypage.leads.service.persistence.DetailDrivePersistence;
import com.mypage.leads.service.persistence.DetailHealthIndividuPersistence;
import com.mypage.leads.service.persistence.DetailInternationalTravelPersistence;
import com.mypage.leads.service.persistence.DetailPetPersistence;
import com.mypage.leads.service.persistence.DetailSmartactivePersistence;
import com.mypage.leads.service.persistence.DetailTlpPersistence;
import com.mypage.leads.service.persistence.LeadsPersistence;
import com.mypage.leads.service.persistence.PaymentPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the detail drive local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.leads.service.impl.DetailDriveLocalServiceImpl}.
 * </p>
 *
 * @author Gositus
 * @see com.mypage.leads.service.impl.DetailDriveLocalServiceImpl
 * @generated
 */
public abstract class DetailDriveLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DetailDriveLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DetailDriveLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DetailDriveLocalServiceUtil</code>.
	 */

	/**
	 * Adds the detail drive to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DetailDriveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param detailDrive the detail drive
	 * @return the detail drive that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DetailDrive addDetailDrive(DetailDrive detailDrive) {
		detailDrive.setNew(true);

		return detailDrivePersistence.update(detailDrive);
	}

	/**
	 * Creates a new detail drive with the primary key. Does not add the detail drive to the database.
	 *
	 * @param detailDriveId the primary key for the new detail drive
	 * @return the new detail drive
	 */
	@Override
	@Transactional(enabled = false)
	public DetailDrive createDetailDrive(long detailDriveId) {
		return detailDrivePersistence.create(detailDriveId);
	}

	/**
	 * Deletes the detail drive with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DetailDriveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param detailDriveId the primary key of the detail drive
	 * @return the detail drive that was removed
	 * @throws PortalException if a detail drive with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DetailDrive deleteDetailDrive(long detailDriveId)
		throws PortalException {

		return detailDrivePersistence.remove(detailDriveId);
	}

	/**
	 * Deletes the detail drive from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DetailDriveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param detailDrive the detail drive
	 * @return the detail drive that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DetailDrive deleteDetailDrive(DetailDrive detailDrive) {
		return detailDrivePersistence.remove(detailDrive);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DetailDrive.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return detailDrivePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.leads.model.impl.DetailDriveModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return detailDrivePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.leads.model.impl.DetailDriveModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return detailDrivePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return detailDrivePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return detailDrivePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DetailDrive fetchDetailDrive(long detailDriveId) {
		return detailDrivePersistence.fetchByPrimaryKey(detailDriveId);
	}

	/**
	 * Returns the detail drive with the primary key.
	 *
	 * @param detailDriveId the primary key of the detail drive
	 * @return the detail drive
	 * @throws PortalException if a detail drive with the primary key could not be found
	 */
	@Override
	public DetailDrive getDetailDrive(long detailDriveId)
		throws PortalException {

		return detailDrivePersistence.findByPrimaryKey(detailDriveId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(detailDriveLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DetailDrive.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("detailDriveId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			detailDriveLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DetailDrive.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"detailDriveId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(detailDriveLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DetailDrive.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("detailDriveId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return detailDrivePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return detailDriveLocalService.deleteDetailDrive(
			(DetailDrive)persistedModel);
	}

	public BasePersistence<DetailDrive> getBasePersistence() {
		return detailDrivePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return detailDrivePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the detail drives.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.mypage.leads.model.impl.DetailDriveModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of detail drives
	 * @param end the upper bound of the range of detail drives (not inclusive)
	 * @return the range of detail drives
	 */
	@Override
	public List<DetailDrive> getDetailDrives(int start, int end) {
		return detailDrivePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of detail drives.
	 *
	 * @return the number of detail drives
	 */
	@Override
	public int getDetailDrivesCount() {
		return detailDrivePersistence.countAll();
	}

	/**
	 * Updates the detail drive in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DetailDriveLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param detailDrive the detail drive
	 * @return the detail drive that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DetailDrive updateDetailDrive(DetailDrive detailDrive) {
		return detailDrivePersistence.update(detailDrive);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DetailDriveLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		detailDriveLocalService = (DetailDriveLocalService)aopProxy;

		_setLocalServiceUtilService(detailDriveLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DetailDriveLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DetailDrive.class;
	}

	protected String getModelClassName() {
		return DetailDrive.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = detailDrivePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DetailDriveLocalService detailDriveLocalService) {

		try {
			Field field = DetailDriveLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, detailDriveLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CustomerPersistence customerPersistence;

	@Reference
	protected DetailDomesticTravelPersistence detailDomesticTravelPersistence;

	protected DetailDriveLocalService detailDriveLocalService;

	@Reference
	protected DetailDrivePersistence detailDrivePersistence;

	@Reference
	protected DetailHealthIndividuPersistence detailHealthIndividuPersistence;

	@Reference
	protected DetailInternationalTravelPersistence
		detailInternationalTravelPersistence;

	@Reference
	protected DetailPetPersistence detailPetPersistence;

	@Reference
	protected DetailSmartactivePersistence detailSmartactivePersistence;

	@Reference
	protected DetailTlpPersistence detailTlpPersistence;

	@Reference
	protected LeadsPersistence leadsPersistence;

	@Reference
	protected PaymentPersistence paymentPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}