/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.leads.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import com.mypage.leads.model.DetailTlp;
import com.mypage.leads.service.DetailTlpService;
import com.mypage.leads.service.DetailTlpServiceUtil;
import com.mypage.leads.service.persistence.CustomerPersistence;
import com.mypage.leads.service.persistence.DetailDomesticTravelPersistence;
import com.mypage.leads.service.persistence.DetailDrivePersistence;
import com.mypage.leads.service.persistence.DetailHealthIndividuPersistence;
import com.mypage.leads.service.persistence.DetailInternationalTravelPersistence;
import com.mypage.leads.service.persistence.DetailPetPersistence;
import com.mypage.leads.service.persistence.DetailSmartactivePersistence;
import com.mypage.leads.service.persistence.DetailTlpPersistence;
import com.mypage.leads.service.persistence.LeadsPersistence;
import com.mypage.leads.service.persistence.PaymentPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the detail tlp remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mypage.leads.service.impl.DetailTlpServiceImpl}.
 * </p>
 *
 * @author Gositus
 * @see com.mypage.leads.service.impl.DetailTlpServiceImpl
 * @generated
 */
public abstract class DetailTlpServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, DetailTlpService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DetailTlpService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DetailTlpServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DetailTlpService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		detailTlpService = (DetailTlpService)aopProxy;

		_setServiceUtilService(detailTlpService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DetailTlpService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DetailTlp.class;
	}

	protected String getModelClassName() {
		return DetailTlp.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = detailTlpPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(DetailTlpService detailTlpService) {
		try {
			Field field = DetailTlpServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, detailTlpService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CustomerPersistence customerPersistence;

	@Reference
	protected DetailDomesticTravelPersistence detailDomesticTravelPersistence;

	@Reference
	protected DetailDrivePersistence detailDrivePersistence;

	@Reference
	protected DetailHealthIndividuPersistence detailHealthIndividuPersistence;

	@Reference
	protected DetailInternationalTravelPersistence
		detailInternationalTravelPersistence;

	@Reference
	protected DetailPetPersistence detailPetPersistence;

	@Reference
	protected DetailSmartactivePersistence detailSmartactivePersistence;

	@Reference
	protected com.mypage.leads.service.DetailTlpLocalService
		detailTlpLocalService;

	protected DetailTlpService detailTlpService;

	@Reference
	protected DetailTlpPersistence detailTlpPersistence;

	@Reference
	protected LeadsPersistence leadsPersistence;

	@Reference
	protected PaymentPersistence paymentPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}