/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mypage.agencyportal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.mypage.agencyportal.model.AgentSalesTools;
import com.mypage.agencyportal.model.AgentSalesToolsModel;
import com.mypage.agencyportal.model.AgentSalesToolsSoap;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AgentSalesTools service. Represents a row in the &quot;AP_AgentSalesTools&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AgentSalesToolsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AgentSalesToolsImpl}.
 * </p>
 *
 * @author Gositus Team
 * @see AgentSalesToolsImpl
 * @generated
 */
@JSON(strict = true)
public class AgentSalesToolsModelImpl
	extends BaseModelImpl<AgentSalesTools> implements AgentSalesToolsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a agent sales tools model instance should use the <code>AgentSalesTools</code> interface instead.
	 */
	public static final String TABLE_NAME = "AP_AgentSalesTools";

	public static final Object[][] TABLE_COLUMNS = {
		{"agentSalesToolsId", Types.BIGINT}, {"title", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"categoryId", Types.BIGINT},
		{"category", Types.VARCHAR}, {"fileUploadEntryId", Types.BIGINT},
		{"fileUploadUrl", Types.VARCHAR}, {"mypageUserRoleId", Types.BIGINT},
		{"role_", Types.VARCHAR}, {"active_", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("agentSalesToolsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("category", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileUploadEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileUploadUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mypageUserRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("role_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("active_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AP_AgentSalesTools (agentSalesToolsId LONG not null primary key,title VARCHAR(75) null,description VARCHAR(75) null,categoryId LONG,category VARCHAR(75) null,fileUploadEntryId LONG,fileUploadUrl VARCHAR(75) null,mypageUserRoleId LONG,role_ VARCHAR(75) null,active_ INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AP_AgentSalesTools";

	public static final String ORDER_BY_JPQL =
		" ORDER BY agentSalesTools.agentSalesToolsId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AP_AgentSalesTools.agentSalesToolsId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CATEGORY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MYPAGEUSERROLEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGENTSALESTOOLSID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static AgentSalesTools toModel(AgentSalesToolsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AgentSalesTools model = new AgentSalesToolsImpl();

		model.setAgentSalesToolsId(soapModel.getAgentSalesToolsId());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setCategoryId(soapModel.getCategoryId());
		model.setCategory(soapModel.getCategory());
		model.setFileUploadEntryId(soapModel.getFileUploadEntryId());
		model.setFileUploadUrl(soapModel.getFileUploadUrl());
		model.setMypageUserRoleId(soapModel.getMypageUserRoleId());
		model.setRole(soapModel.getRole());
		model.setActive(soapModel.getActive());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<AgentSalesTools> toModels(
		AgentSalesToolsSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<AgentSalesTools> models = new ArrayList<AgentSalesTools>(
			soapModels.length);

		for (AgentSalesToolsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AgentSalesToolsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _agentSalesToolsId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAgentSalesToolsId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _agentSalesToolsId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AgentSalesTools.class;
	}

	@Override
	public String getModelClassName() {
		return AgentSalesTools.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AgentSalesTools, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AgentSalesTools, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AgentSalesTools, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AgentSalesTools)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AgentSalesTools, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AgentSalesTools, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AgentSalesTools)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AgentSalesTools, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AgentSalesTools, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AgentSalesTools, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AgentSalesTools, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AgentSalesTools, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<AgentSalesTools, Object>>();
		Map<String, BiConsumer<AgentSalesTools, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AgentSalesTools, ?>>();

		attributeGetterFunctions.put(
			"agentSalesToolsId", AgentSalesTools::getAgentSalesToolsId);
		attributeSetterBiConsumers.put(
			"agentSalesToolsId",
			(BiConsumer<AgentSalesTools, Long>)
				AgentSalesTools::setAgentSalesToolsId);
		attributeGetterFunctions.put("title", AgentSalesTools::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<AgentSalesTools, String>)AgentSalesTools::setTitle);
		attributeGetterFunctions.put(
			"description", AgentSalesTools::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<AgentSalesTools, String>)
				AgentSalesTools::setDescription);
		attributeGetterFunctions.put(
			"categoryId", AgentSalesTools::getCategoryId);
		attributeSetterBiConsumers.put(
			"categoryId",
			(BiConsumer<AgentSalesTools, Long>)AgentSalesTools::setCategoryId);
		attributeGetterFunctions.put("category", AgentSalesTools::getCategory);
		attributeSetterBiConsumers.put(
			"category",
			(BiConsumer<AgentSalesTools, String>)AgentSalesTools::setCategory);
		attributeGetterFunctions.put(
			"fileUploadEntryId", AgentSalesTools::getFileUploadEntryId);
		attributeSetterBiConsumers.put(
			"fileUploadEntryId",
			(BiConsumer<AgentSalesTools, Long>)
				AgentSalesTools::setFileUploadEntryId);
		attributeGetterFunctions.put(
			"fileUploadUrl", AgentSalesTools::getFileUploadUrl);
		attributeSetterBiConsumers.put(
			"fileUploadUrl",
			(BiConsumer<AgentSalesTools, String>)
				AgentSalesTools::setFileUploadUrl);
		attributeGetterFunctions.put(
			"mypageUserRoleId", AgentSalesTools::getMypageUserRoleId);
		attributeSetterBiConsumers.put(
			"mypageUserRoleId",
			(BiConsumer<AgentSalesTools, Long>)
				AgentSalesTools::setMypageUserRoleId);
		attributeGetterFunctions.put("role", AgentSalesTools::getRole);
		attributeSetterBiConsumers.put(
			"role",
			(BiConsumer<AgentSalesTools, String>)AgentSalesTools::setRole);
		attributeGetterFunctions.put("active", AgentSalesTools::getActive);
		attributeSetterBiConsumers.put(
			"active",
			(BiConsumer<AgentSalesTools, Integer>)AgentSalesTools::setActive);
		attributeGetterFunctions.put("groupId", AgentSalesTools::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AgentSalesTools, Long>)AgentSalesTools::setGroupId);
		attributeGetterFunctions.put(
			"companyId", AgentSalesTools::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AgentSalesTools, Long>)AgentSalesTools::setCompanyId);
		attributeGetterFunctions.put("userId", AgentSalesTools::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<AgentSalesTools, Long>)AgentSalesTools::setUserId);
		attributeGetterFunctions.put("userName", AgentSalesTools::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<AgentSalesTools, String>)AgentSalesTools::setUserName);
		attributeGetterFunctions.put(
			"createDate", AgentSalesTools::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AgentSalesTools, Date>)AgentSalesTools::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AgentSalesTools::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AgentSalesTools, Date>)
				AgentSalesTools::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getAgentSalesToolsId() {
		return _agentSalesToolsId;
	}

	@Override
	public void setAgentSalesToolsId(long agentSalesToolsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_agentSalesToolsId = agentSalesToolsId;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoryId = categoryId;
	}

	@JSON
	@Override
	public String getCategory() {
		if (_category == null) {
			return "";
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_category = category;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCategory() {
		return getColumnOriginalValue("category");
	}

	@JSON
	@Override
	public long getFileUploadEntryId() {
		return _fileUploadEntryId;
	}

	@Override
	public void setFileUploadEntryId(long fileUploadEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileUploadEntryId = fileUploadEntryId;
	}

	@JSON
	@Override
	public String getFileUploadUrl() {
		if (_fileUploadUrl == null) {
			return "";
		}
		else {
			return _fileUploadUrl;
		}
	}

	@Override
	public void setFileUploadUrl(String fileUploadUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileUploadUrl = fileUploadUrl;
	}

	@JSON
	@Override
	public long getMypageUserRoleId() {
		return _mypageUserRoleId;
	}

	@Override
	public void setMypageUserRoleId(long mypageUserRoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mypageUserRoleId = mypageUserRoleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalMypageUserRoleId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("mypageUserRoleId"));
	}

	@JSON
	@Override
	public String getRole() {
		if (_role == null) {
			return "";
		}
		else {
			return _role;
		}
	}

	@Override
	public void setRole(String role) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_role = role;
	}

	@JSON
	@Override
	public int getActive() {
		return _active;
	}

	@Override
	public void setActive(int active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return 0;
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AgentSalesTools.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AgentSalesTools toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AgentSalesTools>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AgentSalesToolsImpl agentSalesToolsImpl = new AgentSalesToolsImpl();

		agentSalesToolsImpl.setAgentSalesToolsId(getAgentSalesToolsId());
		agentSalesToolsImpl.setTitle(getTitle());
		agentSalesToolsImpl.setDescription(getDescription());
		agentSalesToolsImpl.setCategoryId(getCategoryId());
		agentSalesToolsImpl.setCategory(getCategory());
		agentSalesToolsImpl.setFileUploadEntryId(getFileUploadEntryId());
		agentSalesToolsImpl.setFileUploadUrl(getFileUploadUrl());
		agentSalesToolsImpl.setMypageUserRoleId(getMypageUserRoleId());
		agentSalesToolsImpl.setRole(getRole());
		agentSalesToolsImpl.setActive(getActive());
		agentSalesToolsImpl.setGroupId(getGroupId());
		agentSalesToolsImpl.setCompanyId(getCompanyId());
		agentSalesToolsImpl.setUserId(getUserId());
		agentSalesToolsImpl.setUserName(getUserName());
		agentSalesToolsImpl.setCreateDate(getCreateDate());
		agentSalesToolsImpl.setModifiedDate(getModifiedDate());

		agentSalesToolsImpl.resetOriginalValues();

		return agentSalesToolsImpl;
	}

	@Override
	public int compareTo(AgentSalesTools agentSalesTools) {
		long primaryKey = agentSalesTools.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AgentSalesTools)) {
			return false;
		}

		AgentSalesTools agentSalesTools = (AgentSalesTools)object;

		long primaryKey = agentSalesTools.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AgentSalesTools> toCacheModel() {
		AgentSalesToolsCacheModel agentSalesToolsCacheModel =
			new AgentSalesToolsCacheModel();

		agentSalesToolsCacheModel.agentSalesToolsId = getAgentSalesToolsId();

		agentSalesToolsCacheModel.title = getTitle();

		String title = agentSalesToolsCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			agentSalesToolsCacheModel.title = null;
		}

		agentSalesToolsCacheModel.description = getDescription();

		String description = agentSalesToolsCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			agentSalesToolsCacheModel.description = null;
		}

		agentSalesToolsCacheModel.categoryId = getCategoryId();

		agentSalesToolsCacheModel.category = getCategory();

		String category = agentSalesToolsCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			agentSalesToolsCacheModel.category = null;
		}

		agentSalesToolsCacheModel.fileUploadEntryId = getFileUploadEntryId();

		agentSalesToolsCacheModel.fileUploadUrl = getFileUploadUrl();

		String fileUploadUrl = agentSalesToolsCacheModel.fileUploadUrl;

		if ((fileUploadUrl != null) && (fileUploadUrl.length() == 0)) {
			agentSalesToolsCacheModel.fileUploadUrl = null;
		}

		agentSalesToolsCacheModel.mypageUserRoleId = getMypageUserRoleId();

		agentSalesToolsCacheModel.role = getRole();

		String role = agentSalesToolsCacheModel.role;

		if ((role != null) && (role.length() == 0)) {
			agentSalesToolsCacheModel.role = null;
		}

		agentSalesToolsCacheModel.active = getActive();

		agentSalesToolsCacheModel.groupId = getGroupId();

		agentSalesToolsCacheModel.companyId = getCompanyId();

		agentSalesToolsCacheModel.userId = getUserId();

		agentSalesToolsCacheModel.userName = getUserName();

		String userName = agentSalesToolsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			agentSalesToolsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			agentSalesToolsCacheModel.createDate = createDate.getTime();
		}
		else {
			agentSalesToolsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			agentSalesToolsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			agentSalesToolsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return agentSalesToolsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AgentSalesTools, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AgentSalesTools, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AgentSalesTools, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AgentSalesTools)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AgentSalesTools, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AgentSalesTools, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AgentSalesTools, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AgentSalesTools)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AgentSalesTools>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AgentSalesTools.class, ModelWrapper.class);

	}

	private long _agentSalesToolsId;
	private String _title;
	private String _description;
	private long _categoryId;
	private String _category;
	private long _fileUploadEntryId;
	private String _fileUploadUrl;
	private long _mypageUserRoleId;
	private String _role;
	private int _active;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AgentSalesTools, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AgentSalesTools)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("agentSalesToolsId", _agentSalesToolsId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("categoryId", _categoryId);
		_columnOriginalValues.put("category", _category);
		_columnOriginalValues.put("fileUploadEntryId", _fileUploadEntryId);
		_columnOriginalValues.put("fileUploadUrl", _fileUploadUrl);
		_columnOriginalValues.put("mypageUserRoleId", _mypageUserRoleId);
		_columnOriginalValues.put("role_", _role);
		_columnOriginalValues.put("active_", _active);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("role_", "role");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("agentSalesToolsId", 1L);

		columnBitmasks.put("title", 2L);

		columnBitmasks.put("description", 4L);

		columnBitmasks.put("categoryId", 8L);

		columnBitmasks.put("category", 16L);

		columnBitmasks.put("fileUploadEntryId", 32L);

		columnBitmasks.put("fileUploadUrl", 64L);

		columnBitmasks.put("mypageUserRoleId", 128L);

		columnBitmasks.put("role_", 256L);

		columnBitmasks.put("active_", 512L);

		columnBitmasks.put("groupId", 1024L);

		columnBitmasks.put("companyId", 2048L);

		columnBitmasks.put("userId", 4096L);

		columnBitmasks.put("userName", 8192L);

		columnBitmasks.put("createDate", 16384L);

		columnBitmasks.put("modifiedDate", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AgentSalesTools _escapedModel;

}